### ISSUE TITLE
allow defining custom functions for actuated traffic lights with custom switching rules

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#10123]
```
<function id="FNAME" numArgs="2">
   <assignment id="COND1" check="1" value="$1 + $2"/>
   <assignment id="$0" check="1" value="COND1 * COND1"/>
</function>

<condition id="COND2" value="FNAME:3,4"/>
```

- may access any defined conditions
- return value of function is $0 (defaults to 0)
- $1 .. $n are set to the arguments of the functions

in the above example `COND2` receives a value of 49

**Comment by namdre** [comment]
@ambuehll Have you tried custom switching rules already? At the moment you can *kind of* emulate function calls with repeated assignments but it's not fun.

**Comment by ambuehll** [comment]
No, I haven't looked into it yet. I will in the future. Thanks for this!
