### ISSUE TITLE
connection closed by SUMO

### ISSUE THREAD

**Issue by emotion68** [eclipse-sumo/sumo#10184]
Add your issue description here.
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
![image](https://user-images.githubusercontent.com/82993708/154827060-16c7c292-a466-4496-9006-88619f711a4e.png)
![image](https://user-images.githubusercontent.com/82993708/154827065-adcb8a69-10ff-4b8a-a6fb-95ef0512d38c.png)
why？

**Comment by namdre** [comment]
Either sumo aborted with an error or it crashed. 
- add the arguments `, "--log", "log.txt"` to your `traci.start` command and report the contents of log.txt
- which version of sumo are you using?

**Comment by emotion68** [comment]
> 相扑因错误而中止或崩溃。
> 
> * 将参数添加`, "--log", "log.txt"`到您的`traci.start`命令并报告 log.txt 的内容
> * 你用的是哪个版本的相扑？



> Either sumo aborted with an error or it crashed.
> 
> * add the arguments `, "--log", "log.txt"` to your `traci.start` command and report the contents of log.txt
> * which version of sumo are you using?

![image](https://user-images.githubusercontent.com/82993708/155052523-d97d3229-0321-4c2e-ab3e-11263a70057e.png)
![image](https://user-images.githubusercontent.com/82993708/155052625-917af3cc-83e5-41cd-bc54-567a9675d023.png)


Why does it prompt no connection, is the node definition wrong?

**Comment by emotion68** [comment]
> 
The node type I set is zipper，why does this prompt still appear?
Node types：zipper

**Comment by namdre** [comment]
@emotion68 please post any answers or comments in this ticket rather than replying directly to a github notification.

**Comment by emotion68** [comment]
> @emotion68 please post any answers or comments in this ticket rather than replying directly to a github notification.

Is there a python tool for drawing 3D diagrams in SUMO?

**Comment by namdre** [comment]
No, for this you have to do your own post-processing of the outputs. This might help: https://sumo.dlr.de/docs/Tools/Xml.html#xml2csvpy
