### ISSUE TITLE
Open too many SUMO applications

### ISSUE THREAD

**Issue by ghost** [eclipse-sumo/sumo#10223]
Hellow guys!

I use the SUMO and Matlab with Traci4matlab API, I designed a situation where I want to loop the SUMO simulation using Matlab, like the code in Matlab below.
This method will lead to opening too many SUMO application windows. 
When the program iterate to a certain number, it will not be able to open SUMO application anymore.
I would like to ask if the same SUMO server is used because there are too many application windows?

Best regards!

------------------------------------------------------
for i= 1:Iteration
    import traci.constants;
    traci.start('sumo-gui -c ./test.sumocfg --start');
    traci.close;    
end
------------------------------------------------------

**Comment by namdre** [comment]
No, each call of 'start' should create a new instance that acts as a server.
I'd guess the operating system may prevent to many windows from being opened. I suggest that you run 'sumo' instead of 'sumo-gui' and check if that improves things.
