### ISSUE TITLE
non-deterministic behavior with option --device.rerouting.threads --weights.random-factor

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#10292]

**Comment by namdre** [comment]
fix only works on linux at the moment

**Comment by namdre** [comment]
another bad thing: even on linux where the non-determinism is fixed, the results now depends on the number of routing threads (not sure whether this is fixable at all)

**Comment by namdre** [comment]
A possible solution would be a pseudo-random mapping of (seed, edgeNumericalID, vehicleNumericalID, simStep) onto the range [0,1].
This might be accomplished by an appropriate hash function.
The resulting hash value would  be independent of thread-based race conditions and could replace the call to RandHelper::rand().

**Comment by ambuehll** [comment]
I know this is an older thread, but we do see quite the differences in different runs with identical random seeds.  I am bringing this up, given that I pinged #14720

**Comment by namdre** [comment]
what platform are you targeting? The code that would fix the problem for linux was disabled in 1622dc4

**Comment by namdre** [comment]
We'll try (but I cannot test it on mac myself).

**Comment by namdre** [comment]
try reverting the mentioned commit and tell me what error comes up (and if it compiles, see whether the random weights are stable)

**Comment by EduFalbel** [comment]
Hi all. I tried building on mac after reverting the commit and got the following error (seems to be the exact file modified by the commit):
 
```
/sumo/src/microsim/devices/MSRoutingEngine.cpp:432:26: error: no matching conversion for C-style cast from 'FXThreadID' (aka 'unsigned long') to 'std::thread::id' (aka 'std::__thread_id')
            myThreadRNGs[(std::thread::id)t->id()] = new SumoRNG("routing_" + toString(i++));
```
 
My specs: 
* M3 Max MacBook Pro running MacOS Sonoma 14.4
* Output of `clang --version`:
```
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
 
Build steps (followed https://sumo.dlr.de/docs/Installing/MacOS_Build.html):
 
```
brew install cmake
brew install --cask xquartz
brew install xerces-c fox proj gdal gl2ps python swig eigen pygobject3 gtk+3 adwaita-icon-theme
git clone --recursive https://github.com/eclipse-sumo/sumo
export SUMO_HOME="$PWD/sumo"
git revert 1622dc4 --no-commit
cd $SUMO_HOME
cmake -B build .
cd $SUMO_HOME
cmake --build build --parallel $(sysctl -n hw.ncpu)
```
 
I then attempted to build in an Ubuntu container following similar steps (but with apt) and had no issues

**Comment by ambuehll** [comment]
Amazing! 🥇 just tested it.
thank you very much!
