### ISSUE TITLE
Specific Vehicle Lane Change Issues

### ISSUE THREAD

**Issue by xielang404** [eclipse-sumo/sumo#10449]
Add your issue description here.
      How to ensure that a specific vehicle located on lane_0 will not change lanes to the lane next to lane_0, but keep executing, how can we use traci to achieve it (not all vehicles on lane_0 can not change lanes)?

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
use setLaneChangeMode on that vehicle: https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6

**Comment by xielang404** [comment]
For example: lane_0, lane_1, and lane_2 are three in the same direction and belong to one Edge. Lane_0, lane_1, and lane_2 belong to the right lane, middle lane, and left lane of the Edge, respectively. When a traffic accident occurs in the middle of lane_1 (there is a car parked in position at 200m of lane_1).
How to use sumo or traci to control the vehicle at 200m from lane_0 (right lane) to achieve straight driving, I found that sumo in this case, the default right lane can drive straight, but it still chooses to give priority to changing lanes to the middle lane ( traffic accident) @namdre

**Comment by namdre** [comment]
setting option **--lanechange.overtake-right**  should help
