### ISSUE TITLE
How to SUMO count the length of vehicle queues?

### ISSUE THREAD

**Issue by xielang404** [eclipse-sumo/sumo#10678]
Add your issue description here.

After a traffic accident, how does SUMO count the length of vehicle queues? For example, if there is a traffic accident at 200m from E1_0 in 10s, I want to count the queue length of vehicles at each time interval after 10s. Sorry to trouble you again.

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Simulation/Output/Lanearea_Detectors_%28E2%29.html
