### ISSUE TITLE
invalid result by couldChangeLane

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#10739]
~~returns True if a change (abs(direction) == 1) cannot be performed and the state is 'sublane'~~

**Comment by alexmajy** [comment]
problem: couldChangeLane seems incorrect
in the simulation of attache file 9.7s, the invoking of `couldChangeLane ` with turn-CAV.1 gets ture. However:
the returning of `getLaneChangeState` (not blocked) seems inconsistent with **lcState right** (blocked) showed in GUI (see the following). It seems that there is problem with `couldChangeLane `.

- version: sumo-1.21.0
- os: win10
- python 3.8



[could_change_lane_bug_sumo-1.21.0.zip](https://github.com/user-attachments/files/17677154/could_change_lane_bug_sumo-1.21.0.zip)

<img width="949" alt="incorrect_couldChangeLane" src="https://github.com/user-attachments/assets/f8cdfbba-e3ed-485e-89ff-deeffce01426">

**Comment by namdre** [comment]
@alexmajy Thanks for the report. I can confirm the bug

**Comment by namdre** [comment]
regression in version 1.13.0  via #10212

**Comment by namdre** [comment]
note: the gui dialog is not affected because it shows the state after incorporating the traci requests (which equals the non-buggy original state in this case).
