### ISSUE TITLE
How getJamLength command measure the jam length?

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse-sumo/sumo#10876]
Hi,
I intend to use getJamLength command in TraCI to measure the queue length at an intersection. I was wondering to know how the jam length is measured using this command. Should the speed of a vehicle be less than a limit to be considered in jam. The is also a parameter called jamThreshold. I was wondering how this parameter is used. Is one vehicle not considered as a jam if it is stopped but not close to any other vehicle with a distance less than jamThreshold. Should at least two vehicles be present to be considered a jam?

Best,
Reza.

**Comment by m-kro** [comment]
See the corresponding detector attributes jamThreshold, speedThreshold in the [docs](https://sumo.dlr.de/docs/Simulation/Output/Lanearea_Detectors_%28E2%29.html#attributes).

**Comment by behrisch** [comment]
Please leave another comment if the answer is not sufficient

**Comment by MohamadReza-Haghani** [comment]
Thank you for your response! I was wondering if speedThreshold is the limit using which it is decided if a vehicle is part of the queue or not. The default value for speedThreshold is 3.6. I have seen vehicles with lower speeds in my simulation which joined the queue but were not considered in queue length when I used getLastStepVehicleNumber until their speed became very close to 0.

**Comment by m-kro** [comment]
You can also set a time threshold after which vehicles are counted first (E2 detector attribute timeThreshold). It can be useful if you have a lot of vehicles advancing slowly e.g. upstream of a traffic signal, but when your goal is to capture only long lasting queues.

As the threshold has a default value of 1s, you may have used it implicitly without thinking about it. You could try to set timeThreshold="0" and run the simulation again.
