### ISSUE TITLE
retrieve road angle

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#10901]
- lane.getAngle(laneID, pos = -1)
 - edge.getAngle(edgeID, pos = -1)

If a negative position is given, the total angle (from start to end) is returned, otherwise the angle at the given position (the value should match the returned angle for a vehicle at that position)

**Comment by namdre** [comment]
The current work-around is to retrieve the lane shape and then compute the angle manually (i.e. with the help of sumolib.geomhelper)

**Comment by behrisch** [comment]
@bcoueraud87 for you!

**Comment by bcoueraud87** [comment]
@behrisch yes, please assign me

**Comment by behrisch** [comment]
I would rather add this to sumolib instead. I think if we start making static info like this available via traci people will (rightfully) expect other things like getLength etc. I do not want to follow that path @namdre Opinions?

**Comment by namdre** [comment]
Maybe getLength is a bad example because we already provide this for traci.lane. Obviously, we need to draw the line somewhere but I think we might just put getAngle on the traci side of the line (seeing how we don't even need a new message id).

There is also the point of how to support users that are not using python.

**Comment by behrisch** [comment]
But getLength is not there for the edge, so maybe it is actually a good example ;-) where we put in some kind of effort but did not have everything the user might expect. I agree on the part about the non-Python users though. So let's just add getAngle and discuss "the line" in the next developer meeting.

**Comment by behrisch** [comment]
@namdre Any objection against using INVALID_DOUBLE_VALUE instead of -1?

**Comment by namdre** [comment]
using INVALID_DOUBLE_VALUE in the output is preferred but it's cumbersome to use in the input whereas -1 is fine as an invalid offset. I guess we could support counting backwards from the lane end with negative values.

Go ahead an use INVALID_DOUBLE_VALUE

**Comment by namdre** [comment]
@bcoueraud87 can you extend the docs at
https://sumo.dlr.de/docs/TraCI/Lane_Value_Retrieval.html
https://sumo.dlr.de/docs/TraCI/Edge_Value_Retrieval.html
?
