### ISSUE TITLE
The problem of vehicle blocked.Change lanes to the accident lane instead of choosing to go straight through the accident-free lane

### ISSUE THREAD

**Issue by xielang404** [eclipse-sumo/sumo#10957]
Add your issue description here.

![9GY4SH}JW)N3XRKG1GTQ866](https://user-images.githubusercontent.com/60722429/174086222-aa95ce59-40a7-4286-aff6-818da4dc2760.png)
If a standard vehicle goes straight, there will be no blocked problem. I would like to ask why the car in the right lane chooses to change lanes by default to the already congested road in the middle. I think this car wants to change lanes to the left lane. In this case, you should keep going straight, how to avoid this kind of vehicle blocked problem

**SUMO-version:**

**operating system:**
![9GY4SH}JW)N3XRKG1GTQ866](https://user-images.githubusercontent.com/60722429/174086222-aa95ce59-40a7-4286-aff6-818da4dc2760.png)

**Comment by namdre** [comment]
If you haven't yet solved the problem yourself, can you provide a minimal example scenario to replicate the situation?

**Comment by m-kro** [comment]
Closing due to lack of feedback
