### ISSUE TITLE
bus stop locates on an unaccessible road

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse-sumo/sumo#11373]
Add your issue description here.
Bus stops/lines were generated by osmWebWizard.py with the option "Import public transport". But it happens that bus stop locates on a bicycle/pedestrian path, not accessible by bus. 

 *If possible, upload an example that shows your problem.*
The example network is attached. The information about the unaccessilbe bus stop and the bus line is listed below.

<busStop id="4834521456" name="Hellerhof S" lane="99391463#0_0" startPos="77.56" endPos="92.56" friendlyPos="true"/>

    <ptLine id="7360821" name="Bus SB57: Südpark =&gt; Turnerstraße, Langenfeld" line="SB57" type="bus" vClass="bus" completeness="0.33">
        <route edges="311029588#0 311029589#1 311029589#3 836501441 103422447 259769228#0 55473752#1 103422449#0 103422449#1 261093142#0 261093142#1 261093142#3 26448848 87724956#0 87724956#1 103182099 -55502833 -127077997#2 -127077997#1 -26448849#0 503658759#1 -377352109#1 -377352109#0 -860434550 -860434551 -376977005 -42646746#2 -123194201#2 -291507267#3 -291507267#2 -291507267#1 -291507267#0 -291507263 -123268861#2 -291507265#2 -291507265#1 -291507262 -376977015#1 -376977015#0 -376977007 -23386586#1 -23386586#0 -101532637#1 -101532637#0 -261093141 -92024717 -103182097#2 -103182097#0 -376977029#1 -376977029#0 -376977032#2 -376977032#0 -181301099#1 -181301099#0 -376950687"/>
        <busStop id="319259009" name="Dresdener Straße"/>
        <busStop id="5269071013" name="Hellerhof S"/>
        
        <busStop id="253033082" name="Eichsfelder Straße"/>
    </ptLine>

**SUMO-version:**
v1_14_1+0350-48d7f2812e8

**operating system:**
Windows

[osm_bbox.osm.xml.gz](https://github.com/eclipse/sumo/files/9357247/osm_bbox.osm.xml.gz)

**Comment by yunpangfloetteroed** [comment]
When opening the respective sumo network, the following warnings appear as well.
Warning: Unequal lengths of neigh lane ':1102443735_7_0' and lane ':1102443735_3_0' (1.60 != 0.55).
Warning: Unequal lengths of neigh lane ':2371780366_1_0' and lane ':2371780366_0_0' (0.12 != 0.14).
Warning: Unequal lengths of neigh lane ':cluster_1054581058_248532782_7_0' and lane ':cluster_1054581058_248532782_1_0' (13.06 != 12.37).
Warning: Unequal lengths of neigh lane ':cluster_1054581059_1054581100_252920529_19_0' and lane ':cluster_1054581059_1054581100_252920529_9_0' (20.21 != 20.40).
Warning: Unequal lengths of neigh lane ':cluster_1054581059_1054581100_252920529_20_0' and lane ':cluster_1054581059_1054581100_252920529_2_0' (20.86 != 20.44).
Warning: Unequal lengths of neigh lane ':cluster_1374660972_69194149_5_0' and lane ':cluster_1374660972_69194149_1_0' (9.96 != 10.48).
Warning: Unequal lengths of neigh lane '-95008583#1_0' and lane '-95008583#0_0' (24.34 != 24.92).
Warning: Unequal lengths of neigh lane '35050936_0' and lane '-35050936_0' (254.77 != 254.78).
Warning: Unequal lengths of neigh lane '775163660_0' and lane '-775163660_0' (96.00 != 96.01).

**Comment by namdre** [comment]
the busstop "Hellerhof S occured twice in the relation: once as 'stop' and once as 'platform' (the latter located on the bike path).
The current version of netconvert correctly imports the 'stop' on the road.
Presumably, the problem was fixed in another ticket.
