### ISSUE TITLE
bluelight device: unneeded change of vType when running without sublanes

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#11615]
the vTypes of vehicles around the bluelight equipped vehicle are temporarily replaced to modify their preferred lateral alignment. Since this takes no effect in a non-sublane simulation it can be dispensed with.

Pro: would avoid confusion as in #11597 
Con: would still lead to surprising effects with regard to vType ids when switching on the sublane model (at least the current behavior is consistent across models)

**Comment by behrisch** [comment]
maybe apply the filter to the "original" type

**Comment by namdre** [comment]
There are other parameters which get adapted (lcSpeedGainLookAhead and lcSpeedGainRemainTime) and which take effect in a non-sublane simulation.
