### ISSUE TITLE
Unexpected scenes during simulation

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse-sumo/sumo#11676]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
Hello,
 I have a freeway network with an off-ramp.First,I designed three lane  with 1.5 km and after a deceleration lane for off-ramp vehicles (totally four lane). I set the junction type as "zipper" to give right from middle lane of three-lane section through deceleration lane (right-most lane of four lane section). During the simulation, I save screens as below. Red vehicles are governed by Krauss, green vehicles are governed by IDM.I did not get emergency braking or collision warnings for those vehicles. Is this expected?Thank you for help,regards.
![scene1](https://user-images.githubusercontent.com/79362739/191816234-9ef24a0c-39d8-473d-b0ae-7f186c93e45b.PNG)
![scene2](https://user-images.githubusercontent.com/79362739/191816260-44677ec1-f25b-487b-a9d3-e5f03a9eec07.PNG)

**Comment by namdre** [comment]
- The intended use for a zipper junction is at a lane drop and it is expected that the zipper connection is not crossed by another straight connection.  Hence no checking is done for the conflict in your setup. 
- Collision warnings for intersections must be explicitly activated with option **--collision.check-junctions**
- If you want to make it easier to move from the middle lane to the acceleration lane, you can build a zipper junction ahead of the 4 lane section (in a 3-lane-to-3-lane section). This way the zipper connection is not being crossed.
