### ISSUE TITLE
priority among minor green streams

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#11737]
It should be possible to model the priority of a right turning stream (let's say from west to south) over a left turning stream (east to south) which have simultanoeusly green minor. The right turning stream has minor because it potentially has to wait for bicycles.

**Comment by behrisch** [comment]
It is visible in the cut_map of Ingolstadt, the scenario is about to be published. Maybe setting jmTimegapMinor for the vehicles helps. I'll keep this ticket open until I have rechecked with the scenario

**Comment by behrisch** [comment]
netconvert creates a mutual conflict which should eventually be resolved vusing multiple response matrices (cannot find the ticket reference). But even when adding **--tls.ignore-internal-junction-jam** the left turning stream gets priority, see the failing test

**Comment by namdre** [comment]
the ticket is #8626

**Comment by namdre** [comment]
related to 
- #1844
-  #7764
-  #6269 
-  #4187
- #5378
- #5379

Proposed implementation
- symmetrical response stays in the default response matrix
- whenever symmetrical response is present and both vehicles are approaching the link with minor priority an additional layer of conflict resolution is needed:
   - user provided ordering of tls link indices (`<phase ... prio="3,8"/>`) indices that are not in the list implicity get lower prio   
   - default ordering if nothing is provided (probably based on turning direction)

**Comment by namdre** [comment]
There is a new reason for needing a dynamic response matrix: If we want the off-state to work like an allway-stop (#12043) we need to have response equal to foes for the off duration (but this might still be handled as a special case)

**Comment by namdre** [comment]
There is an invalid edge priority in the test network from [dea22b3](https://github.com/eclipse-sumo/sumo/commit/dea22b3b4c809d3dbafeb0da81b44eeec366f889). Edge gneE12 should have priority 12 like the rest of *Hindenburgstraße". 
The invalid priority "-1" cause a default signal plan that doesn't group gneE12 with the opposite incoming 737320747#4.146. Then it doesn't get the expected internal junction position.

**Comment by namdre** [comment]
Also, the bicycle right turn from west to south is explicitly non-controlled whereas the east-south turn is controlled by the traffic light. The expected behavior is to have non-controlled connections always yield to controlled connections.
