### ISSUE TITLE
The gap becomes larger after the vehicle turns right when using simpla

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse-sumo/sumo#11811]
hello,sumo developer，my question is that when i using simpla to create platooning vehicle, the gap becomes larger after the vehicle turns right.Normally, the platoon vehicle spacing should be constant.
<img width="726" alt="gap become larger" src="https://user-images.githubusercontent.com/59630993/195226445-9589b388-db07-41ea-bead-d5886ce0e3b0.png">
<img width="832" alt="normal platoon" src="https://user-images.githubusercontent.com/59630993/195226450-a453f300-cb57-4a6f-8a64-ef36e6f5ce41.png">
[simpla_test221002.zip](https://github.com/eclipse/sumo/files/9760645/simpla_test221002.zip)

**Comment by m-kro** [comment]
The connection between the access lane and the main carriageway has a lower speed than the neighbour elements due to its angle. If you overwrite the speed limit e.g. in Netedit, neither the leader nor the followers brake and thus the inter-vehicle distance remains constant.

**Comment by zhaotuo0815** [comment]
> The connection between the access lane and the main carriageway has a lower speed limit than the neighbour elements due to its angle. If you overwrite the speed limit e.g. in Netedit, neither the leader nor the followers brake and thus the inter-vehicle distance remains constant.
but the speed limit are the same!

**Comment by m-kro** [comment]
No they aren't. Please check the [docs](https://sumo.dlr.de/docs/Simulation/Intersections.html#speed_while_passing_the_intersection). By default, speed limit is reduced within an intersection depending on the turning radius.
