### ISSUE TITLE
Issues on creating crossings

### ISSUE THREAD

**Issue by felixfroehling** [eclipse-sumo/sumo#11826]
Hey guys,
i want to add some crossings so pedestrians can take the route like the red arrows in the image. 
When I try to create a crosswalk (blue circles in the image below) I either get an error that there is no route or Sumo crashes.
I hope you guys can tell me if i made a mistake in netedit or if it is a bug.

The Net file is attached.
[ingolstadt.net.xml.zip](https://github.com/eclipse/sumo/files/9778206/ingolstadt.net.xml.zip)

Thank you for your help!

![Sumo_gui_edit](https://user-images.githubusercontent.com/63063096/195637128-f798828a-ccff-46ca-add1-858699d29458.PNG)
![fkk_netedit](https://user-images.githubusercontent.com/63063096/195637140-db6d8094-ef67-4965-b2be-ef3be656fc9a.PNG)

**Comment by m-kro** [comment]
Could you please explain a little more what you do to make the program (which: SUMO or Netedit?) crash? You supplied a network with pedestrian crossings, so which error message did you get before?

**Comment by felixfroehling** [comment]
Big Thanks to @behrisch for helping me out with this problem.
He will push the updated map to our projekt repository soon.
https://github.com/TUM-VT/sumo_ingolstadt

Thank you all guys!
