### ISSUE TITLE
update travelTime and cost of current stage

### ISSUE THREAD

**Issue by rummel123** [eclipse-sumo/sumo#11838]
`traci.person.getStage(person_id, 0).length` gives the current length of the already travelled way of the current stage.
`traci.person.getStage(person_id, 0).travelTime` and `traci.person.getStage(person_id, 0).cost` gives the default value `-1073741824.0`, due to the stage is not yet finished and will be calculated only when the stage is finished. It would be nice to update these values just as well the length to get the current travel time and current cost of the current stage.

**Comment by rummel123** [comment]
I need this extension for the drtOrtools.py. Can I help somehow? In which file is it calculated?

**Comment by namdre** [comment]
libsumo/Person.cpp in `getStage`.
the traveltime can be computed from the depart time (time of entering the vehicle)
cost is usually identical to traveltime (except when using a very special router but that isn't applied to taxi routing.

**Comment by rummel123** [comment]
I added the current travel time of the already traveled way of the current stage.
I don't how to add a test for that. I tested with my scenarios and it seems to work.

**Comment by rummel123** [comment]
I found and adapted a suitable test
