### ISSUE TITLE
Emergency Vehicle & Rescue Lane issues on freeway

### ISSUE THREAD

**Issue by heinovski** [eclipse-sumo/sumo#12067]
I am currently trying to simulate emergency vehicles in a simple freeway scenario (i.e., 4 lanes, traffic jam). I put some vehicles on the road to create a traffic jam and scheduled an emergency vehicle to pass through the jam. I am currently experiencing some unexpected behavior by the emergency vehicles as well as the other vehicles.

Current behavior:
- The other vehicles create a rescue lane correctly, but only at a reaction distance of >= 400m. If the reaction distance is <400m, the rescue lane is not (correctly) created.
- The emergency vehicle approaches the other vehicles on the rightmost lane and only moves to the correct sub-lane to pass the rescue lane when it is very close to the other vehicles. This wastes a lot of time and is not expected. When the reaction distance is <400m (e.g., 100m), the emergency vehicles is stuck between the other vehicles and cannot continue.
- Adding `lcKeepRight="0"` and `lcStrategic="1"` to the emergency vehicle type does not have any impact.
- The other vehicles do not close the rescue lane after the emergency vehicle has passed it.

Expected behavior:
- The other vehicles create the rescue lane correctly with a lower reaction distance (e.g., 100m).
- The emergency vehicle approaches the vehicles on the correct sub-lane such that it can immediately drive through the rescue lane. At least when adding `lcKeepRight="0"` and `lcStrategic="1"` to the vehicle type.
- Other vehicles close the rescue lane after the emergency vehicles has passed it.

I attached my simple scenario configuration: [freeway.zip](https://github.com/eclipse/sumo/files/10030132/freeway.zip)
The only changes to the default values I did is to make the emergency vehicle larger in width (2.5m) but to cope with that I also increase the lane width to 3.75m and used a lateral resolution of 0.5m (see [this](https://de.wikipedia.org/wiki/Rettungsgasse#Ausreichende_Breite_der_Fahrspur)). The issues also occurs with the default values.

**SUMO-version:** 1.15.0

**operating system:** Ubuntu 20.04 LTS

**Comment by namdre** [comment]
There are probably more things going on here but  #12108 is part of the problem.

**Comment by namdre** [comment]
Here is another one: #12109

**Comment by namdre** [comment]
> There are probably more things going on here but #12108 is part of the problem.

This one is fixed now
