### ISSUE TITLE
review person gap acceptance

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#12107]
the code at https://github.com/eclipse/sumo/blob/2af25c2cbe37c2f44adbe3d660ea0ade72805ee0/src/microsim/transportables/MSPModel_Striping.cpp#L1186-L1198

looks dubious: a faster person has a higher passingLength (corresponding to vehicleLength) and thus takes *longer* to pass the crossing?!

**Comment by behrisch** [comment]
The code is actually fine. The higher passingLength is just calculated to compensate for the faster person and keep the time constant.
