### ISSUE TITLE
invalid handling of stopOffset exceptions (stopOException)

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#12153]
sublane_model/junction/bicycle_box/lane_choice/net.net.xml

net has:
```
<edge id="gneE4c" from="gneJ7" to="gneJ1" priority="-1">
        <stopOffset vClasses="passenger" value="10.00"/>

```
- stopOException should list everything except passenger (but lists all classes)
- changing stopOException changes the permissions on the edge instead

Possibly a regression - please check. (I do think this was working before)

**Comment by palvarezlopez** [comment]
After a recent refactoring, this problem was fixed (6057551e482b4280c4955afabb1d0706054cbeba)
