### ISSUE TITLE
Save SUMO Config in SUMO-GUI doesn't save the header

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse-sumo/sumo#12212]

**Comment by palvarezlopez** [comment]
@behrisch Why don't use` device.writeXMLHeader(toString(SUMO_TAG_CONFIGURATION), "sumoConfiguration.xsd"... 
` in `GUIApplicationWindow::onCmdSaveConfig(FXObject*, FXSelector, void*) ?`

**Comment by behrisch** [comment]
maybe because there is no outputdevice yet but we could of course create one.

**Comment by namdre** [comment]
It's working now.  Presumably fixed in some other ticket.
