### ISSUE TITLE
add new vClasses

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#12335]
- aircraft
- cable car
- subway (to ease map matching)
- wheelchair
- ~~cargo bike~~
- container (#14353)
- (e) scooter
- small delivery robots in pedestrian zones?

**Comment by M-Colley** [comment]
This addition would really help my work and would be highly appreciated. Any chance that this will be added still in version 1.20.0?

Kind regards

**Comment by namdre** [comment]
which ones would you need in particular?

**Comment by M-Colley** [comment]
Thank you very much for your quick answer!

For me, the priority would be:

1. (e)scooter
2. aircraft
3. wheelchair

Kind regards

**Comment by JulianCzymmeck** [comment]
I'm personally very interested in official (e)scooter and aircraft support as well. Much appreciated!

**Comment by namdre** [comment]
I'll try to include this in 1.20 (which will be delayed anyway)

**Comment by M-Colley** [comment]
Hey @namdre, if possible, could you also add further micromobility classes - I think about **segways**, **electric unicycles,** and **one-wheeled skateboards**?

Kind regards

**Comment by M-Colley** [comment]
Thanks for the quick answer!

so micromobility in general (e-scooter unicycles etc) are driven both on roads and sidewalks. I think this is done less with bicycles. Regarding electric unicycles, I became aware that people do not take them off even in buildings, but that probably is not a relevant use case. So I think a general class micromobility device (that includes e-scotter, segway etc) is needed in addition to bicycles but that this will be sufficient (so no extra classes for segways, electric unicycles, and one-wheeled skateboards). Thanks!

**Comment by namdre** [comment]
sumo-gui is crashing

**Comment by namdre** [comment]
fixed with temporary icons (#14646)

**Comment by namdre** [comment]
Opening older networks should be "smart" regarding the new vClasses. (subway should be forbidden when rail_urban is forbidden, etc.)

**Comment by yuuhhhaooo** [comment]
Hey there, I can see that you were thinking about small delivery robots in pedestrian zones. In my work, I would be highly interested in simulating a range of robots. For example, this could be delivery robots but also humanoid robots. 

If this fits the plans for SUMO, I would be very happy for an official integration. 

@namdre 

Thank you for considering.

**Comment by namdre** [comment]
vehicle classes are mainly used to distinguish where entities can move. If a humanoid robot can go anywhere that a human can go, it would be perfectly fine to model them with vClass `pedestrian` and distinguish their behavior by other attributes of their type (i.e. speed, size, ...).
Likewise, wheeled robots might have a very similar mobility to vClass `wheelchair`. If you simulate access restrictions different to these two classes, you can use `drone`. If you need more you can also use `custom1` and `custom2`.
