### ISSUE TITLE
permit persons and container to use any kind of stopping place

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#12384]
this is tricky from a UI perspective:
- sumo permits containers and persons to stop at any kind of stopping place (see `tests/sumo/basic/person/riding/ride_stoppingPlace`)
- in most cases users willl want persons to stop at busStops and container to stop at containerStops
- netedit fails to load input files where transportables stop at non-standard stopping places

a compromise could be to permit ctrl+clicking on any kind of stopping place to let a person/container stop there and to load the corresponding files as valid input.

**Comment by namdre** [comment]
should be fixed together with #13268

**Comment by palvarezlopez** [comment]
Fixed during #15405 and tested.
