### ISSUE TITLE
reconsider default rainbow colors

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#12483]
- [red, ..., magenta] is bad.
- maybe even a reduced rainbow with more than two hues is bad: See also: https://blog.bioturing.com/2018/09/24/heatmap-color-scale/
  - add a dropdown for selecting between a few palette presets?
- adding a third value to set the "neutral" point for diverging palettes scale could be useful

**Comment by namdre** [comment]
a nice heatmap is included in #10186

**Comment by namdre** [comment]
see also https://betterfigures.org/2015/06/23/picking-a-colour-scale-for-scientific-graphics/

**Comment by namdre** [comment]
matplotlib scales: https://matplotlib.org/stable/tutorials/colors/colormaps.html

**Comment by rummel123** [comment]
I really like to have a better default color scale than the rainbow scale.

The [colorbrewer2](https://colorbrewer2.org/) has good color scales (also colorblind safe). They are listed [here].(https://github.com/axismaps/colorbrewer/blob/master/export/colorbrewer.json)
I prefer:

- 7-class **YlOrRd** as sequential scale: ["rgb(255,255,178)", "rgb(254,217,118)", "rgb(254,178,76)", "rgb(253,141,60)", "rgb(252,78,42)", "rgb(227,26,28)", "rgb(177,0,38)"]
- 7-class **RdBu** as diverging scale: ["rgb(178,24,43)", "rgb(239,138,98)", "rgb(253,219,199)", "rgb(247,247,247)", "rgb(209,229,240)", "rgb(103,169,207)", "rgb(33,102,172)"]
