### ISSUE TITLE
How can I use libtorch in microsim?

### ISSUE THREAD

**Issue by ckh0715** [eclipse-sumo/sumo#12599]
I only want to use pytorch model to predict vehicle trajectories. 
When I write some code about torch in MSLaneChanger.cpp, I always make failed. Only when I write code in sumo_main.cpp can success. I can use target_link_libraries at CMakeLists.txt under src to link torch libraries, and it's successful  to run torch code in sumo_main.cpp. But when I modify CMakeLists.txt under src/microsim, it's always unsatisfactory.

**Comment by behrisch** [comment]
Can you maybe publish the code changes somewhere for us to reproduce?

**Comment by behrisch** [comment]
It should not be necessary to disable unit tests. Probably you just need to link the torch libraries there a s well.
