### ISSUE TITLE
Vehicles fail to change lanes and merge out at the exit of the expressway in time

### ISSUE THREAD

**Issue by tangjingye** [eclipse-sumo/sumo#12758]
I am using sumo to do a simulation of expressway exit area. However, the vehicles in the middle lane and the innermost lane did not change lanes to the outermost lane in advance, and they did not change lanes until they reached the exit, resulting in congestion. How can I solve this problem? We look forward to your reply!
![image](https://user-images.githubusercontent.com/127025953/222960064-04990528-bfda-47cc-b93b-6ed3eba94864.png)

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/Motorways.html#combined_on-off-ramps

**Comment by tangjingye** [comment]
Thank you for your reply! I try to change the node to zipper and control the vehicle to force lane change according to the tutorial. However, vehicles did not change lanes compulsorily, and the congestion was still not relieved. The car-following model of my first type car is kruass model and the lane change model is SL2015. The car-following model of the second type car is CACC model and the lane change model is SL2015. The simulation scenario is an expressway exit with one-way three-lane traffic volume of 2800pcu/h. During the simulation, I turned on the blue model. We look forward to your reply!
![image](https://user-images.githubusercontent.com/127025953/223013619-5307e272-d076-4db1-83a1-bd68ef4504b0.png)
![image](https://user-images.githubusercontent.com/127025953/223013658-ff1d25a0-6873-47ff-8682-f64d911cef2c.png)
![image](https://user-images.githubusercontent.com/127025953/223013688-69cc844a-3780-4270-ba3b-6b98c7a5a4db.png)

**Comment by namdre** [comment]
It sounds as if you read the wrong section of the page that I linked. Setting node type to zipper is not the solution here (it wouldn't reflect the preference for the right lane when exiting and also has no effect unless you add an extra connection).

You should leave the node type at 'priority' and add a connection from the middle lane to the off-ramp (ctr+click in netedit to create a conflicting connection).

**Comment by tangjingye** [comment]
Thank you for your reply!

I try to change the node to 'priority', add the connection between the innermost lane and the middle lane to the ramp, and enlarge the area. I don't know whether this approach is correct, but from the results, the simulation has improved, but there is still congestion. What can I do to ensure that this will not happen

We look forward to your reply!
![image](https://user-images.githubusercontent.com/127025953/223070128-858e9991-451d-420f-b9cb-dc3cfbc9fa5a.png)
![image](https://user-images.githubusercontent.com/127025953/223070200-414a5685-1a82-4a9c-8a44-e3d239a09d1d.png)

**Comment by namdre** [comment]
enlarging the junction  is not a good choice since it reduces the space for "normal" lane changing.  
If congestion happens frequently, I suggest you investigate why the vehicles are forced into a weaving situation. Possibly the vehicles depart on implausible lanes upstream of the off-ramp.
Setting vehicle attribute `departLane="best"` will resolve problems based on insertion lane.

**Comment by tangjingye** [comment]
Hello!


I'm glad to receive your reply so soon! According to your method, the vehicle runs smoothly at the exit of the expressway without congestion. But I have a problem. I want to research the risk of vehicles and surrounding vehicles in the process of forced lane change in the exit area. When the departure lane of the vehicle is set to 'best', will the lane change behavior of the vehicle in the exit area be reduced, and will this have an impact on my research?


We look forward to your reply!





唐颢
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eclipse/sumo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月6日(星期一) 下午5:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eclipse/sumo] Vehicles fail to change lanes and merge out at the exit of the expressway in time (Issue #12758)





 
enlarging the junction  is not a good choice since it reduces the space for "normal" lane changing.
 If congestion happens frequently, I suggest you investigate why the vehicles are forced into a weaving situation. Possibly the vehicles depart on implausible lanes upstream of the off-ramp.
 Setting vehicle attribute departLane="best" will resolve problems based on insertion lane.

**Comment by namdre** [comment]
1. With departLane="best" vehicles will often not need to change lanes close to their insertion point (possibly never in your use case). This will definitely impact your reseach

2. In the real world, lane-changing behavior in time-critical situations can be anything on a continuum between the following two extremes:
  a) perform any dangerous lane change (by accepting short gaps)
  b) never perform dangerous lane change and stop instead

The default behavior of sumo is *b* (because SUMO is intended to be collision-free by default). To get behavior that is closer to *a* you can set a number of lane changing parameters: 
See https://sumo.dlr.de/docs/Simulation/Safety.html#lane-changing_model

Allowing dangerous lane changes can also easy the congestion you observed originally.

**Comment by tangjingye** [comment]
Hello!


Thank you for your previous reply. I tried to force the vehicle to change lanes before the main line of the expressway and change lanes to the outermost lane to enter the ramp. But the actual effect is not good. There are still vehicles that do not change lanes compulsorily, resulting in congestion. This is the code for my simulation. Could you help me find out what's wrong?






唐颢
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eclipse/sumo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月6日(星期一) 晚上6:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eclipse/sumo] Vehicles fail to change lanes and merge out at the exit of the expressway in time (Issue #12758)





  
 
With departLane="best" vehicles will often not need to change lanes close to their insertion point (possibly never in your use case). This will definitely impact your reseach
 
 
 
In the real world, lane-changing behavior in time-critical situations can be anything on a continuum between the following two extremes:
 a) perform any dangerous lane change (by accepting short gaps)
 b) never perform dangerous lane change and stop instead
 
  
The default behavior of sumo is b (because SUMO is intended to be collision-free by default). To get behavior that is closer to a you can set a number of lane changing parameters:
 See https://sumo.dlr.de/docs/Simulation/Safety.html#lane-changing_model
 
Allowing dangerous lane changes can also easy the congestion you observed originally.

**Comment by tangjingye** [comment]
![image](https://user-images.githubusercontent.com/127025953/223325538-14b553e1-1c70-4870-947f-bb24c92687c3.png)
![image](https://user-images.githubusercontent.com/127025953/223325582-487a7395-415c-4faa-bb7c-739a4d8408a9.png)

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6
also: https://sumo.dlr.de/docs/FAQ.html#i_want_to_do_a_project_with_sumo_can_you_help_me_with_the_implementation

**Comment by jiaery** [comment]
I am very fortunate to see your question, I also encountered the same problem, can you solve it? how to solve it, I look forward to your reply, thank you so much.

**Comment by lin-prob** [comment]
同学，您好，我在使用sumo仿真时也遇到了类似的问题，能否和您讨论一下，有偿
