### ISSUE TITLE
modify chargingStation attributes at runTime

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#12772]

**Comment by m-kro** [comment]
Would be useful in the context of limiting the charging due to too many users of the energy supply.

**Comment by m-kro** [comment]
Request by @PhilippWidmann : 

- make attributes readable, most interested in power & efficiency
- access current occupancy and vehicle capacity

**Comment by extremeCrazyCoder** [comment]
Because it fits into this issue:

It would be nice if the charge_delay parameter was readable (and maybe writable) via traci

**Comment by m-kro** [comment]
some documentation is missing
