### ISSUE TITLE
emission output filter

### ISSUE THREAD

**Issue by jianki1314** [eclipse-sumo/sumo#12850]
How to output only the desired value in the emission output

**Comment by m-kro** [comment]
This is currently not supported. We take your suggestion to include a filter.

**Comment by namdre** [comment]
Filtering of **--emission-output** attributes should work with a new option **--emission-output.attributes** similar to filtering of fcd-output (**--fcd-output.attributes**).

**Comment by jianki1314** [comment]
Thanks, I have solved the problem by checking the documentation。
