### ISSUE TITLE
Add gap time (GT) / time advantage (TADV) / predicted PET (PPET) to SUMO

### ISSUE THREAD

**Issue by bcoueraud87** [eclipse-sumo/sumo#12907]
For the needs of the SAVeNoW project, I need to have access to gap time (GT) / time advantage (TADV) / predicted PET (PPET), as used in _Online risk estimation of critical and non-critical interactions between right-turning motorists and crossing cyclists by a decision tree_ by Hagen Saul, Marek Junghans, Mandy Dotzauer, and Kay Gimm.

Excerpt from the article: _gap time (GT) or alternatively called time advantage (TADV) is a continuous version of the PET indicating how close two road users will miss each other if their speed and present course remain — thus, it has a predictive character._

**Comment by behrisch** [comment]
PPET is the preferred name

**Comment by namdre** [comment]
as discussed with Micha:  prediction simply extrapolates acceleration and if vehicles appear to break ahead of the stop line, there is no conflict and thus no PPET.

**Comment by namdre** [comment]
@bcoueraud87 can you test the resulting values and see whether they are useful for their intended purpose?

**Comment by namdre** [comment]
no complaints were forthcoming.
