### ISSUE TITLE
Whether to disable SUMO's car following model

### ISSUE THREAD

**Issue by a-123-du** [eclipse-sumo/sumo#13014]
Hi, I'm working on unsignaled intersections, controlling vehicles and dispatching by myself, and I'm wondering, should I turn off sumo's car following model or add controls to its own car following model?Thank you very much for your answer.

**SUMO-version:1.16.0**

**operating system:Windows**

**Comment by namdre** [comment]
Controlling vehicles via TraCI (and disabling SUMO control) is easier to implement, whereas adding a custom car following model has the potential for better runtime performance.  A typical approach is to start with TraCI and only switch to an internal C++ implementation if running time is a bottleneck.

**Comment by a-123-du** [comment]
> Controlling vehicles via TraCI (and disabling SUMO control) is easier to implement, whereas adding a custom car following model has the potential for better runtime performance. A typical approach is to start with TraCI and only switch to an internal C++ implementation if running time is a bottleneck.
Yes,I will use traci. But by disabling sumo control, do you mean turning off the  car following model? I'm struggling with whether or not I should turn off the car following model.

**Comment by namdre** [comment]
If by *switching off the car following model*, you mean using `traci.vehicle.setSpeedMode` to override the model speed with your own speed, then you only need to disable the parts that interfere with your custom algorithm.
