### ISSUE TITLE
Add polygon shapes on lanes and intersections

### ISSUE THREAD

**Issue by a-123-du** [eclipse-sumo/sumo#13031]
Hello, could you please tell me how to add polygon shapes on lanes and intersections in SUMO, just like the green rectangle box in the picture below. What I want is for me to be able to autonomously make it appear and make it disappear while the vehicle is in motion. Thank you very much for your answer.
![6ce63b2fabc3778f1d7b2f00e18b9ca](https://user-images.githubusercontent.com/54823725/231973010-1b126249-9b3b-422d-9d58-6bdeb1b27597.png)

**SUMO-version:1.16.0**

**operating system:Windows**

**Comment by namdre** [comment]
have you tried looking into the traci documentation?
