### ISSUE TITLE
invalid geometry point modification on overlapping edges

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#13045]
- create two edges that cross each other without a junction (thus creating overlap)
- create a geometry point on one of the edges in the overlapping area
- in move mode, try to move the geometry point
  - the point is highlighted but when trying to draw it, it may happen than a new poin on the *other* edge is created instead

**Comment by palvarezlopez** [comment]
Is the same problem of #15322 , and therefore the same solution.
