### ISSUE TITLE
Improving SSM device outputs

### ISSUE THREAD

**Issue by robertalms** [eclipse-sumo/sumo#13070]
In order to get speed information for conflict events one has to write full trajectory data to the ssm-output `"device.ssm.trajectories" value="true"` which increases the output file size significantly. Also, the xml is then quite inconvenvient to parse in order to match conflict events with the actual velocity. 
To makes things even more difficult, conflicts are written redundantly for `foe` and `ego`.

To make things a bit easier to handle SSM output data, I'd suggest to:

1. add an option to the SSM device for users to choose only to write 'foe' or 'ego' events.
2. add the speed of the vehicle to the currently available SSMs `TTC`, `DRAC` and `PET`. (This would save the trouble to even add trajectories to the xml-output.)

**Comment by m-kro** [comment]
Another suggestion by @robertalms : MDRAC measure, see e.g. [this publication](https://downloads.hindawi.com/journals/jat/2017/8376572.pdf)

**Comment by namdre** [comment]
DCIA klingt auch sinnvoll

**Comment by m-kro** [comment]
@robertalms Is there anything left? If not we can close this one...
