### ISSUE TITLE
[Bug] gtfs2pt.py - Error in routeID and vehicleID in xml file 

### ISSUE THREAD

**Issue by JoaoMarcelino** [eclipse-sumo/sumo#13346]
Hello,

I was trying to translate GTFS data to SUMO using python, but sometimes the route id comes in a messy format and thus unavailable to use in the simulation.

The  command used was 
`
    options = [
        "-n",
        network_file,
        '--gtfs',
       gtfs_file,
        '--date',
        '20220912',
        '-v',
        '--fcd',
        fcd_folder,
        '--network-split',
        resources_folder,
        '--vtype-output',
        vtpyes,
        '--route-output',
        routes,
        '--additional-output',
        stops,
    ]
gtfs2pt.main(gtfs.get_options(options))
`

Resulting in a vehicles.add.xml file with:

`   
<route id="('106_0_U_10',)" edges="158756053  (...)">
`

and

`   
<vehicle id="('106_0_U_10',).0" route="('106_0_U_10',)" type="bus" depart="33590" line="('106_0_U_10',)">
`

I tried replicating the bug in Windows 10 sumo version 1.17.0 but the route id came clean and ready to be used in simulation.
`
<route id="106_0_U_10" edges="158756053 (...)">
`

**SUMO-version:**
Eclipse SUMO sumo Version 1.17.0
 Build features: Linux-5.4.0-147-generic x86_64 GNU 9.4.0 Release FMI Proj GUI Intl SWIG GDAL GL2PS Eigen

**operating system:**
Docker 
ubuntu:20.04

**Comment by behrisch** [comment]
@JoaoMarcelino Can you report the Python and pandas version used?

**Comment by JoaoMarcelino** [comment]
The error occured in Python 3.8.10 and pandas 2.0.2.
After testing in other computer with the same docker version, sumo version, Python 3.8.10 and pandas 1.5.3 the bug no longer occured, and it was possible to create the file correctly.

**Comment by behrisch** [comment]
The reason is the change in pandas 2.0 due to https://github.com/pandas-dev/pandas/issues/42795
