### ISSUE TITLE
Collision on junction

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse-sumo/sumo#13363]
Hello @namdre , I am using (v1_17_0+0687-80de905e644) nightly snapshot. It occurs with default car following model, step-length 0.1s at time 10346.00.

**Warning: Teleporting vehicle 'c9900_323'; junction collision with vehicle 'c9900_330', lane=':J2_4_0', gap=-2.33, time=10346.00 stage=move.**

Regards.
[collision_on_junction.zip](https://github.com/eclipse/sumo/files/11645583/collision_on_junction.zip)

**Comment by mehmetnedimyavuz** [comment]
Hello @namdre, In my scenario, I set the --collision.check-junctions "True". Totally there are 13 collisions warnings. Can you check with added files? I am using  Eclipse SUMO sumo Version v1_17_0+1032-444433aca76. Also, why default setting of collision check is False? Thank you,regards.

**1.	Warning: Teleporting vehicle 'c900_56'; junction collision with vehicle 'c900_53', lane=':J0_3_0', gap=-1.00, time=1028.60 stage=laneChange.
2.	Warning: Teleporting vehicle 'c1800_39'; junction collision with vehicle 'c1800_37', lane=':J0_3_0', gap=-1.00, time=1919.50 stage=laneChange.
3.	Warning: Teleporting vehicle 'c1800_156'; junction collision with vehicle 'c1800_149', lane=':J0_3_0', gap=-1.00, time=2033.20 stage=laneChange.
4.	Warning: Teleporting vehicle 'c2700_654'; junction collision with vehicle 'c2700_631', lane=':J0_3_0', gap=-1.00, time=3559.40 stage=laneChange.
5.	Warning: Teleporting vehicle 'c4500_100'; junction collision with vehicle 'c4500_91', lane=':J0_3_0', gap=-1.00, time=4709.10 stage=laneChange.
6.	Warning: Teleporting vehicle 'c5400_312'; junction collision with vehicle 'c5400_301', lane=':J0_3_0', gap=-1.00, time=5876.00 stage=laneChange.
7.	Warning: Teleporting vehicle 'c5400_670'; junction collision with vehicle 'c5400_663', lane=':J0_3_0', gap=-1.00, time=6333.00 stage=laneChange.
8.	Warning: Teleporting vehicle 'c6300_213'; junction collision with vehicle 'c6300_209', lane=':J0_3_0', gap=-1.00, time=6624.50 stage=laneChange.
9.	Warning: Teleporting vehicle 'c8100_340'; junction collision with vehicle 'c8100_333', lane=':J0_3_0', gap=-1.00, time=8578.90 stage=laneChange.
10.	Warning: Teleporting vehicle 'c9000_422'; junction collision with vehicle 'c9000_413', lane=':J0_3_0', gap=-1.00, time=9571.10 stage=laneChange.
11.	Warning: Teleporting vehicle 'c10800_172'; junction collision with vehicle 'c10800_163', lane=':J0_3_0', gap=-1.00, time=11100.50 stage=laneChange.
12.	Warning: Teleporting vehicle 'c10800_391'; junction collision with vehicle 'c10800_379', lane=':J0_1_1', gap=-1.00, time=11372.90 stage=laneChange.
13.	Warning: Teleporting vehicle 'c11700_72'; junction collision with vehicle 'c11700_62', lane=':J0_3_0', gap=-1.00, time=11829.40 stage=laneChange.**
[junction_collisions.zip](https://github.com/eclipse/sumo/files/11816971/junction_collisions.zip)

**Comment by namdre** [comment]
By default, collision checks on junctions are disabled because they are computationally expensive and the collisions are usually not expected to occur.

**Comment by mehmetnedimyavuz** [comment]
Note: Collisions occurs not only with step-length 0.1 s,but also with step-length 1s.

**Comment by namdre** [comment]
continued in #15927 because this ticket already occurred as closed in a change log
