### ISSUE TITLE
Unknown Edge

### ISSUE THREAD

**Issue by Swayam069** [eclipse-sumo/sumo#13594]
There is one edge which is produced when we create the osm map form the sumo simulation which is of ash color, all the other are of normal black color but this is some thing different. The vehicle don't even run on those edge, why is this problem occurring and why is it not having any x y coordinate but when i try to print all the edges in some txt file from the net file this edge appear. the edge is having the start and end junction/node. 
I will  attach  the screen shot with the actual visual of the edge.
![edge_pic](https://github.com/eclipse/sumo/assets/100756153/05d5ade5-c803-4a8b-86c3-b6cd28ba686e)
Thanks,
-Swayam

**Comment by namdre** [comment]
OSM contains edges of different types and some are only useful in a multi-modal simulation (i.e. with bicycles or pedestrians). Keeping these edges shouldn't have a negative impact on your simulation results.
If you wish to exclude them, then check the "Car-only Network" button in the osmWebWizard or set option **--keep-edges.by-vclass passenger** when running netconvert.
