### ISSUE TITLE
Repeated route with single stop will cause stops to be concatenated

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#13639]
The vehicle will stop the first time, advance a small step but still be within the stop range. This triggers immediately the stop of the next round although the edges haven't been traveled!

**Comment by m-kro** [comment]
Internal logic for stops has to be adapted as the vehicle will still try to stop a second time. Some idea:

- add cycle counter
- check if the stop can still be reached along the route (excluding the current edge when already at the stop)

**Comment by m-kro** [comment]
Waitin' for @behrisch

**Comment by namdre** [comment]
test added in  047c647

**Comment by namdre** [comment]
the debug build has a failing test because `assert(haveValidStopEdges());` produces warnings

```
> Warning: Stop 1 on edge 'SC' is used in 7 edges but first encounter is in 3 edges for vehicle '0' at time=93.00
> Warning: Stop 1 on edge 'SC' is used in 6 edges but first encounter is in 2 edges for vehicle '0' at time=101.00
> Warning: Stop 1 on edge 'SC' is used in 5 edges but first encounter is in 1 edges for vehicle '0' at time=109.00
> Warning: Stop 1 on edge 'SC' is used in 4 edges but first encounter is in 0 edges for vehicle '0' at time=116.00
```
