### ISSUE TITLE
Let the user provide a default waiting position (contPos) for internal junctions

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#13642]
Currently only possible by specifying it explicitly for every connection using the Plain XML format.
Suggested by Sasan Amini on the [mailing list](https://www.eclipse.org/lists/sumo-user/msg13256.html).

Proposal: new netconvert option **--default.junctions.cont-pos DOUBLE**

**Comment by namdre** [comment]
The option doesn't take effect when connections are guessed (rather than loaded)
