### ISSUE TITLE
Variable speed signs are disregarded when using vehicle class limits from edge type

### ISSUE THREAD

**Issue by yuameier111** [eclipse-sumo/sumo#13652]
hello, here is my vss code and the videorecord. Why the vehicles can't stop as the speed limit? 

https://github.com/eclipse/sumo/assets/136823316/03b0873b-224d-49d8-bd60-95ad39f430da

[test.zip](https://github.com/eclipse/sumo/files/12140965/test.zip)

**Comment by m-kro** [comment]
@yuameier111 You can try the [development version](https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version) from our website which makes the vehicles stop in your scenario.

**Comment by namdre** [comment]
Can we get a test on this? I think the logic might be the wrong way around since it uses `isDefault` as `mySpeedByVSS` (which I think is true when the VSS hands back control)

**Comment by m-kro** [comment]
You are right, is was wrong way around.
