### ISSUE TITLE
VSS and TraCI-induced lane speed limit override edge type speed restrictions

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#13665]
There are a few ways how to set the max. allowed edge/lane speed. They could be classified according to these criteria:
- defined in input file / user input through GUI or TraCI
- constant / dynamic: whether the speed limit is subject to change over the simulation time

Before #13652 , edge type speed restrictions (if defined) would override any other speed definition for a certain vehicle class. This is particularly problematic if the edge type speed limit exceeds the freshly imposed one e.g. by TraCI or variable speed signs.

Some general guidelines on how to change the way the final allowed speed could be changed:

- give priority to dynamic speed limits over constant ones
- give priority to speed limits issued through user input over those defined in input files
- maybe still respect edge type restrictions **if** their speed limit is lower than the one from GUI / TraCI / variable speed sign

**Comment by yuameier111** [comment]
thanks for your help, and where to set the priority of the edge/lane speed limit ?

**Comment by m-kro** [comment]
This issue is meant or developers to rethink the internal rules of allowed lane speeds in SUMO. The work hasn't been done yet.
