### ISSUE TITLE
[using multiple displays] context menus are being shown only on the main display

### ISSUE THREAD

**Issue by angelobanse** [eclipse-sumo/sumo#13674]
This seems to only affect Windows (in macOS it works as expected).
 
![grafik](https://github.com/eclipse/sumo/assets/16121932/1505fcae-365e-4a45-aa2f-d24e72390891)

**Comment by m-kro** [comment]
Same for me... And it uses the resolution of the screen where netedit/sumo-gui is placed for the context menu.

**Comment by angelobanse** [comment]
The position of the primary and secondary screens seem to matter.
If the main monitor is located to the right of the secondary, this context menu phenomenon/issue occurs. Selecting the left monitor as the primary avoids it.

**Comment by angelobanse** [comment]
It seems this issue has been around for years -> https://sourceforge.net/p/foxgui/bugs/89/

**Comment by m-kro** [comment]
Seems to be influenced by Windows screen scale settings.

**Comment by m-kro** [comment]
OK now the story: We were to blame for the main point as negative coordinates (for secondary monitors on the left side) had been prevented. The current solution will at least reposition the context menu correctly to stay completely on the same screen as sumo for a main and a secondary left screen.  @angelobanse Is it still OK on Mac?

Further problems with screen coordinate calculation:

- screen scale factor (Windows) will impact the coordinates retrieved through FOX
- screen boundaries cannot be queried easily in FOX, as the returned screen height refers to the total visible area = max. screen height and the width of neighbour screens is not easily retrievable

**Comment by angelobanse** [comment]
This didn't affect macOS previously, and it still doesn't (Version v1_18_0+0822-0778820e305) at least on sumo-gui.
