### ISSUE TITLE
Recompute during undo-redo doesn't keep connections

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse-sumo/sumo#13699]
Found during #13673

1 - Create a chain of two or more edges
2 - Undo all
3- F5
4 - Redo all

It's a design problem, and causes the following bugs:
#3742
#9383
#10605

This problem exists for years ago.

**Comment by namdre** [comment]
connections are computed when first pressing F5 so the following two things work as expected:
- pressing F5 after step 4 correctly creates all connections
- when pressing F5 after step 1 (which creates connections) and skipping step 3, the connections will also be present after step 4

However, the sequence with F5 after step 1 and F5 in step 3 will indeed cause missing connections (which becomes visible when pressing F5 again after step 4. 
Additionally, trying to click on a connection directly after step 4 crashes netedit.

**Comment by namdre** [comment]
This sequence first fails with 1.19.0:   (hence a regression)
1. create 2 edges
2. inspect mode, enable 'show connections'
3. F5
4. undo all
5. F5
6. redo all
7a. - click on visible connection -> crash (in 1.18 and earlier, no connection is visible here)
7b -  F5  expecting to see connections again but getting a disconnected edge

This sequence first crashes in the dev version (hence we also have a dev_regression):
1. create 2 edges
2. (optionally F5 to first compute connections)
3. undo all
4. F5
5. redo all


@palvarezlopez Can you give a detailed event sequence for versions before 1.19? maybe I'm missing something.

**Comment by namdre** [comment]
working as expected after fixed to #14391.

**Comment by namdre** [comment]
#10605 is completely unrelated to this topic.
