### ISSUE TITLE
libtracijni/libsumojni missing from ARM64 version of Ubuntu deb

### ISSUE THREAD

**Issue by megascrapper** [eclipse-sumo/sumo#13702]
I noticed that the ARM64 and armhf version of SUMO deb package from the PPA does not include `libsumojni` and `libtracijni`, while the amd64 version does.

Is there any reason for this? Would it be possible to include the JNI libraries (and also probably the `libsumo`/`libtraci` for Python) for all versions?

**SUMO-version: 1.18.0**

**operating system: Ubuntu 22.04 on Docker**

**Comment by m-kro** [comment]
@megascrapper Can you provide the link from where you get the package?

**Comment by megascrapper** [comment]
> @megascrapper Can you provide the link from where you get the package?

It's the PPA mentioned in the [downloads page](https://sumo.dlr.de/docs/Downloads.php#linux)

<https://launchpad.net/~sumo/+archive/ubuntu/stable>

**Comment by behrisch** [comment]
It seems the arm64 build does not install the jdk. Maybe I was wrong about what Build-Depends-Indep: is supposed to do.

**Comment by behrisch** [comment]
For python you should be able to use the [pip repo](https://pypi.org/project/libsumo/) BTW

**Comment by behrisch** [comment]
should be fixed
