### ISSUE TITLE
crash in netedit due to netbuild / connections

### ISSUE THREAD

**Issue by angelobanse** [eclipse-sumo/sumo#13731]
Steps to reproduce:
- Create a *conflicting connection*
- Select **Prohibition mode** and click on any connection on the node where the conflicting connection was created

![grafik](https://github.com/eclipse/sumo/assets/16121932/81618bc7-2be8-4abe-af28-6d91f60374b0)

Computing the junctions (F5) between these steps avoids the crash.

In `src/netbuild/NBRequest.cpp` the following evaluates to true `linkIndex = (int)myFoes.size()` (before manually triggering the recompution of junctions):
https://github.com/eclipse/sumo/blob/37467cf468896d42aa2c40f9cc59691d973c0a4f/src/netbuild/NBRequest.cpp#L385

**Comment by behrisch** [comment]
I tried to fix it by adding a computeLogic call after the connection modification but it did not work. Maybe we could just force network computation when we switch to prohibition mode? @palvarezlopez What do you think?

**Comment by palvarezlopez** [comment]
@behrisch yes, It's a good solution. I'm going to implement it
