### ISSUE TITLE
getStopParameter() 

### ISSUE THREAD

**Issue by claudiacbh** [eclipse-sumo/sumo#13748]
Hello!
I need to know the last bus stop visited by a particular bus. For this purpose, I am using the getStopParameter() function. However, when I execute in Python console, I encounter the following error: "TraCIException: getting a stop parameter needs a compound object description of 2 items."

Can you help me figure out this problem?

*If possible, upload an example that shows your problem.*

            listaVeh = traci.vehicle.getIDList()
            for vehID in listaVeh:
                bStop = traci.vehicle.getStopParameter(vehID, -1, "busStop")

I tried with different parameters such as "duration," and I also attempted using `nextStopIndex=1`. However, I discovered that the error lies within the "param" itself, requiring a compound object description of 2 items.

**SUMO-version:**
SUMO 1.18.0
**operating system:**
Windows 11

**Comment by behrisch** [comment]
The message you refer to has been changed in https://github.com/eclipse-sumo/sumo/commit/8686eddfbf5a3502d179b341e432d636cd7277ff so before 1.18.0. Please double check that you are not accidentally using an old sumo version. Maybe your PATH contains another sumo.

**Comment by behrisch** [comment]
Please add another comment if you have more information

**Comment by claudiacbh** [comment]
Thank you. It was the Path.
