### ISSUE TITLE
Extend the log files with timestamps and process names

### ISSUE THREAD

**Issue by bcoueraud87** [eclipse-sumo/sumo#13757]
It has been asked to extend log files with timestamps for every relevant line, as well as the name of the SUMO process that is responsible for logging the line.

**Comment by bcoueraud87** [comment]
@behrisch Please assign me.

**Comment by palvarezlopez** [comment]
https://github.com/eclipse/sumo/pull/13765

**Comment by behrisch** [comment]
has been prepared in #13767
