### ISSUE TITLE
documentation on traci exceptions

### ISSUE THREAD

**Issue by anthonyKiggundu** [eclipse-sumo/sumo#13753]
The documentation that accompanies libtraci is not helpful for the developer because no detail is provided about exception handling which makes it extremely difficult to debug with or even walk-around errors like the one below. It would be helpful if we have  a list of all exceptions so that we know how to get around. 

https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html
or -> https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#handling_exceptions

*CarID is = veh5 
Traceback (most recent call last):
  File "test_traci.py", line 58, in <module>
    print("Position = %s, %s" % traci.vehicle.getPosition(VehId))
  File "/usr/local/lib/python3.8/dist-packages/libtraci/libtraci.py", line 4496, in getPosition
    return _libtraci.vehicle_getPosition(vehID, includeZ)
libtraci.libtraci.TraCIException: Vehicle 'veh5' is not known.*

**1.8.0**

**Ubuntu 20**

**Comment by behrisch** [comment]
There are only two exceptions TraCIException and FatalTraCIError and I don't think we will document all the places where they can occur. Can you elaborate a little on your expectations?

**Comment by behrisch** [comment]
closing for lack of feedback. Please add another comment if you can describe what is actually missing
