### ISSUE TITLE
some problems with lane-changing, the unefficient use for the lane space of the edge.

### ISSUE THREAD

**Issue by Siyu-Hong** [eclipse-sumo/sumo#13766]
Add your issue description here.
During simulation, one lane becomes two lanes, and the vehicle will only select one of the two lanes. How can I solve this problem so that the probability of two lanes being selected is equal?

*If possible, upload an example that shows your problem.*

**SUMO-version:**  SUMO v1_12_0+1907-607e5205ffc

**operating system:**   Windows 11
[test.zip](https://github.com/eclipse/sumo/files/12495683/test.zip)

**Comment by behrisch** [comment]
Convert it to a zipper junction https://sumo.dlr.de/docs/Networks/PlainXML.html#node_types. Do so by changing the junction type in netedit and then resetting the connections (right click on the junction)
