### ISSUE TITLE
Request to add additional osm tags to output of netconvert tool (elmar format)

### ISSUE THREAD

**Issue by EricNeid** [eclipse-sumo/sumo#13762]
In the OSM format there are the tags maxheight, maxwidth and maxweight. It would be very good if the content of these tags could be added to the Elmar (dlr-navtech) output format when using the *netconvert* tool. Furthermore the surface tag would also be beneficial.

Example osm way:

```xml
  <way id="345198954">
    <nd ref="3518912628"/>
    <nd ref="3157445536"/>
    <nd ref="3518912630"/>
    <nd ref="4515969330"/>
    <nd ref="4515969331"/>
    <nd ref="3157445537"/>
    <tag k="highway" v="service"/>
    <tag k="maxheight" v="3.8"/>
    <tag k="maxwidth" v="3"/>
    <tag k="oneway" v="yes"/>
    <tag k="surface" v="paving_stones"/>
    <tag k="traffic_sign" v="NL:C19"/>
    <tag k="traffic_sign_1" v="NL:C18"/>
    <tag k="tunnel" v="building_passage"/>
    <tag k="zone:traffic" v="NL:urban"/>
  </way>
```

* these properties should be present in the output file *links_unsplitted.txt*
* the default value of *-1* can be used if the tag is not present

**SUMO-version:**

Eclipse SUMO netconvert Version 1.9.2

**operating system:**

Build features: Windows-10.0.17763 AMD64 MSVC 19.27.29111.0 Release Proj GUI SWIG

**Comment by behrisch** [comment]
The Elmar format 6.5 does not know these columns. Should we add them nevertheless or add a switch to keep backwards compatibility?

**Comment by behrisch** [comment]
There might be the additional problem that the tags are sometimes applied to nodes as well. It is a bigger effort to parse those as well.

**Comment by behrisch** [comment]
@EricNeid I would consider it completed but would very much like to enter the correct new Elmar version number here

**Comment by EricNeid** [comment]
Thank you. I forwarded your request to Alex and Elmar. I hope they can answer your question regarding the version number.

**Comment by also90** [comment]
@behrisch  There was currently no versioning in the Elmar-format, so we agreed to set the last stable version as 1.99.

**Comment by behrisch** [comment]
@also90 There is this line at the header of each file: `Format matches Extraction version: V6.5` I thought this refers to a version number?

**Comment by also90** [comment]
@behrisch this is the version of the GDF extractor, but for consistency we agree to use this version as the first version to pass to netconvert.

**Comment by behrisch** [comment]
@also90 @elmarbrockfeld @EricNeid The current implementation uses 6.5 as default version and it will output the additional values like maxheight etc. if you specify a different version. I will adapt the code such that a minimum version of 7 is needed to output the new values. Okay? Or should 7 be the new default and you need to enable the old behavior explicitly by choosing 6.5?

**Comment by behrisch** [comment]
After speaking to @elmarbrockfeld the default stays with 6.5 for now. Any given major version > 6 will trigger the output of the new attributes.
