### ISSUE TITLE
SUMO GUI shows black screen when loading network file on Ubuntu 22.04

### ISSUE THREAD

**Issue by holtvogt** [eclipse-sumo/sumo#13763]
I noticed a black screen when loading a network file on Ubuntu 22.04, while it works on an Ubuntu 20.04 machine.

![image](https://github.com/eclipse/sumo/assets/35570024/239fde49-9c5c-48bf-ba9f-742ae55e92eb)

**SUMO Version:**
1.18.0

**Operating System:**
Ubuntu 22.04

**Comment by palvarezlopez** [comment]
@holtvogt Thanks!

**Comment by behrisch** [comment]
@holtvogt Can you please report the graphics card and the driver you use and also whether it is wayland or Xorg? Thank you!

**Comment by holtvogt** [comment]
**GPU:**
NVIDIA RTX A2000

**Driver Version:**
517.51

**Protocol:**
Wayland

**Comment by behrisch** [comment]
Can you try switching back to Xorg (and I suppose you are running Xorg on 20.04)?

**Comment by holtvogt** [comment]
Wayland is also running on the 20.04 machine. Therefore, does it make sense to disable Wayland?

**Comment by behrisch** [comment]
Probably not. Does the 20.04 machine also use the same graphics card driver?

**Comment by holtvogt** [comment]
Yes, I use 20.04 and 22.04 via WSL

**Comment by behrisch** [comment]
@holtvogt Do simple test programs like glxgears work?

**Comment by holtvogt** [comment]
Sorry for my late reply! I encountered the same black screen issue for glxgears, too. But sometimes, a simple GPU driver update does the trick. I updated to 537.42 and it works now
