### ISSUE TITLE
Error loading configurations in paths which contain 'ñ/Ñ' characters 

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse-sumo/sumo#13768]

**Comment by behrisch** [comment]
Does this happen on Windows and Linux?

**Comment by palvarezlopez** [comment]
in Windows

**Comment by angelobanse** [comment]
> I cannot reproduce it from the command line or using a double click. @angelobanse Is this maybe the same as #14005 ?

@behrisch yes it is.
