### ISSUE TITLE
IOError: osmWebWizard XML files not generated 

### ISSUE THREAD

**Issue by AligetiDivya** [eclipse-sumo/sumo#13770]
Kindly help me to solve this issue. osmWebWizard.py cannot generate XML files and it says ioerror

![PXL_20230901_155557620](https://github.com/eclipse/sumo/assets/37445617/feaf4a39-0874-43e0-9bbe-13ae5fe3f5b6)

![PXL_20230901_155657048](https://github.com/eclipse/sumo/assets/37445617/0d9dfe62-b327-4cc5-906e-8254028a654c)

**SUMO-version:** 1.4.0

**operating system:** linux

**Comment by behrisch** [comment]
Is there any reason why you use such an old SUMO and python 2?

**Comment by AligetiDivya** [comment]
git clone --recursive https://github.com/eclipse/sumo
I just cloned using this command for sumo

**Comment by behrisch** [comment]
Closing for lack of feedback. Please add another comment if you think we can help.
