### ISSUE TITLE
Multiple OpenDRIVE traffic lights associated with SUMO junction links when running netconvert

### ISSUE THREAD

**Issue by Mr-Bl0nde** [eclipse-sumo/sumo#13775]
I'm trying to track down why multiple OpenDRIVE traffic light IDs are being associated with their corresponding SUMO links. In the following screenshot, I would expect each of the **param:linkSignalID:X** attributes to have just 1 value. For links 0, 1, and 2, for example (corresponding with right, straight, and left turns from the northern edge of the intersection) the associated OpenDRIVE traffic light ID should be 1025, but link 0 has both 1024 and 1025.

![image](https://github.com/eclipse/sumo/assets/55114665/df6df8fb-e05b-4b80-95ab-7ab9c3092f26)

Context: I am running netconvert on [Town07.xodr](https://carla.readthedocs.io/en/latest/map_town07/) from the additional maps package of the [CARLA project](https://carla.readthedocs.io/en/latest/) (v 0.9.12). I didn't run any netconvert cli options that should affect the outcome, just --opendrive, --offset.disable-normalization, and --tls.cycle.time 20. No other [netconvert tls-related cli options](https://sumo.dlr.de/docs/netconvert.html#tls_building) seem to make any difference, but maybe I just don't understand them fully. I'm not sure if this issue arises from netconvert or the underlying .xodr.

Please let me know if I should add more context, I didn't want to overload this initial post.

EDIT: Here is a [closed issue introducing linkSignalID:X writing logic](https://github.com/eclipse/sumo/issues/6863) in [netconvert source code](https://github.com/eclipse/sumo/blob/main/src/netbuild/NBTrafficLightLogicCont.cpp).

**SUMO-version:** Win64 v1.16.0

**operating system:** Microsoft Windows Enterprise 10.0.22000

**Comment by m-kro** [comment]
The network contains problematic signal definitions similar to #8695 . However it has to investigated whether this causes the described param values, too.

**Comment by Mr-Bl0nde** [comment]
Here is a zipped folder with Town07.xodr and the netconverted .net.xml:

[XODR_and_net_xml.zip](https://github.com/eclipse-sumo/sumo/files/12602197/XODR_and_net_xml.zip)

@m-kro The .xodr does assign the signal's id to the sidewalk/shoulder element it is nearest to as you warned against in #8695. The mis-assignment of traffic light IDs, however, doesn't appear have a regular pattern based on right-hand turn proximity as far as I can tell. If there were, I might expect substitution with the wrong tlid, but not a concatenation (e.g. 1024 1025)?

**Comment by m-kro** [comment]
Turns out the OpenDrive file has defined multiple connecting roads inside the intersection for the same origin/destination pair:

- Road 770 connects roads 14 to 27 with lanes 2 to 0 and is controlled by signal 1024
- Road 775 connects roads 14 to 27 with lanes 0 to -1 and is controlled by signal 1025

That's why in the end they get marked in the same SUMO connection. In the end it can be tracked back to the problem in #8695 : How to interpret the OpenDrive signal and signal reference tags? Do they indicate the physical position of a signal and / or the logical assignment to a lane / connection? Actually the OpenDrive reference is not 100% clear in this. Currently SUMO interprets signals and and signal references the same way but this is maybe wrong...?

**Comment by Mr-Bl0nde** [comment]
Thank you so much for identifying the source of these concatenated linkSignalIDs, it does seem to be arising from OpenDRIVE IDs associated with shoulder/sidewalk “road” elements (e.g. Road 770). I believe the OpenDRIVE ID is being assigned to these automatically because traffic signals are being physically placed on the sidewalks/shoulders, even though they’re not meant to affect the logical control of traffic on these roads (see discussion below).

I assume the CARLA team duplicated these road connections to ensure the sidewalks connected properly at intersections, but ultimately netconvert should be able to filter them out. There is an option to include all lanes including these sidewalks/shoulders in the .net.xml (--opendrive.import-all-lanes), but there is no way to opt out of them for traffic light identification. **There should be a maximum of one linkSignalID value for a given junction link. If there are multiple, then the tiebreaker can be the OpenDRIVE lane attribute “type”. If the <road> does not have any <lane> elements with type=“driving” then it should not be considered.** Other values “shoulder” or “sidewalk” indicate those non-drivable entities that shouldn’t be controlled by a traffic light. If nothing else, this would be a valuable fix.

If I understand [OpenDRIVE signal positioning documentation](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4422&token=e590561f3c39aa2260e5442e29e93f6693d1cccd#top-f2ed3a40-e47a-4ab9-bb5d-0caa9c3b22ca) correctly, OpenDRIVE assumes the physical and logical position of a <signal> element are the same unless a separate physical position is specified with either a <positionRoad> or <positionInertial> element. It states 

- 12: “Signals shall be positioned in such a way that it is clear to which road or lane they belong and where their validity starts. Ambiguity about their interpretation shall be avoided.”
- 12.4: “**A signal should be placed next to the road for which it is valid**, enabling the application to identify the signals [sic] validity. **This is called the logical position of a signal**.”
- 12.4 again: “**A signal may be positioned at another physical position** that is described with [a reference line coordinate system/an inertial coordinate system]”

With that interpretation, netconvert’s default behavior of assigning OpenDRIVE <signal> elements to the road in which it is specified is justified.

This .xodr, however, doesn’t seem to follow the OpenDRIVE guidelines very well at all. I can’t speak for the CARLA team who created this and other benchmark OpenDRIVE maps, but **the intention appears to be to place <signal> elements at their physical positions, and thensolely represent logical lane control with <signalReference> elements on the roads acting as junction links**. That is based on the rendered position of traffic lights in CARLA. <signal> elements appear to be exclusively for rendering the “Signal_3Light_Post01” asset.

I guess all of this is to say that netconvert is likely correct in its current interpretation of OpenDRIVE, but it may be _useful_ to include a parameter that executes a different interpretation. I have no idea how common it is to fully adhere to OpenDRIVE traffic light standards in the wider OpenDRIVE community, but others may come across OpenDRIVE maps that take this approach. Therefore it could be useful to add a parameter, perhaps "--opendrive.signal-as-physical-position" that ignores the position of <signal> elements for logical assignment of tlids to junction links. It assumes the <signal> represents a physical, not logical, location for visualization in other simulations.

Please let me know if that makes sense, I've been staring at this problem far too long today.

**Comment by m-kro** [comment]
I take your suggestion to filter by the lane type attribute ( #13836 ) . This seems reasonable to me and not too far from the guidelines. If there were more OpenDrive networks which respect newer standards than v.1.4, many problems would have been gone for long.

I didn't really get what "--opendrive.signal-as-physical-position" should do...?

**Comment by m-kro** [comment]
A new option **--opendrive.ignore-misplaced-signals true** has been introduced today in Github source which allows to skip all signals which don't have any "driving" lane under control. See #13836 . There seems to be a separate problem regarding the connection direction vs. signals, though. Every connection gets only one traffic signal assigned but apparently it is not the right one everywhere ...!

**Comment by m-kro** [comment]
@Mr-Bl0nde Could you please check if the new option fits your purpose? 
I fear the CARLA network differs in more aspects from OpenDrive guidelines which causes "wrong" signal assignments: The orientation attribute of signals does not fit the lane validity values in some places ("+" orientation indicates lanes in the same direction as the reference line >> **negative** lane IDs). However the lane validity tag inside the same signal definition states lane 1.

**Comment by Mr-Bl0nde** [comment]
@m-kro 
1) Thank you for adding the --opendrive.ignore-misplaced-signals parameter to netconvert! I was able to reproduce a .net.xml file from Town07.xodr and there were only single linkSignalIDs per link. As you mentioned, however, there are often inaccurate linkSignalIDs for those that remain. The highlighted linkSignalIDs should be switched, for example.
![image](https://github.com/eclipse-sumo/sumo/assets/55114665/d3bb2e60-f11d-4413-bc44-b4591ddc398b)

2) Sorry about the confusion over "--opendrive.signal-as-physical-position". It didn't help that I accidentally omitted all tag mentions (`<example>`) by not marking them as code lol. I edited that comment in case it helps clear things up. To reiterate, I think it would be useful to have a netconvert parameter that assigns linkSignalID values from OpenDRIVE internal junction roads and their `<signalReference>` tags alone, without any inference from the physical position of a `<signal>` tag.

3) I am a little confused at the last comment; I'm finding that within a given `<signalReference>` tag in Town07.xodr, the orientation attribute of that tag (+/-) corresponds 100% with the sign of fromLane and toLane attributes in the `<validity>` tag. Example:
            
            <signalReference id="1032" ... orientation="-">
                <validity fromLane="-1" toLane="-1"/>

For a given `<signal>` tag corresponding with a light post, however, the orientation attribute seems unrelated to the sign of the validity tag, because all values of the validity tag are 0:

    <signal name="Signal_3Light_Post01" id="1022" ... orientation="-" ...>
                <validity fromLane="0" toLane="0"/>
	<signal name="Signal_3Light_Post01" id="1009" ... orientation="+" ...>
                <validity fromLane="0" toLane="0"/>

**Comment by m-kro** [comment]
Regarding my last comment: It's a matter of how you read the guideline. My interpretation of the OpenDrive 1.4 standard is the following:

- the road reference line (p. 10), also named "track", is defined along the "s" axis
- right lanes (in positive "s" direction) have negative indices (p. 11)
- signal orientation is defined in relation to the track direction (p. 75): a plus means "valid in positive track direction" which for me translates to the right lanes
