### ISSUE TITLE
`sigmaStep` and `step-length` for the default krauss model

### ISSUE THREAD

**Issue by woodwm** [eclipse-sumo/sumo#13806]
On the page https://sumo.dlr.de/docs/Simulation/RoadCapacity.html, 
> for the default Krauss model, step-length has a side effect on the average speed reduction from sigma (this can be remedied by setting `sigmaStep="1"` in the vType)

What I understand of this sentence is that the average speed is higher when setting `sigmaStep="1"` if step-length is less than the default value `1` s. However, this is not the case in the simulation. I have a simple on-ramp simulation using the default Krauss model and the `step-length=0.1`. The  total travel time when `sigmaStep` is the default is `477783.80 s`. After I changed the  `sigmaStep` to 1, then the total travel time becomes `601218.10 s`. Setting `sigmaStep="1"` makes the simulation more congested.

I do not know how to explain the side effect on the average speed reduction  from sigma because of step-length and what is the sugested setting when the `step-length=0.1`.

*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.18.0
**operating system:**
Win 11

**Comment by behrisch** [comment]
Can you please share your scenario?

**Comment by woodwm** [comment]
Sorry, I have problems in reproducing the issue after I restart my computer. Currently, when `step-length value="0.1"`, after I set `sigmaStep="1"`, the total travel time reduces 6% in my simulation. It is very strange as I got the result described in the issue multiple times previously. 

I will close the issue now.
