### ISSUE TITLE
standard way to modify attributes of several objects at once in sumo-GUI?

### ISSUE THREAD

**Issue by govin08** [eclipse-sumo/sumo#13818]
I'm following the [quickstart tutorial](https://sumo.dlr.de/docs/Tutorials/quick_start.html#example_description), where it explains 'priority of edges'. It says

> To change the priority, please select the edges you want to modify (see picture below). Switch to the Inspect mode. Then, you will be able to change the priority information of all selected edges by clicking on one of the selected edges.

with providing the following two screenshots.

![image](https://github.com/eclipse-sumo/sumo/assets/65585738/c71a25e1-01c6-4790-884a-c480b9fd5cda)

![image](https://github.com/eclipse-sumo/sumo/assets/65585738/e0a2a2da-627d-4066-a8bd-69ce75845bdf)

But what I found in my 1.18 version of `netedit` is like this;

![image](https://github.com/eclipse-sumo/sumo/assets/65585738/22028ca7-c316-4b41-8d32-51a9b1c5c5e2)

So, **I can't find the right way of selecting a bulk of objects** (in this case they are edges ; they can also be junctions or lanes) and modifying an attribute** (in this case it is priority ; they can also be others).

I suspect that the junction chooser like this

![image](https://github.com/eclipse-sumo/sumo/assets/65585738/116b64b2-2342-4b90-92b6-e5fb6ee2f118)

could do what I meant, but it doesn't seem that I can change attributes of several objects at once. (I'm using only when centering on the specific object. I helps, but I want more.)

- SUMO-version : I'm using `netedit` 1.18.0
- OS : windows 10

**EDIT(1)** : Further, (I might want too many things) it will be perfect if I can drag and drop to make a rectangle and to select the objects inside the rectangle so that one can view and modify the attributes of the objects. This kind of selecting method is common ; windows, starcraft, geogebra. Especially in geogebra, it enable me to do just what I want. Surely, drag and drop (left click) in this `netedit` (1.18) moves the viewing window, you can replace this functionality by "drag and drop (wheel button)" if you want (geogebra does like this).

**EDIT(2)** : And surely, I can do what I want by **find and replace** in the xml file. But I inquire if I can do this in `netedit`.

**Comment by angelobanse** [comment]
You need to go to ![](https://sumo.dlr.de/docs/images/icon_modeselect.png) **Select mode** (shortcut S) first. 
There you can:
- Hold shift and drag the selection
- Click manually on every element you want to include in the selection
- Select elements that match certain attributes using the "Match Attribute" option

You can also use the Junction Chooser (similar to the Edge chooser in your screenshot) to select all, or add to selection.

Selected elements will be colored blue.

After performing the selection, go to the ![](https://sumo.dlr.de/docs/images/icon_modeinspect.png) **Inspect mode** (shortcut I) to change parameters for all the selected elements at once.

**Comment by govin08** [comment]
Thanks. that's just what I wanted to know. It really helps.
