### ISSUE TITLE
Reuse of internal routes

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#13810]
[This user](https://www.eclipse.org/lists/sumo-user/msg13309.html) reused an internal route defined inside a flow element for a separate vehicle. Consequence: SUMO crashes when the separate vehicle leaves as the flow is still running and new vehicles are to be generated - but the pointer to the route is lost.

**Comment by behrisch** [comment]
Issue a warning if the route has an auto generated id with "!" (maybe even an error)
