### ISSUE TITLE
Vehicle speed over the speed limit

### ISSUE THREAD

**Issue by Chenyu3194** [eclipse-sumo/sumo#13826]
Hello,

I used traci to read the vehicle speed from the beginning of the simulation til the vehicle leaves the scene, and I just notice that the speed of the vehicle on the lane is actually always faster than the speed limit, for example, the limit is 50 km/h or 13.89 m/s and the plot shows that the actual speed is about 14.5 m/s. What is the default setting of the behaviour here? I changed the sigma value and it does not affect.

**SUMO-version:1.18.0**

**operating system: WIN 11**

**Comment by m-kro** [comment]
Vehicles can speed using a speedFactor attribute value greater than 1. See the [docs](https://sumo.dlr.de/docs/Simulation/VehicleSpeed.html#edgelane_speed_and_speedfactor) how to configure the vehicle behaviour in this context.
