### ISSUE TITLE
Inserting a vehicle with maximum allowed speed results in random change of departure speed

### ISSUE THREAD

**Issue by Phims22** [eclipse-sumo/sumo#13822]
I am refering to a similar problem to: https://github.com/eclipse-sumo/sumo/issues/6626

I am using SUMO 1.17.0 and traci 1.17.0

Adding vehicles via traci with following parameters:
traci.vehicle.add(vehID='veh5',routeID='Route1',departSpeed=40,depart=0,typeID='ego_vehicle',departLane='first',departPos='free')
traci.vehicle.add(vehID='veh6',routeID='Route1',departSpeed=40,depart=0,typeID='ego_vehicle',departLane='first',departPos='free')
traci.vehicle.add(vehID='veh7',routeID='Route1',departSpeed=40,depart=0,typeID='ego_vehicle',departLane='first',departPos='free')
 
 results in following warnings:
 
Warning: Choosing new speed factor 2.88 for vehicle 'veh5' to match departure speed 40.00 (max 9.97).
Warning: Choosing new speed factor 2.88 for vehicle 'veh6' to match departure speed 40.00 (max 23.98).
Warning: Choosing new speed factor 2.88 for vehicle 'veh7' to match departure speed 40.00 (max 12.33).

The SpeedMax of the vehicle class is 55.55 and the allowed speed on the lane is 13.89.

As the vehicle should be able to fullfill the speed of 40 with the vehicle maximum speed, it shouldn't be a problem adding a vehicle with the given speed. Also the different max values in the Warning by giving the same input, implies a calculation bug

**Comment by m-kro** [comment]
The speed factor relates to the allowed speed on the lane. 40 m/s seem to be way above the speed limit `speedFactor * allowedSpeed` for the three added vehicles. So the warning is expected to inform you about the durable speed factor change - it influences the vehicles along their whole route. 
Do you use a vehicle type distribution containing vehicle types with various speed factor values? Then it would be possible to have different max speed values...

**Comment by Phims22** [comment]
I got the same Warning with 14.1 m/s.  The speedlimit on the lane is 13.89 and I am using the following vehicle type (Not a distribution type):

<vType id="ego_vehicle" tau="1.928" length="4.920" accel="1.822" decel="1.376" emergencyDecel="4.490" speedFactor="1.110" vClass="passenger" carFollowModel="EIDM" lcKeepRight="0.100" lcOvertakeRight="0.500" maxSpeed="55" />

Eventhough the vehicle is slighly over the speed limit, with the speedFactor=1.11, it shouldn't be a problem

**Comment by m-kro** [comment]
There are still a few things to consider:

- speedDev value contributes to the actual chosen speed factor for a single vehicle of the type (the speed factor is sampled froma distribution by default)
- the warning is issued only if the new speed factor exceeds `speedFactor + 2 * speedDev`

**Comment by m-kro** [comment]
The speed factor is still sampled as long as you don't set speedDev to 0.
