### ISSUE TITLE
what is the unit of 'Float' of duarouter mapmatch function "--mapmatch.distance [<FLOAT>]"?

### ISSUE THREAD

**Issue by jinx2plus** [eclipse-sumo/sumo#13825]
what is the unit of 'Float' of duarouter mapmatch function "--mapmatch.distance [<FLOAT>]"?
(https://sumo.dlr.de/docs/duarouter.html)
I'm confused by setting 100 as default. I guess it's meter but I want to make sure. 

**SUMO-version:**

**operating system:**

**Comment by m-kro** [comment]
Yes, it is meters.

**Comment by jinx2plus** [comment]
Thank you!
