### ISSUE TITLE
Memory leak when libsumo.vehicle.moveToXY() fails to match the coordinate onto any road.

### ISSUE THREAD

**Issue by hongyu9876** [eclipse-sumo/sumo#13821]
Hi,

I ran into some memory leak problems when using the libsumo, and eventually traced back to the moveToXY function. There seems to be some bugs in the c++ code related to libsumo. But I couldn't get any further to adress it.

Though I have replaced the libsumo to avoid this problem, I still think it's an important issue worthy to be reported to you contributors. And hope you can fix it in the following releases.

You can reproduce the memory leak problem by runing the libsumo_test.py script in the zip file uploaded below. Here are the results obtained by runing `mprof run libsumo_test.py` from the command line:
```
mprof: Sampling memory every 0.1s
running new process
running as a Python program...
Filename: libsumo_test.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
     7     43.9 MiB     43.9 MiB           1   @profile
     8                                         def libsumo_test():
     9     47.8 MiB      3.9 MiB           1       libsumo.start(['sumo', '-c', './test.sumocfg'])
    10   1134.2 MiB    -29.7 MiB    10000001       for i in range(10000000):
    11   1134.2 MiB    -29.7 MiB    10000000           try:
    12   1134.2 MiB    -29.5 MiB    10000000               libsumo.vehicle.add(vehID='test', routeID='')
    13   1134.2 MiB    -12.6 MiB    10000000               libsumo.vehicle.moveToXY(vehID='test', edgeID='', laneIndex=-1, x=0, y=0, keepRoute=0, matchThreshold=5)
    14   1134.2 MiB   1039.0 MiB    10000000           except libsumo.libsumo.TraCIException:
    15   1134.2 MiB    -29.6 MiB    10000000               pass
    16                                                 finally:
    17   1134.2 MiB    -29.2 MiB    10000000               libsumo.simulationStep()
    18   1134.2 MiB    -31.4 MiB    10000000               libsumo.vehicle.remove(vehID='test')
```
![libsumo_test](https://github.com/eclipse-sumo/sumo/assets/144883785/b4572921-20f5-4388-ada6-33886a9aa3cb)

 And this only happen when the coordinate cannot be matched onto any road in the network. By simply set the `matchThreshold=500`, the memory usage would stay at a normal level.

*If possible, upload an example that shows your problem.*
[test.zip](https://github.com/eclipse-sumo/sumo/files/12594961/test.zip)
**SUMO-version:**
1.14.1
**operating system:**
Windows 10

**Comment by behrisch** [comment]
The problem seems to be in the exception handling in python

**Comment by behrisch** [comment]
@hongyu9876 Thanks for reporting! It would be great if you could recheck on your system whether it really has been fixed.

**Comment by hongyu9876** [comment]
It does work! Thanks for your kind response.
