### ISSUE TITLE
Filter signals by lane type to exclude wrong lane - signal relation (OpenDrive 1.4)

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#13836]
Add an option which does the following:

- works only with OpenDrive 1.4 networks
- excludes signals (traffic light) which are placed on lanes not allowed to drive on (when lane type attribute equals "none", "sidewalk",...)

This is a workaround to keep only the signals which actually control the road they are placed on. From standard v.1.5 on, additional elements to specify a different physical position have been introduced (see #12803 ).

**Comment by behrisch** [comment]
test still missing

**Comment by m-kro** [comment]
A test has been added to the internal SVN.
