### ISSUE TITLE
Lane Change Without Safety Checks with TraCI

### ISSUE THREAD

**Issue by amin-tabrizian** [eclipse-sumo/sumo#13848]
Is it possible to do lane change without any safety considerations in TraCI? What exactly I am looking for is a function that forces the vehicle to do a lane change in any condition. There is a function in TraCI for lane changing but it only performs lane change when it's successful within given time amount (changeLane).

**Comment by m-kro** [comment]
Please have a look at `traci.vehicle.setLaneChangeMode` (see [docs](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6), Python [ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setLaneChangeMode)) on how to configure the lane change behaviour for TraCI. You can enable/disable safe behaviour with bit 9 & 8.
