### ISSUE TITLE
a typing error in 

### ISSUE THREAD

**Issue by govin08** [eclipse-sumo/sumo#13841]
In  [**internal_edges** paragraph in **SUMO_Road_Networks**](https://sumo.dlr.de/docs/Networks/SUMO_Road_Networks.html#internal_edges)

It is typed like

> In case of multi-lane internal edges, the INDEX jumps by the number **of of** lanes so that EDGE_INDEX + LANE_INDEX = CONNECTION_INDEX.

As you can see, **of** is duplicated.

I'm a newcomer and I will not modify this documentation even if it is a rule that anyone can fix it. So please anyone edit this issue.

**Comment by govin08** [comment]
Another typing error in the same document.

> A special case are so called [internal junctions](https://sumo.dlr.de/docs/Networks/SUMO_Road_Networks.html#internal_junctions). These mark places where vehicles wait within an intersection before passing through foe traffic. The most common occurrence for this are:

It should be

> Special cases are so called

**Comment by m-kro** [comment]
This has been corrected, thank you.

**Comment by govin08** [comment]
> This has been corrected, thank you.

Thanks you.
