### ISSUE TITLE
Any ways to plot points in netedit?

### ISSUE THREAD

**Issue by govin08** [eclipse-sumo/sumo#13849]
Hello, I'm a newcomer. And I'm studying and getting accustomed to sumo and related things.

Here is a four-way-junction (J0). 

![image](https://github.com/eclipse-sumo/sumo/assets/65585738/f3ff0bc0-c657-4522-b100-5e293067b1ed)

I know that junctions have attribute 'shape'. And also, internal lanes have shapes, too. For example, An internal lane ":J0_0_0" has shape "-1.60,7.20 -1.95,4.75 -3.00,3.00 -4.75,1.95 -7.20,1.60" I can expect what this coordinates mean by speculation (they are intermediate points of this polyline), but I want to be more precise. It will be accomplished by plotting points in this Cartesian coordinate.

What I can do is to make junction by "create edge mode". After creating five junctions and removing unnecessary edges, I can specify the coordinates of the five junctions and see where these points are. But, this kind of approach is not good. The points (which are actually junctions) are so big that I can't recognize the location of the points well.

Is there any way to plot or mark points with specific x and y coordinates?

- SUMO-version : I'm using netedit 1.18.0
- OS : windows 10

**Comment by m-kro** [comment]
I am entirely sure I have understood what you want. If you want internal lanes to have more intermediate geometry points, there are these options:

- raise the number of points used in automatic shape generation (netconvert option **--junctions.internal-link-detail** or find it in Netedit > Processing > Options > Junctions)
- set a custom internal lane shape: select connection, choose "Set custom connection shape" from context menu
- provide a custom shape to netcomvert in a PlainXML connection file (see [docs](https://sumo.dlr.de/docs/Networks/PlainXML.html#connection_descriptions))

**Comment by govin08** [comment]
> I am not entirely sure I have understood what you want. If you want internal lanes to have more intermediate geometry points, there are these options:
> 
> * raise the number of points used in automatic shape generation (netconvert option **--junctions.internal-link-detail** or find it in Netedit > Processing > Options > Junctions)
> * set a custom internal lane shape: select connection, choose "Set custom connection shape" from context menu
> * provide a custom shape to netcomvert in a PlainXML connection file (see [docs](https://sumo.dlr.de/docs/Networks/PlainXML.html#connection_descriptions))

Sorry for ambiguous-looking question. But I just want to plot a point in `netedit` : making a small dot in `netedit` coordinate.

**Comment by m-kro** [comment]
Then create an edge, delete the edge and you are left with the start/end points. You can move them or edit their coordinate in the inspect frame.

**Comment by govin08** [comment]
> Then create an edge, delete the edge and you are left with the start/end points. You can move them or edit their coordinate in the inspect frame.

That's just what I'm explaining in the above text. If I do this, the point is too big. I just wanted to know if there are some other way.

**Comment by m-kro** [comment]
Please use the View Settings to scale the points. See the [docs ](https://sumo.dlr.de/docs/sumo-gui.html#changing_the_appearancevisualisation_of_the_simulation)how to get to the View Settings. You can lower the value of Junctions > Exaggerate by to a value below 1.

**Comment by govin08** [comment]
> Please use the View Settings to scale the points. See the [docs ](https://sumo.dlr.de/docs/sumo-gui.html#changing_the_appearancevisualisation_of_the_simulation)how to get to the View Settings. You can lower the value of `Junctions > Exaggerate by` to a value below 1.

Wow thanks. that's what I wanted.
