### ISSUE TITLE
What does `areFoes` do?

### ISSUE THREAD

**Issue by govin08** [eclipse-sumo/sumo#13850]
Hello. I want to know what does `areFoes` do.

Here is what `areFoes` looks like in the source code. (I can't find the meaning since I don't know what the `_foes` mean.

```
def areFoes(self, link1, link2):
    return self._foes[link1][len(self._foes[link1]) - link2 - 1] == '1'
```

Here is my MWE. A four-way-intersection with one-lane edges.

![image](https://github.com/eclipse-sumo/sumo/assets/65585738/17551903-5722-42c7-bf49-45591d1ee04a)

It has 12 connections as it should. (maybe I should call 'normal' connections, because there are some awkward connections)
After I return all the `areFoes` values. It looks like

![image](https://github.com/eclipse-sumo/sumo/assets/65585738/8d2577dd-488c-4ced-9d32-34d311a1bb71)

`areFoes` seems that it returns a pair of integers of connections that conflicts each other.

As for connection number 0(green) it has the following `True` connections
![image](https://github.com/eclipse-sumo/sumo/assets/65585738/7b96514e-ebeb-4347-b1f4-dcd2f404fae6)

For 1, it has

![image](https://github.com/eclipse-sumo/sumo/assets/65585738/69646ed8-cfac-4464-a321-fd74485974ac)

For 2, it has

![image](https://github.com/eclipse-sumo/sumo/assets/65585738/e5b01efb-b8c7-4dcd-888b-82476a3a3d65)

**Question** :  Does `areFoes` return a pair of indices of connections that conflicts each other?
I suspect it. But In `i=2`, areFoes(2,8)=True, although they don't conflict.

SUMO-version : I'm using netedit 1.18.0
OS : windows 10

**Comment by m-kro** [comment]
You have already understood the concept of foes. I suspect the left turns overlap (your screesnhot only shows the center lines, not the actual internal lane width).

**Comment by govin08** [comment]
> SUMO-version : I'm using netedit 1.18.0
> OS : windows 10

Thanks a lot!

**Comment by govin08** [comment]
> You have already understood the concept of foes. I suspect the left turns overlap (your screenhot only shows the center lines, not the actual internal lane width).

Do you know 'foe' is an abbreviation of what word?

Thanks, as always.

**Comment by m-kro** [comment]
It isn't. See the [Cambridge dictionary](https://dictionary.cambridge.org/dictionary/english/foe) for a definition.

**Comment by govin08** [comment]
> It isn't. See the [Cambridge dictionary](https://dictionary.cambridge.org/dictionary/english/foe) for a definition.

Thanks. It just has a meaning of "enemy".
