### ISSUE TITLE
Potential bug in node.forbids(conn_1, conn_2)

### ISSUE THREAD

**Issue by xiaoyu-huang-plus** [eclipse-sumo/sumo#13857]
Add your issue description here.
- The final return `ps[-(possProhibitorIndex - 1)] == '1'` is very suspicious to me; `ps[-(possProhibitorIndex + 1)]` seems to be the correct indexing.

*If possible, upload an example that shows your problem.*

**SUMO-version:** sumolib 1.18

**operating system:** Ubuntu 20.04.3 LTS

**Comment by m-kro** [comment]
Thank you!
