### ISSUE TITLE
How can I get angle of an edge?

### ISSUE THREAD

**Issue by govin08** [eclipse-sumo/sumo#13856]
Given an edge E, I want to find the angle (with respect to the vector (0,-1), the north direction, for example). Is there any tool to accomplish this (e.g. in sumolib)

SUMO-version : I'm using netedit 1.18.0
OS : windows 10

**Comment by govin08** [comment]
My code : 

## Given an edge, getting an angle(orientation of a node)

# get x and y coordinates of from-point and to-point
node_to = edge.getToNode().getCoord()
node_from = edge.getFromNode().getCoord()
# the edge as a vector
x = node_to[0] - node_from[0]
y = node_to[1] - node_from[1]

# clockwise angle with respect to north direction
angle = np.angle(complex(x,y), deg=True) % 360
angle

**Comment by behrisch** [comment]
Without knowing the respective numpy function the code looks good to me. What is the question?

**Comment by govin08** [comment]
> Without knowing the respective numpy function the code looks good to me. What is the question?

Sorry. I had question. But it was solved. I'll close this issue. Thanks for your comment.
