### ISSUE TITLE
Question on rerouting by traci

### ISSUE THREAD

**Issue by thinker310** [eclipse-sumo/sumo#13865]
Hello, I set  routing mode to ROUTING_MODE_AGGREGATED for every vehicle in my simulation, and using TraCI functions vehicle.rerouteTraveltime. But I find when I change the value of --device.rerouting.adaptation-weight, simulation results seem no difference for travel time or waiting time. Could you help me? Thank you in advance!
![image](https://github.com/eclipse-sumo/sumo/assets/62609436/651d52df-2801-4f35-b19a-8359d52922da)

**Comment by m-kro** [comment]
Travel times and waiting times change only if vehicles travel along a different path than without TraCI rerouting. You can use TraCI or the [vehicle routes output](https://sumo.dlr.de/docs/Simulation/Output/VehRoutes.html) to check for changes.

Does your scenario feature any situations where you except the rerouting to make a difference?

**Comment by thinker310** [comment]
> Travel times and waiting times change only if vehicles travel along a different path than without TraCI rerouting. You can use TraCI or the [vehicle routes output](https://sumo.dlr.de/docs/Simulation/Output/VehRoutes.html) to check for changes.
> 
> Does your scenario feature any situations where you expect the rerouting to make a difference?

Yes, I need re-routing in each intersection with experienced travel time. According to your comment "_Travel times and waiting times change only if vehicles travel along a different path than without TraCI rerouting._", do you mean that the travel time can not change under TraCI rerouting commands?

**Comment by m-kro** [comment]
No, I wanted to say something different. If the mean speed on an edge doesn't change much throughout the simulation, smoothing it with the option **--device.rerouting.adaptation-weight** will have no effect on rerouting. If the rerouting commands are the same as without the option, the travel and waiting times will be the same as well.
