### ISSUE TITLE
Merges edges

### ISSUE THREAD

**Issue by Clown1206** [eclipse-sumo/sumo#13867]
I use this command line to merge edges (netconvert -s D:\Desktop\map\changsha\changsha5.net.xml -o D:\Desktop\map\changsha\changsha6.net.xml) --edges.join true), but my network didn't change

![image](https://github.com/eclipse-sumo/sumo/assets/59904738/d03b0ae2-603c-4976-a132-042c0e6d6426)

*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.16
**operating system:**
win 10

**Comment by m-kro** [comment]
You should look at the intersection after executing `Processing > Compute junctions` in netedit (shortcut: F5). If you want to connect the edges in an intersection, select their end points and choose `Processing > Join Selected Junctions` (shortcut: F7). I don't see any edges for which the option **--edges.join true** would apply, as it looks for those connecting the same nodes only.

What you may want is **--junctions.join** combined with **--junctions.join-dist**?
