### ISSUE TITLE
[NetEdit] Loading a TAZ fails somehow

### ISSUE THREAD

**Issue by bcoueraud87** [eclipse-sumo/sumo#13863]
Steps to reproduce:
- Load the network,
- Load the additional polygons (additional file),
- Load the TAZ (additional file). At that point, on the screen it seems everything is loaded but NetEdit writes out messages concerning the creation of the previous polygons (from step 2, although the loading of the additional polygons was deemed successful) and that the TAZ couldn't be loaded:

![image](https://github.com/eclipse-sumo/sumo/assets/56519579/53cc9abb-a9fd-4390-ae5a-3e8103bf5f4b)

The [files](https://github.com/eclipse-sumo/sumo/files/12701966/files.zip) for this ticket.

**Comment by m-kro** [comment]
Some polygons in both additional files share the same ID. So there seems nothing wrong to me...?

**Comment by palvarezlopez** [comment]
@bcoueraud87 netedit works as expected handling duplicated elements

**Comment by bcoueraud87** [comment]
Thanks! However, I don't understand why the JuPedSim elements, that is, the polygons with types `jupedsim.something` are saved in the same file, causing this problem. There is a separate button, called _Save JuPedSim elements_, that has been created for that purpose apparently.
