### ISSUE TITLE
Question on details in rerouting scheme 

### ISSUE THREAD

**Issue by thinker310** [eclipse-sumo/sumo#13864]
Hello, I wonder how the parameter 'weights.tls-penalty' is used specifically when vehicles are rerouted, where is the source code I can reference? Thank you!

**Comment by m-kro** [comment]
https://github.com/eclipse-sumo/sumo/blob/9554271d25e5000747dc94ce0be3c52c066261c1/src/microsim/MSEdge.cpp#L132-L149
