### ISSUE TITLE
netconvert

### ISSUE THREAD

**Issue by zhoupeng0427** [eclipse-sumo/sumo#13878]
Is the road network converted by netconvert the same for xodr files in different projection coordinates?

**Comment by m-kro** [comment]
This is not limited to OpenDrive, but rather a general question about projections. Different projections may lead to different road networks. You can supply a target projection to netconvert using the [projection options](https://sumo.dlr.de/docs/netconvert.html#projection), though.

**Comment by zhoupeng0427** [comment]
> This is not limited to OpenDrive, but rather a general question about projections. Different projections may lead to different road networks. You can supply a target projection to netconvert using the [projection options](https://sumo.dlr.de/docs/netconvert.html#projection), though.

Thanks for your answer, but I can't seem to find the documentation, can you tell me how to use the projection option to provide a target projection for netconvert? Thank you very much!

**Comment by m-kro** [comment]
It's the **--proj** option (just follow the link in the previous post). You need to provide the "proj.4" string related to your target projection. [This website](https://epsg.io/4326) lists the "proj.4" string in the detail sheet of every projection.
