### ISSUE TITLE
Coordinate system transformation

### ISSUE THREAD

**Issue by zhoupeng0427** [eclipse-sumo/sumo#13870]
Please ask sumo how to deal with the road network, to convert the WGS84 based coordinate system network to cgcs2000 based coordinate system network. In addition, I would like to ask whether sumo can directly read the road network file of the 2000 coordinate system.

**Comment by bcoueraud87** [comment]
@m-kro Please assign me

**Comment by bcoueraud87** [comment]
Try to use netconvert (included in the SUMO distribution) together with the option --proj "EPSG:4490" (this is the EPSG codename of your coordinate system according to [this page](https://epsg.io/4490)). Also, SUMO can't directly read a network file with the coordinate system you mentionned.
