### ISSUE TITLE
Source code compilation, delete some buttons

### ISSUE THREAD

**Issue by Alexsv2** [eclipse-sumo/sumo#13877]
I want to know in the process of source code compilation, delete some buttons, such as Toggle View Tooltips, Toggle Menu Tooltips, what code should be commented out in the source code.

**Comment by m-kro** [comment]
You can find the code for this type of buttons in `src/utils/gui/windows/GUIGIChildWindow.cpp`, especially here:

https://github.com/eclipse-sumo/sumo/blob/387409305a90afb56c8082c172fe907c541c7029/src/utils/gui/windows/GUIGlChildWindow.cpp#L114-L148
