### ISSUE TITLE
show the information of loaded route file in the sumo-gui

### ISSUE THREAD

**Issue by woodwm** [eclipse-sumo/sumo#13875]
Add your issue description here.

*If possible, upload an example that shows your problem.*
In the latest version 1.18.0, sumo-gui shows the information of loading net-file and additional-file, but no route file. 

![image](https://github.com/eclipse-sumo/sumo/assets/13971199/cac1c960-102e-465c-bac8-fefd012eb364)

**SUMO-version:**
1.18.0
**operating system:**
windows 11

**Comment by woodwm** [comment]
I have a question on the loading route file. When I start sumo-gui by both a configuration file and a route file, but they point to two different route files, which one is loaded eventually?

**Comment by woodwm** [comment]
@m-kro Sorry, I do not mean the information on loading route files is shown in previour version, but do not shown in the latest version. I want to request a feature to add the information on loading route files in sumo-gui.

Thanks for answering the question.

**Comment by behrisch** [comment]
We should use a different message here since route files are not loaded completely
