### ISSUE TITLE
Python packages for nightly versions is not available (linux)

### ISSUE THREAD

**Issue by usamael2000** [eclipse-sumo/sumo#13899]
Add your issue description here.

I am trying to download the latest nightly version of sumo via:
pip install -i https://test.pypi.org/simple/ eclipse-sumo
but I got the latest stable version (1.18.0) instead. 

I checked the: https://test.pypi.org/simple/eclipse-sumo/
but it seems it has only the mac versions.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
OS: Debian GNU/Linux 12 (bookworm) x86_64

**Comment by behrisch** [comment]
Thanks for reporting! There were still some leftovers from the repository move
