### ISSUE TITLE
`TypeError` and Detector Mapping Issues in `mapDetectors.py`

### ISSUE THREAD

**Issue by Yunfei-Ma-McMaster** [eclipse-sumo/sumo#13891]
When using the `mapDetectors.py` script to map detectors to a network in SUMO, I encountered a `TypeError: '<' not supported between instances of 'Lane' and 'Lane'`. This error seems to be triggered when the script is attempting to sort lanes. How can I fix this?  @namdre 

Example dataset 
```
id;lat;lon;value
det6_N-24;43.581744;-79.73740190622411;100
det6_S-24;43.581744;-79.7379540937759;200
det7_N-24;43.594703;-79.73915184677554;300
det7_S-24;43.594703;-79.73970415322447;400
```

Plus if anyone can help demand modeling where I have edge-based traffic counts but not for individual lanes.

**SUMO-version: 1.18.0** 

**operating system: MacOS with M1**

**Comment by m-kro** [comment]
This has already been fixed in the development version (see #13845 ). You can download the updated file here from Github.
