### ISSUE TITLE
Setting different TTC thresholds for different vehicle types

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse-sumo/sumo#13897]
Hello @m-kro ,My goal is to define different TTC thresholds for different vehicle types. I am using the randomtrips tool to create route file. In this regard, I created additional xml that contains vehicle types. I defined thresholds using <param under vType element as shown figure below.
![image](https://github.com/eclipse-sumo/sumo/assets/79362739/10d9a273-4140-464f-9d95-7c5092e99783)

There is no error while running simulation files. However, at the end of simulation, there is no  output  file regarding to SSM results. Can you help me with this problem? Thank you,regards.

**Comment by m-kro** [comment]
You have to define the SSM params as child elements of the vType element. Have a look at the [example XML](https://sumo.dlr.de/docs/Simulation/Output/SSM_Device.html) in our documentation.

**Comment by mehmetnedimyavuz** [comment]
Thank you.
