### ISSUE TITLE
Custom lane change model modification error

### ISSUE THREAD

**Issue by huyanlei123** [eclipse-sumo/sumo#13905]
Error reported after modifying the custom lane changing model according to the official website   "Error: Unknown lane change model 'AL2023' when parsing vType 'CarA'Quitting (on error)."

**Comment by m-kro** [comment]
Did you follow the steps in the developer docs, especially [this one](https://sumo.dlr.de/docs/Developer/How_To/Lane-Changing_Model.html#registering_the_model_name_as_possible_value)?

**Comment by huyanlei123** [comment]
I referenced https://sumo.dlr.de/docs/Developer/How_To/Lane-Changing_Model.html. 
But I don't quite understand how to operate this step"Using Custom Parameters via TraCI"

**Comment by huyanlei123** [comment]
I have not changed any parameters of SL2015, but if I copy and change the model name, an error will appear

**Comment by m-kro** [comment]
So did you register the model name as mentioned in the docs ("Registering the model name as possible value")?

**Comment by huyanlei123** [comment]
I have added my model parameters here as follows：“”
   // al2023 (extension of lc2013)
        std::set<SumoXMLAttr> al2023Params = lc2013Params;
        al2023Params.insert(SUMO_ATTR_LCA_PUSHY);
        al2023Params.insert(SUMO_ATTR_LCA_PUSHYGAP);
        al2023Params.insert(SUMO_ATTR_LCA_SUBLANE_PARAM);
        al2023Params.insert(SUMO_ATTR_LCA_IMPATIENCE);
        al2023Params.insert(SUMO_ATTR_LCA_TIME_TO_IMPATIENCE);
        al2023Params.insert(SUMO_ATTR_LCA_ACCEL_LAT);
        al2023Params.insert(SUMO_ATTR_LCA_TURN_ALIGNMENT_DISTANCE);
        al2023Params.insert(SUMO_ATTR_LCA_LANE_DISCIPLINE);
        allowedLCModelAttrs[LaneChangeModel::AL2023] = sl2015Params;
But my problem still hasn't been solved

**Comment by m-kro** [comment]
Please check that the laneChangeModel attribute string from the route input really matches the internal model name. Pay attention to whether there are (not displayed) control characters and which encoding is used.
