### ISSUE TITLE
Sumo Opposite direction overtake or travel on opposite road.

### ISSUE THREAD

**Issue by MoazzamAliSE** [eclipse-sumo/sumo#13900]
Sumo Gui / Netedit

Sir, I am building a scenario in sumo gui/ netedit.
I have applied many ways but all in vain.
Please guide me on how to achieve this .
as i want that I have a 4 lane road .
and i had blocked 2 road which are on left side , and i want that the vehicles should go from opposite road, but i have enabled the opposite.guess  but the vehicle also stopped their .These yellow vehicles are also stopped here but they should go from opposite road and continue their journey.
as it is a small thing , If you helped me i will be very thankful to you. 
![image](https://github.com/eclipse-sumo/sumo/assets/102206806/4203ca08-242e-4515-a778-8ca056470137)

**Comment by m-kro** [comment]
The opposite lane has to be defined explicitly (see the [doc](https://sumo.dlr.de/docs/Simulation/OppositeDirectionDriving.html)). Did you set the "opposite" attribute for the inner lane(s)?

**Comment by MoazzamAliSE** [comment]
Yes sir I have applied to use the opposite attribute as the vehicles which
are going from left to right are ok and on the same road/ lane the vehicle
should go from right to left but i could not manage how to do this.
Also
yes sir i have applied all things to do this as it would overtake in one
way road but all in vain ..
Can you create a 5 min video and send me please..
I will be very thankful to you...


and one more thing.. as the latitude and longitude values , i got by using
Traci Api . Can you tell me if there is any other device information which
I can get from this.
also how can i use this as Vanet

**Comment by m-kro** [comment]
It seems overtaking through the opposite edge is limited to [emergency vehicles](https://sumo.dlr.de/docs/Simulation/Emergency.html#vehicle_class_emergency) if the forward edge has more lanes. This was hard to find in the documentation, so I added a reference on the [opposite direction driving](https://sumo.dlr.de/docs/Simulation/OppositeDirectionDriving.html) page.
