### ISSUE TITLE
 the modifications of Krauß-model

### ISSUE THREAD

**Issue by JJ-passion** [eclipse-sumo/sumo#13917]
Hello, the description of Krauß-model is "the Krauß-model with some modifications which is the default model used in SUMO". Could you please tell me what specific content has been modified in carFollowing-Krauss. Since I am not a C++ user, is there any relevant literature introduction?

**Comment by m-kro** [comment]
I fear there is no such documentation. You can find some comments across the [source code](https://github.com/eclipse-sumo/sumo/blob/main/src/microsim/cfmodels/MSCFModel_Krauss.cpp), but no clear summary.
