### ISSUE TITLE
about dijkstra

### ISSUE THREAD

**Issue by Clown1206** [eclipse-sumo/sumo#13914]
Add your issue description here.
If I use the Dijkstra algorithm in sumocfg, does the vehicle travel the shortest distance？
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by m-kro** [comment]
By default, the travel time is used as edge weight in routing, not the distance. In order to use distance, you can load custom edge weights or modify the network (see the[ docs](https://sumo.dlr.de/docs/Simulation/Routing.html#routing_by_distance)).
