### ISSUE TITLE
combining `net`, `tll` and `add`

### ISSUE THREAD

**Issue by govin08** [eclipse-sumo/sumo#13911]
I have three files
- `sumo.net.xml`
- `sumo.tll.xml`
- `waut.add.xml`

I want to open the first file, with the remaining file applied.
What should I type in cmd?
(Either just opening, or saving as a new net file are both OK)

Maybe, documentation has it, but I can't find.

**Comment by m-kro** [comment]
You can first open the network in netedit and then load additional files (`sumo.tll.xml` and `waut.add.xml` are probably of this type) using the menu `File > Additionals and Shapes > Load Additionals...`. If you want to have a look at the network in sumo-gui you can call it like this:
`sumo-gui -n sumo.net.xml -a "sumo.tll.xml,waut.add.xml"`

**Comment by govin08** [comment]
> You can first open the network in netedit and then load additional files (`sumo.tll.xml` and `waut.add.xml` are probably of this type) using the menu `File > Additionals and Shapes > Load Additionals...`. If you want to have a look at the network in sumo-gui you can call it like this: `sumo-gui -n sumo.net.xml -a "sumo.tll.xml,waut.add.xml"`

Thanks, but it works only partially.

<About your netedit solution>

I opened (double-clicked) `sumo.net.xml` and then pressed `Ctrl + A` (equivalent to `File > Additionals and Shapes > Load Additionals`) Then, I can see only `waut.add.xml` file. After filtering `XML files`, I can select both of the `sumo.tll.xml` and `waut.add.xml` files. Message window says
- `Loading of additional file sucessfully: path\sumo.tll.xml`
- `Loading of additional file sucessfully: path\waut.add.xml`
indicating that the files are added properly.

But, when I click a junction in `netedt`, the junction has no program ID (it only has the default program ID 0) or TTL names although I set the programs and TTL names at `sumo.tll.xml`.

<About your CLI solution>
`sumo-gui -n sumo.net.xml -a "sumo.tll.xml,waut.add.xml"` works. But I don't want to simulate (use GUI) since it has no vehicles yet. Is there any CLI command that make one file (combine) out of this three files?

**Comment by govin08** [comment]
> You can first open the network in netedit and then load additional files (`sumo.tll.xml` and `waut.add.xml` are probably of this type) using the menu `File > Additionals and Shapes > Load Additionals...`. If you want to have a look at the network in sumo-gui you can call it like this: `sumo-gui -n sumo.net.xml -a "sumo.tll.xml,waut.add.xml"`

I finally found solution : 

`netedit -s sumo.net.xml -i sumo.tll.xml`

Thanks for your previous reply.
