### ISSUE TITLE
about trip files

### ISSUE THREAD

**Issue by Clown1206** [eclipse-sumo/sumo#13915]
Add your issue description here.
Can sumo generate trip files that start and end with network nodes
*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.16
**operating system:**
win 10

**Comment by m-kro** [comment]
Sumo can use trip files which use junctions as start or end point, if that was the question (see [docs](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#routing_between_junctions)). However trip files generated by SUMO tools usually use edges.
