### ISSUE TITLE
bug: vehicles clashed in queues in front of the parking line

### ISSUE THREAD

**Issue by Sirius-1110** [eclipse-sumo/sumo#13928]
As it's shows in the picture below, vehicles clashed in queues in front of the parking line, It looks like the problem is caused by the vehicles changing lane while stopping for a green light.
![image](https://github.com/eclipse-sumo/sumo/assets/55885023/e8f5b485-8fe2-4d86-bc09-b00f2871203e)

I recorded a video file that hopefully helps you find the problem.

https://github.com/eclipse-sumo/sumo/assets/55885023/6ad33dc7-944d-4f6e-8650-58d696289a63

Thanks!

**SUMO version:**
**Eclipse SUMO sumo Version 1.18.0**
**Build features: Windows-10.0.17763 AMD64 MSVC 19.29.30133.0 Release FMI Proj GUI Intl SWIG**

**Windows version: Win10 64-bit 22H2**

**Comment by Sirius-1110** [comment]
Another possibility is that this was not a collision. But as you can see, in sumo-gui, mold crossing occurred (two cars overlapped).
![image](https://github.com/eclipse-sumo/sumo/assets/55885023/da18745c-4442-46b1-af2e-092d1fb2d823)

**Comment by ishuwen** [comment]
I have the same problem as you, i guess the vehicle has already reach the next lane during it changing lane just like what sumo works without sublane model or lanechange duration, the sumo-gui just show the process animation, so the behind vehicle can't recognize it in the original lane
<img width="431" alt="1697007680831" src="https://github.com/eclipse-sumo/sumo/assets/32593963/6a9165ff-2051-4bf9-b730-7c568b10dc4d">

**Comment by Sirius-1110** [comment]
> I have the same problem as you, i guess the vehicle has already reach the next lane during it changing lane just like what sumo works without sublane model or lanechange duration, the sumo-gui just show the process animation, so the behind vehicle can't recognize it in the original lane <img alt="1697007680831" width="431" src="https://user-images.githubusercontent.com/32593963/274173199-6a9165ff-2051-4bf9-b730-7c568b10dc4d.png">

yes, it seems that we have encoutered the same problem...

**Comment by Sirius-1110** [comment]
How can I avoid this happening? Is it feasible to prohibit vehicles from changing lanes while waiting for a green light?

**Comment by m-kro** [comment]
Please let us investigate the issue #13926 . It may well be the same problem. You can limit lane changes to named vehicle classes using the lane attributes `changeLeft` and `changeRight` (accessible in netedit and through netconvert, see [docs](https://sumo.dlr.de/docs/Networks/PlainXML.html#lane_change_restrictions)).

**Comment by Sirius-1110** [comment]
> Please let us investigate the issue #13926 . It may well be the same problem. You can limit lane changes to named vehicle classes using the lane attributes `changeLeft` and `changeRight` (accessible in netedit and through netconvert, see [docs](https://sumo.dlr.de/docs/Networks/PlainXML.html#lane_change_restrictions)).

Thanks for your help!

I found that changing the driver model to IDM improved this problem. And I will try this solution you proposed in my future work!

**Comment by Sirius-1110** [comment]
> > Please let us investigate the issue #13926 . It may well be the same problem. You can limit lane changes to named vehicle classes using the lane attributes `changeLeft` and `changeRight` (accessible in netedit and through netconvert, see [docs](https://sumo.dlr.de/docs/Networks/PlainXML.html#lane_change_restrictions)).
> 
> Thanks for your help!
> 
> I found that changing the driving model to IDM improved this. And I will try this solution you proposed in my future work!

Switching to idm doesn't seem to have any effect, the error still occurs.
![1697602295445_5F32689C-A30C-49cc-8BAD-2C8154694E5E](https://github.com/eclipse-sumo/sumo/assets/55885023/fe71f551-a436-4985-b81d-2eba4afb8315)
