### ISSUE TITLE
Output different if created with sumo-gui

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#13921]
The SSM output file from #13918 contains more & different conflicts if generated in sumo-gui with respect to sumo (1084/978).

**Comment by m-kro** [comment]
Actually other output (tripinfo, detectors) is concerned, too. So the origin may be something else.

**Comment by m-kro** [comment]
The sumocfg had both seed and **--random true** included :-(

**Comment by usamael2000** [comment]
actually it does not matter whether I set the --random to false or true. I got the same behaviour (records for SSM_output.xml when run the simulation for the first time, and empty file when run the simulation again using the reload tab in the top toolbar).

I set the   <random value="false" /> and still the same behaviour I mentioned before
