### ISSUE TITLE
Custom lane change model modification error

### ISSUE THREAD

**Issue by huyanlei123** [eclipse-sumo/sumo#13927]
Error reported after modifying the custom lane changing model according to the official website "Error: Unknown lane change model 'AL2023' when parsing vType 'CarA'Quitting (on error)."

 I have added my model parameters here as follows：“”
// al2023 (extension of lc2013)
std::set al2023Params = lc2013Params;
al2023Params.insert(SUMO_ATTR_LCA_PUSHY);
al2023Params.insert(SUMO_ATTR_LCA_PUSHYGAP);
al2023Params.insert(SUMO_ATTR_LCA_SUBLANE_PARAM);
al2023Params.insert(SUMO_ATTR_LCA_IMPATIENCE);
al2023Params.insert(SUMO_ATTR_LCA_TIME_TO_IMPATIENCE);
al2023Params.insert(SUMO_ATTR_LCA_ACCEL_LAT);
al2023Params.insert(SUMO_ATTR_LCA_TURN_ALIGNMENT_DISTANCE);
al2023Params.insert(SUMO_ATTR_LCA_LANE_DISCIPLINE);
allowedLCModelAttrs[LaneChangeModel::AL2023] = sl2015Params;
But my problem still hasn't been solved

**Comment by huyanlei123** [comment]
"AL2023" is my Custom lane change model

**Comment by m-kro** [comment]
Duplicate of #13905
