### ISSUE TITLE
Netconvert problems with UTF-8 BOM character sequence

### ISSUE THREAD

**Issue by transport111** [eclipse-sumo/sumo#13932]
Hi everyone, 
I have a problem with importing a VISUM net file to the SUMO. I fixed the language problem at first, but now i got so many warning messages, but not this is my biggest problem, I got errors also.  "Error: Too short value line in NODE occurred." This error message is for the node, zone, linktype. I checked none of the rows are empty , even i did not save zones in the net file. Can somebody help me with this problem please? 
Thank you so much.

**Comment by m-kro** [comment]
Could you provide the VISUM file?

**Comment by m-kro** [comment]
Note: There is a problem with the general input parser `LineReader` we have to solve. Shifting the reader forward to a certain character offset does not work (different offset).

**Comment by m-kro** [comment]
@transport111 Your input file has some "invisible" characters at the begin (Hex: EF BB BF) which confuse netconvert. Did you process it after saving in VISUM or did you provide it "as is"?

**Comment by m-kro** [comment]
Actually this is a bug/feature of the internal parser `LineReader`. We will fix that.

**Comment by m-kro** [comment]
@transport111 Please try again with a fresh build from Github source or wait until tomorrow for new [development binaries](https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version). Our parser had some issues with considering the UTF byte order mark (BOM) correctly. Your small example network does not have any edges, though, so the import will fail nonetheless.
