### ISSUE TITLE
Departure time in OD2Trips

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [eclipse-sumo/sumo#13936]
Hello. Thank you very much for providing simulation tools.
I used OD2TRips to generate traffic from the OD matrix and TAZ files. The trip file includes the departure time and its direction. I do not know how to calculate the departure time with this tool.
I tried to read other issues on GitHub but could not find it. 
Thank you very much for replying to me

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by m-kro** [comment]
You can influence the departure time distribution like described in the [docs](https://sumo.dlr.de/docs/Demand/Importing_O/D_Matrices.html#splitting_large_matrices).
