### ISSUE TITLE
dfrouter

### ISSUE THREAD

**Issue by michelmadeira** [eclipse-sumo/sumo#13933]
I´m using dfrouter to alocate the demand.

But the function is creating the 'emitters' output using `<additional>` as a root tag. I had to manually switch to `<routes>`.

Also, in this file, the header `<routeDistribution>` is messing with crescent order of the departure times, giving an error when opening in sumo-gui.

Thank you

**Comment by m-kro** [comment]
Route file elements are permitted in additional files, too. The main difference is that they are read completely before simulation begin whereas route files are read in chunks. Could you please elaborate more about the error you received in sumo-gui?

**Comment by michelmadeira** [comment]
When I try to run the simulation straight ahead with dfrouter outputs (with emitters as additional), I´m getting the message "Invalid reference to route 'origin_to_destination' in route distribution 'route_distribution'.

Even tought this route is defined in the routes.rou generated file.

When I´m passing 'emitters' as a route file in sumo.config I´m receiving a Warning: Warning: Found root element 'additional' in file <FILE> (expected 'routes'). 

And thats okay, but only the first <tripDistribution> is producing trips in the simulation. 
The others Distribution is not (because when the second tag of <tripDistribution> came in the .xml file, the depart times begin from zero, and It´s like the all tripDistribution definition not working in a simultaneous way.

It work when I separate manually the definition.

Thank you for you attention

**Comment by m-kro** [comment]
Yes that's a problem with the loading order unfortunately. Additional files are loaded **before** route files, so that the referenced routes are not known yet. You can load the route definitions in an additional file and before the route distribution.

Regarding the vehicle departures: Does the (very old) issue #1158 describe your problem? dfrouter is not used very much so we didn't put much effort into it recently. It has been created with relatively simple networks in mind, such as motorways with a few on/off ramps.

**Comment by michelmadeira** [comment]
thank you for your response.

I´m pretty new in SUMO and I understand the whole conjuncture of the software.
I´m just doing a deep/wide research on the software, and probably I´ll encounter some more issues.

What you related is nice to be in function webpage.

Yeah, issue #1158 describe the problem. Depart times are sorted indeed, but with `<tripDistribution>` definition in the same level of the vehicles in the .xml file. That what I think that are causing the problem.

I´ll try to load with different order, as you mentioned.

Thank you for you attention
