### ISSUE TITLE
[QUESTION] Use SUMO graphics

### ISSUE THREAD

**Issue by Grufoony** [eclipse-sumo/sumo#13937]
Hi, I've just a question for this project.
I've developed a traffic simulator as a project, you can find it [here](https://github.com/Grufoony/TrafficFlowDynamicsModel).
Could it be possible to produce an output compatible with SUMO's graphics?
The thing I wanna do it's like:
- run the simulation on my framework
- produce an output file with all computed timesteps
- give this file to SUMO
- visualize it

I know that it's possible to customize SUMO models but I'm searching for a faster way.

**Comment by m-kro** [comment]
This is certainly possible. I didn't read about your system in detail but I see two fast options regarding the output file:

- [FCD output](https://sumo.dlr.de/docs/Simulation/Output/FCDOutput.html) file format as an input to [fcdReplay.py](https://github.com/eclipse-sumo/sumo/blob/main/tools/fcdReplay.py) (still missing in the docs) which will create the animation in sumo-gui
- [edge data](https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html#visualization_plotting) for lane/edge-based aggregated measures

Then if you want to customise the appearance in sumo-gui, you can adapt fcdReplay.py to your needs and make use of the [visualisation settings](https://sumo.dlr.de/docs/sumo-gui.html#changing_the_appearancevisualisation_of_the_simulation) in sumo-gui.

**Comment by Grufoony** [comment]
Thank You!
I'll try and I'll let you know.
