### ISSUE TITLE
question about stop the car

### ISSUE THREAD

**Issue by ishuwen** [eclipse-sumo/sumo#13930]
I want to stop the vehicle by TraCI, i try to use setspeed and slowdown, the speed is down to zero, but the car is still active, it lights on, and behind vehicle will brake and wait for a while.
<img width="506" alt="28e749bc3a9d3db9a4c15ffb8c47ce7" src="https://github.com/eclipse-sumo/sumo/assets/32593963/442ac37b-63a8-4c6c-9032-f622f82c2ee3">

but if i right click it and choose stop, the stop vehicle will off the light and the behind vehicle will change lane immediately and overtake it, the behind will recognize it as a barrier and avoid it, this is what i want, i know there is a setstop command in TraCI, but i don't know the stop position on the edge, i just want the vehicle stop in the correct sim time, is there any good way? Thanks.
<img width="559" alt="f4d84c888314ce21179d6b1a338d6dd" src="https://github.com/eclipse-sumo/sumo/assets/32593963/f38fe2da-db07-4e31-8686-9ae4d6baa1bf">
<img width="347" alt="ce4809545637517a5e4e13bc39682f0" src="https://github.com/eclipse-sumo/sumo/assets/32593963/8f7a384b-4472-4150-b4ab-5c1568a7d641">

**SUMO-version:**

**operating system:**

**Comment by m-kro** [comment]
There is no direct way to achieve this currently. 

We have `traci.vehicle.getStopSpeed` which returns the safe speed given a gap but you want the opposite. You could guess a braking distance given the vehicle type characteristics, eventually confirm using `traci.vehicle.getStopSpeed` and then place the stop with `traci.vehicle.setStop`.

**Comment by ishuwen** [comment]
ok thanks, so is there any good way to create a road barrier? i want the behind vehicles could change lane forehead to avoid it but they always brake and wait for a long time.

**Comment by m-kro** [comment]
You can add a new vehicle using `traci.vehicle.add` and give it a stop with `traci.vehicle.setStop` as well to serve as a barrier. Then vehicles should overtake it.

**Comment by ishuwen** [comment]
> You can add a new vehicle using `traci.vehicle.add` and give it a stop with `traci.vehicle.setStop` as well to serve as a barrier. Then vehicles should overtake it.

thanks, it works, but i have another new question, when i stop the vehicle and use moveToXY, it will keep stop if vehicle still in the current edge, and become active again when they are moved to the new edge, anyway i can still keep it stop? or can i set stop by X Y?

**Comment by m-kro** [comment]
Stops always belong to a single edge. They are defined by the lane and a start and end position along the edge. You can still add a new stop on the other edge if you wish.
