### ISSUE TITLE
Combo box for vehicle class selection ignores user input

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#13943]
Several attributes allow a selection of vehicle classes (=permission). In netedit inspection frame, a combo box is used to select from the valid vehicle classes (e.g. "changeLeft", "changeRight"). However, the user input is ignored:

- selecting a value from the list will revert to "ignoring"
- typing a vehicle class name will revert to "ignoring"

Apart from that, for me as a user it is unclear how to select/unselect multiple vehicle classes...

**Comment by palvarezlopez** [comment]
Broken during implementation of new MFXComboBox

**Comment by namdre** [comment]
> Broken during implementation of new MFXComboBox

@palvarezlopez so it was a regression in 1.18.0?
