### ISSUE TITLE
A question about "Abstract Network Generation"

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse-sumo/sumo#13940]
Hello,

"Could you please explain the theoretical science behind "Abstract Network Generation" in SUMO? Do the networks, including  "grid, spider, and random" resemble the networks found in urban cities? Can we simulate any urban city network using the "netgenerate" tool in SUMO? Additionally, could you please provide references based on which such networks are introduced in SUMO?"

Thank you in advance for your help.

**Comment by m-kro** [comment]
Abstract networks are generated mainly for testing purposes. While there are a lot of cities with grid networks (in some publications they are even called Manhattan networks, guess why), there may be less whose networks resemble spider or our "random" networks. If you need a different kind of network topology, you have to look into our import options (e.g. from OpenStreetMap) or draw the network in netedit.

**Comment by amiradavoudi** [comment]
Thank you very much for the help.
