### ISSUE TITLE
can't save the lanechange setting in netedit

### ISSUE THREAD

**Issue by ishuwen** [eclipse-sumo/sumo#13954]
i set the changeRight and changeLeft all to disallowed in netedit, but when i saved and reopen it, the lane set still back to all allowed, how can i save 
the netedit lanechange setting?
<img width="160" alt="1697616891760" src="https://github.com/eclipse-sumo/sumo/assets/32593963/72665340-5fa9-4cef-9d81-fb78f1bdc98e">

**SUMO-version:**
1.18
**operating system:**

**Comment by m-kro** [comment]
We are already noted this ourselves (see #13943) and will make it work.
