### ISSUE TITLE
[Question] configuration for off road driving

### ISSUE THREAD

**Issue by LekYang** [eclipse-sumo/sumo#13950]
Is there a specific configuration for sumo for off road driving? currently, the vehicle disappears when i try to move it outside off the lane. 

Below are the arguments pass to the command line:
traci.start([sumoBinary, "-c", file_pathing,"--delay","0","--collision.action","warn","--collision.stoptime","100","--collision.check-junctions","True","--quit-on-end","True"])

**Comment by m-kro** [comment]
I assume you use `traci.vehicle.moveToXY` ([ref](https://sumo.dlr.de/pydoc/traci._vehicle.html)) to place the vehicle off the road. You can call it with keepRoute=2 to move the vehicle freely.

**Comment by LekYang** [comment]
I think I found my problem. thanks for your help
