### ISSUE TITLE
When there is a lot of subscribed content, traci.simulationStep() takes a long time.

### ISSUE THREAD

**Issue by Sirius-1110** [eclipse-sumo/sumo#13951]
In order to improve the efficiency of reading data, I subscribed to the vehicle data near the following intersections.

`traci.junction.subscribeContext(junction_id, tc.CMD_GET_VEHICLE_VARIABLE, 20000,
                                    [tc.VAR_SPEED, tc.VAR_ACCELERATION, tc.VAR_DISTANCE,
                                     tc.VAR_STOP_ARRIVALDELAY,
                                     tc.VAR_ROAD_ID, tc.VAR_LINE, tc.VAR_PERSON_NUMBER,
                                     tc.VAR_ANGLE, tc.VAR_POSITION, tc.VAR_STOPSTATE,
                                     tc.VAR_TYPE, tc.VAR_LANE_ID, tc.VAR_VEHICLECLASS,
                                     tc.VAR_DEPARTURE])`

However, each time traci.simulationStep() is executed, sumo will take tens of milliseconds or even hundreds of milliseconds. Moreover, as the number of vehicles increases, the time consumption will also increase.
Is there any way to solve this problem? For example, multi-threaded, multi-process, or asynchronous?
Thanks!

**SUMO-version: 1.18**

**operating system: windows10 64-bit**

**Comment by m-kro** [comment]
You can try if using [libsumo ](https://sumo.dlr.de/docs/Libsumo.html) instead makes a difference if you run everything on the same computer. Currently, we do not have implemented concepts for efficient multi-threading. If the time increase is mainly due to more vehicles to simulate, then the time steps will get longer (see [FAQ](https://sumo.dlr.de/docs/FAQ.html#how_fast_can_sumo_run), too)

**Comment by Sirius-1110** [comment]
> You can try if using [libsumo ](https://sumo.dlr.de/docs/Libsumo.html) instead makes a difference if you run everything on the same computer. Currently, we do not have implemented concepts for efficient multi-threading. If the time increase is mainly due to more vehicles to simulate, then the time steps will get longer (see [FAQ](https://sumo.dlr.de/docs/FAQ.html#how_fast_can_sumo_run), too)

Thank you so much!
Also, can libsumo and traci work together? My project now uses traci extensively, and I hope that part of the code using traci will be replaced by libsumo

**Comment by Sirius-1110** [comment]
> You can use libsumo in place of TraCI (with some restrictions as mentioned in the [docs](https://sumo.dlr.de/docs/Libsumo.html)).

Thank you, I just read the content of the link you gave. Then, I wrote two demos using libsumo and traci to compare their running speeds. Indeed, libsumo is faster than traci.
```
import time
import traci
import libsumo

sumo_tsp_on_conf_file = r'tsp.sumocfg'

def __run_by_libsumo():
    # libsumo
    step_counts = 0
    libsumo.start(["sumo", "-c", sumo_tsp_on_conf_file])
    while step_counts < 1000:
        libsumo.simulationStep()
        # traci.connect()
        step_counts += 1
    libsumo.close()

# traci

def run_by_traci():
    step_counts = 0
    traci.start(sumo_cmd, port=9009)
    while step_counts < 1000:
        step_counts += 1
        traci.simulationStep()
    traci.close(False)

```

However, I still have some questions about the following content.
[Limitations](https://sumo.dlr.de/docs/Libsumo.html#limitations)

> libsumo by itself cannot be used to [connect multiple clients to the simulation](https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#controlling_the_same_simulation_from_multiple_clients) (though connecting normal TraCI clients to a libsumo instance is possible)

The meaning of this passage seems to indicate that I can use libsumo and traci to jointly control a sumo instance.
I tried running `traci.simulationStep()` directly after `libsumo.start()`, but something went wrong.
```
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 45, in check
    raise FatalTraCIError("Not connected.")
traci.exceptions.FatalTraCIError: Not connected.
```
However, how could I connecting normal TraCI clients to a libsumo instance with TraCi? Could you provide some examples written in python?

**Comment by Sirius-1110** [comment]
> > You can use libsumo in place of TraCI (with some restrictions as mentioned in the [docs](https://sumo.dlr.de/docs/Libsumo.html)).
> 
> Thank you, I just read the content of the link you gave. Then, I wrote two demos using libsumo and traci to compare their running speeds. Indeed, libsumo is faster than traci.
> 
> ```
> import time
> import traci
> import libsumo
> 
> sumo_tsp_on_conf_file = r'tsp.sumocfg'
> 
> def __run_by_libsumo():
>     # libsumo
>     step_counts = 0
>     libsumo.start(["sumo", "-c", sumo_tsp_on_conf_file])
>     while step_counts < 1000:
>         libsumo.simulationStep()
>         # traci.connect()
>         step_counts += 1
>     libsumo.close()
> 
> 
> def run_by_traci():
>     # traci
>     step_counts = 0
>     traci.start(sumo_cmd, port=9009)
>     while step_counts < 1000:
>         step_counts += 1
>         traci.simulationStep()
>     traci.close(False)
> ```
> 
> However, I still have some questions about the following content. [Limitations](https://sumo.dlr.de/docs/Libsumo.html#limitations)
> 
> > libsumo by itself cannot be used to [connect multiple clients to the simulation](https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#controlling_the_same_simulation_from_multiple_clients) (though connecting normal TraCI clients to a libsumo instance is possible)
> 
> The meaning of this passage seems to indicate that I can use libsumo and traci to jointly control a sumo instance. I tried running `traci.simulationStep()` directly after `libsumo.start()`, but something went wrong.
> 
> ```
>   File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 45, in check
>     raise FatalTraCIError("Not connected.")
> traci.exceptions.FatalTraCIError: Not connected.
> ```
> 
> However, how could I connecting normal TraCI clients to a libsumo instance with TraCi? Could you provide some examples written in python?

**Comment by m-kro** [comment]
@behrisch Could you maybe help regarding libsumo vs. multiple clients?

**Comment by Sirius-1110** [comment]
to add on:
I tried subscribing to vehicle departure times using the following code:
```
libsumo.junction.subscribeContext(junction_id, tc.CMD_GET_VEHICLE_VARIABLE, 2000, [tc.VAR_DEPARTURE])
```
But it seems that the data of `tc.VAR_DEPARTURE` cannot be read.
```
     veh_departure = veh_data[tc.VAR_DEPARTURE]
KeyError: 58
```

**Comment by behrisch** [comment]
May I ask about your use case? Do you have multiple clients connecting to the same sumo instance? Or do you control multiple sumo instances with one client? If you said no to both questions replacing traci with libsumo should be as easy as writing `import libsumo as traci` instead of `import traci` at the top of each file

**Comment by Sirius-1110** [comment]
Sure! 
I have an old project where a lot of the code uses traci. However, I need to add some new features, which requires reducing the time-consuming single-step simulation.
Therefore, I decided to use libsumo instead of `traci`. However, it seems that some data cannot be read directly with `libsumo`. For example, the `VAR_DEPARTURE` example I gave above. Therefore, I would like to ask if I can first start the sumo instance（or process） with libsumo.start(), and then connect the just started instance through traci.connect(), and use traci to read the data (such as `VAR_DEPARTURE`) in the simulation ?

In general,  I only started *one sumo instance*, but I want to start it with libsumo, and then use traci and libsumo to read the data from one sumo instance.
Actually, I'm not quite sure what "multiple clients" means. I'm very sorry for the inconvenience this has caused you!

**Comment by behrisch** [comment]
libsumo.vehicle.getDeparture should definitely work. We have a test for that. Please double check that you use the most recent version 1.18 since this is a quite new function. Can you maybe send an example scenario?
There is really no point in calling traci functions if you use libsumo because they are functionally equivalent.

(With multiple clients I mean multiple (python) scripts connecting to the same sumo instance.)

**Comment by Sirius-1110** [comment]
> libsumo.vehicle.getDeparture should definitely work. We have a test for that. Please double check that you use the most recent version 1.18 since this is a quite new function. Can you maybe send an example scenario? There is really no point in calling traci functions if you use libsumo because they are functionally equivalent.
> 
> (With multiple clients I mean multiple (python) scripts connecting to the same sumo instance.)

Thanks! Both sumo and traci on my computer are version 1.18, but I found that the version of libsumo is lagging behind. I updated libsumo and the problem was solved!

**Comment by Sirius-1110** [comment]
to add on: pedestrians overlap with vehicles when crossing the road.

![image](https://github.com/eclipse-sumo/sumo/assets/55885023/f649c7dd-7784-45d3-9570-01d56516f3a2)

**Comment by behrisch** [comment]
Please open a separate issue for that and add a small example scenario if possible

**Comment by behrisch** [comment]
Since the original issue seems to be solved, I am closing this one
