### ISSUE TITLE
What does "time gap on lane=-1.00" mean?

### ISSUE THREAD

**Issue by woodwm** [eclipse-sumo/sumo#13956]
Add your issue description here.

In the sumo simulation using the default Krauss car following model, sometimes I find that few vehicles cannot accelerate to the maximum speed even there is very large gap. I check the vehivle parameters and find that "time gap on lane [s]" is `-1.00`. What does this means? Is this the reason a vehicle cannot accelerate?

In the following photos, the red vehicle's maximum speed is 33 m/s, but it cannot accelerate to that speed even though it could. Its speed stays around 23 m/s. Sometime the vehicle stay even lower speed when "time gap on lane=-1.00".

![image](https://github.com/eclipse-sumo/sumo/assets/13971199/0368f1a2-83b6-4c27-82a6-5d8e5083a10e)

![image](https://github.com/eclipse-sumo/sumo/assets/13971199/a89ec3dd-9dcd-430c-9e38-35ad9d2f3f96)

![image](https://github.com/eclipse-sumo/sumo/assets/13971199/1744f313-176c-4c2a-85d7-08edf573158a)

*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.18.0
**operating system:**
win 11 x64

**Comment by m-kro** [comment]
`time gap = -1` probably indicates that there is no leader vehicle in front (it is kind of a dummy value). Regarding the speed: You have set/sampled a rather low speed factor which gets applied to the permitted speed on the lane. This restricts the speed of the vehicle, see [docs](https://sumo.dlr.de/docs/Simulation/VehicleSpeed.html#edgelane_speed_and_speedfactor).

**Comment by woodwm** [comment]
@m-kro That is great answer to my question. I agree with you `time gap = -1` indicates no leader vehicle or very large gap. The large gap is because of low speed factor from the sampling of a normal distribution.
