### ISSUE TITLE
Modification to Lane Change and Lane Forwarding motion

### ISSUE THREAD

**Issue by mshah72** [eclipse-sumo/sumo#13952]
I have a question -
I am trying to make changes to the existing Lane Forwarding and Lane Changing motion. How should I do that? Is it possible to do using TraCI or writing a new model under sumo/src/microsim module more advisable?

So in a simulation, I want to simulate some vehicles using the existing SUMO model and some vehicles with my modified model.

Can someone please help me with it? Is it easier to write a new model? 

I am simulating motion planning algorithms and I am new with software level development.

**Comment by m-kro** [comment]
Both options are possible, but I would advise you to start with TraCI. Please take a look at our [TraCI tutorials](https://sumo.dlr.de/docs/Tutorials/index.html#traci_tutorials) if you didn't use it before and look at the TraCI section of our documentation. 

You can find functions to [read](https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html)/[influence](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html) vehicles in sumo. Among others, there are `traci.vehicle.setSpeed` and `traci.vehicle.changeLane` to give you some point to start. We cannot go through the process of developing lane change and car-following models here step by step though.
