### ISSUE TITLE
[question] number of rejected/accepted number of over-takings

### ISSUE THREAD

**Issue by usamael2000** [eclipse-sumo/sumo#13955]
Is there a way to estimate the number of rejected over-takings and the number of accepted over-takings?

**Comment by m-kro** [comment]
Please look closely at `traci.vehicle.getLaneChangeState` ([docs](https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html#extended_retrieval_messages), [reference ](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getLaneChangeState)). It returns information on whether a lane change is possible, a reason if it is not and whether the decision stems from the lane change model or further TraCI commands.

**Comment by usamael2000** [comment]
Is it possible to get all of that in the lane-change file without using traci?

**Comment by m-kro** [comment]
This output is triggered only if the vehicle completed a lane change.
