### ISSUE TITLE
A question about the simulation of toll pricing

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse-sumo/sumo#13958]
Hello,

I want to simulate a city, including several toll stations, for the purpose of the analysis of toll pricing. Actually, I want to locate several toll stations on a network of a city and then assign toll prices to them. 
Which network can I use to locate several toll stations there? As far as I know, SUMO supports grid, spider, and random networks, but I wonder which network is more suitable for this analysis. Is there any reference through which I can get my answer?

Thank you in advance for your help.

**Comment by m-kro** [comment]
You already asked similar questions (#13940 #13941) about abstract networks. In theory, you can use use all abstract network types **AND** any other city network for toll pricing. I don't think there is a general consensus which network is most suitable here.

**Comment by amiradavoudi** [comment]
Thank you for the response.
