### ISSUE TITLE
"Show geometry point indices" option doesn't work

### ISSUE THREAD

**Issue by angelobanse** [eclipse-sumo/sumo#13969]
The "Show geometry point indices" option in the "openGL" viewsettings section does nothing.

This option was introduced in v.1.14.0 - and actually newer worked.

**Comment by angelobanse** [comment]
It works in sumo-gui, but not in netedit

**Comment by palvarezlopez** [comment]
It works, but like a party

https://github.com/user-attachments/assets/11e3a320-dd95-4893-9906-bece2c2aaba2
