### ISSUE TITLE
Question about the "randomTrips.py"

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse-sumo/sumo#13967]
Hello, I read the documentation regarding the randomTrips tool. The documentation says that "It does so by choosing the source and destination edge either uniformly at random or with a modified distribution as described below." I would like to ask: how does the randomTrip tool decide the intermediate edges to reach the destination with default settings? 
Thank you for help, regards.

**Comment by m-kro** [comment]
It is explained in the [docs](https://sumo.dlr.de/docs/Tools/Trip.html#validated_routes_and_trips): randomTrips.py uses duarouter to compute the fastest route for any origin/destination pair using the edge weight (default: free flow travel time).
