### ISSUE TITLE
error in defining a distribution for speedFactor in vType

### ISSUE THREAD

**Issue by woodwm** [eclipse-sumo/sumo#13964]
Add your issue description here.

When I define the speedFactor in vType in `.rou.xml` file, like

```xml
<vType id="hv" speedFactor="norm(1.0, 0.5)"/>
```

I get the following error message in sumo-gui.
```bash
Error: value 'norm(1.0, 0.5)' does not match any member types of the union
```

Similar error happens when I define speedFactor as `normc()` as well. It should be allowed to define the speedFactor as a distribution according to [here](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#defining_a_normal_distribution_for_vehicle_speeds).

*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.18.0
**operating system:**
win 11 x64

**Comment by m-kro** [comment]
The error stems from XML validation. If you don't care, it may work if you disable it with commad line option `-X never`. Otherwise, remove any space character from the speedFactor definition:
```
<vType id="hv" speedFactor="norm(1.0,0.5)"/>
```

**Comment by woodwm** [comment]
@m-kro Then the documentation [here](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#examples) need to be updated.

> Define a vehicle type with high speed deviation and no cut-off
```xml
  <vType id="example2" speedFactor="norm(1.0, 0.5)"/>  
```
