### ISSUE TITLE
Netedit crashes when setting the edge template

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#13971]
- select an edge in inspect mode
- choose "Set edge 'XY' as Template"
- an MFXComboBox message window appears
- netedit chrashes after closing the message window

Screenshot:
![grafik](https://github.com/eclipse-sumo/sumo/assets/33294728/c12c5cc8-ef18-482d-bd86-bdae8536c204)

**Comment by behrisch** [comment]
@palvarezlopez was this an regression?

**Comment by palvarezlopez** [comment]
Yes, due the new ComboBox.
