### ISSUE TITLE
Preserve right of way of when importing roundabouts from OSM

### ISSUE THREAD

**Issue by ambuehll** [eclipse-sumo/sumo#13970]
https://www.openstreetmap.org/way/10559093#map=17/47.43088/8.55116

OSM way is tagged as roundabout. This tag seems to be ignored by netconvert. 

<img width="905" alt="image" src="https://github.com/eclipse-sumo/sumo/assets/48930860/8f9aaa64-7000-46b1-9432-2ac3c1c1be99">

Files attached.
cmd: netconvert --osm-files planet.osm

**SUMO-version:** 1.18.0

[planet.osm.zip](https://github.com/eclipse-sumo/sumo/files/13053626/planet.osm.zip)

**Comment by m-kro** [comment]
Well it is not completely ignored. The tag is read but leads only to one way streets by now. We should try to influence the right of way rules, too, as some approaches get the priority in the current state.

**Comment by m-kro** [comment]
@ambuehll "roundabout" tag values are now considered in the netconvert OSM import and lead to an explicitly defined roundabout in sumo with the appropriate right-of-way.
