### ISSUE TITLE
Why does enlarging a network make an error?

### ISSUE THREAD

**Issue by govin08** [eclipse-sumo/sumo#13978]
1.
Here is `simple.net.xml` ;
![image](https://github.com/eclipse-sumo/sumo/assets/65585738/408ab765-9574-49ac-9844-76aa47f412d4)

The center node, `J0`, has two signal programs encoded in `simple.tll.xml` as follows

```
<tlLogics>

    <tlLogic id="J0" type="static" programID="1" offset="0">
        <phase duration="16" state="gGGgrrgrrgrr"/>
        <phase duration="4"  state="gyygrrgrrgrr"/>
        <phase duration="16" state="grrgGGgrrgrr"/>
        <phase duration="4"  state="grrgyygrrgrr"/>
        <phase duration="16" state="grrgrrgGGgrr"/>
        <phase duration="4"  state="grrgrrgyygrr"/>
        <phase duration="16" state="grrgrrgrrgGG"/>
        <phase duration="4"  state="grrgrrgrrgyy"/>
    </tlLogic>

    <tlLogic id="J0" type="static" programID="2" offset="80">
        <phase duration="26" state="gGggrrgGggrr"/>
        <phase duration="4"  state="gyygrrgyygrr"/>
        <phase duration="26" state="grrgGggrrgGg"/>
        <phase duration="4"  state="grrgyygrrgyy"/>
    </tlLogic>

</tlLogics>
```

With these two files `simple.net.xml` and `simple.tll.xml` I implemented `netedit -s simple.net.xml -i simple.tll.xml` and it works. That is, I can see the network without an error in `netedit` and I can identify two programs in `J0`.

2.
Now I enlarge the network with the file name `simple_2.net.xml`, which looks like

![image](https://github.com/eclipse-sumo/sumo/assets/65585738/5fcdf103-cd93-47f0-b9d3-e681d035a258)

So I created three more nodes and three pairs of edges where the node `J1` becomes an intersection.

With the same tll file as before, I implemented `netedit -s simple.net.xml -i simple.tll.xml`. But it doesn't work, producing following messages :

```
Error: File 'simple_2.net.xml' is not accessible (No such file or directory).
Parsing traffic lights from 'simple.tll.xml' ... 
Error: Cannot load traffic light program for unknown id 'J0', programID '1'.
Error: Cannot load traffic light program for unknown id 'J0', programID '2'.
done.
Error: No nodes loaded.
Error: Failed to build network.
```

Why does it happen and how can I fix it?

- SUMO-version : netedit 1.18.0
- OS : windows 10

**Comment by m-kro** [comment]
The error message should already give you the right hint: Netedit cannot find the net file at the given file path.

**Comment by govin08** [comment]
> The error message should already give you the right hint: Netedit cannot find the net file at the given file path.

My gosh. I did all things in the different folder. Now all is good. Thanks.
