### ISSUE TITLE
question about lane selection

### ISSUE THREAD

**Issue by ishuwen** [eclipse-sumo/sumo#13984]
as it shown that most vehicle are more likely to choose the left lane, it looks weird in the simulation, i have set lcStrategic="0" lcSpeedGain="10" lcKeepRight="0", i know this could be adjust by setting arrival lane, but the downstream road are complicated so i want vehicle could choose lane dynamic, how can i let vehicle move more like real traffic?
<img width="1014" alt="1698218953987" src="https://github.com/eclipse-sumo/sumo/assets/32593963/ed4599d6-daa7-4b9a-94f6-9cd33bed3e79">

**SUMO-version:**
sumo-1.18
**operating system:**
win11

**Comment by m-kro** [comment]
I have build a small network from your screenshot and here vehicles choose both lanes. Did you set other lane change parameters you didn't mention? Anyhow, this is again one of the lane change questions. As a last resort you can change the vehicle type locally if you find a setting which fits your purpose: Place [calibrator](https://sumo.dlr.de/docs/Simulation/Calibrator.html#calibrating_vehicle_types) elements at the borders of the area where different vehicle type settings should be applied and define separate vehicle types for the area.

**Comment by ishuwen** [comment]
Hi, this is my simulation, i haven't defined other lanchange parameters in the rou file, maybe some other setting i dont know, please check it
[fivebyfive.zip](https://github.com/eclipse-sumo/sumo/files/13163502/fivebyfive.zip)

**Comment by m-kro** [comment]
You have there a lefthand driving network. That's why the vehicles prefer driving on the left. If you convert it to righthand driving with netconvert, it will be the other way round. With `lcStrategic="1"` vehicles will use both lanes.

**Comment by ishuwen** [comment]
change to righthand network may let vehicle more likely to driving on the left, but it still not straight in driving, and they will not select the inner lane, i want they could see straight lane as the first selection and they will do the second selection if the straight lane is jam, could it work if i only use lanechange model?
<img width="1172" alt="1698281392621" src="https://github.com/eclipse-sumo/sumo/assets/32593963/6be639c3-6031-498d-bf54-e25896e48621">

**Comment by m-kro** [comment]
By straight lane you mean the left lane?

**Comment by ishuwen** [comment]
> By straight lane you mean the left lane?

yes, i mean the lane that looks straight connect to the former lane

**Comment by ishuwen** [comment]
I think I have the same problem as this #13300 , it looks like the vehicle can not choose lane randomly when pass the junction right？

**Comment by m-kro** [comment]
Yes, that's true.

**Comment by ishuwen** [comment]
is there any way i can let the vehicle choose a specific lane to drive? the default setting is vehicle always drive from lane 0 to lane 0, can i set the vehicle drive always on the biggest lane number? thanks for the answering

**Comment by m-kro** [comment]
You could direct them to a specific lane using [waypoints](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#waypoints).
