### ISSUE TITLE
Check what is doing the function couldChangeLane

### ISSUE THREAD

**Issue by bcoueraud87** [eclipse-sumo/sumo#13981]
What does the function [couldChangeLane](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-couldChangeLane) exactly? Is it checking that the lane change has finished (look into the past) or does it check that the lane change can be achieved (look into the future)?

**Comment by behrisch** [comment]
It refers to the past, I tried to clear this up in the docs
