### ISSUE TITLE
od2trips problem from The Amitran format

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#13988]
Add your issue description here.

*If possible, upload an example that shows your problem.*
![微信截图_20231026094300](https://github.com/eclipse-sumo/sumo/assets/120693511/2df1c1c1-0353-4a6b-868a-333aa7745cf3)

**SUMO-version:**
SUMO v1_18_0+1122-6a98504d485
**operating system:**
Windows 64

**Comment by m-kro** [comment]
You have to provide the files using the option ***--od-amitran-files* if you use the Amitran format.
