### ISSUE TITLE
Trips do not respect "via" loops across start/end edges

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#13987]
At the moment, the start and end edges are disregarded when creating a route from a trip definition independently of eventual loops. A vehicle might want to stop at the final edge, run another loop and stop elsewhere before terminating there. As a result, the created route does not match the stops and throws an error.

**Comment by namdre** [comment]
Is there a test for this?

**Comment by m-kro** [comment]
Now there is one.

**Comment by namdre** [comment]
@m-kro could this problem also affect duarouter?

**Comment by m-kro** [comment]
@namdre duarouter returns the correct route given the trip definition from the test.
