### ISSUE TITLE
Rail car parks next to the rails when receiving a triggered stop

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#13990]
Happens when defining a triggered stop (no duration or departure time) for a rail vehicle:
See the screenshot:
![grafik](https://github.com/eclipse-sumo/sumo/assets/33294728/ba88b327-75c7-4f7c-80c2-5a3488b3f77d)

(Discovered by railway group people)

**Comment by behrisch** [comment]
This is not the proper solution, triggered always implies parking. If this is not wished you can set explicitly parking="false".

 @bcoueraud87 this might be responsible for the bug at the DB side
