### ISSUE TITLE
macOS 13.5.2  (Ventura) : segmentation fault

### ISSUE THREAD

**Issue by Jantalus** [eclipse-sumo/sumo#13997]
Running in CPU: 2,3 GHz Intel Core i7

The segmentation fault (code 76084): 
![image](https://github.com/eclipse-sumo/sumo/assets/37963256/44d7f08d-1b07-4675-9a50-1f003c39cc7f)

**SUMO-version:**  (output when running sumo executable)
Eclipse SUMO sumo Version v1_18_0+2141-9dd26a22ea8
 Build features: Darwin-22.6.0 x86_64 Clang 14.0.3.14030022 Release FMI Proj GUI Intl SWIG GDAL GL2PS Eigen
 Copyright (C) 2001-2023 German Aerospace Center (DLR) and others; https://sumo.dlr.de
 License EPL-2.0: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
 Use --help to get the list of options.

**operating system:**
macOS 13.5.2  (Ventura)

--- 

I already tried reinstalling sumo multiple times (according to the official website), I tried to fix the segfault with the issue mentioned in the web but with no result because the fox brew cask didn't have the indicated line.
Then I downloaded the repo and compiled everything as also indicated by the web, then creating a sym link to the executable generated and the same result.

**Comment by m-kro** [comment]
Can you share your testing scenario (just in case it has to do with it)?

**Comment by Jantalus** [comment]
Sure! 
simple_simulation.sumocfg:
```
<configuration>
    <input>
        <net-file value="simple_network.net.xml"/>
        <route-files value="simple_routes.rou.xml"/>
    </input>

    <time>
        <begin value="0"/>
        <end value="3600"/>
    </time>
</configuration>
```

simple_routes.rou.xml:
```
<routes>
    <vType id="car" accel="2.0" decel="7.5" sigma="0.5" length="4.5" maxSpeed="30"/>
    <route id="route1" edges="edge1"/>

    <vehicle id="vehicle1" type="car" route="route1" depart="0"/>
</routes>
```

simple_network.rou.xml:
```
<net version="1.0">
    <location netOffset="0,0" convBoundary="0.00,0.00,1000.00,0.00" origBoundary="0.00,0.00,1000.00,0.00" projParameter="!"/>
    <edge id="edge1" from="start" to="end" type="a1" shape="0.00,0.00 1000.00,0.00"/>
    <junction id="start" x="0.00" y="0.00" type="internal"/>
    <junction id="end" x="1000.00" y="0.00" type="internal"/>
</net>
```

**Comment by angelobanse** [comment]
I also get this (on Sonoma). It looks like some issue with the network file.

**Comment by Jantalus** [comment]
Dang.. my bad then, do you have some xml example files that work on your pc?

**Comment by m-kro** [comment]
sumo-gui crashes as well on Windows.

**Comment by m-kro** [comment]
@Jantalus You cannot have edges without lanes. Did you write the network file yourself without using netedit/netconvert? This is [extremely discouraged](https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why) as such problems will happen frequently.

**Comment by Jantalus** [comment]
Oh my... sorry for the trouble. 
If you have some tutorial or guideline it would be awesome! (then I'll close the issue)

**Comment by m-kro** [comment]
Well, [here](https://sumo.dlr.de/docs/#network_building) is the section of network building. If you want a proper tutorial, try [this one](https://sumo.dlr.de/docs/Tutorials/Hello_World.html).

**Comment by Jantalus** [comment]
Thanks!
