### ISSUE TITLE
showing the cursor geo-position in Google Maps doesn't work

### ISSUE THREAD

**Issue by angelobanse** [eclipse-sumo/sumo#14007]
GeoHack and OSM work just fine

**Comment by behrisch** [comment]
Works fine for me on Linux but not on Windows. Windows opens a file chooser dialog for whatever reason. Was still working in 1.18.0

**Comment by behrisch** [comment]
has been broken by https://github.com/eclipse-sumo/sumo/commit/24f58b312ec25367c11f098fb03600d7e5f222ba but actually every geo link with a space in a name did not work
