### ISSUE TITLE
"Set breakpoint at " message appearing

### ISSUE THREAD

**Issue by angelobanse** [eclipse-sumo/sumo#14003]
`Set breakpoint at 26.00` or `Set breakpoint at -2.00` appears in the Status Line in netedit when clicking on any of the following lines which start with a number:

```
 Import done:
   653 nodes loaded.
   13 types loaded.
   1131 edges loaded.
```

**Comment by m-kro** [comment]
Cannot reproduce it on my side

**Comment by angelobanse** [comment]
![bug](https://github.com/eclipse-sumo/sumo/assets/16121932/d3bd6fd8-9562-4e91-b4e0-2acc8f485d96)

**Comment by angelobanse** [comment]
> Cannot reproduce it on my side

try clicking a little bit under the last line

**Comment by m-kro** [comment]
OK it doesn't happen with my network, but the relevant code is here:

https://github.com/eclipse-sumo/sumo/blob/d2b4eb5e0e77e37acab61c07d7ae392d0373475b/src/utils/gui/div/GUIMessageWindow.cpp#L167-L186

Do you have " time" somewhere in the messages?

**Comment by m-kro** [comment]
@angelobanse Can you try with rebuild netedit? I added some refactoring in f722bba which might influence the problem.

**Comment by angelobanse** [comment]
@m-kro That just fixed it. Good job!

**Comment by m-kro** [comment]
Actually very sad that apparently we used a string search without checking the result properly for ages...
