### ISSUE TITLE
How to locate a road segment in netedit using latitude and longitude?

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14016]
Add your issue description here.
Hi,recently I have been trying to compare simulation results with real-world data, and I wanted to incorporate E2 detectors for this purpose. However, I found it cumbersome to locate the corresponding road segments on the map. Is there a way to directly locate road segments using latitude and longitude?
*If possible, upload an example that shows your problem.*
![微信图片_20231101213101](https://github.com/eclipse-sumo/sumo/assets/120693511/4a0ca94c-778c-48dc-90d2-1beeed7ca00e)

**SUMO-version:**
netedit v1_18_0+1122-6a98504d485
**operating system:**
Windows 11

**Comment by m-kro** [comment]
You can use the [mapDetectors](https://sumo.dlr.de/docs/Tools/Detector.html#mapdetectorspy) script.
