### ISSUE TITLE
When there are too many vehicles in sumo, the operation becomes sluggish.

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14014]
Add your issue description here.
Hi,I am trying to simulate the traffic flow of a certain scenario for a day, but when there are too many vehicles, the simulation runs very slowly. Besides running SUMO directly through the command line, are there any other ways to improve the speed?

*If possible, upload an example that shows your problem.*
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/ebb08f39-6948-43f6-b07c-8bd428e41323)

**SUMO-version:**
SUMO v1_18_0+1122-6a98504d485
**operating system:**
Windows 11

**Comment by m-kro** [comment]
If you have already cut down your requirements for output, temporal resolution of the simulation and so on to the minimum, then unfortunately not. We haven't advanced much in the process of making really use of multiple threads.
