### ISSUE TITLE
Parameter meaning

### ISSUE THREAD

**Issue by zhoupeng0427** [eclipse-sumo/sumo#14017]
```
<vType id="car" accel="2.6" decel="4.5" sigma="0.5" length="4.5" maxSpeed="55" fuelConsumption="0.2" carFollowModel="CACC" emissionClass="HBEFA3" />
```
This is a type of vehicle, what is the meaning of sigma and the unit of fuelConsumption? Thank you for your answers!

**Comment by m-kro** [comment]
"sigma" denotes the driving imperfection and reduces the acceleration randomly (see [docs](https://sumo.dlr.de/docs/Simulation/VehicleSpeed.html#dawdling)). Unsure where you got the fuelConsumption attribute from, though.
