### ISSUE TITLE
mapDetector problem

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14022]
Add your issue description here.
Hi, last time I asked how to locate and add detectors to a road segment directly using latitude and longitude in Netedit, and you provided the "mapdetector" method. It worked successfully in a small scenario, but when I tried to run it in a larger scenario, an error occurred.
*If possible, upload an example that shows your problem.*
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/77415a09-b416-436e-9ae6-0d9c8a5bebe6)
**SUMO-version:**
SUMO v1_18_0+1122-6a98504d485
**operating system:**
Windows 10

**Comment by nudtdyk** [comment]
Here is the content of the det.csv file:
[det.csv](https://github.com/eclipse-sumo/sumo/files/13239292/det.csv)

**Comment by m-kro** [comment]
Please download the script from [Github](https://raw.githubusercontent.com/eclipse-sumo/sumo/main/tools/detector/mapDetectors.py), as the version included in the last release had a problem with sorting. See #13845 .
