### ISSUE TITLE
"Undo/Redo history" dialog title does not change according to language

### ISSUE THREAD

**Issue by angelobanse** [eclipse-sumo/sumo#14023]
As far as I have noticed, it's the only place where the default text in english always stays, not changing to the desired/selected language.

This happens to me in Windows (system language DE, with `%LANG%` set to `en`) and macOS (system language ES).

**Comment by angelobanse** [comment]
Seems to also affect the viewsettings color schemes

**Comment by behrisch** [comment]
Every object which gets initialized before GNEApplicationWindow::dependentBuild has been called will not get translated. This is for instance true for everything which is already created in the GNEApplicationWindow constructor

**Comment by behrisch** [comment]
I don't think this commit can fix all the problems we saw especially . We should probably rather do the language initialization earlier.
