### ISSUE TITLE
Reading depart time of vehicles through python 

### ISSUE THREAD

**Issue by Nitinyerra** [eclipse-sumo/sumo#14020]
Hi,

I would like to know whether there is a way of how we can read the **depart** time of vehicles from the available traci API's or any other 
rather than using a xml parsing technique on the file that generates the routes and depart related information (.rou.xml)

![image](https://github.com/eclipse-sumo/sumo/assets/140040498/900ba7ed-2607-4921-a52d-a443f567496d)

I am using SUMO 1.15.0 version

**Comment by m-kro** [comment]
You can query the actual departure (after queuing for insertion) during the simulation using `traci.vehicle.getDeparture` (see [docs](https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html#command_0xa4_get_vehicle_variable), [ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getDeparture)). There is no additional utility code for parsing the route input data, though.
