### ISSUE TITLE
How to extract information from OpenStreetMap (OSM) based on an existing TAZ file?

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14035]
Add your issue description here.

Hi, recently I've been trying to generate traffic flow for a scene. Now I have partitioned the scene into TAZs, and here is a part of it:
```
<poly id="430102001000" type="unknown" color="51,128,255" fill="1" layer="-1.00" shape="43140.939657,35280.473422 43033.101800,35286.685007 42913.934751,35283.068315 42862.892253,35281.455807 42805.384198,35278.850831 42626.089001,35270.705056 42490.968883,35263.727849 42426.877093,35261.349559 42389.216825,35264.170015 42327.423883,35271.362490 42312.261273,35261.692897 42312.002942,35259.471781 42309.642928,35259.654904 42306.395645,35260.045219 42300.591983,35260.615450 42303.267679,35277.173926 42318.273794,35368.531300 42331.821386,35458.978123 42334.475235,35476.866398 42334.715441,35480.195667 42334.941157,35484.411457 42336.118636,35502.498400 42336.666434,35511.042401 42336.975856,35516.145210 42340.662961,35572.956895 42341.141549,35579.726250 42352.102237,35654.169215 42355.372574,35676.391639 42358.119406,35700.599605 42363.680386,35750.902114 42364.374404,35804.560142 42365.108235,35855.781347 42347.537039,35963.453625 42303.116840,36103.607940 42295.865967,36126.654882 42240.747983,36272.509283 42474.270515,36266.462559 42661.227851,36261.542067 42669.774513,36261.349504 42762.511568,36259.210804 42801.610637,36258.299696 42932.367011,36255.233635 43286.325099,36246.856634 43291.532033,36246.720491 43291.181208,36244.165280 43278.562507,36139.543698 43272.304847,36042.232719 43270.656349,36017.043713 43268.847095,35935.877317 43275.768142,35867.269028 43278.677661,35839.606563 43279.266850,35833.630586 43280.086983,35825.552339 43280.317927,35823.450068 43281.943614,35808.181207 43290.177267,35749.347781 43290.290009,35748.462869 43297.020054,35691.490229 43299.862173,35673.912489 43305.859155,35637.654802 43309.635993,35611.004201 43313.636529,35582.693485 43332.457382,35447.332283 43333.788490,35438.043134 43334.350401,35433.729393 43334.459506,35433.066113 43356.259340,35277.801703 43358.150576,35264.309633 43357.657838,35264.412383 43351.961376,35264.429640 43349.166851,35261.169212 43140.939657,35280.473422">
        <param key="Name" value="文艺路街道" />
        <param key="gml_id" value="layer_township_pg.32676" />
        <param key="grade" value="4" />
        <param key="layer" value="乡镇" />
    </poly>
``` 
How can I map this XML file onto the OSM map to obtain the number of POIs and building information for a specific TAZ? Are there any existing programs for this purpose currently available?

*If possible, upload an example that shows your problem.*
Here is a program I found from a certain author, but she directly extracted the TAZs from OSM and determined the weights and other information, so the accuracy is not high.
[generateTAZBuildingsFromOSM.txt](https://github.com/eclipse-sumo/sumo/files/13261892/generateTAZBuildingsFromOSM.txt)

**SUMO-version:**
SUMO v1_18_0+1122-6a98504d485
**operating system:**
Windows 10

**Comment by m-kro** [comment]
Polyconvert is not made for exporting the polygons back to some external format. Instead you could create the polygons right away in another software and then import it together with other needed information. [QGIS ](https://qgis.org/en/site/) might be worth looking at for example.

**Comment by angelobanse** [comment]
You could download the OSM map for a certain area (given a boundary or polygon), using our [osmGet.py](https://sumo.dlr.de/docs/Tools/Import/OSM.html#osmgetpy) tool, and later take a look at the downloaded file for the POIS and buldings you are interested.
