### ISSUE TITLE
Could not find vehicle or person '0'.

### ISSUE THREAD

**Issue by kudurupaka-vamshi-krishna** [eclipse-sumo/sumo#14039]
When I am using TraCI to communicate with Unity 3D, but I am getting the following error in SUMO. 

This project I am using: https://github.com/JCP1014/ICG-Project/tree/main

Error: Answered with error to command 0xcc: Could not find the vehicle or person '0'.

**SUMO-version: 1.16.0**

**operating system: 10**

**Comment by m-kro** [comment]
The error message itself is easy to understand I suppose. There is a vehicle "0" defined in the linked sumo scenario departing at t=0. So it probably has already left the network at the time of the TraCI query.
