### ISSUE TITLE
How to make an special car's left tires to be on the left marked line

### ISSUE THREAD

**Issue by harirRzi** [eclipse-sumo/sumo#14030]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
Hello. I define two edges each edge has 3 lanes like the following. 

```
 <edge id="e1" from="1" to="2" priority="2">
        <lane id="e1_0" index="0" speed="13.89" length="1000.00" shape="0.00,-8.00 1000.00,-8.00"/>
        <lane id="e1_1" index="1" speed="13.89" length="1000.00" shape="0.00,-4.80 1000.00,-4.80"/>
        <lane id="e1_2" index="2" speed="13.89" length="1000.00" shape="0.00,-1.60 1000.00,-1.60"/>
    </edge>
```

Now my problem is how can I define one special car's left tires to be for example for 5 time steps on the left marked line and the behaves normal for a few time steps and again back to it previous behavior, putting all its left tires on the left lane marks. I appreciate if anyone can suggest me a solution.

Here is the code using traci to move the vehicle d2 to a specific x and y:

```
def run():

  target_lateral_position = 2.0
  step=0
  while traci.simulation.getMinExpectedNumber()>0:
    traci.simulationStep()
    #print(step)
    
    if step==40:

      if "d2" in traci.vehicle.getIDList():
        #current_lateral_position = int(traci.vehicle.getLateralLanePosition("d2"))
        print('yes')
      else:
        print('No')
      current_lateral_position = traci.vehicle.getLateralLanePosition("d2")
      try:
        pos = traci.vehicle.getPosition("d2")
        print('pos:',pos)
      except traci.TraCIException:
        pass # or do something smarter
      if current_lateral_position < target_lateral_position: 
                #traci.vehicle.getLaneID("d2")
                traci.vehicle.moveToXY("d2", 0,0,
                            traci.vehicle.getLateralLanePosition("d2") + 0.1,
                            traci.vehicle.getLanePosition("d2") + 0.1, 25, 1)

```
But I ger this error at time step=41:

```
  File "/opt/homebrew/opt/sumo/share/sumo/tools/traci/connection.py", line 144, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Could not map vehicle 'd2', distance to road is 153.63.
```

**Comment by m-kro** [comment]
`traci.vehicle.getLateralLanePosition` and `traci.vehicle.getLanePosition` return positions in a local coordinate system of the lane, while `traci.vehicle.moveToXY` requires X/Y coordinates in the global coordinate system. You could try to use `traci.vehicle.moveTo` and `traci.vehicle.setLateralPosition` instead.

**Comment by harirRzi** [comment]
Thank you for your answer. How can I find the right most coordinate of the the current edge that the car is driving?

**Comment by m-kro** [comment]
In the following I assume righthand driving networks. You can get the shape of the rightmost lane (index 0), its width `sumolib.lane.getWidth` and then project the shape center line 1/2 width orthogonally to the right.
