### ISSUE TITLE
Making network out of ordered pairs of points

### ISSUE THREAD

**Issue by govin08** [eclipse-sumo/sumo#14037]
I made a set of ordered pairs of points like

437.59, 566.10
439.35, 418.47
439.35, 301.92
439.35, -1.11
1.76, 562.77
228.50, 563.88
-0.88, 150.96
0.00, 0.00
224.97, -1.11
285.84, 0.00

With these points, I want to make a network.

My previous approach, which is also valid, is to run netedit and to click create edge mode.
After clicking several points (actually, several edges), I set the inspect mode, left click the points, and edit the pos values.
I can do this, but It is not a good way. Can I make any CLI approach?
For example, I could make it out of xml file. Any reference to watch?

Making edges out of these nodes is easy if I use netedit. But before doing that, I want to make the basic structure.

**Comment by m-kro** [comment]
Maybe the [Plain XML](https://sumo.dlr.de/docs/Networks/PlainXML.html) approach works for you? You didn't develop how the points should actually be connected (which with which, are there geometric intermediate points etc).

**Comment by govin08** [comment]
chat GPT solved my issue. I'll close this issue.

Here is the solution from GPT

---

Yes, you can create a SUMO network using a Command Line Interface (CLI) approach by defining the network in an XML file and then using the netconvert tool provided by SUMO to generate the network. Here's a step-by-step guide:

Define Nodes in an XML File:
Create a file named nodes.xml and define your nodes:

xml
Copy code
<nodes>
    <node id="n0" x="437.59" y="566.10" type="priority"/>
    <node id="n1" x="439.35" y="418.47" type="priority"/>
    
</nodes>
Define Edges in an XML File:
Create a file named edges.xml. Here you define the connections between nodes:

xml
Copy code
<edges>
    <edge id="e0" from="n0" to="n1" priority="1" numLanes="1" speed="13.89"/>
    
</edges>
Note: The attributes like priority, numLanes, and speed can be adjusted based on your requirements.

Use netconvert to Generate the Network:
Once you have the nodes.xml and edges.xml files, you can use the netconvert tool to generate the SUMO network:

bash
Copy code
netconvert --node-files=nodes.xml --edge-files=edges.xml -o myNetwork.net.xml
Visualize in SUMO or netedit:
You can now open myNetwork.net.xml in SUMO or netedit to visualize and further edit the network if needed.

References:

[SUMO netconvert](https://sumo.dlr.de/docs/netconvert.html)
[SUMO Node and Edge Definition](https://sumo.dlr.de/docs/Networks/Building_Networks_from_own_XML-descriptions.html)
By following this approach, you can automate the process of creating SUMO networks without manually clicking and editing in netedit.

**Comment by govin08** [comment]
> Maybe the [Plain XML](https://sumo.dlr.de/docs/Networks/PlainXML.html) approach works for you? You didn't develop how the points should actually be connected (which with which, are there geometric intermediate points etc).

Yeah it helps. I could make plain xml file with a simple syntax. And then I could make edges out of it. Thanks! I'll close this issue.
