### ISSUE TITLE
How to disable emergency braking for a vehicle in sumo?

### ISSUE THREAD

**Issue by Ambica2022** [eclipse-sumo/sumo#14044]
Hi,

I would like to control the decelaration of my vehicle through the code.....but sumo automatically making emergency braking for that vehicle.How can I disable the default emergency braking for a vehicle.

Thanks in advance.

Regards,
Ambica

*If possible, upload an example that shows your problem.*

<img width="366" alt="2023-11-07 10-38-18_Ubuntu-Focal Fossa  Running  - Oracle VM VirtualBox" src="https://github.com/eclipse-sumo/sumo/assets/116077953/b760a8d0-0f50-4f08-93b2-137e61ce94f4">

Ubuntu-Focal Fossa

**Comment by m-kro** [comment]
Well there is probably a reason the vehicle brakes. Do you want the vehicle not to brake at all or at a lesser degree?

- You can lower the emergency deceleration using the vehicle type attribute `emergencyDecel` (see [docs](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#available_vehicle_attributes))
- If you want the vehicle to disregard various rules regarding its speed, you can change the vehicle's [speed mode](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#speed_mode_0xb3) in [TraCI](https://sumo.dlr.de/docs/TraCI.html) using the `traci.vehicle.setSpeedMode` function

**Comment by Ambica2022** [comment]
Thank you for the information.
I want to keep the default decel/emergencyDecel values as suggested here https://sumo.dlr.de/docs/Vehicle_Type_Parameter_Defaults.html
But when the vehicle in front of my ego vehicle has stopped.....my ego vehicle should not stop and keep moving.....so that I can decelerate it/apply brake according to my code.

**Comment by m-kro** [comment]
Then the way to go is setting a different speed mode in TraCI (see the links in the previous answer). Set the speed mode to (int) 32 to disable all checks.
