### ISSUE TITLE
This system has no OpenGL support 

### ISSUE THREAD

**Issue by tranvary** [eclipse-sumo/sumo#14046]
I use VNC Viewer to connect to a Ubuntu server and try to run SUMO,but fail.The error message is: This system has no OpenGL support.However,when I run SUMO on this Ubuntu server directly(not through VNC Viewer or SSH),no error is reported and it runs successfully.How to fix this problem?Thank you.

**Comment by behrisch** [comment]
Please try a different viewer and also have a look at https://stackoverflow.com/questions/51705471/current-state-and-solutions-for-opengl-over-windows-remote. I don't think we can do much from the SUMO side here.
