### ISSUE TITLE
How to get the number of times a car has stopped during a simulation in real time?

### ISSUE THREAD

**Issue by zhangm269** [eclipse-sumo/sumo#14048]
Hello, I recently ran into a problem where I need to get the number of times a car has stopped during a simulation **in real time.** 

So is it possible to get the number of times a car has stopped **in a certain lane** or the number of times it has stopped during the whole simulation in real time **via traci**?

**SUMO-version:**
1.17.0
**operating system:**
Windows

**Comment by m-kro** [comment]
There is no direct way but you can get to your result by combining a few TraCI calls. I suppose you intend v=0 when you say _stopped_ without necessarily letting somebody board the vehicle?

- you can monitor the vehicles on a lane using `traci.lane.getLastStepVehicleIDs` and then proceed to query their speeds using `traci.vehicle.getSpeed` (you can use [subscription](https://sumo.dlr.de/docs/TraCI.html#subscriptions) in this context)
- you can monitor a specific vehicle directly with `traci.vehicle.getSpeed` if you do not care about the lane

**Comment by zhangm269** [comment]
Thanks for your help! Is there some code or video tutorial on how to use Object Context Subscription? I'm still a little confused about [the official documentation](https://sumo.dlr.de/docs/TraCI/Object_Context_Subscription.html).

**Comment by m-kro** [comment]
You can have a look in our test examples (see [docs](https://sumo.dlr.de/docs/Tutorials/index.html#using_examples_from_the_test_suite)). Here is [one](https://sumo.dlr.de/extractTest.php?path=complex/traci/ContextSubscriptionFilters/lanesUpDownDistance) example to download which uses context subscription.
