### ISSUE TITLE
Getting names of a node

### ISSUE THREAD

**Issue by govin08** [eclipse-sumo/sumo#14042]
In `sumolib`, I want to do something like this

```
net = sumolib.net.readNet('../../../sumo/demo/demo.net.xml')
nodes = net.getNodes()
node_ids = [node.getID() for node in nodes]
node_names = [node.getName() for node in nodes]
```
But it doesn't work. (the last line)

After doing

```
node = nodes[0]
dir(node)
```

I get

```
['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_coord',
 '_foes',
 '_fringe',
 '_id',
 '_incLanes',
 '_incoming',
 '_intLanes',
 '_outgoing',
 '_params',
 '_prohibits',
 '_shape',
 '_shape3D',
 '_type',
 'addIncoming',
 'addOutgoing',
 'areFoes',
 'forbids',
 'getConnections',
 'getCoord',
 'getCoord3D',
 'getFringe',
 'getID',
 'getIncoming',
 'getInternal',
 'getLinkIndex',
 'getNeighboringNodes',
 'getOutgoing',
 'getParam',
 'getParams',
 'getShape',
 'getShape3D',
 'getType',
 'setFoes',
 'setParam',
 'setShape']
```

So it seems to be impossible to use method like `getName`. But is there any alternative way to achieve this?

P.S. I think  `'__getattribute__',` would be related to what I want to do.
But after

```
node = nodes[0]
node.__getattribute__(1)
```

I'm stuck. I don't know what argument to input.

**Comment by m-kro** [comment]
As you already noticed, this hasn't been implemented in sumolib. The name attribute is optional anyway. 
It should not be too difficult to implement it yourself in sumolib. if you want, you can then contribute and we may integrate your changes.

**Comment by govin08** [comment]
> As you already noticed, this hasn't been implemented in sumolib. The name attribute is optional anyway. It should not be too difficult to implement it yourself in sumolib. if you want, you can then contribute and we may integrate your changes.

My programming skill is quite poor. But if you let me know how to pull-request (this is the first time for me to pull-request to the 'big' module like sumolib.), I'll try. Hm. Should I fork the sumo library and modify the library to get sumo enabled to functionality like 'getName', which will be an attribute (or method?) of `sumolib.net.node`?

**Comment by m-kro** [comment]
General steps to do for the pull request:

- fork sumo repository in your Github account (see [Github help](https://docs.github.com/en/get-started/quickstart/fork-a-repo))
- [synchronise ](https://git-scm.com/docs/git-fetch) your local copy of this fork
- you'll find the sumolib files at ./tools/sumolib/net
- integrate your changes in the python code
- commit locally (with option --signoff)
- upload the changes to Github ([git push](https://git-scm.com/docs/git-push))
- start the [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on Github
- register at Eclipse to accept the agreement for contributing to SUMO

**Comment by govin08** [comment]
> General steps to do for the pull request:
> 
> * fork sumo repository in your Github account (see [Github help](https://docs.github.com/en/get-started/quickstart/fork-a-repo))
> * [synchronise ](https://git-scm.com/docs/git-fetch) your local copy of this fork
> * you'll find the sumolib files at ./tools/sumolib/net
> * integrate your changes in the python code
> * commit locally (with option --signoff)
> * upload the changes to Github ([git push](https://git-scm.com/docs/git-push))
> * start the [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on Github
> * register at Eclipse to accept the agreement for contributing to SUMO

Thanks. I'll try. But I can't guarantee that I could do this.

**Comment by govin08** [comment]
> General steps to do for the pull request:
> 
> * fork sumo repository in your Github account (see [Github help](https://docs.github.com/en/get-started/quickstart/fork-a-repo))
> * [synchronise ](https://git-scm.com/docs/git-fetch) your local copy of this fork
> * you'll find the sumolib files at ./tools/sumolib/net
> * integrate your changes in the python code
> * commit locally (with option --signoff)
> * upload the changes to Github ([git push](https://git-scm.com/docs/git-push))
> * start the [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on Github
> * register at Eclipse to accept the agreement for contributing to SUMO

I've tried, but unsuccessfully. Here is what I've done.

- I've forked the repository to [my github account](https://github.com/govin08/sumo)
- I've synchronized : `git remote add upstream https://github.com/eclipse/sumo.git`

Then, I modified the `C:\github\sumo\tools\sumolib\net\node.py` as follows

```
    def __init__(self, id, type, coord, incLanes, intLanes=None, name=None):
        self._id = id
        self._type = type
        self._coord = coord
        self._incoming = []
        self._outgoing = []
        self._foes = {}
        self._prohibits = {}
        self._incLanes = incLanes
        self._intLanes = intLanes
        self._shape3D = None
        self._shape = None
        self._fringe = None
        self._params = {}
        self._selected = False
        self._name = name

(omit)

    def getName(self):
        """Returns the name of the node"""
        return self._name
```

I think I've done right, but after I make an `ipynb` file in `C:\github\test_sumo\.ipynb` with the following codes

```
import sys
sys.path.insert(0, 'C:\\github\\sumo\\tools\\sumolib')
from sumolib.net.node import Node

node_with_name = Node(id="5790", type="traffic_light", coord=(1816.19, 1836.81), incLanes=["903_0", "903_1"], name="N")

print(node_with_name.getName())
```

It makes an error : 

```
recovering from ImportError 'No module named 'xml.etree'; 'xml' is not a package'
Traceback (most recent call last):
  File "c:/Github/test_sumo/.py", line 3, in <module>
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\sumolib\__init__.py", line 27, in <module>
    from . import files, net, output, sensors, shapes, statistics, fpdiff  # noqa
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\sumolib\net\__init__.py", line 34, in <module>
    from xml.sax import handler, parse
  File "C:\github\sumo\tools\sumolib\xml.py", line 32, in <module>
    import xml.etree.ElementTree as ET
ModuleNotFoundError: No module named 'xml.etree'; 'xml' is not a package
```

Things seems to be so easy although it is not that easy.

Surely I have to deal something with `xml` or something : It's clear ; net file is of the form `xml` And I think I have to do something more beside modifying code in `node.py`. Can you let me know?

**Comment by m-kro** [comment]
The net file is read in `./tools/sumolib/net/__init__.py` (NetReader class).

**Comment by govin08** [comment]
> NetReader

I'll make a new issue.
