### ISSUE TITLE
getLaneChangeState() returns unexpected value (1073741824,1073741824) for all vehicles

### ISSUE THREAD

**Issue by honly0301** [eclipse-sumo/sumo#14051]
## Environment

- **SUMO Version**: 1.18.0
- **Operating System**: Windows 11
- **Python Version**: 3.9.12

## Issue Description

I am encountering an issue where `traci.vehicle.getLaneChangeState()` consistently returns the value `(1073741824, 1073741824)` for all vehicles throughout the simulation, regardless of the lane change maneuvers they are performing. According to the documentation, I expect a bitmask indicating the lane change state for each vehicle, but the value I receive seems to exceed the documented range of states.

### Steps to Reproduce
1. Run a SUMO simulation using a Python script with traci to control and monitor the simulation.
2. Call `traci.vehicle.getLaneChangeState(veh_id, 0)` for each vehicle at each simulation step.
3. Observe that the return value is always `(1073741824, 1073741824)`.

### Expected behavior
I would expect a tuple representing the bitmask of the lane change states according to the documentation, where each bit represents a different lane change state (e.g., 2^0 for stay, 2^1 for left, and so on).

### Actual Behavior
No matter the context or the actual behavior of the vehicles, `getLaneChangeState()` returns `(1073741824, 1073741824)`.

### Code
Here's the relevant part of the code I am using to call `getLaneChangeState()`:

```python
      for step in range(max_steps):
            traci.simulationStep()
            # 收集车辆数据
            for veh_id in traci.vehicle.getIDList():
                veh_type = traci.vehicle.getTypeID(veh_id)
                speed = traci.vehicle.getSpeed(veh_id)
                lane_change = traci.vehicle.getLaneChangeState(veh_id, 0)
                ttc = -1  # 初始化TTC为缺省值
                try:
                    front_id, front_dist = traci.vehicle.getLeader(veh_id)
                    if speed - traci.vehicle.getSpeed(front_id) > 0:
                        ttc = front_dist / (speed - traci.vehicle.getSpeed(front_id) + 0.001)  # 计算TTC
                except TypeError:
                    pass
                # 将车辆数据添加到DataFrame中，包括TTC的缺省值
                vehicle_data = pd.concat([vehicle_data, pd.DataFrame({
                "Time": [step],
                "Vehicle_ID": [veh_id],
                "Vehicle_Type": [veh_type],
                "Speed": [speed],
                "Lane_Change": [lane_change],
                "TTC": [ttc]
            })], ignore_index=True)
            # 收集车道平均速度数据
            lane_speeds = [(lane_id, traci.lane.getLastStepMeanSpeed(lane_id)) for lane_id in traci.lane.getIDList()]
            lane_data = pd.concat([lane_data, pd.DataFrame([{"Time": step, "Lane_ID": lane_id, "Lane_Avg_Speed": speed} for lane_id, speed in lane_speeds])], ignore_index=True)

        # 断开与traci的连接并停止SUMO仿真
        traci.close()
```
### Possible Solutions or Ideas
I have checked the SUMO documentation and forums but did not find any references to such high values for the lane change state. I suspect this might be either a documentation issue where new lane change states have been added without being documented or an internal bug.

### Supporting Information
```
log> c:\users\11\desktop\untitled0.py(90)run()
     88                 veh_type = traci.vehicle.getTypeID(veh_id)
     89                 speed = traci.vehicle.getSpeed(veh_id)
1--> 90                 lane_change = traci.vehicle.getLaneChangeState(veh_id, 0)
     91                 ttc = -1  # 初始化TTC为缺省值
     92                 try:


veh_id
Out  [2]: 'f_0.0'

traci.vehicle.getTypeID(veh_id)
Out  [3]: 'Car'

traci.vehicle.getSpeed(veh_id)
Out  [4]: 26.8

traci.vehicle.getLaneChangeState(veh_id, 0)
Out  [5]: (1073741824, 1073741824)
```
[untitled0.txt](https://github.com/eclipse-sumo/sumo/files/13298941/untitled0.txt)

**Comment by m-kro** [comment]
The documentation has been updated regarding the [lane change state](https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html#change_lane_information_0x13).

**Comment by honly0301** [comment]
Thank you for the update on the documentation. 

I noticed that the getLaneChangeState() function now includes a bit with the value 2^30 labeled as "undetermined." Could you please provide more information about what scenarios might cause this "undetermined" state to occur? Understanding this will help me interpret the results of the function correctly in the context of my simulations.

**Comment by m-kro** [comment]
A return value of `(1073741824, 1073741824)` happens with vehicles off the road and when no other reason/context has been determined (the initial condition when vehicles are inserted).

**Comment by honly0301** [comment]
Based on the images displayed in the GUI, I am confident that at least some vehicles have been correctly inserted into the road network and have completed normal lane changes. However, traci.vehicle.getLaneChangeState() returns the value (1073741824, 1073741824) for all vehicles at every simulation step. (Attached is a screenshot for your reference.)
![image](https://github.com/eclipse-sumo/sumo/assets/51837310/47fb2ad9-2664-4c8b-8e62-11485e9fc34d)

Enclosed are the network and route configuration files I'm using, should you need them for further investigation.
[freewaymerge.zip](https://github.com/eclipse-sumo/sumo/files/13305252/freewaymerge.zip)

**Comment by m-kro** [comment]
You only check the lane change state for staying on the lane. You'll get different state values for changing lane to left/right. As there is no target lane a vehicle absolutely has to go to follow its route, that seems to be a reasonable return value.

**Comment by honly0301** [comment]
I apologize for my delayed response. After conducting additional tests across various network and route configurations, I have come to believe that there might indeed be bugs within the `getLaneChangeState()` function. No matter the simulation context or vehicle dynamics, this function persistently returns the same value: `(1073741824, 1073741824)`. This behavior remains consistent across different scenarios, which leads me to suspect an underlying issue in the function's implementation.

Additionally, I have concerns regarding the `getLaneChangeStatePretty()` function. In my observations, it only seems to return empty arrays, irrespective of the simulation conditions. This unexpected behavior further suggests potential anomalies in the lane change state reporting mechanisms of the software.

I would recommend testing this function in any network to observe if this issue can be replicated. If needed, I am willing to provide my network and route configuration files for further investigation.

Your prompt attention to this matter and any guidance you can provide would be greatly appreciated.

**Comment by honly0301** [comment]
Yes, it stays the same and still returns (1073741824, 1073741824) in both cases.

```
veh_id
Out  [5]: 'f_0.0'

traci.vehicle.getSpeed(veh_id)
Out  [6]: 26.8

traci.vehicle.getLaneChangeState(veh_id, 1)
Out  [7]: (1073741824, 1073741824)

traci.vehicle.getLaneChangeState(veh_id, -1)
Out  [8]: (1073741824, 1073741824)

traci.vehicle.getLaneChangeState(veh_id, 0)
Out  [9]: (1073741824, 1073741824)
```

**Comment by honly0301** [comment]
I tried to replace this function with `FCDOutput`, which works but is inefficient and cumbersome.

**Comment by m-kro** [comment]
This is my output script used with your freeway scenario:
```
import os
import sys
from datetime import datetime
SUMO_HOME = os.environ.get('SUMO_HOME',
                           os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
sys.path.append(os.path.join(SUMO_HOME, 'tools'))
import traci
import sumolib  # noqa

traci.start(["sumo", "-c", "freewaymerge.sumocfg"])
step = 0
while traci.simulation.getMinExpectedNumber() > 0:
    vehIDs = traci.vehicle.getIDList()
    print("step %d:" % step)
    for vehID in vehIDs:
        changeState = traci.vehicle.getLaneChangeState(vehID, -1)
        print("\tstep %d veh %s changeState %s" % (step, vehID, str(changeState)))
    traci.simulationStep()
    step += 1
traci.close()
```

I get values different from (1073741824, 1073741824) starting from the second time step.
