### ISSUE TITLE
Error when starting traci from python

### ISSUE THREAD

**Issue by cyty98** [eclipse-sumo/sumo#14050]
Add your issue description here.

I am trying to start traci simulation through python on windows, everything worked well until this evening, and I suddenly started to receive this error:

Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).

Now I cannot even run the simplest sumocfg file (like the box route provided in examples\sumo\simple_nets). Yet all sumocfg file worked normally when double clicking and running on sumo-gui.
I tried importing traci from sumo directory and pip install traci, none of them worked.
I am using these codes:

```
import traci
from sumolib import checkBinary

if __name__ == '__main__':
    sumoBinary = checkBinary('sumo')
    sumocfg_path = 'example/test.sumocfg'
    sumocmd = [sumoBinary, '-c', sumocfg_path]
    traci.start(sumocmd)
```

How can I get further information on the error? Is there any log file where I can know what happened?

*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.16.0 (also tried 1.19.0, the same error)
**operating system:**
Windows 10

**Comment by m-kro** [comment]
This error message indicates that sumo-gui crashed while communicating with a TraCI client. Some topics to investigate:

- Is the relative path to the sumocfg file right?
- Please ensure the imported modules (traci, sumolib) and the binaries (sumo, sumo-gui) belong to the same release.

**Comment by cyty98** [comment]
I am sure the path of sumocfg is right, since if I run the file with sumo-gui, the window pops with the scene out normally and crashes when I press Run button. Could you please tell me how can I check the consistency of modules and binaries?

**Comment by cyty98** [comment]
Here's some further info, according to the printed message, traci , sumolib and sumo executables are in the same directory,
![output](https://github.com/eclipse-sumo/sumo/assets/141025598/c096d10f-fff3-463d-9243-ffd286057ba4)

**Comment by m-kro** [comment]
That's very mysterious... So if the sumocfg is nothing special or even from our examples and the sumo-gui invoked by double click is the same which is called by TraCI, then it becomes difficult to track the error.
The only option I see is to try self-compiled sumo-guiD (debug version) and then possibly give us the stack trace of a hypothetic error. Do you know how to proceed in this case? We have some [instructions](https://sumo.dlr.de/docs/Installing/Windows_Build.html) about building SUMO in Windows in our docs.

**Comment by cyty98** [comment]
I found the problem: I should add traci.simulationStep() and traci.close(). In this case when I press Run, the simulation will run 100 steps and reach to an end. 
It was a foolish mistake...   
![51c90476fd3ad9d2ffd3cad0fe8a125](https://github.com/eclipse-sumo/sumo/assets/141025598/cb0af695-0c16-4df4-a02c-e301d565597e)
