### ISSUE TITLE
In what situation should I use Libtraci python API and in what situation should I use Traci python API?

### ISSUE THREAD

**Issue by wgy8283335** [eclipse-sumo/sumo#14068]
There are two Python APIs in sumo: Libtraci and Traci.
In what situation should I use Libtraci python API and in what situation should I use Traci python API?

**Comment by behrisch** [comment]
The pure python traci should always be your first choice. There are only very few special cases where you should use libtraci in python. We use it basically to test the C++ API easily and make sure the interface is stable, see #13283 .
