### ISSUE TITLE
How to add restricted areas in sumo?

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14062]
Add your issue description here.
I have already defined the TAZ in the road network, and now I want to simulate the impact of a major event on traffic. Therefore, I want to set up several restricted areas. Vehicles should not be able to pass through these restricted areas, and they should choose alternative routes to reach their destination based on an algorithm. How can I achieve this?Can the time periods for restricted areas be set as well?

If possible, upload an example that shows your problem.
The restricted road sections are shown in the following figure:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/d0806257-2b32-45be-a497-f734b2b68a27)

SUMO-version:
SUMO v1_18_0+1122-6a98504d485
operating system:
Windows 10

**Comment by m-kro** [comment]
This can be done by changing the forbidding the access to some lanes to (all) vehicle classes. Please read the [docs](https://sumo.dlr.de/docs/Simulation/VehiclePermissions.html) to get an overview of the methods how to do this. If the event happens after simulation start, you can use TraCI to change the permissions of all lanes leading to the area to be closed to traffic.

**Comment by m-kro** [comment]
Here is an [example](https://sumo.dlr.de/extractTest.php?path=complex/traci/lane/lane) scenario where the lane permissions are changed by TraCI. You can find [TraCI tutorials](https://sumo.dlr.de/docs/Tutorials/index.html#traci_tutorials) in our docs.

**Comment by nudtdyk** [comment]
Vielen Dank!
