### ISSUE TITLE
Traffic light controlled roundabout

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse-sumo/sumo#14061]
I have a traffic light controlled rounabout network. I created network in Netedit tool. I would like to put 4 traffic signal as shown figure below. While trying to put traffic light at position labeled as 1,it give an error like below. I cannot solve the cause of this problem. Thanks for your help. Regards.
![soru](https://github.com/eclipse-sumo/sumo/assets/79362739/8e06b7cf-8077-42ba-b232-fb0919ff5cdc)

![image](https://github.com/eclipse-sumo/sumo/assets/79362739/b054a943-236e-4020-b238-f311eecd5146)

**Comment by palvarezlopez** [comment]
hi @mehmetnedimyavuz. The problem is that the junctions doesn't have connections. To solve it, go to inspect mode, right click over every junction, and select "reset connections". Then you can create traffic lights.

Regards
