### ISSUE TITLE
Can I use get vehicles' info more efficiently in a simulation？

### ISSUE THREAD

**Issue by jinyuxinjinyuxin** [eclipse-sumo/sumo#14069]
I need to obtain the latitude and longitude information of all vehicles in each simulation step, but I cannot find a function to retrieve information for all vehicles. Using traci.vehicle.getPosition(vehID) in a loop is not an efficient method.

**Comment by jinyuxinjinyuxin** [comment]
x,y = traci.vehicle.getPosition(vehID)
    #lng,lat = traci.simulation.convertGeo(x,y,fromGeo=True) # 直接traci转换转不过去
    lon,lat = convertLonLat2XY(net,x,y)
    angle = round(traci.vehicle.getAngle(vehID),2)
    vtype = traci.vehicle.getTypeID(vehID)
    speed = round(traci.vehicle.getSpeed(vehID),2)
    pos = round(traci.vehicle.getLanePosition(vehID),2)
    lane = traci.vehicle.getLaneID(vehID)
    slope = round(traci.vehicle.getSlope(vehID),2)
    
I also need to obtain attributes other than just the position, is it possible to directly return a class? Calling methods one by one still seems to be inefficient.

**Comment by behrisch** [comment]
Please use [subscriptions](https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#subscriptions). This way you can retrieve multliple values for multiple vehicles at once.

**Comment by jinyuxinjinyuxin** [comment]
@behrisch 

import traci
import traci.constants as tc

traci.start(["sumo", "-c", "my.sumocfg"])
traci.vehicle.subscribe(vehID, (tc.VAR_ROAD_ID, tc.VAR_LANEPOSITION))
print(traci.vehicle.getSubscriptionResults(vehID))
for step in range(3):
    print("step", step)
    traci.simulationStep()
    print(traci.vehicle.getSubscriptionResults(vehID))
traci.close()

I have watched the demo; however, the traci.vehicle.getSubscriptionResults function also requires a vehID. This means that I have to use a loop to retrieve results using this function instead of fetching multiple values for multiple vehicles at once. If I have thousands of vehicles, I will have to use many loops. In this situation, is libsumo the only way to meet my needs?
