### ISSUE TITLE
pedestrians two stage crossing

### ISSUE THREAD

**Issue by way-thu** [eclipse-sumo/sumo#14063]
Sorry to bother everybody, i want create a safety island or refugee island to simulate pedestrians two stage crossing the intersection, the safety island is just like the following picture shows (the yellow part), but i do not know how to create it by sumo, hope someone can provide me some help.
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/45b32359-2732-40b6-9924-7c32ac80d24f)
**SUMO-version:1.18

**operating system:windows

**Comment by m-kro** [comment]
Try to build separate pedestrian crossings across the incoming and the outgoing lanes. SUMO should then connect the pedestrian crossings with which could be assimilated to your "safety island".

**Comment by zlh212** [comment]
> @m-kro Much appreciate， i have solved it， thanks for your help!
I also encountered a similar problem, can you ask me how you solved it

**Comment by namdre** [comment]
In netedit, use crossing-mode,
1. click the junction
2. click the first part of the road to be crossed, press enter
3. click the other part (other direction) of the road to be crossed, press enter
