### ISSUE TITLE
od2trips problem

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14072]
Add your issue description here.
Hi, recently I generated TAZ zones based on the shp file and tried to create an O/D matrix in Amitran format. However, I found some issues when using od2trips.

*If possible, upload an example that shows your problem.*
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/e4a1b0d4-d659-49bb-a933-50c69a1c04f6)

After running od2trips, an empty file was generated as shown in the screenshot below:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/5dcc2d9c-7fbe-4795-835b-4005aebc656a)

I have packed the relevant files into a zip file. Could you please help me take a look and see where the problem lies?
[test.zip](https://github.com/eclipse-sumo/sumo/files/13344168/test.zip)

SUMO-version:
SUMO v1_18_0+1122-6a98504d485
operating system:
Windows 10

**Comment by m-kro** [comment]
You actually reference TAZ IDs in your OD matrix which are not defined in the TAZ file. Please check this (missing origin OR destination will give you an error, both missing = warning).

**Comment by nudtdyk** [comment]
Vielen Dank für den Hinweis. Ich habe gerade bemerkt, dass die IDs tatsächlich einen zusätzlichen Leerzeichen enthalten.
