### ISSUE TITLE
Creating Opposite lane with the same edge

### ISSUE THREAD

**Issue by prashant-prashan** [eclipse-sumo/sumo#14074]
Add your issue description here.
I want to create an opposite lane for a pedestrian. creating a two-way lane with the edge going in unidirectional only.
![Screenshot 2023-11-14 170954](https://github.com/eclipse-sumo/sumo/assets/112210445/085a19af-df09-485d-8a69-31e393a06bf0)

*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.18.0
**operating system:**
Windows

**Comment by m-kro** [comment]
You still have to create an edge for the opposite direction which only allows pedestrians (see [docs](https://sumo.dlr.de/docs/Simulation/Pedestrians.html#generating_a_network_with_sidewalks)).
