### ISSUE TITLE
How to draw Macroscopic Fundamental Diagram (MFD) in SUMO?

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14078]
Add your issue description here.

Hi, recently I came across an article in Nature Communication 《Understanding congestion propagation by combining percolation theory with the macroscopic fundamental diagram》that used SUMO to run actual traffic data and obtain the relationship between Macroscopic Fundamental Diagram (MFD) and the percolation theory. They also provided corresponding files. However, I am not sure how to plot the results.

*If possible, upload an example that shows your problem.*
Here are some of the plots it includes:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/cce036d0-c027-40a5-8c96-8647ac0686d7)
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/445de19b-eb03-4439-9278-20e68deb30a9)

Here are the relevant files obtained after running it, but I'm not sure where to start:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/37cb3f5d-e5fc-40a5-82e3-e7b39c546291)

SUMO-version:
SUMO v1_18_0+1122-6a98504d485
operating system:
Windows 10

**Comment by m-kro** [comment]
It is unclear whether the published sumocfg files were used for generating the MFD input. I would assume they do not necessarily contain the exact option used for the figures. You can try [EdgeData](https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html) output and average over the network (see the [docs](https://sumo.dlr.de/docs/Tutorials/FundamentalDiagram.html#introduction) about the fundamental diagram). Then you have data points to plot like shown in the publication.

**Comment by nudtdyk** [comment]
Vielen Dank!
