### ISSUE TITLE
How to convert the output of polyconvert to the standard TAZ format?

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14070]
Add your issue description here.

Recently, I used polyconvert to project a shapefile onto the SUMO road network to create traffic analysis zones (TAZ), but it is slightly different from the standard TAZ format.

*If possible, upload an example that shows your problem.*
The conversion result is shown in the following picture:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/b447cd6a-d2e2-42b7-aa93-5b1bf36920ba)
But the standard TAZ file format should be like this:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/d6a5497f-ea6f-4e73-80ed-b6169e3e2a2d)
How can I convert the first format into the second standard format?Thank you

SUMO-version:
SUMO v1_18_0+1122-6a98504d485
operating system:
Windows 10

**Comment by behrisch** [comment]
Please use [edgesInDistricty.py](https://sumo.dlr.de/docs/Tools/District.html#edgesindistrictspy).
