### ISSUE TITLE
cropping a huge network in rectangular fashion

### ISSUE THREAD

**Issue by govin08** [eclipse-sumo/sumo#14085]
I have a network named `\[path]\test.net.xml`. It has

```
<location netOffset="-322525.46,-4125416.86" convBoundary="0.00,0.00,20747.58,26836.42"
origBoundary="126.995306,37.260145,127.228470,37.502638"
projParameter="+proj=utm +zone=52 +ellps=WGS84 +datum=WGS84 +units=m +no_defs">
```

as its `location` tag, so that the xy-coordinate is computed in longitude-latitude fashion.

I want to crop this big network to have a small portion, where the portion is of rectangular shape. The rectangular can be defined by

```
{
    "max_lng": 127.117747,
    "min_lng": 127.107801,
    "max_lat": 37.36989,
    "min_lat": 37.361945
}
```

I want to enter a command like

```
netconvert --net-file test.net.xml --bounding-box 127.107801,37.361945, 127.117747, 37.36989 --plain-output-prefix demo
```

to crop the network  (in the `[path]`, using windows CMD). I have confirmed that the above code (from chatGPT) doesn't work. I know [where the reference is](https://sumo.dlr.de/docs/netconvert.html), but I don't really know how to do it. Can you help me?

- SUMO-version : I'm using netedit 1.18.0
- OS : windows 10

**Comment by m-kro** [comment]
You can use the selection mechanism in netedit and then delete the unwanted parts. There is no command line option to remove parts of the network. If you do not know exactly where to cut, you can import a polygon with geographic coordinates using polyconvert (e.g. from ESRI shp format).

**Comment by govin08** [comment]
> You can use the selection mechanism in netedit and then delete the unwanted parts. There is no command line option to remove parts of the network. If you do not know exactly where to cut, you can import a polygon with geographic coordinates using polyconvert (e.g. from ESRI shp format).

Thanks. I used  Select mode and shift to get the network that I wanted as you said. I appreciate as always.

By the way, can I choose "question label"? when I publish a new issue? You or other people always add the question label. Sorry for viewing that, I ask if I can choose the 'button'.

**Comment by m-kro** [comment]
@govin08 Labeling is done by people with committer rights. You don't need to care about it.

**Comment by govin08** [comment]
Thank you.
