### ISSUE TITLE
Is there any way to build a "two way single lane"? 

### ISSUE THREAD

**Issue by Karl131127** [eclipse-sumo/sumo#14083]
I wanna build a lane whose width only allows one car to pass, but the lane should allow cas to pass from two diections.
like:
![image](https://github.com/eclipse-sumo/sumo/assets/122240456/e30aac0f-dd1b-41f6-909d-d5140d4f989d)

**SUMO-version:**

**operating system:**windows

**Comment by m-kro** [comment]
In SUMO we call this case a bidirectional edge. This can be build with two edges which connect the same nodes (one per direction) which share the exact same geometry. You can design one in netedit by:

- create an edge
- select it and choose "add reverse direction" from the context menu
- set spreadType for both to "center"
- adapt the shape coordinates of one of them to match the shape of the other
- activate "bidi" checkbox

**Comment by Karl131127** [comment]
Thanks! I solved this problem

**Comment by DinoCappe** [comment]
How can I do this with netconvert? I'm ok in setting the spreadType but I don't get how I can specify the bidi mode

**Comment by namdre** [comment]
when in doubt, edit in netedit and than save as "plain-xml" to see how the values are encoded.

**Comment by namdre** [comment]
You may encounter issues because of #10941
A safe way to regulate access to the bidi-edge is https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#phase_layout_alternateoneway
