### ISSUE TITLE
Traci control problem

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14087]
Add your issue description here.
Hi, recently I've been trying to use Traci to control road restrictions and make vehicles change routes, but I've encountered some issues.

*If possible, upload an example that shows your problem.*
As you can see, the vehicle arrived early at the upcoming closed section of the road, and after the closure, it couldn't travel along the planned route, so it was removed. How can we solve this problem so that vehicles can find new routes to reach their destinations?
![1700190883163](https://github.com/eclipse-sumo/sumo/assets/120693511/034985a1-b037-46cb-96fc-f532eb2a8c10)
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/7431dca3-931a-4c36-a9a4-6d8ce81746f0)

**SUMO-version:**
SUMO 1.19.0
**operating system:**
Windows 10

**Comment by nudtdyk** [comment]
Another issue is: I set certain roads to be closed during a specific time period in the code, but after that time period, they still remain closed. How can I make them automatically open after that time period? I found a relatively simple method to restore the open status using if-else statements, as shown below:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/c5ed576a-7e4d-4228-bf72-fb337742d0bc)

**Comment by behrisch** [comment]
Concerning the first problem. Did you try the methods mentioned here: https://sumo.dlr.de/docs/Demand/Automatic_Routing.html and here https://sumo.dlr.de/docs/Simulation/Rerouter.html? In general it may of course still happen that the vehicle is already near to the street to be closed and any rerouting attempt comes too late. This is unavoidable (also in reality ;-)) One possibility here is to allow turnarounds at every possible entry but this cannot be done dynamically.

**Comment by behrisch** [comment]
> Another issue is: I set certain roads to be closed during a specific time period in the code, but after that time period, they still remain closed. How can I make them automatically open after that time period? I found a relatively simple method to restore the open status using if-else statements, as shown below:

There is nothing wrong with that method. What did you try where you expected the street to reopen automatically?

**Comment by nudtdyk** [comment]
> Concerning the first problem. Did you try the methods mentioned here: https://sumo.dlr.de/docs/Demand/Automatic_Routing.html and here https://sumo.dlr.de/docs/Simulation/Rerouter.html? In general it may of course still happen that the vehicle is already near to the street to be closed and any rerouting attempt comes too late. This is unavoidable (also in reality ;-)) One possibility here is to allow turnarounds at every possible entry but this cannot be done dynamically.

Thank you, I will try it later.

**Comment by nudtdyk** [comment]
> > Another issue is: I set certain roads to be closed during a specific time period in the code, but after that time period, they still remain closed. How can I make them automatically open after that time period? I found a relatively simple method to restore the open status using if-else statements, as shown below:
> 
> There is nothing wrong with that method. What did you try where you expected the street to reopen automatically?

Okay, I just want to know if there is anthoer option. Thanks!

**Comment by m-kro** [comment]
If the opening/closing times don't depend on your TraCI script, you can use [Rerouters](https://sumo.dlr.de/docs/Simulation/Rerouter.html#closing_a_street) as well. They allow to close and reopen edges or lanes at given times.

**Comment by nudtdyk** [comment]
> If the opening/closing times don't depend on your TraCI script, you can use [Rerouters](https://sumo.dlr.de/docs/Simulation/Rerouter.html#closing_a_street) as well. They allow to close and reopen edges or lanes at given times.

Thank you for suggestion!

**Comment by nudtdyk** [comment]
> If the opening/closing times don't depend on your TraCI script, you can use [Rerouters](https://sumo.dlr.de/docs/Simulation/Rerouter.html#closing_a_street) as well. They allow to close and reopen edges or lanes at given times.

I am wondering if I can use traci to retrieve the vehicles on these restricted lanes and then use traci to change the trajectories of these vehicles.Because the methods you provided require defining the relevant information in advance.

**Comment by m-kro** [comment]
See `traci.lane.getLastStepVehicleIDs` ([ref](https://sumo.dlr.de/pydoc/traci._lane.html#LaneDomain-getLastStepVehicleIDs)) and `traci.vehicle.rerouteEffort` ([ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-rerouteEffort)) or `traci.vehicle.setRoute` ([ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setRoute)).

**Comment by nudtdyk** [comment]
Hi, recently I've been using mpl_dump_onNet.py for visualization. I followed the instructions and performed the operations, but encountered the following error:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/8f9682e9-6383-4145-8638-9440568e725d)

![image](https://github.com/eclipse-sumo/sumo/assets/120693511/6f23d078-eef8-4b1c-876a-e8f8eeb30887)

**Comment by behrisch** [comment]
> Hi, recently I've been using mpl_dump_onNet.py for visualization.
This script is deprecated. Please use rather https://sumo.dlr.de/docs/Tools/Visualization.html#plot_net_dumppy

And please open a new issue for new topics
