### ISSUE TITLE
flows in the route file `*.rou.xml` have to be ordered by `begin` time

### ISSUE THREAD

**Issue by woodwm** [eclipse-sumo/sumo#14088]
Add your issue description here.

I find that flows in the route file `*.rou.xml` have to be ordered by `begin` time. Otherwise, some flows will not be generated.

For example:
In the following flow definitions, no flows are generated from E4 (ramp) to E3 from 0 to 450. This behaviour is not documented. Please either add documentation or change the way of loading flows.

```xml
    <flow id="f_20" type="t_0" begin="0.00" departSpeed="avg" from="E1" to="E3" end="400.00" vehsPerHour="1500.00"/>
    <flow id="f_21" type="t_0" begin="400.00" departSpeed="avg" from="E1" to="E3" end="800.00" vehsPerHour="800.00"/>
    <flow id="f_10" type="t_0" begin="0.00" departSpeed="avg" from="E4" to="E3" end="300.00" vehsPerHour="600.00"/>
    <flow id="f_11" type="t_0" begin="300.00" departSpeed="avg" from="E4" to="E3" end="450.00" vehsPerHour="1000.00"/>
    <flow id="f_12" type="t_0" begin="450.00" departSpeed="avg" from="E4" to="E3" end="800.00" vehsPerHour="500.00"/>
```

All simulation files are attached as well.
[flow_sumo.zip](https://github.com/eclipse-sumo/sumo/files/13386916/flow_sumo.zip)

*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.19.0
**operating system:**
Win 11

**Comment by behrisch** [comment]
I agree that the documentation is not very prominent but it is there: https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#routes and there is even a warning being emitted. We could still improve on the docs though.

**Comment by woodwm** [comment]
Thanks for pointing the place of documentation that is related. I never pay attention to there as I though I am definiting flows rather than routes. 

Can we add an order function when loading the route file? This reduces the chances of making errors for the users.

**Comment by behrisch** [comment]
The simple workaround is to load the routes as additional files (use -a instead of -r). Then the order is not checked but the drawback is that the whole file is loaded into memory at once.

**Comment by woodwm** [comment]
@behrisch I do not understand why an order function in the preprocessing break the purpose of loading files incrementally **during running**. How much memory does it cost for an order function? The current issue is that sumo strongly requries the input flow to be ordered and silently ignore some that are not. The users may get wrong results without warning and not sure how to fix this. 

Why cannot make the users' life simpler by adding an order function after checking?

**Comment by woodwm** [comment]
@m-kro I think this issue is closed too early as @behrisch clearly mentioned that the documentation need to be refined to better address this issue.

**Comment by behrisch** [comment]
> I do not understand why an order function in the preprocessing breaks the purpose of loading files incrementally **during running**. How much memory does it cost for an order function?

@woodwm 
An order function needs to load the whole file because the first vehicle to start may be the last in the file. You could also do the sorting out of memory but you will at least need to read the file completely. That's not what we want.

> One way is to create a new route file after runing the order function and load it incrementally during the simulation. The current issue is that sumo strongly requries the input flow to be ordered and silently ignores those that are not. The users may get wrong results without warning and not sure how to fix this.

The route file may easily have several Gigabyte. We do not want to fill the user's disk arbitrarily. And it is not silently ignored. There is a warning being emitted. The user can easily run sort_routes.py herself.

> Why cannot make the users' life simpler by adding an order function after checking?

If you still think it is useful and does not incur performance penalties you are free to submit a pull request and we can discuss it directly with your code.
