### ISSUE TITLE
About sublane model

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse-sumo/sumo#14084]
Hello, Is it possible to apply sublane model on a part of road network? For example, I would like to apply only inside the roundabout while vehicles are turning, not the leg of an intersection. Thank you for help, regards.

**Comment by m-kro** [comment]
No, this is not possible.

**Comment by zlh212** [comment]
That is to say, in a simulation, you can only choose to open the sub-lane mode or not. It cannot be partially opened, for example, only in bike lanes. Is that right?

**Comment by zlh212** [comment]
> No, this is not possible.

That is to say, in a simulation, you can only choose to open the sub-lane mode or not. It cannot be partially opened, for example, only in bike lanes. Is that right?

**Comment by namdre** [comment]
correct

Am Mi., 24. Juli 2024 um 04:53 Uhr schrieb zlh212 ***@***.***
