### ISSUE TITLE
Why did the vehicles stop suddenly even though the light was green?

### ISSUE THREAD

**Issue by suruotong** [eclipse-sumo/sumo#14080]
Hi, I encounter a weird phenomenon that the cars can not go through the intersection when the traffic light keep green, just as the picture below. And If I move the first car in the queue, the remaining cars can move normally. But at the same time, left-turning cars can move, cars in the middle and right lane cannot. I use the reinforcement learning for training, this situation happens about 4 or 5 times in 100 episodes.  And the remaining episodes is active normally. How to sovle it? Thank you in advance!
 File( (the network, routes and config files)  is in the attachment.
[sumo_rou.zip](https://github.com/eclipse-sumo/sumo/files/13365670/sumo_rou.zip)
![スクリーンショット 2023-11-15 232931](https://github.com/eclipse-sumo/sumo/assets/108106431/8751745c-f5c5-4350-99e1-f4fb6d7670a7)
![スクリーンショット 2023-11-15 232946](https://github.com/eclipse-sumo/sumo/assets/108106431/a7455463-0379-4aaa-98cd-3188e686ee8d)

**Comment by suruotong** [comment]
> I cannot reproduce it. Which SUMO version do you use? Do you use a random seed you didn't put into to the download files?

I'm sorry, I don't understand what you cannot being able to reproduce？The netfile or the phenomenon that I mentioned above？

**Comment by m-kro** [comment]
When I run the simulation, the cars leave the intersection as planned.

**Comment by suruotong** [comment]
> When I run the simulation, the cars leave the intersection as planned.

[Normal-Crossing.zip](https://github.com/eclipse-sumo/sumo/files/13374048/Normal-Crossing.zip)
Simply run the 'simulation_normal_new.py' file, and the sumo-gui will appear automatically. Keep in mind that this phenomenon may not occur in every episode, so you'll need to be patient and wait for it. Thank you very much for your assistance.

**Comment by suruotong** [comment]
> When I run the simulation, the cars leave the intersection as planned.

I've observed that the issue of stopping occurs when the 'Show current route' of the frontmost vehicle in each of the four directions doesn't match its actual position. Interestingly, when I select the first vehicle in the waiting queue in any direction and click 'remove,' all vehicles resume normal movement. However, I'm unsure about the underlying relationship between these actions.

**Comment by suruotong** [comment]
> When I run the simulation, the cars leave the intersection as planned.

"I've observed that the issue of stopping occurs when the 'Show current route' of the frontmost vehicle in each of the four directions doesn't match its actual position. Interestingly, when I select the first vehicle in the waiting queue in any direction and click 'remove,' all vehicles resume normal movement. However, I'm unsure about the underlying relationship between these actions."
![2](https://github.com/eclipse-sumo/sumo/assets/108106431/6ed9363d-bb4a-480f-a92e-17b1e60d99af)
![1](https://github.com/eclipse-sumo/sumo/assets/108106431/a20b5dca-3d46-47cf-8e80-63d991ff2899)

**Comment by suruotong** [comment]
> When I run the simulation, the cars leave the intersection as planned.

I've observed that the issue of stopping occurs when the 'Show current route' of the frontmost vehicle in each of the four directions doesn't match its actual position. Interestingly, when I select the first vehicle in the waiting queue in any direction and click 'remove,' all vehicles resume normal movement. However, I'm unsure about the underlying relationship between these actions.
![2](https://github.com/eclipse-sumo/sumo/assets/108106431/f529e95a-03ca-4d7c-bf6d-4928f2a750a2)
![1](https://github.com/eclipse-sumo/sumo/assets/108106431/24625df5-d8d9-473e-b56f-52add8a151fe)

**Comment by m-kro** [comment]
This has nothing to do with it. Routes are edge-based and are displayed on the first lane (rightmost in righthand networks, leftmost in lefthand networks).

**Comment by m-kro** [comment]
@suruotong I won't run your complex RL system. Please give me a ready-to-use case where I can spot the problem.
You do not seem to use any internal SUMO random seed features but you create the traffic demand depending on random numbers as well as issue TraCI commands. This means I'll need the scenario files where the problem happens as well as a log of the TraCI commands (see [docs](https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands) on how to generate these) from the same simulation run.

**Comment by m-kro** [comment]
@suruotong No. Please follow the link to read how to get one. You have to define a TraCI log file path inside the `traci.start` command. And please provide only the files of the simulation where the vehicles block the intersection.

**Comment by suruotong** [comment]
@m-kro Thank you very much for your explanation. Is this it?
[traci.zip](https://github.com/eclipse-sumo/sumo/files/13389135/traci.zip)

**Comment by m-kro** [comment]
Now I can reproduce it. Thank you.

**Comment by m-kro** [comment]
@suruotong I'm currently working on finding the problem origin and solving it. Additionally I have seen your GUI settings file includes the setting `personQuality="5"` which crashes sumo-gui. Did you edit the file and especially this setting manually? I cannot remember we have ever had 5 different person drawing styles...

**Comment by m-kro** [comment]
The vehicles stopped because they waited for others from the orthogonal direction to clear the intersection. A practical solution would be to increase the intergreen time to give vehicles more time. Still sumo has a problem when multiple vehicles drive into the intersection and get blocked by others.

**Comment by m-kro** [comment]
@namdre Can you give some advice where to look in the code when it comes to blocked vehicles inside the intersection?

**Comment by namdre** [comment]
- using 'select foes' (vehicle context menu) + color-by-selection helps to spot cycles in the foe relationship
- reacting to junction foes is handled in MSLink::getLeaderInfo and MSVehicle::isLeader. It helps to enable debugging macro DEBUG_PLAN_MOVE_LEADERINFO in MSVehicle and then selecting the vehicle being suspected of erroneous behaviour in the simulation.

**Comment by namdre** [comment]
The source of the problem lies in invalid right-of-way rules encoded in the network. Rebuilding the network with netconvert version 1.19 or later should fix this.  For reference, the change that causes the network difference is de55a6d2f70d37243a12ab48d660fe0af279b0fd (#13542)
