### ISSUE TITLE
Traci problem

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14086]
Add your issue description here.
Hi, recently I've been using Traci and Python for joint simulation, but I've encountered some minor issues. Could you please help take a look at the reasons?

*If possible, upload an example that shows your problem.*
I tried to restrict the passage of vehicles in the road network, and found that all vehicles were of the default type when I queried them. However, when I executed the command, it gave me an error as follows:
![161a09aff1550ab003b81c36007a96b](https://github.com/eclipse-sumo/sumo/assets/120693511/86d5e81e-f809-461a-aaba-b79dd3c1d1c9)

SUMO-version:
SUMO v1_18_0+1122-6a98504d485
operating system:
Windows 10

**Comment by m-kro** [comment]
Vehicle types and vehicle classes are separate concepts. "DEFAULT_VEHTYPE" is the default vehicle type, which belongs to the vehicle class "passenger". You have to provide a vehicle class ID to change the lane permissions, not a vehicle type ID. Please read the docs about the [vehicle classes](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#abstract_vehicle_class).
