### ISSUE TITLE
SUMO Netedit: produces jagged and irregular open drive files

### ISSUE THREAD

**Issue by HariKrishnaPadala** [eclipse-sumo/sumo#14095]
Hi, 

I am using SUMO NetEdit interface to export open drive output from open street maps.
The road geometry in the open drive file which is generated from the network's sumo file using netconvert 
is having jagged and irregular shapes. The road boundaries are not smooth curves but are jagged lines.

Can anyone suggest a way to obtain smooth open drive roads from Netedit interface?

Thank you.

**Comment by m-kro** [comment]
Could you post either a screenshot or Geo coordinates to try?

**Comment by HariKrishnaPadala** [comment]
I guess any road region with more curvature is having this issue.
The road left and right boundaries are having zig-zag pattern along the boundary instead of smooth curve.

Is there a way in NetEdit or NetConvert to correct these irregularities?

**Comment by HariKrishnaPadala** [comment]
I am trying to import the generated open drive from Netconvert into Carla using "client.generate_opendrive_world()" feature of CARLA. The roads imported are not smooth in CARLA environment.

**Comment by m-kro** [comment]
@HariKrishnaPadala Could you please try [odrviewer.io](https://odrviewer.io/) to see if you encounter the same problem? It could be as well that it is rather a CARLA topic?

**Comment by HariKrishnaPadala** [comment]
Yes even I think the issue is at CARLA world generation side. The open drive generated from Netconvert is looking smooth and good in odrviewer. Thank you for suggestion.
