### ISSUE TITLE
How can I download precise map files from OpenStreetMap?

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14090]
Add your issue description here.
Hi, I'd like to ask how to download a more precise map file from OSM that includes geographic boundaries. The default rectangular selection often leads to less precise downloads.

*If possible, upload an example that shows your problem.*
So, when I project the shapefile that defines the boundaries of the area to generate TAZ files, I encounter some issues: certain zones are being left out. How can I solve this problem? Do I have to use a rectangular selection for a larger area?

Here are the issues I encountered when directly projecting to generate TAZ files and then generating routes using an OD matrix:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/2b2a2484-8880-4e91-95bf-1b9e1bba2a3e)

SUMO-version:
SUMO 1.19.0
operating system:
Windows 10

**Comment by m-kro** [comment]
There are services like [overpass](https://overpass-turbo.eu/) where can you select OSM data depending on a search query. Maybe this is an option?

**Comment by nudtdyk** [comment]
Danke für deinen Vorschlag!

**Comment by nudtdyk** [comment]
Another issue is that:
Recently I've been using mpl_dump_onNet.py for visualization. I followed the instructions and performed the operations, but encountered the following error:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/e2964fb9-082b-4abc-be5a-581c66e242dd)

![image](https://github.com/eclipse-sumo/sumo/assets/120693511/efdb9f91-e051-4354-b13f-e15298cbbb35)

**Comment by m-kro** [comment]
@nudtdyk Next time open a separate issue for a clearly separate topic. This script is considered as outdated in the docs. Could you please [plot_net_dump.py](https://sumo.dlr.de/docs/Tools/Visualization.html#plot_net_dumppy) try which seems to do the same thing?

**Comment by nudtdyk** [comment]
> @nudtdyk Next time open a separate issue for a clearly separate topic. This script is considered as outdated in the docs. Could you please [plot_net_dump.py](https://sumo.dlr.de/docs/Tools/Visualization.html#plot_net_dumppy) try which seems to do the same thing?

I'm very sorry for any inconvenience I may have caused you. I will make sure to ask questions in a more standardized manner in the future.
