### ISSUE TITLE
trips problem

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14096]
Add your issue description here.
Hi, recently I've been using Sumo to simulate traffic in a city, but I found several issues with the trip.xml file during runtime.

*If possible, upload an example that shows your problem.*
First, TAZ (Traffic Analysis Zone) partitions are defined manually, and then the OD (Origin-Destination) matrix is obtained based on weights and other information. After converting the OD matrix into trips, the following results are obtained:
![1700638033727](https://github.com/eclipse-sumo/sumo/assets/120693511/59529688-88ec-4656-9556-8027cada0ea9)

When searching for paths for vehicles, corresponding algorithms have also been set up for them.
![1700638170658](https://github.com/eclipse-sumo/sumo/assets/120693511/814fefdc-b7bc-4ce1-8cb4-3761178f849a)

However, during runtime, the following errors are inevitably encountered:
![1700638170626](https://github.com/eclipse-sumo/sumo/assets/120693511/00dc6b82-9788-480f-8c3d-9bbc6adc4681)

I would like to know whether the vehicles I have selected are ultimately removed directly from the road network, or if they are selected for a different route according to the algorithm. If they are removed directly, how can these vehicles be rerouted to reach their destinations?

SUMO-version:
SUMO 1.19.0
operating system:
Windows 10

**Comment by m-kro** [comment]
Maybe it is better to just use fromTaz/toTaz attributes to define the trip when the from/to edge cannot be used anyway? Or do you expect those edges to be tried first before heading on to the TAZ values?

**Comment by nudtdyk** [comment]
> Maybe it is better to just use fromTaz/toTaz attributes to define the trip when the from/to edge cannot be used anyway? Or do you expect those edges to be tried first before heading on to the TAZ values?

How should it be implemented specifically?
As you can see, the content format of the trip file is as follows, including fromTaz/toTaz and from/to edge:
<trip id="4057" depart="1.27" from="186395681#3" to="658931701#1" fromTaz="430111010000" toTaz="430105016000" departLane="free" departSpeed="max"/>

**Comment by nudtdyk** [comment]
Hi, I tried to keep only the from taz and to taz parts as requested, but I'm getting an error when running the code. The error message is as follows:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/905654f9-738b-4600-a8de-453dd8853c9f)

**Comment by m-kro** [comment]
This means the referenced TAZ is not defined. You have to load all the TAZ items you refer to in the trips.

**Comment by nudtdyk** [comment]
> This means the referenced TAZ is not defined. You have to load all the TAZ items you refer to in the trips.

Vielen Dank für Ihren Hinweis. Das Problem ist jetzt gelöst.
