### ISSUE TITLE
Load selection file from command line option

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#14093]
Load a selection the same way as using the menu `Edit > Edit Selected > Load selection` but from the command line... If somebody relies on drawing schemes "by selection", this can be useful to automate the process.

**Comment by behrisch** [comment]
probably useful for netedit as well

**Comment by namdre** [comment]
I'm happy this is getting some progress (#5427). 
It would be nice to permit selecting objects that are created at runtime (i.e. vehicles).

**Comment by namdre** [comment]
selecting of dynamic objects after they are loaded was implemented via #5427
