### ISSUE TITLE
Question in using NETEDIT tools

### ISSUE THREAD

**Issue by michelmadeira** [eclipse-sumo/sumo#14091]
Hi guys,

I´m trying to use many python tools trought NETEDIT interface, but I alway get this path error message:

```
starting process...
python: can't open file 'C:\\Program Files (x86)\\Eclipse\\Sumo"/tools/net/net2kml.py --net-file E:\\000_CURSO_SUMO\\Cenário': [Errno 22] Invalid argument
process finished

```

What is happening?

There is a especific directories to use the functions? 
Can I use functions in any directory in my computer? I set sumo to my enviroment variables and I manage to execute trought command line, but I can´t use netedit interface.

Thanks for you help

**Comment by angelobanse** [comment]
It should work on any directory. The problem is due to the directory name `Cenário`. Try renaming that folder to something else in the meantime.

```
  File "C:\Repos\sumo\tools\sumolib\net\__init__.py", line 925, in readNet
    parse(gzip.open(filename), netreader)
```

```
  File "C:\Repos\sumo\tools\sumolib\net\__init__.py", line 927, in readNet
    parse(filename, netreader)
```
