### ISSUE TITLE
Sumo Installation

### ISSUE THREAD

**Issue by nmeskin** [eclipse-sumo/sumo#14105]
Hello,

I am trying to install SUMO on Ubuntu 20.04 and I am getting the following error:

sudo apt-get install sumo sumo-tools sumo-doc: command not found.

Thanks,

**Comment by m-kro** [comment]
I am not a regular Linux user, but doesn't this tell you it cannot find the package manager command (apt-get) at all (so a general problem / nothing SUMo-specific)?

**Comment by nmeskin** [comment]
I am following the instruction in installation website.
