### ISSUE TITLE
Convert from flow to vehicles

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [eclipse-sumo/sumo#14107]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
Hello, thank you for sharing your coding.

I would like to ask you how to convert from flow to each vehicle with its route in rou.xml?
I only see the vehicle2flow.py
thanks

**Comment by m-kro** [comment]
There is no helper script for that purpose. If you disregard any flows depending on random seed, this is quite a trivial task to parse the data and run a for loop to create single vehicle definitions, though.
