### ISSUE TITLE
Distance interval of a vehicle with respect to both the preceding and following vehicles

### ISSUE THREAD

**Issue by claudiacbh** [eclipse-sumo/sumo#14102]
Hello!
Can you tell me if there is a specific function to determine the distance interval of a vehicle with respect to both the preceding and following vehicles (in my case, for bus control)? In case it doesn't exist, could it be considered for inclusion in a future version?

**SUMO-version:**
1.18.0

**Comment by m-kro** [comment]
You have `traci.vehicle.getLeader` ([ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getLeader)) which returns the direct leader and the distance between it and the vehicle you ask for. Just be sure to provide a search distance using the "dist" argument.

Usually, searching upstream is not so much requested and we do not have a particular function for that. A general approach to get vehicles along the route would be to read the route using `traci.vehicle.getRoute` ([ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getRoute)) and then iterate through the vehicles on the returned edges using `traci.edge.getLastStepVehicleIDs` ([ref](https://sumo.dlr.de/pydoc/traci._edge.html#EdgeDomain-getLastStepVehicleIDs)).
