### ISSUE TITLE
Pedestrian speed control 

### ISSUE THREAD

**Issue by muhammadfaizan91** [eclipse-sumo/sumo#14117]
I am new user of sumo . I am going through a problem in which I want to create a person whose speed should remain constant while walking from one edge to the 2nd edge. For example, I want the speed to remain 1.5m/s. When I get the output there is a lot of fluctuation in the speed of the pedestrian (in the range of 20% lower (1.2-1.5 m/s). I tried to adjust it through "desiredMaxSpeed" and setting "speedDev " the following error is occurring 
"PersonDomain.appendWalkingStage() got an unexpected keyword argument 'speedDev'" 

The speed profile of the person before applying the "speedDev" is attached which shows a lot of fluctuation. 
![pedspeed](https://github.com/eclipse-sumo/sumo/assets/147474607/20f4988a-56b0-48dc-ad59-f8503b0f159c)

The code used for the person generation is as follows. Please correct me if something is wrong with the code 

`traci.person.add(personID="P1", edgeID="E1", pos= 0,depart=0)
traci.person.appendWalkingStage(personID="P1", edges="E1", arrivalPos=60,  speed=1.5, stopID="" )`

*If possible, upload an example that shows your problem.*

Note: I am generating person with the help of Traci and I want to control it by Traci as well. Thanks 

**SUMO-version:**   1.16.0 

**operating system:** Windows 11

**Comment by m-kro** [comment]
You set the `speedDev` value at the vType your persons belongs to. If you didn't specify a custom one, it's `DEFAULT_PEDTYPE`. If all your pedestrians should go at the same speed, just add this to one of your route/additional files:
 ```
<vType id="DEFAULT_PEDTYPE" speedDev="0"/>
 ```
[Here](https://sumo.dlr.de/docs/Specification/Persons.html#available_vtype_attributes) you can find the available vType attributes for persons.
