### ISSUE TITLE
Cannot change taxi behavior after dropping off the passenger

### ISSUE THREAD

**Issue by buddih09** [eclipse-sumo/sumo#14115]
The issue I describe is related to the taxi behavior after dropping off the passenger at the destination. As mentioned in a previous [issue](https://github.com/eclipse-sumo/sumo/issues/10933), the taxi disappears. The sumo [documentation](https://sumo.dlr.de/docs/Simulation/Taxi.html#taxi_behavior) provides some options to change this behavior and divert the taxis to a parking area or do random circling. However, in my attempt, neither of these options changed the default behavior, which is disappearing taxis. To reproduce the issue, I am sharing the relevant files [here](https://www.swisstransfer.com/d/315fdbe2-d72c-4c0f-91c6-1419bcc77cf4). 

Can you kindly advise me regarding the source of this unexpected behavior? 

**SUMO-version:**
1.18.0
**operating system:**
Windows 10

**Comment by m-kro** [comment]
Your case is different from the cited [issue](https://github.com/eclipse-sumo/sumo/issues/10933) as you didn't define a taxi fleet at all. Your person is transported by a triggered vehicle (see docs about [PersonTrip](https://sumo.dlr.de/docs/Specification/Persons.html#persontrips)).

**Comment by buddih09** [comment]
Thank you for the reply. I did not realize the difference you mentioned compared to the other case I linked.
But you also say that the way I defined the case for a single taxi and two users is also correct. But, then I do not understand why the idle behavior does not work properly. Do you have any suggestions?

**Comment by m-kro** [comment]
Sorry I mixed a bit two different things.

1. You didn't define a taxi vehicle at all (only the vehicle type). You just defined trips to be completed with a taxi.
2. The taxi device definition including the idle behaviour in the vehicle type seems to be fine.

**Comment by buddih09** [comment]
Thank you. I think what I miss is the following kind of definition, if I understand correctly.
```
   <vehicle id="v0" route="route0" depart="0" line="taxi">
        <param key="has.taxi.device" value="true"/>
    </vehicle>
```
The problem is, suppose I want to operate the taxi fleet based on the demand, and I want the taxis to dynamically decide which person they should take. For example, I want to have an algorithm that instructs the nearest available taxi to go to the ride-hailing passenger. Then, I do not want to assign a route to the taxi in advance. Maybe I'm missing some key modeling strategy here. What do you think?

**Comment by m-kro** [comment]
The taxi works like this:

- insert it with an initial route (can be short)
- after the initial route, the idle behaviour becomes active
- serve customers according to the dispatch algorithm or waiting for customer (idle behaviour)

**Comment by buddih09** [comment]
Since this is still an open issue, let me update you on some things I have been trying and the progress so far.
As @m-kro suggested, I defined the vehicles with a short initial route. 
`<vehicle id="v0" type="taxi" depart="0" route="route0"/>`

The vehicle starts at this position and then goes into idling, which is the expected behavior. PeronTrips are defined like this.
```
<person id="1" departPos="random"  arrivalPos="random" depart="33.88">
        <personTrip from="279398453#2" to="232339038#1" modes="taxi"/>
</person>
```
As expected, at the time of departure, the taxi started moving towards the passenger. I still have some remaining questions that I still need to solve.

1. The above behavior is observed only when the idling strategy is not set to taxistand. When the idling strategy is taxistand, the taxi moves to the taxi stand and starts the idling process as expected. But it fails to resume at the time when a passenger becomes available.
2. For the case of a large taxi fleet, it would be nice to have a built-in option to place the taxis randomly. At the moment, I'm trying to do this by reading the network file, selecting a random edge from all edges that allows taxi vehicles, and then searching for the next connected edge. Sometimes, this strategy generates islanded taxis that get stuck because the streets surrounding them do not allow that type of vehicle. So, we need some validation process, which I think is an interesting addition to sumo.

**Comment by m-kro** [comment]
@buddih09 The taxi cannot reach the parking because access roads do not allow its vehicle class. This triggered an endless recursion in the idling code which has been fixed (stopped) now. So please review your lane permissions and possibly update to the development version tomorrow.
