### ISSUE TITLE
Question of node type at intersection

### ISSUE THREAD

**Issue by Shawkncok** [eclipse-sumo/sumo#14113]
Add your issue description here.
Dear sir or madam:

I simulate a non-signalized intersection, and use different node types (unregulated, right before left, all-way stop), but collision would happen in unregulated condition. I wonder why?? I read the paper "SUMO’s Road Intersection Model" but still have no idea.

And I also wonder the details of right-of-ways of different node types because the explain in  https://sumo.dlr.de/docs/Networks/PlainXML.html is not clear

**Comment by m-kro** [comment]
This behaviour happens by definition for the unregulated nodes (see [docs](https://sumo.dlr.de/docs/Networks/PlainXML.html#node_types)). Please choose a different node type, e.g. "priority". What exactly do you not understand in the right-of-way explanation?

**Comment by Shawkncok** [comment]
As Krauß's car-following model is adopted, collsion should not happen because the vehicle should stop once the gap between vehicles become 0. But if I use "unregulated" node type, collision would happen. I wonder why??

And another question is that article [SUMO’s Road Intersection Model] says: " To be able to use the car following functions two things are required 1. A vehicle needs to know the lead vehicle; 2. There must be a well-defined distance between the follower and the lead vehicle."

For my perspective, different type node has different way to recognize the leading vehicle. Is that right??

**Comment by m-kro** [comment]
As already written, the "unregulated" node is a special and deliberate case where effectively collisions may happen. Just don't use it if you have no special use case for it.
The node types differ in the rules who gets the right of way, but they do not influence the leading vehicle. Anyway the citation is about car-following and not about the intersection model...
