### ISSUE TITLE
Detailed information about “Speed adjustment to support lane-changing” of lane-changing model in SUMO

### ISSUE THREAD

**Issue by JingyanXing** [eclipse-sumo/sumo#14116]
In my current research, I have focused on the motion of the following vehicles in the target lane when vehicles actively change lanes. In Chapter 1.4.3 of the PDF provided at the link https://elib.dlr.de/89233/, the logic behind the motion of the following vehicles is described. Could you please guide me to the specific formulas corresponding to this logic for calculating the changes in speed?
Thank you.

**Comment by m-kro** [comment]
The logic has been described in the publication in an abstract fashion for better understanding. The actual conditions of the decision logic are distributed at multiple places inside the lane-change model code. So they cannot be pointed to easily.

I invite you to look at methods using the internal messagging system for lane changes (method names starting with "inform") in the following files:

- [abstract lane change model definition](https://github.com/eclipse-sumo/sumo/blob/main/src/microsim/lcmodels/MSAbstractLaneChangeModel.cpp)
- [SL2015 implementation](https://github.com/eclipse-sumo/sumo/blob/main/src/microsim/lcmodels/MSLCM_SL2015.cpp)
