### ISSUE TITLE
Thanks for your response, but I don't want the CAVs to be restricted from entering the bus lane or to be allowed to enter it all the time. I just want them to be prohibited from entering, but only those CAVs will be allowed to enter if some conditions are met for them in that specific simulation step. If I allow the whole CAV type to enter, those with unmet condition may enter because of sumo's default lane changes. Can this issue be solved?

### ISSUE THREAD

**Issue by Paniz97** [eclipse-sumo/sumo#14122]
Thanks for your response, but I don't want the CAVs to be restricted from entering the bus lane or to be allowed to enter it all the time. I just want them to be prohibited from entering, but only those CAVs will be allowed to enter if some conditions are met for them in that specific simulation step. If I allow the whole CAV type to enter, those with unmet condition may enter because of sumo's default lane changes. Can this issue be solved?

_Originally posted by @Paniz97 in https://github.com/eclipse-sumo/sumo/issues/14121#issuecomment-1830035099_

**Comment by m-kro** [comment]
Discussion continues in #14121.
