### ISSUE TITLE
Libsumo cannot find xerces-c install

### ISSUE THREAD

**Issue by Josh-Woodcock** [eclipse-sumo/sumo#14126]
I am helping someone use `libsumo` on their M1 Silicon Mac.

When they try to import `libsumo` in their test script they get the following error:

        /Users/user/opt/anaconda3/envs/SUMO/bin/python /Users/user/Desktop/test2/Weather_normalisation/test neural prophet/test sumo.py 
        Traceback (most recent call last):
          File "/Users/user/Desktop/test2/Weather_normalisation/test neural prophet/test sumo.py", line 1, in <module>
            import libsumo
          File "/Users/user/opt/anaconda3/envs/SUMO/lib/python3.9/site-packages/libsumo/__init__.py", line 30, in <module>
            from .libsumo import vehicle, simulation, person, trafficlight  # noqa
          File "/Users/user/opt/anaconda3/envs/SUMO/lib/python3.9/site-packages/libsumo/libsumo.py", line 13, in <module>
            from . import _libsumo
        ImportError: dlopen(/Users/user/opt/anaconda3/envs/SUMO/lib/python3.9/site-packages/libsumo/_libsumo.so, 0x0002): Library not loaded: /usr/local/opt/xerces-c/lib/libxerces-c-3.2.dylib
          Referenced from: <BC6D02D9-F662-3A88-BAFD-3510A31F2793> /Users/user/opt/anaconda3/envs/SUMO/lib/python3.9/site-packages/libsumo/_libsumo.so
          Reason: tried: '/usr/local/opt/xerces-c/lib/libxerces-c-3.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/xerces-c/lib/libxerces-c-3.2.dylib' (no such file), '/usr/local/opt/xerces-c/lib/libxerces-c-3.2.dylib' (no such file), '/usr/local/lib/libxerces-c-3.2.dylib' (no such file), '/usr/lib/libxerces-c-3.2.dylib' (no such file, not in dyld cache)
        
        Process finished with exit code 1

Operating system: MacOS 13.5.2

I believe the issue is how M1 Silicon Mac's install their packages in Homebrew. `libsumo` is looking for `xerces-c` in the location where it should be on non-Silicon Mac's but cannot find the `xerces-c` install in `opt/Homebrew`.

How can the issue be resolved ?

**Comment by m-kro** [comment]
Can you install `libsumo` from pip?

**Comment by Josh-Woodcock** [comment]
Yes, while the print out is from Anaconda I have also tried with `pip` in a seperate virtual environment

**Comment by Josh-Woodcock** [comment]
As in self compile xerces-c ? I haven't tried that

**Comment by temetski** [comment]
@Josh-Woodcock Have you tried looking in the `/usr/local/opt/xerces-c/lib/` or any other directories mentioned in the 3rd to last lines of the output? Could you perhaps have a xerces-c installed, but with the library having a different version? I find that the distributet pip builds of sumo/libsumo may require specific versions of the dependencies to work, and the dylib files change version numbers over different brew installs of libraries.

**Comment by behrisch** [comment]
@Josh-Woodcock No, I actually meant self-compiling libsumo

**Comment by behrisch** [comment]
Closing for lack of feedback. Please add another comment if you have more information
