### ISSUE TITLE
Getting current green duration via TraCI

### ISSUE THREAD

**Issue by burakseyitkara** [eclipse-sumo/sumo#14120]
I try some different tls algo with python  on static tls system, on some conditions im extending green time. But with "getphaseduration" i cant get current extended green duration on code. How can i get current green duration via TraCI?

SUMO-version:1.19

operating system:win11

**Comment by m-kro** [comment]
You can get around that by 

- tracking the signal switching times (either checking for state changes of `traci.trafficlight.getRedYellowGreenState()` or reading `traci.trafficlight.getNextSwitch()`
- remember yourself the times when you extended the green duration
