### ISSUE TITLE
Junction intersecting with tram line

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse-sumo/sumo#14128]
Hello,
I have a junction intersecting with a tram line as shown below figure. This junction has a signal phase plan. Before tram arrives to junction, all direction should be red. After tram leave, signal phase plan should return back. How can set this process in SUMO? Is there any test scenario to investigate? Thank you for help, regards.
![image](https://github.com/eclipse-sumo/sumo/assets/79362739/dc3933a7-df6f-4d17-8ac0-ac1feac865d9)

**Comment by m-kro** [comment]
This can be done with actuated traffic lights, either using the [integrated ones](https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#traffic_lights_that_respond_to_traffic) or controlling the traffic light externally via TraCI. There is an [example scenario](https://sumo.dlr.de/extractTest.php?path=sumo/tls/actuated/conditions/bus_prio) similar to your case in our test collection using the internal actuated traffic light with custom switching rules.

**Comment by mehmetnedimyavuz** [comment]
Thank you @m-kro .I will examine example scenario.
