### ISSUE TITLE
How to disable Sumo's basic lane changes only to/from a specific lane?

### ISSUE THREAD

**Issue by Paniz97** [eclipse-sumo/sumo#14121]
Hello, I am modeling a scenario where I want to force CAVs (of passenger class) to enter the dedicated bus lane when some conditions are met using sumo TraCI. The problem is that if I set the bus lane restricted, no vehicles of other classes will be able to enter it, and if it's not restricted, passenger vehicles will enter the bus lane and buses change lane as well, based on sumo's lane change model. If I disable all sumo's lane changes, the passenger vehicles will not be able to change lane between ordinary lanes, so the model will not be precise. Is there a way to disable sumo's basic lane changes only between the bus lane and the adjacent lane?

I tried to set lane change mode for lanes, but I realized that setting lane change mode is only available for vehicles.

**Comment by m-kro** [comment]
You can restrict changes between lanes to certain vehicle classes using the lane attributes `changeLeft` and `changeRight`. These are available in the netedit lane attributes frame or can be patched using [PlainXML format](https://sumo.dlr.de/docs/Networks/PlainXML.html#lane_change_restrictions).

Optionally you could assign your CAV vehicle class `custom1` or `custom2` (or any other you do not use for other purpose in your simulation) to separate their rights from other passenger vehicles.

**Comment by Paniz97** [comment]
Thanks for your response, but I don't want the CAVs to be restricted from entering the bus lane or to be allowed to enter it all the time. I just want them to be prohibited from entering, but only those CAVs will be allowed to enter if some conditions are met for them in that specific simulation step. If I allow the whole CAV type to enter, those with unmet condition may enter because of sumo's default lane changes. Can this issue be solved?

**Comment by Paniz97** [comment]
I wish you hadn't closed my issue.

**Comment by Paniz97** [comment]
> You can restrict changes between lanes to certain vehicle classes using the lane attributes `changeLeft` and `changeRight`. These are available in the netedit lane attributes frame or can be patched using [PlainXML format](https://sumo.dlr.de/docs/Networks/PlainXML.html#lane_change_restrictions).
> 
> Optionally you could assign your CAV vehicle class `custom1` or `custom2` (or any other you do not use for other purpose in your simulation) to separate their rights from other passenger vehicles.
Thanks for your response, but I don't want the CAVs to be restricted from entering the bus lane or to be allowed to enter it all the time. I just want them to be prohibited from entering, but only those CAVs will be allowed to enter if some conditions are met for them in that specific simulation step. If I allow the whole CAV type to enter, those with unmet condition may enter because of sumo's default lane changes. Can this issue be solved?

**Comment by m-kro** [comment]
I just tried to issue a lane change using TraCI with the lane change forbidden by the `changeLeft` attribute and it works. Maybe you give it a try?

**Comment by Paniz97** [comment]
> I just tried to issue a lane change using TraCI with the lane change forbidden by the `changeLeft` attribute and it works. Maybe you give it a try?

**I took the idea of defining custom1 and custom2 vehicle classes from you and changed the vClass of CAVs dynamically during simulation based on their condition and permission to enter or not, and it worked. Thanks a lot.**
