### ISSUE TITLE
netconvert with option "--osm.bike-access" (and "--dlr-navteq-output"): Request to 

### ISSUE THREAD

**Issue by elmarbrockfeld** [eclipse-sumo/sumo#14138]
When using netconvert especially with option "--osm.bike-access" (don't known if used option "dlr-navteq-output" is also important in this case) some links are not attributed properly concerning use of bicycles. For ``tag k="highway" v="footway"`` with ``tag k="foot" v="designated"`` and ``tag k="bicycle" v="yes"`` the link is attributed (in dlr-navteq-output) with vehicle_type=000000000001. Thus, pedestrians are allowed, but bicycles not. Correct attribution should be 000000000011.

netconvert Version v1_19_0+0208-13a9e45677a

**Example commandline netconvert:**
netconvert.exe --osm-files brunswick2023q4_bbox.osm.xml --dlr-navteq-output brunswick2023q4 --dlr-navteq.version 7.0 --output.street-names --type-files osmNetconvert.typ.keepmoving.xml,osmNetconvertUrbanDe.typ.xml --verbose --osm.speedlimit-none 36.389 --osm.bike-access

**Example link in osm:**
https://www.openstreetmap.org/way/1135408728#map=21/52.31260/10.55992&layers=T

**XML download of the link:**
```<osm version="0.6" generator="CGImap 0.8.10 (476947 spike-07.openstreetmap.org)" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/">
<way id="1135408728" visible="true" version="1" changeset="131728759" timestamp="2023-01-26T11:22:37Z" user="Langlaeufer" uid="34953">
<nd ref="4841763578"/>
<nd ref="4239824306"/>
<nd ref="469936789"/>
<tag k="bicycle" v="yes"/>
<tag k="foot" v="designated"/>
<tag k="highway" v="footway"/>
<tag k="lcn" v="yes"/>
<tag k="lit" v="no"/>
<tag k="surface" v="paving_stones"/>
<tag k="traffic_sign" v="DE:239,1022-10"/>
</way>
</osm>
```

**map around the example link (in red)**
* dotted links in the north: same problem
* dotted links in the south: ok. with the following attribution
```
<tag k="bicycle" v="designated"/>
<tag k="foot" v="designated"/>
<tag k="highway" v="path"/>)
```

![brunswick_bicycle_waggumer_weg_north](https://github.com/eclipse-sumo/sumo/assets/150748531/6108666b-9512-4262-9056-ec6e1457f695)

**Comment by behrisch** [comment]
After consulting @elmarbrockfeld everything seems to be fine
