### ISSUE TITLE
vehicle setting

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14130]
Add your issue description here.
Hi, recently I've been trying to build a scenario using sumo and python. I was wondering if it's possible to set an initial value for each vehicle (to store its initial fuel level). As the distance increases, the fuel level gradually decreases until it reaches a certain threshold and the vehicle will choose the nearest parking lot to park. If there is no parking lot available, the vehicle will be removed directly from sumo.

May I ask if you can provide me with some ideas? For example, can we use traci to accomplish this task?

*If possible, upload an example that shows your problem.*

SUMO-version:
SUMO 1.19.0
operating system:
Windows 10

**Comment by m-kro** [comment]
You can attach key-value pairs to vehicles using the ["generic parameters"](https://sumo.dlr.de/docs/Simulation/GenericParameters.html) feature. The values can be read and set via TraCI. Currently the fuel reserve of a vehicle is not modelled by sumo, so you have to do it yourself.

You can send vehicles to a parking by rerouting it `traci.vehicle.changeTarget()` and adding a stop at a parking `traci.vehicle.setParkingAreaStop()`. Either let the route terminate there or remove the vehicle directly with `traci.vehicle.remove()`.

**Comment by nudtdyk** [comment]
Vielen Dank für Ihren Ratschlag.
