### ISSUE TITLE
Problems using NETEDIT Tools

### ISSUE THREAD

**Issue by Vort3x98** [eclipse-sumo/sumo#14134]
Hello, I'm new to SUMO environment. I'm trying to use the tools in netedit 1.19.0 in Windows 11 for my thesis but the tools don't work. 

After every run, this error appears:

```
python "C:\Program Files (x86)\Eclipse\Sumo\"/tools/net/netdiff.py C:\PROVA_SUMO\sumo2023_tutorial\00_netgenerate\x.net.xml C:\PROVA_SUMO\sumo2023_tutorial\00_netgenerate\x2.net.xml C:\PROVA_SUMO\sumo2023_tutorial\00_netgenerate\diff starting process...
python: can't open file 'C:\\Program Files (x86)\\Eclipse\\Sumo"/tools/net/netdiff.py C:\\PROVA_SUMO\\sumo2023_tutorial\\00_netgenerate\\x.net.xml C:\\PROVA_SUMO\\sumo2023_tutorial\\00_netgenerate\\x2.net.xml C:\\PROVA_SUMO\\sumo2023_tutorial\\00_netgenerate\\diff  ': [Errno 22] Invalid argument
process finished
```

Can someone help me, please?

**Comment by m-kro** [comment]
This looks like a problem with the file paths. Could you please try to install SUMO at a file path which does not contain " " (space) characters?

**Comment by Vort3x98** [comment]
Hello, thank you for the fast answer, but the error is the same:
`python "C:\INSTALLAZIONE_SUMO\"/tools/net/netdiff.py C:\PROVA_SUMO\sumo2023_tutorial\00_netgenerate\x.net.xml C:\PROVA_SUMO\sumo2023_tutorial\00_netgenerate\x2.net.xml C:\PROVA_SUMO\sumo2023_tutorial\00_netgenerate\diff --write-shapes starting process...
python: can't open file 'C:\\INSTALLAZIONE_SUMO"/tools/net/netdiff.py C:\\PROVA_SUMO\\sumo2023_tutorial\\00_netgenerate\\x.net.xml C:\\PROVA_SUMO\\sumo2023_tutorial\\00_netgenerate\\x2.net.xml C:\\PROVA_SUMO\\sumo2023_tutorial\\00_netgenerate\\diff --write-shapes  ': [Errno 22] Invalid argument
process finished
`

**Comment by davide990** [comment]
Are you sure that backslash and double quotes are not the problem?
`"C:\INSTALLAZIONE_SUMO\"/`
`                      ↑↑`

**Comment by m-kro** [comment]
@davide990 is completely right. Please remove the last backslash from your `SUMO_HOME` variable. From now on, netedit will do this on the fly (if built from Github source or using [development binaries](https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version) starting from tomorrow).

**Comment by Vort3x98** [comment]
Thanks to everybody for the support, now it is working.
