### ISSUE TITLE
How to get the id of edges inside traffic island and intuitive tool for comparing simulator results. 

### ISSUE THREAD

**Issue by jinx2plus** [eclipse-sumo/sumo#14132]
If I want to get edge IDs of each in list format(python), which function should I use from sumolib? 

![two edges, in yellow box ](https://github.com/eclipse-sumo/sumo/assets/51274389/89597375-0528-4808-8219-461c74fbc01a)

Also, is there an easy way to compare result of two separate simulator scenario intuitively? If there are lots of scenarios, should I make my own python code? 

**SUMO-version:**

**operating system:**

**Comment by m-kro** [comment]
You have to load the network using the following switches (see docs):
```
# import the library
import sumolib
# parse the net
net = sumolib.net.readNet('myNet.net.xml', withPedestrianConnections=True, withInternal=True)
```
When traversing the network using sumolib, keep in mind that pedestrians can use an edge in both directions but the edge has still a defined direction in sumolib. So sometimes you may have to inverse the search direction on the other side of the pedestrian crossing.

**Comment by jinx2plus** [comment]
I haven't added any pedestrian sidewalk to the edges I've mentioned. If there are no pedestrian connections, on the edges, I guess I'll have to use vertices(or center points) of junctions with tls in it and locate the edges diagonal to it.
