### ISSUE TITLE
'Connection' object has no attribute '_socket' in Co-Simulation between SUMO and CARLA

### ISSUE THREAD

**Issue by ShenZC25** [eclipse-sumo/sumo#14131]
Add your issue description here.

Thank you very much for your excellent work. I encountered the following problems when using SUMO and CARLA for joint simulation (it seems that there were similar problems in previous issues, but I still don't know how to solve them)

Traceback (most recent call last):
  File "run_synchronization.py", line 396, in <module>
    synchronization_loop(arguments)
  File "run_synchronization.py", line 325, in synchronization_loop
    synchronization.tick()
  File "run_synchronization.py", line 117, in tick
    self.sumo.tick()
  File "F:\CARLA_0.9.10\WindowsNoEditor\Co-Simulation\Sumo\sumo_integration\sumo_simulation.py", line 532, in tick
    traci.simulationStep()
  File "F:\Program Files\Eclipse\Sumo\tools\traci\main.py", line 207, in simulationStep
    return _connections[""].simulationStep(step)
  File "F:\Program Files\Eclipse\Sumo\tools\traci\connection.py", line 323, in simulationStep
    result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
  File "F:\Program Files\Eclipse\Sumo\tools\traci\connection.py", line 185, in _sendCmd
    return self._sendExact()
  File "F:\Program Files\Eclipse\Sumo\tools\traci\connection.py", line 83, in _sendExact
    if self._socket is None:
AttributeError: 'Connection' object has no attribute '_socket'

This seems to be that I have too many cars colliding at the intersection, and then some cars can't be removed. If it is caused by this reason, please tell me how to solve it (for example, how to remove the vehicle), otherwise please help me to confirm the problem.

Besides, there are some other problems. That is to say, when I was conducting joint simulation, I found that the simulation time of SUMO and CARLA was out of sync. Can you tell me why? thank you
![Snipaste_2023-11-30_22-25-15](https://github.com/eclipse-sumo/sumo/assets/89288084/61c978c2-a7e8-4a68-a7fb-00abad6a9b8f)
As the picture shows, SUMO has crashed, but CARLA hasn't, but my understanding is that they should be synchronized?

Looking forward to your answer, thank you.

*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.13.0

**operating system:**
win11

**Comment by ShenZC25** [comment]
> In a previous issue (#10551), teleporting was supposed to be a possible trigger for crashing sumo. Could you try to deactivate teleporting in your simulation (start sumo with **--time-to-teleport -1**) to see if this makes a difference? Additionally we would like to have the sumo scenario and a TraCI log of the issued commands to see why sumo would crash. See the [docs](https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands) how to generate this log file.

Thank you for your advice. I read it before I asked issue(https://github.com/eclipse-sumo/sumo/issues/10551), but it seems that there is no solution to the problem.
Now I have made the following settings in the configuration file xxx.sumocfg of SUMO, but it still doesn't solve the problem.

    <processing>
        <time-to-teleport value="-1"/>
        <ignore-route-errors value="true"/>
    </processing>

I look forward to your further guidance. Thank you.

**Comment by behrisch** [comment]
@ShenZC25 Can you try to run this with a newer SUMO version than 1.13?

**Comment by behrisch** [comment]
Closing for lack of feedback. Please add another comment if you have more information
