### ISSUE TITLE
[Question] Emergency brake signal in TRACI

### ISSUE THREAD

**Issue by LekYang** [eclipse-sumo/sumo#14149]
Is there a method in TRACI to detect or retrieve the emergency brake signal? For example, I want to use TRACI to keep track of the warning output in SUMO GUI.

"Warning: Vehicle 'obstacle_1' performs emergency braking on lane '-E14_0' with decel=9.00, wished=4.50, severity=1.00, time=25392.50."

**Comment by m-kro** [comment]
You could call `traci.vehicle.getSpeed` ([ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getSpeed)) at every time step and compute the difference to the last time...

**Comment by LekYang** [comment]
I had hoped for a simpler solution, considering the warning is already display in the GUI, but I suppose this works too if there are no other way
