### ISSUE TITLE
Adapt plot_trajectories.py for call from netedit UI

### ISSUE THREAD

**Issue by Nifemi954** [eclipse-sumo/sumo#14147]
The plot trajectories option within netedit does not have a way to upload the FCD-file.

**Comment by m-kro** [comment]
You are right. This is due how the options are implemented in `plot_trajectories.py` and we will change that. In the meantime, please call the script directly from the command line.

**Comment by Nifemi954** [comment]
I have an issue with a simulation I am running, where the last vehicle does not complete the route but stops at a particular TLS. The simulation just keeps running afterwards.  

Attached below is the config file;

<?xml version='1.0' encoding='UTF-8'?>
<configuration><input><net-file value="osm2.net.xml" /><route-files value="rsampler_trips900.xml" /><no-step-log value="True" /><time-to-teleport value="0" /></input></configuration>

**Comment by m-kro** [comment]
@Nifemi954 Please open new issues for separate topics.
