### ISSUE TITLE
unrecognized arguments when using randomTrips.py

### ISSUE THREAD

**Issue by corinnegroth** [eclipse-sumo/sumo#14142]
I am trying to create a route file using randomTrips.py. In the past, I was able to use the arguments "--random True (with a random seed)" and "--random-depart True" to make the routes even more random. Now, I get the following error when trying to use those arguments:

randomTrips.py: error: unrecognized arguments: True True

SUMO: 1.19.0

Windows

**Comment by m-kro** [comment]
Both options continue to exist. You can inspect the available options by calling the script with **--help**:
```
python randomTrips.py --help
```
You just have to leave out the boolean values after the options. The options are **False** by default and turn to **True** once you mention them in the arguments. This logic applies to many other boolean options in our python, too. Example:
```
python randomTrips.py --random --seed 42 --random-depart [...more arguments]
```
