### ISSUE TITLE
LIBSUMO and Python compatibility

### ISSUE THREAD

**Issue by prajwalvinod** [eclipse-sumo/sumo#14150]
I am trying to use the sumo-rl environment in python to implement an RL algorithm. After creating the environment and running the sumocfg file open loop without any RL agent I find that the phases of the traffic light do not change. I have verified that they change if I run the config file directly. After reading through the documentation I came across a line which I did not quite understand which I feel might be causing the issue after eliminating more obvious issues. Under limitations of LIBSUMO it says:

"The following things currently do not work (or work differently than with the TraCI Python client):

running with [sumo-gui](https://sumo.dlr.de/docs/sumo-gui.html) does not work on Windows and is still highly experimental on other platforms"

I would like to know if LIBSUMO causes any compatibility issues while running python scripts. Also are there dependency issues that exist across python libraries such as sumolib, libsumo and traci. 

Thanks

**SUMO-version: 1.15.0.2196**

**Operating system: Windows 11**

**Comment by behrisch** [comment]
I am not sure how the question relates to libsumo compatiblity. Does your scenario use libsumo or traci or is it supposed to run with both? Is the GUI supposed to be used or not? In general I think libsumo with the GUI will simply not work on Windows but apart from this and the other topics mentioned in the docs it should work.

**Comment by prajwalvinod** [comment]
The scenario uses both libsumo and traci as I am using the sumo-rl package to create python environments for my experiment. In relation to the GUI, there is an option within the env to use it or not but essentially I ask because for some reason I cannot get the traffic lights to change when running the network from python. Everything else works properly.

**Comment by behrisch** [comment]
And it works if you use traci but it does not work if you use libsumo?

**Comment by prajwalvinod** [comment]
Sorry for the delay in my reply. It so happens that the issue lay in the traffic light logic and its interpretation within the environment unrelated to the packages.
