### ISSUE TITLE
How to set up both connected and non-connected vehicles?

### ISSUE THREAD

**Issue by zhangm269** [eclipse-sumo/sumo#14158]
Hello! During the process of using sumo for research, I encountered a problem。I want to set up both connected and non-connected vehicles

> **connected and non-connected vehicles**. 
- Connected vehicles can obtain their location, speed, and other information through Traci, 
- non-connected vehicles cannot obtain any information.

**I'm not sure how to distinguish between these two types of cars in sumo.**

- One method I can think of is to define two types of vehicle models separately, such as defining type as CV or non CV. Does sumo itself have relevant functions to set up these two types?

**SUMO-version:**
sumo1.17.0
**operating system:**
window10

**Comment by m-kro** [comment]
You can easily define multiple vehicle types (see [docs](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#vehicle_types)). Moreover, you can read the vehicle's type using TraCI calling `traci.vehicle.getTypeID` ([ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getTypeID)). You'll have to provide your own logic for the TraCI calls of your connected vehicles, though. SUMO doesn't have any builtin feature for vehicle communication.
