### ISSUE TITLE
Speed per vehicle definition in SUMO

### ISSUE THREAD

**Issue by TAlfaCentauro** [eclipse-sumo/sumo#14157]
Hello!
I would like to know which available output file in SUMO  I should use if I want to know the average speed per vehicle every 5 seconds, please.
For example, I use "Trajectories Output" and get:
motionState vehicle="17" speed="196" time="7000" acceleration="1960"
motionState vehicle="2" speed="592" time="7000" acceleration="-543"
motionState vehicle="18" speed="220" time="7000" acceleration="2200"

But I don't know if this is the average speed per vehicle at that time or is the instantaneous speed.
I am using an old version of SUMO (1.1.0) and Debian as operating system.

Thanks in advance.

**Comment by m-kro** [comment]
The only output options which can get you average speeds of time intervals directly are local [detectors](https://sumo.dlr.de/docs/Simulation/Output/index.html#simulated_detectors). All others (like Amitran trajectories, FCD, raw dump) will output the speed of the referenced time step.

**Comment by TAlfaCentauro** [comment]
> The only output options which can get you average speeds of time intervals directly are local [detectors](https://sumo.dlr.de/docs/Simulation/Output/index.html#simulated_detectors). All others (like Amitran trajectories, FCD, raw dump) will output the speed of the referenced time step.

Thank you for your reply.
I understand that local detectors get the average speed for all vehicles, not the average speed for each vehicle. Am I right?

**Comment by m-kro** [comment]
Yes, you are right. In order to get an average speed per vehicle and time interval, you'll have to accumulate the data yourself.

**Comment by TAlfaCentauro** [comment]
> Yes, you are right. In order to get an average speed per vehicle and time interval, you'll have to accumulate the data yourself.

All right. Thank you!

**Comment by TAlfaCentauro** [comment]
All right. Thank you!
