### ISSUE TITLE
Question - Implementing Urban Air Mobility

### ISSUE THREAD

**Issue by JulianCzymmeck** [eclipse-sumo/sumo#14153]
Hello SUMO team,
I intend to implement a new tavelling mode: Urban Air Mobility as described in #12022
The long term goal would be for that to be a contribution to your code with features such as a new type of vehicle, special edges and the ability to create such networks as a new layer in netedit.

What would be the best way to go about implementing such features or the best place to start?

Kind regards

**Comment by behrisch** [comment]
Hi, I think Jakob gave already a quite good explanation on how to achieve this in #12022. Maybe we should continue the discussion there.
