### ISSUE TITLE
Teleporting on restricted/forbidden lane confuses detectors

### ISSUE THREAD

**Issue by wangchao2022** [eclipse-sumo/sumo#14168]
I have set the emergency lanes and set the closingLaneReroute's parameter allow=“vip”.Under normal circumstances，the nVehEntered of detector output data shuould be 0, but we get the non-zero number. Why does this happen and how should it be resolved?

*If possible, upload an example that shows your problem.*
![微信图片_20231217163038](https://github.com/eclipse-sumo/sumo/assets/105579557/6b3ecd9f-6e38-436a-bfb4-4c3c8de911c3)
**SUMO-version:1.16.0**

**operating system:**

**Comment by m-kro** [comment]
Did you check in sumo-gui whether the lane had its permissions changed and whether there were no vehicles on it?

**Comment by wangchao2022** [comment]
> Did you check in sumo-gui whether the lane had its permissions changed and whether there were no vehicles on it?

For example，I set the emergency lane parameter  allow=“vip”, the color will be gray and there will not appear vehicles theoretically. 
![微信图片_20231218175723](https://github.com/eclipse-sumo/sumo/assets/105579557/e205cc1e-17c7-487d-8247-2ff4d9110204)

Only when the parameter allow=vip is not set the emergency lane will turn black and there will be vehicles passing by.
![1](https://github.com/eclipse-sumo/sumo/assets/105579557/e0291be2-c541-49a8-b3cb-83a8649386da)
![2](https://github.com/eclipse-sumo/sumo/assets/105579557/4d642bd1-2b80-4a45-bb8e-3da478f50d7e)

Since our simulation took a long time, we did not check each one one by one.

**Comment by wangchao2022** [comment]
Thank you for your answer，but this happened when the emergency lane closing all the time.

**Comment by wangchao2022** [comment]
> It could be that some vehicles were still on the emergency lane when you closed it. Then they might have passed the detector while looking for a gap to change lanes. Now if you open/close lanes frequently and there are few gaps, this may be visible in the detector data as well.

Thank you for your answer，but this happened when the emergency lane closing all the time.

**Comment by wangchao2022** [comment]
[our model example.zip](https://github.com/eclipse-sumo/sumo/files/13711269/our.model.example.zip)
Here is our model example. Our test result shows there have vehicles passing by from 38400s to 71700s in the emergency lance.

**Comment by m-kro** [comment]
Thanks for your example scenario. I could reproduce the problem. It seems vehicles from other lanes are detected by the detector on the rightmost lane which is very strange...?!

**Comment by m-kro** [comment]
Related to frequent teleports (**time-to-teleport 1**). There is some last resort logic which would teleport vehicles on the rightmost lane. 
@wangchao2022: While we try to understand how to prevent this, you could disable teleporting by **time-to-teleport -1** and get rid of your detector problems.

**Comment by wangchao2022** [comment]
In our simulation, if the  time-to-teleport  set bigger, maybe some other problems happen. And if the lane were not crowded like this, the detector would not record the strange data, so it seems like a bug happened in the crowded scenario?

**Comment by m-kro** [comment]
@wangchao2022 : I have changed the code such that vehicles are not teleported anymore on forbidden lanes as long as there are other options. You can build fresh binaries from Github source or wait for the new [development binaries](https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version) of tomorrow.
