### ISSUE TITLE
what part of the edge does tracemapper.py(sumolib.route.mapTrace) calculate with input postion(lon, lat)? 

### ISSUE THREAD

**Issue by jinx2plus** [eclipse-sumo/sumo#14163]
I am curious of the principle of tracemapper.py, one of the tools for matching nearest edge in net.xml from lon,lat. 
I got the result from using option debug and verbose as this. 

```
pos:759.3571800422505, 482.2739771474153
candidates:[(<edge id="-N2234W000046" from="N1234W000280" to="N1234W000081"/>, 0.17859684730076736), (<edge id=":N1234W000280_1" function="internal"/>, 4.3091930273172725), (<edge id="-N2234W000292" from="N1234W000113" to="N1234W000280"/>, 4.3091930273172725), (<edge id=":N1234W000280_0" function="internal"/>, 5.298606210653705), (<edge id="N2234W000161" from="N1234W000280" to="N1234W000350"/>, 5.723798828885492), (<edge id=":N1234W000280_15" function="internal"/>, 9.54611817800915), (<edge id=":N1234W000280_16" function="internal"/>, 7.934013795646526), (<edge id=":N1234W000280_6" function="internal"/>, 8.20649228889455)]

**************** result:
path:-N2234W000046
```
Can you tell me which place the "sumolib.route.mapTrace" uses to calculate the nearest distance of edges. 

Here is the picture of the edge matched from various candidates. And also the position (759.3571800422505, 482.2739771474153) signified as red dot in the picture. 

![result edge is selected](https://github.com/eclipse-sumo/sumo/assets/51274389/e8cbe417-6acd-4c61-82f3-470a43ceb815)

**Comment by m-kro** [comment]
All geometry points of the edge are used. You can check the math done in 
https://github.com/eclipse-sumo/sumo/blob/ba08aa24ebb905c4903ccf4a8dc4e6e440d2dd42/tools/sumolib/geomhelper.py#L77

where _point_ is the trace point and _polygon_ the edge geometry (the reference line of the edge).
