### ISSUE TITLE
question about the stop line of traffic light

### ISSUE THREAD

**Issue by ishuwen** [eclipse-sumo/sumo#14173]
when i run others simulation, the stop line of traffic light is set on the edge rather than junction, how can i change it?
<img width="512" alt="1702950436862" src="https://github.com/eclipse-sumo/sumo/assets/32593963/647fc711-2351-4ab7-90ba-6c79a8ad361c">

**Comment by m-kro** [comment]
They probably used the edge attribute ["endOffset"](https://sumo.dlr.de/docs/Netedit/attribute_help.html#edge) to move the stop line upstream.

**Comment by ishuwen** [comment]
Thanks, they actually use endoffset for this, thanks for answering my question
