### ISSUE TITLE
How long does CACC need to complete formation?

### ISSUE THREAD

**Issue by ShouhaiChen** [eclipse-sumo/sumo#14178]
Hello! Under normal circumstances, what is the length of road section required to complete CAV vehicle formation with CACC in SUMO? Because I want to complete the formation of vehicles on a section of road near the intersection, and then let the vehicles safely pass through the intersection.
**SUMO-version:1.18

**Comment by m-kro** [comment]
This cannot be said exactly as it depends on a lot of car-following model (CFM) parameters (e.g. acceleration capability). If you intend to use the [CACC CFM](https://sumo.dlr.de/docs/Car-Following-Models/CACC.html): Its maximum distance where vehicle may interact is set to 250m.
