### ISSUE TITLE
How to use flow of vehicles using traci or any other inbuilt python tool

### ISSUE THREAD

**Issue by prasuka4** [eclipse-sumo/sumo#14177]
Hello
I have total number of vehicles count per hour and also pre defined routes. I want to run the flow of vehicles using traci or any other python files that are present in the sumo folder.

Could you let me know is there any way to do this.

**SUMO-version:**
1.19

**operating system:**
Windows

**Comment by m-kro** [comment]
Managing flows by TraCI isn't implemented yet. See #12600 .
