### ISSUE TITLE
parsing too many vehicles during "def getFlows" of tlsCycleAdaptation.py

### ISSUE THREAD

**Issue by jinx2plus** [eclipse-sumo/sumo#14182]
1. The message of "print("Parsed %s vehicles from %s." % (parsed, file))" gives out "Parsed 1609 vehicles from D:\anyang\231208_tracemapper_result_d10___addtime_FINAL_NEW_17_FINAL.rou.xml."
Input data consists of 546 vehicles, but seem to parse about 3(minimum of 1~ maximum of 4) times the number of vehicle ids in route.xml.
I also checked "tlsFlowsMap" value and "connFlowsMap" value, but unmatches the real value from route.xml. 

2.Also, tls consists of this but keep getting error message from the same code. 
Is there an anyway to fixit? 
What will be the most fast way?

```
    <tlLogic id="N1234W000081" type="static" programID="b" offset="-25">
        <phase duration="39" state="GrrrGrrrrgrg"/>
        <phase duration="3"  state="Grrryrrrrrrg"/>
        <phase duration="22" state="GGrrrrrrrrrg"/>
        <phase duration="3"  state="yyrrrrrrrrrr"/>
        <phase duration="40" state="rrGrrrGrgrgr"/>
        <phase duration="3"  state="rryrrryrrrrr"/>
        <phase duration="17" state="rrrGrrrGrrrr"/>
        <phase duration="3"  state="rrryrrryrrrr"/>
        <phase duration="27" state="rrrrGGrrrgrr"/>
        <phase duration="3"  state="rrrrGyrrrgrr"/>
    </tlLogic>
```
```
TLS: N1234W000081 --> the tl-indices with more than one major-green:[0, 0, 4, 4]
phase: 0
group flows: [39]
The used lanes: []
phase: 2
group flows: [22]
The used lanes: []
phase: 4
group flows: [40]
The used lanes: []
phase: 6
group flows: [17]
The used lanes: []
phase: 8
group flows: [27]
The used lanes: []
the current cycle length:160 sec
groupFlowsMap {0: [39], 2: [22], 4: [40], 6: [17], 8: [27]}
 multiOwnGreenMap {'N1234W000081': [0, 0, 4, 4]}
getmultiOwnGreen False
criticalFlowRateMap is zero {0: 0.0}
criticalFlowRateMap is zero {0: 0.0, 2: 0.0}
criticalFlowRateMap is zero {0: 0.0, 2: 0.0, 4: 0.0}
criticalFlowRateMap is zero {0: 0.0, 2: 0.0, 4: 0.0, 6: 0.0}
criticalFlowRateMap is zero {0: 0.0, 2: 0.0, 4: 0.0, 6: 0.0, 8: 0.0}
N1234W000081 {0: 0.0, 2: 0.0, 4: 0.0, 6: 0.0, 8: 0.0}
```

![signalized intersection](https://github.com/eclipse-sumo/sumo/assets/51274389/085c4e0c-e81f-4efe-9c3c-6e3eafa0fb49)

Always thank you for your kind answers.

**Comment by m-kro** [comment]
Regarding 1: The message was a bit misleading. It is the sum of signals the vehicles will pass along their routes which is printed. So the number is equal to the number of defined vehicles only if there is exactly one traffic light along their routes.

**Comment by jinx2plus** [comment]
I see it corresponds with the connections of two edges in tls intersection. Thank you. Have a nice day.
