### ISSUE TITLE
Warning: No connection between edge '-387' and edge '473' found.

### ISSUE THREAD

**Issue by jianghuyihei** [eclipse-sumo/sumo#14185]
I generated a SHP file myself using code, and then converted it to a net.xml file using：
netconvert --shapefile-prefix edges -o edges.net.xml --shapefile.street-id edgeid --shapefile.from-id fromid --shapefile.to-id toid --shapefile.type-id type --shapefile.use-defaults-on-failure --shapefile.traditional-axis-mapping --shapefile.all-bidirectional. 

Next, I generated a trip.xml file with：
activitygen --net-file edges.net.xml --stat-file edges.stat.xml --output-file edges.trips.xml --random. Finally, I used duarouter --net-file edges.net.xml --route-files edges.trips.xml --output-file edges.rou.xml --ignore-errors.

However, I encountered the following error messages: "Warning: No connection between edge '-158' and edge '477' found. Warning: Mandatory edge '477' not reachable by vehicle 'h35675c1:6'."

I have checked the network, and it is all connected. How can I resolve this issue?
[0.zip](https://github.com/eclipse-sumo/sumo/files/13766626/0.zip)
<img width="669" alt="rechable" src="https://github.com/eclipse-sumo/sumo/assets/109561120/9f8d964a-81ab-4737-acea-813e4e2394ca">

**Comment by m-kro** [comment]
Edges "470" and "-470" are not connected with the neighboring parts of the network. I imagine your SHP file lacks a node there. The shapes are adjacent but they are not connected.

**Comment by jianghuyihei** [comment]
> 边“470”和“-470”未与网络的相邻部分连接。我想你的 SHP 文件在那里缺少一个节点。这些形状是相邻的，但它们没有连接。

My shp file was converted through a PNG format image using a script I wrote myself. How to check if it is fully connected

**Comment by jianghuyihei** [comment]
> Edges "470" and "-470" are not connected with the neighboring parts of the network. I imagine your SHP file lacks a node there. The shapes are adjacent but they are not connected.

Thank you for your reminder. I have identified the problem
