### ISSUE TITLE
How to edit network quickly?

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14196]
Add your issue description here.
Hi, recently I want to use netedit to delete some minor roads or less frequently used roads in the road network, while keeping the main roads. Is there any quick method to do that?
*If possible, upload an example that shows your problem.*
For example, during path planning, roads like the one below are not necessary to consider:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/6c931a77-b8c1-4bed-9f9a-4839c62c9607)

**SUMO-version:**
SUMO1.19.0
**operating system:**
Windows10

**Comment by m-kro** [comment]
You can select multiple objects (edges in your case) and edit/delete them together. You can select by region or by object attributes and refine your selection using multiple criteria in the selection mode. See the docs [how to select](https://sumo.dlr.de/docs/Netedit/editModesCommon.html#select) in netedit. Then press [DEL] to delete the objects. If you want to set an object attribute to the same value for all selected objects of the same type, go to inspect mode and edit the attribute.

**Comment by nudtdyk** [comment]
Dear author, I want to delete edges of type "highway.footway" as shown in the following image:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/22c2a57e-812d-4e3b-9ec5-b2e35a15d91c)

However, I found that the connections and junctions cannot be deleted together. Below is the effect after deletion:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/dd646764-3da0-4ef5-bc73-731496203319)
How can I delete them together? Thank you.

**Comment by nudtdyk** [comment]
I have already resolved it on my own by using hierarchical selection. Thank you.
