### ISSUE TITLE
Deleting too many elements in netedit selection mode

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14197]
Add your issue description here.
Dear author, last time I asked you about how to batch delete roads of the same type along with their connections and junctions. However, during my actual operation, I encountered some issues.

*If possible, upload an example that shows your problem.*
As you can see, I want to delete the roads along with their connections and junctions as shown in the image below. 
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/965d052c-cdf9-4572-b4ec-59c9e2dfd1c3)

However, when I delete them, I unexpectedly found that some other connected main roads were also deleted.
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/30f26783-7826-42b5-b6ba-da182d2731e2)

Is there a way to avoid this outcome?
**SUMO-version:**
SUMO1.19.0
**operating system:**
Windows10

**Comment by palvarezlopez** [comment]
This happening because you selected the roads **and** the junctions. Unselect the marked junctions and check it again
![294191185-965d052c-cdf9-4572-b4ec-59c9e2dfd1c3](https://github.com/eclipse-sumo/sumo/assets/8238561/85a000b8-9017-4f4d-839a-3af3a0be25e5)
