### ISSUE TITLE
Path planning between POIs

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14193]
Add your issue description here.
Recently, I have been using traci to re-plan paths for vehicles. I intend to directly plan a path between two POI points, but I have found that traci can only plan paths from edge to edge.

*If possible, upload an example that shows your problem.*
 Is there any way to convert the location of a POI to the nearest edge? Or do you have any other suggestions? Could you please help me with this question whenever you have time? Thank you!

**SUMO-version:**
SUMO 1.19.0
**operating system:**
Windows10

**Comment by m-kro** [comment]
There are functions to find the closest edges to a point. First get the POI coordinates by `traci.poi.getPosition` ([ref](https://sumo.dlr.de/pydoc/traci._poi.html#PoiDomain-getPosition)), then query the closest edges with sumolib (see [this example](https://sumo.dlr.de/docs/Tools/Sumolib.html#locate_nearby_edges_based_on_the_geo-coordinate), skip the geo-conversion related part).

**Comment by nudtdyk** [comment]
Hi, according to the official documentation, the modified code should be as shown in the following figure:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/33f56c1d-f2d9-4f4f-85f4-ee2550888fae)

After running the modified code, the error message is as follows:
Traceback (most recent call last):
  File "D:\sumox.py", line 159, in <module>
    plan_paths_for_vehicles(task_assignments)
  File "D:\sumox.py", line 109, in plan_paths_for_vehicles
    start_roadID = locate_nearby_edges(poi_position[0], poi_position[1])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sumox.py", line 18, in locate_nearby_edges
    distancesAndEdges = sorted([(dist, edge) for edge, dist in edges])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'Edge' and 'Edge'

**Comment by m-kro** [comment]
Yes this was a bit short-sighted example in the docs. I corrected the command to the following:
```
distancesAndEdges = sorted([(dist, edge) for edge, dist in edges], key=x:x[0])
```
This way, only the distance is used for sorting.

**Comment by nudtdyk** [comment]
I'm very sorry to bother you again. According to the new error message from running the code, it is as follows:
    distancesAndEdges = sorted([(dist, edge) for edge, dist in edges], key=x:x[0])
                                                                            ^
SyntaxError: invalid syntax

**Comment by nudtdyk** [comment]
I see the problem: key=lambda
Thanks！

**Comment by nudtdyk** [comment]
Wait a minute！！！！！！
Dear author, when I try to obtain the nearest edge and use traci.vehicle.changeTarget, I get the following error:
Traceback (most recent call last):
  File "D:\sumox.py", line 162, in <module>
    plan_paths_for_vehicles(task_assignments)
  File "D:\sumox.py", line 123, in plan_paths_for_vehicles
    traci.vehicle.changeTarget(vehicle_id, start_roadID)
  File "D:\Sumo\tools\traci\_vehicle.py", line 1191, in changeTarget
    self._setCmd(tc.CMD_CHANGETARGET, vehID, "s", edgeID)
  File "D:\Sumo\tools\traci\domain.py", line 164, in _setCmd
    self._connection._sendCmd(self._cmdSetID, varID, objectID, format, *values)
  File "D:\Sumo\tools\traci\connection.py", line 231, in _sendCmd
    return self._sendExact()
           ^^^^^^^^^^^^^^^^^
  File "D:\Sumo\tools\traci\connection.py", line 144, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Destination edge '<edge id="471129127#0" from="4652920958" to="4652921397"/>' is not known.
