### ISSUE TITLE
Route setting and updating with rerouters for train simulation fails

### ISSUE THREAD

**Issue by mesjou** [eclipse-sumo/sumo#14195]
**Summary:** 

Vehicles' routes are not being updated correctly when the vehicle encounters edges closed by rerouters in SUMO.

We use rerouters to simulate a railway network that has disruptions. By our definition, disruptions are tracks/edges that are temporarily not accessible due to construction works, broken signals etc. We want to detect vehicles that will go through disruptions and then change their schedule (i.e. their upcoming stops) so that the vehicles will turnaround before the disruption and continue their route in the other direction.

When we remove the upcoming stops of a vehicle that will go through the disruption, the route of the vehicle is not updated. When we later want to add new stops, SUMO throws an error saying that: Stop insertion failed for vehicle 'S7_10' (No route found from stop edge 'F_737659-737648' to edge 'S_751764-751768').

**Example:**

1. Vehicle "S7_10" has next stops and a route that goes through a disruption. The edges are closed by a rerouter that looks like this: `<closingReroute id=”S_121411-123312” allow=”authority”/>`. Thus, calling libsumo.vehicle.isRouteValid(“S7_10”) returns False.
3. Removing the upcoming stops that are disrupted works by calling libsumo.vehicle.replaceStop(vehID=“S7_10”, edgeID=''). Calling libsumo.vehicle.getNextStops(“S7_10”) returns a list of stops without the disrupted stops.
4. However, the route of the vehicle did not change. Calling libsumo.vehicle.getRoute(“S7_10”) before and after the stop removal returns the same list of edges. Also updating the route manually by libsumo.vehicle.rerouteTraveltime(vehID=“S7_10”) does not change the route.
5. Adding a new stop by calling libsumo.vehicle.insertStop(“S7_10”) failes because route is not valid: Stop insertion failed for vehicle 'S7_10' (No route found from stop edge 'F_737659-737648' to edge 'S_751764-751768')

**Expected Behavior:**

For our use-case, we would like to update routes that are invalid due to a rerouter applied to some edges. We could i) either disable the rerouter during route finding/updating if libsumo would provide this functionality and it is not too slow or ii) route errors could be ignored for the rerouters. We found that there is an option for sumo called --ignore-route-errors. Probably this option could be enhanced to cover rerouters or an extra option for rerouters could be added. We are also happy about other proposals or advise how to handle our use-case. 

**Additional use-case:**

For a different part in our simulation, we need to set the upcoming stops of a vehicle knowing that the route is closed by a rerouter because our trains have to follow a schedule. We want to let the train drive its route and handle the closed route when the train reaches this part. However, if we want to set this route with edges closed by the rerouter, we get the same route error as in the example. We would be very happy, if your solution could handle this use-case as well. 

**SUMO-version:**

1.19.0.post242

**operating system:**

linux

**Comment by behrisch** [comment]
`traci.vehicle.rerouteTraveltime` is not useful here because it tries to keep the destination which is not reachable anymore. You will need to use `traci.vehicle.changeTarget`. Please report back here whether this works. For the other topics I opened new issues

**Comment by mesjou** [comment]
Using  `traci.vehicle.changeTarget` works sometimes. However, sometimes it removes stops from the vehicle. 

In one example, the vehicle has 5 stops. When I do `traci.vehicle.changeTarget()` to the edge of the last stop, SUMO will remove stop 2 and 3 from the next stops. Do you know why this could happen?

**Comment by behrisch** [comment]
Sorry for the delay. Does the new route still contain the stop edges?

**Comment by mesjou** [comment]
yes the route does not change

**Comment by namdre** [comment]
by default, replaceStop does not update the route when used for stop removal. To trigger a route update you have to call `vehicle.replaceStop(..., teleport=2)`

**Comment by behrisch** [comment]
Please leave another comment if it is still unanswered
