### ISSUE TITLE
Traci learning

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14190]
Hi, recently I have been conducting experiments using Traci in conjunction with Sumo. However, the official website's introduction to Traci is relatively simple and I don't know how to apply it.

For example, I want to use Traci to obtain the total number of vehicles currently loaded in the scene. The official documentation mentions a method called getCurrentTime. However, when I click on the detailed page, there is no specific explanation on how to use this method.
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/26f6302b-f722-456e-a830-56f1944fd8c4)
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/f3382957-866f-4fa1-8031-daf60536997d)

During the practical process, I tried traci.vehicle.getCurrentTime(), traci.constants.getCurrentTime(), and traci.getCurrentTime(), but none of them worked.
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/fba5180c-dc57-4f46-a63f-28fefb01feac)

**Comment by m-kro** [comment]
So you want to use the TraCI [Python interface](https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html). There you have to care about the domains the functions have been assigned to. You can find the domains in the [python reference](https://sumo.dlr.de/pydoc/traci.html) and access the available methods for each in the respective linked detail page. In your case, this is the `simulation` domain: `traci.simulation.getCurrentTime()` (deprecated function, replaced by `traci.simulation.getTime`).
