### ISSUE TITLE
routing-algorithm problem

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14192]
Add your issue description here.

Hi, recently I have been using SUMO to build OD flows for scene simulation. I found that SUMO has built-in path algorithms for constructing paths between regions, as shown in the following diagram:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/db99fcf3-682f-41a6-b0e4-ef455adbf350)

*If possible, upload an example that shows your problem.*
But what puzzles me is, if the OD for 100 vehicles is the same, will the paths planned for these 100 vehicles using the built-in path algorithm in SUMO be the same? Would you please take a look at this question when you have time? Thank you!
**SUMO-version:**
SUMO1.19.0
**operating system:**
Windows10

**Comment by m-kro** [comment]
No, it would take the current travel times into account. If an edge is heavily used and the travel time increases, a different path may be chosen. This is even more likely if the alternative edge has the same speed limit and isn't much longer.

**Comment by nudtdyk** [comment]
Vielen Dank für die Beantwortung meiner Frage!
