### ISSUE TITLE
How to close a certain distance of a designated lane (such as specifying the starting and ending points), rather than closing the entire lane?

### ISSUE THREAD

**Issue by wangwgithub** [eclipse-sumo/sumo#14194]
How to close a certain distance of a designated lane (such as specifying the starting and ending points), rather than closing the entire lane?

*If possible, upload an example that shows your problem.*

**SUMO-version:**1.19

**operating system:** win10

**Comment by wangwgithub** [comment]
current i use example code, `lane_id = "20_0"
traci.lane.setDisallowed(lane_id ,"all")`

**Comment by wangwgithub** [comment]
i want get a method like this, `lane_id = "20_0", startPos=(x,y) ,  endPos = (x,y), traci.lane.setDisallowed(lane_id ,startPos, endPost, "all")`

**Comment by m-kro** [comment]
This is not possible. You can still place stopping/parking vehicles on the stretch you want to "close" though. See the [docs](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#stops_and_waypoints) how to define stops.

**Comment by behrisch** [comment]
Or if you always want to close the same stretch you could consider splitting the edge

**Comment by wangwgithub** [comment]
ok, thank you, i just do like this !
