### ISSUE TITLE
SSM device crashes when iterating over incomplete routes

### ISSUE THREAD

**Issue by hhhhhhyl** [eclipse-sumo/sumo#14201]
Hello, I would like to use SSM Device to output TTC values for all vehicles, but I have conducted two simulations and both have encountered situations where the simulation suddenly terminates without any error before it is completed. May I ask why this is happening? How can I solve this problem?
The following two images show my interrupt results. My input files are uploaded in the form of Google Cloud Drive. Please check them. Thank you very much.
![屏幕截图 2023-12-25 172227](https://github.com/eclipse-sumo/sumo/assets/96480310/7c0de4ca-d9f8-42a4-9a5c-6f96af23a5cd)
![屏幕截图 2024-01-05 134808](https://github.com/eclipse-sumo/sumo/assets/96480310/b16cf1c3-b298-475d-a1ee-ecf97f546c6b)
input file:https://drive.google.com/file/d/17Eu1T655NFT_BwtcvwMrRmuv1VpPjhsP/view?usp=sharing

**Comment by m-kro** [comment]
Downloading from Google Drive fails for the moment. I'll try again later. Could you please check in the meantime if the result is the same with the latest SUMO release v.1.19?

**Comment by m-kro** [comment]
@hhhhhhyl Can you please check the download? I still get a timeout after waiting for the download to start during some seconds...

**Comment by hhhhhhyl** [comment]
Hello, download failure may be a web disk problem. Can I send it directly to your email attachment?

**Comment by m-kro** [comment]
Now the download worked. I was able to reproduce the problem but the scenario is that big it takes ages to debug... If you had a smaller working example that would be better. Keep in mind that the debug version of SUMO is much slower due to all the additional debug logic and output.

**Comment by m-kro** [comment]
Breaks 

https://github.com/eclipse-sumo/sumo/blob/06127e5703275d251dd23fa789dfff1708adeb07/src/utils/router/IntermodalEdge.h#L198

**Comment by hhhhhhyl** [comment]
Ok, I will try to build a small range of cases to upload, now my network is not stable, I will upload later, thank you for your hard work.

**Comment by hhhhhhyl** [comment]
I'm sorry to have kept you waiting. I just got back from a business trip. The following web disk link is a small size of the input file, it still does not work properly, it's hard for me to check the cause of the error. I hope I can get your help, thank you very much.
input file: https://drive.google.com/file/d/15l-VteEP8Wz6pTpL4IwNW55ZMBnOdjtY/view?usp=sharing

**Comment by hhhhhhyl** [comment]
Hello, may I ask if there is any current solution to this problem?

**Comment by m-kro** [comment]
There is no workaround AFAIK, but I'll have a look shortly whether the problem can be resolved easily in the code.

**Comment by hhhhhhyl** [comment]
Thabk you very much. May I ask if the same issue occurs when it runs on your computer?

**Comment by hhhhhhyl** [comment]
> Downloading from Google Drive fails for the moment. I'll try again later. Could you please check in the meantime if the result is the same with the latest SUMO release v.1.19?

Hello, I tried to run the simulation in the latest v.1.19 but still encountered the same issue.
![error-1 19](https://github.com/eclipse-sumo/sumo/assets/96480310/de0b03dc-cab8-4fab-aee6-af173b6180ba)

**Comment by m-kro** [comment]
@hhhhhhyl I already confirmed that a few posts before. Apparently it has nothing to do with the intermodal edge length even if the assert invariant is violated.

**Comment by hhhhhhyl** [comment]
I'm very sorry, there was an error with the small example file I uploaded earlier. I am re-uploading the small example file here and have found an issue: when I use the "duarouter" command to generate a route file from the trip file and simulate using the route file, the simulation can run normally and successfully output results(see "small example (successed)": https://drive.google.com/file/d/1wXwo7suspBuOPTd4BPyzyD8krusXIW8N/view?usp=sharing ). However, when I directly use the trip file for simulation, the simulation will suddenly terminate, same as the previous error (see "small example (failed)":https://drive.google.com/file/d/1je3CC90u1akgBpqGbMGE8zIe2kJFDlBb/view?usp=sharing).
I hope the files I provide can help you correct this error as soon as possible and I urgently need the complete output results without suddently terminate. Thank you very much and I'm looking forward to your reply.

**Comment by m-kro** [comment]
Although your network invalidates some routing invariants (see post above), this was not the cause for crashing the program. There is at least one non-continuous bus route `bus_浦东25:1` with intermediate edges without connection (from `-148212569` to `303902223#0`). The SSM device relies on complete and valid route edge data to compute conflicts and gets a nullptr at an unexpected point.

**Comment by hhhhhhyl** [comment]
> Although your network invalidates some routing invariants (see post above), this was not the cause for crashing the program. There is at least one non-continuous bus route `bus_浦东25:1` with intermediate edges without connection (from `-148212569` to `303902223#0`). The SSM device relies on complete and valid route edge data to compute conflicts and gets a nullptr at an unexpected point.
Hello, is there any way to ignore the errors caused by the non-continuous route mentioned above?

**Comment by m-kro** [comment]
I have added a workaround code block which stops looking for the conflict lane of the foe vehicle in case of incomplete routes. You can get it with the [development binaries](https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version) of tomorrow or build right now from Github source.

**Comment by hhhhhhyl** [comment]
Hello, I have downloaded the latest version through  https://sumo.dlr.de/daily/sumo-win64-git.msi, but it will still stop running at the location where the original problem occurred and display a SUMO stop working prompt box.
<img width="886" alt="屏幕截图 2024-02-06 140243" src="https://github.com/eclipse-sumo/sumo/assets/96480310/f1c60185-7831-425b-8eeb-137a6d39c091">
May I ask is it the issue with the version I downloaded or other reasons?

**Comment by m-kro** [comment]
So probably you have installed multiple SUMO versions. Please take care which one you call. Please run the command "where sumo" in the working directory you start the simulation from and check it actually is the developer version. If not, preprend the full path to the right executable.

**Comment by m-kro** [comment]
@hhhhhhyl Can you please give feedback whether you really used the recent development version with the fix? If not, we can close here.

**Comment by hhhhhhyl** [comment]
Sorry, I deleted other versions and only downloaded the latest version. I also checked that the running version of sumo is the latest version, but the same error still occurs as before.

**Comment by m-kro** [comment]
@hhhhhhyl I just ran it again and it went way past the last time step in your output (t=21795). You could run sumo without arguments to get the version and paste that information here.

**Comment by hhhhhhyl** [comment]
Thank you for your patient answer. I will try again and reply to you after the results are available. Thank you again.

**Comment by hhhhhhyl** [comment]
Hello, I have confirmed again that I am using the sumo version as shown in Figure 1. In addition, I ran the previously uploaded "small example (failed)" data again, and the simulation ran successfully. However, when I replaced the route file with another one (see https://drive.google.com/file/d/1wXwo7suspBuOPTd4BPyzyD8krusXIW8N/view?usp=sharing), the simulation terminated again, as shown in Figure 2.
![Figure 1](https://github.com/eclipse-sumo/sumo/assets/96480310/0e433323-07f1-430c-b4fe-8d4f63fc674f)
![Figure 2](https://github.com/eclipse-sumo/sumo/assets/96480310/4228d84a-30c2-4a31-afcf-1528aa4043b1)

**Comment by m-kro** [comment]
The other scenario runs as well past the time you showed in the screenshot. Did you copy the development version of sumo into the bin directory of the release? If not, there is a chance you used the release version because you started the simulation from the release bin directory... I think we stop this here. You can still post here if you are really sure there are more problems even with the development version. Then we can reopen the issue.

**Comment by hhhhhhyl** [comment]
Thank you very much for your patient answer. I will check again. Thank you.

**Comment by hhhhhhyl** [comment]
Hello, I am currently using sumo version v1_19-0+0790-688b415f482. I would like to ask what "development version" specifically refers to? I am not quite sure what the difference between "development version" and "release version" is. Could you please give me some guidance on how to use "development version"? Thank you again.

**Comment by m-kro** [comment]
That one is a development version which should have the fix included. The question is rather whether you still have the release version and use one of both without knowing which...

**Comment by hhhhhhyl** [comment]
Thank you, I should only have this version and there are no other versions available.

**Comment by hhhhhhyl** [comment]
Hello, I downloaded the latest version of SUMO from a brand new computer, but still encountered a sudden termination of the program (specific files and error information can be seen on https://drive.google.com/file/d/1Ybvqbj3bZimmMsShQOo6d33GMA_yRdIQ/view?usp=sharing). This computer has never downloaded SUMO before, so I don't think it's a version issue. May I ask if it is possible that the program was terminated due to an issue with the SUMO source code?

**Comment by hhhhhhyl** [comment]
> Hello, I have confirmed again that I am using the sumo version as shown in Figure 1. In addition, I ran the previously uploaded "small example (failed)" data again, and the simulation ran successfully. However, when I replaced the route file with another one (see https://drive.google.com/file/d/1wXwo7suspBuOPTd4BPyzyD8krusXIW8N/view?usp=sharing), the simulation terminated again, as shown in Figure 2. ![Figure 1](https://private-user-images.githubusercontent.com/96480310/305140314-0e433323-07f1-430c-b4fe-8d4f63fc674f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTQ3OTUsIm5iZiI6MTcwOTU1NDQ5NSwicGF0aCI6Ii85NjQ4MDMxMC8zMDUxNDAzMTQtMGU0MzMzMjMtMDdmMS00MzBjLWI0ZmUtOGQ0ZjYzZmM2NzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEyMTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZDViN2QwNDNmNmEzMjBkYjdmZDA4N2JjYWE0MGVlMDE3YjUxNTQ4YWVkYmEyODg1ODk5MDZmYTRlZmZkMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h01BKL6nbe45NEa79YtdanJiUgfnn2ArcuOfcFb3IFQ) ![Figure 2](https://private-user-images.githubusercontent.com/96480310/305140354-4228d84a-30c2-4a31-afcf-1528aa4043b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTQ3OTUsIm5iZiI6MTcwOTU1NDQ5NSwicGF0aCI6Ii85NjQ4MDMxMC8zMDUxNDAzNTQtNDIyOGQ4NGEtMzBjMi00YTMxLWFmY2YtMTUyOGFhNDA0M2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEyMTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZTNlNTcwYzI3Yjc0OTE3MTJlNGRhYzUzYzNhNGQxZmMwMDE5YmRmZjZmOGMyNjQzM2ZkN2Q5ZDdmYTVlZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w717ccA568Gmvmw4iR4uCj658dVFANNp4XfHF6-ax14)

Sorry, I found that there was an error in the link I uploaded at that time, when I replaced the route file with another one (see https://drive.google.com/file/d/1SH1RQa_vR4oAYeNitp1mZZHsIdQN8i0y/view?usp=sharing), the simulation terminated again, as shown in Figure 2.
