### ISSUE TITLE
Net edit won’t save

### ISSUE THREAD

**Issue by Davedasun** [eclipse-sumo/sumo#14200]
I am a new SUMO user and is using net edit to make networks but when I save it says “could not build input file ‘(file name)’ (Permission Denied)

*If possible, upload an example that shows your problem.*

**SUMO version : 1.19.0**

**operating system: Windows **

**Comment by palvarezlopez** [comment]
Please check that your file path doesn't contains strange characters (Kanjis, äëïöü, ñ, etc.)

**Comment by Davedasun** [comment]
![Uploading image.jpg…]()

**Comment by Davedasun** [comment]
![image](https://github.com/eclipse-sumo/sumo/assets/155702967/a734709a-8a5d-490a-a414-c90df49a76e6)

**Comment by Davedasun** [comment]
> Please check that your file path doesn't contains strange characters (Kanjis, äëïöü, ñ, etc.). If the problem persists, please send a screenshot of the file path.

![image](https://github.com/eclipse-sumo/sumo/assets/155702967/f26949c1-7224-436b-b841-d6d5e546db50)
