### ISSUE TITLE
Inconsistent behavior concerning edges blocked by rerouters

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#14203]
If the vehicle is already in the simulation when the blocking interval starts there is no error and the vehicle can simly use the rerouter but if the vehicle gets inserted while the blocking is active, I get a route error. This is well documented in https://sumo.dlr.de/docs/Simulation/Rerouter.html#vehicle_behavior_when_closing_a_street but still somehow unexpected and especially hard for the user to check beforehand. Maybe we can at least introduce a command line switch to change it. see also #14195

**Comment by namdre** [comment]
commandline option **--device.rerouting.mode 8** now fixes this problem.

**Comment by behrisch** [comment]
@namdre should we maybe change the default here?

**Comment by namdre** [comment]
maybe, yes. But there are cases were vehicle behavior would degrade (be less reactive) to permission changes and this might break existing simulations.
