### ISSUE TITLE
Net edit won’t save

### ISSUE THREAD

**Issue by Davedasun** [eclipse-sumo/sumo#14204]
The network I made won't save, it says that it 'Could not build output file'. I have not used any special/weird characters and have only used the English alphabet in the name. I am trying to save them into a folder named "networks" within SUMO

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAsQAAACrCAYAAABhaIolAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAACyXSURBVHhe7d1tjB3XeR/ws0tFlGpFWvuDYKexLa9EWvG6TcFmgaYSalTxlYQoQEW3mxZIFDCuXAosIjC1QiBb1EYcgAUYOWFVlA0jxV5XCdCaacgCoSvrQgpU0IgNomxSex2ZlFaSkzSO/UGULb5IFunOf+489z5z7pkz7zN37vx/wOHMnHk7c+bcmWfPPbtc+EHA5JBz89zbU3mscyIiovmxsLAQzVFeWesuc0CcJ8jKui0DNyLKg88MmlUMWIial+dzl7ZtakCc5wWUZVu+0OrHOiYiIpof/IErmyz1lLRNYkCcJ6hK27bseiKqFj9zRAQMtKirUnt8Petd65wBcZ6XpW/bouuoHNYtERHR/OAPLn55g1+h100FxFmDqbTtktZnPb5WZB+iJrBtEhHlxwCP0hRpI0n7ZAmKYwFx1pe7bzvXuqx586TN65v3uqV2sX0RVYvBIdWtTBvrQvt0lTFrnsgdECdt48q3865evRrNTWQ5J+XDOqV5xbbdDV14gRJ1CT9Tbr6g155qzrzgBRO+YbK8aFzbpOVh3t7GtY9P3u2pONY1ERFR9VxBGCXLW1/29rJsTzWdlzkgdq238+xlu0c4bftZM+vlmyesayIiaoIrMKJ6NFHX9jmSlu2pGOcHgQiEC0lc65Gn8+1tktb5tpsn83pds4r1TUTUH3ZQQ37zWF9Jga3Qy/a8a9vUgNi1ztfzm3ce7OV5MI/XNMtY30RE/WEHNOQ3j/Wlr8kV4ArffGw5CG4TIwlX4KrzkuZBlrNsb+87D+bxmurE+uoH3mdKo19QREnYTvKZx/qKBbOO+aT1oJcXFxfDaWJA7ApYXXmQNp81b57M4zWlcf0VEZpNfWyfRHWyX7g0u7p4r8qWeR7bp1yTvjbXfNp6wLwzIMbL0n5h6uW0eV+ea12arNu5lNm3jLbO26Y+XnObWN9E80G/mKl+fazvLl5zWpllvd7OzvOtA50XC4jlBWu/aPVy2nzSFDAvSZazyLrdLOlimaGr5e4i1jURtU0HB5Suq/XVxXJnLbNsNx76EC3r/e085zoJiOXlbL+kk5Z1vp3nmkqSZT1Nk3W7qrV13jbxmqlOrGtKo19UNNt4r/Lpan21Ve6s55Xt9FSSLPumgPkwIJaXlOtlpfNc29l5eqqT5Pmms2ZWy5Wmi+VmXefX1Tojojj9YqZspDewL9psI7PaPqVcvmlSr7FrunDlypXxW9V+weplmfflYSrz8gtWrnVJ0zrUeew6Sf11SVfruow+XnNX8V41R14yNPv6eK+6eM1tlrnMuesstxzbNU1ahwA5aV2mgFjn23kyRQDnWpc0L1OdX4c6j+3T1nnLYrn7gfVFVC15qVI2Xa0vljufOs8rx9a9wJKnp648V8/xOCC2X5B6Webtqe4Fdm3jmk8KnOtS57F92jov9PGa29LFnnzqlrY+V/KioNnXxXtVtsx9vOYy2jp3neeVY8vU7v3NOj9eTguIdb7MZ+0N1svY5/Lly+bVV181Fy9eNBcuXDBvvfVWuD6NHKdPGGg1p4/ti4ioLAkkqH5l67qL9yprma+99lpz/fXXm7e97W1maWnJXHfddePgWI7hm4dwe1dA7JqXqQRqWNbr7HlZluD5O9/5jvnWt/7a3Pwj15m33fBD5oYfvtb80LUyKD7bRZdT1zlGxx1dbZzrjK7tqFlJLSH9HvLuUZXYnvpDP0nS7nvSE6oObIPl1VeHdbUEu8RNtrhqja7kzTevmte/96a5+Ppb5lt/dcm8853vMjfffPM48LUTuObDgFiCVyHL9lQHwzKVZC/r9Morr5ir5oJ5z/IPm+uuvybcNq6J21HnORa8Hwl9Zt92VJzUcdb6HW2PrePtwrX/ZAvevWzy3YV+YlvqlrxPGNust3W2x3Lqqb/pVlP2PKMjuo7S3adx/GouX3rLfHPrdXPlre1meXk5NoxC9xpLnp6f+rslCGBdJF9P9baYl95gndAzjGD4/StvN9c7g+F+ydrosF3WbWkif52hDUvy7T9p60RE3aCfb75ENB/Q6bpzZcksXvOG+fa3vz2ORUHHpnYeTAXEwt5YlsGel0BYliVdunQpHCaBnuFwXfivS/IaorzK/iCh9x/Ns33mg1rLkvqs79ffNXgGVPUckGNVeUyXOo9NTZi+g/YzNG9yS14z65Lb+HuWbzB/8zffCuNQHZdK0nGrWNQZ9krZUeh53RsMMq8TfoEOY4bRMxw/skv6FsV193ZTMWXv+OTxUWe7pH6TVlZlotmj74vrecJnTLfVe//ms3XgqqpIyRB3vvNvXx/Goa74FOw8Zw+x3kCWhZ2vk5Bl/DUJ/AJddpNjVIMviT6Y3OF4+0m688ktwm5/VbdHorrxeTcNdSKpLvocdsqCz5ruwT1r5r7JmfKmJNIq87RQP9fZfakZf+uGa2I9xEKW7eQcQ4yURO+sYRm9xrrnGH9aDQFxvsuvqrKquc1Z8bHXnkmd6rswynXdl/j2kgTWSiIiotmmn9lNptnnK63r3ThvEH+iY1ZiUolRXbB+HBDLDjbJk0BXw7IdBOuEvzN87fZt0dZNavpWj+ol6axYK4nqMV2/k7vhui/T96IPjweiPpKnw/Snvjr6HDplxedPMXnquL/qbV2zew+2B/Hnm2++ORWbuuJWCANinWFPQedJkmUXvc0EbkkTH/q2Hiyj6+VjrV3uFum+L0nbEnUXW3V15J0lqQjXe9BW9Nh9x7bevtm/BxKPuuJVOz/2S3VJXNu4eoXdUbf9MMny4U8vk1udDxb7OlyylztrSeu8onk1uQvx++Gqy6ItjboGd7oPaR7Js7fJp6HrXEXPb98XfT1Fj5lFncemLkhuYfZzo2jqBh2j6vjUzk/8s2sgG2tl8iamb9GffOmMuXH7B8cpOMJoRWajY/74j91jDn/6d8P5Kvybhz8VHtOGvJdf+otoKS7rY8i3nb76pO1wnVmu9b9//gvmpu0/Zj7yMx+LcqbhOH8vus6sx9X+5Ev/O3Z8OVa7dM2NatRVl5O6xlpJRERdg6eZTkI/2+blGee6pjrT7OteiesnsajEo0mxKfK8AXG9Jrft5Zf+yjz04L81331jM0z/9/kvmj/4/P8Mt8rrz/78i2b/x/9ltFSNl7b+IggQnwjmpitx2mgbXJkdJLr4Gi2OJKmMX//kfzB/9vzT5g//6PEoZxrq7E+DupsX0/U2qWlXnfu2p3mA+9mHNI/k0xn/hNbLda6i57fvi76eosfMq6nzzDP7s2bf12JcRy2asrHbgutIZVM3tRgQT/z1//u2+anBHdGSMbe870fNP/vZn46W2veZJx81n1j/tNUjnH7jszaLupvPS1vfDOr03dFSvyS9BpLqnK8N6ra6nyZdhrrRKQ2eBjoVYZ/HdZyix6b2ZWlH0/K0wmrZba2uEugrzJvaM/6lOpvdrYx5GWchZBud9DjirH7yjl3miaP/1fk1PfJu3L4yTi+/9JfmDz7/BbP7Z/5VtMXIjds/EAasyMfwC8CwBmyLdUj6+KPjTvIx9UFQ/Mu/9OvRkr5po3k5FhJ6hpHuuevnzTPDU+Fwhd/+T0/GhhHgnBiOIbBOAm5sL0lvg95m7Id8DIPQJN8exoE8mWIbGT4hCeUE5OtzaSibbK/Pi+0l/ytf/tMod/aoFhtNR5I+etlbLhHNvqQXbdITIAs5ZlrKqo2nTp7yUbJ89VhtraPd5EnJXFvbqRnVt0s7TkVyxakz0UMMGCrx3B9/JQgoV8YBLeCrfBlK8Zknf8M89lufDXuPt178ZhgcA4LeB/f+C2cv6O//lxPBvl8Ph2GglxdwfMwjHykL6bHGuYRUJQJvHF+O99CDvxoG+V989vfMTw3uNK+98efmoX/9gFm+9T3jgPWzT3w+HIoByMO69wXlR/D5mSc/He6D9HI4XGMSyP+vP/5ymP9PVQ86gtSN4HjIt+sAeTJFXWI/zCM9FZTvN/79b4frkyAI/89PHBzvg+EXgDKhbJKPcnVD8x9vIppVfQsK9fMvzzOQwfP8mdxTvg1HZiYghuN/9DtBQLlp7rnrgVjgKb3DH33gV6IcY37xwTVz4g9HY14R9K798/vCedtv/cd/F04RKL5v+d1h8PmVL/8f86mDHw/zIeuYYxzrow88Ei2N4HgIbP/u7feMe4ixbPfUwj/6x/8gKPPT4ToMEUF50EOLvJ/7hd3jfXSw+yu/+lAs2MSyhnUIUvOM/5Ue33vv+vkoJxl6uLGd9ARj+AXKjPPqstjlQoDfBa7HPB/9RPPEF/wVCQVcTwjfObKQY8pxdKpC2adaVeWgamsS97VoSpd/jyq019ZiAbHuShbSpay7lmUb2V7y7HlZzuuLzz4ZBrmAQHjU+zrqIRb3f+Qe89knjgVB5KiXGD2yefzou98VzWWHoBqBNHpHdcCHwFZ6hyW5eqvv/8jdYSCJAPgf3vkTYcJQg+eCvJ9Y/TvRVtNuCY6fBD3lCFJdAbgLgmHp8UUPcRbSCyzpJ+/4+2H+u37k5nDq4vsFvlmjP+jNfeiJ6lDsmdsPqBs7Cf3aT0s2fRw97+La35WnpR2T2pX//mAPSW1LKkNaq6xH9TWi41F7mITkSX4DPcTpF4jeYD1MAj24CDIFfskOJEgG5CEo/eVf+pT5uV+4P8rNBsGwfPUPkyEJ6U0AvcmfWH80DERBAl/doy0QMMp2gG2xjKAYQzCQEAwjD+vkWHqcLoY03BEEzkn2PPizYWD747ffHeWkk0D22H87GU59MORDD9kQCNIxfEXooRcIztGbXCfcqfIf2EnbnD5e9R9MmiW4v/OY+kA+reWfACNVHUek3Qdd/qznLnpv85wjTVXHmRfVfObkKG2lbFx71pHaNRNDJhAYPvTg+nhoBMYS/+Zjo6EOGBss+TpIBgTCzwy/NB7fmxW2x5AFGeKQF8b4oldWHg//4wu/Gw6lkOPJL/xJgIvgUILcu9Rf0xC/GAS1AkMfPvrAx8dDFDDMQg+hcEGPLcqkz5MEATSC56wBK3p6Pxn8ACDlQQ8z/OZjnzDPBnUv+Sjn7JOXg36wuz6USDTf+HKneZD03LKfc1WYx+eiXX950vyRVtPXp+PC97///R9IFzKmkuxlnfRwCVm285C++tWvmjvukiC27irWx9eNNf286NH8Jz/9YPg3jLPzHTd+ft9Hxz6Kb1sqL17frG2qG9tYPeSTXLZ+098P6ewylDlm0vUkHdN3/a592B7dZr9eqmipxaTVTR0lq+5+nHr2L80HP/hBs7i4aBYWFsYJy1N50T4NaKrB2edJPy/+nJr+O8jZ+I4bbyC+5tJUrdAI65ua1d5rbL7hk5z304x7YackcnxXsunj+I6ZhWv/ssekLsPdb68FuNq7VlfJ5KqzpOpM/VKdTXp7hT0vPcOyLFNJcfZyFfJXCnqEZXiDDJnAEID8VF2o5OIrpd6n2tvbH3laQdI9orb4PjnzgJ/qduV5OkBaW3Stz3sOHzlWlcckv77Uszxrs6bsXHunpWr4750dlwrMI37VWhhDXFU1FH9YYGyv/osQ+HNv9cl/vXwENkXaEGuciOYR3j86UTL9Psia6hU/g30vi6QqTUpX9MhVl6ismfilumrZjbTuRju6pXKWtLO51tddwj7I+3Gf3p53oT2o+3mu/zwtk6qX9+mQ1hZd6/Oeo258njWj+nrGESXVQ5+hTCqvmqNU97kbB8T28Iak7mXJ10MlQOb1VK+PS8qvSrU3LausZ2u2VORTd0ukvmMLq4d+xuvkg3thpySuY0uy6eP4jlkHV3lceVSf9PqWlpMluVXVrpLPUFTRklVTkvSzIw7VQyPs2BTrZH0DPcRJl930g6NOuBY7+Unjr755EuSp2/S7Rf1gf4arSFS9Kp+addyjpu+7PO3yPPWoKeXvSD3tSZ5QZVM1XEfOkqrV0JAJfkipHWx5RETUXfKDji9RFRIDYnu4g152rZM8TO3hFCN9vol2XVCT+tTSqAz7+VQkUf2qfJ5Wcc/sY7iOiTJXVW45VpXHpLo0c4fyP39kj6pTMa4j5UnpdFyqY1aB9XP4S3Wzig+uNmX7yBCVxZbWDDxPXclHv0AlVcV3TF2utDKmce3vO2aV10hu6fcUW2RN5bR/v7OWoPy1avLZc6XsGBA3qtom0Cf5mzbE6zv//kRFsKXNlmJPj/rU8R7wHVOu305UXvX3EkfMmtx89zZ5r2LSS+Oj93alpi288cYb4XntrmTdpSxdzUiu+aS8r33ta+bOO+8Mj0FERERE1JRTp07F/utm33/hzB5iIiIiIuo1BsRERERE1GtTATGGO2gY+iD0OhkikZSn84mIiIiImuaLTXUee4iJiIiIqNdiAbErchZ6Xn5xTsOy5OlfsiMiIiIiaprEojLawRWbSh57iImIiIio1xgQExEREVGvjQNiVxey0L9Y5/olOz2EwtctTURERETUBMShEpe64lM9ZQ8xEREREfUaA2IiIiIi6jVnQCxdyKC7k13DJfS2HC5BRERERLPEjlkx1TErsIeYiIiIiHqNATERERER9VoYEOvhDUXmJdnLkkdERERE1CQ7JpVkQx57iImIiIio1xYuX74chsp29KwTBh7b8zIY+cqVK+NlWSd5X//6182HPvShcLsmHF5aiubc9p8/H80RERER0Tx77rnnzAc+8AGzsLBgtm3bFk4XFxfHSZYx7XxArIPgT0bTJL8WTYHBMREREdH8yhMQd3rIBIJhBMGS0uht03qTiYiIiKgfcgXE6PXVU+klBjtPr6saglkJhouSoJiBMREREdF8suNSO5aVaed6iCUQLhMMCzkOg2IiIiKi/upUQFy2VzgJg2IiIiKi/hoHxNJlDK75pCmgGxrLrkRERERE1DQ7HvVNO9ND7O0dji4ok4Rt2UtMRERE1E+dCIgzBcNZguKUbRkUExEREfXPVEAs3cdgdym7YJ2st3+Dr3b2eXznzbMtEREREc0FHavKvF6GTv1S3ZSFhWhGiS4sxpXn2peIiIiIeicMiO0oGfS8sLdzbY+pa31R3uESkBYUu8rgCYaLD5vYMkcGS2Yp2DdMgyNBThlDs39pYI44D+JbV7WC59o6Ygbj/WblWio03D+5z5mv1SXYfqqtpLUlnGN/8K8N+Wq/Ltbr1DUsmQEuolQdJ9s6MjBL+6drMkbutZRFGe6Xco7Kg+XJNlnv05LxF0Fdb6weqpBUxoC67qWkbSqXUmdTFaXqpjVZy+Cp65kzC/VahC53MO95D08++9hn8lms/blZ5DNc+efeVvJ+Fyrf5Jzx52a17Ng06W8RQ7d7iEVSUKwudKyOnuGwMewyZw+cN+fPR+moMU9148kXKPlhcFneZ4bnh2bfcrTcmKquxXecYN3ahtlzLLjPw31mucprzdSWBua+PRvmpLN9rZqDZ0b7nTlozPresj+YtWFyDUhDVGwd7Smo673Hd5szhwdRhgvu9WZUnmNmZX3vuE3gIX5o55monKOyDQ6fMbuPyzbZ7hOStwha5fWQUEa0wzVjjkXlO39mpznXyPPMX2erm2spPzy41PB8K8R3bXnNyjXlNSPlnvrsN/jcLPIZbu19mlHJ8sWfm+2Zj4AYsgS6dQTD6M3bu25WguAo9lILGsi+rC856qBVs/PWaLYy2dvS4OGDZjPlzbq874DZc/q4eapzL81mbD113Jjd9xrvM3zrnNlc3W3uDTdCQHPanH0R80NzcvOgOTr1Blg2+w6smPXHRvcmy31qm7OML541p1d3mnETb/B55quz3QeCdYe6+EPeSBfaQx/4Pvt8brYh/txsy6LuLnbNp03lbxCDnsp8o3wBby3BcGDrKXP89B5zn+9lEfb6Tb6SmfRw2D8te356VscYHDkXZdqi/Y8kfMXrLAf2WTMb5rRZ3xXkJ3W/vKjPL8f0lb/stQRy1xum9rVE64Z5yu86joivGx3LPo4SuwbX16UDcxi9zJhNa0v4Clu+Aly+1+zePOQ+p9OojPv3DyblSKzfQOweHVHXN32cybCBII0PEtWJqnesCr+mjJbzfUWWt47jw05i1xbaMqN3Imp+tO24PHY9G3k5BkHwRnR/hifNxspZ85icV381e+tOs7p5brJ/rvuUVm5dD9N1PKnThOO46spVxsF9QVCwbvZOFdy+D/7yeO95Uvvz1dmt+8yBFVe5IlPXhzLFP8tor5N6ta4H+8vKpPJF+8Q+S2NYNzpPcIDpe+C8tqgMmZ7bbV+TVr7cE57PoJwn97NEPVtj9Gc/g6nrALu+8pQx2jZcdH1OXXl6n0DKfUy8J5o6xtR72HPN7mP7yqfak++c+rlZA1d8ag+fmJ8e4jbpnpQpQUPZNer1G331eNBsrqmGk0n8GEeDF/RGtGZa8LA5e9/oXMf2mNPrj0WNMakcwUPj/DGzR74ycn53GxzzkDFHo/2M+to4v6zXUqTekq4lb/l9dRJfF36dnwjXcNzsjr6KC3Yzh9IqztuWtNFP1Mc93RhbRw6ZjXHvJpw2mzuPBmU5HFyFr37T7pE+TlAjh6NjoF429Mte1XvQFjfWlsze4GijutBt0xa9MKMH5+Rh75JQx8PHzPrKsahcriEJL5qzp1fMjrBugrocYjgEyhMcD0MFxi/SYN3RICQOy4MVo2sObWyandF5j+kgbXmHWTl9NjhDuJBwn/Q1ygsDL8Jd5vhuGYaRZShFQtt2Xn9Se3SVEe0cX2PuynAPtKz33Nf+/G17cDg+dGXCdX23Tn2WB/cF5ZJe2uAHm81VMz5X2HMYfvXjKx/EPwMjuH/hOJPRM8N5DzztIfG5PUPXNKVcuSeCekn8DELWdpWF/uxPiz83XdchFWbXV4EyutpI6rMr/T6674kWP0b8Ge+/5mzHdu3vO2cg9txsx3wFxL5ead+6snw3EV+5Bo+Aca/f8j5zYPy1a0bh17YHzcPRMcKvdEazDsHDRjZEL09w9nNoi6XKERzzaPRwKlJ+Leu1VFFvYxWWP4/wGoIHiAQ+axtBU0k5sa8tDQ6PxixHi7i/K8efsn6inpxv1/qK9VJZnfSK+Oo39R6p48D4l6/Q+6Opeg/botpPt80p0QsTD9MgOd/DIqmO0duwsZbcOzIlCACDB/eaHfSiR2Nv9JIL0n0nVXC458B4zBwCksm9vdXsXFXX5rxP+hqj80XfEBzINRAvoW27rt/XHp1lRJASlC984WYNijPec1/7A2d5BO6V4+tV3/VpqidqeHLT7D6wG9FjsKx6DtPKp68rcnzv6IeZcXtNaoNJ7SHxuT1D1zSlZLljEj6DoYztqrBJWWPPTe912PVVoIyuNpLUbkSG++i8JxqOkfSMT7nmTMd27e87Z8h6brbAGRAnDXfQXc56Cr68RmQ5Vx3lwVdgq1X9okQXbJlzm9FsJzVd/j2TX0xC8kV3udvSwNy3sm7icUHwwLIDrTohYAw7kHC+M+bgapTfKEcdBy+JYTB/1OwNH8rZezjj7LGGsZ64RHYPlOs+1UG17cTrT2qPnjIGxzoa3Nj0665SSp0NHjYHnb9gl+Hzhs+ZwTAYjAPfbe4dYDn4QRQ/kARzVkyY0ekgrcaDvsR7kLc9zNA15ZLj2dc633OzxutwtZGKnl3llL3mIvv7e+6LQhxqx6euPAyfmI8e4uiCYjBm2DVu2LVtKfgKbPT1SKzhBoHCkbBx7zArRgU5Qf4hGYcY/kSkfrLDuMRoNib8KmHyAA2/0hnNZuctR5rTk6/4YuNcM5Zfy3otVdTbWIXlzyO6hsnXTWlS2lJsXN1I4V/S8dVv1nsE+pevwroNc5uTUsfL+4bmTBDMbU53zVi9EcPR17T4fm9tMuZteceKOa1684YnN8wqvn5G78h4eMiWOXJow+yRD1PYExIf+pLpPkU/EGVvL5DUtkdi159SV7EyDoM2N94MvYynR9dd1WfG1/4i/joLPitH0XOtvpVIub6JZXMvOlD3HjKb4Q87WN40Jx87O/nhJ0P54lbN7qNDc8xM9+y52mDmz+3MXVPwOdFjRZNkLrc+nvszWD37s++R+TrKcbWRxGdX7vvogGMkPePLXnPS/r5zQuy5mbGdVWzmA+L9wU8XvxbNOyUFwyJnUIxz4Zy54Kvs6GtF/EQXpr0m+Ck9XGkO63Xh2Br5CXQSAIXrTuLnKhd8lTTZbm/wE797Ox9fOQbhb8+HX3E4fxxdNStnRz+tLoVjgPKWX8t6LUXrzXUtRcqfVidZjK4hOMjo+Ehpx/K2JQcEUbl+aUv420Pm9oaeOrNudoXlPGtWGu8hTqjj8TCO0Veg08MQogAiDCZH4yQ3Dz4cHG1gHj64adbkB4/gfpzZfXx0fUFaC8KD0bhxnFfGFu8Kx/yNO0HwQ8LKjuAMytR9Ul8pBmkUcATtMRxHObmW9KaX0Lad15/SHnUZBzvM2XH5Rtc3uu4in3kXX/uLpLXtqOd6Iun6pj/Ly7j5wQ9v8pU2ljc3NidfcWcpn8Poz0cF50f78bXBzJ/bGbumKC9d9nKPeD6DldOf/TRJ11ERVxtJfXYVu49xwTESn/Flrzn53nvfK67nZsMWLl26FEaH8tciXEnW6anMX7lyxTmP6fPPP2/uuuuu8ERlJP7nHMF5piT9NYmM2xYKiGmG4SfNQ2bnmRn+G45lBQ/QwbmHU37Br4StI2aw66w50MQQjCbhujA+ODbOuiy82MODTre3yu9TDW277raU16yVp0rzfG2zrpbPPhXneW6W9Oyzz5rbb7/dLC4uhmkhiPu2bdsWTrGs57s9ZMIOaB0B7liebYm6ZHC41pfq8LH1+N+knRfoYUTvb4U9PsP96E2d/LJdTM33qRKzVsYu1FlR83xts66Gzz4V531uNqgTAbF32IQEtlkC3JRt2TtMBPhpPfqqK0hrG3usv1YxPzBOr8pfkgn/BF2Vv3RDRLWo+rNPxc3KczMcMoEhDnbCkAfQQyBkas9LwpAJnf+Nb3yjkiETInHoRAUYDBMRERHNDwyZeP/73z8eMuFN0T5ERERERL0UC4jRu5tlCjpP54Nr+yp4h06UwN5hIiIiovmiY9S0+c71EEtQXEVgLMdhMExERETUX50cMoEAtmxvsQTCDIaJiIiI+m1Ruoxd9DrdtSzsed9yHSQolpRGb8tAmIiIiGi+2fEo/uiD0PkLFy9eDJeQKRthai/rPJnaCX9lAuQ/6MB/zPHhD384zGsC/gqFD4NgIiIion545plnzM6dO8P/gEP+moT85xyxvzCB/HkKiImIiIiIIE9AHI4hRoCLJPOuqWZv71smIiIiImpaUmyq5wHz/DvERERERNRrDIiJiIiIqNfCgBjjKVx017Kw5/Uy2MtERERERG3wxaU6jmUPMRERERH12viX6lxT3XMseYD5LMs6j4iIiIioaXY86opR2UNMRERERL3GgJiIiIiIei0xIJauZN2l7Opy1rAsiYiIiIioLToedcWoepk9xERERETUawyIiYiIiKjXpgJi3ZUs7DzXsiTAX6ewtyEiIiIiapKOT4UrRmUPMRERERH1GgNiIiIiIuq1Rek2dnUf+7qYMZ+0T9I6IiIiIqIm6djUjk8ljz3ERERERNRrzoAYkbL8t82uSFqTyJqIiIiIaJbomFbHtnb8unDhwoVw6erVq+OVmJc8O9+Vrly5MrUeeefOnTODwSA8lnbixIlojoiIiIionPvvvz+amxgOh2bHjh1m27ZtZnFxMZwiKEaSvHF+GwHxTTfdFM0REREREZXz2muvRXMTlQTEdhAs2+iUFAjLfFJATERERERUJwTEt912WywgliA4FgwHATJ/qY6IiIiIeo0BMRERERH1WhgQY9iDi86XIRQ2yU9aT0RERETUBgyH0Oy4VWJX9hATERERUa8xICYiIiKiXpsKiNF1bHcva7qLWW+n5/U2RERERERNs+NRTJNiXPYQExEREVGvjQNi3Ztrz+tlTfJlG3tbX08zEREREVFdJA51xaN2DBv+xxyYwX+kAZjKSvkPNvQ6V5L/oEP/pxxIL7zwAv9jDiKaWY888kg0R0U8+uij0RwR0eyx/2MO/R9xIOl8BsRE1FsIiB9//PFoifL42Mc+xoCYiGZaawGxzEs+/uvmu+++O9yXiGjWSEDs+j/wKdmJEyfMqVOnGBAT0Ux7+umnzY4dO2LBcBj8WsFwmKJ9iIh67b3vfS+nGaZERPOIPcRE1FvsIc4HQfErr7zCHmIi6oRcPcQIZEXSPHbUsC5pvb0tEVEXsAc0HYJhIqIu8sWqWOaQCSKiAIO9dPyhgYjmFQNiIqJAq8HecL9ZWloap8GRrWgFDM3+pYGZZG2ZI4Ngu/3DaLk5/KGBiOaVNyDGsAjXEAjkIcnQCRk+oeeJiLqktWAPwfDapjl45rw5fx7pjNl9fJcVFE8M9+8yx3efMecPN/8nLdlDTERd5YpX9TJ7iImIAu0Ee1vmyKENs+fY0OxbjrLMstl39KAx648Zuw9468jArJljZjjZuFHsISaiecWAmIgo0Eqwt/WUOX56j7nP7uxdvtfsXt0053Qn8VP7za7ju82ZFnqGBXuIiWheTQXE0n0s7GXN9Vt6RERd1Fqwt7rT3BrNxp02Z1+MZoP59fUNs+fAPtNO3/AIe4iJqMt8cSt7iImIAq0Fe6fPmnHcG7Nqdo4j5VVz8NhBs7mmf7mueewhJqJ5FQbE6AWWKBlT6RWWPCzbSdjbyDwRUZe0EuyFQyM2zMmpwcIYSrFiduju4Fv3meGxFbO+a//U2OKmsIeYiLpK9waDvcweYiKiQDvB3rLZd2CP2VjTQe7Q7N+1bszBh83UaOHBYXPm4KZZGxwxbXQUs4eYiOYVA2IiokBrwV4Q5J4/Zsza+O8Qrxlz7HziX5JY3jc0x1bWza4WgmL2EBPRvFrUQx7ykCESsp/uera7oYmIZl2rwR6C4vBvEI9S/A9JDMzh8/rPsmHzYLth879gxx5iIuoqHbOCHcOyh5iIKNBGsKf/d7qkNEvYQ0xE84oBMRFRoI1gT/cKJ6VZwh5iIppXmQNidCe7kubKIyLqAgn2OE2esoeYiLrEFae6YOjEwoULF35w9erV8VgKJL2MeSSQeZ2uXLkSTvW2knfu3Dlz9913h/sSEc2aRx55xDz++OPmtddei3IoixMnTphTp06ZRx99NMohIpo9w+HQ3HbbbWZxcTFM27ZtC6cIjKfyGBATUV9JQPy5z30uyqGsGBAT0ayrLCB25fuSBMKSGBAT0SxDQEzFMSAmoln29NNPmx07doyDXl+KBcSYgl5OC4h9PcQvvPCCGQym/rQ8EREREVGt7B7ia665ZhT8qh7icUIga7MHHeugWJJwDVBGniufiIiIiKhJEpfaMSzIuvCvTEjwKhsnkZ1ke6H3l3kcBxH3G2+8ES4TERERETUB8SeGSrhiVBfvn13z7ZhEAmrse91115nvfve74TIRERERURPw14O2b98ezvviWek1dgbEdi+xfSAs20noPATE/HNGRERERNQkdMgiDk2KUe00FRAjU09trnw7gBY33HBD+IfcL168GOUQEREREdUHcSfiT8ShWY0D4rQA2LUeeTrZeeiqfsc73mGef/75cB0RERERUZ0Qd7797W8P41Adl4Je1vnOIROyMok+gO4dlnydbrrppjBSP3PmjLlw4UK0JRERERFRdXS8ubS0NBWTgky1cP3rr78eRrQIbOXvCetk/41hkHnk2/8Zh95W1iOdP3/evPrqq+aWW24xN954YxgoY2wHEREREVERly9fDscL43fWXn755bBnGMGw628OY97+TzpkffgfcyBwlSSBrL2s83We6z/mSFqHP4Hxve99Lyz8pUuXYtv7pK33KbNvGW2dF1CnbWjzmtvSVl23qY/3mSiNq9epC8qUu81r7mJ9I+gqqo91nXZerEedIvDF0Ijrr78+HDOMeQl0dfAr28ufYpN8WZcYEIPM21OZd6WkdfZ+CJZ1ng+2KSrt2D5lzltmX2jr3G3VV1ltnbut+wRdvOY2dbXcbcELoou6WO6yZS6zf1v11eZ9KnNuBE9FtXXesma1viSQxVQn5Em+BMSyjKkrSA7n7YAYSYIiTGVZTyW5eoddyzrftR+mPmnrfXD8oto6b1llys1r7o62yt3mfaZ8yrQRvCi6qEy527pm1nWzEPwU1dY1l62vts5dZ11jvQSzkiRPphL8gmwj+Xp/zHsDYpl3TWVeJ53nW6/3l55in7T1PjhHUWXOW2ZfaOvcZctdVJn7BG2Vu826buua+6iPdY0XBDWjbF2X2b+tfctCENOGrtZ1mfqa1brGet0DjCTzmLrW2UnvEwbEOLAOVHWyA1hXnk46T7Zx9Qjb2/lgm6LSju3T1r7Qx2suo0x9taXN+urqfS6jq+XuIrxc+gYv1ba0Vd9tXnMZZeqrrX3L1vU8XjOOjW2QMC/LmOYOhpFcAbG9LPP2VK+Xnl69DZIcS6+XbfT2PnKcItKO7dPWvtDFcrd1n8pq69x9vOY+KvO5aBNeFH2Dl2IXtVXuMuctW+Y2z11Umc9UV+urzL5p9RULZoOEZTvJdnaS7fX+iQExppKn1+k80MuuoBhTPa97i/U6H2xTVNqxfdo6b1llyt3FfaHs/kW1dV5os76JKA4v1KLK7FtWW+dGMNKWMtfcZrnLKFPutuor7bx2QItlPTZY5+uk12M6PpYExHhBSqBqL+t5nZe0zjdEQtbb63zS1vvgHEWVOW+ZfaGtc7d5zWXwmruhi2VuW1t1hpdFG9o6b5vavGYJCIpos9xdbJ9l9i1zn6Ct+qqzfWE9Es6hk+QnrbOn46QDYiQJIPWyPa/zktYlDZHQ28g6pLqUOTbK2Ja2yt3Ffbuqznafpo/13cdrbgteLn1T5prL1lcf6xvBTBvaus9lr7fNc9cF5ZKE65OpJCzbPcZJ24bb2QGxnfDSTpu38/RUUtp2PtimqC7uC3275q7WVxltnbesrpab+gEvt74pc81t1RcCkra0VV9t3qd5vOZMQa5jvd4ulnfx4sXg/TYJVsEVwILM6/y0PHtd0rY+2KaoMvumlatObV1zmX3LKHvevtVXWV0tdxl9vOa24AXTN21ec1vnRhDRlrauucx529oXuljutH2TAlx7WU8lSNZpvL0OiEHmJViVPFcga8/Lsmu9PdUJeT7Ypqgy+6aVy6fMeaHs/kW1VddtXS90sa6hq+UmqhNebF1Ttsxl9m+rvtq8T32sLwR9RbVVX2llxrF1Gge2al5P9XpJk7wF8/8BYEXrUnORqRwAAAAASUVORK5CYII=

**SUMO-version: 1.19.0**

**operating system: Windows**

**Comment by palvarezlopez** [comment]
This happens beacuse you don't have writting permission in C:\ Program Files. Try to save it in C:\sumo_project
