### ISSUE TITLE
Check/update map service URLs of tileGet.py

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#14202]
Looks like `https://open.mapquestapi.com/staticmap/v4/getmap` is not available anymore? There is still a MapQuest service at `https://www.mapquestapi.com/staticmap/v5/map` which works with a key, though.

**Comment by m-kro** [comment]
Happened in 2016 (see [discussion](https://stackoverflow.com/questions/38315300/mapquest-direct-tile-access-discontinued) at stackoverflow) ...!

**Comment by behrisch** [comment]
Google API still works
