### ISSUE TITLE
How to obtain values of cumulative number of vehicles arrive at or leave a particular lane?

### ISSUE THREAD

**Issue by TGW795** [eclipse-sumo/sumo#14219]
Hi.

I'd like to use values of cumulative number of vehicles arrive at or leave a particular lane in python code, but I have no idea how to do that. Could anyone show me how should I do that?

**SUMO-version:**
Latest

**operating system:**
Ubuntu 22.04 LTS

Thank you.

**Comment by m-kro** [comment]
If you need to keep track of the vehicle count during the simulation (possibly at each time step), then you can use [TraCI](https://sumo.dlr.de/docs/TraCI.html) to read the vehicles on a particular lane. Use `traci.lane.getLastStepVehicleIDs` ([ref](https://sumo.dlr.de/pydoc/traci._lane.html#LaneDomain-getLastStepVehicleIDs)) for that purpose. You'll have to do some bookkeeping to decide whether the vehicle just arrived (not present in the previous step) or left (present only in the previous step).

**Comment by TGW795** [comment]
It worked!
Thank you, @m-kro :)
