### ISSUE TITLE
The content displayed in netedit is different from the content in net.xml.

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14215]
Add your issue description here.
Hi, I found that some edges in the XML file cannot be located in netedit when I edit the road network using netedit.

*If possible, upload an example that shows your problem.*
As you can see, there is an edge "3139883096_0" in the net.xml file:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/1cca4833-0a65-40a1-a100-f0dc71473609)

However, when I try to locate that road segment in netedit, I cannot find the edge. The Center option box is grayed out and cannot be selected.
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/2a5befb5-f1cf-4438-898c-dfc517aabf64)

Can you tell me how to solve this problem? Thank you.

**SUMO-version:**
SUMO1.19.0
**operating system:**
Windows10

**Comment by m-kro** [comment]
This is an internal lane as you can see by the ID starting with a colon symbol (":"). It is present in the network as part of a connection but cannot be selected directly through the locating mechanism. Usually the ID is constructed using the node ID as a base path. Look if there is an intersection with an ID like the part between the colon and the underscore.

**Comment by nudtdyk** [comment]
Thanks！
