### ISSUE TITLE
Cadyts usage

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14213]
Add your issue description here.
Hi, after building a traffic scene using SUMO, I want to calibrate the traffic flow in the scene using real data.

*If possible, upload an example that shows your problem.*
I found through research that the Cadyts tool in SUMO can achieve this functionality. However, when I looked at the official documentation, I found that the examples were not very detailed, as shown below:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/074ecf3e-f79c-48e0-9593-1b1f04cc929e)

I'm not sure how to use the existing real data, such as the parameters in the `<REALFLOWS>`-file, as I don't know the specific meanings of these parameters.Can you give me more details？Thanks.
**SUMO-version:**
SUMO 1.19.0
**operating system:**
Windows10

**Comment by nudtdyk** [comment]
Thank you for your response. I am puzzled by the following points:
1、How is the "link" defined in "singlelink link="1to21""? Is it the ID of two edges?
2、What do "measured value" and "standard deviation" specifically refer to, and how are they determined?
3、In SUMO, isn't the default type passenger cars? Is the "COUNT_VEH" property independent?
If you have a simple example, could you please provide me with a reference? Thank you very much.

**Comment by m-kro** [comment]
Please read carefully. Cadyts is a contributed tool and as such does not follow the SUMO terms exactly. 

- Link means edge and the given ID is just an example of an edge ID. Probably the ID contains the connected node IDs in this case, but that is not important. "measured value" could be the vehicle count. 
- It seems Cadyts knows more types of measurements, but here only the vehicle count is given. Nevertheless, you have to tell Cadyts what type of values you give as input by the attribute "type" as shown.

**Comment by nudtdyk** [comment]
Thank you for your patient explanation. I apologize for disturbing you.
