### ISSUE TITLE
walkingarea width and length change

### ISSUE THREAD

**Issue by way-thu** [eclipse-sumo/sumo#14224]
Is there any method we can change the width and length of walking area, I try to change it in the .net.xml, but it seems don't work.
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/807cf613-5206-4f99-9edd-1ef8bbef6f9d)
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/e719ffbb-af62-4734-84af-fb81cfc47bf0)
By the way, when I run the simulation, the situation occurs below, how can I solve the warning? my first thought was change  the width and length of walking area, is there any other way to solve them?
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/d7657411-dc9d-4eeb-9328-93fb651559db)

**Comment by m-kro** [comment]
`walkingArea` elements cannot be edited because they are generated automatically depending on the neighbour elements (sidewalk lanes, pedestrian crossings)

**Comment by behrisch** [comment]
see also #11623
