### ISSUE TITLE
vehicle lane change with Traci 

### ISSUE THREAD

**Issue by yuameier111** [eclipse-sumo/sumo#14221]
I write a code to identify the "HV_car"type vehicle that their destination edge is "E1", to escape them  from driving in the lane"E0_0", I call "traci.vehicle.lanechange" to remove them. but in simultaion, those vehicle perform "back-and-forth" lane change. is there any way to stop them from changing lanes like this? Thanks for your help.
add: cannot remove the connection between lane "E0_0" and "E1"

code:
```
def classical_car(veh_ids):
    for vehicle_id in veh_ids:
        vehicle_type = traci.vehicle.getTypeID(vehicle_id)
        route = traci.vehicle.getRoute(vehicle_id)
        line_id = traci.vehicle.getLaneID(vehicle_id)
        if vehicle_type == "HV_car" and line_id == "E0_0" and route[-1] != "E1":
            traci.vehicle.changeLane(vehicle_id, 1, 3)
```

**Comment by m-kro** [comment]
I assume the vehicle has to change lane back to the rightmost lane to follow the route. You can either try to change the [lane change mode](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6) for some time or the [lane change model parameters](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#supported_lanechangemodel_parameters) (especially lcStrategic).
