### ISSUE TITLE
Decouple taxi vehicle class from taxi device

### ISSUE THREAD

**Issue by JulianCzymmeck** [eclipse-sumo/sumo#14223]
Related to #12022 I created a lane with access restricted to only custom vehicles (custom1 which are equipped with a taxi device) and a  sidewalk for pedestrians to be able to access bus stops (taxi stands).
As soon as a pedestrian attempts to make a taxi reservation the following error is thrown: `Error: Cannot add taxi reservation for person 'HeadingBusstop1' because destination edge 'E0' does not permit taxi access`.
As far as I understand every vehicle type may be equipped with a taxi device, but this error leads me to believe that currently only edges which allow the vehicle type taxi may be chosen as a destination edge for taxi travel. But this limitation doesn't make sense when all vehicles types may be "taxis".

I want for this lane to be impossible for all other vehicles to access (since it's supposed to simulate a lane above the ground) but still make use of the taxi device. Is there another way to achieve this or is the scenario as described here an oversight?

Kind regards

**Comment by m-kro** [comment]
Lane permissions and vehicle devices are separate topics. Currently you would choose a vehicle class which is not used for other purpose in the simulation and equip vehicles of this class with a taxi device.

**Comment by JulianCzymmeck** [comment]
That is exactly what I did. I chose the vehicle class "custom1" and equipped it with a taxi device. But I can't generate taxi reservations for a destination edge which doesn't allow the specific vehicle class "taxi".

**Comment by m-kro** [comment]
Sorry for the misunderstanding. After trying it myself, I see a warning being emitted if a vehicle with a different vehicle class than "taxi" gets a taxi device. You are right this should probably be decoupled in the future...

**Comment by namdre** [comment]
the main ticket for this is #9812
