### ISSUE TITLE
When converting xodr to a sumo net file, the connections are lost

### ISSUE THREAD

**Issue by daqiu12** [eclipse-sumo/sumo#14226]
Add your issue description here.
Converting xodr to a sumo net file，in xodr intersections, if the incoming lane has two lanes and the outgoing lane has one lane, one connection will be lost in the end.
*If possible, upload an example that shows your problem.
[Uploading Archive(1).zip…]()

**SUMO-version:**
1.19.0
**operating system:**
windows 11

**Comment by daqiu12** [comment]
The command is as follows：
netconvert --opendrive shiyan.xodr -o net.net.xml --ignore-errors --opendrive.curve-resolution 1 --opendrive.internal-shapes true --junctions.corner-detail 8 --output.original-names --speed-in-kmh true

**Comment by m-kro** [comment]
I think this is done by design. Although you can force netedit to build such connection layout, it is considered not the right way to build lane reductions in `netconvert`. Vehicles will be able to change lanes along the two-lane section.
