### ISSUE TITLE
How to make simulation input the same for different simulation tests?

### ISSUE THREAD

**Issue by way-thu** [eclipse-sumo/sumo#14238]
I want to make the same simulation input by different simulation tests, including vehicle depart time, depart lane and so on. Since there are many experiments to be performed, I used the easy way to define the rou.xml, I defined my rou.xml like below:
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/fc8eb738-d760-4e44-a767-309753d459be)
The sumo.cfg file is written like below:
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/1b183c2d-2e46-4217-9696-94a37db3dc3c)
After reviewing the SUMO documentation, my understanding is that when I keep the value of seed constant, the inputs(when and where the car or pedestrains depart) and outputs(tripinfo output) of the simulation are the same no matter how many times I run it.
However, when I set the value of seed to 1, I run the simulation twice, and the net.xml, rou.xml, and sumo.cfg are the same for both times, but it appears that the inputs for vehicles and pedestrians are not the same for two simulations.
The output of the first simulation as below, the car "flow_n_s.0" depart at 5.00.
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/54b9fb66-a464-474d-8c9e-4d173f911bd7)
The output of the second simulation as below, the car "flow_n_s.0" depart at 8.00, that is to say, although I set seed value the same, the simulation inputs are not the same.
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/ab71c36f-8b30-4c12-a764-7c30b82e4ca6)
Is there an easy way to achieve the results I want? (Keep the input the same for many times)
Hope to receive your reply!

**SUMO-version:1.18.0

**operating system: win 10

**Comment by m-kro** [comment]
The option **--random** takes precedence over **--seed**. Both cannot be used together if you read the [description](https://sumo.dlr.de/docs/sumo.html#random_number) carefully. So please just remove the **--random** option from your sumocfg.

**Comment by way-thu** [comment]
@m-kro I have got it, much thanks!
