### ISSUE TITLE
In a roundabout, vehicles turn from the outermost lane of the roundabout.

### ISSUE THREAD

**Issue by ufukkirbas** [eclipse-sumo/sumo#14237]
Dear Sir/Madam,

I designed a roundabout in SUMO. I modeled it with a signal system that is very frequently applied in my country (Türkiye). Traffic flows from the main road with 2 traffic lanes at this intersection. Afterwards, the number of lanes at the intersection increases to 3. Then the traffic flow spreads towards the branches, which continue as 2 traffic lanes. Since a signal is placed inside the circular island, the intersection is designed as 3 lanes in order to increase capacity.

In field observations, under congested flow conditions, the interior of the island is completely filled with vehicles during the red (stop) phase. It does not even allow cutting currents to pass. In other words, due to the extended queue of stored vehicles, they cannot go to the interrupting current even if the light is green.

In the simulation, vehicles pass from the left lane on the main road and pass to the rightmost lane within the roundabout and try to complete their maneuvers. In other words, they use the outermost traffic lanes on the island. Although I have loaded congested traffic, I cannot see the dense vehicle storage seen in field observations inside the roundabout. I added the image of the simulation as a screenshot. Even though I changed many parameters in the Lane change model, Junction model or Car Following models, I could not solve this problem. I use Krauss as the Car Following model. In the Junction model, I changed the ignoreKeepClearTime parameter to 2 and the impatiente parameter to 0.1.

I would be very grateful if you could give me information on what settings I need to change to solve this problem.

Best wishes,
Ufuk KIRBAŞ

![example intersection image 1](https://github.com/eclipse-sumo/sumo/assets/153180912/17274154-0e8d-4688-8085-57335a7214d0)
![example intersection image 2](https://github.com/eclipse-sumo/sumo/assets/153180912/40829840-aae9-4de5-b1b5-04f3f29d93b4)

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by m-kro** [comment]
I feel this will be difficult to get right with sumo. You can still try to change [lane change parameters](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models) though. Might be worth starting with low **lcStrategic** and high **lcAssertive** values...

**Comment by namdre** [comment]
sumo contains a model for having cars use the inside lanes of a multi-lane roundabout whenever they have a somewhat longer route inside the roundabout. This (cooperation) model interacts with the strategic lane choice model which tries to prevent vehicles from being stuck on the wrong lane (and thereby makes them move to the outside lane). 

Besides the two useful settings suggested by @m-kro , you can also increase the willingness to change to empty lanes by setting a higher value for lcSpeedGain and lcSpeedGainLookahead

You can overrule both models be setting waypoints for some of the cars on the inside lane.

For traffic light controlled roundabouts, you can easily get jamming if give more green light for entering vehicles and a bit less green light for vehicles already inside.
