### ISSUE TITLE
How can sumo simulate conform to real-time time queue length in intersection

### ISSUE THREAD

**Issue by allenzhuyi** [eclipse-sumo/sumo#14231]
I have an intersection scenario, where I can obtain the real-time queue length of each incoming lane through radar devices installed at each entrance. Now, I want the SUMO simulation to reference the real-time queue length detected by the radar. I wonder how I can make some parameter adjustments at each simulation step, such as controlling vehicle parameters (like speed) and lane measures (maximum speed), in order to make the queue situation of each lane in the simulation close to the real-time queue length detected by the radar. The goal is to make the simulation conform to the real-world situation.

**SUMO-version:**  sumo 1.19

**operating system:** windows 10

**Comment by m-kro** [comment]
Well you can control vehicle parameters and speed limits with SUMO (and TraCI). Here are some parts of the documentation you can read more about it:

- online simulation control with [TraCI](https://sumo.dlr.de/docs/TraCI.html), especially [change vehicle state](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html)
- [variable speed limits](https://sumo.dlr.de/docs/Simulation/Variable_Speed_Signs.html)

If you don't mind that vehicles are added/removed to match a target volume, then the [Calibrator](https://sumo.dlr.de/docs/Simulation/Calibrator.html) system might be of interest for you.

**Comment by allenzhuyi** [comment]
I am quite interested in the calibrator, as adjusting vehicle speeds at each simulation step is too difficult. However, currently, I only have data on the real-time vehicle count for each lane at each entry point detected by radar. How can I use this data to convert it into traffic flow in order to use calibrator?

**Comment by m-kro** [comment]
You could work with moving averages and find decide which update and aggregation intervals fit your purpose best. There are several time intervals to decide:

- which vehicles are part of the moving average volume
- what is the update frequency of the calibrator settings (Calibrators can be updated using TraCI)
- what is the planned duration of calibrator settings
- do you want to do the process for vehicle flow or speed or both?
