### ISSUE TITLE
[Questions] Inquiries Regarding Pedestrian Sidewalks

### ISSUE THREAD

**Issue by LekYang** [eclipse-sumo/sumo#14239]
with SUMO's current capabilities, is it feasible for pedestrians to move in both directions on a single side of the road, or are they required to adhere to the direction of vehicular traffic? The pedestrian should also be able to access the intersection crossing. I am aiming to simulate a more realistic traffic flow. 

<img width="930" alt="image" src="https://github.com/eclipse-sumo/sumo/assets/52774722/bd9705ba-9b0c-420c-87bb-cb640fe62a79">

**Comment by m-kro** [comment]
Pedestrians can walk in both directions on dedicated infrastructure like sidewalks.
