### ISSUE TITLE
Function to  Determine Boarding Issues

### ISSUE THREAD

**Issue by claudiacbh** [eclipse-sumo/sumo#14234]
Hello! 
I am developing a model for a Bus Rapid Transit (BRT) system, and I need to know if a person at a stop was unable to board the bus because the bus did not pick them up as it was full (capacity) or because the bus departed before they could board (short extension). In case it does not exist, is it possible to include a function that calculates the required information in the next release of Traci?
Thank you!!

SUMO-version:1.18.0

operating system: Windows 11

**Comment by m-kro** [comment]
You can check the bus occupancy comparing the results of the following calls:
`traci.vehicletype.getPersonCapacity` ([ref](https://sumo.dlr.de/pydoc/traci._vehicletype.html#VTypeDomain-getPersonCapacity)) and `traci.vehicle.getPersonNumber` ([ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getPersonNumber)).

You can inspect as well the upcoming stops of the vehicle by calling `traci.vehicle.getStops` ([ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getStops)) and see whether the stop in question is still there.
