### ISSUE TITLE
Internal lane length missing in some cases of traci.vehicle.getNextTLS

### ISSUE THREAD

**Issue by nobugforerer** [eclipse-sumo/sumo#14246]
why does the ouput distance between the starting point of the current car "1" and the last TLS differ among steps of simulation by running codes as follow
```python
traci.start([sumoBinary, "-c", "osm_test.sumocfg"])
step = 10
traci.simulationStep(step)
while traci.vehicle.getIDCount() > 0:
    print(traci.vehicle.getDistance("1")+traci.vehicle.getNextTLS("1")[-1][2])
    step += 10
    traci.simulationStep(step)
traci.close()
```

**Comment by nobugforerer** [comment]
![Uploading 无标题.png…]()

**Comment by m-kro** [comment]
You simulate multiple time steps in a row before printing the distance sum again. Did you check if the vehicle crossed a traffic light in between? Then the next traffic light downstream is somewhere else than before.

**Comment by nobugforerer** [comment]
> You simulate multiple time steps in a row before printing the distance sum again. Did you check if the vehicle crossed a traffic light in between? Then the next traffic light downstream is somewhere else than before.

No, the car goes normally and the STL is still in the same place throughout the process of simulation and the result remains

![无标题](https://github.com/eclipse-sumo/sumo/assets/92627523/4f4fee19-859f-4cc9-9908-42253d770369)

**Comment by nobugforerer** [comment]
> > You simulate multiple time steps in a row before printing the distance sum again. Did you check if the vehicle crossed a traffic light in between? Then the next traffic light downstream is somewhere else than before.
> 
> No, the car goes normally and the last TLS is still in the same place throughout the process of simulation and the result remains
> 
> ![无标题](https://private-user-images.githubusercontent.com/92627523/298622133-4f4fee19-859f-4cc9-9908-42253d770369.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MzU1MTAsIm5iZiI6MTcwNTkzNTIxMCwicGF0aCI6Ii85MjYyNzUyMy8yOTg2MjIxMzMtNGY0ZmVlMTktODU5Zi00Y2M5LTk5MDgtNDIyNTNkNzcwMzY5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDE0NTMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYjc4M2IwOTE2OWE2ODZhMzNmNWI3ZjQ1NWNiMjk1MDI2YTUwNzc3ODZlYWQ2OWQwZDYxMzEwZTI3N2QyODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zXu0P_-tW8StX8-zWNMlpsIQ5sbx_RJkbZ1NDS0JdEk)

The fourth ouput decreases strangely but the car goes normally all the time indeed

**Comment by m-kro** [comment]
Then can you please check the used TraCI functions individually? Which function result increases/decreases more than expected? Where is the vehicle when the sum changes?

**Comment by nobugforerer** [comment]
The first comes from getdistance(), the second comes from getNextTLS()
I can not identify from which one the problem comes from...
![2](https://github.com/eclipse-sumo/sumo/assets/92627523/6c0c551e-d816-4dc3-8a48-0ee8422ff215)
This is the scene where the decrease happens
![1](https://github.com/eclipse-sumo/sumo/assets/92627523/65724afb-c6e6-44e0-ab3f-ccc2b41ad9e3)

**Comment by m-kro** [comment]
I'm already in the process of investigating. There are some time steps as well in my test case where the two distances change by different amounts.

**Comment by m-kro** [comment]
In some occasions the lengths of the internal lanes in between are not counted correctly.

**Comment by m-kro** [comment]
@nobugforerer There was a small bug considering the internal lane lengths. Now with the corrected version, the returned distance to traffic lights decreases with the same amount as the driven distance increases. You can either wait until tomorrow for new [developer binaries](https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots) or compile sumo directly from Github source to try it out.

**Comment by nobugforerer** [comment]
> @nobugforerer There was a small bug considering the internal lane lengths. Now with the corrected version, the returned distance to traffic lights decreases with the same amount as the driven distance increases. You can either wait until tomorrow for new [developer binaries](https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots) or compile sumo directly from Github source to try it out.

Thanks for your efforts, i am looking forward to the new version

**Comment by nobugforerer** [comment]
![1711777517170](https://github.com/eclipse-sumo/sumo/assets/92627523/095e8a98-2a25-4f82-8c89-81fa23650017)
![1711777545683](https://github.com/eclipse-sumo/sumo/assets/92627523/75ebb113-7aa5-4638-8827-ddb83b736c02)
the problem remains in the latest version

**Comment by m-kro** [comment]
The TLS distance is computed in two steps:

- first iterating through bestContLanes
- then through the remaining route edges

The iterator of the second stage started one edge too early and ended one edge too early as well. This means as long as the route was long enough to exceed bestContLanes, one edge was counted twice and one left out. This has been changed with the latest commit.

@nobugforerer Please try again with fresh SUMO development version.
