### ISSUE TITLE
Which variable to use from output of SUMO simulator, for "control delay"(MOE, calculating LOS from HCM) 

### ISSUE THREAD

**Issue by jinx2plus** [eclipse-sumo/sumo#14245]
I figure it's "timeLoss" element from tripinfo-output(xml). 
Just to make sure..

**Comment by m-kro** [comment]
That is certainly the best fit, although it might overestimate the delay. `timeLoss` contains any delay the vehicle gets by not following the maximum speed (either limited by the vehicle's capabilities or the road speed limit). This means even road speed limit changes contribute to `timeLoss` as vehicles have to adapt to it upstream.

**Comment by jinx2plus** [comment]
How about internal edges speed? If a vehicle goes through internal edge, is timeLoss affected by its speed value? 
I am trying to match timeLoss value from simulation output and calculate it with real data. I guess it's hard to calculate it with real data.

**Comment by m-kro** [comment]
Internal edges can contribute as well to `timeLoss`.
