### ISSUE TITLE
How to prevent weaving of a car if in the desired lane there is no space using Traci

### ISSUE THREAD

**Issue by harirRzi** [eclipse-sumo/sumo#14244]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version: 1.18.0**

**operating system: Mac OS**
Hello,
I am trying to simulate weaving behavior of car with ids, d0 and d1 in Sumo like the following via Traci in python file. However I also want to write in my code if there are some cars moving in the lane that d0 and d1 wants to change to them, so they shouldn't change their lane in order to prevent accident and should wait until there is empty space in their desired lane. Is it possible to it?
```
if step==160:
       traci.vehicle.changeLane("d0", 0, 10.0) 
       traci.vehicle.changeLane("d1", 1, 10.0)
```

**Comment by m-kro** [comment]
As long as you don't deactivate safety checks of the [lane change mode](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6), the vehicles adapt their behaviour to avoid collisions or even the need to brake for vehicles entering their lane.
