### ISSUE TITLE
How to download vehicle's guiShape images?

### ISSUE THREAD

**Issue by XuanlinZeng** [eclipse-sumo/sumo#14251]
How can I download the guiShape images in the Vehicle Type attributes? Thank you!
![QQ截图20240123083447](https://github.com/eclipse-sumo/sumo/assets/91841853/9d814d2a-b09f-4b2f-b259-5e1ede334dc6)

**SUMO-version: 1.18.0**

**operating system: Windows 11**

**Comment by m-kro** [comment]
Same as #14250
