### ISSUE TITLE
Can sumo set up real-time dynamic road signs?

### ISSUE THREAD

**Issue by HRYEJJKUK** [eclipse-sumo/sumo#14254]
Hi, I would like to ask if it is currently possible with sumo to implement signs on a link? The sign reflects real-time dynamic road information, such as road tolls, congestion levels, etc. Or is it possible to combine sumo with other software to achieve this task.
![image](https://github.com/eclipse-sumo/sumo/assets/121792232/51435e12-aade-41c6-a6f4-0605babbe562)

**SUMO-version:1.14.1**

**operating system:Windows**

**Comment by m-kro** [comment]
You can add polygons and POI items (optionally with bitmap images) to the network to enhance the visualisation. These items can be updated during the simulation using [TraCI](https://sumo.dlr.de/docs/TraCI/Change_PoI_State.html). PoI and Polygon items can be given a type and a unique ID where information could be encoded. 

Unfortunately there is no easy way to place text items. Vehicles can be set to display a custom [param](https://sumo.dlr.de/docs/Simulation/GenericParameters.html) value in the sumo-gui, though.
