### ISSUE TITLE
Do the settings of the minGap and tau parameters in the CACC following model change the critical values for activating various modes in the CACC following model?

### ISSUE THREAD

**Issue by ijcfamily** [eclipse-sumo/sumo#14257]
Do the settings of the minGap and tau parameters in the CACC following model change the critical values for activating various modes in the CACC following model?

For example, if the minimum gap (minGap) is set to 0.3m, will the (ii) gap control mode, as described in the official website documentation, never be activated? Similarly, if the time constant (tau) is set to 2.0s, will the (iii) gap-closing control mode, as described in the official website documentation, never be activated?
If not the above explanation, what is the significance of setting the minGap and tau parameter values in the CACC following model?

**Comment by robertalms** [comment]
The very short answer should be: No. Setting minGap or tau to different values should have no effect on the parameterisation of the CACC parameters (considering the current CACC implementation as it is).  Try setting the parameters individually to see the respective effects. (see [doc](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#car-following_model_parameters))
