### ISSUE TITLE
error in command line after producing xml output file from Sumo simulation

### ISSUE THREAD

**Issue by harirRzi** [eclipse-sumo/sumo#14253]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version: 1.18.0**

**operating system: Macos**
Hello. I am trying to output my sumo simulation using following command. After running it, I see the below error. I appreciate if anyone can tell me how to fix it. 
`sumo -c demo.sumocfg --fcd-output sumoTrace1.xml`

`Step #0.00 (1ms ~= 1000.00*RT, ~3000.00UPS, vehicles TOT 3 ACT 3 BUF 1)         Step #100.00 (1ms ~= 1000.00*RT, ~70000.00UPS, vehicles TOT 70 ACT 70 BUF 0)    Step #200.00 (0ms ?*RT. ?UPS, vehicles TOT 70 ACT 1 BUF 0)                      Step #203.00 (0ms ?*RT. ?UPS, vehicles TOT 70 ACT 0 BUF 0) `

Also, I want the output xml file in addition to the attributes it provides now with the above command, I need it also provides me information about acceleration for each of vehicle. How can I do it?

**Comment by m-kro** [comment]
This is a regular output message, not an error. You can suppress it with the option **--no-step-log true** (see [docs](https://sumo.dlr.de/docs/sumo.html#report)).

**Comment by harirRzi** [comment]
I need in addition to current attributes that the above command produces for each vehicle, it also provides me acceleration, How can I do it?

**Comment by m-kro** [comment]
Add `--fcd-output.acceleration true` to your sumo call to get the acceleration included in the FCD output.
