### ISSUE TITLE
How to prevent accident between normal car behavior and anomalous car behavior in Sumo

### ISSUE THREAD

**Issue by harirRzi** [eclipse-sumo/sumo#14252]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version: SUMO 1.18.0**

**operating system: Mac OS**

Hi. I defined the following in .rou.xml file. I want to keep the defined behavior for d2 and d6 but if possible to change the behavior for carflowNormal_8 in order not to have accident. Is it possible to do it?

```
   <vType id="Normal-car-1" vClass="passenger" length="5" accel="2.8" decel="4.5" sigma="0.5" minGap="1.0" maxSpeed="16.66" speedDev="0.1"/>
  <flow id="carflowNormal_8" type="Normal-car-1" beg="30" number="13" route="route_0" departLane="random" probability="0.5" />
<vType id="d_2" vClass="passenger" sigma="0.9" accel="3.5" decel="2.5" maxSpeed="18.05" speedDev="0.1" color="blue" />
<vType id="d_6" vClass="passenger" sigma="0.8" minGap="0.2" tau="0.1" impatience="1" accel="10" decel="9.5" lcAssertive="0.9" lcSigma="0.8" lcPushy="0.9" maxSpeed="18.05" speedDev="0.1" color="255,10,240"/> 
```
Here is the error I get:
```
Warning: Teleporting vehicle 'd2'; collision with vehicle 'carflowNormal_8.12', lane='e1_1', gap=-5.17', latGap=-0.53, time=76.00 stage=laneChange.
Warning: Vehicle 'd2' ends teleporting on edge 'e2', time=76.00.
Warning: Teleporting vehicle 'd6'; collision with vehicle 'carflowNormal_8.10', lane='e1_0', gap=-0.22', latGap=-0.30, time=104.00 stage=move.
Warning: Vehicle 'd6' ends teleporting on edge 'e2', time=105.00.
```

Also I defined some other vehicles for example for d0 I have the following but I get warnings. I need to define some vehicle's behaviors that doesn't obey the rules to follow its front car and it's always try to be very close to its front car. In my current simulation, I can not see when for example d0 is following its front car. How can I show this in simulation without having accident?

`<vType id="d_0" vClass="passenger" sigma="0.9" maxSpeed="19.44" lcAssertive="0.8" minGap="0.5" tau="0.05" accel="7" lcPushy="0.9" decel="8" speedDev="0.1" lcSigma="0.8" color="green" />`

Warning: Value of tau=0.05 in vehicle type 'd_0' lower than simulation step size may cause collisions.
Warning: Value of tau=0.01 in vehicle type 'd_5' lower than simulation step size may cause collisions.
Warning: Value of tau=0.10 in vehicle type 'd_6' lower than simulation step size may cause collisions.
Warning: Value of tau=0.50 in vehicle type 'd_7' lower than simulation step size may cause collisions.
Warning: Value of tau=0.50 in vehicle type 'd_8' lower than simulation step size may cause collisions.

**Comment by m-kro** [comment]
As the **tau** parameter is defined as the minimum time gap to the leader vehicle, values lower than the time step can lead to collisions. The follower isn't able anymore to brake in time. Read more about it in the [docs](https://sumo.dlr.de/docs/Car-Following-Models.html#tau). So this behaviour is expected. You write:

> [...] that doesn't obey the rules to follow its front car and it's always try to be very close to its front car

So what do you expect to happen if someone breaks the rules?
