### ISSUE TITLE
How to download vehicle guiShape images?

### ISSUE THREAD

**Issue by XuanlinZeng** [eclipse-sumo/sumo#14250]
How can I download the guiShape images in the Vehicle Type attributes? Thank you!
![QQ截图20240123083447](https://github.com/eclipse-sumo/sumo/assets/91841853/9d814d2a-b09f-4b2f-b259-5e1ede334dc6)

**SUMO-version: 1.18.0 **

**operating system: Windows 11**

**Comment by m-kro** [comment]
These shapes are drawn directly in sumo-gui from geometric primitives and some more complicated geometries. Consequently they are not available as separate image files. So if you don't want to write code to let them be drawn, you are stuck with taking screeenshots...

**Comment by XuanlinZeng** [comment]
> These shapes are drawn directly in sumo-gui from geometric primitives and some more complicated geometries. Consequently they are not available as separate image files. So if you don't want to write code to let them be drawn, you are stuck with taking screeenshots...

Thank you, Mirko
