### ISSUE TITLE
An error of "The start edge is not known"

### ISSUE THREAD

**Issue by hhhhhhyl** [eclipse-sumo/sumo#14255]
Hello, I encountered an error with "The start edge for person '611' is not known" while running the simulation. Upon checking the route file, I found that the starting edge of person "611" is a bus stop rather than an edge. However, this issue seems to have been resolved in version 1.18.0. The relevant link is: https://github.com/eclipse-sumo/sumo/issues/13506#issue-1776243717
May I ask why this error still occurs in version 1.19.0? How should I solve it?
Here are my error screenshots and file contents：
![error](https://github.com/eclipse-sumo/sumo/assets/96480310/e933858a-90fc-4b66-a7c0-c68b454494f2)

![route file](https://github.com/eclipse-sumo/sumo/assets/96480310/d725d979-24c8-4dba-85df-48353fe92ca1)

All input files will be uploaded in the form of a cloud drive. If needed, please check: https://drive.google.com/file/d/15l-VteEP8Wz6pTpL4IwNW55ZMBnOdjtY/view?usp=sharing

**Comment by m-kro** [comment]
You have to define the start edge of the ride (see [docs](https://sumo.dlr.de/docs/Specification/Persons.html)). This attribute is missing for the person 611. The attribute `busStop` defines where to leave the public transport vehicle, not where to board.

If you want the persons to start traveling from a public transport stop, enter the edge ID of the stop for the from attribute of the first stage = ride. Set `departPos` value in the person definition to a value inside the stop extension.

**Comment by hhhhhhyl** [comment]
Thank you for your answer. But my route file is automatically generated by the "duarouter" command, and the size of my route file is relatively large, making it difficult to add edges in sequence if there are many similar problems. Previously fixed this issue in version 1.18.0(see https://github.com/eclipse-sumo/sumo/issues/13506#issue-1776243717), may I ask why the old issue still exists in version 1.19.0?https://github.com/eclipse-sumo/sumo/issues/13506#issue-1776243717

**Comment by hhhhhhyl** [comment]
Thank you for your answer. But my route file is automatically generated by the "duarouter" command, and the size of my route file is relatively large, making it difficult to add edges in sequence if there are many similar problems. Previously fixed this issue in version 1.18.0(see https://github.com/eclipse-sumo/sumo/issues/13506#issue-1776243717), may I ask why the old issue still exists in version 1.19.0?

**Comment by hhhhhhyl** [comment]
Ok, I see. Thank you very much.
