### ISSUE TITLE
how can i split lane or edge dynamically  in traci? 

### ISSUE THREAD

**Issue by wangwgithub** [eclipse-sumo/sumo#14266]
In SUMO, is there a way to dynamically divide a lane on a road into several segments, or to split a road into multiple segments?I would like to close a section of a lane within TraCI.
last time ,i just ask a question: [here](https://github.com/eclipse-sumo/sumo/issues/14194)。I've split an edge within an OpenDRIVE xord file. Now, I am curious whether it is possible to dynamically split that edge again after converting the xord file to a SUMO net (.net) file.

*If possible, upload an example that shows your problem.*

**SUMO-version:**1.19.0

**operating system:**win10

**Comment by meco2020** [comment]
traci 干不了这事，仿真加载后路网就是固定的了

**Comment by m-kro** [comment]
Why do you ask the same question again? The answer remains the same: you can't change the road network during the simulation. You can only split the road network before simulating, either

- through the edge context menu (right click on object) in netedit
- defining the split points in [PlainXML](https://sumo.dlr.de/docs/Networks/PlainXML.html#road_segment_refining) format and run netconvert to obtain the updated network

**Comment by wangwgithub** [comment]
> traci 干不了这事，仿真加载后路网就是固定的了

那就是目前没有任何办法，模拟时随意封闭一段指定的距离（两个坐标点）。可现实中，封路常规的做法，就是随意封闭一段距离。

**Comment by wangwgithub** [comment]
> Why do you ask the same question again? The answer remains the same: you can't change the road network during the simulation. You can only split the road network before simulating, either
> 
> * through the edge context menu (right click on object) in netedit
> * defining the split points in [PlainXML](https://sumo.dlr.de/docs/Networks/PlainXML.html#road_segment_refining) format and run netconvert to obtain the updated network

sorry,i just want know how it support that  the traic dynamically operate lane or road。by the way,  SUMO In future versions, is there a plan to support dynamically closing a specified distance of a lane or road?

**Comment by m-kro** [comment]
No, there is no plan to support that. What is your use case?

**Comment by wangwgithub** [comment]
> No, there is no plan to support that. What is your use case?

My use case involves simulating a highway expansion and renovation project. During the construction period, I would like to model the closure of a lane at arbitrary positions for a given distance and observe the traffic congestion patterns on the road under different closure locations. for example, choose a segment of a lane randomly,  close the red area.
![222](https://github.com/eclipse-sumo/sumo/assets/34933988/6764e2fd-143a-489d-b352-9aac62446f71)

**Comment by m-kro** [comment]
Construction works usually are planned at a higher level than what SUMO aims for. The main task of SUMO is simulating traffic flow, which means a time horizon from milliseconds to at most a few days. Construction works are planned weeks or months in advance. In your case I advise to split the edge at the construction work limits.

**Comment by wangwgithub** [comment]
> 建筑工程的规划水平通常高于 SUMO 的目标。SUMO的主要任务是模拟交通流，这意味着时间范围从毫秒到最多几天。建筑工程提前几周或几个月计划。对于您的情况，我建议在施工限制处分割边缘。

OK，Thank you for your response.!

**Comment by namdre** [comment]
an alternative solution is to place a stopped vehicle of suitable length in the section that is to be closed for construction.
