### ISSUE TITLE
How to make a space between the stop line and pedestrian crossing?

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse-sumo/sumo#14260]
Hi,

I made a 4-leg intersection in SUMO as follows.

![hhhhhh](https://github.com/eclipse-sumo/sumo/assets/64617116/156f3a5e-f007-406a-b5b6-b26180f56741)

I was wondering how I can move the pedestrian crossing a little down to make an open space between the stop line and crossing of the SB approach.

Best,
Reza.

**Comment by m-kro** [comment]
You can define a custom crossing shape either in netedit through the [context menu of the crossing](https://sumo.dlr.de/docs/Netedit/neteditPopupFunctions.html#crossing) (right mouse click) or in the [PlainXML](https://sumo.dlr.de/docs/Networks/PlainXML.html#pedestrian_crossings) file format.
