### ISSUE TITLE
I'm having problems exporting rou.xml using dua.

### ISSUE THREAD

**Issue by HRYEJJKUK** [eclipse-sumo/sumo#14267]
Hi：
Question 1:
    Firstly,I generated the flow file using od2trips.
    ![image](https://github.com/eclipse-sumo/sumo/assets/121792232/97f29875-11e4-4998-8606-d773f444d4b3)
    Successfully generated flow file.
    ![image](https://github.com/eclipse-sumo/sumo/assets/121792232/27360133-f483-462d-b324-a1c476ad702b)
    And then,I used Duarouter to load net.xml,flow,vtype,taz,and weight.xml files.
    ![image](https://github.com/eclipse-sumo/sumo/assets/121792232/4a852eb4-5915-447f-9c1a-c1daef51bfe3)
    Just then the system reports an error, here is the type of error.
    ![image](https://github.com/eclipse-sumo/sumo/assets/121792232/c5a213ff-f15a-42f3-9159-7e4f337534b2)
Question 2:
    The max speed used by duarouter in the weight calculation for undefined edges, which speed is meant. Is it the speed in the edge in the net.xml file?
![image](https://github.com/eclipse-sumo/sumo/assets/121792232/5f95fda9-3d73-48a3-b0ad-152d04c37582)
![image](https://github.com/eclipse-sumo/sumo/assets/121792232/ec222dde-2c18-43da-b5fe-38d7614e5aa0)

**SUMO-version:1.14.1**

**operating system:wingdows10**

**Comment by HRYEJJKUK** [comment]
Sorry ,The question 1 maybe I know why, because number=0 in flow.The question 2, can you answer it for me?

**Comment by m-kro** [comment]
It is the minimum of the edge speed limit and the max. speed of the vehicle.
