### ISSUE TITLE
pedestrian waiting time output

### ISSUE THREAD

**Issue by way-thu** [eclipse-sumo/sumo#14264]
I need to output the waiting time for pedestrians at the end of the simulation (due to the influence of red lights), It seems that the tripinfo.output file does not include the waiting time for pedestrians. Is there a way to directly output the waiting time for pedestrians? 

**SUMO-version:1.18.0

**operating system: windows

**Comment by way-thu** [comment]
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/29773817-ee18-49ca-a8f2-066dc38189c7)

**Comment by m-kro** [comment]
Given the low speed pedestrians reach during their trip, the `timeLoss` attribute is quite close to the pure waiting time. You cannot differentiate between delays due to traffic lights or other reasons (queues, blocking pedestrians from the opposite direction,...), though.

**Comment by way-thu** [comment]
Thanks for your reply firstly. Can I understand that, under normal circumstances, the speed of pedestrians is always the maximum speed, and when it is less than the maximum speed, it can be approximately considered that their speed is less than 0.1m/s, which is the return value of the 'getWaitingTime(self, personID)' function in person.py?
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/ba36f301-60e6-433a-8537-baf9144cd7f0)

**Comment by m-kro** [comment]
Yes.
