### ISSUE TITLE
xml2csv Are the semicolon separated values in the first line of a csv file in alphabetical order?

### ISSUE THREAD

**Issue by XuanlinZeng** [eclipse-sumo/sumo#14265]
Are the semicolon separated values in the first line of a csv file in alphabetical order?
xml：
![image](https://github.com/eclipse-sumo/sumo/assets/91841853/be790fea-856e-4fa0-b336-46f8409a3899)
csv：
![image](https://github.com/eclipse-sumo/sumo/assets/91841853/86dce16e-3fa3-4fb3-959c-30ce447f6954)

**SUMO-version: 1.18.0 **

**operating system: Windows 11**

**Comment by m-kro** [comment]
Yes, they are sorted when reading the XML file.
