### ISSUE TITLE
Is there an api to retrieve all traffic light ids in C++ (libsumo specifically)

### ISSUE THREAD

**Issue by Metro1998** [eclipse-sumo/sumo#14273]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version: latest**

**operating system: Linux**
First, thanks for your execellent worl!
I know that TRACI has a Python API called 'getIDList' to get the IDs of all traffic lights; now, I want to use a C++-based api but it seems I couldn't find a similar method in src/libsumo.Is there an available api, or could I use other C++-based methods to retrieve all traffic light ids.

**Comment by m-kro** [comment]
Actually there is one:

https://github.com/eclipse-sumo/sumo/blob/72c9a9d3985b58fe18ca463efdf21cb8be21b936/src/libsumo/TrafficLight.cpp#L58-L61

**Comment by Metro1998** [comment]
I got it，thanks a lot, I may have paid so much attention on the TrafficLight.h.
