### ISSUE TITLE
duarouter failed to transfer trip to route

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14274]
Add your issue description here.
Hi, recently I generated a trip file through the OD matrix and I want to further generate the complete route, but encountered some problems.
*If possible, upload an example that shows your problem.*
As you can see, directly running the trip file, some traffic flows cannot find valid paths, so I want to plan the route through duarouter.
![1706514391649](https://github.com/eclipse-sumo/sumo/assets/120693511/0eaab3a4-98c1-48d2-b6bd-53a7c7083c81)

However, when I use duarouter, there are also some warnings and errors, and eventually the program has to be terminated.
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/f5407883-0ec3-42a6-a3bb-17ae87b22266)
Is there any way to avoid vehicle no-path issues, or skip those vehicles without a route? Thank you!

**SUMO-version:**
SUMO1.19.0

**operating system:**
Windows10

**Comment by m-kro** [comment]
Append **--ignore-errors true** to the duarouter command to skip the vehicles without a route. There is no way to avoid the problem, if you actually need the named edges for other vehicles...

**Comment by nudtdyk** [comment]
Thank you for your reply! Is the most fundamental reason that the roads are not connected?

**Comment by m-kro** [comment]
Generally speaking, **missing connections** can be a reason. The error message form your screenshot tells another one: **edge permissions** do not match the wanted vehicle class on the departure edge.

**Comment by nudtdyk** [comment]
Thank you for your explanation, I understand it now.

**Comment by namdre** [comment]
To avoid invalid departure/arrival edges you can pre-process your TAZ file: https://sumo.dlr.de/docs/Tools/District.html#filterdistrictspy
