### ISSUE TITLE
The method of calculating the weight of an edge in duarouter.

### ISSUE THREAD

**Issue by HRYEJJKUK** [eclipse-sumo/sumo#14279]
Q1：
Is the default formula for defining the weight of an edge in duarouter the edge length/speed? Or what?

![1706595214355](https://github.com/eclipse-sumo/sumo/assets/121792232/4ec4e6a1-8044-465f-995f-a2876392e5f1)
⬆️The length of the edge above is 1114.86m and the speed is 16.66m/s. The weight, if it is what I understand it to be, should be 66.92.

But when I output the roux with duarouter, by setting --exit-times=true, I get a weight of 4141.99 for that edge.⬇️
![1706595170613](https://github.com/eclipse-sumo/sumo/assets/121792232/67c61118-e918-4a23-a7e8-1c5f5be4991c)
I'm guessing that maybe the weights are in real time. But did not set too much demand for that edge.
Q2：
May I ask if I want to charge a fee ($/m) for some edges. The value of time is (second/$),so I need to reset the weight of these edges.So how should I set it? The formula I am currently using is: edge length/speed(set in netedit) + length*fee*time of value.Is  it right?

Is there an official reference manual that has the information written in it?

**SUMO-version:1.14.1**

**operating system:win 10**

**Comment by m-kro** [comment]
You can use your own edge-based data for routing. Have a look at the documentation: General introduction to [routing by effort](https://sumo.dlr.de/docs/Simulation/Routing.html#routing_by_effort) and a [weight file example](https://sumo.dlr.de/docs/Demand/Shortest_or_Optimal_Path_Routing.html#custom_edge_weights).

**Comment by HRYEJJKUK** [comment]
I looked at Routing by effort, and since the value of time it doesn't change over time. Just make this defined edge add a value of time to the BPR routing resistance function that is considered when utilising duarouter.
![1706608322871](https://github.com/eclipse-sumo/sumo/assets/121792232/a3d9d69a-be04-4396-aee6-f30cba469f19)
⬆️My situation matches the NOTE in the chart above.
So I just need to input the initial weight of the edge to the duarouter without defining the weight-attribute.
I did this and came up with among other things: the weight of the edge being defined, and that weight doesn't change with the traffic flow of the roadway when traffic assignments are made. In fact I thought that DUA, in its execution, subtracts the free-flow travelling time of the edge from the weight being defined, and uses the result obtained as a value to be added. The resulting BPR road resistance is added to this to-be-increased value when this edge is subjected to each iteration of traffic assignment. Compare it with other edges and then route it.

**Comment by namdre** [comment]
| But when I output the roux with duarouter, by setting --exit-times=true, I get a weight of 4141.99 for that edge.⬇️

exit-times are cumulative travel times along the whole route (the absolute time at which a vehicle would exit that edge). If you do not load weights, then the permitted speed on each edge is assumed.
