### ISSUE TITLE
compiler dependency of sumo

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#14276]
the test sumo\opposite_direction_driving\slalom\2queues gives a different result when sumo is compiled on my local machine (VS 2022) or on the test server (VS 2019). The problem is not in the libraries since I can copy the sumo.exe to trigger the differing behavior.

**Comment by palvarezlopez** [comment]
@behrisch probably related with the problem of @m-kro with their compiled SUMO

**Comment by namdre** [comment]
fixed via #14475
