### ISSUE TITLE
StartUpDelay does not work with small timesteps and IDM

### ISSUE THREAD

**Issue by Domsall** [eclipse-sumo/sumo#14289]
Right now:
- myTimeSinceStartup gets set to 0 when the vehicle's acceleration is not "strong" enough
- This can happen when simulating with small timesteps (vNext <= SUMO_const_haltingSpeed) and/or with a vehicle model that does not accelerate hard from startup (IDM)
- The result:
  - startupDelay gets ignored OR
  - the vehicle starts driving, but after reaching SUMO_const_haltingSpeed, the vehicle stops again

https://github.com/eclipse-sumo/sumo/blob/50b43697ca8d665b4b13b0a23d01dc148f558ee6/src/microsim/MSVehicle.cpp#L4415-L4415

Possible solution:

- if (vNext <= **NUMERICAL_EPS_SPEED** && myWaitingTime > MSGlobals::gStartupWaitThreshold && rawAccel <= accelThresholdForWaiting() && myActionStep)

ToDo (for me as reminder):

1. Wait for the changes documented in #14229
2. Create a test that shows this issue
3. Change the Code
4. Update all tests (check for unintended behavior)

**Comment by namdre** [comment]
apologies. It will take a bit longer to come around to this

**Comment by Domsall** [comment]
I am not in a hurry and already using the pull request on my side, so no worries.
