### ISSUE TITLE
How to get(return) edges(dead ends) of net.xml?

### ISSUE THREAD

**Issue by jinx2plus** [eclipse-sumo/sumo#14284]
I have just found out there is a tool for selecting "dead ends" edges and "dead Starts" edges in netedit-Network-Edit Connections menu. 
Will it be possible for me to get edges of them? 
I've already searched sumolib, but I think I have to make a code for my self.  

----------------------------------------------------------
**SUMO-version:1.17.0

**operating system:Windows 10

**Comment by m-kro** [comment]
So you intend to get dead ends from a Python script? You can use sumolib for that purpose. Just count the size of `sumolib.net.node.getIncoming` and `sumolib.net.node.getOutgoing` ([ref](https://sumo.dlr.de/pydoc/sumolib.net.node.html)) result: dead ends have 0 outgoing, dead starts 0 incoming edges.
