### ISSUE TITLE
Invalid path to Tools in console 

### ISSUE THREAD

**Issue by TIMON72** [eclipse-sumo/sumo#14280]
I can’t use Tools because the path is written incorrectly in the console:
![image](https://github.com/eclipse-sumo/sumo/assets/20472858/e87a099c-6a68-4c4c-8624-79839d969b2e)

In the Conference Tutorial 2023 is correct path:
![image](https://github.com/eclipse-sumo/sumo/assets/20472858/672f2b46-9d2d-4e6e-89f9-0a9c2b0a0c03)

Briefly about my problem:
python %SUMO_HOME%\tools\net\netdiff.py ... - it's work
python "D:\Programming\Sumo\"/tools/net/netdiff.py ... -it's not work (but that's what the console does in netedit)

Sumo and Python are installed correctly, the argument <SUMO_HOME> is registered in the system

netedit 1.19.0
Windows 10 Pro 22H2 build: 19045.3930

**Comment by m-kro** [comment]
Seems to be the same problem as in #14134 . Please remove the final backslash of the path stored in your SUMO_HOME variable. The development version (and next releases will) work around that automatically.

**Comment by TIMON72** [comment]
Thanks, It's help. But why does the intaller create such an argument? It's should be fixing by removing an unnecessary character "\" at the end of the path SUMO_HOME in the windows installer.
