### ISSUE TITLE
netedit writes unsupported attribute 'fromBusStop'

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14296]
currently, one needs to define at least a `<stop busStop="..."/>` to define a person which starts at a busStop.

We may want to support `fromBusStop`  sumo/duarouter but it should be discussed first.

regression in 1.19. via #13828

**Comment by palvarezlopez** [comment]
@namdre I vote for the support in sumo/duarouter.

**Comment by namdre** [comment]
> @namdre I vote for the support in sumo/duarouter.

I prefer having netedit create two stages in the background for the following reasons:
- right now we have 6 distinct attributes for defining the destination stop of a stage (busStop, trainStop, chargingStation, ...) which may all be used as part of a personTrip definition. Since 5 of these have a distinct namespace (we can have both a busStop and chargingStation with the same ID), it would be necessary to create 5 or 6 new attributes `fromBusStop`, fromChargingStation` 
- we already have tooling to create trips between busStops consisting of two stages (randomTrips), having netedit also create two stages in the background would have similar convenience as intended by the current netedit UI
