### ISSUE TITLE
Bus holding time 

### ISSUE THREAD

**Issue by claudiacbh** [eclipse-sumo/sumo#14293]
Hello! 

I am developing a reinforced learning to  reduce the waiting time with real-time control in a BRT system. So far, I have used the "duration" parameter for control, but I need to change it to "holding time," which is the time the bus remains stationary at the bus stop after passengers have finished boarding or alighting. 

I appreciate it if you could tell me how I can implement holding time.

SUMO-version:1.18.0

operating system: Windows 11

**Comment by m-kro** [comment]
You can observe the boarding process by calling `traci.vehicle.getPersonNumber` ([ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getPersonNumber)) repeatedly. Then you can subtract the time the number does not change anymore from the departure time at the stop.

**Comment by claudiacbh** [comment]
Thank you
