### ISSUE TITLE
Enabling Lane Changes for Cars Across Bike Lanes in Two-Lane Roads

### ISSUE THREAD

**Issue by henrigrossmann** [eclipse-sumo/sumo#14294]
I'm currently working on a road network that includes dedicated bike lanes. Presently, the bike lanes are only accessible to bicycles. This restriction causes problems, particularly on two-lane roads that are separated by a bike lane. Cars are unable to change lanes because they are not allowed on the bike lane that separates them (see screenshot).

I'm seeking guidance on how to implement a solution to this problem without compromising the principle that bike lanes should primarily serve bicycles. Could utilizing the lane attribute 'prefer' be a viable solution to this issue? Unfortunately, I couldn't locate detailed documentation explaining the functionality of this attribute.

Thank you for your help!

<img width="526" alt="Screenshot 2024-02-01 at 14 39 18" src="https://github.com/eclipse-sumo/sumo/assets/151520729/4add47a7-d187-477a-b6e6-c38367e31b51">

**Comment by m-kro** [comment]
There is a reason this attribute is not documented. The "prefer" attribute seems to be implemented on the input side only but isn't used inside the simulation. Unfortunately I don't know any viable solution for your use case.

**Comment by m-kro** [comment]
@henrigrossmann Your screenshot suggests the bike lane continues along the whole length between two intersections. If the bike lane was only in an intersection approach (~50-100m upstream), then a practical solution could still be to simply to open the bike lane to cars (or split the edge and allow only one part). Cars wouldn't want to stay long on the bike lane as downstream connections start from car lanes. Unfortunately, cars might block cyclists if the lane change could not be completed.

Can you tell us where we can find such configuration in the real world? From a German perspective, only intersection approaches came to our minds.

**Comment by henrigrossmann** [comment]
Thank you for your solution suggestions @m-kro. https://www.openstreetmap.org/way/1130581203 is the edge that the screenshot shows in the city of Basel, Switzerland (or here on google maps: https://maps.app.goo.gl/mptBWGcPvRLTyB4B9).

**Comment by namdre** [comment]
If splitting is not feasible, than you can also permit cars on the bike lane but disallow cars on the connection outgoing of the bike lane. This way, the strategic lane choice behaviour will ensure that cars only use the bike lane briefly since it doesn't continue their route.
