### ISSUE TITLE
netconvert on modified osm file fails

### ISSUE THREAD

**Issue by MatteoFel** [eclipse-sumo/sumo#14290]
Dear Sumo-Team

I am trying to apply netconvert to an OSM file that was **modified once** using a command from osmfilter. 

Unfortunately, I get a segmentation fault error. Is there a way you to figure out which part of the osm file is causing this issue? 

The netconvert configuration and OSM file are attached below.

Thank you for your help!

SUMO-version: 1.19

operating system: MacOS

[netconvert_issue.zip](https://github.com/eclipse-sumo/sumo/files/14122171/netconvert_issue.zip)

**Comment by m-kro** [comment]
That's strange because I was able to reproduce it.

**Comment by MatteoFel** [comment]
Oh, that's already very helpful, thank you! It could be that roundabout edges are filtered out in the osmfilter step. Let me get back to you!

**Comment by MatteoFel** [comment]
Hi, indeed it was a mistake on my part. I didn't import highway=roundabout when running the osmfilter. Thanks for the quick response and for pointing me to the roundabouts - that was very helpful!!

**Comment by MatteoFel** [comment]
Hi,

I am sorry to reopen this - but the issue is still there (with the same network)! If you find the time could let me know which roundabouts are affected, so that I can try to resolve the issue on our side?

Thanks a million!

**Comment by MatteoFel** [comment]
Oh, so importing highway=cycleway fixes it in this particular case (and not highway=roundabout, this value doesn't exist).

Sorry for the back and forth!
