### ISSUE TITLE
Avoid unlikely signal state sequences (green-yellow-green) for generated signal programs

### ISSUE THREAD

**Issue by gladysmcgan** [eclipse-sumo/sumo#14295]
I notice some instances in my networks where traffic signals turn green - yellow - green again. In my opinion it should rather be green in that whole duration if possible. 

For example, the left edge going south in the network BAS_sumo_raw1.net.xml, files here: [GYG_issue.zip](https://github.com/eclipse-sumo/sumo/files/14128398/GYG_issue.zip)

Thanks for looking into this!

**SUMO-version:** 1.19

**operating system:** MacOS

0
<img width="453" alt="Screenshot 2024-02-01 at 5 53 53 PM" src="https://github.com/eclipse-sumo/sumo/assets/59922884/5c22c15b-38e5-46de-8f5d-7cd915a8266a">
1
<img width="429" alt="Screenshot 2024-02-01 at 5 53 56 PM" src="https://github.com/eclipse-sumo/sumo/assets/59922884/e2087528-3c64-4b5d-8536-2fb743133d3e">
2
<img width="400" alt="Screenshot 2024-02-01 at 5 54 00 PM" src="https://github.com/eclipse-sumo/sumo/assets/59922884/1f080713-2351-4042-986b-81871d462360">

**Comment by m-kro** [comment]
Could you please provide the used netconvert options as well?

**Comment by m-kro** [comment]
Currently, the generated signal plans aren't checked well for strange phase sequences. Only identical phases are merged. However we can fix this shortly.

**Comment by m-kro** [comment]
Now netconvert iterates through auto-generated signal programs to remove sequences of the pattern green-yellow-green. Please update tomorrow to new [developer binaries](https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version) or build now from Github source.
