### ISSUE TITLE
Problems installing sumo in the make file

### ISSUE THREAD

**Issue by andres2700-sudo** [eclipse-sumo/sumo#14305]
hello, im trying to run veins through sumo and omnet 6++, and im having an issue installing the sumo v1.0.1, specifically in the make file, i did a grep to see where the error was and i got this response, 

/tmp/sumoA1.0.1-20240205-39553-dqietb/sumo-1.0.1/src/utils/geom/GeoConvHelper.cpp:428:9: error: use of undeclared identifier 'myProjection'
/tmp/sumoA1.0.1-20240205-39553-dqietb/sumo-1.0.1/src/utils/geom/GeoConvHelper.cpp:431:27: error: use of undeclared identifier 'myProjection'
2 errors generated.

because of this error the make command can not be done and i cant link omnet and veins with sumo, any suggestions??

**Comment by m-kro** [comment]
Is there any reason you cannot use a newer SUMO release?

**Comment by zazim13** [comment]
Hello there, 
I am experiencing the same error while installing sumo v1.0.1 also. 
I have to use this version as newer version are not compatible with my traci API version. While trying to use last version of sumo, I have this error: 
"TraCI server reports unsupported TraCI API version: 21. We recommend using Sumo version 1.0.1 or 0.32.0 -- in module (veins::VeinsInetManager) vehicularMec.manager (id=7), at t=0s, event #2"

Best regards 
Hakim

**Comment by m-kro** [comment]
In any case we will not backport fixes to long superseded releases. You can obtain the old source code [here](https://sourceforge.net/projects/sumo/files/sumo/version%201.0.1/) and fix the problem for yourself. It could be that newer compilers find more issues than at the time version 1.0.1 was released. 

Out of curiosity: Which veins release and compiler do you use?

**Comment by zazim13** [comment]
Hi. 
Thanks for your suggestion. Turns out sumo1.8.0 works for me.
I am using veins5.2 and gcc 11.4.0 compiler.
Best regards
Hakim
