### ISSUE TITLE
Question: seed simulation

### ISSUE THREAD

**Issue by claudiacbh** [eclipse-sumo/sumo#14302]
Hello!

I am developing a Reinforcement Learning (RL), for this purpose, I created a simulation in SUMO that I am adapting as my Environment for my RL using the Gym library. I need to change the seed with each iteration (at the end of the episode/simulation before start over), so, I am trying to use:

traci.close()
seed = np.random.randint(0, 10000) 
traci.start([self.sumoBinary, "-c", "rl_brt.sumocfg", "seed", str(seed)])

in my method reset(), but  doesn't work (error: Could not connect to TraCI server using port...)

Could you tell me how I can change the simulation seed, please?

I truly appreciate the assistance you have provided me to develop this simulation.

SUMO-version:1.18.0

operating system: Windows 11

**Comment by m-kro** [comment]
Please do not forget the preceding "minus" signs of the seed option (see [list of command options](https://sumo.dlr.de/docs/sumo.html#random_number)):
```
traci.start([self.sumoBinary, "-c", "rl_brt.sumocfg", "--seed", str(seed)])
```

**Comment by claudiacbh** [comment]
Thank you!
