### ISSUE TITLE
Packaging Error in libsumo Causes ModuleNotFoundError

### ISSUE THREAD

**Issue by given-woo** [eclipse-sumo/sumo#14314]
## Issue Description

When attempting to import and use the libsumo library on an Apple M1 system, the following error occurs:

```python
# test.py
import libsumo
libsumo.start(["sumo", "-c", "test.sumocfg"])
libsumo.simulationStep()
```

```
Traceback (most recent call last):
  File "/Users/junwoo/Documents/GitHub/Traffic-Control/test.py", line 2, in <module>
    import libsumo
  File "/opt/homebrew/opt/sumo/share/sumo/tools/libsumo/__init__.py", line 30, in <module>
    from .libsumo import vehicle, simulation, person, trafficlight, edge  # noqa
ModuleNotFoundError: No module named 'libsumo.libsumo'
```
Examining the __init__.py file in the libsumo package reveals import lines incorrectly expecting the presence of  submodules named '.libsumo' and '._libsumo'. These submodules appear to be missing.  

## Environment
Operating System: macOS Sonoma 14.0
Hardware: Apple M1 Air
Python Version: 3.9.18
SUMO Version: 1.19.0
libsumo Version: 1.19.0

**Comment by m-kro** [comment]
Did you follow the [instructions](https://sumo.dlr.de/docs/Libsumo.html#building_and_installing_it) to install/build libsumo?

**Comment by given-woo** [comment]
I solved the issue by using PYTHONPATH for importing libsumo and traci instead of pip installed version

**Comment by neimandavid** [comment]
Any chance you could give some more details here? I seem to be having a similar issue, but I'm fairly sure I have my PYTHONPATH set correctly:

`davidneiman@MacBookPro12BQ5-573 ~ % python3
Python 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libsumo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/sumo/1.18.0/share/sumo/tools/libsumo/__init__.py", line 30, in <module>
    from .libsumo import vehicle, simulation, person, trafficlight, edge  # noqa
ModuleNotFoundError: No module named 'libsumo.libsumo'
>>> exit()
davidneiman@MacBookPro12BQ5-573 ~ % echo $PYTHONPATH
/usr/local/Cellar/sumo/1.18.0/share/sumo/tools
`

When I clear my PYTHONPATH, things seem to get worse
`davidneiman@MacBookPro12BQ5-573 ~ % export PYTHONPATH="" 
davidneiman@MacBookPro12BQ5-573 ~ % echo $PYTHONPATH

davidneiman@MacBookPro12BQ5-573 ~ % python3
Python 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libsumo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/libsumo/__init__.py", line 30, in <module>
    from .libsumo import vehicle, simulation, person, trafficlight  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/libsumo/libsumo.py", line 13, in <module>
    from . import _libsumo
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/libsumo/_libsumo.so, 0x0002): Library not loaded: /usr/local/opt/libtiff/lib/libtiff.5.dylib
  Referenced from: <BC6D02D9-F662-3A88-BAFD-3510A31F2793> /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/libsumo/_libsumo.so
  Reason: tried: '/usr/local/opt/libtiff/lib/libtiff.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libtiff/lib/libtiff.5.dylib' (no such file), '/usr/local/opt/libtiff/lib/libtiff.5.dylib' (no such file), '/usr/lib/libtiff.5.dylib' (no such file, not in dyld cache), '/usr/local/Cellar/libtiff/4.5.1/lib/libtiff.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/libtiff/4.5.1/lib/libtiff.5.dylib' (no such file), '/usr/local/Cellar/libtiff/4.5.1/lib/libtiff.5.dylib' (no such file), '/usr/lib/libtiff.5.dylib' (no such file, not in dyld cache)`

Is there anything else you had to do here?

Initially installed SUMO using [these](https://sumo.dlr.de/docs/Installing/index.html) instructions. Tried reinstalling from source using [these](https://sumo.dlr.de/docs/Installing/MacOS_Build.html) instructions and got the same errors, so I don't think that was the problem?
