### ISSUE TITLE
deterministic netedit crash on recompute

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14315]
- rectangle selection
- move nodes and edges
- deselect
- move one node on top of another node, confirm merge
- F5

(tested with  tests/sumo/extended/stops/jumps/net2.net.xml)

```
...
Error: Attempt to delete instance of GNEReferenceCounter with count 4
Error: Attempt to delete instance of GNEReferenceCounter with count 4
Segmentation fault
```

**Comment by palvarezlopez** [comment]
Check please if the crash is coming from something related with connections

**Comment by namdre** [comment]
thankfully no crash in 1.19.0

**Comment by namdre** [comment]
> Check please if the crash is coming from something related with connections

#8  0x00007ffff58ae4d8 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff58a54cd in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x0000555555a5dd2b in std::vector<GUIDottedGeometry, std::allocator<GUIDottedGeometry> >::_M_range_check (
    this=0x7ffedc0efd80, __n=0) at /usr/include/c++/11/bits/stl_vector.h:1073
#11 0x0000555555a5d7f5 in std::vector<GUIDottedGeometry, std::allocator<GUIDottedGeometry> >::at (
    this=0x7ffedc0efd80, __n=0) at /usr/include/c++/11/bits/stl_vector.h:1094
#12 0x0000555555a5b84c in GNEContour::buildContourClosedShape (this=0x7ffedc0f0c70, s=..., 
    d=GUIVisualizationSettings::Detail::Level1, shape=..., scale=1)
    at /home/erdm_ja/sumoD/src/netedit/elements/GNEContour.cpp:390
#13 0x0000555555a5a449 in GNEContour::calculateContourClosedShape (this=0x7ffedc0f0c70, s=..., 
    d=GUIVisualizationSettings::Detail::Level1, glObject=0x7ffedc0f0a80, shape=..., scale=1)
    at /home/erdm_ja/sumoD/src/netedit/elements/GNEContour.cpp:78
#14 0x0000555555ac6784 in GNEJunction::calculateJunctioncontour (this=0x7ffedc0f0a80, s=..., 
    d=GUIVisualizationSettings::Detail::Level1, exaggeration=1, drawBubble=true)
    at /home/erdm_ja/sumoD/src/netedit/elements/network/GNEJunction.cpp:1772
#15 0x0000555555abb48c in GNEJunction::drawGL (this=0x7ffedc0f0a80, s=...)
    at /home/erdm_ja/sumoD/src/netedit/elements/network/GNEJunction.cpp:670
#16 0x0000555555a6e478 in GNEEdge::drawGL (this=0x7ffedc0eca40, s=...)
    at /home/erdm_ja/sumoD/src/netedit/elements/network/GNEEdge.cpp:660
#17 0x0000555555781bb9 in RTree<GUIGlObject*, GUIGlObject, float, 2, GUIVisualizationSettings, float, 8, 4>::Search (this=0x7ffedc03ccc0, a_node=0x7ffedc073ab0, a_rect=0x7fffffffcde0, a_foundCount=@0x7fffffffcdd4: 2, 
    c=...) at /home/erdm_ja/sumoD/src/foreign/rtree/RTree.h:1584
--Type <RET> for more, q to quit, c to continue without paging--
arch (this=0x7ffedc03ccc0, a_min=0x7fffffffce78, a_max=0x7fffffffce80, c=...) at /home/erdm_ja/sumoD/src/foreign/rtree/RTree.h:547
#19 0x0000555555774a9b in SUMORTree::Search (this=0x7ffedc03ccc0, a_min=0x7fffffffce78, a_max=0x7fffffffce80, c=...) at /home/erdm_ja/sumoD/src/foreign/rtree/SUMORTree.h:118
#20 0x0000555555800cc6 in GNEViewNet::drawGLElements (this=0x555557451b00, bound=...) at /home/erdm_ja/sumoD/src/netedit/GNEViewNet.cpp:3318
#21 0x00005555557ed7a0 in GNEViewNet::updateObjectsInPosition (this=0x555557451b00, pos=...) at /home/erdm_ja/sumoD/src/netedit/GNEViewNet.cpp:513
#22 0x00005555557f58f9 in GNEViewNet::doPaintGL (this=0x555557451b00, mode=7168, bound=...) at /home/erdm_ja/sumoD/src/netedit/GNEViewNet.cpp:1327
#23 0x0000555555de8a4e in GUISUMOAbstractView::paintGL (this=0x555557451b00) at /home/erdm_ja/sumoD/src/utils/gui/windows/GUISUMOAbstractView.cpp:327
#24 0x0000555555dec5cf in GUISUMOAbstractView::onPaint (this=0x555557451b00) at /home/erdm_ja/sumoD/src/utils/gui/windows/GUISUMOAbstractView.cpp:994
#25 0x0000555555de6e0f in GUISUMOAbstractView::handle (this=0x555557451b00, sender=0x7fffffffd440, sel=1048576, ptr=0x7fffffffd640) at /home/erdm_ja/sumoD/src/utils/gui/windows/GUISUMOAbstractView.cpp:133
#26 0x00005555557ea962 in GNEViewNet::handle (this=0x555557451b00, sender=0x7fffffffd440, sel=1048576, ptr=0x7fffffffd640) at /home/erdm_ja/sumoD/src/netedit/GNEViewNet.cpp:238
#27 0x00007ffff5d4bbc5 in FX::FXApp::dispatchEvent(_XEvent&) () from /lib/x86_64-linux-gnu/libFOX-1.6.so.0
#28 0x00007ffff5d4b0da in FX::FXApp::runOneEvent(bool) () from /lib/x86_64-linux-gnu/libFOX-1.6.so.0
#29 0x00007ffff5d4b175 in FX::FXApp::run() () from /lib/x86_64-linux-gnu/libFOX-1.6.so.0
#30 0x00005555556cd8f6 in main (argc=3, argv=0x7fffffffdc98) at /home/erdm_ja/sumoD/src/netedit/netedit_main.cpp:105

**Comment by namdre** [comment]
I did a git bisect and this is what i got:

```
9c28754713a095b2b855694c080239671ba902db is the first bad commit
commit 9c28754713a095b2b855694c080239671ba902db
Author: Pablo Alvarez Lopez <pablo.alvarezlopez@dlr.de>
Date:   Fri Jan 5 11:09:37 2024 +0100

    Fixed problem moving junction contours. Refs #14175

 src/netedit/elements/GNEContour.cpp          | 8 ++++++++
 src/netedit/elements/GNEContour.h            | 4 ++--
 src/netedit/elements/network/GNEJunction.cpp | 2 ++
 3 files changed, 12 insertions(+), 2 deletions(-)
```


for the record:

```
git bisect start
# bad: [b62391d70d86a4889d2af502a731211ce4122851] smaller toc navigation #2
git bisect bad b62391d70d86a4889d2af502a731211ce4122851
# good: [baa66a0f3641e556723892e62a29b453bf011b70] version bump 1.19.0
git bisect good baa66a0f3641e556723892e62a29b453bf011b70
# good: [b7e13884a9dc45963ffc771dff1873ea91e36432] Refactored GNELane. Refs #13894
git bisect good b7e13884a9dc45963ffc771dff1873ea91e36432
# bad: [f8169dca7d44f24a30dfaced3db29abb0c0dcbf8] adapting web wizard test #21
git bisect bad f8169dca7d44f24a30dfaced3db29abb0c0dcbf8
# skip: [6655e32115f4a5c109a688b77e769137bc161088] Added contour variable within path Segments. Refs #13894
git bisect skip 6655e32115f4a5c109a688b77e769137bc161088
# good: [83e0e43d4cbdee8673f5ccf2708ab506df8efeda] Updated GNELane. Refs #13894
git bisect good 83e0e43d4cbdee8673f5ccf2708ab506df8efeda
# good: [2f3a8a0e61ed8f57d74ab9935bb5ddeeadd61b3b] add current travel time to current stage, instead of placeholder, ref. #11838
git bisect good 2f3a8a0e61ed8f57d74ab9935bb5ddeeadd61b3b
# good: [59c3e9418bac6ef9862eb56682c027ea05038d45] Clarify opposite direction driving with multiple lanes ref #2
git bisect good 59c3e9418bac6ef9862eb56682c027ea05038d45
# bad: [76bd5abc57d7841d56d0b576483223702e7d9930] Renamed MoveSingleElementValues and MoveMultipleElementValues. Refs #12
git bisect bad 76bd5abc57d7841d56d0b576483223702e7d9930
# good: [6ef10bfe21fd3d2afb4572924d22fa6c1c6319c6] adding pandas_read_xml requirement for macrOutput
git bisect good 6ef10bfe21fd3d2afb4572924d22fa6c1c6319c6
# good: [167bcd84139b1823ef0d85775ff0f6254324ae3d] update doc ref #2 #14202
git bisect good 167bcd84139b1823ef0d85775ff0f6254324ae3d
# good: [1d2741cfb9d826ffe501765e8ab3931a65a535e6] adapting tests to penalty #21
git bisect good 1d2741cfb9d826ffe501765e8ab3931a65a535e6
# bad: [6824808166832f0c959e35d3444be85c23a95ecc] Disabled moving contour when an element is moved. Refs #14175
git bisect bad 6824808166832f0c959e35d3444be85c23a95ecc
# bad: [9c28754713a095b2b855694c080239671ba902db] Fixed problem moving junction contours. Refs #14175
git bisect bad 9c28754713a095b2b855694c080239671ba902db
# first bad commit: [9c28754713a095b2b855694c080239671ba902db] Fixed problem moving junction contours. Refs #14175
```

In between there was
- a commit that didn't build
- a commit where rectangle selection was broken
- a commit where junction nodes where invisible/flickering

**Comment by palvarezlopez** [comment]
Ok, its the new GNEContours. I check it.
