### ISSUE TITLE
ubuntu 22.04 doesn't show taskbar icons for sumo-gui / netedit

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14317]

**Comment by behrisch** [comment]
It seems to be very dependent on the window manager / desktop environment you use. On XFCE I do not experience it. On Budgie only after a suspend. Sometimes it only affects the task switcher but not the taskbar. @namdre You use plain GNOME?

**Comment by namdre** [comment]
I'm using GNOME 42.9 with the Dash-to-Panel extension.

**Comment by namdre** [comment]
Seems to be related to the window manger rather than a SUMO regression then.

**Comment by behrisch** [comment]
It seems to be we can't do much about it. Feel free to reopen if more problems like this arise and we can do something.
