### ISSUE TITLE
function: how many people get off a vehicle

### ISSUE THREAD

**Issue by claudiacbh** [eclipse-sumo/sumo#14313]
Hello

Could you please tell me how to know in real-time how many people get off a bus?  Is there a TRACI function that does this? I need this data to calculate the necessary time that a bus needs to stay stationary at the bus stop (for people boarding and alighting) in case more people get off than those who board? 

Thank you very much!

SUMO-version:1.18.0

operating system: Windows 11

**Comment by m-kro** [comment]
This can only be done indirectly. You can iterate through the plans of travelling persons (`traci.person.getStage` [ref](https://sumo.dlr.de/pydoc/traci._person.html#PersonDomain-getStage)) to get an idea of how many of them want to arrive at a certain stop. If the bus has already arrived at the stop, I think there is no way to monitor the boarding process effectively.

**Comment by m-kro** [comment]
I'll add a test case within the next weeks which shows how one can aggregate the count of persons to alight at a stop.
