### ISSUE TITLE
crash when trying to define a chargingStation

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14323]
thankfully our tests are catching this

**Comment by palvarezlopez** [comment]
probably related with charging stations attributes. I'm going to check it as soon as possible.

**Comment by palvarezlopez** [comment]
The problem is caused by new attribute SUMO_ATTR_PARKING_AREA

**Comment by namdre** [comment]
still crashes when trying save chargingStation "Error: attribute 'parkingArea' doesn't have a default value
Quitting (on error)"
