### ISSUE TITLE
Retrieve Number of People Waiting on the Bus Stop in SUMO Simualtion

### ISSUE THREAD

**Issue by kendo2** [eclipse-sumo/sumo#14328]
I have this  script to extract number of people wait in the bus stop:
===============================
j = 0
step=60
# Initialize an empty list to collect the bus data
data_bus = []
```
`bus_stop=traci.busstop.getIDList();
 
print(bus_stop)

while(j<=10000):
    #this runs one simulation step
    traci.simulationStep();
   
    count=traci.busstop.getIDCount()
    #print('time', total_people)
    
    if j==step:
        print('time ',step)
        for i in bus_stop:
            total_people=traci.busstop.getPersonCount(i)
            print(j,i,total_people)
        step=step+1`
```
===============================

But the result always zero:
489 5_2 0
489 5_3 0
489 5_4 0
489 6_1 0
489 6_2 0
489 6_3 0
489 6_4 0
489 6_5 0
489 7_1 0
489 7_2 0
489 7_3 0
489 8_1 0
489 8_2 0
489 8_3 0
489 8_4 0
489 8_5 0
489 9_1 0
489 9_2 0
489 9_3 0

I dont know why. When I check, there are many people waiting but it could not extracted.

Here is example of y trips data:
`
```
<routes>
  <person id="0" depart="0">
    <walk from="37403051#6" to="37403051#6"/>
    <ride busStop="6_5" to="469347904" arrivalPos="2"/>
  </person>
  <person id="1" depart="0">
    <walk from="-842128019#0" to="1002913246#2"/>
    <ride busStop="19_3" to="469347904" arrivalPos="2"/>
  </person>
  <person id="2" depart="0">
    <walk from="-450736356#1" to="468205957"/>
    <ride busStop="18_2" to="469347904" arrivalPos="2"/>
  </person>
  <person id="3" depart="0">
    <walk from="-478972124#1" to="-476477708#1"/>
    <ride busStop="1_1" to="117760420#1" arrivalPos="2"/>
  </person>
  <person id="4" depart="0">
    <walk from="158059104#2" to="-59526908"/>
    <ride busStop="15_1" to="469347904" arrivalPos="2"/>
  </person>`
```

and additional data:

```
` <flow id="0" type="bus" to="164685644#15" from="164685644#15" begin="600" end="7200" period="300">
    <stop busStop="0_3" duration="30"/>
    <stop busStop="0_1" duration="30"/>
    <stop busStop="0_2" duration="30"/>
    <stop busStop="0_4" duration="30"/>
  </flow>
```

Please let me know.
Thank you

I hope I can retrieve number of people data

**Comment by namdre** [comment]
The 'busStop' attribute of the ride defines the destination. To let people wait at a busStop, the 'busStop' attribute must also be given in the `<walk>`. In your current input, people only ride to a busStop but never wait at one.

**Comment by kendo2** [comment]
It perfectly works!! Thank you so much
