### ISSUE TITLE
broken visualization of rail tracks

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14327]
- netedit shows rails very narrow (looks like spread-bidi mode but there is only a single track)
- sumo-gui shows rails as roads and only goes to rail style when activating spread-bidi mode

**Comment by palvarezlopez** [comment]
@namdre about the first points, can we discuss at the next Development Meeting? I enable it after a debate with Micha.

**Comment by namdre** [comment]
> But I'm not sure if is a regression or not.

What do you mean? It was still working in 1.19, hence tagged as dev_regression.

**Comment by namdre** [comment]
> about the first points, can we discuss at the next Development Meeting? I enable it after a debate with Micha.

Is there a ticket for this change?

**Comment by palvarezlopez** [comment]
> > But I'm not sure if is a regression or not.
> 
> What do you mean? It was still working in 1.19, hence tagged as dev_regression.

I mean that I don't remember if it was e changed it for an specifically reason, or is a regression (But if you say that is a regression, then is ok)

> > about the first points, can we discuss at the next Development Meeting? I enable it after a debate with Micha.
> 
> Is there a ticket for this change?

Not specifically, it was done in the context of optimization. The rollback is very easy (just changing two or three code lines in GNELane::drawGL()

**Comment by namdre** [comment]
I feel strongly about the visual change in netedit: Having tracks being drawn normal/narrow communicates important information about bidirectional track usage. The current change violates this expectation and breaks my workflow. If there is a strong rendering speed-up to be had I'd like to have some numbers and then we could make it optional. Though I'd have to be convinced first that having narrow tracks is the only way to draw things fast.

**Comment by palvarezlopez** [comment]
> I feel strongly about the visual change in netedit: Having tracks being drawn normal/narrow communicates important information about bidirectional track usage. The current change violates this expectation and breaks my workflow. If there is a strong rendering speed-up to be had I'd like to have some numbers and then we could make it optional. Though I'd have to be convinced first that having narrow tracks is the only way to draw things fast.

In this case, this doesn't affect to the optimization. (My mistake was not having made a specific ticket.) I enabled it as default because I received a feedback of Evi about problems editing connections between rails due superposition. But as I say, I can rollback it very easily.

**Comment by namdre** [comment]
Please do. The problem of Evi is easily solved by switching to the "rail" visualisation mode preset or by activating spread-bidi in the settings explicitly.

**Comment by palvarezlopez** [comment]
@namdre and about the second point? All of my changes were done in GNELane.

**Comment by palvarezlopez** [comment]
> You did, in [8173327](https://github.com/eclipse-sumo/sumo/commit/81733275c5c7e17c2cee3f44ef37665593750c11)

😨 😱 right, sorry.

**Comment by namdre** [comment]
nope. Still doesn't look as it should:
![Bildschirmfoto von 2024-02-18 08-54-53](https://github.com/eclipse-sumo/sumo/assets/6240630/413887df-2d64-4ef3-8e7a-b841486aedbd)
![Bildschirmfoto von 2024-02-18 08-55-15](https://github.com/eclipse-sumo/sumo/assets/6240630/01587f1e-0e2c-47e1-a5d0-c9b2754f32a4)

**Comment by namdre** [comment]
single track mode is fixed but spread-bidi mode still doesn't look like it used to. 
![Bildschirmfoto von 2024-02-23 07-38-34](https://github.com/eclipse-sumo/sumo/assets/6240630/5cc0f790-f7f6-4ee7-8151-875ab2bebf36)

and this is what it should look like (1.19.0):
![Bildschirmfoto von 2024-02-23 07-39-59](https://github.com/eclipse-sumo/sumo/assets/6240630/d9a2088e-dbf9-4e2e-b624-07cbdf98fb21)

**Comment by namdre** [comment]
- this fix broke the coloring (i.e. color by speed etc.)
- compared to 1.19 the rendering is broken when switching from "spread-bidi" mode back to normal view. (it should all be on top of each other again but isn't)
