### ISSUE TITLE
Count People on the bus stop

### ISSUE THREAD

**Issue by kendo2** [eclipse-sumo/sumo#14321]
Hi, I try to count people who stop in the bus stop for each time step. I use this script:
```
bus_stop=traci.busstop.getIDList();
 
print(bus_stop)

while(j<=10000):
    #this runs one simulation step
    traci.simulationStep();
   
    count=traci.busstop.getIDCount()
    #print('time', total_people)
    
    if j==step:
        print('time ',step)
        for i in bus_stop:
            total_people=traci.busstop.getPersonCount(i)
            print(j,i,total_people)
        step=step+60
```
     
but the result always 0

========
360 4_1 0
360 4_2 0
360 4_3 0
360 4_4 0
360 5_1 0
360 5_2 0
360 5_3 0
360 5_4 0
360 6_1 0
360 6_2 0
360 6_3 0
360 6_4 0
360 6_5 0
360 7_1 0
360 7_2 0
360 7_3 0
360 8_1 0
360 8_2 0
360 8_3 0
360 8_4 0
360 8_5 0
360 9_1 0
360 9_2 0
360 9_3 0
========

the person info:
```
<person id="7612" depart="0">
    <walk from="-478011644" to="165486948#5"/>
    <ride busStop="9_3" to="117760420#1" arrivalPos="2"/>
  </person>
  <person id="7613" depart="0">
    <walk from="478011644" to="165486948#5"/>
    <ride busStop="9_3" to="117760420#1" arrivalPos="2"/>
  </person>
```
Please share the info for this if some one know

**Comment by m-kro** [comment]
You do not check the waiting persons at every time step but only every 60th time step. I don't know how long your time steps are, but let's say you use the default of 1s, the bus may have already collected them (or they haven't arrived at the bus stop yet).

**Comment by m-kro** [comment]
Same as #14328

**Comment by kendo2** [comment]
Thank you, really appreciate it
