### ISSUE TITLE
Vehicles block each other in front of parking vehicles

### ISSUE THREAD

**Issue by oshadajay** [eclipse-sumo/sumo#14322]
Hi, I am running a SUMO simulation with a set of parked vehicles on road and it seems like some vehicles are showing a weird behavior when changing lanes around parked vehicle. They also move into the space of parking area which is already occupied by a vehicle which ideally should not happen. I have attached a video below. Appreciate if you can look into this. Thank you.

https://github.com/eclipse-sumo/sumo/assets/55861474/46654045-cb1c-4aa8-857b-7a7ba7ef451b

**SUMO-version:**
1.18

**operating system:**
Windows 10

**Comment by m-kro** [comment]
I noted:

- some lane change issues due to the high flow (vehicles don't manage to change lane before the parking lane begins)
- vehicle queues grow upstream into empty parking spaces

I didn't see vehicles entering an already occupied parking space... Maybe can you point us to the exact situations you consider weird?

**Comment by oshadajay** [comment]
I have attached an image to describe what I mean by vehicles entering an already occupied parking space. I think if the vehicle parks in the middle of the bay the impact of this would be reduced. In addition to that, the bullet points you have listed are the weird behaviors I have observed. Two vehicles get stuck behind the parking area, yet there is no reason for them since they are not looking for parking and they should move ahead using the other lane.

![image](https://github.com/eclipse-sumo/sumo/assets/55861474/0d03fcee-c5f9-4aa1-a173-9e5226df7930)

**Comment by oshadajay** [comment]
I have attached the files here. Thank you for looking into this.

[parking_issue.zip](https://github.com/eclipse-sumo/sumo/files/14290667/parking_issue.zip)

**Comment by m-kro** [comment]
Happens on edge B2B1 where vehicles 329 and 341 block each other...

**Comment by oshadajay** [comment]
Hi, thank you for identifying this as a bug. Would this be assigned to someone from the development team?

**Comment by namdre** [comment]
Appreciate the offer to contribute.  It's easier for me to tackle this issue if you can reproduce it in the development version. Right now, there are no deadlocks/teleports when using the current nightly build: https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots

**Comment by oshadajay** [comment]
Oh shoot, I missed this comment. I'll use the nightly build and let you know. Maybe the issue is already solved. Thank you.

**Comment by oshadajay** [comment]
@namdre With the nightly build I could not observe the issue occurring. Probably it has been solved by some other developments. Let's close the issue for now and I'll reopen it if I observe it in the future. Thanks a lot for your support on this.

**Comment by oshadajay** [comment]
@namdre Unfortunately, I observed the issue again with version 1.20. I have attached a video below. Would you be able to reopen the issue and look into this? Thanks a lot.

https://github.com/eclipse-sumo/sumo/assets/55861474/8ee5982a-da43-44f5-8150-6b74dbd48b28

**Comment by oshadajay** [comment]
You can reproduce the issue by running "sumo-gui -c melb.sumocfg --tripinfo-output test.xml --step-length 0.1" with the attached files. Kindly let me know if you need any additional information or support. Thank you.

[sumo_issue_v1_20.zip](https://github.com/eclipse-sumo/sumo/files/15494708/sumo_issue_v1_20.zip)
