### ISSUE TITLE
which options limit the minimum headway time

### ISSUE THREAD

**Issue by NekoHanko** [eclipse-sumo/sumo#14331]
Hi, I used the command traci.vehicle.settau in SUMO, but when I set a headway time less than 1, it seems that vehicles do not follow the desired headway time for car-following. I have already set speedMode to 0, but it doesn't seem not work.
I wanna know which options limit the headway time,thanks!

**Comment by namdre** [comment]
setTau is expected to take effect. Note that sumo automatically extends the headway by minGap so this may be a confounder in your observation. What carFollowModel are you using?

**Comment by NekoHanko** [comment]
Thanks for your support! I have been using the ACC，CACC and IDM models, and I've set their default Tau values to 0.6. Before running the setTau command, vehicles were working well. When I use the setTau command to increase Tau (greater than 1), vehicles can quickly follow the desired headway time for car-following. However, when I use the command to decrease it back to 0.6, vehicles seem to not follow the desired headway time that I've set (only decreasing to 1).

**Comment by namdre** [comment]
A vehicle can only catch up to it's leader if its desired (and permitted) speed is higher than the leader speed. Since the desired speed is randomized by default, catchup is only expected 50% of the time. See https://sumo.dlr.de/docs/Simulation/VehicleSpeed.html

**Comment by NekoHanko** [comment]
> A vehicle can only catch up to it's leader if its desired (and permitted) speed is higher than the leader speed. Since the desired speed is randomized by default, catchup is only expected 50% of the time. See https://sumo.dlr.de/docs/Simulation/VehicleSpeed.html

Got it！Thanks a lot!Have a nice day!
