### ISSUE TITLE
Unboard train's passengers through doors when the rail line is curved

### ISSUE THREAD

**Issue by bcoueraud87** [eclipse-sumo/sumo#14334]
The current code, located in MSStageDriving.cpp, makes the assumption that the train is driving on straight rail line. Thanks to the train helper, it is possible to now take into curvature the curvature.

**Comment by bcoueraud87** [comment]
Please assign me.

**Comment by bcoueraud87** [comment]
Note: the original feature was created for the needs of the JuPedSim coupling but actually can be used standalone.

**Comment by namdre** [comment]
Would you mind listing the pull requests or direct commits that already went into this ticket?

**Comment by bcoueraud87** [comment]
I think we should close this ticket, even if #14335 and #7049 are open.
