### ISSUE TITLE
crash on saving network

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14357]
not deterministically )-:

**Comment by palvarezlopez** [comment]
Found after doing some modifications?

**Comment by namdre** [comment]
most likely. Happened on windows so no console errors.

**Comment by namdre** [comment]
Lots of nightly netedit tests failed. When I manually run demandelements/basic/separated_vtypes, this is what I get:

```
Error: Attempt to delete instance of GNEReferenceCounter with count 1
Error: Attempt to delete instance of GNEReferenceCounter with count 1
Error: Attempt to delete instance of GNEReferenceCounter with count 1
Error: Attempt to delete instance of GNEReferenceCounter with count 1
Error: Attempt to decrement references below zero for instance of GNEReferenceCounter
Error: Attempt to decrement references below zero for instance of GNEReferenceCounter
Error: Attempt to decrement references below zero for instance of GNEReferenceCounter
Error: Attempt to decrement references below zero for instance of GNEReferenceCounter
Error: Attempt to decrement references below zero for instance of GNEReferenceCounter
Error: Attempt to decrement references below zero for instance of GNEReferenceCounter
Error: Attempt to decrement references below zero for instance of GNEReferenceCounter
Error: attribute 'parkingArea' doesn't have a default value
Quitting (on error).
```

**Comment by palvarezlopez** [comment]
This is probably caused by the charging station saving error.

**Comment by namdre** [comment]
the crash with the chargingStation is fixed via dc71733326e6897aa0910b7db21bb52566302c34, but we should wait for tomorrow on the nightly results. Also, the crash I experienced didn't have any additionals so there is still something else going on.

**Comment by palvarezlopez** [comment]
I think that after https://github.com/eclipse-sumo/sumo/commit/dc71733326e6897aa0910b7db21bb52566302c34 and https://github.com/eclipse-sumo/sumo/issues/14315 we can close this ticket

**Comment by namdre** [comment]
we'll just open it again if crashes show up again
