### ISSUE TITLE
get pedestrian depart time

### ISSUE THREAD

**Issue by way-thu** [eclipse-sumo/sumo#14366]
Is there any method to get the pedestrian departure time just like the traci.vehicle.getDeparture() function does, return the value of when the person departs in the simulation.
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/574438ea-3e6b-405b-b1f0-05520fa19de9)

**SUMO-version:**

**operating system:**

**Comment by way-thu** [comment]
The way of my person simulation input is just like this:
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/0f22d569-2db0-4d26-976e-326cf122c43e)

**Comment by m-kro** [comment]
You can inspect the single stages of the person plan using `traci.person.getStage` ([ref](https://sumo.dlr.de/pydoc/traci._person.html#PersonDomain-getStage)). Provide a negative index to access past stages. The returned stage object contains the departure time (not sure if it is the planned or the actual one).
