### ISSUE TITLE
Car following model

### ISSUE THREAD

**Issue by khzannat** [eclipse-sumo/sumo#14364]
I am trying to do traffic simulation in Sumo based on the Newell's car following model. My calibrated parameters for Newell's models are tau and minimum gap. 
<vType id="type_1" minGap="1.67" maxSpeed="13.4112" vClass="passenger" accel="4" decel="4" sigma="0.5" tau="1.5" speedDev="0" />
I am wondering, as the deafult car following model in Sumo is Karuss model, do I need to add  carFollowModel="Krauss" (as I am using some parameters from krauss model in the simulation except ) along with the above mentioned parameters? 
My another query is regarding followers and leaders speed and velocity. After specifying the parameters of Newell's model, how can I determine which speed and velocity my followers and leaders are following? 

TIA
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by m-kro** [comment]
If you are interested in actually implementing Newell's model, then please look into the [docs](https://sumo.dlr.de/docs/Developer/How_To/Car-Following_Model.html) about our advice in this respect. There it is described how parameters are read, where formulas for speed should go etc. 

Apart from that, car-following parameters have default values as mentioned in the [docs](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#car-following_model_parameters). `carFollowModel="Krauss"` actually is a default and so the Krauss model is chosen if not defined differently. Many parameters are shared among multiple car-following models as well.

**Comment by namdre** [comment]
see #6397 on how to approximate Newell with Krauss.

**Comment by khzannat** [comment]
@namdre I have followed the attached issue in my case. Then I couldn't figure it out what was my leader's and follower's speed equation. Is it following the "Krauss" model's unbounded speed and acceleration equation?

**Comment by namdre** [comment]
Here is how I understand the explanation given in #6397: 
- Newel does not bound acceleration / deceleration
- setting very high values for `accel` and `decel` for the default Krauss model is a good approximation for Newel (Krauss  then follws at a fixed distance of  `tau` * speed + minGap)
- you need to set step-size to the same value as tau (or just leave both at their default of "1") to make this work

**Comment by khzannat** [comment]
Thank you very much, the issue has been resolved.
