### ISSUE TITLE
Nightly Snapshots

### ISSUE THREAD

**Issue by transport45678** [eclipse-sumo/sumo#14378]
While I am checking download pages to load recent nightly snapshot, I recognized that Windows installer with all extras (contains GPL code) : https://sumo.dlr.de/daily/sumo-win64extra-git.msi November 09 2023 04:19:44 UTC 169.8 MB. 
 
Is the date true?

![image](https://github.com/eclipse-sumo/sumo/assets/153621221/dbb6f167-216b-48cb-bc12-65384a2ce0de)

**Comment by m-kro** [comment]
We'll check whether the installer really hasn't been updated automatically since then. In the meantime you can download the zip archive (one line below) and extract it to a directory of your choice. Then set the environment variable **SUMO_HOME** to the file path of the SUMO main directory.

**Comment by behrisch** [comment]
has been fixed in https://github.com/eclipse-sumo/sumo/commit/8d399266049169309c1bd63d3088f83bee3a8dac
