### ISSUE TITLE
Changing crossing elevation

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse-sumo/sumo#14385]
Hi,

I was wondering if there is a way to change the elevation of a pedestrian crossing without changing the elevation of the whole junction in NETEDIT.

Best,
Reza.

**Comment by namdre** [comment]
At the moment, no. Can you explain the use case?

**Comment by MohamadReza-Haghani** [comment]
I made a real-time connection between Unity and SUMO. SUMO creates vehicles and pedestrians. Then, at every simulation step, SUMO sends the positions of vehicles and pedestrians to Unity to make a 3D representation of the simulation. In my Unity network, sidewalks are a little higher than crossings. To create the corresponding elevation difference in SUMO, I need to either reduce the elevation of crossings or increase the elevation of sidewalks. As you see in the following screenshot, the EastBound sidewalk is attached to the edge having a cycle track. I was wondering if it is possible to set a different elevation to the crossing without changing the elevation of the junction or set a different elevation to the sidewalk without changing the elevation of the edge.

![Capture](https://github.com/eclipse-sumo/sumo/assets/64617116/5245419e-f717-4e91-b056-cb768ce7ef24)

Thanks,
Reza.

**Comment by namdre** [comment]
actually, you can set a custom shape for a crossing and this custom shape may use positions in x,y,z format so you *can* change the elevation. (see https://sumo.dlr.de/docs/Networks/PlainXML.html#pedestrian_crossings)

**Comment by MohamadReza-Haghani** [comment]
Very helpful, thanks! I also was wondering if I could change the shape of a specific lane in an edge and give that specific lane a different elevation.

**Comment by namdre** [comment]
same concept: https://sumo.dlr.de/docs/Networks/PlainXML.html#lane-specific_definitions
