### ISSUE TITLE
Tutorials-Manhattan Error in running the sample program

### ISSUE THREAD

**Issue by XuanlinZeng** [eclipse-sumo/sumo#14398]
Hello, I am learning the [Tutorials-Manhattan](https://sumo.dlr.de/docs/Tutorials/Manhattan.html).

When I am running the program as the tutorial shows:
![image](https://github.com/eclipse-sumo/sumo/assets/91841853/32402e77-25f6-4bb1-b2a3-18cc3271283d)

` <SUMO_HOME>/tools/randomTrips.py -n net.net.xml -o flows.xml --begin 0 --end 1 --flows 100 --jtrrouter  --trip-attributes 'departPos="random" departSpeed="max"'`

the cmd dialog shows: `randomTrips.py: error: unrecognized arguments: trip-attributes departSpeed=max`.

How can I run the program successfully?

**SUMO-version: 1.18.0**

**Windows 11**

**Comment by m-kro** [comment]
Please try other methods of using quotation marks in the script call. What happens with `<SUMO_HOME>/tools/randomTrips.py -n net.net.xml -o flows.xml --begin 0 --end 1 --flows 100 --jtrrouter  --trip-attributes "departPos=\"random\" departSpeed=\"max\""`?

**Comment by XuanlinZeng** [comment]
Thank you, Mirko. It makes sense! The program runs successfully now.
