### ISSUE TITLE
unable to right-click on riding person

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14390]
clicks always go to the vehicle (still working in 1.19.0), alt+click still works and lists the person

**Comment by namdre** [comment]
@palvarezlopez do you have any idea what could have causes this to regress?

**Comment by palvarezlopez** [comment]
@namdre I don't know. @bcoueraud87 did you changed something of the person code during your changes in JuPedSim?

**Comment by bcoueraud87** [comment]
> @namdre I don't know. @bcoueraud87 did you changed something of the person code during your changes in JuPedSim?

Nope.

**Comment by namdre** [comment]
I'll do a git bisect...

**Comment by namdre** [comment]
it was broken with 44adc3b777a5a476ca92eaff1b6313f9b330591b

**Comment by namdre** [comment]
This is worse. Now right-click on vehicles doesn't work anymore.

**Comment by namdre** [comment]
I tested on windows and linux. Both show the same faulty behavior.

**Comment by palvarezlopez** [comment]
[taxi.zip](https://github.com/eclipse-sumo/sumo/files/14479594/taxi.zip)
 
 I used this network for the testing. Can you please check if you have the same problem? (I tested it when the person takes the taxi)

**Comment by namdre** [comment]
I can confirm that right-click on vehicle fails

**Comment by palvarezlopez** [comment]
Ok, I check it.
