### ISSUE TITLE
invalid train labels

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14393]
- was working in 1.19.0
- only shows up when rendering rail carriages with exaggerated size
[vehLabels.zip](https://github.com/eclipse-sumo/sumo/files/14375120/vehLabels.zip)

![Bildschirmfoto von 2024-02-23 01-56-35](https://github.com/eclipse-sumo/sumo/assets/6240630/1e5a9796-d8f1-4753-9601-17bc5524b7c8)

**Comment by namdre** [comment]
@bcoueraud87 git bisect revealed that 6d4808c849f6164d32c310a3e903935eb3d1589e broke the labels. Probably something related to unmatched pushMatrix/popMatrix.

**Comment by bcoueraud87** [comment]
I will have a look.
