### ISSUE TITLE
hotkey Alt+L,Alt+E no longer works

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14396]
the elements of the locate menu (Alt+L) could be selected with standard menu shortcuts Alt+LETTER in 1.18 but no longer in 1.19

It's still working in sumo-gui, thankfully.

(important to me personally, because that's what I've been using all the time)

**Comment by palvarezlopez** [comment]
uhm, strange. I'm going to check it

**Comment by palvarezlopez** [comment]
the problem is probably caused by the language. I checked netedit in english, and it works as expected.

**Comment by namdre** [comment]
For me it does not. Tested with english on linux and windows.

**Comment by namdre** [comment]
was broken in e87513569167ae5a9ccc9e8006e3cd992db988a2

**Comment by palvarezlopez** [comment]
I cannot understand why in my Windows worked as expected (I tested it yesterday)

**Comment by namdre** [comment]
I suspect that the translations still had the `&` characters.
