### ISSUE TITLE
missing connections after adding edge

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14391]
- create an edge
- F5
- create a second edge outgoing of the first
- F5

Expectation (working in 1.18): there is a connection between the edges
Observation (1.19): missing connection

I'm guessing this is closer to the root cause for #13699

**Comment by namdre** [comment]
@palvarezlopez I'll do a git bisect but will probably have to discuss things with you.

**Comment by palvarezlopez** [comment]
@namdre can you filter in the bisect all #13667 tickets? (is the JuPedSim Ticket)

**Comment by namdre** [comment]
I cannot filter the diff any further. However, if you can (locally) fix the build for versions between the last known good and the first known bad version, you can check whether they are affected by the problem an we can get a smaller range and shorter diff.

**Comment by palvarezlopez** [comment]
Broken in https://github.com/eclipse-sumo/sumo/commit/436f243bf8bf83b31fe33a07f3346c7716cad5bb
