### ISSUE TITLE
Installing python environment of the test server via pip3 and req_test_server.txt results in malfunctioning environment

### ISSUE THREAD

**Issue by RobertHilbrich** [eclipse-sumo/sumo#14392]
When trying to recreate the python environment of the test server on another machine running Ubuntu 22.04 by using `pip3` (and not `apt`), the result is a python environment that does not work. 

```pip3 install -r $SUMO_HOME/tools/req_test_server.txt```

Issues:
- Texttest does not work (could be removed from `req_test_server.txt`?) - missing gi module (GObject)
- Rtree version 0.9.7 from pypi seems to be buggy (GTFS tests do not work)

**Comment by namdre** [comment]
seems to be unlisted dependencies for texttest: we could add them explicitly as a workaround (Robert Alms)

**Comment by behrisch** [comment]
I am not sure whether the texttest problem can be solved with pip alone. There are dependencies concerning GTK where we need at least some OS packages installed. @robertalms Did you check which dependencies are missing and whether they are all available on pypi?

**Comment by robertalms** [comment]
I cannot retrace my steps, unfortunately, but I vaguely remember that I had to subsequently install something like `pygobject` and `pycairo` to get texttest to run without errors on my fresh Ubuntu 22 server...

**Comment by behrisch** [comment]
Yes and here is the problem. Both of them cannot be installed right away from pypi but need header files on the underlying system. I think removing texttest from req_test_server.txt is the easiest solution, because we do not use it as a library anyway

**Comment by behrisch** [comment]
@RobertHilbrich I cannot reproduce the rtree problem here. Do you still have the error message somewhere?
