### ISSUE TITLE
Accessing Current Green Phase Duration in Real-Time with TraCI

### ISSUE THREAD

**Issue by unversezai94** [eclipse-sumo/sumo#14400]
Hello,

I am currently managing a traffic intersection using the TraCI module with SUMO. In this management scheme, the duration of the green phases changes according to the traffic conditions. I would like to monitor this duration in real-time and enforce a maximum limit to prevent it from exceeding a certain value. However, I am facing difficulties in retrieving the current green phase duration directly through TraCI during the simulation.

I noticed that this value is displayed for each phase under the "track phases" option in the sumo-gui. Is there a way to programmatically access this green phase duration value through TraCI? This feature would be incredibly useful for dynamically managing traffic lights based on real-time traffic conditions, allowing for more efficient traffic flow and reduced waiting times.

Any guidance on how to achieve this or pointers to relevant documentation would be greatly appreciated.

Thank you for your support.

SUMO-version: 1.19.0

operating system: Win11 Pro

**Comment by m-kro** [comment]
Please see #14120 for some advice.
