### ISSUE TITLE
SUMO Re-compiling Issue

### ISSUE THREAD

**Issue by Sid9993** [eclipse-sumo/sumo#14408]
I'm using the SUMO with the Plexe and I re-built the source code of both Plexe and SUMO for introducing our custom car following model. But when I recompile the SUMO I'm getting a lot of "Could not find" errors mainly in Java and JNI.

<img width="928" alt="image" src="https://github.com/eclipse-sumo/sumo/assets/75777345/e76996a1-71e6-4c1b-bd31-2eab66d84c0a">
Is this normal or should I need to solve the errors? If so, how can I solve these errors?

**PLEXE-version:**Instant Plexe 3.0
**SUMO-version:**1.7.0
**operating system:**Debian 10, Linux 4, GNOME 3

**Comment by namdre** [comment]
If you don't need java bindings you can safely ignore this.

**Comment by Sid9993** [comment]
> If you don't need java bindings you can safely ignore this.

Ok thanks namdre
