### ISSUE TITLE
Falied to convert osm net files from open-source datasets.

### ISSUE THREAD

**Issue by fantastic8124** [eclipse-sumo/sumo#14407]
Add your issue description here.
Hi, while using SUMO to convert road network files, I have been unable to convert the following road network files, from open-source datasets including HighD, inD, resulting in the following error:

      netconvert --osm-files mapfile-Tianjin.osm -o t6.net.xml
      Error: No nodes loaded.
      Quitting (on error).

But when I tried to convert the map exported directly from the OSM website, I was successful, so I am sure there is no problem with the environment configuration;
I have also reviewed previous issues and tried to replace the SUMO version, but it was not successfully resolved. I hope you can give me some suggestions. Thank you very much!

*If possible, upload an example that shows your problem.*
[examples.zip](https://github.com/eclipse-sumo/sumo/files/14395333/examples.zip)
The uploaded files are all unconverted road networks from the IND, HighD, and SinD open-source datasets

**SUMO-version:**
1.19.0
**operating system:**
Windows 11 (x64)

**Comment by namdre** [comment]
this is not an OSM dataset.  At best it's something inspired by the OSM data format.

If you replace `<tag k='type' v='virtual' />` for the `<way>` elements with `<tag k='highway' v='unclassified'/>`, the netconvert will be able to import it as a road network. 
Note, that the coordinates aren't plausible lat/lon values either. If you want a somewhat usable network you can set netconvert option **--proj.scale 10** (or some larger value).

**Comment by fantastic8124** [comment]
Thank you for your suggestion！
I found that these road networkts were edited by JOSM, and according to your suggestion, they can indeed be converted to SUMO road network. However, the network is chaotic and may require further clarification of replacement rules.
![image](https://github.com/eclipse-sumo/sumo/assets/63543931/f9b79054-aac5-4203-a4d7-9d29f4f184fc)

**Comment by namdre** [comment]
> Note, that the coordinates aren't plausible lat/lon values either. If you want a somewhat usable network you can set netconvert option --proj.scale 10 (or some larger value).

This is what my other comment was addressing.
