### ISSUE TITLE
SUMO Wiki down

### ISSUE THREAD

**Issue by robertalms** [eclipse-sumo/sumo#14406]
Apparently SUMO's documentation site is down at the moment: [docs](https://sumo.dlr.de/docs/)
time. Sat, 24th Feb, 17:45.

The page looks like this:
![image](https://github.com/eclipse-sumo/sumo/assets/53571755/b8367201-0b45-4bbd-8e49-bccb27888e84)

**Comment by robertalms** [comment]
correction: seems to be the landing page only. I could use the search bar, at least.

**Comment by namdre** [comment]
seems fixed (I triggered a rebuild)
