### ISSUE TITLE
combo boxes drop downs are too short

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14412]
the gui settings combo box should accomodate all entries or at least up to bigger maximum. Same for the various coloring scheme dropdowns.

**Comment by namdre** [comment]
was still working in 1.18.0

**Comment by namdre** [comment]
was broken in a1e91cf22a3f3b821cb9d80ecc1c95615bbd9952

**Comment by namdre** [comment]
During work on the combobox the maximum number of rows was limited to 15.  This was persumably done because some combination of OS and display scaling cannot fit more row on screen. 

Since many other OS/scaling combinations can fit more rows comfortably (and there are some situations where it makes sense to do so), this decision needs to be re-evaluated.

**Comment by namdre** [comment]
@palvarezlopez The new comboboxes seem to be "smart" in the sense of never showing more rows than the current number of items. Therefore we don't need multiple size constants but only have to define the maximum. Are you aware of any exceptions to this?

**Comment by palvarezlopez** [comment]
I'm thinking, and I can't find an exception.
