### ISSUE TITLE
Shared bus bike lanes assigned width of 1m in netconvert

### ISSUE THREAD

**Issue by gladysmcgan** [eclipse-sumo/sumo#14419]
Hi, I noticed that bus lanes in my network are being created in netconvert with a width of 1. 

![Screenshot 2024-02-27 at 10 15 00](https://github.com/eclipse-sumo/sumo/assets/59922884/456692a0-2743-4ec4-b404-6d330ef11484)

It seems like it happens because of overlapping tags with the bicycle lanes.

```
    <tag k="oneway:bicycle" v="no"/>
    <tag k="oneway:bus" v="no"/>
```
or

```
    <tag k="cycleway" v="opposite"/>
    <tag k="oneway:bus" v="no"/>
```

I have two small examples here: [bus-bike-lane.zip](https://github.com/eclipse-sumo/sumo/files/14417233/bus-bike-lane.zip)

Is this a bug in netconvert, or can this perhaps be changed using a typemap file?

Thanks for your help!

**SUMO-version:** v1_19_0+0827-a4d069b0d4a

**operating system:** MacOS

**Comment by m-kro** [comment]
When I use the netconvert dev version I get a separate bike lane (which isn't there in the real example either) and a separate bus lane (with a separate tram edge on top).

**Comment by gladysmcgan** [comment]
According to the [OSM tagging guide](https://wiki.openstreetmap.org/wiki/Tag:cycleway%3Dopposite) `cycleway=opposite` and `oneway:bicycle=no`  indicate that there are no dedicated lanes for bicycles. 

In SUMO it is helpful if the tag is present to create an opposite bicycle lane nonetheless, so that bicycles can use the road in that direction. But if there is also an opposite lane for buses I think it works the best if bicycles and buses share one bus lane.

**Comment by m-kro** [comment]
@gladysmcgan Can you please check if it seems fine to you after todays's commit?

**Comment by gladysmcgan** [comment]
It's great, thank you! :)
