### ISSUE TITLE
lane markings are rendered on top of the junction bubble

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14417]
- was still working in 1.11
- since 1.12 the black (inverse) markings are drawn on top 
- in dev the white markings are drawn on top

easy to check with tests/sumo/net2.net.xml

**Comment by palvarezlopez** [comment]
Caused by glTranslated(geom[i].x(), geom[i].y(), 2.1); in GLHelper::drawInverseMarkings

**Comment by namdre** [comment]
I also noticed that directional arrows are affected. They always used to be on top of the junction bubble and are now hidden beneath (in dev)

**Comment by palvarezlopez** [comment]
Invalid reference
