### ISSUE TITLE
randomtrips.py with --fringe-junctions stops trips from "normal" fringe edges?

### ISSUE THREAD

**Issue by RIFJo** [eclipse-sumo/sumo#14411]
When using randomtrips.py with parameter --fringe-junctions, trips are no longer generated from/to "classic" fringe edges (entry/exit edges). I am not sure if this is intended behavior or not. I would like to be able to generate trips from both "classic" fringe edges and edges starting at "fringe junctions".

This is the test network. Top-Right corner is marked in netedit as "outer fringe", bottom left and bottom right edges are "classic" fringe edges
![grafik](https://github.com/eclipse-sumo/sumo/assets/55147726/63e7839b-8ff0-45f8-8fa5-33381ccc9199)

- Generating without "--fringe-junctions" correctly generates trips only to/from the entry/exit/entry edges
- **Generating trips with "--fringe-junctions" generates no trips from/to the bottom classic entry/exit edges**. I would expect the script to produce trips to/from both the fringe junction edges and the classic entry/exit edges

In both cases, the edge-weight output confirms the observation from the generated trips.trips.xml - its either the entry/exit edges that are assigned probability 100, or the edges from/to the top-right junction. Never both.

I know that i can manually change the probabilities of each individual edge, but is there a way to achieve this result automatically? For my real use-case with a larger network, manually editing these files is a lot of work that i would like to skip

*If possible, upload an example that shows your problem.*
Minimal net.xml file for reproduction (remove .txt suffix from file, GitHub won't let me upload .xml)
[fringe-test.net.xml.txt](https://github.com/eclipse-sumo/sumo/files/14403866/fringe-test.net.xml.txt)
Commands for comparison
```
python randomTrips.py -n fringe-test.net.xml --fringe-factor 20000 --weights-output-prefix probabilities -b 0 -e 100 -p1 --fringe-junctions
python randomTrips.py -n fringe-test.net.xml --fringe-factor 20000 --weights-output-prefix probabilities -b 0 -e 100 -p1

```
**SUMO-version:**
1.19

**operating system:**
Win11 x64

**Comment by namdre** [comment]
The goal behind option **--fringe-junctions** is to "Determine fringe edges based on junction attribute 'fringe'".  The intended use case is one where automatic fringe detection is unreliable and the user specifies the fringe instead.

 If you want to make use of this option and also want the classic edges to be counted as fringe, you have to mark the two bottom junctions as fringe. Using netconvert option **--fringe.guess** you can automatically set fringe edges based on topology which should cover those classic edges (and avoid the need for setting things manually).

PS: github allows uploading zip files.
