### ISSUE TITLE
Vissim Network to SUMO

### ISSUE THREAD

**Issue by SUMO2Unity** [eclipse-sumo/sumo#14413]
I am using netconvert to import vissim network to SUMO, however, it gives me this error:

Error: Index out of range in bracket operator of PositionVector
Quitting (on error).

[VissimNetwork.zip](https://github.com/eclipse-sumo/sumo/files/14406816/VissimNetwork.zip)

Any help really appreciate it,

**Comment by namdre** [comment]
the geometry of edge '111' seems to be broken (only one geometry point) but that's still no reason for netconvert to crash.
