### ISSUE TITLE
trip with fromLonLat finds no edges

### ISSUE THREAD

**Issue by rummel123** [eclipse-sumo/sumo#14429]
I try to use `fromLonLat` and `toLonLat` in a trip. The net is georeferenced (generated with osmWebWizard). The coordinates are within the given net. SUMO gives me the error:
```
Error: The route for trip 'trip_0' has no edges.
Quitting (on error).
```
What could be the problem?
[trip_with_fromLonLat.zip](https://github.com/eclipse-sumo/sumo/files/14434819/trip_with_fromLonLat.zip)

**Comment by namdre** [comment]
this is known behavior (#2182). In the meantime, use duarouter

**Comment by namdre** [comment]
sumo now supports these attributes in the latest development version.
