### ISSUE TITLE
Pedestrians ignore TLS at crossings at signalized junctions when using JuPedSim model

### ISSUE THREAD

**Issue by patmalcolm91** [eclipse-sumo/sumo#14424]
When using the JuPedSim model to simulate pedestrians at a junction with TLS control, the pedestrians ignore the current signal phase for their crossing.

I know that the JuPedSim integration is still relatively new and a work in progress, but I couldn't find any reference in the documentation or existing issues on whether this should currently already be working or if it has just yet to be implemented.

**Example scenario:** [intersection1a_test.zip](https://github.com/eclipse-sumo/sumo/files/14420963/intersection1a_test.zip)
![grafik](https://github.com/eclipse-sumo/sumo/assets/13092577/86e2a139-25d7-4b8d-a091-b720c7b018bb)

**SUMO-version:** 1.19.0+1037-fbe07f999a4

**operating system:** Windows 11

**Comment by bcoueraud87** [comment]
Discussions on how to implement interactions between JuPedSim pedestrians and SUMO LSA have just started with partners. For the moment nothing has been implemented and so the behavior that you are experiencing is normal.

**Comment by patmalcolm91** [comment]
Thanks for the quick response, @bcoueraud87! I look forward to testing the feature once it is implemented.
