### ISSUE TITLE
how we can find another results on  simuLTE (just like speed and time and CO2 emision of the cars )  

### ISSUE THREAD

**Issue by Y-AMDIAZ** [eclipse-sumo/sumo#14434]
Just when we use the veins, we can take a lot of KPIs, such as lostpacket, CO2 emissions, speed, BSM and WSM  and time. How can I find them in an LTE simulation?
<img width="842" alt="image" src="https://github.com/eclipse-sumo/sumo/assets/129278941/8443c527-38b8-41ba-9ee5-9a9edf19deec">

**Comment by m-kro** [comment]
This has nothing to do with SUMO. Please look at the [veins FAQ](https://veins.car2x.org/documentation/faq/) to find the help contact for veins / OMNeT++.
