### ISSUE TITLE
Problem simulating trips with vehicle ownership

### ISSUE THREAD

**Issue by buddih09** [eclipse-sumo/sumo#14432]
Hello, I generated a set of trips for simulation that follows the XML schema below.
The idea is to simulate a sequence of trips each person performs using their vehicle. I do not know if there is an easier way to represent vehicle ownership. This is important to me because, later, I want to include energy use, etc., in the simulation. 

But there is an issue with this XML. It did not issue any warning, but none of the trips were simulated. Do you have any suggestions for me to fix this problem? 

```
<?xml version="1.0" ?>
<routes>
	<vType id="car" accel="0.8" decel="4.5" sigma="0.5" length="5" maxSpeed="70" vClass="passenger"/>
	<vehicle id="v100072" type="car" depart="triggered" departPos="0"/>
	<vehicle id="v101470" type="car" depart="triggered" departPos="0"/>
	<vehicle id="v101474" type="car" depart="triggered" departPos="0"/>
	<person id="100072" depart="24300">
		<ride from="--2145#0" to="--1939#0" lines="v100072"/>
		<ride to="-2259#0" lines="v100072"/>
		<ride to="--2166" lines="v100072"/>
		<ride to="-699" lines="v100072"/>
		<ride to="-2226#3" lines="v100072"/>
		<ride to="-699" lines="v100072"/>
		<ride to="--2145#1" lines="v100072"/>
	</person>
	<person id="101470" depart="52200">
		<ride from="--1215#6" to="--837" lines="v101470"/>
		<ride to="--2229#0" lines="v101470"/>
	</person>
	<person id="101474" depart="27900">
		<ride from="--1054#0" to="--2387#1" lines="v101474"/>
	</person>
</routes>
```

**Comment by buddih09** [comment]
I copy the following summary also, if it is helpful. 

```
Simulation started with time: 0.00.
Simulation ended at time: 150000.00
Reason: The final simulation step has been reached.
Performance: 
 Duration: 21.58s
 Real time factor: 6951.52
 UPS: 0.000000
 UPS-Persons: 3467954.397998
Vehicles: 
 Inserted: 0
 Running: 0
 Waiting: 0
Persons: 
 Inserted: 659
 Running: 659
```

**Comment by m-kro** [comment]
The vehicles don't feature any route information. Even though their departure time is triggered by the person, the route itself is not derived from the person.

**Comment by buddih09** [comment]
Is it possible to make sumo figure of the route information based on the from-to information of each ride?

**Comment by namdre** [comment]
You may use `<personTrip from=... to=... modes="car"/>` which automatically create a car with the desired route

**Comment by namdre** [comment]
Yes and no. Car re-use is not supported by the automated intermodal routing of `<personTrip>`. However, you can define an explicit `<ride>`  home that uses the vehicle from earlier. In this case you have to define the vehicle as in your first input but it needs at least  a `<stop  edge="workEdge" triggered="person"/>` (this is where it will drop off the person and then wait for it to come back) and a `from` and `to` definition with the home address.

**Comment by buddih09** [comment]
@namdre Thanks a lot. I will try this way and let you know whether it worked. Btw to clarify, so: 

- I need to add a stop child element under the vehicle definition like this.
```
<vehicle id="v100072" type="car" depart="triggered" departPos="0" line="ev">
     <stop edge="-959#0" duration="12" parking="true" triggered="person" friendlyPos="true"/>
</vehicle>
```
- Then I have to define the rides likes this.
```
	<person id="100072" depart="24300">
		<ride from="--2145#0" to="--1939#0" lines="v100072"/>
		<ride to="-2259#0" lines="v100072"/>
		<ride to="--2166" lines="v100072"/>
	</person>
```
question: Vehicles also have a "line" attribute. So, when I create a ride, should i set the "lines" attribute to vehicle id or it's line attribute value?

**Comment by namdre** [comment]
>  I need to add a stop child element under the vehicle definition like this.

Yes. This stop both serves to deliver the person and also to keep the vehicle in the simulation until the return journey

>  question: Vehicles also have a "line" attribute. So, when I create a ride, should i set the "lines" attribute to vehicle id or it's line attribute value?

Lines is only needed for public transport (where the rider doesn't care about a particular vehicle). You can omit the line attribute for the vehicle and simply is it's id in the `lines` attribute of the ride.

**Comment by m-kro** [comment]
@buddih09 You forgot about the `from` and `to` attributes which would define a trip.

**Comment by namdre** [comment]
A `<trip>` a top level element just like `<vehicle>`. Its main use is to signify that the route of the vehicle must still be computed. You cannot use it as a child element. Please refer to https://github.com/eclipse-sumo/sumo/blob/b68d14c46b55dbfad1999fe4a0ea87f6db3a1f71/tests/sumo/basic/person/riding/ride_reuse_car/input_routes.rou.xml

**Comment by buddih09** [comment]
> A `<trip>` a top level element just like `<vehicle>`. Its main use is to signify that the route of the vehicle must still be computed. You cannot use it as a child element. Please refer to https://github.com/eclipse-sumo/sumo/blob/b68d14c46b55dbfad1999fe4a0ea87f6db3a1f71/tests/sumo/basic/person/riding/ride_reuse_car/input_routes.rou.xml

@namdre Thank you for the example. I tested what you proposed (an example of one trip below for reference). 
```
    <vType id="car" length="5.00" maxSpeed="70.00" vClass="passenger" accel="0.8" decel="4.5" sigma="0.5"/>
    <trip id="trip444003" depart="19200.00" from="--2338" to="-2338"/>
    <person id="444003" depart="19200.00">
        <ride from="--2338" to="-2016#3" lines="trip444003"/>
        <ride to="--2148" lines="trip444003"/>
        <ride to="-2338" lines="trip444003"/>
        <ride to="-2040#1" lines="trip444003"/>
        <stop edge="-2040#1" endPos="0.00" duration="2100.00"/>
        <ride to="-1323#0" lines="trip444003"/>
        <ride to="-2338" lines="trip444003"/>
        <stop edge="-2338" endPos="0.00" duration="480.00"/>
    </person>
```
My first observation is that in the tripinfo output, the stop period seems to be missing. I do not know for sure whether this is a reporting error or the stop condition did not execute at all. 

`<tripinfo id="trip444003" depart="19200.00" departLane="--2338_0" departPos="5.10" departSpeed="0.00" departDelay="0.00" arrival="19414.00" arrivalLane="-2338_0" arrivalPos="1674.76" arrivalSpeed="16.14" duration="214.00" routeLength="3411.84" waitingTime="0.00" waitingCount="0" stopTime="0.00" timeLoss="15.87" rerouteNo="1" devices="tripinfo_trip444003 routing_trip444003" vType="DEFAULT_VEHTYPE" speedFactor="1.05" vaporized=""/>`

The second observation is that the vType in the tripinfo output is not the same as the one that I declared. 
On a related note, in the example you showed, how can I define two or more vTypes and assign different trips to different vTypes? Could you please extend your test example for this case too? Thanks a lot.

**Comment by m-kro** [comment]
@buddih09 [Here](https://sumo.dlr.de/docs/Demand/Shortest_or_Optimal_Path_Routing.html#trip_definitions) you have the available attributes for trips. You can reference the vType using the `type` attribute.

**Comment by buddih09** [comment]
Thank you. Do you have any idea why the stop conditions are missing in the results? And also the reason for teleporting?
I get the same warning even after setting the type attribute for the trips.

**Comment by namdre** [comment]
My guess is that you are using a very old version of SUMO. There no warnings with any of the recent versions.

**Comment by m-kro** [comment]
@buddih09 In comparison to the test example, you miss the vehicle stop (as a child of the trip definition)...

**Comment by buddih09** [comment]
Sumo version: Version v1_19_0+0914-fcac56c5a2b

@m-kro Thank you for pointing it out. I fixed this mistake. Sumo did not accept `edge=...` as a stop attribute in the child element of the trip. Instead, I had to provide the lane information. This is different from the example @namdre shared.

**Comment by namdre** [comment]
SUMO accepts the 'edge' attribute within a stop since version 1.8.0 was released in 2020. The problem must be something more specific.

**Comment by buddih09** [comment]
I try to reproduce the issue with one of your test networks (net2.net). 
I think you are right about the edge attribute, but I cannot know for sure why it is not working. But the teleporting issue persists even with the test network. Have a look at the routes file below. 

```
<?xml version="1.0" ?>
<routes>
	<vType id="car" sigma="0.5" vClass="passenger"/>
	<trip id="trip107640" from="CE" to="WC" depart="triggered" type="car" departPos="0"/>
	<trip id="trip104631" from="CE" to="CE" depart="triggered" type="car" departPos="0">
		<stop edge="WC" parking="true" triggered="person"/>
	</trip>
	<trip id="trip100072" from="SC" to="NC" depart="triggered" type="car" departPos="0">
		<stop edge="WC" parking="true" triggered="person"/>
		<stop edge="NC" parking="true" triggered="person"/>
	</trip>
	<trip id="trip102035" from="NC" to="NC" depart="triggered" type="car" departPos="0">
		<stop edge="EC" parking="true" triggered="person"/>
	</trip>
	<trip id="trip107540" from="EC" to="EC" depart="triggered" type="car" departPos="0">
		<stop edge="WC" parking="true" triggered="person"/>
	</trip>
	
	<person id="107640" depart="0">
		<ride from="CE" to="WC" lines="trip107640"/>
	</person>
	<person id="104631" depart="25">
		<ride from="CE" to="EC" lines="trip104631"/>
		<ride to="EC" lines="trip104631"/>
		<ride to="WC" lines="trip104631"/>
		<stop edge="WC" duration="60" parking="true"/>
		<ride to="CE" lines="trip104631"/>
	</person>
	<person id="100072" depart="130">
		<ride from="SC" to="CN" lines="trip100072"/>
		<ride to="CN" lines="trip100072"/>
		<ride to="EC" lines="trip100072"/>
		<ride to="WC" lines="trip100072"/>
		<stop edge="WC" duration="120" parking="true"/>
		<ride to="NC" lines="trip100072"/>
		<stop edge="NC" duration="60" parking="true"/>
		<ride to="SC" lines="trip100072"/>
		<ride to="NC" lines="trip100072"/>
	</person>
	<person id="102035" depart="150">
		<ride from="NC" to="EC" lines="trip102035"/>
		<stop edge="EC" duration="100" parking="true"/>
		<ride to="SC" lines="trip102035"/>
		<ride to="CN" lines="trip102035"/>
		<ride to="NC" lines="trip102035"/>
	</person>
	<person id="107540" depart="180">
		<ride from="EC" to="WC" lines="trip107540"/>
		<stop edge="WC" duration="110" parking="true"/>
		<ride to="NC" lines="trip107540"/>
		<ride to="CW" lines="trip107540"/>
		<ride to="EC" lines="trip107540"/>
	</person>
</routes>
```
I run this and I get the following two teleports.
```
Warning: Teleporting person '102035' from vehicle destination edge 'NC' to intended destination edge 'SC' time=331.00
Warning: Teleporting person '107540' from vehicle destination edge 'EC' to intended destination edge 'NC' time=422.00
```
I think the reason is routing related. I perform duarouter on the trips above and get the following results.

```
    <vehicle id="trip102035" type="car" depart="triggered" departPos="0.00">
        <route edges="NC CE EC CN NC"/>
        <stop edge="EC" triggered="person" parking="1"/>
    </vehicle>
    <vehicle id="trip107540" type="car" depart="triggered" departPos="0.00">
        <route edges="EC CW WC CE EC"/>
        <stop edge="WC" triggered="person" parking="1"/>
    </vehicle>

    <person id="102035" depart="150.00">
        <ride from="NC" to="EC" lines="trip102035"/>
        <stop edge="EC" duration="100.00" parking="1"/>
        <ride to="SC" lines="trip102035"/>
        <ride to="CN" lines="trip102035"/>
        <ride to="NC" lines="trip102035"/>
    </person>
    <person id="107540" depart="180.00">
        <ride from="EC" to="WC" lines="trip107540"/>
        <stop edge="WC" duration="110.00" parking="1"/>
        <ride to="NC" lines="trip107540"/>
        <ride to="CW" lines="trip107540"/>
        <ride to="EC" lines="trip107540"/>
    </person>
```
Now we can spot that the routing plan and the set of rides do not match.

**Comment by namdre** [comment]
If you want person 102035 to have intermediate ride targets to SC and CN then you need to the vehicles stop on these edges to let the person get out (just as for the ride to EC)
