### ISSUE TITLE
how to disable lane change mode of a car in Sumo

### ISSUE THREAD

**Issue by harirRzi** [eclipse-sumo/sumo#14453]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

Hi. I have defined the following in .rou.xml file and I want to specify every car from the following flows which is inserted to Sumo, should should stay in the same lane that in the beginning was inserted and no cars are allowed to change lane. How can I say this? I know one solution is I can use traci.vehicle.setLaneChangeMode("carflowNormal_0", 0) but the problem is I am going to define a lots of cars and I don't know when each of the will be inserted.

```
<routes>
<vType id="Normal-car-0" vClass="passenger" length="5" accel="1.6" decel="0.5" sigma="0.5" minGap="1.5" maxSpeed="19" speedDev="0.1" color="255,3,30"/>

   <vType id="Normal-car-1" vClass="passenger" length="5" accel="1" decel="1.5" sigma="0.5" minGap="1" maxSpeed="16" speedDev="0.1"/>

<!—normal flow—>
<flow id="carflowNormal_0" type="Normal-car-0" beg="0" number="3" route="route_0" departLane="random" probability="0.5" />
   <flow id="carflowNormal_1" type="Normal-car-1" beg="3" number="2" route="route_0" departLane="random" probability="0.5" />
 </routes>
```

**Comment by m-kro** [comment]
AFAIK This is possible only with TraCI. You can still monitor the inserted cars by calling `traci.vehicle.getIDList` ([ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getIDList)) repeatedly and check for new entries matching the flow ID pattern.
