### ISSUE TITLE
Crash during closing of netedit while a TL is edited

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse-sumo/sumo#14451]
Caused because during closing netedit, all elements are removed first, and later all frames are destroyed. But when the TLSFrame is destroyed, the inspected junction doesn't exist.

**Comment by namdre** [comment]
is this a regression or a dev_regression?

**Comment by palvarezlopez** [comment]
Isn't a regression, is a design fail. (I put a throw ProcessError during the design without thinking in this case)

**Comment by namdre** [comment]
What I meant to ask is:  Was this problem introduced in dev or in an already released version?

**Comment by palvarezlopez** [comment]
In an already released version (probably in the version in which I implemented the new GNETLS Frame)

**Comment by namdre** [comment]
I tested older versions (1.17, 1.18, 1.19) and none of them crash. The dev version crashes reliably though.

**Comment by namdre** [comment]
The line you removed has been sitting there for over 6 years. I find it worrying that this is the solution without myself having a further understanding for the root cause of the crash.

**Comment by palvarezlopez** [comment]
> The line you removed has been sitting there for over 6 years. I find it worrying that this is the solution without myself having a further understanding for the root cause of the crash.

This line belongs to the old GNETLSFrame, the new doesn't need a call in the destructor
