### ISSUE TITLE
intersection creation

### ISSUE THREAD

**Issue by way-thu** [eclipse-sumo/sumo#14454]
I want to create an intersection just like following， when pedestrians want crossing the street， they firstly cross the “Crosswalk” on the right-turn vehicle lane, and the entering in the "Waiting corner", is there any example to create such an intersection?
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/7377d55d-9a5e-4283-8681-d083ea6876dd)

*If possible, upload an example that shows your problem.*

**SUMO-version:1.19

**operating system:windows

**Comment by way-thu** [comment]
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/712969d3-3e64-490e-9b76-00e3f8d40b3e)

**Comment by namdre** [comment]
you can download example files at https://sumo.dlr.de/extractTest.php?path=netconvert/function/crossings/specified/4_arm/separate_right_turn_island
