### ISSUE TITLE
Some questions about LC2013 and SL2015 lane-changing model

### ISSUE THREAD

**Issue by AntaiXie** [eclipse-sumo/sumo#14467]
Hello, I have read articles related to the three lane changing models of SUMO, and I have seen the relevant formulas of DK2008. However, for LC2013 and SL2015, I have only seen an introduction to the four lane changing motivations. What I want to know is, where can I learn about the relevant mathematical formulas of LC2013 and SL2015? I want to know how those lane changing model parameters, such as lcSpeedGain, specifically affect lane changing behavior.Looking forward to your reply.

**Comment by m-kro** [comment]
You can find the source code at `src/microsim/lcmodels`:

- [LC2013](https://github.com/eclipse-sumo/sumo/blob/main/src/microsim/lcmodels/MSLCM_LC2013.cpp)
- [SL2015](https://github.com/eclipse-sumo/sumo/blob/main/src/microsim/lcmodels/MSLCM_SL2015.cpp)

 There is no further explanation other than the mentioned publications. Hope you can find your way through the code and learn something from the code (comments).
