### ISSUE TITLE
invalid "save" dialog after loading additionals 

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14464]
if nothing is modified, the dialog shouldn't come up. Last working in 1.15.0

**Comment by palvarezlopez** [comment]
If I remember correctly, we activated this option for the case in which we load two different additional files from two differents sources (example: One file with detectors and another with busStops).

There is a middle solution, and is only enable the save dialog after loading additional, if previously there are at least one additional in the network. What do you mean?
