### ISSUE TITLE
Tools path wrong

### ISSUE THREAD

**Issue by AndiLeni** [eclipse-sumo/sumo#14469]
I think I found a bug using the randomTrips tool from inside netedit. Might as well apply to other tools too.
I receive this error message when I try to execute the randomTrips tool:

```
python "C:\Program Files (x86)\Eclipse\Sumo\"/tools/randomTrips.py --net-file "C:\Users\andil\Desktop\Masterarbeit Dateien\SUMO Simulationen\T-Kreuzung\T-Kreuzung.net.xml" --additional-files "C:\Users\andil\Desktop\Masterarbeit Dateien\SUMO Simulationen\T-Kreuzung\simulation.add.xml" --fringe-factor "max" --period "0.5" Prozess starten...
python: can't open file 'C:\\Program Files (x86)\\Eclipse\\Sumo"/tools/randomTrips.py --net-file C:\\Users\\andil\\Desktop\\Masterarbeit': [Errno 22] Invalid argument
Prozess abgeschlossen
```

I think this is caused by the weirs placement of the "" speech marks. 

While this throws an error:
`python "C:\Program Files (x86)\Eclipse\Sumo\"/tools/randomTrips.py`
this calls the script just fine:
`python "C:\Program Files (x86)\Eclipse\Sumo\/tools/randomTrips.py"`

May this be caused by the whitespaces in the path? Then installing SUMO in a folder with no whitespaces should solve this temporarily.

**SUMO-version:**
1.19.0

**operating system:**
windows 10

**Comment by namdre** [comment]
As far as I can tell, #14134 only fixed the backslash problem but not the bad quotation marks for paths with spaces.

**Comment by AndiLeni** [comment]
This seems to be correct. The other issue only deals with the backslashes
which is not a problem when running the tool. The double quotes are causing
the problem.

Jakob Erdmann ***@***.***> schrieb am Di., 5. März 2024,
22:34:

**Comment by namdre** [comment]
- I am able to replicate a path quoting problem with netdiff (involving whitespace) 
- randomTrips.py with whitespace path should work:
  - with 1.19.0 if the trailing backslack is removed from SUMO_HOME
  - with the dev version regardless of backslash

**Comment by AndiLeni** [comment]
@namdre Thanks for picking this issue up so quickly.
The current solution creates weirdly formatted paths in all constellations on my end.

Removing the trailing slash from the SUMO_HOME env variable works, but creates a command which can not be copied to cli.
F.e. I use the netedit gui to create randomTrips but I need to copy the resulting command to a "build" script for my project for later execution. 

When I remove the traling slash the command looks like this: `"C:\Program Files (x86)\Eclipse\Sumo"/tools/randomTrips.py` which is not formatted correctly for windows systems.
```
PowerShell 7.4.1
PS C:\Windows\System32> "C:\Program Files (x86)\Eclipse\Sumo"/tools/randomTrips.py
ParserError:
Line |
   1 |  "C:\Program Files (x86)\Eclipse\Sumo"/tools/randomTrips.py
     |                                        ~
     | You must provide a value expression following the '/' operator.
PS C:\Windows\System32>
```

Wouldn't it be easier to just eppend the quotes to the very end of the command?
F.e. like this in \sumo\src\netedit\tools\GNEPythonTool.cpp:

```c++
if (sumoHomeEnv != nullptr && sumoHomeEnv != std::string("")) {
        sumoHome = std::string(sumoHomeEnv);
        // harmonise slash
        if (sumoHome.back() == '\\') {
            sumoHome = sumoHome.substr(0, sumoHome.size() - 1);
        }
        // quote string to handle spaces but prevent double quotes
        if (sumoHome.front() != '"') {
            sumoHome = "\"" + sumoHome;
        }
        // REMOVE THIS PART, INSTEAD APPEND AT THE VERY END 
        // if (sumoHome.back() != '"') {
        //     sumoHome += "\"";
        // }
        sumoHome += "/";
    }
    // get command
    std::string command = python + " " + sumoHome + myToolPath + "\""; // ADD QUOTE HERE
```

This shouls encapsulate the complate command which sould work on all systems as far as I was able to test this quickly.

**Comment by m-kro** [comment]
@AndiLeni Curiously it works if only backlashes are used... at least for normal command line (cmd)

**Comment by AndiLeni** [comment]
@m-kro Yes, you are right, the classic cmd works. But since most of the windows 10 and all windows 11 systems use the terminal which uses powershell by default this issue might still be relevant in the future for anyone who encounters the same problem as me :)

**Comment by AndiLeni** [comment]
Thanks for the quick fix :)
