### ISSUE TITLE
Support for turn:bus:lanes Tag Interpretation

### ISSUE THREAD

**Issue by henrigrossmann** [eclipse-sumo/sumo#14476]
The top figure in https://wiki.openstreetmap.org/wiki/Key:turn:bus:lanes illustrates how to specify turning restrictions for certain lanes, where only specific lanes are allowed to make certain turns (for instance, in the provided example, only buses are permitted to go straight on the rightmost lane, while cars must turn right on that lane). As far as I'm aware, SUMO does not currently recognize these tags. Is there an easy workaround to implement such restrictions nevertheless?

Thank you for your help.

**Comment by m-kro** [comment]
As we do not read this OSM key at the moment, I assume the resulting network does not contain the straight connection for public transport. Then this information is lost. Obviously you could add it with a separate heuristic (discover the concerned junctions e.g. using sumolib, creating PlainXML patch files and running netconvert again) or add it manually in netedit, but I wouldn't classify any as an easy workaround. 

It doesn't sound too difficult to implement in the OSM import.

**Comment by namdre** [comment]
there are some complications after all  #14477 and #14478.

@henrigrossmann can you provide a location where neither of these issues apply so I can test the basic feature of `turn:bus:lanes` in isolation?

**Comment by namdre** [comment]
for the record, here is a first implementation draft that I don't wish to commit without a nice test: 
[diff.workOn14476.txt](https://github.com/eclipse-sumo/sumo/files/14523009/diff.workOn14476.txt)

**Comment by henrigrossmann** [comment]
That was a super quick implementation! Highly appreciated, Jakob! 

Here's an example of way 1240741141 which has dedicated bus turn lanes. [map.osm.zip](https://github.com/eclipse-sumo/sumo/files/14524227/map.osm.zip)
