### ISSUE TITLE
<chargingstations-output    records non zero   step_energyCharged   when the battery is full

### ISSUE THREAD

**Issue by theDivj** [eclipse-sumo/sumo#14473]
[MSDevice_Battery.cpp](https://github.com/eclipse-sumo/sumo/blob/main/src/microsim/devices/MSDevice_Battery.cpp)

MSDevice_Battery::notifyMove ~ line 242 onwards:
    correctly prevents the battery capacity from being set beyond maximum but then passes myEnergyCharged
to  addChargeValueForOutput  even though that charge was not actually added.
```
      // Calulate energy charged
      myEnergyCharged = myActChargingStation->getChargingPower(myTrackFuel) * myActChargingStation->getEfficency() * TS;

      // Update Battery charge
      if ((myEnergyCharged + getActualBatteryCapacity()) > getMaximumBatteryCapacity()) {
          setActualBatteryCapacity(getMaximumBatteryCapacity());
      } else {
          setActualBatteryCapacity(getActualBatteryCapacity() + myEnergyCharged);
      }
 }
// add charge value for output to myActChargingStation
myActChargingStation->addChargeValueForOutput(myEnergyCharged, this);
```

obviously a minor issue - chargingstations-output is only incorrect if a vehicle is stopped at a charging station after it is fully charged.

**Comment by m-kro** [comment]
Thanks!
