### ISSUE TITLE
some questions about IDM car-following model

### ISSUE THREAD

**Issue by AntaiXie** [eclipse-sumo/sumo#14479]
Hello, I defined the maximum deceleration of a car using the "traci. vehicle. setDecel" command, which uses IDM as the car-following model. May I ask if this maximum deceleration is the "b" of the following formula?
![df06e95600b14b46ba5f40a4aebc0665](https://github.com/eclipse-sumo/sumo/assets/117359479/6effbea6-4a94-45fd-ae13-8b37e9d947c1)

**Comment by m-kro** [comment]
Yes.
