### ISSUE TITLE
netconvert should not write a network on error

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#14470]
Currently an exception on writing will create an invalid network. All error checks should probably be done before writing. It seems to affect one check for non-negative speeds and one for the endOffset, see tests/netconvert/function/railway/bidi_endOffset_invalid

**Comment by namdre** [comment]
it might be easier to delete the network on error (code and performance wise)

**Comment by behrisch** [comment]
You are too fast ;-) I thought checking beforehand would be better because then the check would not need to be repeated for every output.

**Comment by behrisch** [comment]
No, they will simply write faulty networks ;-(
