### ISSUE TITLE
Question: creating an idle taxi / omitting routes

### ISSUE THREAD

**Issue by JulianCzymmeck** [eclipse-sumo/sumo#14485]
Hey Sumo team,
I'm trying to create idle vehicles with taxi devices, that wait at parking areas (taxi stands) until a custom makes a reservation. For that I'm using the `device.taxi.dispatch-algorithm traci` in combination with `device.taxi.idle-algorithm taxistand`.
As far as I know, I have to specify a route (or something similar) upon vehicle creation.

The problem that occurs is that after the taxi vehicle completes it's dispatch, it always returns to "complete" it's given route before getting rerouted into my defined taxi stands, which leads to a lot of undesired travel time.

My question is how I can create and manage my taxis, so that they (optimally) start idle in a parking area (taxi stand), then drive to complete the given taxi dispatch, and afterwards get immediately rerouted to the "best" taxi stand, without any influence of the given route upon vehicle creation.

Kind regards

**Comment by JulianCzymmeck** [comment]
I still haven't managed to find a solution to this problem. It would appreciate any kind of feedback regarding this issue.

**Comment by JulianCzymmeck** [comment]
It seems that the problem no longer exists on the latest version of sumo. My scenario works now. I'm sorry to have wasted time regarding this issue.

One small question regarding the creation of "idle" taxis: Is the best way to currently do this to start the route of the taxi as close to the desired taxi stand as possible, and have a rerouter on that edge, which reroutes to said taxi stand. Or is there a better way?

**Comment by namdre** [comment]
if you're adding the taxi with traci, then yes. For xml input you can also define a trip without from/to and a single stop at the parkingArea. Also, you don't need the rerouter. As soon as the taxi is identified as idle, the configured taxistand rerouter will kick in.
