### ISSUE TITLE
How to make the departure time of some cars to be earlier than flow of cars

### ISSUE THREAD

**Issue by harirRzi** [eclipse-sumo/sumo#14492]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

Hello. I am trying to add some abnormal behavior of cars among normal behavior cars. I want if there are some normal flow of cars so the abnormal cars should be among them, not at the end of simulation or in the beginning of simulation.I defined code like the following in routes.rou file. I want some of the cars with the id carflowNormal to depart after any of the vehicles that their id starts with 'd' (I mean the normal cars should be behind them). For doing so, I tried to make the 'beg' parameter of some of carflowNormal to be for example 400 and making the 'depart' parameter of the cars that their id starts with 'd' to be less than 400 to let them depart to the road earlier than some of normal flow .But now I see some of the cars that their id starts with 'd' are departing into the simulation after all the carflowNormal already departed. I appreciate if any one can help me to solve the problem.

```
 <flow id="carflowNormal_0" type="Normal-car-0" beg="0" number="3" route="route_0" departLane="random" probability="0.5" />
   <flow id="carflowNormal_1" type="Normal-car-1" beg="0" number="2" route="route_0" departLane="random" probability="0.5" />
   <flow id="carflowNormal_2" type="Normal-car-2" beg="0" number="4" route="route_0" departLane="random" probability="0.5" />
   <flow id="carflowNormal_4" type="Normal-car-4" beg="1" number="2" route="route_0" departLane="random" probability="0.5" />
   <flow id="carflowNormal_6" type="Normal-car-5" beg="3" number="3" route="route_0" departLane="random" probability="0.5"/>
   <flow id="carflowNormal_3" type="Normal-car-3" beg="10" number="4" route="route_0" departLane="random" probability="0.5" />
   <flow id="carflowNormal_5" type="Normal-car-5" beg="23" number="6" route="route_0" departLane="random" probability="0.5" />
   <flow id="carflowNormal_7" type="Normal-car-0" beg="27" number="5" route="route_0" departLane="random" probability="0.5" />
   <flow id="carflowNormal_8" type="Normal-car-1" beg="36" number="5" route="route_0" departLane="random" probability="0.5" />
   <flow id="carflowNormal_9" type="Normal-car-2" beg="75" number="6" route="route_0" departLane="random" probability="0.5" />

   <flow id="carflowNormal_10" type="Normal-car-2" beg="220" number="4" route="route_0" departLane="random" probability="0.5" />

   <flow id="carflowNormal_11" type="Normal-car-5" beg="400" number="7" route="route_0" departLane="random" probability="0.5" />

   <!--<flow id="carrevflow" type="car" beg="0" number="225"  route="route_1" departLane="random" probability="0.5" latAlignment="arbitrary"/>-->
   <vehicle id="d6" type="d_6" depart="3" route="route_0" number="1"  departPosLat="random"/>
   <vehicle id="d10" type="d_6" depart="3" route="route_0" number="1"  departPosLat="random"/>
   <vehicle id="d9" type="d_7" depart="7" route="route_0" number="1"  departPosLat="random" departLane="best"/>
   <vehicle id="d3" type="d_3" depart="9" route="route_0" number="1"  departPosLat="random" departLane="best"/>
   <vehicle id="d2" type="d_2" depart="10" route="route_0" number="1"  departPosLat="random" departLane="best"/>
   <vehicle id="d8" type="d_8" depart="15" route="route_0" number="1"  departPosLat="random" departLane="best"/>
   <vehicle id="d0" type="d_0" depart="18" route="route_0" number="1" departPosLat="random" departLane="best"/>
   <vehicle id="d5" type="d_5" depart="19" route="route_0" number="1"  departPosLat="random"/>
   <vehicle id="d12" type="d_5" depart="19" route="route_0" number="1"  departPosLat="random"/>
   <vehicle id="d7" type="d_7" depart="21" route="route_0" number="1"  departPosLat="random" departLane="best"/>
   
   <vehicle id="d4" type="d_4" depart="21" route="route_0" number="1"  departPosLat="random" departLane="best"/>
   <vehicle id="d11" type="d_4" depart="21" route="route_0" number="1"  departPosLat="random" departLane="best"/>
   <vehicle id="d1" type="d_1" depart="22" route="route_0" number="1"  departPosLat="random"/>
```

**Comment by namdre** [comment]
The vehicles in each input file must be sorted according to the begin and depart values. If you want to avoid mixing both groups you can put the two sorted groups into different files (`sumo --route-files file1,file2`)

**Comment by harirRzi** [comment]
Thank you for your r response. I want to mix them but I want in my
simulation the normal flows depart then those vehicles among some normal
flows depart and at the end only any remaining normal flows depart not
those cars that their ids start with ‘d’. How can I do that? Actually, I
defined all of those normal and abnormal in the same file. Should I also
define them in separate files?

**Comment by namdre** [comment]
if you want them in the same file, you have to write them sorted like this:
```
<flow id="carflowNormal_6" type="Normal-car-5" beg="3" ...
<vehicle id="d10" type="d_6" depart="3" ...
<vehicle id="d9" type="d_7" depart="7" 
<flow id="carflowNormal_3" type="Normal-car-3" beg="10"
<vehicle id="d8" type="d_8" depart="15"
```
if you put them in different files (and they are only sorted for each file), sumo will do the sorting between the files automatically). Your choice.

**Comment by harirRzi** [comment]
Thank you for your response, Now I defined like the following in routes.rou.xml file, but after running Sumo, I don't see any car from normal flows and I only see d cars. Could you please suggest me what should I do?

```
<flow id="carflowNormal_0" type="Normal-car-0" beg="0" number="3" route="route_0" departLane="random" probability="0.5" />

   <vehicle id="5001" type="d_6" depart="3" route="route_0" number="1"  departPosLat="random"/>

    <flow id="carflowNormal_1" type="Normal-car-5" beg="5" number="3" route="route_0" departLane="random" probability="0.5" />

   <vehicle id="5002" type="d_8" depart="7" route="route_0" number="1"  departPosLat="random"/>

   <flow id="carflowNormal_2" type="Normal-car-1" beg="8" number="3" route="route_0" departLane="random" probability="0.5" />

   <vehicle id="5003" type="d_7" depart="9" route="route_0" number="1"  departPosLat="random"/>
....
```

**Comment by namdre** [comment]
possibly too much traffic. check for insertion delays:
https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html#delayed_departure
https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html#investigating_insertion_delay

**Comment by harirRzi** [comment]
Thank you for your answer. Actually I see the following warning and I don't see the normal flow 1. I defined the 'beg' parameter for car normal flow to be more than the vehicle with the id="5001" but it doesn't show up. I appreciate your help.

`Warning: Route file should be sorted by departure time, ignoring 'carflowNormal_1'!`

 ```
  <flow id="carflowNormal_0" type="Normal-car-0" beg="0" number="3" route="route_0" departLane="random" probability="0.5" />

   <vehicle id="5001" type="d_6" depart="5" route="route_0" number="1"  departPosLat="random"/>

   <flow id="carflowNormal_1" type="Normal-car-5" beg="7" number="3" route="route_0" departLane="random" probability="0.5" />
```

**Comment by namdre** [comment]
I cannot see the problem without looking at the whole input file.

Am Do., 14. März 2024 um 17:40 Uhr schrieb hRzi ***@***.***>:
