### ISSUE TITLE
provide minimal topology access

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14490]
traci.edge.getFromJunction
traci.edge.getToJunction
traci.junction.getIncomingEdges
traci.junction.getOutgoingEdges

reason: project requirement where traci is used and 5s extra time for loading the network with sumolib should be avoided

**Comment by technomancerAdarsh** [comment]
@namdre hey i just too want the implementation of this two function urgently 
traci.junction.getIncomingEdges
traci.junction.getOutgoingEdges

so if you have any other way then please do let me know or lets connect and discuss

**Comment by namdre** [comment]
> @namdre hey i just too want the implementation of this two function urgently traci.junction.getIncomingEdges traci.junction.getOutgoingEdges
> 
> so if you have any other way then please do let me know or lets connect and discuss

see #15378
