### ISSUE TITLE
Actuated signal control

### ISSUE THREAD

**Issue by way-thu** [eclipse-sumo/sumo#14509]
When I change my traffic light from "static" to "actuated", one issue happens, phase 9 cannot set parameters "min" and "max", but the phase0,3,6 work well. 
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/020bfb5a-0218-474c-bd2b-e598f3c5b642)
When I run the simulation, the issue occurs like below:
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/78870608-d452-4f96-86c8-0267de500b1a)
How can I solve this problem?  

**SUMO-version:1.18

**operating system:windows

**Comment by way-thu** [comment]
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/4f81975d-49c1-4956-9017-aac0f8838954)
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/cf216e27-0651-483c-aa74-4a36ae0b278b)

**Comment by way-thu** [comment]
Although I add the "min" and "max" parameter in net.xml, the simulation problem still occurs
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/9deed737-b5ce-4f62-86fb-37ed7cefe037)

**Comment by way-thu** [comment]
I probably find where the problem is, the "g" in phase 9 should be "G".

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#detectors
