### ISSUE TITLE
Failure to Replicate Bus Connections

### ISSUE THREAD

**Issue by henrigrossmann** [eclipse-sumo/sumo#14507]
Somewhat related to #14476: 

Issue Description:
Netconvert fails to accurately implement bus only connections when two different lanes of the same edge target the same lane due to conflicting connections. Despite being achievable through netedit, netconvert does not replicate these conflicting connections.

Example:
Consider way ID 288968955 in the attached OSM file. In the backward direction, it features three turning lanes (turn:bus:lanes:backward = left|through|through;right). Consequently, the two rightmost lanes require a connection to go straight (one for cars, one for bus only). However, the target way has only one lane, resulting in netconvert creating only one lane for going straight, ignoring the second "through" in (turn:bus:lanes:backward = left|through|**through**;right). Additionally, no warning is issued when creating the net using netconvert, like for example "Warning: Cannot apply turn sign information for edge '-288968955#0' because the target edge '-288968953#2' has no suitable lanes"

Version:
v1_19_0+1227-3616da08d4d

[OSM.zip](https://github.com/eclipse-sumo/sumo/files/14591046/OSM.zip)

**Comment by henrigrossmann** [comment]
Just a small update: If a bicycle lane and a bus lane merge into a single car lanes it works perfectly fine. I attach an example where a bus (-13251973_1) and a bicycle lane (-13251973_0) merge into the same target lane (-1262633729_0).
[example.zip](https://github.com/eclipse-sumo/sumo/files/14665722/example.zip)

**Comment by namdre** [comment]
actually, there is a warning:
`Warning: Cannot apply turn sign information for edge '-288968955#0' because the target edge '-29151276#5' has no suitable lanes`
If one loads a typemap with
```
    <type id="highway.service"        numLanes="1" speed="5.56"  priority="1"  oneway="false" allow="delivery pedestrian bicycle passenger"/>
```
the the connection layout works fine (bus and passenger straight connections merge into a single lane)
