### ISSUE TITLE
Visibility distance in highway

### ISSUE THREAD

**Issue by MarMar-s** [eclipse-sumo/sumo#14505]
Hello,

I would like to reduce the visibility distance for drivers to react in highway curves where there are trees or mountains, but I couldn't find any related options in SUMO. Could you please guide me on how I can do this?
Furthermore, does the shape of the road in netdit affect visibility?

Thank you so much in advance for your response.

**Comment by namdre** [comment]
at the moment, sumo only considers visibility distance when approaching an intersection (the distance at which the driver can clearly see approaching cars on conflicting roads).
SUMO doesn't have a visibility model for car following on a road and for this reason, the geometry / curvature / obstacles don't have any effect.

What kind of behavior would you like to model?
- reckless drivers that ignore reduced visibility, fail to take into account slow leaders and therefore create dangerous situations
- careful drivers that drive slower at reduced visibility to compensate for potential unobserved leaders (regardless of actual leader vehicle presence)

**Comment by MarMar-s** [comment]
Thank you for your response. 
I want to model reckless drivers that ignore reduced visibility, fail to take into account slow leaders and therefore create dangerous situations. Could you please provide guidance on how I can model this behavior?

**Comment by namdre** [comment]
Using traci you can do the following:
- monitor vehicles that pass a zone with reduced visibility (i.e. traci.lane.getLastStepVehicleIDs(laneID)
- for each of these vehicles, retrieve their leader and it's distance with traci.vehicle.getLeader
- if the distance to the leader is above the visibility threshold, use traci.vehicle.setParameter("carFollowModel.ignoreIDs", foeID)
- once the vehicle has passed the low-visibility zone, restore interaction with traci.vehicle.setParameter("carFollowModel.ignoreIDs", "")
