### ISSUE TITLE
Finding the alternate route for a vehicle

### ISSUE THREAD

**Issue by Nitinyerra** [eclipse-sumo/sumo#14516]
I am trying to create a scenario with accident in one of the edge and then reroute the other vehicle to reach its destination through another path avoiding the edge with accident involved.
As a part of it I have tried
```
current_position_index = current_route.index(current_edge)
new_route = []
for edge in current_route[current_position_index:]:
	if edge != current_edge:
		new_route.append(edge)
if new_route == current_route or set(new_route).intersection(current_route):
	print("New route overlaps with the current route. Trying to find another route...")
	new_route = traci.simulation.findRoute(current_edge, current_route[-1]).edges
print(new_route)
traci.vehicle.setRoute("emergency_1", new_route)
```
where I have used newRoute traci but the route it is generating is always the same which is preconfigured one in my case

is there any way to get all the possible routes of a vehicle from source  to destination ?

you can refer some of the scenario screenshots

![image](https://github.com/eclipse-sumo/sumo/assets/140040498/6970e498-cab6-4c32-a540-d0b0a56de6a4)
![image](https://github.com/eclipse-sumo/sumo/assets/140040498/4e24fece-2fa5-49a6-8018-920764f174f4)

The XML file of rou.xml is 
![image](https://github.com/eclipse-sumo/sumo/assets/140040498/c5230e9b-4b7b-4f73-96ce-c1bd9d22a25e)

SUMO version 1.15.0

Windows 10 OS

**Comment by namdre** [comment]
Put a large time penalty on the disturbance edge using `traci.edge.adaptTraveltime` before calling findRoute.
If you need more alternatives, put a smaller time penalty on all the edges currently being used. The vehicle will then try to find a new way (but may still use old edges when there is no alternative).
