### ISSUE TITLE
exception for libtraci in java

### ISSUE THREAD

**Issue by lxqever** [eclipse-sumo/sumo#14510]
I am calling libtraci in java and now I have a problem. I cannot catch a broken link exception. What should I do?

**Comment by m-kro** [comment]
Can you please post more information? E.g. a stack trace or relevant parts of your script?

**Comment by lxqever** [comment]
> Can you please post more information? E.g. a stack trace or relevant parts of your script?

The libtraci exception was not thrown and I was unable to use the exception to process the business logic

**Comment by lxqever** [comment]
例如，链接断开，我捕获到异常后重新连接。现在的问题是异常没有抛出来

**Comment by lxqever** [comment]
For example, if the link breaks, I catch an exception and reconnect. The problem now is that the exception is not thrown

**Comment by lxqever** [comment]
resolved
