### ISSUE TITLE
Max vehicle speed exceeds expected value

### ISSUE THREAD

**Issue by Phims22** [eclipse-sumo/sumo#14511]
I have a vehicle with vType:

`<vType id="passenger" tau="1.065" length="4.509" accel="1.809" decel="1.497" emergencyDecel="5.048" speedFactor="0.89" vClass="passenger" carFollowModel="EIDM" lcKeepRight="0.100" lcOvertakeRight="0.500" minGap="1.0" speedDev="0" />`

As far as I understand, the max_Speed on a lane is calculated with:

`v_max=v_max_allowed*speedFactor`

with:

`actual_speed_Factor=speedFactor + 2 * speedDev`

Therefor the maximal Speed on a lane with `v_max_allowed=13.89` should be:

`v_max = v_max_allowed*actual_speed_Factor = v_max_allowed*(speedFactor + 2 * speedDev) = 13.89*(0.89+2*0)=12.3621`

Nevertheless, I can observe values slightly above (-->v_max=12.3851812477).

Are there other variables included in calculating the maximal speed for the EIDM or are there internal rounding errors occurring?

**Comment by m-kro** [comment]
I think this is due to the chosen car-following model. In my test case, the vehicle would exceed the speed limit even more when departing.

**Comment by Phims22** [comment]
Where I got concerned is that I can observe these higher speeds, as mentioned, but Traci will not let me insert a car on that lane with a higher start speed then `v_max = v_max_allowed*actual_speed_factor'. 

 Maybe there are some random values set by default for the EIDM?

Or maybe the EIDM allows higher speeds but taci doesn't?

**Comment by namdre** [comment]
@Domsall any Ideas?

**Comment by Domsall** [comment]
yes, that is expected behavior. The driving errors can cause higher speeds than calculated with v_max*speedfactor

**Comment by namdre** [comment]
Since version 1.15.0 we are distinguishing between `desiredMaxSpeed` (psychological limit) and `maxSpeed` (technical limit). I would expect that the first can be exceeded due to driving error but that the second value sets a hard limit.

**Comment by Domsall** [comment]
Yes, that should also hold for the EIDM
