### ISSUE TITLE
gtfs2pt.py raising KeyError:There is no item named 'routes.txt' in the archive

### ISSUE THREAD

**Issue by ramu13** [eclipse-sumo/sumo#14522]
Hello, I am a beginner with sumo.

I tried to import GTFS data by using the command below:
`% python $SUMO_HOME/tools/import/gtfs/gtfs2pt.py --network {my network file} --gtfs gtfs.zip --date {an existing day in the gtfs.zip} --osm-routes gtfs.ptlines.xml --modes bus --vtype-output pt_vtypes.xml`

Then I get this kind of messages:

> function import_gtfs called at Fri, 15 Mar 2024 23:18:44 +0000
Traceback (most recent call last):
  File "/opt/homebrew/opt/sumo/share/sumo/tools/import/gtfs/gtfs2pt.py", line 465, in <module>
    main(get_options())
  File "/opt/homebrew/opt/sumo/share/sumo/tools/import/gtfs/gtfs2pt.py", line 394, in main
    routes, trips_on_day, shapes, stops, stop_times = gtfs2osm.import_gtfs(options, gtfsZip)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/sumo/share/sumo/tools/sumolib/miscutils.py", line 48, in benchmark_wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/sumo/1.19.0/share/sumo/tools/import/gtfs/gtfs2osm.py", line 114, in import_gtfs
    routes = pd.read_csv(gtfsZip.open('routes.txt'), dtype=str)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usrname/.pyenv/versions/3.11.3/lib/python3.11/zipfile.py", line 1546, in open
    zinfo = self.getinfo(name)
            ^^^^^^^^^^^^^^^^^^
  File "/Users/usrname/.pyenv/versions/3.11.3/lib/python3.11/zipfile.py", line 1475, in getinfo
    raise KeyError(
KeyError: "There is no item named 'routes.txt' in the archive"

I unzipped the gtfs.zip and checked that there exists the routes.txt in the unzipped directory (as the other required txt files).
Is there any way to solve this problem?

**Comment by m-kro** [comment]
Are you sure the file path to the GTFS archive is correct?

**Comment by ramu13** [comment]
Yes, I have checked several times.

**Comment by m-kro** [comment]
Can you attach the GTFS here or provide a link to it?

**Comment by ramu13** [comment]
This is the original link:
https://openmobilitydata.org/p/opentransit/354/latest

And this is my downloaded zip:
[gtfs.zip](https://github.com/eclipse-sumo/sumo/files/14618501/gtfs.zip)

**Comment by m-kro** [comment]
I don't know why you get the message about missing route.txt, but the GTFS data you use does not include a calendar.txt our import script relies on (see [docs](https://sumo.dlr.de/docs/Tools/Import/GTFS.html#gtfs2ptpy)).

**Comment by m-kro** [comment]
Closing due to lack of feedback
