### ISSUE TITLE
getDistanceRoad

### ISSUE THREAD

**Issue by claudiacbh** [eclipse-sumo/sumo#14525]
Hello!

I appreciate if you could help me with the following question:

I am using the `traci.simulation.getDistanceRoad()` function to calculate the distance between the vehicle and the next bus stop. However, when the vehicle is at the bus stop, it returns a distance of 1.79769e+308 instead of a number close to 0.

I can verify that a bus is at a station because I use the function `traci.vehicle.isAtBusStop(vehID)` and through visual verification.

Why does the function return a very large number instead of a very small number when the bus is at the bus stop?

Here is the part of the code where I use the function:

```python
traci.simulation.getDistanceRoad(traci.vehicle.getRoadID(vehID), traci.vehicle.getLanePosition(vehID), stop_id_edgeID, traci.busstop.getStartPos(stop_id[0].stoppingPlaceID), isDriving=True)
```

SUMO-version:1.18.0

operating system: Windows 11

**Comment by namdre** [comment]
the value of busstop get StartPos is likely smaller than the value of vehicle.getLanePosition. Hence the vehicle would have to drive a loop to approach the stop edge from the start. If no such loop exists in the network, the large value indicates disconnectedness
