### ISSUE TITLE
Fixing headways between vehicles

### ISSUE THREAD

**Issue by kudurupaka-vamshi-krishna** [eclipse-sumo/sumo#14527]
In continuation with issue #14025 
I have planned to generate vehicles with the following headways:
   - Vehicle 1 follows Vehicle 0 with a 4-second headway.
   - Vehicle 2 follows Vehicle 1 with a 3-second headway.
   - Vehicle 3 follows Vehicle 2 with a 2-second headway.

Calculate Equilibrium Speed for Each Headway:
   - Given:
     - Minimum gap requirement (minGap) = 2.5 meters and length of vehicle: 5.0m
     - Desired time headway for each vehicle:
       - Vehicle 1:   4 seconds
       - Vehicle 2:   3 seconds
       - Vehicle 3:  2 seconds
 
Equiilibrium speed = (Vehicle Length +minGap)/ Desired headway.

vehicle 1:
Equiilibrium speed =  (5+2.5)/4 = 1.875 m/s

 vehicle 2:
Equiilibrium speed =  (5+2.5)/3 = 2.5 m/s

vehicle 3:
Equiilibrium speed =  (5+2.5)/2= 3.75 m/s

I am using the above values to run the model. However I got the following values, whenever the vehicles passed through the induction loop.
Vehicle ID: D0, Lane: E0_0, Speed: 13.103295870544388, Passage Time: ('D0', 5.0, 7.230966694531794, 7.612550080070678, 'V1')
Vehicle ID: D1, Lane: E0_0, Speed: 11.853984976092622, Passage Time: ('D1', 5.0, 10.821594685793004, -1.0, 'V2')
Vehicle ID: D1, Lane: E0_0, Speed: 12.141032884827153, Passage Time: ('D1', 5.0, 10.821594685793004, 11.237639261264242, 'V2')
Vehicle ID: D2, Lane: E0_0, Speed: 12.932567395444721, Passage Time: ('D2', 5.0, 13.990990394661232, -1.0, 'V3')
Vehicle ID: D2, Lane: E0_0, Speed: 13.036602642003208, Passage Time: ('D2', 5.0, 13.990990394661232, 14.374597800198014, 'V3')
Vehicle ID: D3, Lane: E0_0, Speed: 13.610011449887418, Passage Time: ('D3', 5.0, 16.163439624592947, 16.530816244253423, 'V4')

Please tell me where I am going wrong and the route file I used is.

```
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2023-10-27 01:52:36 by Eclipse SUMO netedit Version 1.16.0
-->

<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">

    <vType id="V1" sigma="0.5" length="5.0" tau="1.0" maxSpeed="25"/>
	<vType id="V2" sigma="0.5" length="5.0"  tau="1.0" maxSpeed="25"/>
    <vType id="V3" sigma="0.5" length="5.0"  tau="1.0" maxSpeed="25"/>
    <vType id="V4" sigma="0.5" length="5.0"  tau="1.0" maxSpeed="25"/>

    <route id="r_0" edges="E0 E1"/>
    <route id="r_1" edges="-E1 -E0"/>
	
	<!-- Vehicles -->
	<vehicle depart="0" id="D0" route="r_0" type="V1" />
	
    <!-- Vehicle 1 (4-sec headway) -->
	<vehicle depart="4" id="D1" route="r_0" type="V2"  departSpeed="1.875"/>

    <!-- Vehicle 2 (3-sec headway) -->
    <vehicle depart="8" id="D2" route="r_0" type="V3"  departSpeed="2.5"/>

    <!-- Vehicle 3 (2-sec headway) -->
    <vehicle depart="10" id="D3" route="r_0" type="V4"  departSpeed="3.75"/>
	
</routes>
```

**Comment by namdre** [comment]
- set speedDev=0 in the vType to prevent vehicles driving at different speeds
- set sigma=0 in the vType to prevent speed fluctuations that would interfere with the distances

- to observe fixed headways there are two possible strategies:
 - a) insert vehicle at the desired spacing and with the same speed and ensure that they drive at fixed speed (i.e with all having the same desired speed)
 - b) let the leader drive at a lower desired speed than the followers (so they catch up) and adjust the equilibrium headways by setting a distinct tau value for each follower.

**Comment by kudurupaka-vamshi-krishna** [comment]
According to your suggestion, I have changed the route file as follows. with these settings I am getting the desired headway 4-sec, 3-sec, 2-sec. But if I want the headway to be 4-sec, 2-sec, 1-sec. I am getting the previous headway i.e.,  4-sec, 3-sec, 2-sec when I debug it.

```
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">

    <vType id="V1" accel="2.6" decel="4.5" length="5.0" minGap="2.5" tau="1" sigma="0" speedDev="0" maxSpeed="20"/>
    <vType id="V2" accel="2.6" decel="4.5" length="5.0" minGap="2.5" tau="4" sigma="0" speedDev="0" maxSpeed="20"/>
    <vType id="V3" accel="2.6" decel="4.5" length="5.0" minGap="0.5" tau="3" sigma="0" speedDev="0" maxSpeed="20"/>
    <vType id="V4" accel="2.6" decel="4.5" length="5.0" minGap="0" tau="1.6" sigma="0" speedDev="0" maxSpeed="20"/>

    <route id="r_0" edges="E0 E1"/>
    <route id="r_1" edges="-E1 -E0"/>
	
     <!-- Vehicles -->
     <vehicle depart="0" id="D0" route="r_0" type="V1" />
	
    <!-- Vehicle 1 (4-sec headway) -->
	<vehicle depart="4" id="D1" route="r_0" type="V2"/>

    <!-- Vehicle 2 (3-sec headway) -->
    <vehicle depart="7" id="D2" route="r_0" type="V3" />

    <!-- Vehicle 3 (2-sec headway) -->
    <vehicle depart="9" id="D3" route="r_0" type="V4"/>
	
</routes>
```

**Comment by namdre** [comment]
what is your input for the 4,3,2 headways?

**Comment by kudurupaka-vamshi-krishna** [comment]
`<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">

    <vType id="V1" accel="2.6" decel="4.5" length="5.0" minGap="2.5" tau="1" sigma="0" speedDev="0" maxSpeed="20"/>
	<vType id="V2" accel="2.6" decel="4.5" length="5.0" minGap="2.5" tau="4" sigma="0" speedDev="0" maxSpeed="20"/>
    <vType id="V3" accel="2.6" decel="4.5" length="5.0" minGap="0" tau="2" sigma="0" speedDev="0" maxSpeed="20"/>
    <vType id="V4" accel="2.6" decel="4.5" length="5.0" minGap="0" tau="1" sigma="0" speedDev="0" maxSpeed="20"/>

    <route id="r_0" edges="E0 E1"/>
    <route id="r_1" edges="-E1 -E0"/>
     
	<vehicle depart="0" id="D0" route="r_0" type="V1" />
	
    
	<vehicle depart="4" id="D1" route="r_0" type="V2"/>

    
    <vehicle depart="6" id="D2" route="r_0" type="V3" />

    
    <vehicle depart="7" id="D3" route="r_0" type="V4"/>
	
	
	
	
	
	
</routes>
`

The output that I am getting is:
Vehicle ID: D0, Lane: E0_0, Speed: 7.800000000000001, Passage Time: ('D0', 5.0, 3.269230769230769, 3.9102564102564106, 'V1')
Vehicle ID: D1, Lane: E0_0, Speed: 7.800000000000001, Passage Time: ('D1', 5.0, 7.269230769230769, 7.910256410256411, 'V2')
Vehicle ID: D2, Lane: E0_0, Speed: 6.9495000000000005, Passage Time: ('D2', 5.0, 9.546945823440536, -1.0, 'V3')
Vehicle ID: D2, Lane: E0_0, Speed: 9.5495, Passage Time: ('D2', 5.0, 9.546945823440536, 10.1938844965705, 'V3')
Vehicle ID: D3, Lane: E0_0, Speed: 6.297999999999998, Passage Time: ('D3', 5.0, 11.81041600508098, -1.0, 'V4')
Vehicle ID: D3, Lane: E0_0, Speed: 8.897999999999998, Passage Time: ('D3', 5.0, 11.81041600508098, 12.427736570015734, 'V4')
Data saved to CSV files for each lane and induction loop.

**Comment by kudurupaka-vamshi-krishna** [comment]
Do I need to consider depart speed also for maintaining specific headway?

**Comment by namdre** [comment]
1. yes, you need to use a higher departSpeed to be able to simulation 1s headways in this scenario. Otherwise vehicle D2 hasn't cleared the way for timely insertion of D3 (setting departSpeed="max" in all vehicles is sufficient)
2. the tau value in the vType is the headway between leader back and follower front (so it must be set to a lower value than the front-to-front headways you want to simulate). Setting tau values of 3, 1.5 and 0.5 is enough to make the other values come out as desired
