### ISSUE TITLE
meso induction loop not accessible via traci

### ISSUE THREAD

**Issue by aminissn** [eclipse-sumo/sumo#14529]
In SUMO 1.19.0 when I try to get values of induction loops using traci, I get an error saying the detector doesn't exist, even though I get the IDs from traci itself:

```
traci.start(sumoCmd)
dets = traci.inductionloop.getIDList()
for det in dets:
    print(traci.inductionloop.getLastStepVehicleIDs(det))
```
--> Error: Answered with error to command 0xa0: Induction loop 'e1_0' is not known

**Comment by namdre** [comment]
please provide a minimal input example as I seem unable to replicate it.

**Comment by aminissn** [comment]
here is a small example, I created the detectors in netedit, but after the error tried to modify the xml file and change the "inductionloop" tag to "e1Detector" but still failed. 
and my script:
sumoCmd = ['sumo', '-c', 'sumo.sumocfg']
traci.start(sumoCmd)
dets = traci.inductionloop.getIDList()
print(dets)
for step in range(3):
    print("step", step)
    traci.simulationStep()
print("inductionloops", traci.inductionloop.getIDList())
print("inductionloop count", traci.inductionloop.getIDCount())
loopID = dets[0]
print("examining", loopID)
print("vehNum", traci.inductionloop.getLastStepVehicleNumber(loopID))
print("meanSpeed", traci.inductionloop.getLastStepMeanSpeed(loopID))
print("vehIDs", traci.inductionloop.getLastStepVehicleIDs(loopID))
print("occupancy", traci.inductionloop.getLastStepOccupancy(loopID))
print("meanLength", traci.inductionloop.getLastStepMeanLength(loopID))
print("timeSinceDet", traci.inductionloop.getTimeSinceDetection(loopID))
print("vehData", traci.inductionloop.getVehicleData(loopID))
print("position", traci.inductionloop.getPosition(loopID))
print("laneID", traci.inductionloop.getLaneID(loopID))
traci.close()
[Archive.zip](https://github.com/eclipse-sumo/sumo/files/14633021/Archive.zip)

**Comment by namdre** [comment]
the inductionloop works differently in meso since vehicle movements are different as well. What kind of data were you intending to retrieve?

**Comment by aminissn** [comment]
I am actually trying to create a perimeter control scheme and need to measure the traffic inflow into a region of my network. I thought I could use loops instead of lane/edge output

**Comment by aminissn** [comment]
but only after this bug is resolved, I assume, right? because now it is not possible to access individual loops with their IDs for any of the traci functions

**Comment by namdre** [comment]
correct.

**Comment by namdre** [comment]
see #7492

**Comment by namdre** [comment]
in the latest dev version you can now retrieve occupancy, meanSpeed and vehicleNumber  for the current interval
