### ISSUE TITLE
Evenly (or close to it) distribute routes through 3 specific edges

### ISSUE THREAD

**Issue by corinnegroth** [eclipse-sumo/sumo#14537]
I am trying to use randomTrips.py to generate routes for vehicles. I have noticed that most routes go through one edge (greater than 50%). The attached snapshot shows which edge is the preferred edge.
![Screenshot 2024-03-18 133814](https://github.com/eclipse-sumo/sumo/assets/59060490/dcc1b8b9-de3d-4812-9f7d-30b9c939e0d9)

I would like to use randomTrips.py to generate routes for vehicles that go through these edges as evenly distributed as possible.
![Screenshot 2024-03-18 134926](https://github.com/eclipse-sumo/sumo/assets/59060490/a5c0fa2d-1db6-483b-a1c9-19aa8a390b0b)

I have tried adjusting the weights of these edges in my weights.via.xml file, but that does not seem to help. Is there any argument I could use to accomplish this?

SUMO 1.19.0

Windows

**Comment by namdre** [comment]
potential solutions:

a) set option --random-factor 2  (this assumes many of your trip start at the very left and go to the very right. In this case the choice of intermediate edge is determined by shortest path routing which would introduce the observed bias, the given option disturbs the routing to give you more paths)

b) set option --intermediate 1. This forces trips to pass one random intermediate edge. (by default, the weights.via.xml file doesn't take effect)

**Comment by corinnegroth** [comment]
Thank you!

Neither of those worked. Is there a way to "turn off" shortest path routing using any of the available randomTrips.py arguments?

**Comment by namdre** [comment]
setting a high enough random-factor will essentially pick random paths through the network. There might be some other factor about your setup I'm failing to comprehend. Can you attach your input network and post the exact argument string you are using with randomTrips?

**Comment by corinnegroth** [comment]
Yes!
python randomTrips.py -n base_model_network2.net.xml --weights-prefix base_model_weights --random --random-depart --intermediate 1 --insertion-rate="100" -b 0 -e 86400 --route-file base_model_routes.rou.xml

[base_model_network2.net.zip](https://github.com/eclipse-sumo/sumo/files/14728657/base_model_network2.net.zip)

**Comment by namdre** [comment]
- use this as your via weights:

```
<edgedata>
    <interval begin="0" end="86400">
	<edge id="LEP1_IN" value="0.033"/>
	<edge id="LEP2_IN" value="0.033"/>
	<edge id="LEP3_IN" value="0.033"/>
    </interval>
</edgedata>
```
- set option --random-routing-factor 10 (this is the option that puts noise on the shortest path routing, whereas option --random-factor disturbs the weights for picking origing, destination and via edges)
- if you don't yet like the random outcome, also set option  --duarouter-seed 44  

Note, that you can quickly check for even distribution with the following commands:
```
sumo/tools/countEdgeUsage.py -i -o usage.xml base_model_routes.rou.xml
sumo-gui -n base_model_network2.net.xml --edgedata-files usage.xml
```
in the gui, color by edge weights attribute 'intermediate',  press recalibrate rainbow and 'show edge color value'

![Screenshot from 2024-03-23 11-05-41](https://github.com/eclipse-sumo/sumo/assets/6240630/0437078d-21d7-41aa-918a-ddc5edb1a73f)
![Screenshot from 2024-03-23 11-05-28](https://github.com/eclipse-sumo/sumo/assets/6240630/3b5a1b33-5720-4036-b2e4-af3b4bb9c253)

**Comment by corinnegroth** [comment]
Thank you so much! The first suggestion worked!
