### ISSUE TITLE
Flows along route distributions in netedit

### ISSUE THREAD

**Issue by dmariaa** [eclipse-sumo/sumo#14536]
Netedit doesn't seem to support using a route distribution id in the "route" field. The editor shows the route distribution id in red color (error in value) and doesn't let to save it. It can be modified in the XML file and used in sumo and it works quite well. When I try to load the network and route files, I get an error...

"Error: Invalid route 'rd_0' used in flow 'f_0'.
Error: Loading of network3.rou.xml failed." 

...and the route file is not loaded.

![Captura de pantalla 2024-03-18 191858](https://github.com/eclipse-sumo/sumo/assets/5584976/fce355b7-e2de-48aa-acbc-492cb1696a25)

![Captura de pantalla 2024-03-18 192517](https://github.com/eclipse-sumo/sumo/assets/5584976/099843de-1bda-4375-8b01-3b83fe5292be)

**SUMO version: 1.19.0**

**OS: Windows**

**Comment by namdre** [comment]
Unfortunately, yes. This is a known issue (#14137)

**Comment by Troy312** [comment]
Same problem here. Seems like netedit only receives routes with exclusive id. But routes under different routeDistribution can have the same id.

**Comment by namdre** [comment]
Thanks. I'm adding this to the main ticket.
