### ISSUE TITLE
[Question] Does speedmode still work after using exeuteMove?

### ISSUE THREAD

**Issue by yougeyxt** [eclipse-sumo/sumo#14548]
I am using `traci.simulation.executeMove()` and then use `traci.vehicle.movetoXY` to update the vehicle state. I am using speedmode = 31 (all checks on by `traci.vehicle.setSpeedMode`) for all vehicles but I notice the vehicle will run red light. So I am wondering if speedmode still works after using `traci.simulation.executeMove()`.

**Comment by namdre** [comment]
speedMode  only applies to setSpeed and slowDown bit is completely ignored by moveToXY
