### ISSUE TITLE
[Question] outflow limit

### ISSUE THREAD

**Issue by MarMar-s** [eclipse-sumo/sumo#14541]
Hello,

I would like to impose an outflow limit (e.g., N vehicles per hour) on the final edge of my network to simulate congestion upstream. However, I could not find any option to implement this. Alternatively, using traffic light to simulate congestion results in non-continuous movements. I'd greatly appreciate any guidance you could provide on this matter.

Thank you in advance for your help.

**Comment by m-kro** [comment]
Traffic lights are a viable option. Less direct options could be a low speed limit or [stops](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#stops_and_waypoints).

**Comment by namdre** [comment]
see here for the effect of lower speeds on capacity: https://sumo.dlr.de/docs/Simulation/RoadCapacity.html
