### ISSUE TITLE
re-order stop-output attributes by importance. The stopping place id shouldn't be last

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14542]
advantage: the (most often) relevant info can bee seen without horizontal scrolling or line wrapping)

disadvantage: potentially breaks every user script that uses parse_fast on stop-output 
this only seems to affect ptlines2flows on our side

**Comment by namdre** [comment]
xml attribute order is generally not to be relied on... (Mirko)

**Comment by namdre** [comment]
@behrisch your comments?

**Comment by behrisch** [comment]
Go ahead. I would not agree in general because apparently parse_fast relies on the order but stop-output does not seem so important to me. (I would not agree if we reorder fcd-output attributes for instance).
