### ISSUE TITLE
[Question] What is the key of the `traci.junction.getContextSubscriptionResults`?

### ISSUE THREAD

**Issue by govin08** [eclipse-sumo/sumo#14540]
I'm reading the [Interfacing TraCI from Python](https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html).

Here is a code block in that website ;

```
scResults = traci.junction.getContextSubscriptionResults(junctionID)
halting = 0
if scResults:
    relSpeeds = [d[tc.VAR_SPEED] / d[tc.VAR_ALLOWED_SPEED] for d in scResults.values()]
```

I printed out the `scResults` and got a dictionary

{'3401.0': {64: 5.2, 68: 7.1, 183: 11.521069999999998}, '3410.0': {64: 10.235643, 68: 5.0, 183: 10.235643}, '3410.1': {64: 2.6, 68: 5.0, 183: 12.748724999999999}, '3414.0': {64: 10.094546, 68: 5.0, 183: 10.094546}, '3414.1': {64: 10.21009, 68: 5.0, 183: 10.21009}, '3414.2': {64: 10.435623, 68: 5.0, 183: 10.435623}, '3414.3': {64: 10.600050999999999, 68: 5.0, 183: 10.600050999999999}, '3414.4': {64: 2.6, 68: 5.0, 183: 10.724483}, '3414.5': {64: 0.0, 68: 5.0, 183: 9.837905}, '3414.6': {64: 0.0, 68: 5.0, 183: 12.76539}, '3415.0': {64: 12.213223, 68: 5.0, 183: 12.213223}, '3418.0': {64: 10.948905, 68: 5.0, 183: 10.948905}, '3422.0': {64: 10.4, 68: 5.0, 183: 11.3322}, '3422.1': {64: 0.0, 68: 5.0, 183: 10.281194}}

I understand the values : they are dictionaries themselves where 64 is `traci.constants.VAR_SPEED`, 68 is `traci.constants.VAR_LENGTH` and so on. But what dos the keys like '3401.0', '3410.0' and '3410.1' mean?

**Comment by govin08** [comment]
They are vehicle ids.

**Comment by namdre** [comment]
You already figured it out but I'm putting it here for future reference: They are vehicle IDs.
