### ISSUE TITLE
pedestrian speed

### ISSUE THREAD

**Issue by way-thu** [eclipse-sumo/sumo#14553]
I defined a personflow with speed 1.2m/s, however, during the simulation, the speed of some person is lower than 1.2 even though I set the speedDev as 0. Why this happens and how can I make each person's speed is 1.2m/s when they are walking.
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/50359cd6-b5f5-46ee-a10d-aa06ee506c1c)
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/157efb68-f470-4232-9817-a87f9c3aa04e)

![image](https://github.com/eclipse-sumo/sumo/assets/113359869/96d709c2-6e3f-480b-878a-a8730983efd3)

*If possible, upload an example that shows your problem.*

**SUMO-version:1.18.0

**operating system:win 10

**Comment by namdre** [comment]
set option **--pedestrian.striping.dawdling 0**
