### ISSUE TITLE
Question - Meso lane queue mode

### ISSUE THREAD

**Issue by xingminw** [eclipse-sumo/sumo#14551]
This might be related to issue #14443

I am wondering how meso handles `<meso-lane-queue value="true"/>`. If this is turned on, is each lane considered to be a single queue or still the whole edge a queue?

The other reason I am asking this is that in meso mode, traci cannot get the lane info of the vehicle no matter whether the lane queue mode is turned on or not.

**Comment by namdre** [comment]
1. if the option is turned on each lane is a queue (though possibly split into multiple segments longitudinally) 
2. this is currently the expected behavior (generally, the lane is not known in meso and there is no special case built in for the API / outputs when using meso-lane-queue mode)
