### ISSUE TITLE
netconvert: bike lane default width not applied to lanes in both directions

### ISSUE THREAD

**Issue by gladysmcgan** [eclipse-sumo/sumo#14560]
When I use the option `osm.bike-access` in netconvert together with the option `default.bikelane-width`, my set default is only applied to one side of the two-way edge.

For example here, the left cycle lane has the SUMO default of width 1 and the right cycle lane has my set default of 2.

<img width="516" alt="Screenshot 2024-03-20 at 14 55 04" src="https://github.com/eclipse-sumo/sumo/assets/59922884/8331849c-0dc4-443c-9580-a8723f119f39">

Thanks for your help! Suggestions on other ways to set a default are also appreciated :)

**SUMO-version:** v1_19_0+1405-a2afc8b27d6

**operating system:** MacOS

example net here:
[bike-lane-default.zip](https://github.com/eclipse-sumo/sumo/files/14667525/bike-lane-default.zip)

**Comment by m-kro** [comment]
Should be fine by now. Please get a fresh SUMO dev version (precompiled binaries of tomorrow).

**Comment by gladysmcgan** [comment]
Super, thanks! :)
