### ISSUE TITLE
Which SUMO CACC controller used by Plexe? 

### ISSUE THREAD

**Issue by mateen-malik** [eclipse-sumo/sumo#14569]
Hi,

I have a few questions about the CACC controller used by the platooning vehicles in the Plexe simulations version 2.1. These are as follows;

1a: Do the vehicles have the 'collision avoidance function' while driving in a platoon (i.e., when the CACC controller is active)? If the front vehicle gets too close to the following vehicles will the vehicle perform any safety maneuvers?

1b: Are there any active local sensors in the platooning vehicles?

2a: Does the Plexe use the same CACC controller described on the SUMO webpage (https://sumo.dlr.de/docs/Car-Following-Models/CACC.html)?

2b: Does the CACC controller that Plexe uses, reside in Plexe or SUMO simulator?

3: Are there any specific references where I can find exactly how Plexe's CACC controller is modeled and its properties? I have been trying to find the documentation of how that controller is built and what safety properties it might have. Unfortunately, I have not been successful in finding the precise document explaining the CACC controller that Plexe uses.

I am looking forward to hearing from you.
I really appreciate any help you can provide.

**Comment by mateen-malik** [comment]
@michele-segata Hi could you please also respond to my above queries in this thread? Thanks in advance!

**Comment by michele-segata** [comment]
1a: No. The control algorithm is regulating the acceleration depending on the inputs received. If some input is missing (e.g., loss of packets) then vehicles can collide, but this was done on purpose to study the impact of communication failures.
1b: The model assumes a radar to be present, but the radar is simply implemented by asking SUMO distance and relative speed to the front vehicle
3: Yes, there is a lot of documentation on that. This has been documented in the original [Plexe paper](https://disi.unitn.it/~msegata/bibfiles/segata2014plexe.pdf) (see equations 7-12 for the control law plus equations 1-2 for the engine lag). The [Plexe website](http://plexe.car2x.org/features/) also list the publications developing the CACC algorithms that you find in Plexe. The default one is reference number 2.

**Comment by mateen-malik** [comment]
Thanks a lot Michele, i really appreciate your help. Wishing you the best! by /Mateen
