### ISSUE TITLE
Is there a way to convert net.xml to shp file?

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14567]
Add your issue description here.

Hi, given the good simulation performance of SUMO, I am considering integrating the traffic flow generated by SUMO into a visualization platform. However, vehicles need to run on road network files that SUMO can read. 
Therefore, I would like to ask if there is a way to convert the road network files in SUMO to SHP files? Thank you!

SUMO-version:
SUMO1.19.0

operating system:
Windows10

**Comment by m-kro** [comment]
Maybe by creating a vector screenshot (svg) and processing this further in other software (e.g. Inkscape, QGIS)? If you use the "extra" release, you have the option to save screenshots in vector formats. Unfortunately on Windows there can be some artefacts in the vector screenshot file.

**Comment by namdre** [comment]
you can get geojson with tools/net/net2geojson.py  
QGIS should be able to load this and save as shapefile

**Comment by nudtdyk** [comment]
Thank you for your guidance on the methods. However, when I run it, it encounters breakpoint situations. How can I fix this or are there any other options to add corresponding points? The specific visual effect is as shown below:
![0b062ba9be4c98693f7ed85cdc5dd76](https://github.com/eclipse-sumo/sumo/assets/120693511/28cedd51-84a0-419f-b5d9-b66fb44edc70)

**Comment by namdre** [comment]
set net2geojson option --internal to avoid the gaps

**Comment by nudtdyk** [comment]
> set net2geojson option --internal to avoid the gaps

Thanks so much!

**Comment by dominique-AR** [comment]
thanks
