### ISSUE TITLE
template generation is unreliable with clang debug build

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#14576]
- [ ] The call to sumoD segfaults but unfortunately non-deterministic
- [ ] Since c5ca9040237175e9afa02e15053fb736745f3c11 there seems to be an issue with the bitset triggering the undefined behavior sanitizer

```
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bitset:657:46: runtime error: left shift of 18446744073709551615 by 32 places cannot be represented in type 'std::_Sanitize::_WordT' (aka 'unsigned long')
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bitset:657:46 in 
```

**Comment by namdre** [comment]
Are you sure that the ubsan warning is wrong? We might be misusing the bitset (though I don't see how).

**Comment by behrisch** [comment]
No, I'm not sure, I just filtered it to have a more reliable build

**Comment by behrisch** [comment]
The check is really oversensitive, so disabling it was the right choice https://stackoverflow.com/questions/78209914/why-is-bitsetset-triggering-undefined-behavior?noredirect=1#comment137881685_78209914. After disabling it I could also not reproduce the segfault any longer.
