### ISSUE TITLE
libsumo & traci, disable output

### ISSUE THREAD

**Issue by AndiLeni** [eclipse-sumo/sumo#14572]
I'd like to disable all output when using traci and libsumo.
I tried adding  `--no-step-log` to the cmd attribute, adding `<report><no-step-log value="true"/></report>` to the sumocfg file and trying `verbose=False`.
None of them seem to work as I would expect.

I found a workaround by setting stdout=open("sumo_stdout.txt") which worked for traci but unfortunately not for libsumo.

Are there any other options I may try?

Thanks and kind regards

**SUMO-version:**
1.19.0

**operating system:**
Windows 10

**Comment by behrisch** [comment]
Can you give an example on the messages you would like to hide? Did you try `--no-warnings`?

**Comment by AndiLeni** [comment]
I'd like to hide these kind of messages:

Loading net-file from './Stern/stern.net.xml' ... done (4ms).
Loading additional-files from './Stern/stern.add.xml' ... done (8ms).
Loading done.
Simulation version 1.19.0 started via libsumo with time: 0.00.
Simulation ended at time: 3600.00
Reason: Libsumo requested termination.
Performance:
 Duration: 2.26s
 Real time factor: 1595.74
 UPS: 46052.748227
Vehicles:
 Inserted: 1369 (Loaded: 1514)
 Running: 42
 Waiting: 131
Statistics (avg of 1327):
 RouteLength: 247.59
 Speed: 4.96
 Duration: 75.71
 WaitingTime: 21.71
 TimeLoss: 56.74
 DepartDelay: 103.36

Did you try --no-warnings?

No, I did not consider these messages to be warnings.

Am Fr., 22. März 2024 um 21:54 Uhr schrieb Michael Behrisch <
***@***.***>:

**Comment by behrisch** [comment]
Please try adding `--verbose false` and `--no-duration-log` to your start command (or alternatively to your sumocfg)

**Comment by AndiLeni** [comment]
Thanks, 

these settings in my sumocfg seem to work:

```
<report>
        <duration-log.disable value="true"/>
        <duration-log.statistics value="false"/>
        <no-step-log value="true"/>
    </report>
```
