### ISSUE TITLE
How to make 3 cars from a flow to enter the simulation at the same time in different lane

### ISSUE THREAD

**Issue by harirRzi** [eclipse-sumo/sumo#14574]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
Hi. I defined the following flows of cars and I want all the 3 cars from carflowNormal_0, enter the simulation at the same time to the simulation. I have defined 3 lanes. lane 0,1 and 2. I want each of them enter in one of those 3 lanes. How can I do it?

```
 <flow id="carflowNormal_0" type="Normal-car-0" begin="0" number="3" route="route_0" departLane="random" probability="0.5" />

   <flow id="carflowNormal_1" type="Normal-car-5" begin="4" number="2" route="route_0" departLane="random" probability="0.5" />
```

**Comment by namdre** [comment]
either:
- flows with attribute probability will insert at most 1 car per step so you cannot get 3 cars with 2 flows. You can use three flows or  use poisson arrivals instead (i.e. period="exp(0.5)" will have the same expected rate of 0.5 cars per step but will sometimes insert more than one car). see https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#repeated_vehicles_flows
- if you want to avoid cars picking the same lane (and thus not being inserted in the same step) set departLane="free"
