### ISSUE TITLE
Netedit does not save options when loading .sumocfg file

### ISSUE THREAD

**Issue by AndiLeni** [eclipse-sumo/sumo#14581]
Steps to reproduce:
- open netedit
- file > load sumo config file
- select a .sumocfg file
- operationen > edit sumo options
- change simulation end time 
- click okay

Expections:
- the "save sumo config" button should be clickable now, but it is disabled
- ctrl+s should save the sumocfg file with the new options, but saving does not change the end time

This issue does not exist if sumo-gui.exe is opened first, loads the sumocfg file and then open netedit from within sumo.  

**SUMO-version:**
1.19.0

**operating system:**
Windows 10

**Comment by m-kro** [comment]
See #12880 . Should work by now (dev version).

**Comment by namdre** [comment]
I can replicate the problem. It seems to be specific to the begin/end options but works as expected with other options.  Ctrl+s is working though even when the button is gray

**Comment by AndiLeni** [comment]
@namdre Thanks for confirming.
I just went and checked again, ctrl+s does not save my changes if I **only** made changes to the end time.
It does however save correctly if I edit the end time and also another option. Then both of them are saved correctly.

**Comment by m-kro** [comment]
hmm works on my side with some basic sumocfg from the test suite...

**Comment by namdre** [comment]
ctrl+s is for saving the network. ctr+**shift**+s is for saving the sumocfg

**Comment by AndiLeni** [comment]
@namdre Sorry to comment on an already closed issue, but it seems like other options are affacted as well.
F.e. I tried setting the "input > routes" option, but the setting is not persisted in the sumocfg file. 

Tested version is from today (27.03.2024) from github actions.

**Comment by namdre** [comment]
It's fine to post relevant things in closed tickets (-:
For the route-files, netedit tries to be "smart" and use the demand files loading in netedit. This resets any custom values in the input field (#14614)
