### ISSUE TITLE
Issues related to user equalisation

### ISSUE THREAD

**Issue by HRYEJJKUK** [eclipse-sumo/sumo#14588]
Hi：
     I used duarouter to generate the roux.xml file assuming: from_taz="0",to_taz="1" and then defined the weight file for the edges and have made sure that duarouter successfully read the edges file. A couple of problems were found: 
     1) All vehicles choose a shortest path. However, according to the user equilibrium definition, when a large number of vehicles concentrate on choosing a path, the road resistance of that path will increase over the suboptimal path. It should happen that some vehicles choose the optimal path, and no vehicles choose the suboptimal path. Eventually, all vehicles will choose the path with the lowest impedance. But what I have seen so far is that all vehicles choose the same path. 
     2) As the edge weight increases, the vehicle path selection will change abruptly. For example, Weights below 10, all vehicles will choose 1 path. Once the weight exceeds 10, all vehicles shift to 2 path.

**SUMO-version:1.19.0**

**operating system:Win64**

**Comment by namdre** [comment]
It seems like you're not using the iteration tool and are instead running duarouter directly.
Did you read about: https://sumo.dlr.de/docs/Demand/Dynamic_User_Assignment.html#iterative_assignment_dynamic_user_equilibrium

**Comment by HRYEJJKUK** [comment]
OK,Thanks.Do you know how to pass a weights file into duaiterate?

**Comment by namdre** [comment]
normally this isn't needed because duaIterate recomputes weights during each iteration. What exactly are you trying to accomplish?

**Comment by HRYEJJKUK** [comment]
1、Since I need to toll certain roads in the network, I use the WEIGHT file to set weights for those toll roads.
          <python duaIterate.py -n 1.net.xml -t -1.trips.xml -l 1000 --max-convergence-deviation 0.05 --logit --weight-memory --additional 1.add.xml duarouter--vtype-output dummy.xml duarouter--additional-files 1.add.xml duarouter--weight-files edge_weight.xml sumo--step-length 1 -b 0 -e 10800>
           I used the above command. Let duarouter consider the weights of the tolled road sections in every iteration.
           2、While performing the iteration, the following error occurred in the second iteration.         
![image](https://github.com/eclipse-sumo/sumo/assets/121792232/196890cd-374a-4c8e-8f27-1043a63692d6)
           Is it because I'm reloading the road network weights on each iteration?

**Comment by HRYEJJKUK** [comment]
<python duaIterate.py -n 1.net.xml -t 1.trips.xml -l 10 --max-convergence-deviation 0.05 --logit --weight-memory **-J edge_weight.xml** --additional JingXiong.add.xml duarouter--vtype-output dummy.xml duarouter--additional-files JingXiongvType.def.xml sumo--step-length 1  -b 0 -e 10800>
I tried the above code again.
![image](https://github.com/eclipse-sumo/sumo/assets/121792232/23d591c6-2d86-4e28-8c60-95beedb93476)
I want to know how to fix it.

**Comment by namdre** [comment]
loading the extra weights with --addweights (or -J) is correct. Simply remove option --weight-memory.

**Comment by namdre** [comment]
Also, in the development version it should be possible to use both options together.

**Comment by HRYEJJKUK** [comment]
Hi:
    When I use Duaiterate, there are a lot of warning messages logged in the dua.log file. They fall into the following four main categories:
1). Warning: Teleporting vehicle '10686'; waited too long (yield), lane=':7949182348_1_0', time=365.00.
2). Warning: Teleporting vehicle '13267'; waited too long (jam), lane=':557282348_2_1', time=391.00.
3). Warning: Vehicle '44646' performs emergency braking on lane '256857274#8_1' with decel=9.00, wished=4.50, severity=1.00, time=515.00.
4). Warning: Vehicle '13267' ends teleporting on edge '117070569#0', time=515.00.
5). Warning: Vehicle '92911' performs emergency stop at the end of lane 'E14_0' because of a red traffic light (decel=-20.21, offset=12.63), time=540.00.
6). Warning: Teleporting vehicle '10870'; waited too long (wrong lane), lane='102413734#0_0', time=648.00.
    How can I fix this please? Does it affect the simulation results? Or is it just logging the vehicle status.As there are tens of millions of entries logged in total.

**Comment by namdre** [comment]
the "teleporting" indicates severe jamming. This is expected during iterations but shouldn't happen in the final simulation.
If it still does, see https://sumo.dlr.de/docs/FAQ.html#the_simulation_has_lots_of_jamsdeadlocks_what_can_i_do

the traffic light warning likely comes from a faulty signal plan which switches from green to red without yellow.
