### ISSUE TITLE
The issue of Sumo termination during operation.

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14591]
Add your issue description here.
Hi, recently I've been running experiments using SUMO via the command line. I've set the simulation termination time to be 86400 seconds, but it always stops prematurely before reaching the scheduled time. Specifically, as shown in the figure below:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/6797c27d-efba-4130-8354-9cc3fcbf773b)

![image](https://github.com/eclipse-sumo/sumo/assets/120693511/2b905377-2fbe-4978-92e5-c6c22c33c67b)
Could you please advise on how to resolve this issue? Thank you.
**SUMO-version:**
SUMO 1.19.0
**operating system:**
Windows10

**Comment by m-kro** [comment]
Please check first when the last vehicle defined in `osm.rou.xml` shall be inserted. If the traffic demand ends long before the defined simulation end, this is expected... 
You could try as well running sumo with **--verbose true** to see if the message of simulation end is printed. If not, sumo may crash silently because of a yet unhandled situation, though.

**Comment by namdre** [comment]
option  **--end** works independent of any vehicles in the input route file. However, your output only shows when the last warning was issued. The simulation continued running afterwards (or possibly crashed). Please post the output of running with **--verbose**

**Comment by nudtdyk** [comment]
> option **--end** works independent of any vehicles in the input route file. However, your output only shows when the last warning was issued. The simulation continued running afterwards (or possibly crashed). Please post the output of running with **--verbose**
Thank you for your advice, and I apologize for keeping you waiting. When I ran the program according to your suggestion, it seems to indicate that the termination of the operation is due to traffic congestion. Specifically, as shown in the following figure:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/fb082a3f-a220-4caf-a159-7e605ba13dd2)
Could you tell me how to fix it. Thanks!

**Comment by namdre** [comment]
dealing with jams is a complex topic, see https://sumo.dlr.de/docs/FAQ.html#the_simulation_has_lots_of_jamsdeadlocks_what_can_i_do

From the output you are posting I still get the impression of improper termination. Could you please run 
`sumo -c hhh.sumocfg --verbose -t --log log.txt` and then attach the generated file log.txt to this issue?

**Comment by nudtdyk** [comment]
> dealing with jams is a complex topic, see https://sumo.dlr.de/docs/FAQ.html#the_simulation_has_lots_of_jamsdeadlocks_what_can_i_do
> 
> From the output you are posting I still get the impression of improper termination. Could you please run `sumo -c hhh.sumocfg --verbose -t --log log.txt` and then attach the generated file log.txt to this issue?

Thank you for your patience. The log file after execution is as follows：
[tb_1000log.txt](https://github.com/eclipse-sumo/sumo/files/14770104/tb_1000log.txt)

**Comment by m-kro** [comment]
@nudtdyk Can you please provide the SUMO files as well? The log output suggests improper termination of the program. Btw did you change something in your sumocfg (because in the first screenshot the simulation runs til at least t=19679 whereas now it crashes at t=2000)?

**Comment by nudtdyk** [comment]
[hhh.zip](https://github.com/eclipse-sumo/sumo/files/14770676/hhh.zip)
The files are as above. Thanks！

**Comment by m-kro** [comment]
@nudtdyk Unfortunately your achive contains only the sumocfg file. We need all files referenced in the sumocfg as well.

**Comment by nudtdyk** [comment]
> @nudtdyk Unfortunately your achive contains only the sumocfg file. We need all files referenced in the sumocfg as well.

Thanks for your kind, please give me an email as GitHub does not support the transfer of large files. Thanks again!

**Comment by palvarezlopez** [comment]
> Thanks for your kind, please give me an email as GitHub does not support the transfer of large files. Thanks again!

You can use googleDrive or dropbox to upload the files there, and share here the link.

**Comment by m-kro** [comment]
Closing due to lack of feedback
