### ISSUE TITLE
Unexpected rerouting

### ISSUE THREAD

**Issue by henrigrossmann** [eclipse-sumo/sumo#14594]
**Description:**
I've configured my simulation setup with preset weights for routing and ensured that the adaptation interval and rerouting period are set to very high values in order to prevent rerouting and changed weights during the simulation. However, upon examining the output TripInfo file (attached as "velo_trips_CRG.xml") I noticed that some vehicles are being rerouted multiple times, contrary to my expectations.

**Expected Behavior:**
I expect vehicles to be routed only once at the beginning of their trips or at the start of the simulation, given the high values set for adaptation interval and rerouting period.

**Additional Context:**
The _device.rerouting.adaptation-interval_ is set to a high value ("82800") to prevent weight changes during simulation.
_device.rerouting.period_ is also set to that value to prevent rerouting.

**Questions:**
What might be causing these unexpected reroutings despite the configured settings?
Is there a simpler approach to ensure each vehicle is routed only once at the beginning of their trips or at simulation start using the loaded weights?

**Files Attached:**
- Simulation setup file with relevant configurations and input
- Output file "velo_trips_CRG.xml" showcasing the unexpected rerouting instances.

[ReroutingIssue.zip](https://github.com/eclipse-sumo/sumo/files/14749790/ReroutingIssue.zip)

**Comment by namdre** [comment]
you are probably seeing pre-insertion rerouting which can be disabled with **--device.rerouting.pre-period**  (default is 60)
you can set both period options to 0 to disable rerouting.
Also, setting the adapation-interval to 0 disables adaptation.

**Comment by henrigrossmann** [comment]
Thank you for clarifying. When the pre-period is set to 0, vehicles are no longer routed based on their loaded weights though.

**Comment by namdre** [comment]
please try setting a high value for pre-period then

**Comment by henrigrossmann** [comment]
That works but then again I have some trips with rerouteNo=0 and some with rerouteNo=1 (but no trips with rerouteNo > 1, which is what I wanted to achieve). I think if the vehicles keep their original route as given in the input file, their rerouteNo=0 and if they change their original route it switches to rerouteNo=1. Might that be the case?

**Comment by namdre** [comment]
Yes. rerouting isn't counted if the route remains the same.

**Comment by henrigrossmann** [comment]
Great, thank you for your fast answers!
