### ISSUE TITLE
Is there any UI platform or libraries that developers use to make sumo-gui?

### ISSUE THREAD

**Issue by juun9714** [eclipse-sumo/sumo#14595]
I just want to know if sumo-gui developers used UI platform or GUI libraries to develop sumo-gui. 

**SUMO-version: 1.19.0**

**operating system: Windows**

**Comment by palvarezlopez** [comment]
@juun9714 yes, for the GUI we use FOX Toolkit. You have all SUMO libraries here: https://github.com/DLR-TS/SUMOLibraries
