### ISSUE TITLE
Getting several signals at once is possible?

### ISSUE THREAD

**Issue by juun9714** [eclipse-sumo/sumo#14606]
Hi, I'm using SUMO to create vehicle signals and get signals to implement my project.

In this process, I have one question. As I know we can define vehicle type on ".rou.xml" with our user-defined attributes by _**param key=**_

And if we add vehicle with that type, then we can set and get our user-defined attributes. In this step, I want to get several attributes at once, rather than call "**_vehicle.getParameter()_**" for each user-defined attributes.

Is it possible to get several attributes at once?

**SUMO-version:1.19.0**

**operating system:Windows**

**Comment by m-kro** [comment]
No it is not. Even [object subscriptions](https://sumo.dlr.de/docs/TraCI/Object_Variable_Subscription.html#special_cases) would return only the value of the latest defined parameter key.
