### ISSUE TITLE
Changing edge lengths after junction computation

### ISSUE THREAD

**Issue by aminissn** [eclipse-sumo/sumo#14602]
I define E1 detectors by reading the network in sumolib, but after loading the detectors in NETEDIT, I realized some detectors have invalid positions over lane. The issue is that edge lengths are in (this case) shorter before compute junctions and the given pos is marked as invalid. Even friendlyPos=True doesn't solve the issue.

**Comment by namdre** [comment]
can you provide example inputs?

**Comment by namdre** [comment]
can you attach the detector file as well?

**Comment by aminissn** [comment]
I had a typo in writing friendlyPos... so that solves the issue. But the edge lengths are recalculated after computing junctions. Not sure when reading the network with sumolib, does it read with or without computing the junctions.

**Comment by namdre** [comment]
sumolib reads the computed lane length values from the .net.xml and edge length is simply the length of lane 0
