### ISSUE TITLE
Atomic lane change by a platoon of vehicles

### ISSUE THREAD

**Issue by michele-segata** [eclipse-sumo/sumo#14623]
Hi guys,

I'm reaching out for a suggestion on how to properly perform a lane change atomically on a platoon, something that is missing from Plexe since a long time and sometimes causes simulations to crash or to behave in an unwanted manner. The situation is the following. Imagine having two platoons that both want to change lane towards the central one at the same time:

<img width="600" alt="" src="https://github.com/eclipse-sumo/sumo/assets/2064511/12efef93-23f4-487a-8827-b684cf703b9f">

The way I am doing safety checks in `MSCFModel_CC` right now is by having the leader check the lane change status of all followers. If all of them report a free destination lane, I am calling `changeLane()` on all the vehicles in the platoon. Given the above image, however, the central lane is free for both of them, so `changeLane()` will be called on all vehicles of both platoons. As the lane change is applied independently on each vehicle, I am ending up with the following situation:

<img width="600" alt="" src="https://github.com/eclipse-sumo/sumo/assets/2064511/ae8d6d2a-a89b-4c53-a3be-d060e95b5d7e">

The upper platoon changes lane, the first two vehicles of the lower platoon find the lane busy and don't change lane, but the third vehicle of the bottom platoon finds the lane free and the lane change logic moves the car disrupting the platoon.

I've implemented a solution [in this commit](https://github.com/michele-segata/plexe-sumo/commit/94ab6a46acd8cbb34930840a642388ca2a95a53f). The idea is, when the actual lane change is done, re-ask the whole platoon whether changing is still safe. If the lane change logic has moved some vehicle, then they will realize the lane is not free anymore and not commit to the lane change.
Although this works, I don't like the implementation at all because it is modifying `MSLaneChanger::checkChange()` in its core. Ideally, if the lane changer class implementation could be chosen via a parameter like car following or lane change models, then it would be simple: implement my own lane changer overriding that method. However there is nothing like this, as the only two options are the "discrete" lane changer and the sublane one. Of course something like this could be implemented, even making it backward compatible, but before doing something like this I wanted to have an opinion from you, whether there is another way of doing it more simply/elegantly.

Thanks guys!

**Comment by namdre** [comment]
The easiest solution whithin SUMO would be to have MSLaneChanger call some yet-to-be-defined function on the current lane changing model to handle commitment. Then you can implement your custom lane changing model (https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models) and this implements the desired custom behavior whereas the default implementation for commitment does nothing.

A maybe easier solution outside SUMO would be to identify vehicles around a platoon and disable their lane-changing desire for the duration of the platoon change (either via setLaneChangeMode or by setting laneChangeModel parameters that influence the different lane changing motivations).

**Comment by michele-segata** [comment]
Thanks Jakob! I gave it a try to the second solution, and indeed I quickly managed to implement that by having a kind of lane reservation method, at least for vehicles using `MSCFModel_CC`. However, in case of mixed simulations with `IDM` vehicles as well, for example, I am not really sure how to do something like this. Is there a way to disable the lane change for a single time step? Of course I could have the `MSCFModel_CC` vehicle change the lane change mode of the `IDM` one, but then I would need to keep track of that and restore it at the next time step.

Otherwise, I'll try to implement the first option trying to minimize the changes in core files and without braking backward compatibility, maybe asking your opinion again before submitting a PR.

**Comment by namdre** [comment]
Setting and restoring a laneChangeMode for surrounding traffic shouldn't be too bad. The bluelight device does something similar to obtain a rescue lane.

**Comment by michele-segata** [comment]
Hi Jakob,

I actually went for the first option (slightly changing `MSLaneChanger` enabling to have a custom lane change model) as changing and restoring the lane change mode seemed more error-prone to me. You find my own branch [here](https://github.com/michele-segata/plexe-sumo/commits/mslcm_lc2013_cc/). Some comments to get your feedback:
- [This commit](https://github.com/michele-segata/plexe-sumo/commit/3c595bc74a345b65b3f032c1be57c8f70e6e441a) is the one making changes to the core files (`MSLaneChanger` and `MSAbstractLaneChangeModel`). As you can see the change is minimal and totally backward compatible. The idea is, when a vehicle wants to change lane and it is not blocked, call the `checkChangeBeforeCommitting` method to re-evaluate the blocking state. If not implemented, this method simply returns 0 (so not blocked) and thus have no effect.
- [This commit](https://github.com/michele-segata/plexe-sumo/commit/5593eacd51ac0ad440665504d6ef73bddf5e98e7) instead adds a custom lane change model that extends `LC2013` and which is platoon-aware. For vehicles not using `MSCFModel_CC` the lane change model has no effect, but in any case people not using platooning features would not even instantiate that.

We will run some large scale simulations to properly test this, but before that I'd like to understand whether you think what I did is reasonable or whether something could be done in a better way.
Thanks again!

**Comment by namdre** [comment]
It does look a bit heavy-handed but otherwise doesn't bother me.  You would still need some state variables to prohibit changes and then re-allow them after the platoon change (at least this how I imagine the implemenation of `checkChangeBeforeCommitting`). 
Thus you don't seem to gain so much over just setting existing state variables (laneChangeMode or lcSpeedGain+)

**Comment by michele-segata** [comment]
> It does look a bit heavy-handed but otherwise doesn't bother me. You would still need some state variables to prohibit changes and then re-allow them after the platoon change (at least this how I imagine the implemenation of `checkChangeBeforeCommitting`).

In fact `checkChangeBeforeCommitting` doesn't prohibit and then re-enable. It allows the model to check again for occupancy of the destination lane, which state might have changed within the very same timestep because SUMO is starting to move vehicles on their desired lanes.

> Thus you don't seem to gain so much over just setting existing state variables (laneChangeMode or lcSpeedGain+)

My fear here was having to handle multiple vehicles that request disabling the laneChangeMode of a single one. Where do I store the current laneChangeMode? How do I know whether this has already been disabled during the following timestep by another vehicle? When should I restore such state?
My current solution does depends only on the current timestep, so I deemed it easier.

**Comment by michele-segata** [comment]
Closing as merged
