### ISSUE TITLE
Where SUMO reads the rou.xml's content?

### ISSUE THREAD

**Issue by juun9714** [eclipse-sumo/sumo#14627]
I'm adding some user-defined vehicle signal to mydemo.rou.xml like below. For future I would like to add some signals and I don't want to rebuild SUMO again. I want to know where SUMO reads rou.xml file to get user-defined vehicle attribute(parameter).

```
<vType id="mycar" accel="0.8" decel="4.5" sigma="0.5" length="5" maxSpeed="70">
        <param key="timestamp" value="0"/>
        <param key="latitude" value="0.0"/> 
        <param key="longitude" value="0.0"/> 
        <param key="altitude" value="0.0"/> 
</vType>
```

*If possible, upload an example that shows your problem.*

**SUMO-version:1.19.0**

**operating system:Windows**

**Comment by m-kro** [comment]
The route XML files are read by **src/utils/handlers/RouteHandler.cpp**. Not sure though what you actually want to do...
