### ISSUE TITLE
How to add text to sumo-gui using traci.

### ISSUE THREAD

**Issue by HRYEJJKUK** [eclipse-sumo/sumo#14629]
Hi：
    I want to konw how to add text to sumo-gui using traci.This includes setting the text content, font size, text position and color, etc.

**SUMO-version:1.19.0**

**operating system:win 10**

**Comment by namdre** [comment]
the easiest thing traci.poi.add imgFile attribute and then put whatever you want in the image.

You can also enable poi type rendering and put arbitrary text in the poi type. You would have to load a gui settings file that sets the text size and color but all pois would share the same font settings.
