### ISSUE TITLE
Vehicle energy consumption issue

### ISSUE THREAD

**Issue by jianki1314** [eclipse-sumo/sumo#14628]
how can we reduce the energy consumption of vehicles?

**Comment by namdre** [comment]
reduce their acceleration capabilities, weight and maximum speed? Make traffic flow smoother with better traffic light programs and better route choice, apply GLOSA to avoid some braking/accelerating at red lights.

**Comment by namdre** [comment]
also, transport more passengers per vehicle to reduce the number of cars on the road

**Comment by jianki1314** [comment]
thank you very much
