### ISSUE TITLE
How getParameter() function triggers receive and send function?

### ISSUE THREAD

**Issue by juun9714** [eclipse-sumo/sumo#14626]
Function like libtraci::Vehicle::getSpeed() calls sendExact and receiveExact in socket.cpp. So, I can understand the TraCI client send request and SUMO server reponse with requested value. 

But I cannot find the communication part in the libsumo::Vehicle::getParameter(). It just returns the value of the vehicle without socket communication. Where can I find the socket communication part for getParameter()?

*If possible, upload an example that shows your problem.*

**SUMO-version:1.19.0**

**operating system:Windows**

**Comment by juun9714** [comment]
@jjyyxx oh! thank you :) then where can I check that shared memory on my source code?

**Comment by juun9714** [comment]
I have one more question, then why `libtraci/Vehicle.cpp` code includes the `libsumo/Vehicle.h`?

**Comment by namdre** [comment]
> I have one more question, then why does `libtraci/Vehicle.cpp` code include the `libsumo/Vehicle.h`?

Because libsumo and libtraci have the same API. They only differ in the implementation.

**Comment by juun9714** [comment]
@namdre If so, why do libsumo use shared memory, and libtraci use socket communication? + where can I check shared memory related source code?

**Comment by namdre** [comment]
libsumo has the advantage of speed, whereas libtraci has the advantage of supporting remote connections, gui-support on all platforms and being able to multiplex connections to multiple servers from a single client runtime. The code for libsumo can be found in  sumo/src/libsumo
