### ISSUE TITLE
unexpected next behavior in tls logic

### ISSUE THREAD

**Issue by aminissn** [eclipse-sumo/sumo#14622]
I have defined a custom rule for phase skipping by using next in the tls logic. Howver, when there is no traffic, phase 0 will jump to phase 7 instead of 1, despite having phase 1 in the next tag in the first place (i.e. has the highest priority). Am I making a mistake here?
https://github.com/eclipse-sumo/sumo/assets/30176885/0e56a75b-9ff3-4c80-9735-c1b809ff5d44

**Comment by namdre** [comment]
the code works differently when custom switching rules are in play (see the updated docs). I'm reluctant to change it now because it would brake backward compatibility.
