### ISSUE TITLE
Circular highway misclassified as roundabout

### ISSUE THREAD

**Issue by jiaery** [eclipse-sumo/sumo#14634]
The early stage of the simulation is normal, but after the simulation is carried out for a period of time, most of the vehicles take the ramp and merge into the main road from the ramp, increasing the conflict of the intersection point, resulting in congestion. Is this related to certain parameters of the vehicle, and how can I change it?

![111](https://github.com/eclipse-sumo/sumo/assets/164708306/e3f89ab9-bcdb-4f1a-a461-daec2dd59c28)
**SUMO-version:1.19.0**

**operating system:*win11*

**Comment by namdre** [comment]
this could be a problem with the right-of-way rules or connections at the merging section. Can you attach your simulation or at least the network?

**Comment by jiaery** [comment]
Thank you very much for your reply！I checked that there were no problems with the connections, and the simulation drove normally when the number of vehicles was low in the early stages, and gradually increased in the later stages, and most of the vehicles started to take the ramp, increasing the merge conflict.The connection is shown in the figure below.the right-of-way rules is priority.
![image](https://github.com/eclipse-sumo/sumo/assets/164708306/7c32bd8e-6928-41e3-992a-ed0ba5c7d400)

**Comment by jiaery** [comment]
[osm.net.xml.zip](https://github.com/eclipse-sumo/sumo/files/14824872/osm.net.xml.zip)
This is my simulated road network file. Looking forward to hearing from you.

**Comment by namdre** [comment]
netconvert classifies your whole motorway network as a giant roundabout. Vehicles inside a multi-lane roundabout prefer driving on the inside lane and this is causing congestion and generally wierd behavior in your scenario. The easiest workaround is to set `lcCooperativeRoundabout="0"` in the vType.

**Comment by namdre** [comment]
proposed solution: define a configurable maximum size for roundabout-guessing (i.e. 1km)

**Comment by namdre** [comment]
@jiaery to fix your network you can do the following:

```
netconvert -s osm.net.xml -p plain
netconvert -e plain.edg.xml -n  plain.nod.xml -x plain.con.xml --roundabouts.guess false -o fixed.net.xml
```

(if you are using a dev version after 76926c5 you don't need `--roundabouts.guess false`)
