### ISSUE TITLE
Is it possible to make scenario specifically?

### ISSUE THREAD

**Issue by juun9714** [eclipse-sumo/sumo#14639]
I'm working on SUMO simulation with C++ on Windows. I want to get vehicle signals while simulation. 

I know that I can specify following things on xml files:
- route that vehicle will drive
- route's max speed
- vehicle's max speed & accel value

However I want to specify the vehicle's behavior like these examples:
- increase speed until 100km/h from step 10 to step 20.
- make vehicle run on specific edge on step 100.
- make vehicle accidently stop at step 200 accidently and turn on emergency signal. 

I want to make vehicle's behavior like this only with xml file. 
Is it possible to make xml file to specify detailed vehicle's behavior?

**SUMO-version:1.19.0**

**operating system:Windows**

**Comment by m-kro** [comment]
This can not be predefined in XML. The named topics would be rather a regular output of the simulation than an input. We have [TraCI](https://sumo.dlr.de/docs/index.html#traci_on-line_interaction) functions to override several simulation aspects while it is running, though.

**Comment by namdre** [comment]
you can do a lot of this kind of scripting by defining stops and waypoints in the xml input: https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#stops_and_waypoints
(if you stop on a multi-lane road and it's not the rightmost lane, vehicles will turn on the emergency signal by default).
