### ISSUE TITLE
Vehicles on the highway do not automatically change lanes at the interchange gate to reduce conflicts with other vehicles, resulting in congestion.

### ISSUE THREAD

**Issue by jiaery** [eclipse-sumo/sumo#14638]
Vehicles habitually drive in the rightmost lane on the highway and start queuing to cause congestion, this phenomenon is especially obvious at the entrance of the ramp, the lane change model used is LC2013, I would like to know the cause of this phenomenon and the solution, I look forward to your reply.

![image](https://github.com/eclipse-sumo/sumo/assets/164708306/45d05f3d-7efb-41ca-a153-8754e71f4e26)

**SUMO-version:*1.19.0*

**operating system:*win11*

**Comment by m-kro** [comment]
You can try some different lane change model parametrisation (see [parameters](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models) in doc). 

- There is a parameter for keeping the right lane: Set lcKeepRight to 0.
- If this is not enough, maybe raise lcSpeedGain value. This will work best if some vehicles want to drive faster (=distribution of desired speeds)

**Comment by namdre** [comment]
is this the same network as in #14634  ?

**Comment by jiaery** [comment]
> is this the same network as in #14634 ?
Yes, it's the same road network



> You can try some different lane change model parametrisation (see [parameters](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models) in doc).
> 
> * There is a parameter for keeping the right lane: Set lcKeepRight to 0.
> * If this is not enough, maybe raise lcSpeedGain value. This will work best if some vehicles want to drive faster (=distribution of desired speeds)

I've made some changes based on your comments：
1. Set lcKeepRight to 0.
2.  raise lcSpeedGain value to desired speeds
3. and modified with reference to issue #14634（Set lcCooperativeRoundabout=“0” and fix my network as your suggested）

However, there are still cases where vehicles habitually drive on the right-hand side
![image](https://github.com/eclipse-sumo/sumo/assets/164708306/ed94aba3-0249-419d-84ce-bb6ecc684fbf)
The picture below is my vtype parameter setting, I don't know why this situation still exists, can you give me a little advice, thanks.
![image](https://github.com/eclipse-sumo/sumo/assets/164708306/18a3c60e-785c-4f16-b15c-62116df2b24f)

**Comment by namdre** [comment]
please attach your updated network and route files along with a sumocfg (as a zip archive).

**Comment by jiaery** [comment]
[expressway.zip](https://github.com/eclipse-sumo/sumo/files/14854045/expressway.zip)
Here's my updated network and route files.

**Comment by namdre** [comment]
- the network still had an invalid roundabout classification
- several connections were inappropriate and thereby causing invalid strategic lane changing behavior

Attached is a locally fixed network. The diff-files document the changes. Note, that a lot of acceleration lanes are still missing (i.e. at junction 436884087 and junction 8714596484.  This is a problem in the OSM database and you can fix it manually by increasing the lane number and setting the appropriate conflict-free connections. See https://sumo.dlr.de/docs/Simulation/Motorways.html#reduction_in_the_number_of_lanes

[fixed.zip](https://github.com/eclipse-sumo/sumo/files/14856450/fixed.zip)
