### ISSUE TITLE
The Warnings of duaIterate's log

### ISSUE THREAD

**Issue by HRYEJJKUK** [eclipse-sumo/sumo#14631]
Hi：
   I use duaIterate for dynamic traffic assignment. As a result the log file records the following.
   1). Warning: Teleporting vehicle '112784'; waited too long (yield), lane='507016098#0_3', time=787.00.
   2).Warning: Vehicle '112784' ends teleporting on edge '507016098#4', time=787.00.
   3).Warning: Teleporting vehicle '10153'; waited too long (jam), lane='834360004#0_1', time=727.00.
   4).Warning: Vehicle '10153' ends teleporting on edge 'E4', time=727.00.4). 
   5).Warning: Teleporting vehicle '10870'; waited too long (wrong lane), lane='102413734#0_0', time=648.00.
   6).Warning: Vehicle '127870' performs emergency braking on lane '-1175366590#4_0' with decel=9.00, wished=4.50, severity=1.00, time=900.00.
   7).Warning: Vehicle '127870' performs emergency stop at the end of lane '-1175366590#4_0' because of a red traffic light (decel=-15.71, offset=5.12), time=900.00.
   Is it necessary to define certain parameters by? For example: collision.mingap-factor value, emergencydecel.warning-threshold value, or increase the waiting threshold to prevent teleporting from moving vehicles off the road network.

**SUMO-version:1.19.0**

**operating system:win10**

**Comment by namdre** [comment]
already answered in #14588  (please don't post the same question twice)
