### ISSUE TITLE
Adding a way of getting incoming edges to libsumo junctions

### ISSUE THREAD

**Issue by bran-jnw** [eclipse-sumo/sumo#14665]
Hello, 

I am the principal developer of WUI-NITY (https://www.nfpa.org/education-and-research/research/fire-protection-research-foundation/projects-and-reports/wuinity-a-platform-for-the-simulation-of-wildlandurban-interface-fire-evacuation) and I am currently coupling SUMO through libsumo (C# bindings).

So for everything works great, I am able to add cars to SUMO through the pedestrian module that tracks households walking to their cars, and I can route cars to shelters/evacuation goals set up by the user during runtime.

However, one of the key features of our model is to dynamically change the routing and available goals based on the fire propagation, and I am having a few suggestions/questions regarding how this is best done in SUMO.

My current idea is to track whenever a junction is in a raster cell that is ignited, and from that junction call each connected edge and set the permissions accordingly. The reason for basing it on junctions is due to the simpler positional data (they have one position instead of multiple ones, so only one raster cell will overlap, this is not case for an edge). 

The above can be achieved by parsing the net.xml and extract the incLanes per junction, but it would be easier if it could be done directly through libsumo., so what I have done so far is to add this piece of code in libsumo/Junction (as well declaration in header, and a dummy for libtraci so that SWIG does not complain):
```
std::vector<std::string>
Junction::getIncomingEdges(const std::string& junctionID) {
    std::vector<std::string> edgesOut;
    std::vector<const MSEdge*>  edges = getJunction(junctionID)->getIncoming();

    for (int i = 0; i < (int)edges.size(); ++i)
    {
        const MSEdge* edge = edges.at(i);
        edgesOut.push_back(edge->getID());
    }

    return edgesOut;
}
```
This gets me the all of the edges and then I just get rid of the internal ones by ignoring any edge starting with ":".

So, the question is the can this be added as a default libsumo call or is there any reason why this would be bad? Or is there any other approach that I should rather take?

Best regards, 
Jonathan

**Comment by m-kro** [comment]
The main reason this hasn't been implemented (yet) is that the road network topology is deemed to be static, whereas TraCI (and libsumo) deal with dynamic values of the simulation. For Python we have some utilities ([sumolib](https://sumo.dlr.de/docs/Tools/Sumolib.html)) which help parsing the network. Nevertheless people have been requesting such features for long either because they don't work with Python or are not aware of it...

**Comment by bran-jnw** [comment]
Yes, I did see that sumolib could do what I needed (and also solves some other issues such as finding edges within a given radius), but I do indeed not use Python. Would you see it as more fit to just create glue code to enable use of sumolib from C# in my case rather than to add functionality to libsumo?

**Comment by namdre** [comment]
we already have plans to add the functionality: #14490

**Comment by bran-jnw** [comment]
Great, thanks!
