### ISSUE TITLE
very small poisson arrival rates loads a lot of vehicles

### ISSUE THREAD

**Issue by temetski** [eclipse-sumo/sumo#14664]
When using Poisson distributed flows, setting the arrival rate of X<1e-3 (e.g. 'exp(0.0001)') causing unexpected behavior. Instead of having low arrival rates, this causes sumo to load a lot of vehicles, which is incorrect and also causes the simulation to freeze. This does not occur when X>1e-3.

I believe the issue stems from the conversion of double to long long int done in https://github.com/eclipse-sumo/sumo/blob/b55348ece1fbfe0c90e4e1ade7118bf1c0d52dbb/src/utils/common/SUMOTime.h#L55C13-L57C18

While very small values of arrival rates may be beyond the reasonable design of SUMO, it might be a good idea to document this caveat for anyone who might use Poisson distributed flows.

![image](https://github.com/eclipse-sumo/sumo/assets/6328105/57b25957-103b-4385-bc14-0ace2434d70c)

[config files](https://github.com/eclipse-sumo/sumo/files/14872438/Archive.zip)

*If possible, upload an example that shows your problem.*

**SUMO-version:** 1.19.0

**operating system:** MacOS

**Comment by namdre** [comment]
somewhat related to #14648
