### ISSUE TITLE
linkMaxDur not working with custom switching rules

### ISSUE THREAD

**Issue by aminissn** [eclipse-sumo/sumo#14669]
I am using  linkMinDur and linkMaxDur to define the minimum and maximum green time for each phase. However, when I added my custom rules for phase skipping using "next" attribute, I noticed that only the maxDur from the corresponding phase is taken into account not the extra condition defined in
```
  <param key="linkMinDur:10" value="34"/>. 
```

**Comment by namdre** [comment]
can you provide a minimal failing example?

**Comment by aminissn** [comment]
I am actually not sure if that is the issue or somehow the issue with how next attribute works as discussed in [#14622](https://github.com/eclipse-sumo/sumo/issues/14622 ). The problem is, when there is no traffic, the signal phase stay green up to maxDur and ignores next attribute. I will provide the example for the following screenshot later today.
<img width="1461" alt="image (1)" src="https://github.com/eclipse-sumo/sumo/assets/30176885/ae76aba5-826e-406a-ab00-b009f84d062c">

**Comment by aminissn** [comment]
here is the example:
[next_issue.zip](https://github.com/eclipse-sumo/sumo/files/14918756/next_issue.zip)

**Comment by aminissn** [comment]
I think when custom switching rules are defined, the time-gap switches which are automatically defined for actuated control are ignored --> the user must define the corresponding conditions. It would be nice to allow the user to have the custom rules on top of these automatically created rules

**Comment by namdre** [comment]
> I think when custom switching rules are defined, the time-gap switches which are automatically defined for actuated control are ignored --> the user must define the corresponding conditions. It would be nice to allow the user to have the custom rules on top of these automatically created rules

This is correct. You cannot mix automatic rules with custom rules **in the same step** (but different steps can use either one).
Though the linkMinDur and linkMaxDur values should in principle be usable for custom and automatic rules.
The surprising thing is this:
- the code for linkMaxDur only gets used when the automatic rules are active for that step
- the code for linkMinDur is always active as far as the code is designed

Assuming your simulation runs without traffic (but **--end 3600** instead). In which second does the switching behavior first differ from your expectation?

**Comment by aminissn** [comment]
from second 13 things go wrong. i) it reads maxDur from <phase state="xxx" minDur="x" maxDur="x"/> and not from <param key="linkMaxDur:x" value="x/> ii) I expect in all phases when minDur is reached and there is no traffic, it moves to the next phase. it happens in sec 17 and 33 for phase 0 and phase 3. But at second 89 it shifts to phase 3 (from phase 22) and stays green for 45s even though there is no traffic. Then, it shifts to phase 6 and also stays green for 45s, again after few seconds no car is present on that edge either, a situation I would expect an automatic phase skipping.

**Comment by namdre** [comment]
> from second 13 things go wrong. i) it reads maxDur from <phase state="xxx" minDur="x" maxDur="x"/> and not from <param key="linkMaxDur:x" value="x/>

I'm not sure I understand the problem. In second 13 the control is in phase 0 with maxDur="45. The green links are 6,7,8,9 and 16,17,18,19
For 6,7,8,9 you have defined a linkMaxDur of 65 and for links 16,17,18,19 you haven't defined any linkMaxDur values in the input file. Hence there is no reason why it should end the phase in second 13.

> at second 89 it shifts to phase 3 (from phase 22) and stays green for 45s even though there is no traffic.

If any of the target phases define custom switch rules (`earlyTarget`) then all all target phases should have this. When in phase 3, target phase 4 is lacking an `earlyTarget` condition and thus never gets chosen. The needed condition would be something like
`z:D2.0 > 3 and z:D2.1 > 3` 

Regarding the use of linkMinDur: it generally doesn't make sense to set this to a lower value than the phase minDur because it is used as an additional criterion (not a replacement):  if the current phase gives green to a link and the target phase also gives green to that link then the linkMinDur criterion succeeds, otherwise it may prevent a switch to that particular target phase.

The symmetrical reasoning holds for linkMaxDur: it makes only sense to uses this if consecutive phases give green to the same link and you want to count across phases.

**Comment by aminissn** [comment]
yes, I think the title of the issue is wrong. The main "problem" is that when custom switching rules are added, automatically generated detectors (D0.0, D1.2 etc.) and actuation rules are not used for actuated control. I think it would be nice to enable that as an option.

**Comment by namdre** [comment]
But you can mix them in the same controller. The rule is simply, that if any of the "next" phases for the current phase have custom rules, then all of them need a custom rule. So if you have an extensible phase with all non-custom next, it will switch to the default rules.

How about this: I could add the special condition `DEFAULT` which replicates the default conditions as a custom rule so you could specify `earlyTarget="DEFAULT"` in phase 4 and then phase 3 would work as expected.

**Comment by aminissn** [comment]
I think that's a good solution. Because the detector IDs are not very clear to me as I asked yesterday in the user mail list.

**Comment by aminissn** [comment]
I am getting this Error:

Error: Error when evaluating expression 'earlyTarget=DEFAULT':
  Invalid Number Format (double) earlyTarget=DEFAULT

**Comment by namdre** [comment]
Then you're still using an older version. I only fixed it this morning so
the nightly binaries from today don't have the fix yet.

Am Di., 9. Juli 2024 um 13:21 Uhr schrieb Sasan ***@***.***>:
