### ISSUE TITLE
How to dynamic change lane connections in simulation?

### ISSUE THREAD

**Issue by allenzhuyi** [eclipse-sumo/sumo#14672]
Does SUMO support dynamically changing the connection relationships of lanes? I want to use it for dynamic scenarios with variable lanes. How can I support this? For instance, I want a certain lane to go straight at one time and then straight + left turn at another time. If not, what kind of dynamic workaround can be used to support this?

**SUMO-version:** 1.19

**operating system:** windows 10

**Comment by namdre** [comment]
The easiest way is to provide all connections that are ever needed and the enable/disable them selectively by changing lane permissions for the so called "internal" lanes that are used to pass these connections.
You can set the permissions either via `traci.lane.setAllowed` or with xml input: https://sumo.dlr.de/docs/Simulation/Rerouter.html#closing_a_lane

**Comment by allenzhuyi** [comment]
But I see document(https://sumo.dlr.de/docs/TraCI/Change_Lane_State.html). The setAllowed/setDisallowed method means Sets a list of allowed/disallowed vehicle classes, which is not for lane connections. Can you give an example code ? I want to use dynamically traci method to  enable or disable the lane connection during the simulations.

**Comment by namdre** [comment]
each connection in the simulation corresponds to one or two "internal" lanes and those can be manipulated with the traci.lane api.
see https://sumo.dlr.de/docs/sumo-gui.html#investigating_internal_edges_and_lanes
