### ISSUE TITLE
Traffic demand from observation counts

### ISSUE THREAD

**Issue by NoelGK** [eclipse-sumo/sumo#14677]
Hi,
I am trying to perform a simulation in SUMO starting from traffic count data from detectors. I am trying to use both _dfrouter_ and _flowrouter_, but I can't get neither of them to work as intended. The input files I have used can be seen in [this repository](https://github.com/NoelGK/sumo-testfiles.git)

For the detectors, I am starting from a CSV file with id, latitude and longitude of the detector, which I later convert to a file `detector.xml` using the python code provided [here](https://sumo.dlr.de/docs/Tutorials/HighwayDetector.html#locating_detectors):

Then, I classify detectors into source, sink, etc using _dfrouter_: 
```
dfrouter -n net.net.xml -d detector.xml --detector-output detector.det.xml
```

**For dfrouter**:
```
dfrouter -n net.net.xml -d det.det.det.xml -f flows.csv -o routes.rou.xml --emitters-output vehicles.xml
```
 executes correctly, but when I call _sumo_ as [in the documentation](https://sumo.dlr.de/docs/Demand/Routes_from_Observation_Points.html#how_to_include_the_files), `sumo -n net.net.xml --additional-files routes.rou.xml,vehicles.xml --netstate-dump netstate.xml -b 0 -e 60`, the state of the network doesn't reflect any vehicles:

```
<netstate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/netstate_file.xsd">
    <timestep time="0.00"/>
    <timestep time="1.00"/>
    <timestep time="2.00"/>
...
</netstate>
```

**For flowrouter**
On the other hand, using _flowrouter_ as explained [here](https://sumo.dlr.de/docs/Tools/Detector.html#flowrouterpy): 
```
$SUMO_HOME/tools/detector/flowrouter.py -n net.net.xml -d detector.det.xml -f flows.csv -o routes.rou.xml -e flows.xml -i 15
```

ends in empty and `routes.rou.xml` file.

**SUMO-version:** v1_19_0+1462-65a4e314ace

**operating system:** Ubuntu 20:04

**Comment by m-kro** [comment]
Please stick to the separator **;** (semicolon) for the flows table, This is hard-coded :-\.

**Comment by namdre** [comment]
Note, that there are known problems with dfrouter and flowrouter, I would generally advise on using routeSampler.py instead: https://sumo.dlr.de/docs/Demand/Routes_from_Observation_Points.html#choosing_the_right_tool
