### ISSUE TITLE
Rails hide one side of edge below

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#14678]
Can be seen in the network 2 from #14419  :

![grafik](https://github.com/eclipse-sumo/sumo/assets/33294728/02f18b92-18a7-408c-b07a-16eb8131a3fc)

There are separate edges below the rails as in OSM (Greifengasse, Basel). Although the lower edges have a width of 2.5m, only a narrow stretch is drawn as long as the rails are not hidden/removed.

**Comment by namdre** [comment]
rails are rendering white rectangles between the sleepers (Eisenbahnschwellen). This is hiding the edge below (easier seen when changing the background color.  I don't think transparency between rail tracks should be expected.
