### ISSUE TITLE
Segmentation fault using traci.simulation.executeMove()

### ISSUE THREAD

**Issue by yougeyxt** [eclipse-sumo/sumo#14673]
I am using `traci.simulation.executeMove()` and then `traci.vehicle.moveToXY()` with `keepRoute=3`. Segmentation fault occurs during this process. I am using SUMO 1.19.0 and Linux Ubuntu 20.04.

I tried to use gdb to find the issue and the result is shown in the attached figure. 

Could you please give some suggestions?

Thank you for your help.

![segmentation-fault](https://github.com/eclipse-sumo/sumo/assets/44629219/1a38a2d5-1ee0-4e91-a589-fa2382ae02f7)

**Comment by m-kro** [comment]
You don't need to share your TraCI script. Just [create a log file](https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands) of the used commands like described in the documentation.

**Comment by yougeyxt** [comment]
Thank you for your response. I tried to add `["--log", "traci_log_file.txt"]` to my `traci.start` command. There is a file generated but it is empty, could you please give me some advice? By the way, I have fixed the random seed in the sumocfg using

```
<random_number>
    <seed value="2024"/>
</random_number>
```

**Comment by yougeyxt** [comment]
Thank you for your answer! I have generated a log file but it is larger than 25MB so I cannot directly share it here. Do you prefer that I send it through email or how I can share it with you? BTW, I also generate the fcd_all.xml, will that help and do you want this file also?

**Comment by yougeyxt** [comment]
Please find the data in the zip file. I included 2 scenarios' logs.

[data.zip](https://github.com/eclipse-sumo/sumo/files/14925683/data.zip)

**Comment by m-kro** [comment]
@yougeyxt  Well I still need the referenced scenario - otherwise I cannot replay it...

**Comment by yougeyxt** [comment]
Could you please instruct how to generate the reference scenario? Is the net.xml, route.xml, and sumocfg files you need?

**Comment by yougeyxt** [comment]
@m-kro Please find the files attached. 
[sumo.zip](https://github.com/eclipse-sumo/sumo/files/14934479/sumo.zip)

**Comment by m-kro** [comment]
@yougeyxt  I cannot replicate your problem. After cleaning your TraCI log from calls to getter functions, it crashes at some point where the vehicle mentioned in the setter function **BV_17.1** is not in the network anymore.

**Comment by yougeyxt** [comment]
@m-kro Which TraCI log you are mentioning? In 13-38-45-traci_log_file, it seems the simulation continues to run for a long time after the last setter function with **BV_17.1** (line 49841 in the TraCI log). In 13-38-20-traci_log_file, there is no **BV_17.1** in it.

**Comment by m-kro** [comment]
Actually I had changed very few things in your data which caused the error, sorry. Now I can run the simulation until the end without problems (on Windows though). Still have to try on Linux...

**Comment by yougeyxt** [comment]
No worries, thank you for helping! Please let me know if you need anything from my end.

**Comment by yougeyxt** [comment]
Hi @m-kro, I would like to know if there are any updates on this? Please let me know if you need anything thing from my end. Thanks.

**Comment by m-kro** [comment]
@yougeyxt I tried on Linux as well and could run the simulation until the end. Keep in mind I created a shortened python script out of your TraCI log where all getter functions have been removed (assuming only the setter functions would be needed to trigger the error). 

Your complete TraCI log is too large to run anyway. So if you still need help, please try to get a smaller failing example.

**Comment by yougeyxt** [comment]
Sure, I will get back to you later. Thank you.

**Comment by yougeyxt** [comment]
Hi @m-kro, I found a new failing example as attached, could you please take a look? This example should be much smaller than previous one. BTW, I am now using SUMO 1.20.0 and Linux Ubuntu 20.04. Thank you!
[data-06062024.zip](https://github.com/user-attachments/files/15686928/data-06062024.zip)

**Comment by m-kro** [comment]
Sorry but still I cannot reproduce it neither on Windows nor on Linux Ubuntu 20.04. I can run the TraCI script until the end at simulation time 25.1. That is very unfortunate and I am not sure what to do.

**Comment by namdre** [comment]
@yougeyxt can you check with the latest development version? (https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots)
