### ISSUE TITLE
Clarification on Time-Weighted Average Speed Calculation in "getIntervalMeanSpeed".

### ISSUE THREAD

**Issue by JamesPsh** [eclipse-sumo/sumo#14675]
Hello,

I am currently using the getIntervalMeanSpeed function and would like to clarify how the average speed is calculated in scenarios where the speeds at two different points are measured for varying time intervals.

Based on the documentation, the function calculates the "average (time mean) speed of vehicles during the current interval."
(https://sumo.dlr.de/docs/TraCI/Lane_Area_Detector_Value_Retrieval.html)

For example, if we have two speeds measured as follows:

Speed1 for t1 seconds
Speed2 for t2 seconds
Is the average speed calculated using the time-weighted formula: (speed1*t1 + speed2*t2) / (t1 + t2)? This formula would take into account the duration each speed was maintained, resulting in a time-weighted average.

Could you please confirm if this is the correct interpretation and implementation within the getIntervalMeanSpeed function? If not, could you explain how the average speed should be calculated according to the function's current logic?

Thank you for your assistance.

**Comment by m-kro** [comment]
Your interpretation is correct.
