### ISSUE TITLE
Signalized intersection control with additional detectors

### ISSUE THREAD

**Issue by ufukkirbas** [eclipse-sumo/sumo#14679]
Add your issue description here.
Signalized intersection control with additional detectors

Can continuous control of the detectors be ensured in the simulation environment operating as shown in the figure? For example, by receiving information from the detectors placed in both lanes that the queue length has reached point B, how can the signal system be set up to allow the passage of any vehicle waiting at arm A by turning the signal at arm C to red according to the figure. In other words, after the signalization working system is "actuated", how can the signal phase transition be made at the intersection by receiving information from a detector assigned by ourselves downstream of the intersection. I would be very grateful if you help me.

*If possible, upload an example that shows your problem.*
![1](https://github.com/eclipse-sumo/sumo/assets/153180912/a59eaef4-01dd-4c59-9893-57fe34b19463)
![2](https://github.com/eclipse-sumo/sumo/assets/153180912/1f03fcac-23ef-4133-bfb1-afc45f2cf235)

**SUMO-version:**
SUMO 1.19.0
**operating system:**
Win 11

**Comment by m-kro** [comment]
So you want the traffic light to operate based on outbound detectors. The standard _actuated_ traffic lights in SUMO work with detectors placed upstream of the intersection, but you can define custom signal switching rules (see [doc](https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#type_actuated_with_custom_switching_rules)). There you could define a condition to switch signals if they are occupied for a long time.

**Comment by ufukkirbas** [comment]
I could not solve my problem from the explanation in the place you referenced. Are there any more detailed examples explaining this subject?

**Comment by namdre** [comment]
you can download many examples for customized control here: https://sumo.dlr.de/extractTest.php?path=sumo/tls/actuated/conditions

**Comment by m-kro** [comment]
Here is one which switches phases based on custom conditions: [https://sumo.dlr.de/extractTest.php?path=sumo/tls/actuated/conditions/override_phaseAttrs](https://sumo.dlr.de/extractTest.php?path=sumo/tls/actuated/conditions/override_phaseAttrs)

**Comment by ufukkirbas** [comment]
Thank you very much for your help.

**Comment by ufukkirbas** [comment]
I couldn't run the last example you sent. It gives an error when loading the "input_additional2.add" file into Netedit.

Error: Attribute 'pos' is missing in definition of laneAreaDetector 'AD0.0'.
Error: Attribute 'pos' is missing in definition of laneAreaDetector 'AD0.1'.
Error: Attribute 'pos' is missing in definition of laneAreaDetector 'AD1.0'.
Error: Attribute 'pos' is missing in definition of laneAreaDetector 'AD1.1'.
Error: Attribute 'pos' is missing in definition of laneAreaDetector 'AD2.0'.
Error: Attribute 'pos' is missing in definition of laneAreaDetector 'AD2.1'.
Error: Attribute 'pos' is missing in definition of laneAreaDetector 'AD3.0'.
Error: Attribute 'pos' is missing in definition of laneAreaDetector 'AD3.1'.

**Comment by namdre** [comment]
Not sure which example you mean. The _tls_actuated_conditions_override_phaseAttrs test opens fine in netedit and also doesn't have any laneAreaDetectors in an additional file.

**Comment by ufukkirbas** [comment]
The detectors I am trying to control are downstream. Also, I try to control the detectors I define. Not auto-generated detectors in "actuated" phase arrangement. The file that doesn't work is the "allRed_default" you sent first.

**Comment by namdre** [comment]
the netedit thing is a bug: #14683. You can still run the input with sumo / sumo-gui
