### ISSUE TITLE
How to configure SUMO output content according to requirements

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14689]
Add your issue description here.
Recently, I've been using SUMO to generate 24-hour traffic flow data for a large city and retaining its floating car output data for conducting relevant analyses based on that data.

*If possible, upload an example that shows your problem.*
However, due to its large scale, the floating car data output is typically around 60GB. Parsing the XML file consumes a significant amount of memory. Therefore, I would like to inquire whether there are methods to control the output content. For example, in the image below, I only need the ID of each vehicle at each timestamp along with their x and y attributes：
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/e2dee802-87fe-49d7-aa3a-47bf50f9a1f4)
Thank you！
**SUMO-version:**
SUMO1.19.0
**operating system:**
Windows10

**Comment by namdre** [comment]
set option **-fcd-output.attributes x,y**

**Comment by namdre** [comment]
also see https://sumo.dlr.de/docs/Simulation/Output/FCDOutput.html#filtering_restricting_output

**Comment by nudtdyk** [comment]
> also see https://sumo.dlr.de/docs/Simulation/Output/FCDOutput.html#filtering_restricting_output

Vielen Dank
