### ISSUE TITLE
Removing a stop by traci.vehicle.replaceStop makes vehicle stop permanently and the end of the edge

### ISSUE THREAD

**Issue by oshadajay** [eclipse-sumo/sumo#14696]
I am running a SUMO simulation with vehicles parking randomly on street using TraCI. The logic used is whenever a new vehicle enters the lane and if it is looking for parking, a random on street parking bay get assigned. If no parking bay is available, vehicle would continue without parking. Towards the end of the simulation, vehicles get stuck on the traffic lights and gets teleported for no reason. I have attached the source files to reproduce the issue and kindly let me know if you need any more information. Thank you in advance.

*If possible, upload an example that shows your problem.*
[sumo_issue.zip](https://github.com/eclipse-sumo/sumo/files/14941361/sumo_issue.zip)

**SUMO-version:**
1.19

**operating system:**
Windows

**Comment by oshadajay** [comment]
Further looking into the issue, the vehicles that get teleported are the ones that would continue without parking. The parking stop is removed by using the following code. Am I doing something wrong?

```
traci.vehicle.replaceStop(vehicle, 0, "")
```

**Comment by m-kro** [comment]
You are right that the vehicles which get their stop removed stop at the traffic light although they still have a part of their route to go. Example: vehicle 236.

**Comment by m-kro** [comment]
The BestLanes struct has to be rebuild when the stops change but currently isn't in this case...

**Comment by namdre** [comment]
only missing in the "else" branch of libsumo/Vehicle.cpp:1131 (rerouting triggers update of bestLanes)

**Comment by m-kro** [comment]
@oshadajay You have discovered a bug. Please either try out the [development binaries](https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version) of tomorrow or build now from Github source.

**Comment by oshadajay** [comment]
Sure. Thank you so much for fixing this promptly.
