### ISSUE TITLE
A question about the shape of vehicles in sumilation

### ISSUE THREAD

**Issue by pjj-OSM** [eclipse-sumo/sumo#14695]
In the case, i found the shape of vehicles look like too long or too short in some edges when start simulation? The length of vehicles i set is: **red(private)=5m,green(evehicle)=5m,yellow(bus/coach)=10 or 14**
i need some guidance,thank you~
<img width="749" alt="pic" src="https://github.com/eclipse-sumo/sumo/assets/22164090/93cac4b1-d272-43e4-9c3f-19b95d4797c5">

**Comment by hongyu9876** [comment]
the length of the abnormal lane may have been adjusted manually after the network was generated.
if the length of the lane > length of the edge it belongs, the vehicles on it will be "too short", vice versa.

**Comment by pjj-OSM** [comment]
> the length of the abnormal lane may have been adjusted manually after the network was generated. if the length of the lane > length of the edge it belongs, the vehicles on it will be "too short", vice versa.

I get your mean，i will check the network, thank you~

**Comment by pjj-OSM** [comment]
> the length of the abnormal lane may have been adjusted manually after the network was generated. if the length of the lane > length of the edge it belongs, the vehicles on it will be "too short", vice versa.

The shape of vehicles change will influence the result of simulation？I want to evaluate the trafiic operation by trajectory of vehicles

**Comment by namdre** [comment]
the "visual" shape will not impact simulation. All that matters are the lengths defined in the vType and the lane itself. See https://sumo.dlr.de/docs/Simulation/Distances.html
