### ISSUE TITLE
How to use --fcd-output.params in fcd output when using the command "sumo -c xx.sumocfg"

### ISSUE THREAD

**Issue by pjj-OSM** [eclipse-sumo/sumo#14706]
I need to get more parameters of vehicles after finish simulation,my command is "**sumo -c network.sumocfg --fcd-output trajectory.xml --fcd-output.params ???**", i have get the file of trajectory.xml and some attributes, but i don't know how to use the "--fcd-output.params" to get more other parameters in my file, i need some guidance. 
<img width="737" alt="1" src="https://github.com/eclipse-sumo/sumo/assets/22164090/f22e8a76-0838-43cf-9a2d-b65a604313f6">
<img width="661" alt="2" src="https://github.com/eclipse-sumo/sumo/assets/22164090/7c5d533c-309a-472e-a4e7-9a71ddd6783b">

**Comment by namdre** [comment]
params are something loaded from xml

```
<vehicle ...>
   <param key="..." value="..."/>
</vehicle>
```
or set with `traci.vehicle.setParaemter`
For parameters that are modified during simulation it may be useful to include them in the fcd output by listing the keys.
See also https://sumo.dlr.de/docs/Simulation/GenericParameters.html
