### ISSUE TITLE
EV battery level increases without charging in SUMO

### ISSUE THREAD

**Issue by amininilooffar** [eclipse-sumo/sumo#14704]
Hi, I am currently working with SUMO to make my EV network chargers.
While working with the command traci.vehicle.getParameter(vehicle_id, "device.battery.actualBatteryCapacity", I got that the battery levels are increasing even without being stopped at a charging station. 
What can explain this phenomenon? Do the batteries get charged in slopes?
Thanks for your help in advance.

**Comment by namdre** [comment]
They charge on braking by default (recuperationEfficiency is 0.96 unless reconfigured).
