### ISSUE TITLE
How to make a car to have 10 mph speed lower than speed limit

### ISSUE THREAD

**Issue by harirRzi** [eclipse-sumo/sumo#14708]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
Hello. I am simulating cars behaviors in Sumo. I want to simulate the behavior of one of the cars to be 10 miles per hour or nearly 20 km/h to be lower than speed limit of the road. I didn't specify any speed limit for the road but I want to know to address this, if  I need to add speedFactor=0.2 attribute for that specific car or any other attribute?

**Comment by namdre** [comment]
Either: 
- set a low speedFactor for the vehicle (0.5 will have it drive at 50% of the speed limit but you need to know the speed limit in advance to achieve an exact 10mph reduction)
- set a low maxSpeed in the vehicle vType to set a hard boundary (regardless of road speed limit)
- use traci to determine the current road speed limit and then call traci.vehicle.setSpeedFactor at runtime with the appropriate value (must be repeated every time the speed limit changes).

**Comment by harirRzi** [comment]
Thank you for your response. Here is what I defined for the type of car, but I don't see that speedFactor changed the behavior of the car that I  expected:

```
   <vType id="x_0" vClass="passenger" speedFactor="0.5" sigma="0.8" accel="10.5" decel="9.5" maxSpeed="11.11" speedDev="0.1" lcPushy="1" lcSigma="0.9"/>
   <vType id="x_1" vClass="passenger" speedFactor="0.5" sigma="0.9" accel="8" decel="10"  maxSpeed="13.88" speedDev="0.2" speedFactor="0.5" lcPushy="1" lcSigma="0.9"/>
```

**Comment by namdre** [comment]
the input is invalid (speedFactor defined twice). You should be getting an error when loading this.
