### ISSUE TITLE
routing cost vs travel times

### ISSUE THREAD

**Issue by ambuehll** [eclipse-sumo/sumo#14707]
Hello again, 

I was investigating some routing issue in one of our networks. I came across an unexpected behavior. As a minimum example, I run 20+1 vehicles with the same OD. 20 vehicles are freely routed according to the costs found by astar (or dijkstra). 1 vehicle has a "via". 

**Free-flow case:**
The vehicle 173504B with the "via" runs along a route, which has longer travel time, but smaller routing costs. I am under the assumption that I turned off all the weighing and stochasticity, so I cannot really explain this. 

I am not sure I understand how the costs can be lower than the ones found for the other 20 routes, which have no "via" constaint. See below for example routes and their route costs. 

(I can also provide a (very) large scenario, where the opposite is the case in a congested regime)

<img width="1120" alt="image" src="https://github.com/eclipse-sumo/sumo/assets/48930860/608400c1-a420-4422-b3e0-3c7ae66003e3">

    <vehicle id="17350416" type="car" depart="250.00" departLane="0" departSpeed="10.0385" fromTaz="grid-X137Y50" toTaz="destination-X221Y184" speedFactor="0.8500" arrival="1905.00" routeLength="24012.21">
        <routeDistribution>
            <route cost="1324.26" savings="0.00" replacedOnEdge="526016615#0" replacedOnIndex="48" reason="device.rerouting" replacedAtTime="900.00" probability="0" edges="-438456377#0 374554762#1 5053150 17123304#2-AddedOnRampEdge 17123304#2 45132149 45132149-AddedOffRampEdge 183716942#1 183716942#2-AddedOnRampEdge 183716942#2 183716942#2-AddedOffRampEdge 183716942#3 4485182 1177023264 1177023504 537013686 35359564#0 35359564#0-AddedOffRampEdge 35359564#1 38867855 32278541 537948562 44774431 656681144 210731931#0 210731931#1 548701320 39013712#2 39013712#3 39013712#5 39013712#6 39013712#7 39013712#8 39013712#9 39013712#10 70732841#0 70732841#1 603349808#0 70748294 817867131 188708013#0 188708013#1 817867132#0 15675937#0 15675937#1 548529066#0 526016652 1165309879#0 526016615#0 526016615#1 146977155#0 146977155#1 146977155#2 146977155#3 33693799#0 33693780#0 33693780#1 33693780#2 543888804#0 543888805 332455374#0 332455374#1 548370032 4398951 92142139 92142136 596103315#0 27331400#0 27331400#1 35164367 8139899#0 8139899#1 8436580 550657242 188867142#0 381201436#0 381223036#0 381223036#1 1055792179#0 90062590#2 90004143 90062603-AddedOnRampEdge 90062603 90062603-AddedOffRampEdge 257237954 50638674 257237950 32278429 32278429-AddedOffRampEdge 137477254#1 137477254#2-AddedOnRampEdge 137477254#2 10621364 194211724 194211723 12877351 23637397 23637603 23649359 31007519 43945815 914309457-AddedOnRampEdge 914309457 255102674 15708870 4554725#1-AddedOnRampEdge 4554725#1 255108143#0 255108143#1-AddedOnRampEdge 255108143#1 54264342 54264342-AddedOffRampEdge 1239210516 183836684 1239210515" routeLength="23554.39"/>
            <route cost="850.05" savings="100701.13" replacedOnEdge="596103315#0" replacedOnIndex="68" reason="device.rerouting" replacedAtTime="1080.00" probability="0" edges="-438456377#0 374554762#1 5053150 17123304#2-AddedOnRampEdge 17123304#2 45132149 45132149-AddedOffRampEdge 183716942#1 183716942#2-AddedOnRampEdge 183716942#2 183716942#2-AddedOffRampEdge 183716942#3 4485182 1177023264 1177023504 537013686 35359564#0 35359564#0-AddedOffRampEdge 35359564#1 38867855 32278541 537948562 44774431 656681144 210731931#0 210731931#1 548701320 39013712#2 39013712#3 39013712#5 39013712#6 39013712#7 39013712#8 39013712#9 39013712#10 70732841#0 70732841#1 603349808#0 70748294 817867131 188708013#0 188708013#1 817867132#0 15675937#0 15675937#1 548529066#0 526016652 1165309879#0 526016615#0 526016615#1 146977155#0 146977155#1 146977155#2 146977155#3 33693799#0 33694486#0 1051820108 33694459#2 248669676 -248669678#0 543888806#1 248669682#1 332455374#0 332455374#1 548370032 4398951 92142139 92142136 596103315#0 27331400#0 27331400#1 35164367 8139899#0 8139899#1 8436580 550657242 188867142#0 381201436#0 381223036#0 381223036#1 1055792179#0 90062590#2 90004143 90062603-AddedOnRampEdge 90062603 90062603-AddedOffRampEdge 257237954 50638674 257237950 32278429 32278429-AddedOffRampEdge 137477254#1 137477254#2-AddedOnRampEdge 137477254#2 10621364 194211724 194211723 12877351 23637397 23637603 23649359 31007519 43945815 914309457-AddedOnRampEdge 914309457 255102674 15708870 4554725#1-AddedOnRampEdge 4554725#1 255108143#0 255108143#1-AddedOnRampEdge 255108143#1 54264342 54264342-AddedOffRampEdge 1239210516 183836684 1239210515" routeLength="23944.19"/>
            <route cost="745.50" savings="6.09" replacedOnEdge="32278429" replacedOnIndex="93" reason="device.rerouting" replacedAtTime="1440.00" probability="0" edges="-438456377#0 374554762#1 5053150 17123304#2-AddedOnRampEdge 17123304#2 45132149 45132149-AddedOffRampEdge 183716942#1 183716942#2-AddedOnRampEdge 183716942#2 183716942#2-AddedOffRampEdge 183716942#3 4485182 1177023264 1177023504 537013686 35359564#0 35359564#0-AddedOffRampEdge 35359564#1 38867855 32278541 537948562 44774431 656681144 210731931#0 210731931#1 548701320 39013712#2 39013712#3 39013712#5 39013712#6 39013712#7 39013712#8 39013712#9 39013712#10 70732841#0 70732841#1 603349808#0 70748294 817867131 188708013#0 188708013#1 817867132#0 15675937#0 15675937#1 548529066#0 526016652 1165309879#0 526016615#0 526016615#1 146977155#0 146977155#1 146977155#2 146977155#3 33693799#0 33694486#0 1051820108 33694459#2 248669676 -248669678#0 543888806#1 248669682#1 332455374#0 332455374#1 548370032 4398951 92142139 92142136 596103315#0 27331400#0 27331400#1 35164367 8139899#0 8139899#1 120613506#0 120613506#1 24477759#1 24477759#2 4748727 593076012 593076013#0 -577791926#1 -492432415#1 -492432415#0 -90062599 90062590#2 90004143 90062603-AddedOnRampEdge 90062603 90062603-AddedOffRampEdge 257237954 50638674 257237950 32278429 32278429-AddedOffRampEdge 137477254#1 137477254#2-AddedOnRampEdge 137477254#2 10621364 194211724 194211723 12877351 23637397 23637603 23649359 31007519 43945815 914309457-AddedOnRampEdge 914309457 255102674 15708870 4554725#1-AddedOnRampEdge 4554725#1 255108143#0 255108143#1-AddedOnRampEdge 255108143#1 54264342 54264342-AddedOffRampEdge 1239210516 183836684 1239210515" routeLength="24009.44"/>
            <route cost="457.35" savings="0.32" edges="-438456377#0 374554762#1 5053150 17123304#2-AddedOnRampEdge 17123304#2 45132149 45132149-AddedOffRampEdge 183716942#1 183716942#2-AddedOnRampEdge 183716942#2 183716942#2-AddedOffRampEdge 183716942#3 4485182 1177023264 1177023504 537013686 35359564#0 35359564#0-AddedOffRampEdge 35359564#1 38867855 32278541 537948562 44774431 656681144 210731931#0 210731931#1 548701320 39013712#2 39013712#3 39013712#5 39013712#6 39013712#7 39013712#8 39013712#9 39013712#10 70732841#0 70732841#1 603349808#0 70748294 817867131 188708013#0 188708013#1 817867132#0 15675937#0 15675937#1 548529066#0 526016652 1165309879#0 526016615#0 526016615#1 146977155#0 146977155#1 146977155#2 146977155#3 33693799#0 33694486#0 1051820108 33694459#2 248669676 -248669678#0 543888806#1 248669682#1 332455374#0 332455374#1 548370032 4398951 92142139 92142136 596103315#0 27331400#0 27331400#1 35164367 8139899#0 8139899#1 120613506#0 120613506#1 24477759#1 24477759#2 4748727 593076012 593076013#0 -577791926#1 -492432415#1 -492432415#0 -90062599 90062590#2 90004143 90062603-AddedOnRampEdge 90062603 90062603-AddedOffRampEdge 257237954 50638674 257237950 32278429 32278429-AddedOffRampEdge 137477254#1 137477254#2-AddedOnRampEdge 137477254#2 10621364 194211724 194211723 12877351 23637397 9646839 144008695 255102673 31007519 43945815 914309457-AddedOnRampEdge 914309457 255102674 15708870 4554725#1-AddedOnRampEdge 4554725#1 255108143#0 255108143#1-AddedOnRampEdge 255108143#1 54264342 54264342-AddedOffRampEdge 1239210516 183836684 1239210515" exitTimes="258.00 259.00 278.00 282.00 337.00 345.00 349.00 372.00 376.00 380.00 385.00 408.00 454.00 456.00 463.00 515.00 516.00 522.00 527.00 568.00 598.00 604.00 616.00 643.00 657.00 661.00 720.00 722.00 723.00 724.00 725.00 726.00 727.00 728.00 729.00 731.00 732.00 733.00 768.00 777.00 781.00 799.00 801.00 802.00 823.00 864.00 888.00 897.00 901.00 903.00 904.00 904.00 905.00 906.00 914.00 936.00 943.00 951.00 961.00 970.00 977.00 1008.00 1017.00 1027.00 1032.00 1037.00 1038.00 1072.00 1089.00 1090.00 1115.00 1120.00 1122.00 1136.00 1140.00 1145.00 1154.00 1161.00 1163.00 1176.00 1200.00 1205.00 1209.00 1212.00 1248.00 1286.00 1288.00 1295.00 1385.00 1391.00 1410.00 1424.00 1432.00 1448.00 1455.00 1482.00 1490.00 1492.00 1513.00 1553.00 1562.00 1567.00 1573.00 1601.00 1613.00 1614.00 1651.00 1693.00 1697.00 1768.00 1773.00 1785.00 1789.00 1792.00 1794.00 1799.00 1820.00 1860.00 1863.00 1876.00 1889.00 1905.00"/>
        </routeDistribution>
    </vehicle>

<img width="1093" alt="image" src="https://github.com/eclipse-sumo/sumo/assets/48930860/4e87dfce-4c89-4530-82fd-e27237d3c3f6">

    <vehicle id="173504B" type="car" depart="190.00" departLane="0" departSpeed="10.0385" fromTaz="grid-X137Y50" toTaz="destination-X221Y184" speedFactor="0.8500" arrival="1842.00" routeLength="24007.65">
        <routeDistribution>
            <route cost="1441.66" savings="0.00" replacedOnEdge="10621364" replacedOnIndex="110" reason="device.rerouting" replacedAtTime="1440.00" probability="0" edges="-438456377#0 374554762#1 5053150 17123304#2-AddedOnRampEdge 17123304#2 45132149 45132149-AddedOffRampEdge 183716942#1 183716942#2-AddedOnRampEdge 183716942#2 183716942#2-AddedOffRampEdge 183716942#3 4485182 1177023264 1177023504 537013686 35359564#0 35359564#0-AddedOffRampEdge 35359564#1 38867855 32278541 537948562 44774431 656681144 210731931#0 210731931#1 548701320 39013712#2 39013712#3 39013712#5 39013712#6 39013712#7 39013712#8 39013712#9 39013712#10 32391480#0 70748324#0 464916844#0 464916844#1 548701322#0 284105543#0 73223940#0 382059941#2 488736536#0 488736536#1 39013715#0 82956882 147161801 284686657 147161798#0 70748311#0 330403834 179097891#0 179097891#1 179097891#2 39013717#0 39013717#1 39013717#2 147161802 147390907 4730716 1007827874#0 147164232#0 41221165 170032532#1 170032532#2 71160126#1 71160126#2 71160126#3 71160126#4 4730818 38338813#1 365613466 377211841 377211844#0 377211844#1 550657243#0 550657243#1 522094980 39013721#0 377211842 477680607 576685213 576685216 377211840 377438208 377438209 371730209 362892928 90524272 362892924#2 358991826#0 358991826#1 358991826#2 461214214 381196328 380779297 720178332 27411573#1 51732639 257237959 1121941122 174384439 10621421 38093975 32278429 32278429-AddedOffRampEdge 137477254#1 137477254#2-AddedOnRampEdge 137477254#2 10621364 194211724 194211723 12877351 23637397 23637603 23649359 31007519 43945815 914309457-AddedOnRampEdge 914309457 255102674 15708870 4554725#1-AddedOnRampEdge 4554725#1 255108143#0 255108143#1-AddedOnRampEdge 255108143#1 54264342 54264342-AddedOffRampEdge 1239210516 183836684 1239210515" routeLength="24004.88"/>
            <route cost="400.04" savings="0.32" edges="-438456377#0 374554762#1 5053150 17123304#2-AddedOnRampEdge 17123304#2 45132149 45132149-AddedOffRampEdge 183716942#1 183716942#2-AddedOnRampEdge 183716942#2 183716942#2-AddedOffRampEdge 183716942#3 4485182 1177023264 1177023504 537013686 35359564#0 35359564#0-AddedOffRampEdge 35359564#1 38867855 32278541 537948562 44774431 656681144 210731931#0 210731931#1 548701320 39013712#2 39013712#3 39013712#5 39013712#6 39013712#7 39013712#8 39013712#9 39013712#10 32391480#0 70748324#0 464916844#0 464916844#1 548701322#0 284105543#0 73223940#0 382059941#2 488736536#0 488736536#1 39013715#0 82956882 147161801 284686657 147161798#0 70748311#0 330403834 179097891#0 179097891#1 179097891#2 39013717#0 39013717#1 39013717#2 147161802 147390907 4730716 1007827874#0 147164232#0 41221165 170032532#1 170032532#2 71160126#1 71160126#2 71160126#3 71160126#4 4730818 38338813#1 365613466 377211841 377211844#0 377211844#1 550657243#0 550657243#1 522094980 39013721#0 377211842 477680607 576685213 576685216 377211840 377438208 377438209 371730209 362892928 90524272 362892924#2 358991826#0 358991826#1 358991826#2 461214214 381196328 380779297 720178332 27411573#1 51732639 257237959 1121941122 174384439 10621421 38093975 32278429 32278429-AddedOffRampEdge 137477254#1 137477254#2-AddedOnRampEdge 137477254#2 10621364 194211724 194211723 12877351 23637397 9646839 144008695 255102673 31007519 43945815 914309457-AddedOnRampEdge 914309457 255102674 15708870 4554725#1-AddedOnRampEdge 4554725#1 255108143#0 255108143#1-AddedOnRampEdge 255108143#1 54264342 54264342-AddedOffRampEdge 1239210516 183836684 1239210515" exitTimes="198.00 199.00 218.00 223.00 278.00 285.00 289.00 312.00 317.00 320.00 325.00 348.00 394.00 396.00 404.00 455.00 457.00 462.00 468.00 508.00 538.00 545.00 556.00 583.00 596.00 601.00 630.00 632.00 633.00 634.00 635.00 636.00 637.00 638.00 639.00 642.00 647.00 649.00 653.00 672.00 682.00 688.00 692.00 700.00 720.00 727.00 733.00 735.00 742.00 768.00 776.00 780.00 788.00 790.00 816.00 818.00 820.00 822.00 836.00 849.00 864.00 874.00 885.00 896.00 912.00 917.00 922.00 929.00 930.00 932.00 952.00 956.00 958.00 968.00 984.00 987.00 989.00 989.00 991.00 1008.00 1015.00 1025.00 1060.00 1070.00 1082.00 1097.00 1128.00 1138.00 1146.00 1161.00 1169.00 1187.00 1194.00 1195.00 1212.00 1231.00 1240.00 1247.00 1267.00 1300.00 1313.00 1324.00 1346.00 1352.00 1369.00 1386.00 1394.00 1420.00 1428.00 1430.00 1452.00 1492.00 1500.00 1505.00 1511.00 1539.00 1551.00 1552.00 1588.00 1631.00 1635.00 1706.00 1711.00 1722.00 1727.00 1730.00 1732.00 1736.00 1757.00 1797.00 1801.00 1813.00 1827.00 1842.00"/>
        </routeDistribution>
    </vehicle>

**SUMO-version:**1.19
sumo-gui -c sumo_small.sumocfg --device.rerouting.threads 1 --begin 0 --end 3600 -r small_route_snip.rou.xml
[files](https://drive.google.com/file/d/1iiRYv0Q52_Hm9EH5UCZnvClUrEcMdZp7/view?usp=share_link)

As always, many thanks! 
Lukas

**Comment by namdre** [comment]
I think the cost output is misleading: it always shows the cost for the remaining part of the route at replacement time so any values after the first cost depend on the (practically random) driving progress until replacement time.
The first cost of 1441.66 for the 'B' vehicle is higher than 1324.26 for the non-via vehicles.

I'm not sure the current cost output is useful. at least the actual costs up to the replacement point should be given to avoid misunderstanding. 

comments @behrisch ?

**Comment by ambuehll** [comment]
ok, that makes things clearer. thank you!

In the congested case, every single car takes a route similar to the red one. all cars end up with a higher overall travel time than the "B" vehicle, which is again forced with a via. I understand that the route cost at the very beginning is higher for the "B" vehicle and that potentially this changes while the vehicles are routed. And thus, no vehicle ever takes the B route even though it's faster in the end. I assume that's inherent to the online router. It just surprised me that no vehicle ever took the yellow route.

    <vehicle id="173504" type="car" depart="28666.00" departLane="free" departSpeed="8.0115" fromTaz="grid-X137Y50" toTaz="destination-X221Y184" speedFactor="0.8500" arrival="30203.00" routeLength="23624.74">
        <routeDistribution>
            <route cost="1406.73" savings="0.00" replacedOnEdge="32278541" replacedOnIndex="20" reason="device.rerouting" replacedAtTime="28980.00" probability="0" edges="-438456377#0 374554762#1 5053150 17123304#2-AddedOnRampEdge 17123304#2 45132149 45132149-AddedOffRampEdge 183716942#1 183716942#2-AddedOnRampEdge 183716942#2 183716942#2-AddedOffRampEdge 183716942#3 4485182 1177023264 1177023504 537013686 35359564#0 35359564#0-AddedOffRampEdge 35359564#1 38867855 32278541 537948562 44774431 656681144 210731931#0 210731931#1 548701320 39013712#2 39013712#3 39013712#5 39013712#6 39013712#7 39013712#8 39013712#9 39013712#10 70732841#0 70732841#1 603349808#0 70748294 817867131 188708013#0 188708013#1 817867132#0 15675937#0 15675937#1 548529066#0 526016643 -536841066 -28630236#1 526016665#0 4533226#0 699663268#1 4743830#0 4743830#1 -1111971585#2 -1169825568 -1169825566 -1169825567 -1169825565 -527458585#1 -1169825562#2 -1169825563 -1169825564 -4533227#2 31261713#0 4592591#0 31261712#0 31261712#3 31261712#5 429114142 656591301 21020552 50480403#1 50480403#2 50480403#3 50480403#4 50480403#5 50480417#0 171993690 27410389#0 90004156 455329864#0 27410413#0 90004164 90062603-AddedOnRampEdge 90062603 90062603-AddedOffRampEdge 257237954 50638674 257237950 32278429 32278429-AddedOffRampEdge 137477254#1 137477254#2-AddedOnRampEdge 137477254#2 10621364 194211724 194211723 12877351 23637397 23637603 23649359 31007519 43945815 914309457-AddedOnRampEdge 914309457 255102674 15708870 4554725#1-AddedOnRampEdge 4554725#1 255108143#0 255108143#1-AddedOnRampEdge 255108143#1 54264342 54264342-AddedOffRampEdge 1239210516 183836684 1239210515" routeLength="23531.55"/>
            <route cost="1095.94" savings="11.48" replacedOnEdge="33693780#0" replacedOnIndex="55" reason="device.rerouting" replacedAtTime="29340.00" probability="0" edges="-438456377#0 374554762#1 5053150 17123304#2-AddedOnRampEdge 17123304#2 45132149 45132149-AddedOffRampEdge 183716942#1 183716942#2-AddedOnRampEdge 183716942#2 183716942#2-AddedOffRampEdge 183716942#3 4485182 1177023264 1177023504 537013686 35359564#0 35359564#0-AddedOffRampEdge 35359564#1 38867855 32278541 537948562 44774431 656681144 210731931#0 210731931#1 548701320 39013712#2 39013712#3 39013712#5 39013712#6 39013712#7 39013712#8 39013712#9 39013712#10 70732841#0 70732841#1 603349808#0 70748294 817867131 188708013#0 188708013#1 817867132#0 15675937#0 15675937#1 548529066#0 526016652 1165309879#0 526016615#0 526016615#1 146977155#0 146977155#1 146977155#2 146977155#3 33693799#0 33693780#0 33693780#1 33693780#2 543888804#0 543888805 332455374#0 332455374#1 548370032 4398951 92142139 92142136 596103315#0 27331400#0 27331400#1 35164367 8139899#0 8139899#1 8436580 550657242 188867142#0 381201436#0 381223036#0 381223036#1 1055792179#0 90062590#2 90004143 90062603-AddedOnRampEdge 90062603 90062603-AddedOffRampEdge 257237954 50638674 257237950 32278429 32278429-AddedOffRampEdge 137477254#1 137477254#2-AddedOnRampEdge 137477254#2 10621364 194211724 194211723 12877351 23637397 23637603 23649359 31007519 43945815 914309457-AddedOnRampEdge 914309457 255102674 15708870 4554725#1-AddedOnRampEdge 4554725#1 255108143#0 255108143#1-AddedOnRampEdge 255108143#1 54264342 54264342-AddedOffRampEdge 1239210516 183836684 1239210515" routeLength="23559.49"/>
            <route cost="840.17" savings="0.97" edges="-438456377#0 374554762#1 5053150 17123304#2-AddedOnRampEdge 17123304#2 45132149 45132149-AddedOffRampEdge 183716942#1 183716942#2-AddedOnRampEdge 183716942#2 183716942#2-AddedOffRampEdge 183716942#3 4485182 1177023264 1177023504 537013686 35359564#0 35359564#0-AddedOffRampEdge 35359564#1 38867855 32278541 537948562 44774431 656681144 210731931#0 210731931#1 548701320 39013712#2 39013712#3 39013712#5 39013712#6 39013712#7 39013712#8 39013712#9 39013712#10 70732841#0 70732841#1 603349808#0 70748294 817867131 188708013#0 188708013#1 817867132#0 15675937#0 15675937#1 548529066#0 526016652 1165309879#0 526016615#0 526016615#1 146977155#0 146977155#1 146977155#2 146977155#3 33693799#0 33693780#0 33693780#1 33693780#2 543888804#0 543888805 332455374#0 332455374#1 548370032 4398951 92142139 92142136 596103315#0 27331400#0 27331400#1 35164367 8139899#0 8139899#1 120613506#0 120613506#1 24477759#1 24477759#2 4748727 593076012 593076013#0 -577791926#1 -492432415#1 -492432415#0 -90062599 90062590#2 90004143 90062603-AddedOnRampEdge 90062603 90062603-AddedOffRampEdge 257237954 50638674 257237950 32278429 32278429-AddedOffRampEdge 137477254#1 137477254#2-AddedOnRampEdge 137477254#2 10621364 194211724 194211723 12877351 23637397 23637603 23649359 31007519 43945815 914309457-AddedOnRampEdge 914309457 255102674 15708870 4554725#1-AddedOnRampEdge 4554725#1 255108143#0 255108143#1-AddedOnRampEdge 255108143#1 54264342 54264342-AddedOffRampEdge 1239210516 183836684 1239210515" exitTimes="28676.00 28678.00 28695.00 28699.00 28753.00 28760.00 28764.00 28786.00 28791.00 28794.00 28798.00 28821.00 28866.00 28868.00 28875.00 28925.00 28927.00 28932.00 28937.00 28976.00 29006.00 29012.00 29023.00 29049.00 29062.00 29067.00 29093.00 29094.00 29095.00 29096.00 29097.00 29098.00 29099.00 29100.00 29101.00 29103.00 29104.00 29105.00 29123.00 29129.00 29134.00 29150.00 29156.00 29157.00 29226.00 29287.00 29303.00 29310.00 29314.00 29316.00 29318.00 29318.00 29321.00 29321.00 29332.00 29341.00 29343.00 29347.00 29350.00 29403.00 29410.00 29419.00 29424.00 29428.00 29429.00 29444.00 29458.00 29460.00 29484.00 29489.00 29490.00 29503.00 29505.00 29509.00 29518.00 29525.00 29526.00 29538.00 29550.00 29554.00 29558.00 29559.00 29571.00 29603.00 29605.00 29611.00 29698.00 29704.00 29722.00 29735.00 29743.00 29758.00 29765.00 29790.00 29798.00 29800.00 29820.00 29858.00 29867.00 29871.00 29878.00 29905.00 29917.00 29956.00 29997.00 30001.00 30070.00 30075.00 30086.00 30091.00 30094.00 30096.00 30100.00 30120.00 30159.00 30163.00 30175.00 30188.00 30203.00"/>
        </routeDistribution>
    </vehicle>

    <vehicle id="173504B" type="car" depart="28666.00" departLane="free" departSpeed="6.6147" fromTaz="grid-X137Y50" toTaz="destination-X221Y184" speedFactor="0.8500" arrival="30219.00" routeLength="24009.98">
        <routeDistribution>
            <route cost="1575.91" savings="0.00" replacedOnEdge="38867855" replacedOnIndex="19" reason="device.rerouting" replacedAtTime="28980.00" probability="0" edges="-438456377#0 374554762#1 5053150 17123304#2-AddedOnRampEdge 17123304#2 45132149 45132149-AddedOffRampEdge 183716942#1 183716942#2-AddedOnRampEdge 183716942#2 183716942#2-AddedOffRampEdge 183716942#3 4485182 1177023264 1177023504 537013686 35359564#0 35359564#0-AddedOffRampEdge 35359564#1 38867855 32278541 537948562 44774431 656681144 210731931#0 210731931#1 548701320 39013712#2 39013712#3 39013712#5 39013712#6 39013712#7 39013712#8 39013712#9 39013712#10 32391480#0 70748324#0 464916844#0 464916844#1 548701322#0 284105543#0 73223940#0 382059941#2 488736536#0 488736536#1 39013715#0 82956882 147161801 284686657 147161798#0 70748311#0 330403834 179097891#0 179097891#1 179097891#2 39013717#0 39013717#1 39013717#2 147161802 147390907 4730716 1007827874#0 147164232#0 41221165 170032532#1 170032532#2 71160126#1 71160126#2 71160126#3 71160126#4 4730818 38338813#1 365613466 377211841 377211844#0 377211844#1 550657243#0 550657243#1 522094980 39013721#0 377211842 477680607 576685213 576685216 377211840 377438208 377438209 371730209 362892928 90524272 362892924#2 358991826#0 358991826#1 358991826#2 461214214 381196328 380779297 720178332 27411573#1 51732639 257237959 1121941122 174384439 10621421 38093975 32278429 32278429-AddedOffRampEdge 137477254#1 137477254#2-AddedOnRampEdge 137477254#2 10621364 194211724 194211723 12877351 23637397 23637603 23649359 31007519 43945815 914309457-AddedOnRampEdge 914309457 255102674 15708870 4554725#1-AddedOnRampEdge 4554725#1 255108143#0 255108143#1-AddedOnRampEdge 255108143#1 54264342 54264342-AddedOffRampEdge 1239210516 183836684 1239210515" routeLength="24009.98"/>
            <route cost="1317.99" savings="4.10" replacedOnEdge="71160126#1" replacedOnIndex="66" reason="device.rerouting" replacedAtTime="29340.00" probability="0" edges="-438456377#0 374554762#1 5053150 17123304#2-AddedOnRampEdge 17123304#2 45132149 45132149-AddedOffRampEdge 183716942#1 183716942#2-AddedOnRampEdge 183716942#2 183716942#2-AddedOffRampEdge 183716942#3 4485182 1177023264 1177023504 537013686 35359564#0 35359564#0-AddedOffRampEdge 35359564#1 38867855 32278541 537948562 44774431 656681144 210731931#0 210731931#1 548701320 39013712#2 39013712#3 39013712#5 39013712#6 39013712#7 39013712#8 39013712#9 39013712#10 32391480#0 70748324#0 464916844#0 464916844#1 548701322#0 284105543#0 73223940#0 382059941#2 488736536#0 488736536#1 39013715#0 82956882 147161801 284686657 147161798#0 70748311#0 330403834 179097891#0 179097891#1 179097891#2 39013717#0 39013717#1 39013717#2 147161802 147390907 4730716 1007827874#0 147164232#0 41221165 170032532#1 170032532#2 71160126#1 71160126#2 71160126#3 71160126#4 4730818 38338813#1 365613466 377211841 377211844#0 377211844#1 550657243#0 550657243#1 522094980 39013721#0 377211842 477680607 576685213 576685216 377211840 377438208 377438209 371730209 362892928 90524272 362892924#2 358991826#0 358991826#1 358991826#2 461214214 381196328 380779297 720178332 27411573#1 51732639 257237959 1121941122 174384439 38093976 506747349 51343841#0 51343841#2 51470080 137477254#2-AddedOnRampEdge 137477254#2 10621364 194211724 194211723 12877351 23637397 23637603 23649359 31007519 43945815 914309457-AddedOnRampEdge 914309457 255102674 15708870 4554725#1-AddedOnRampEdge 4554725#1 255108143#0 255108143#1-AddedOnRampEdge 255108143#1 54264342 54264342-AddedOffRampEdge 1239210516 183836684 1239210515" routeLength="24018.92"/>
            <route cost="857.90" savings="76.31" edges="-438456377#0 374554762#1 5053150 17123304#2-AddedOnRampEdge 17123304#2 45132149 45132149-AddedOffRampEdge 183716942#1 183716942#2-AddedOnRampEdge 183716942#2 183716942#2-AddedOffRampEdge 183716942#3 4485182 1177023264 1177023504 537013686 35359564#0 35359564#0-AddedOffRampEdge 35359564#1 38867855 32278541 537948562 44774431 656681144 210731931#0 210731931#1 548701320 39013712#2 39013712#3 39013712#5 39013712#6 39013712#7 39013712#8 39013712#9 39013712#10 32391480#0 70748324#0 464916844#0 464916844#1 548701322#0 284105543#0 73223940#0 382059941#2 488736536#0 488736536#1 39013715#0 82956882 147161801 284686657 147161798#0 70748311#0 330403834 179097891#0 179097891#1 179097891#2 39013717#0 39013717#1 39013717#2 147161802 147390907 4730716 1007827874#0 147164232#0 41221165 170032532#1 170032532#2 71160126#1 71160126#2 71160126#3 71160126#4 4730818 38338813#1 365613466 377211841 377211844#0 377211844#1 550657243#0 550657243#1 522094980 39013721#0 377211842 477680607 576685213 576685216 377211840 377438208 377438209 371730209 362892928 90524272 362892924#2 358991826#0 358991826#1 358991826#2 461214214 381196328 380779297 720178332 27411573#1 51732639 257237959 1121941122 174384439 10621421 38093975 32278429 32278429-AddedOffRampEdge 137477254#1 137477254#2-AddedOnRampEdge 137477254#2 10621364 194211724 194211723 12877351 23637397 23637603 23649359 31007519 43945815 914309457-AddedOnRampEdge 914309457 255102674 15708870 4554725#1-AddedOnRampEdge 4554725#1 255108143#0 255108143#1-AddedOnRampEdge 255108143#1 54264342 54264342-AddedOffRampEdge 1239210516 183836684 1239210515" exitTimes="28682.00 28683.00 28701.00 28704.00 28758.00 28765.00 28769.00 28792.00 28796.00 28800.00 28804.00 28826.00 28871.00 28873.00 28880.00 28930.00 28932.00 28937.00 28942.00 28981.00 29010.00 29016.00 29027.00 29053.00 29066.00 29072.00 29098.00 29099.00 29099.00 29100.00 29101.00 29102.00 29103.00 29104.00 29105.00 29111.00 29115.00 29118.00 29121.00 29130.00 29138.00 29150.00 29153.00 29161.00 29167.00 29172.00 29178.00 29180.00 29186.00 29198.00 29204.00 29208.00 29216.00 29223.00 29230.00 29231.00 29232.00 29234.00 29247.00 29259.00 29276.00 29285.00 29301.00 29311.00 29322.00 29339.00 29344.00 29350.00 29351.00 29353.00 29371.00 29377.00 29379.00 29388.00 29400.00 29401.00 29403.00 29403.00 29405.00 29414.00 29419.00 29428.00 29461.00 29470.00 29481.00 29496.00 29514.00 29522.00 29529.00 29543.00 29551.00 29567.00 29574.00 29575.00 29591.00 29609.00 29617.00 29624.00 29642.00 29673.00 29685.00 29696.00 29717.00 29723.00 29762.00 29778.00 29785.00 29810.00 29817.00 29820.00 29840.00 29878.00 29886.00 29891.00 29896.00 29923.00 29936.00 29971.00 30012.00 30017.00 30086.00 30090.00 30102.00 30106.00 30109.00 30111.00 30115.00 30136.00 30175.00 30178.00 30190.00 30203.00 30219.00"/>
        </routeDistribution>
    </vehicle>

**Comment by namdre** [comment]
The online router has many problems (not being able to see into the future is probably the biggest).
