### ISSUE TITLE
How to prevent speed value to be 0 for some of cars in the output file

### ISSUE THREAD

**Issue by harirRzi** [eclipse-sumo/sumo#14712]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
I am simulation some normal behavior of cars. So  I defined the following as flow:

```
<vType id="Normal-car-1" vClass="passenger" length="5" accel="3" decel="4.5" sigma="0.5" minGap="1.5" maxSpeed="24.99" speedDev="0.1" />  <!--color="255,3,30"/>-->

   <vType id="Normal-car-2" vClass="passenger" length="5" accel="2.8" decel="4.5" sigma="0.5" minGap="1.0" maxSpeed="23.61" speedDev="0.1"/>
```
   
   I used the following command to produce the data simulation

`sumo -c ~/SUMOTutorials/drunk-detection/square-street/new-routes-file/routes-jadid-drunk-aggressive/demo.sumocfg --fcd-output ~/SUMOTutorials/drunk-detection/square-street/new-routes-file/routes-jadid-drunk-aggressive/sumoTracefcdfile.xml --fcd-output.acceleration`

In the output file I sometimes see the @speed column for any car from the above flow are 0, I appreciate, if anyone can tell me how can I prevent 0 in @speed for each car?

**Comment by namdre** [comment]
cars with speed 0 are a normal occurence in traffic (i.e. at intersections or in a traffic jam). You can use sumo-gui to unterstand why cars are waiting. Post more details if you think the behavior is noteworthy.

**Comment by behrisch** [comment]
If you have more information on the issue please leave another comment
