### ISSUE TITLE
sumo junction forced right turn

### ISSUE THREAD

**Issue by han-zhang-baba** [eclipse-sumo/sumo#14716]
In the sumo junction simulation, I have a lane connection which connect two lanes, but sumo forced vehciles to turn right. But I want vehciles run in both lanes.And my sumo vesion if 1.18.0.
![1](https://github.com/eclipse-sumo/sumo/assets/85613839/31772113-0b0d-4a28-9ffe-ff0bb10817ce)
![QQ截图20240415152751](https://github.com/eclipse-sumo/sumo/assets/85613839/2cadd170-120a-4a09-ac74-ed07b6d9b756)

**Comment by namdre** [comment]
related to #7157

**Comment by han-zhang-baba** [comment]
Thanks for your reply. I read the issues #13300, and do the same changes as you said. But I also found vechicles automatically choose the right lane in the connected two lanes. And I also try to change the changelane model, such as: lcStrategic="-1". Neither of them can solve this problem. And my net.xml are as followed. Thanks for your response.
![1](https://github.com/eclipse-sumo/sumo/assets/85613839/2cc83d88-0568-4b8f-b776-a99cbd8273d4)
![QQ截图20240416085908](https://github.com/eclipse-sumo/sumo/assets/85613839/c05f5c92-c83d-43ba-8e5d-860b10a3eb65)

**Comment by namdre** [comment]
Yes. The network modifications discussed in #13300 do not apply to your case. The problem is really with the missing decision/randomization code in case of equally suited lanes (discussed in #7157).

**Comment by behrisch** [comment]
work continues in #7157
