### ISSUE TITLE
How to make big difference in the speed of normal driver and aggressive driver

### ISSUE THREAD

**Issue by harirRzi** [eclipse-sumo/sumo#14715]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
Hello. I defined some behavior like the following to have very high speed more than speed limit:

```
   <vType id="aggressive_0" vClass="passenger" sigma="0.1" maxSpeed="36.11"  accel="10" lcPushy="0.9" decel="9.5" speedDev="0.1" speedFactor="1.2"  color="green"/>
   <vType id="aggressive_1" vClass="passenger" sigma="0.1" maxSpeed="33.44" lcAssertive="1" accel="9.5" decel="10" lcPushy="1" speedDev="0.1" speedFactor="1.2"  color="green"/>
   <vType id="aggressive_2" vClass="passenger" sigma="0.2" maxSpeed="30.55" lcAssertive="0.8" accel="8" decel="9.5" speedDev="0.2" speedFactor="1.3" impatience="1" color="green"/>
```
   
   Also  I defined some behavior like the following for normal driving behavior:
   
```
    <vType id="Normal-car-0" vClass="passenger" length="5" accel="2.6" decel="4.5" sigma="0.5"  maxSpeed="24.99" speedDev="0.1" />

   <vType id="Normal-car-1" vClass="passenger" length="5" accel="3" decel="4.5" sigma="0.5"  maxSpeed="24.99" speedDev="0.1" />

   <vType id="Normal-car-2" vClass="passenger" length="5" accel="2.8" decel="4.5" sigma="0.5" minGap="1.0" maxSpeed="23.61" speedDev="0.1"/>
```
   
   After I produce my dataset, I in the output I see max speed of the aggressive cars is 24.31 and for normal is 22.74. I defined the max speed for aggressive drivers to be very high, but why I can not see big difference in their speed?

**Comment by namdre** [comment]
- the speeds in your network are probably limited by the road speed limit rather than the maxSpeed. Due to the choice of speedFactor 1.2, the aggressive cars are at most  20% faster 
- as soon as a fast car has to follow a slow car, it's speed gets reduced to that of the slow car (this explains why the aggressive cars are effectively only 10% faster)

**Comment by harirRzi** [comment]
Thank you for your response. So if I only define maxSpeed and not speedFactor, then will I see the speed of a car sometime to be 36 for example?

**Comment by namdre** [comment]
you can keep the maxSpeed of the vType and then either
- increase the edge speed or
- increase the speedFactor
