### ISSUE TITLE
A question about the shape of intersection

### ISSUE THREAD

**Issue by pjj-OSM** [eclipse-sumo/sumo#14711]
I get a intersection by netconvert tool with edge.xml and node.xml, the shape of intersection is like fig.1(red). But in fact ,the shape of this intersection is like fig.2(blue line), the stop line is more close to the intersection(see red arrow). can i use netconvert tool to get a intersection like fig.2?
![图片1](https://github.com/eclipse-sumo/sumo/assets/22164090/c7bbdadf-e674-4b3b-ae86-cf2e318efdc0)
![图片2](https://github.com/eclipse-sumo/sumo/assets/22164090/fcb036ca-9055-4f0c-ae2d-271b84594d33)

**Comment by m-kro** [comment]
Does your node have a shape attribute in the node.xml file?

**Comment by namdre** [comment]
yes, you can. Draw a custom node shape in netedit: https://sumo.dlr.de/docs/Netedit/neteditPopupFunctions.html#junction
