### ISSUE TITLE
what is angle in the Sumo output

### ISSUE THREAD

**Issue by harirRzi** [eclipse-sumo/sumo#14713]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
Hello. I use the following command to produce data output from Sumo simulation. I see there is angle feature in the output. Does it mean heading of a car?

`sumo -c ~/SUMOTutorials/drunk-detection/square-street/new-routes-file/demo.sumocfg --fcd-output ~/SUMOTutorials/drunk-detection/square-street/new-routes-file/sumoTracefcdfile.xml --fcd-output.acceleration`

**Comment by namdre** [comment]
yes.
