### ISSUE TITLE
How to make custom emission model?

### ISSUE THREAD

**Issue by Sunburst0614** [eclipse-sumo/sumo#14714]
I want to calculate vehicle emission with my own method. Can you tell me how to make my own custom emission model?

**Comment by namdre** [comment]
The easiest way is probably with a post-processing on fcd ouput in the language of your choice.
If you need the extra speed that comes from having a model inside sumo, take a look at https://github.com/eclipse-sumo/sumo/tree/main/src/utils/emissions
Don't try this unless you are very comfortable with reading and writting C++ code and don't expect a lot of support.
