### ISSUE TITLE
Question about simulation step

### ISSUE THREAD

**Issue by juun9714** [eclipse-sumo/sumo#14722]
Hi, I'm considering SUMO to retrieve some vehicle data for my project. While doing simulation, I got one question. 

There is "step" notion in the simulation. As we can check the definition of "step" on this web page(https://sumo.dlr.de/docs/Simulation/Basic_Definition.html) I found that default one step is one second and we can adjust it ourselves. But when we run the simulation, the simulation finishes too fast. I can check the "step" by printing it, but it takes 11 real-time seconds to run 100 steps in SUMO. 

I cannot understand the simulation step of SUMO pretty well. 

+ Is there any way to set delay on SUMO like we can set the step-length on .sumocfg file? (not sumo-gui)

**SUMO-version:1.19.0**

**operating system:Windows**

**Comment by namdre** [comment]
The step length is for controlling the granularity of the simulation.
sumo always runs as fast as possible whereas sumo-gui can be delayed by setting option
--delay or by dynamically adjusting delay with "delay" slider in the UI: https://sumo.dlr.de/docs/sumo-gui.html#usage_description

If you want to do real-time coupling then the client process has full control over the delays.
