### ISSUE TITLE
Unexpected behavior of tool netdiff.py

### ISSUE THREAD

**Issue by henrigrossmann** [eclipse-sumo/sumo#14721]
**Issue Description:**
netdiff.py is not detecting differences in connection allowance between two SUMO network files.

**Problem Description:**
When comparing two SUMO network files using netdiff.py, it fails to detect differences in connection allowance. Specifically, one network file contains connections with the allow="bicycle" attribute, while the other network file does not have this attribute. Despite this difference, netdiff.py reports that there are no discrepancies between the two files.

**Expected Behavior:**
netdiff.py should accurately detect differences in connection attributes, including allowance, between two SUMO network files.

**Actual Behavior:**
netdiff.py fails to detect differences in connection allowance between two SUMO network files, even when there are discrepancies in the XML attributes.

SUMO version: v1_19_0+1227-3616da08d4d

[diff.zip](https://github.com/eclipse-sumo/sumo/files/14998480/diff.zip)

**Comment by namdre** [comment]
the problem pertains to all attributes that have a default value if the second network uses the default.

**Comment by namdre** [comment]
the 'allow' attribute now has a default value so your particular use case is working fine. For other attributes where the value is not written in the second network, the element will not at least show up in the diff with a comment listing the missing attributes. However, the values still will not be reset when applying the diff to the source network (pending #14726)

**Comment by henrigrossmann** [comment]
thank you @namdre for the quick fix!
