### ISSUE TITLE
additionals are not being saved when saving a NeteditConfig

### ISSUE THREAD

**Issue by angelobanse** [eclipse-sumo/sumo#14739]
This breaks some tests, like `tests\netedit\netelements\edges\contextual_menu\reverse_direction_disconnected`

Maybe introduced by #14464?

**Comment by namdre** [comment]
can you recompile a version before #14464 and check whether this was the cause?

**Comment by palvarezlopez** [comment]
See comments in https://github.com/eclipse-sumo/sumo/issues/14976

**Comment by namdre** [comment]
dev_regression: invalid file names in .sumocfg

**Comment by namdre** [comment]
so, what exactly created the original regression and in which release was it introduced?

**Comment by palvarezlopez** [comment]
It was introduced in 1.20, but I cannot find the exactly commit (#14464 was not the problem)
