### ISSUE TITLE
Dynamic variable lane during simulation running

### ISSUE THREAD

**Issue by thinker310** [eclipse-sumo/sumo#14730]
Just like quesiton #14672 , the solution for that question does not appear to work. To describe my question clearly, two pictures are showed below:
![1713355538561](https://github.com/eclipse-sumo/sumo/assets/62609436/fb19f485-56ad-4bea-913d-c2b72debfea7)
![1713355616414](https://github.com/eclipse-sumo/sumo/assets/62609436/8489d9b2-1afe-491f-9aa7-b97573a76e82)
As demonstrated in this two picture, how to dynamically adjust the connection relationship in real-time during the simulation, is there any methods to solve the problem? such as  adjusting it in real-time by TraCI

**Comment by m-kro** [comment]
Well the answer is the same as in #14672 . You have to set all ever needed connections and then you can control which connections can be used with TraCI (traci.lane.setAllowed [ref](https://sumo.dlr.de/pydoc/traci._lane.html#LaneDomain-setAllowed)). All connections have internal lanes you can set the access permissions.

**Comment by thinker310** [comment]
> Well the answer is the same as in #14672 . You have to set all ever needed connections and then you can control which connections can be used with TraCI (traci.lane.setAllowed [ref](https://sumo.dlr.de/pydoc/traci._lane.html#LaneDomain-setAllowed)). All connections have internal lanes you can set the access permissions.

![image](https://github.com/eclipse-sumo/sumo/assets/62609436/0292e99b-7e46-4b1a-8f43-6428ce1f027a)
But this command is for vehicle class, I just want to adjust the connection relationship, such as left+straight -> straight for a certain entrance lane

**Comment by m-kro** [comment]
Yes

**Comment by thinker310** [comment]
OK, thank you, sir

**Comment by heySummerX** [comment]
May I ask if you have finally achieved it? Can you show me a demo

**Comment by 184815** [comment]
How did you achieve it? Is there any specific code

**Comment by namdre** [comment]
- define all connections that come up during different operating modes
- identify the names of the corresponding "internal lanes" https://sumo.dlr.de/docs/sumo-gui.html#investigating_internal_edges_and_lanes
- call edge.setAllowed / edge.setDisallowed on the internal edges
