### ISSUE TITLE
traci.simulation.getIDList() not working

### ISSUE THREAD

**Issue by JonasLange** [eclipse-sumo/sumo#14738]
When I call traci.simulation.getIDList() I get:
traci.exceptions.TraCIException: Get Simulation Variable: unsupported variable 0x00 specified

Yet 0x00 should not be an unsupported variable. As per the SUMO documentation it should return the :
https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html

**Comment by namdre** [comment]
If you want to retrieve vehicles, call `traci.vehicle.getIDList`
