### ISSUE TITLE
Question on Usage of traci.trafficlight.setProgramLogic and Request for Examples

### ISSUE THREAD

**Issue by JamesPsh** [eclipse-sumo/sumo#14734]
Hello SUMO Team,

I am currently working on integrating traffic light logic control using TraCI in my project. I have a question regarding the use of the traci.trafficlight.setProgramLogic function. Below is the code snippet I intend to use:

~~~
import traci
from sumolib.net import Phase
Logic = traci._trafficlight.Logic

phases = [
    Phase(duration=24.0, state='rrGGrrrrrrrGrrrr'),
    Phase(duration=4.0, state='rryyrrrrrrryrrrr'),
    Phase(duration=64.0, state='rrrrGGGrrrrrGGGr'),
    Phase(duration=4.0, state='rrrrGGGrrrrryyyr'),
    Phase(duration=1.0, state='rrrrGGGrrrrrrrrr'),
    Phase(duration=15.0, state='rrrrGGGGGrrrrrrr'),
    Phase(duration=4.0, state='rrrryyyGGrrrrrrr'),
    Phase(duration=1.0, state='rrrrrrrGGrrrrrrr'),
    Phase(duration=15.0, state='rrrrrrrGGrrrrrrG'),
    Phase(duration=4.0, state='rrrrrrryyrrrrrry'),
    Phase(duration=12.0, state='GGrrrrrrrGGrrrrr'),
    Phase(duration=18.0, state='GGrrrrrrrGGrrrrr'),
    Phase(duration=4.0, state='yyrrrrrrryyrrrrr')
]

traffic_logic = Logic(programID='0630', type=0, currentPhaseIndex=2, phases=phases, subParameter={})
tls_id = 'some_tls_id'  # example TLS ID
traci.trafficlight.setProgramLogic(tls_id, traffic_logic)
~~~

I would like to confirm if the above usage is correct for setting the traffic light logic via TraCI. Additionally, if there are any examples or additional documentation regarding the practical use of this function, I would greatly appreciate it if you could share them.

Thank you for your support and looking forward to your guidance.

**Comment by JamesPsh** [comment]
Additionally, how can offset be defined?

**Comment by namdre** [comment]
1. yes. Examples can be found in https://sumo.dlr.de/extractTest.php?path=complex/traci/trafficlight
2. You can set the offset indirectly by calling trafficlight.setPhaseDuration
