### ISSUE TITLE
Issue with Creating a Crosswalk Parallel to the Sidewalk

### ISSUE THREAD

**Issue by JamesPsh** [eclipse-sumo/sumo#14747]
Hello,

I am trying to create a crosswalk that is parallel to the sidewalk, similar to the real-life example shown in the right-hand image.

However, when I attempt to create the crosswalk, it ends up being slightly skewed,
as seen in the left-hand image, rather than parallel to the sidewalk.

Could you please provide guidance on how to align the crosswalk parallel to the sidewalk?

Thank you.

![img](https://github.com/eclipse-sumo/sumo/assets/101240964/45b36b30-163c-4271-b119-893e37b5d87a)

**Comment by namdre** [comment]
right-click on the crossing and select "set custom crossing shape", move and add geometry by dragging, remove points by shift-click, confirm with enter.

This may cause unexpected walkingarea shapes but these actually do not impact simulation behavior (only visuals).
