### ISSUE TITLE
 How to convert an existing shapefile of a map into taz zones

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14746]
Add your issue description here.
Hi, recently I've been building SUMO simulations of traffic flow using the OD matrix of the city. I've found that the division of TAZ is crucial.

*If possible, upload an example that shows your problem.*
Now I have the related zoning Shp file. Is there a way to map it to a road network file that SUMO can read, thus generating a TAZ file?
Thank you.
**SUMO-version:**
SUMO 1.19.0
**operating system:**
Windows 10

**Comment by namdre** [comment]
steps:
1. use polyconvert to read the shapefile and write polygons in the sumo format (https://sumo.dlr.de/docs/Simulation/Shapes.html#polygon_definitions)
2. use https://sumo.dlr.de/docs/Tools/District.html#edgesindistrictspy to generate the TAZ from the polygons.

**Comment by nudtdyk** [comment]
Danke!
