### ISSUE TITLE
How can I get prevNode and nextNode ID

### ISSUE THREAD

**Issue by juun9714** [eclipse-sumo/sumo#14751]
Hi, I always thank you for your kind reply :)

I have one question. I'm now using SUMO and libtraci library in Windows C++ environment. I want to know ID of the node connected to specific Edge (previous node and next node of edge). I know that we can use sumolib library and read _net.xml_ to get edge and node like below. But is there any way to do same work in C++ environment? 

**nextNodeID = net.getEdge('myEdgeID').getToNode().getID()** (https://sumo.dlr.de/docs/Tools/Sumolib.html#usage_examples)

**SUMO-version:1.19.0**

**operating system:Windows**

**Comment by juun9714** [comment]
@m-kro Thanks :) does this function is supported for libtraci too?

**Comment by m-kro** [comment]
Yes

**Comment by juun9714** [comment]
Thank you !!
