### ISSUE TITLE
Person capacity of vehicles not being checked in SUMO

### ISSUE THREAD

**Issue by RNippold** [eclipse-sumo/sumo#14752]
Although vehicles in SUMO have a passenger capacity, this value is apparently never checked. Therefore, any number of people can be assigned to a vehicle, which will also appear together with the vehicle in the simulation. A warning that the passenger capacity of the vehicle has been exceeded would be desirable here.

**SUMO-version:** v1_19_0+1890-4a6c257cf1f

**operating system:** Linux (but issue is OS independent)

**Comment by namdre** [comment]
When a vehicle stops, the capacity is always checked (MSBaseVehicle::allowsBoarding) but this check is missing for persons with depart="triggered"
