### ISSUE TITLE
Vehicle heading direction and coordinate system

### ISSUE THREAD

**Issue by prasuka4** [eclipse-sumo/sumo#14754]
Add your issue description here.
Hi
I have been trying to understand the vehicle coordinate system of SUMO simulator with respect to Global coordinate system?
Heading direction of a vehicle weather it is considered as y axis or x axis?

Below are the snaps for your reference. If possible provide some images or information related to sumo as well.
Thanks
 
*If possible, upload an example that shows your problem.*
![image](https://github.com/eclipse-sumo/sumo/assets/48856575/371f7c8c-37d1-4648-9434-e0678e3f5c41)

**SUMO-version:**
V1_19
**operating system:**
Windows

**Comment by namdre** [comment]
vehicle angle: 0 degrees is north, 90 degrees east,.... (https://en.wikipedia.org/wiki/Heading_(navigation))
