### ISSUE TITLE
clickable logs do not work in translated GUI

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#14759]
sometimes the object name is translated (like lane -> "Fahrstreifen") which invalidates the link generation code. So link generation should check for the translated string (or maybe both).

**Comment by m-kro** [comment]
This can still go wrong in many ways due to declension, word order etc. The same problem occurs with time values (there should already be a ticket...).

**Comment by behrisch** [comment]
I agree this is not the universal solution. We should still try.
