### ISSUE TITLE
'traci' has no attribute 'start'

### ISSUE THREAD

**Issue by Metro1998** [eclipse-sumo/sumo#14758]
I have two projects that both use the same sumo engine, which `import libsumo as traci`. One of the projects runs `traci.start(cmd)` within sumo engine without any issues. However, the other project throws an error saying 'traci' has no attribute 'start'."

```python
import libsumo as traci
import traci
LIBSUMO = "LIBSUMO_AS_TRACI" in os.environ

 def start_simulation(self):
        """
        Start the sumo simulation according to the sumo commend.
        :return:
        """
        sumo_cmd = [
         ...
        ]

        if LIBSUMO:
            traci.start(sumo_cmd)   #here throws error 'traci' has no attribute 'start'
            self.sumo = traci
            print("LIBSUMO")
        else:
            traci.start(sumo_cmd, label=self.label)
            self.sumo = traci.getConnection(self.label)
``` 

Actually, I've never encountered this issue before. The problem arose recently when I cloned one of my repositories while attempting to set up an instance of a sumo simulation. Additionally, the code in both projects is essentially the same, which makes the error even more baffling.

Debug in the wrong project：
![image](https://github.com/eclipse-sumo/sumo/assets/51565689/dc5452b2-7e77-48bb-b465-d3d7c175f484)
Debug in the right project:
![image](https://github.com/eclipse-sumo/sumo/assets/51565689/2bc3721e-bdf4-42c5-9922-dc096addbe91)

It seems there is a difference between  these two traci, but i dont know where is wrong, can you help me.

**SUMO-version:**   1.60

**operating system:**  win 11

**Comment by namdre** [comment]
did rebuild everything after cloning? Otherwise the libsumo library may be missing.

**Comment by Metro1998** [comment]
Emmmmm but how to rebuild it? In fact, the sumo engine has always been local, not embedded in the project. If Project A can access libsumo directly, there's no reason Project B can't do the same.

**Comment by namdre** [comment]
How did you install sumo initially? 
Does traci still work if you do `import traci` instead of `import libsumo as traci` ?
What is the value of %SUMO_HOME% and does point to the original installation or the clone?
