### ISSUE TITLE
[Question] How to save modified road network after modify network state via Traci

### ISSUE THREAD

**Issue by lindsaymorgan** [eclipse-sumo/sumo#14753]
Hi! I am working on a simulation project in which I change lane / road speed limit or permission via Traci when the simulation is stilling running. My question is: Is there a way to save this modified road network to net.xml file? Or I need to make a network file copy and change the file content by myself?

Thank you so much for your time and support.

**Comment by namdre** [comment]
There is currently now way to persist traci-changes to the road network. You can use sumolib/netconvert though: 

https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#modifying_node_positions_with_the_help_of_sumolib
https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#modifying_the_network

**Comment by lindsaymorgan** [comment]
> There is currently now way to persist traci-changes to the road network. You can use sumolib/netconvert though:
> 
> https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#modifying_node_positions_with_the_help_of_sumolib https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#modifying_the_network

Thanks~
