### ISSUE TITLE
Distance between two parking spots

### ISSUE THREAD

**Issue by oshadajay** [eclipse-sumo/sumo#14750]
Hi, is there a way to calculate the distance between two on-street parking bays in SUMO either from the net/additional xml files or at runtime? Here by distance I mean the distance a vehicle has to travel from one bay to the other. Thank you in advance. 

**SUMO-version:**
1.19

**operating system:**
Windows

**Comment by m-kro** [comment]
You can try one of the functions in [**sumolib.net**](https://sumo.dlr.de/pydoc/sumolib.net.html):

- getFastestPath
- getOptimalPath
- getShortestPath

**Comment by oshadajay** [comment]
Thank you for the response. I believe these functions are to calculate the distance between two edges. Is there a way to calculate the distance between two points in two edges since there can be multiple parking bays in one edge? Thank you.

**Comment by m-kro** [comment]
The sumolib functions allow to give the positions of origin and destination along the edge (arguments **fromPos** and **toPos**). I assume these are taken into account for the cost.

**Comment by oshadajay** [comment]
Yeah that would work. Thank you. I am getting an error as follows when using the getOptimalPath function. Any idea why?

```
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\sumolib\net\__init__.py", line 534, in getOptimalPath
    while toEdge.getFunction() == "internal":
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'getFunction'
```

**Comment by m-kro** [comment]
@oshadajay you need to work with the [sumolib representations of edges](https://sumo.dlr.de/pydoc/sumolib.net.edge.html). Look at the documentation example [how to load the network](https://sumo.dlr.de/docs/Tools/Sumolib.html#loading_a_network_file) in sumolib.

**Comment by oshadajay** [comment]
Thank you. I could get the distance between the edges using the sumolib representation. However I'm not yet clear on how to get the position of a parking area along a lane. Is there a way to load the additional file and get that info similar to https://sumo.dlr.de/pydoc/sumolib.net.html? Thank you.

**Comment by m-kro** [comment]
Sumolib includes some XML handling code, see [example](https://sumo.dlr.de/docs/Tools/Sumolib.html#manipulating_and_writing_xml) in the docs. You can use that to read the additional file if you want (any other python XML module will do as well). Other than that, there isn't more help...

**Comment by namdre** [comment]
there is also traci.simulation.getDistanceRoad(edgeID1, pos1, edgeID2, pos2, isDriving=True)

**Comment by oshadajay** [comment]
Thank you very much!
