### ISSUE TITLE
Is there a solution to make a vehicle run a round-trip between two junctions?

### ISSUE THREAD

**Issue by Karl131127** [eclipse-sumo/sumo#14755]
like this:
![image](https://github.com/eclipse-sumo/sumo/assets/122240456/b69e3a92-a3ce-4e7a-a27b-af400cfcb7cc)
I want to let a car run between  A and B. Just like, a car run from A to B, then return.

**SUMO-version:**

**operating system:**windows

**Comment by namdre** [comment]
`  <trip id="0" depart="0" fromJunction="A" toJunction="A" viaJunctions="B"/>`

see also https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#routing_between_junctions
