### ISSUE TITLE
crash after joining junctions

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14768]
- select some junctions
- F7
- F5
- undo
- F7

now some junctions that were part of the join are still visible. netedit crash on mouseover on these.

**Comment by namdre** [comment]
reproducible with the test network form #14769 when loading the following junction selection: 
[customJoin.txt](https://github.com/eclipse-sumo/sumo/files/15095804/customJoin.txt)

**Comment by palvarezlopez** [comment]
Related with the calculation of geometry under mouse. In the function of checking geometry under mouse, netedit try to check the geometry of the function, but probably doesn't exist.

**Comment by namdre** [comment]
The problem starts earlier: a faulty junction bubble is drawn even though the junction was removed via joining. Mouseover only triggers the crash.

**Comment by namdre** [comment]
Problem is caused by inconsistent removals and additions to the RTree:

```
 addAdditionalGLObject B0 bound=104.00,89.00,126.00,111.00
 removeAdditionalGLObject B0 bound=104.00,89.00,126.00,111.00
 addAdditionalGLObject B0 bound=104.00,89.00,126.00,111.00
 removeAdditionalGLObject B0 bound=104.00,89.00,126.00,111.00
 addAdditionalGLObject B0 bound=104.00,89.00,126.00,111.00
 removeAdditionalGLObject B0 bound=104.00,89.00,126.00,111.00
 removeAdditionalGLObject B0 bound=104.00,89.00,126.00,111.00
 addAdditionalGLObject B0 bound=104.00,89.00,126.00,111.00
 addAdditionalGLObject B0 bound=104.00,89.00,126.00,111.00
 removeAdditionalGLObject B0 bound=104.00,89.00,126.00,111.00
```

its removed twice in a row and then added twice. From that point on, there is a superfluous copy in the tree which means it will always be drawn.

**Comment by namdre** [comment]
when the junction was added into the RTree via undo it's `myJunctionInGrid` status could go out of sync.
