### ISSUE TITLE
Duplicate ID vehicule in two different route files

### ISSUE THREAD

**Issue by Ukiano** [eclipse-sumo/sumo#14767]
Hi, 
I am creating a simulation with different vehicule types and then I have two route files, one with cars and the other one with buses. I constructed my route files with OD2trips and duarouter.
When I am lunching the simulation i have an issue because some vehicules share the same ID in  two different route files. I know that I need to have unique vehicules id for the two files but is it possible to change the vehicules id of one file automatically ? Or is there another way to construct a simulation to obtain two different vehicule types automatically in one route file?
Thanks
**SUMO-version: 1.19.0**

**operating system: Windows**

**Comment by namdre** [comment]
use od2trips option **--prefix** with a different value for the two calls.
