### ISSUE TITLE
How can I make leading vehicles gradually slow down at the stop line?

### ISSUE THREAD

**Issue by govin08** [eclipse-sumo/sumo#14775]
I understand that the parameter tau, which can be applied to any car-following model, increases safety by allowing vehicles to react in advance and therefore stop more gradually.

But, according to the definition of [tau](https://sumo.dlr.de/docs/Car-Following-Models.html#tau), its application is limited to situations where there is a preceding vehicle. This means every following vehicle is influenced by tau only when a preceding vehicle exists. But when there is no preceding vehicle and the succeeding vehicle is stopping because of the crosswalk or red signal, tau does not apply.

Is there alternative way (parameter or car following model, whatever) to make leading vehicle (one without any preceding vehicle) to stop more gradually?

environment : sumo 1.18, windows 10

**Comment by namdre** [comment]
- you set a lower 'decel' value in the vType (though this will apply to all situations and Krauss will always make full use of decel at a stop line)
- you can use another car following model (i.e. carFollowModel="IDM"). most models will stop more smoothly than Krauss.

**Comment by govin08** [comment]
@namdre
1. Lowering `decel` would affect all the vehicles, which is not I wanted. 
So isn't it possible to apply a notion like `tau`(or sensitivity according to [Krauss](https://sumo.dlr.de/pdf/KraussDiss.pdf), the equation 3.1)?
It seems quite unnatural since vehicles should gradually come to a stop at the stop line or crosswalks

2. Thank you. But by "most model will stop more smoothly", do you mean that vehicles will slow down **in front of the stop line or the crosswalks**?

**Comment by namdre** [comment]
1. No, not in the Krauss Model as currently implemented. Though you supply your own version: https://sumo.dlr.de/docs/Developer/How_To/Car-Following_Model.html
2. stopping at stop lines and crosswalks uses the same code (MSCFModel::stopSpeed), so, *yes, both*.

**Comment by govin08** [comment]
@namdre Thanks. It helps a lot.
