### ISSUE TITLE
Linux SUMO build problem

### ISSUE THREAD

**Issue by MoMingQimio** [eclipse-sumo/sumo#14773]
When I build SUMO in ubuntu20.04, I run into an error: 

/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_uint8@LIBFFI_BASE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_prep_closure_loc@LIBFFI_CLOSURE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_pointer@LIBFFI_BASE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_uint64@LIBFFI_BASE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_closure_alloc@LIBFFI_CLOSURE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_prep_cif@LIBFFI_BASE_7.0'
collect2: error: ld returned 1 exit status
make[2]: *** [unittest/src/utils/geom/CMakeFiles/testgeom.dir/build.make:146: ../bin/testgeom] Error 1
make[1]: *** [CMakeFiles/Makefile2:5923: unittest/src/utils/geom/CMakeFiles/testgeom.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_uint8@LIBFFI_BASE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_prep_closure_loc@LIBFFI_CLOSURE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_pointer@LIBFFI_BASE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_uint64@LIBFFI_BASE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_closure_alloc@LIBFFI_CLOSURE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_prep_cif@LIBFFI_BASE_7.0'
collect2: error: ld returned 1 exit status
make[2]: *** [unittest/src/utils/common/CMakeFiles/testcommon.dir/build.make:162: ../bin/testcommon] Error 1
make[1]: *** [CMakeFiles/Makefile2:5884: unittest/src/utils/common/CMakeFiles/testcommon.dir/all] Error 2
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_closure_alloc@LIBFFI_CLOSURE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_uint8@LIBFFI_BASE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_prep_closure_loc@LIBFFI_CLOSURE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_uint64@LIBFFI_BASE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_pointer@LIBFFI_BASE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_prep_cif@LIBFFI_BASE_7.0'
collect2: error: ld returned 1 exit status
make[2]: *** [unittest/src/netbuild/CMakeFiles/testnetbuild.dir/build.make:117: ../bin/testnetbuild] Error 1
make[1]: *** [CMakeFiles/Makefile2:6086: unittest/src/netbuild/CMakeFiles/testnetbuild.dir/all] Error 2
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_closure_alloc@LIBFFI_CLOSURE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_uint8@LIBFFI_BASE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_prep_closure_loc@LIBFFI_CLOSURE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_uint64@LIBFFI_BASE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_type_pointer@LIBFFI_BASE_7.0'
/usr/bin/ld: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined reference to `ffi_prep_cif@LIBFFI_BASE_7.0'
collect2: error: ld returned 1 exit status
make[2]: *** [unittest/src/microsim/CMakeFiles/testmicrosim.dir/build.make:179: ../bin/testmicrosim] Error 1
make[1]: *** [CMakeFiles/Makefile2:6046: unittest/src/microsim/CMakeFiles/testmicrosim.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

the command I used is as below:
cmake --build build -j$(nproc)

how do i do to fix this problem??

**Comment by MoMingQimio** [comment]
it fixed it using the method below:
@SarveshThakur I was able to solve this problem on Ubuntu 20.04 with rm ${CONDA_PREFIX}/lib/libffi.7.so ${CONDA_PREFIX}/lib/libffi.so.7 The problem is that those are dynamically linked to libffi8, which is incorrect. – 
[Zhanwen Chen](https://stackoverflow.com/users/3853537/zhanwen-chen)
 [Oct 30, 2023 at 17:57](https://stackoverflow.com/questions/75045632/apt-update-failed-libp11-kit-so-0-undefined-symbol-ffi-type-pointer-version#comment136434458_75045665)

**Comment by AhmetNeoSari** [comment]
This error is caused by incompatibility of different versions of the **libffi** library. The error is caused by a version mismatch of the libffi library. In particular, the symbolic linking of **libffi.so.7** to **libffi.so.8.1.0** causes this error. This is my solution on ubuntu 20.04 and ros2 foxy

Navigate to the **lib** directory of your Conda virtual environment:
```bash
cd ~/anaconda3/envs/<xxx>/lib
```
Back up the existing libffi.so.7 connection:
```bash
mv libffi.so.7 libffi.so.7.bak
```
Create the new symbolic link:
```bash
ln -s /lib/x86_64-linux-gnu/libffi.so.7.1.0 libffi.so.7
```
Update the connection cache:
```bash
sudo ldconfig
```
