### ISSUE TITLE
"od2trips" is running slowly

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14784]
Add your issue description here.
Hi, I'm trying to generate vehicle routes using od2trips after obtaining the OD matrix, but it keeps getting stuck on the interface.

*If possible, upload an example that shows your problem.*
Here is the picture. It stays on this interface for several minutes or even tens of minutes.
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/6ba005a6-6667-4d7c-a260-0ecd65788801)

**SUMO-version:**
SUMO1.19.0

**operating system:**
Windows 10

**Comment by namdre** [comment]
can you provide the inputs? od2trips is usually quite fast.

**Comment by nudtdyk** [comment]
[inputs.zip](https://github.com/eclipse-sumo/sumo/files/15144504/inputs.zip)


> can you provide the inputs? od2trips is usually quite fast.

Hello，the inputs are as above. thanks

**Comment by namdre** [comment]
runtime is quadratic in the number of edges per TAZ due to an inefficient duplicates check.  Your input has some *very* large TAZ.

**Comment by nudtdyk** [comment]
> runtime is quadratic in the number of edges per TAZ due to an inefficient duplicates check. Your input has some _very_ large TAZ.

thanks

**Comment by namdre** [comment]
you can download a fixed version at https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots
