### ISSUE TITLE
Questioning the `free flow driving speed` in documentation and addressing potential typos

### ISSUE THREAD

**Issue by govin08** [eclipse-sumo/sumo#14787]
I've just read two documents :
- [Speed Distributions](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#speed_distributions)
- [VehicleSpeed](https://sumo.dlr.de/docs/Simulation/VehicleSpeed.html)

I want to know (1) if I understand the notion of `free flow driving speed` right and (2) I suspect that some typo need to be corrected.

<br>
<br>

(1) There are three parameters : `speed`, `maxSpeed` and `desiredMaxSpeed`.

The `speed` attribute can be specified in the `edge` tag. This is the maximum speed (legal road speed limit) allowed on the edge ;

```
    <edge id="-A0" from="J1" to="J0" priority="-1">
        <lane id="-A0_0" index="0" speed="13.89" length="1000.00" shape="1000.00,4.80 0.00,4.80"/>
        <lane id="-A0_1" index="1" speed="13.89" length="1000.00" shape="1000.00,1.60 0.00,1.60"/>
    </edge>
```

The `maxSpeed` and `desiredMaxSpeed` attributes can be specified in the `vType` tag.
`maxSpeed` is the vehicle's technical maximum velocity. `desiredMaxSpeed` is primarily used where there is no legal road speed limit (i.e. pedestrians and bicycles)

```
<vType id="CarB" speedFactor="1.0" speedDev="0.1" maxSpeed="55.55" desiredMaxSpeed="2778" />
```

`speedFactor` is sampled, by default, from the truncated normal distribution. That is, with the above setting of `vType`, 

> `speedFactor` ~ Normal(mean = 1.0, standard_deviation=0.1)

where if the sampled `speedFactor` has the absolute value greater than 0.2 ,of approximately 5% probability, than discard it ; only the sampled `speedFactor` with the absolute value less than or equal to 0.2 is accepted.

With this `speedFactor`, we can get the `free_flow_driving_speed` where

> `free_flow_driving_speed` = min(`maxSpeed`, `speedFactor` * `desiredMaxSpeed`,  `speedFactor` * `speed`).

This (kind of) equation is found in [here](https://sumo.dlr.de/docs/Simulation/VehicleSpeed.html#edgelane_speed_and_speedfactor) and [here](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#individual_speed_factor) and [here](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#departspeed) where the word indicating the value varies depends on the pages ; the desired free flow driving speed of a vehicle or maxSpeed. So I just coined a new word `free_flow_driving_speed` in the above equation.

At an instant, the actual speed of a vehicle doesn't correspond with the `free_flow_driving_speed` in general. So the vehicle accelerate or decelerate to reach `free_flow_driving_speed`. For instance, the vehicle's speed approaches the free_flow_driving_speed as described by the following differential equation.

![image](https://github.com/eclipse-sumo/sumo/assets/65585738/48a6bf2a-bfe1-4a26-93f6-8bb3df64e50a)

Sorry for such a long question. But could you please let me know if what I've stated is right?

<br>
<br>

(2) According to my explanation, I can't understand the 'cutoff' in [the documentation](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#defining_a_normal_distribution_for_vehicle_speeds) like

>- normal distribution: speedFactor="norm(mean,deviation)"
>- truncated normal distribution: speedFactor="normc(mean,deviation,lowerCutOff,upperCutOff)"
>
>The default for passenger cars is "`normc`(1,0.1,0.2,2)" which implies that ~95% of the vehicles drive between 80% and 120% of the legal speed limit.
>
>Instead of giving the multi-parameter definition above, a simpler definition style is also possible.
>
>- setting the deviation of the distribution directly: `speedDev`="0.3"
>- setting the mean of the distribution directly: `speedFactor`="1.2"
>When using the attributes in this way, the default cut-off range [0.2, 2] remains unchanged.

doesn't look  valid. The cutoff should be [0.2, 0.2]. It should look like this ;

>- normal distribution: speedFactor="norm(mean,deviation)"
>- truncated normal distribution: speedFactor="normc(mean,deviation,lowerCutOff,upperCutOff)"
>
>The default for passenger cars is "`normc`(1,0.1,0.2,0.2)" which implies that ~95% of the vehicles drive between 80% and 120% of the legal speed limit.
>
>Instead of giving the multi-parameter definition above, a simpler definition style is also possible.
>
>- setting the deviation of the distribution directly: `speedDev`="0.3"
>- setting the mean of the distribution directly: `speedFactor`="1.2"
>When using the attributes in this way, the default cut-off range [0.2, 0.2] remains unchanged.

Am I misunderstanding? Or is there an typo error?

**Comment by namdre** [comment]
1. yes 
2. not sure what you're quoting there but the documentation I'm reading says `The default for passenger cars is "normc(1,0.1,0.2,2)"`  and `the default cut-off range [0.2, 2] remains unchanged.`  So the individual speedFactor will always be sampled until a value above 0.2 and below 2.0 is found (unless you change the cut-off).

**Comment by govin08** [comment]
@m-kro  Yes I know the definition of closed intervals, denoted by square brackets.
If the mean is 1 and the standard deviation is 0.1, then a sample X from normal(1, 0.1^2) is between 0.8 and 1.2 of probability 95%. So in this sense, the vehicles would drive between 80% and 120% of `free_flow_driving_speed`. So isn't it what it means?

**Comment by govin08** [comment]
@m-kro You're right. [0.2, 0.2] is just a singleton {0.2}.
@namdre Thanks I think I understand what you mean. And the existence of `lowerCutOff` is indeed necessary since velocity can not be negative. So `speedFactor` is guaranteed to exist in the closed interval [0.2, 2].

By the way, does
> "the vehicle's speed approaches the `free_flow_driving_speed` as described by the following differential equation"

right? If I can accept the differential equation, the actual speed would exponentially decay to the `free_flow_driving_speed`.
[This](https://sumo.dlr.de/pdf/KraussDiss.pdf) (equation 3.1) is why I stated it previously. However, the SUMO documentation appears to define tau differently.

**Comment by namdre** [comment]
3.1 doesn't describe the Krauss model. It's part of the general introduction to car following. Instead Krauss cars accelerate continuously up to their driving speed with with a random negative component (configured by model parameter `sigma`) applied to their acceleration.  For Krauss, tau defines the desired minimum time headway to the leader (and thus doesn't affect free flow speed at all).

**Comment by govin08** [comment]
@namdre Thanks for your accurate explanation. I've only read that page (of equation 3.1) since I don't have enough time. So `sigma` (I remember that this parameter is related to the imperfectness) is also related to the accelerating procedure. It sounds like `sigma` is  related to the absolute value of the *derivative* of acceleration, when speeding up.
