### ISSUE TITLE
How can I make changes to the net.xml file in Sumo. 

### ISSUE THREAD

**Issue by ufukkirbas** [eclipse-sumo/sumo#14782]
Add your issue description here.

How can I make changes to the net.xml file in Sumo. For example, I want to add a condition to an “actuated” type signalized intersection. I open the file as xml in wordpad and write the code I want according to the examples. Later, when I open the file in Netedit and Sumo-Gui, I see that it deletes the codes I wrote. Although I changed the xml-validation settings to never in both netedit and Sumo-Gui, I could not add my tls signal conditions to the net.xml file.

*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.19
**operating system:**
Win10 and win11

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why
