### ISSUE TITLE
How to get the number of buildings and POIs within a taz?

### ISSUE THREAD

**Issue by nudtdyk** [eclipse-sumo/sumo#14783]
Add your issue description here.
Hi, recently I've been using SUMO to generate traffic flows, but before that, I need to generate an OD matrix based on TAZ

*If possible, upload an example that shows your problem.*
The general idea is as follows: first, I generate a rough TAZ using [gridDistricts.py](http://griddistricts.py/), and then I determine the weight of each TAZ based on the number of buildings and POIs within the TAZ. With these weights, I aim to generate the corresponding OD matrix. However, I'm unsure how to obtain the number of buildings and POIs within each TAZ. Is there any way to do this? Thank you!
The tazs exported are as follows:
![image](https://github.com/eclipse-sumo/sumo/assets/120693511/a9829c65-59f6-40c3-9021-63797d173e6a)

**SUMO-version:**
SUMO1.19.0

**operating system:**
Windows 10

**Comment by namdre** [comment]
take a look at https://github.com/lcodeca/SUMOActivityGen where exactly this is being done.
And https://github.com/lcodeca/SUMOActivityGen/blob/master/docs/HOWTO.md
The code is included in sumo in tools/contributed/saga

If you want to write your own code, you can use sumolib to help with parsing and geomtry computation. You may also find inspiration in tools/edgesInDisticts.py

**Comment by nudtdyk** [comment]
> take a look at https://github.com/lcodeca/SUMOActivityGen where exactly this is being done. And https://github.com/lcodeca/SUMOActivityGen/blob/master/docs/HOWTO.md The code is included in sumo in tools/contributed/saga
> 
> If you want to write your own code, you can use sumolib to help with parsing and geomtry computation. You may also find inspiration in tools/edgesInDisticts.py

Thank you! I've used this method before to parse OSM map files, but encountered the following issues:
  1. It gets stuck during execution, requiring manual intervention to continue.
  2. For large-scale scenarios, the runtime is excessively long, typically taking up to two days.

**Comment by namdre** [comment]
did you install the python rtree package? Without this, any kind of map matching is very slow

**Comment by nudtdyk** [comment]
> did you install the python rtree package? Without this, any kind of map matching is very slow

Yes, maybe the file is too large with the size of 1.2GB. Is there another reason?

**Comment by namdre** [comment]
> Thank you! I've used this method before to parse OSM map files

Did you use SAGA or your own code based on sumolib?

**Comment by nudtdyk** [comment]
> > Thank you! I've used this method before to parse OSM map files
> 
> Did you use SAGA or your own code based on sumolib?

Yes, I referenced SAGA's [generateTAZBuildingsFromOSM.py] and utilized this program to parse the OSM file.

**Comment by namdre** [comment]
SAGA uses the python shapely library. It would seem that some of the geometry primitives in shapely are slow (depending on the version): https://gis.stackexchange.com/questions/353619/shapely-with-rtree-versus-strtree
