### ISSUE TITLE
make error while building sumo for ubuntu 16.04

### ISSUE THREAD

**Issue by narayankhatrig** [eclipse-sumo/sumo#14808]
While I try to install sumo from online source 
git clone --recursive https://github.com/eclipse/sumo

I got the following error
The ubuntu version used is 16.04.7 LTS (Xenial Xerus)

[ 77%] Linking CXX executable ../../../../bin/polyconvert
[ 78%] Built target polyconvert
Scanning dependencies of target emissionsDrivingCycle
[ 78%] Building CXX object src/tools/CMakeFiles/emissionsDrivingCycle.dir/emissionsDrivingCycle_main.cpp.o
[ 78%] Building CXX object src/tools/CMakeFiles/emissionsDrivingCycle.dir/TrajectoriesHandler.cpp.o
[ 78%] Building CXX object src/tools/CMakeFiles/emissionsDrivingCycle.dir/VTypesHandler.cpp.o
[ 79%] Linking CXX executable ../../../../bin/emissionsDrivingCycle
[ 79%] Built target emissionsDrivingCycle
Scanning dependencies of target emissionsMap
[ 79%] Building CXX object src/tools/CMakeFiles/emissionsMap.dir/emissionsMap_main.cpp.o
[ 79%] Linking CXX executable ../../../../bin/emissionsMap
[ 79%] Built target emissionsMap
Scanning dependencies of target testlibsumostatic
[ 79%] Building CXX object src/traci_testclient/CMakeFiles/testlibsumostatic.dir/testlibsumo_main.cpp.o
[ 79%] Linking CXX executable ../../../../bin/testlibsumostatic
[ 79%] Built target testlibsumostatic
Scanning dependencies of target testlibtraci
[ 80%] Building CXX object src/traci_testclient/CMakeFiles/testlibtraci.dir/testlibtraci_main.cpp.o
[ 80%] Linking CXX executable ../../../../bin/testlibtraci
[ 80%] Built target testlibtraci
Scanning dependencies of target testlibsumo
[ 80%] Building CXX object src/traci_testclient/CMakeFiles/testlibsumo.dir/testlibsumo_main.cpp.o
[ 80%] Linking CXX executable ../../../../bin/testlibsumo
[ 80%] Built target testlibsumo
Scanning dependencies of target utils_traci
[ 80%] Building CXX object src/utils/traci/CMakeFiles/utils_traci.dir/TraCIAPI.cpp.o
[ 80%] Linking CXX static library libutils_traci.a
[ 80%] Built target utils_traci
Scanning dependencies of target TraCITestClient
[ 80%] Building CXX object src/traci_testclient/CMakeFiles/TraCITestClient.dir/tracitestclient_main.cpp.o
[ 80%] Building CXX object src/traci_testclient/CMakeFiles/TraCITestClient.dir/TraCITestClient.cpp.o
[ 80%] Linking CXX executable ../../../../bin/TraCITestClient
[ 80%] Built target TraCITestClient
Scanning dependencies of target netedit_tools
[ 80%] Building CXX object src/netedit/tools/CMakeFiles/netedit_tools.dir/GNEPythonTool.cpp.o
[ 80%] Building CXX object src/netedit/tools/CMakeFiles/netedit_tools.dir/GNENetDiffTool.cpp.o
[ 80%] Building CXX object src/netedit/tools/CMakeFiles/netedit_tools.dir/GNERunPythonTool.cpp.o
[ 80%] Building CXX object src/netedit/tools/CMakeFiles/netedit_tools.dir/GNERunNetgenerate.cpp.o
[ 80%] Linking CXX static library libnetedit_tools.a
[ 80%] Built target netedit_tools
Scanning dependencies of target generate-templates-h
[ 80%] Generating templates.h
Traceback (most recent call last):
  File "/home/narayan/sumo/src/netedit/../../tools/build_config/templates.py", line 420, in <module>
    main()
  File "/home/narayan/sumo/src/netedit/../../tools/build_config/templates.py", line 407, in main
    with open("templates.h", 'w', encoding='utf8') as templateHeaderFile:
TypeError: 'encoding' is an invalid keyword argument for this function
src/netedit/CMakeFiles/generate-templates-h.dir/build.make:61: recipe for target 'src/netedit/templates.h' failed
make[2]: *** [src/netedit/templates.h] Error 1
CMakeFiles/Makefile2:5506: recipe for target 'src/netedit/CMakeFiles/generate-templates-h.dir/all' failed
make[1]: *** [src/netedit/CMakeFiles/generate-templates-h.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
narayan@narayan-virtual-machine:~/sumo/build/cmake-build$

**Comment by behrisch** [comment]
Please make sure you use python3 as your default python. Maybe this one helps: https://stackoverflow.com/questions/41986507/unable-to-set-default-python-version-to-python3-in-ubuntu
