### ISSUE TITLE
Emission class "HBEFA4/LCV_diesel_N1-III_convlt_1986" not recognized

### ISSUE THREAD

**Issue by dennyciccia** [eclipse-sumo/sumo#14810]
Adding emissionClass="HBEFA4/LCV_diesel_N1-III_convlt_1986" to a vType I get this error:
```
Traceback (most recent call last):
  File "C:\Users\Denny\OneDrive\Università\Tirocinio\Progetti SUMO\Simulazioni ed esperimenti SUMO\runner.py", line 45, in <module>
    addVehiclesToSimulation(vehicleList)
  File "C:\Users\Denny\OneDrive\Università\Tirocinio\Progetti SUMO\Simulazioni ed esperimenti SUMO\vehicle_generator.py", line 63, in addVehiclesToSimulation
    traci.vehicle.add(vehID=v.vehicleID, routeID=v.routeID, typeID='vtype-'+v.vehicleID, depart=v.depart, departSpeed=v.initialSpeed, departLane=departLane)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\_vehicle.py", line 1455, in add
    self._setCmd(tc.ADD_FULL, vehID, "t" + (12 * "s") + "ii", 14,
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\domain.py", line 164, in _setCmd
    self._connection._sendCmd(self._cmdSetID, varID, objectID, format, *values)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 231, in _sendCmd
    return self._sendExact()
           ^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 144, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Invalid type 'vtype-vehicle766' for vehicle 'vehicle766'
```
vType vehicle766 declaration:
`<vType id="vtype-vehicle766" length="4.198685001222624" mass="2876.79896324166" accel="4.581168111670639" decel="2.115573561602123" emergencyDecel="4.433753831688516" minGap="7.837819832238101" vClass="delivery" emissionClass="HBEFA4/LCV_diesel_N1-III_convlt_1986" color="#FFFFFF" guiShape="delivery"/>`

**SUMO-version:** 1.19.0

**operating system:** Windows 10 22H2

**Comment by dennyciccia** [comment]
Yes, I checked another time my project and I load the vehicle type definition before adding vehicles to the simulation.
I think the problem is for that specific emission class because for the vehicle types defined before in the xml file, the error does not appear.
I also changed the emission class "HBEFA4/LCV_diesel_N1-III_convlt_1986" with "HBEFA4/LCV_diesel_N1-III_XXIII" and everything worked.

**Comment by m-kro** [comment]
Well I cannot reproduce it on my side. Maybe you have some [control character](https://en.wikipedia.org/wiki/Control_character) inside the emissionClass value and your editor does not display it currently? I think control characters may get removed when posting on Github...

**Comment by dennyciccia** [comment]
I just tried to write the emission class by myself and not copy and paste from the documentation page and now it works properly.
Maybe there was a control character as you said.
Thank you for your support.
