### ISSUE TITLE
Pedestrians skipping at junctions

### ISSUE THREAD

**Issue by Imperialpiggy** [eclipse-sumo/sumo#14827]
Dear all,

I attempted to simulate bedirectional pedestrian movement in a park scenario with SUMO. I created a network using netedit by setting the edge parameters as follows: allow = pedestrian; spreadType = center. However, I noticed that pedestrians jumped over the junctions (see Fig 1). I also tried setting the pedestrian model to "striping" explicitly  in sumo configuration file with "<pedestrian.model value="striping"/>" to avoid the possbile use of the nonInteracting model, but it didn't resolve the issue. Can anyone provide assistance with this? Thank you in advance.

![image](https://github.com/eclipse-sumo/sumo/assets/49153858/e9b987bf-8726-4d8b-9ef9-0f9d4f2876cf)
Fig 1. 

**SUMO-version:** 1.19.0

**operating system:** windows 11

**Comment by namdre** [comment]
Your network doesn't have pedestrian infrastructure ("crossings" and "walkingareas". See https://sumo.dlr.de/docs/Simulation/Pedestrians.html#walkingareas
You can set these options from netedit in the option menu (F10) in the pedestrian tab.

**Comment by Imperialpiggy** [comment]
Thank you so much! It worked! For the purpose of recording, I pressed F10 in netedit, and ticked the walkingareas checkbox in the pedestrian tab, then pressed F5 to rebuilt the network.

> Your network doesn't have pedestrian infrastructure ("crossings" and "walkingareas". See https://sumo.dlr.de/docs/Simulation/Pedestrians.html#walkingareas You can set these options from netedit in the option menu (F10) in the pedestrian tab.
