### ISSUE TITLE
How to change the connection state?

### ISSUE THREAD

**Issue by SongKun2023** [eclipse-sumo/sumo#14824]
Dear Sir, I want to change the state of connection one as is shown In the following screenshot to “M” (major link). What should I do to complete this operation?

![WechatIMG18](https://github.com/eclipse-sumo/sumo/assets/97946646/f6a5faf7-9605-4cb2-9631-31d155c0d84a)

**SUMO-version:** 1.19.0

**operating system:** win10

**Comment by m-kro** [comment]
Recreate the connection in netedit pressing [Shift] + [Left mouse click] to create an unyielding connection.

**Comment by namdre** [comment]
If you care about collision safety, do not create an unyielding connection but rather change the junction type to "zipper"

**Comment by SongKun2023** [comment]
OK, Thanks a lot for your suggestions.
