### ISSUE TITLE
`libsumocs.dll` and `libtracics.dll` doesn't work

### ISSUE THREAD

**Issue by Minokori** [eclipse-sumo/sumo#14838]
I've succeeded in generating the `libsumocs.dll` and `libtracics.dll`, and enabled the CLR supported:
<img width="853" alt="image" src="https://github.com/eclipse-sumo/sumo/assets/73998474/261483d1-fb85-44b4-82be-372beb208ee6">
But sadly,when i used them in a `.NET Framework ` program, it seems doesn't work. When I opened Visual Studio's object viewer, they didn't provide me with useful classes or methods.
<img width="544" alt="image" src="https://github.com/eclipse-sumo/sumo/assets/73998474/1073ce5c-4664-4161-8fcf-7892007550e0">
I think I should have generated *.dlls as document said, but it only provides a poor explain on how to use it. 

**SUMO-version:** 1.19.0

**operating system:** windows 11

**Comment by behrisch** [comment]
Thank you for your feedback. Unfortunately our C# support is still in very early stages. Up to now only the basic code generation has been done, we did not even compile it yet, so you are in fact ahead of us. Please watch #11712 for further progress but of course we would also like to here if you find something by yourself
