### ISSUE TITLE
about timeLoss

### ISSUE THREAD

**Issue by Clown1206** [eclipse-sumo/sumo#14837]
Add your issue description here.
  In the tripinfo file, one of the metrics is timeLoss, is there a specific formula for timeLoss and is it supported by relevant literature? I used timeLoss in one of my papers, but the reviewer suggested me to briefly explain the significance and scope of application of each metric to help readers understand it better.
*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.16
**operating system:**
win 10

**Comment by m-kro** [comment]
You can find a short description of the meaning in the [documentation](https://sumo.dlr.de/docs/Simulation/Output/TripInfo.html#generated_output). Essentially it is the time difference between the real trip duration and an ideal one without slowing down due to other vehicles, intersections, speed limit changes.

**Comment by Clown1206** [comment]
Can the ideal travel time be interpreted as the time it takes for a vehicle to travel from a starting point to a finishing point at its maximum speed (or at the maximum road speed limit) in completely unobstructed conditions?

**Comment by Clown1206** [comment]
> You can find a short description of the meaning in the [documentation](https://sumo.dlr.de/docs/Simulation/Output/TripInfo.html#generated_output). Essentially it is the time difference between the real trip duration and an ideal one without slowing down due to other vehicles, intersections, speed limit changes.

Can the ideal travel time be interpreted as the time it takes for a vehicle to travel from a starting point to a finishing point at its maximum speed (or at the maximum road speed limit) in completely unobstructed conditions?

**Comment by m-kro** [comment]
Yes (with the exception of scheduled stops)
