### ISSUE TITLE
Question: Mesoscopic Lane Selection in GUI

### ISSUE THREAD

**Issue by henrigrossmann** [eclipse-sumo/sumo#14834]
I'm running a mesoscopic simulation. There are edges with two lanes: one lane for all vehicles and one lane for buses only (see screenshot). In the GUI, I've noticed that private cars sometimes use the bus lane and sometimes use the "regular" lane and that it depends on the edge, which of the two lanes they use. Is this behavior normal? What parameter decides which lane the cars will use in the GUI?

Thank you for your help.

<img width="895" alt="Screenshot 2024-05-07 at 11 11 11" src="https://github.com/eclipse-sumo/sumo/assets/151520729/3a07b901-2727-4b7f-a2bc-aa6dbb15505a">

**Comment by namdre** [comment]
unless you're running with option **--meso-lane-queue**, the lanes are only considered when there is a turning lane and permissions are ignored!

**Comment by henrigrossmann** [comment]
Thank you Jakob for the quick reply.
