### ISSUE TITLE
cannot reload sumocfg if SUMO_HOME is not set

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#14830]
complains about invalid document structure

**Comment by namdre** [comment]
is this a regression?

**Comment by behrisch** [comment]
Yes, it has been introduced when we restrained schema checking to local files by default in #11054

**Comment by namdre** [comment]
Why does the initial load work but not the reload?

**Comment by behrisch** [comment]
It seems there is something broken in the validation initialization. The first pass does not do any validation

**Comment by namdre** [comment]
I would say this is a feature. Much better to load without validation then to not load at all. Giving a warning of  `validation not possible, please set SUMO_HOME` is enough in my view. (And the same for reload).

**Comment by behrisch** [comment]
You are right, the broken part is that it does validation in the second pass
