### ISSUE TITLE
invalid connection with option --ramps.guess if the input defines connections

### ISSUE THREAD

**Issue by MatteoFel** [eclipse-sumo/sumo#14833]
Hi all

I was wondering how the following connections on motorways come about. Sometimes when going from one link to the next not every lane is connected to the one directly in front. Is there a specific reason for this?

Thanks a lot!

Current situation:
![Screenshot 2024-05-07 at 10 07 48](https://github.com/eclipse-sumo/sumo/assets/82516091/b6ab7398-2864-4051-8724-e07ea2ec47ed)

How I would expect it:

![Screenshot 2024-05-07 at 10 09 27](https://github.com/eclipse-sumo/sumo/assets/82516091/81be6e66-6869-4574-ba20-292e5cb1e4bf)

*Example*

There are plenty of examples in the following net. The one in the screenshot refers to edge_id 41890650-AddedOffRampEdge and its subsequent links. 
[TUA.net.xml.zip](https://github.com/eclipse-sumo/sumo/files/15232635/TUA.net.xml.zip)

**SUMO-version:**
1.19

**operating system:**
MacOS

**Comment by namdre** [comment]
- the network was built/processed with option **--ramps.guess**   (edges with AddedOnRamp or AddedOffRamp in their id)
  -  this guessed ramps where there are none (i.e at  https://www.google.com/maps/@33.1803588,-87.5537793,128m/data=!3m1!1e3?entry=ttu) and this result in wrong lane numbers
  - the zig-zag geometry of these ramps is a bug
- the strange connectivity was not created by netconvert as far as I can tell. It must have come about by some further processing/editing step

**Comment by MatteoFel** [comment]
Thank you for your quick reply!

I think the strange connectivity might still come from the --ramps.guess option. We perform several netconvert steps with the options --ramps.guess value="true" and ramps.min-highway-speed value="27.8". In the last step we wrongly removed the ramps.min-highway-speed option (while keeping the --ramps.guess option) which lead to netconvert guessing ramps on new links, thus adding additional lanes, but not connections. This leads to the strange connectivity patterns.

By consistently using both options we don't have this issue any longer - we are super happy, thanks for forcing to go through our steps - but maybe it's still useful for you to know that ramp.guess can cause this connection behaviour (at least that's my guess).

In the example below the network version_1.net.xml was created from version_0.net.xml using netconvert and the osm2T.netccfg configuration file.

[example.zip](https://github.com/eclipse-sumo/sumo/files/15234874/example.zip)

Thanks a lot!
