### ISSUE TITLE
How to turn off TraCI step information statements

### ISSUE THREAD

**Issue by corinnegroth** [eclipse-sumo/sumo#14840]
I control traffic in a SUMO simulation using TraCI. Is there a way to "turn off" the simulation step information statements? The red box around the statement is what I'm referring to in the picture below.

![TraCI_print_statements](https://github.com/eclipse-sumo/sumo/assets/59060490/e0eb8a4c-2fd3-4ec9-825c-e2a3131b57d0)

SUMO 1.19.0

Windows

**Comment by m-kro** [comment]
Start sumo with the option **--no-step-log true** (see [documentation](https://sumo.dlr.de/docs/Simulation/Output/index.html#commandline_output_step-log)).

**Comment by corinnegroth** [comment]
Yep, it worked! Thank you for the quick turnaround!
