### ISSUE TITLE
Basic Doubt about Phases and States in TL Logic

### ISSUE THREAD

**Issue by prajwalvinod** [eclipse-sumo/sumo#14849]
Hey,

I would like to know the difference between defining states for a network (Eg: highway network with one ramp) where the TL controls just one traffic signal in which the states change between **g** and **r** with a cycle time of 60 seconds. I understand how states are defined for multiple traffic signals at say an intersection but I am a bit confused about the definitions for states at a single traffic signal.
For example: 
1. What is the difference in the traffic signal control logic between the two following tllogic files ?

**Code 1:**

```
<additional>
    <tlLogic id="J8" programID="0" offset="0" type="static">
        <phase duration="60" state="g"/>
        <phase duration="60" state="r"/>
    </tlLogic>
</additional>
```
**Code 2:**

```
<additional>
    <tlLogic id="J8" programID="0" offset="0" type="static">
        <phase duration="60" state="gr"/>
    </tlLogic>
</additional>
```

2. How does the control within the simulation differ and if I want to control the durations of each state (green and red) externally (like from Python for maybe an RL task) which is more suitable ?

**NOTE:** Additionally, is it possible to control the phase durations such that from an RL perspective when a certain duration is set for the green state, the red state duration automatically becomes **total duration - green duration** for that particular ramp metering action ?
You may ignore the note if the question is too convoluted. I threw it in there since I am working on it for a project at present.

Thank You

**SUMO-version: 1.16.0**

**Operating system: Windows 11**

**Comment by m-kro** [comment]
Code excerpt 1 is the right one. The second one does not make sense  - it just shows the same signal states for the whole duration of the simulation but defines two signals (signal indices). You can achieve [automatic cycle time control](https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#coordination) with actuated traffic lights in SUMO.

**Comment by prajwalvinod** [comment]
Hey @m-kro,

Thanks for your prompt reply. I forgot to add one more question in my previous query.
What exactly is the difference between **g** and **G** ?
The reason I ask is because at the moment in my task I only use one vehicle type and the network is a simple highway network with one ramp but the metrics that I plot at the end of the simulation are quite different. 
What exactly does the difference in notation change in the simulation behaviourally ?

Thanks

**Comment by prajwalvinod** [comment]
Hey @m-kro,

Thanks for your replies. I will go through the documentation again. It was helpful.

Regards

**Comment by CouPPPPPle** [comment]
Hello, I encountered the exactly same problem as you mentioned in your NOTE. May I ask that have you managed to resolve the issue? Specifically, when I attempt to set the phase duration using traci.trafficlight.setPhaseDuration to implement RL output actions, I found that it doesn’t seem to work.

**Comment by namdre** [comment]
setPhaseDuration only effects the current cycle.

**Comment by CouPPPPPle** [comment]
Hello，@prajwalvinod，I encountered the exactly same problem as you mentioned in your NOTE. May I ask that if  you have managed to resolve the issue? Specifically, when I attempt to set the phase duration using traci.trafficlight.setPhaseDuration to implement RL output actions, I found that it doesn’t seem to work.
Hope you can enlighten me. Thanks！

**Comment by CouPPPPPle** [comment]
> > when I attempt to set the phase duration using traci.trafficlight.setPhaseDuration to implement RL output actions, I found that it doesn’t seem to work.
> 
> setPhaseDuration only effects the current cycle.

Thank you very much for your answer. Then, is it possible to dynamically adjust the duration of phases through TRACI, and assign a green light duration to the next phase?

**Comment by namdre** [comment]
You can replace the whole program with a new program that has different timings (`traci.trafficlight.setProgramLogic`)

**Comment by CouPPPPPle** [comment]
> You can replace the whole program with a new program that has different timings (`traci.trafficlight.setProgramLogic`)

I have made the modification according to your instruction and solved the problem. Thank you very much.

**Comment by CouPPPPPle** [comment]
> You can replace the whole program with a new program that has different timings (`traci.trafficlight.setProgramLogic`)

Sorry to disturb you again, but I have encountered a new issue and was wondering if I could seek your advice. I set the phase like:
phases = []
        phases.append(traci.trafficlight.Phase(duration=actions[0]*5, state='G', minDur=0.0, maxDur=60.0, next=()))
        phases.append(traci.trafficlight.Phase(duration=60.0-actions[0]*5, state='r', minDur=0.0, maxDur=60.0, next=()))
        logic = traci.trafficlight.Logic(programID='0', type=0, currentPhaseIndex=0, phases=phases)
        traci.trafficlight.setCompleteRedYellowGreenDefinition('2', logic)
And when the action[0] is 12, the output of traci.trafficlight.getCompleteRedYellowGreenDefinition('2') is: Logic(programID='0', type=0, currentPhaseIndex=1, phases=(Phase(duration=60.0, state='G', minDur=0.0, maxDur=60.0, next=()), Phase(duration=0.0, state='r', minDur=0.0, maxDur=60.0, next=())), subParameter={}) . 
However, when I visualize the SUMO simulation interface, I see that the signal control is indeed showing a full red time. Could you help me understand what might be the problem?

**Comment by namdre** [comment]
Phases with duration 0 are forbidden in xml input so I'd say the behavior in this case is somewhat undefined. However, in my own test the duration-0 phase is simply skipped. Please provide a minimal failure example.

**Comment by CouPPPPPle** [comment]
> Phases with duration 0 are forbidden in xml input so I'd say the behavior in this case is somewhat undefined. However, in my own test the duration-0 phase is simply skipped. Please provide a minimal failure example.

Thanks for your reply, I will try to make some modifications to avoid the duration-0 phase situation. Thank you!

**Comment by prajwalvinod** [comment]
Hey @CouPPPPPle,

Sorry for the late reply. But is your code now working properly with the setProgramLogic command ?

Regards 

Prajwal

**Comment by CouPPPPPle** [comment]
> Hey @CouPPPPPle,
> 
> Sorry for the late reply. But is your code now working properly with the setProgramLogic command ?
> 
> Regards
> 
> Prajwal

Never mind！It seems to work normally now and thanks for your reply!
