### ISSUE TITLE
traci.trafficlights.setCompleteRedYellowGreenDefinition

### ISSUE THREAD

**Issue by deefsgh** [eclipse-sumo/sumo#14845]
![TUUY~IPMRT42A35{K`VBWNB](https://github.com/eclipse-sumo/sumo/assets/104182359/60e18522-b222-4069-a68e-b74c82f9fefe)
Hey! I am trying to implement intersection signal optimization in SUMO using Traci4Matlab, but I am getting this error when using the function “traci.trafficlights.setCompleteRedYellowGreenDefinition()”.How can I solve this problem? 

**SUMO-version:1.17

**operating system:Windows

**Comment by m-kro** [comment]
This means your input to the function is wrong (number of arguments and/or data types). Please check your function call.

P.S.: Traci4Matlab hasn't been updated for long and [alternatives](https://sumo.dlr.de/docs/Libtraci.html#matlab) are available, in case you want to use features of recent SUMO versions.

**Comment by deefsgh** [comment]
Thank you very much for your help！ Also I would like to ask what command should I enter to download the Python package using

**Comment by deefsgh** [comment]
Thanks again for your help, after my debugging the script finally works!
