### ISSUE TITLE
Can't open OSM web wizard on macOS

### ISSUE THREAD

**Issue by jankotschy** [eclipse-sumo/sumo#14842]
HI, after following the download process on your website, I can't open OSM web wizard (no problems with netedit and sumo-gui).  Could you please help me with this issue?

jankotschy@macbook-air-7 ~ % echo $SUMO_HOME
/opt/homebrew/opt/sumo/share/sumo
jankotschy@macbook-air-7 ~ % python3 osmWebWizard.py
/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/jankotschy/osmWebWizard.py': [Errno 2] No such file or directory
jankotschy@macbook-air-7 ~ % 

**SUMO-version:* 1.19.0*

**operating system: macOS Sonoma**

**Comment by jankotschy** [comment]
Sorry but how do I do that? I could only get this to "work":

jankotschy@macbook-air-1 ~ % $SUMO_HOME/tools
zsh: permission denied: /opt/homebrew/opt/sumo/share/sumo/tools

**Comment by namdre** [comment]
from a directory where you have write permissions, call
`$SUMO_HOME/tools/osmWebWizard.py`

**Comment by jankotschy** [comment]
This pops up then...

jankotschy@macbook-air-1 ~ % $SUMO_HOME/tools/osmWebWizard.py
env: python: No such file or directory

**Comment by namdre** [comment]
make sure to install python then: https://www.python.org/

**Comment by jankotschy** [comment]
I have it installed, doesn't seem to work...

jankotschy@macbook-air-1 ~ % python3
Python 3.12.3 (v3.12.3:f6650f9ad7, Apr  9 2024, 08:18:47) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

**Comment by zihaooo** [comment]
Try this:

```bash
cd $SUMO_HOME/tools/
```
and then
```bash
python3 osmWebWizard.py
```

**Comment by jankotschy** [comment]
It works! Thank you so much!
