### ISSUE TITLE
Changing time-to-teleport via traci

### ISSUE THREAD

**Issue by AimanKhan1997** [eclipse-sumo/sumo#14844]
Hi everyone,

I want to change the time-to-teleport via traci during the simulation. I am simulating a scenario where the vehicles can teleport during the warm-up time of the simulation but should not teleport after the warm-up time. I see that there is an option in vehicle type to overwrite the time-to-teleport and I was wondering if there is a function traci.vehicle.settime_to_teleport, so I can change the teleport time after the warm-up time via traci.

Kindly let me know if there are also some workarounds for changing teleport time during the simulation.

Thanks a lot for your time and consideration.

**Comment by namdre** [comment]
unfortunately, this isn't possible yet (#10430). You could save the state after the warmup time and the load the state with another option for --time-to-teleport   (and not set anything in the vType). See https://sumo.dlr.de/docs/Simulation/SaveAndLoad.html
