### ISSUE TITLE
question: how can I retrieve all the vehicle that will depart in the future using traci

### ISSUE THREAD

**Issue by lindsaymorgan** [eclipse-sumo/sumo#14851]
Hello, I am currently trying to retrieve all the vehicle that will depart in the future at a certain time while simulation is running. I have tried [getLoadedIDList](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getLoadedIDList), but it only return part of those vehicles. Is there a better way?

**Comment by namdre** [comment]
if you load your route file using the option **--additional-files** they will all be available from the start (rather than incrementally at runtime). See https://sumo.dlr.de/docs/sumo.html#loading_order_of_input_files

**Comment by lindsaymorgan** [comment]
> if you load your route file using the option **--additional-files** they will all be available from the start (rather than incrementally at runtime). See https://sumo.dlr.de/docs/sumo.html#loading_order_of_input_files

Thanks!
