### ISSUE TITLE
“py.traci.trafficlight().Phase()”is not available

### ISSUE THREAD

**Issue by deefsgh** [eclipse-sumo/sumo#14853]
Hey!
When calling python's traci from within a Matlab script,  an error occurs: “Unrecognized object, attribute or field 'Phase' of class 'py.traci._trafficlight.TrafficLightDomain'”，the specific function called is py.traci.trafficlight().Phase
I'd like to know how this works out. Thanks!
![DZ9B2VWX8_X}4}9LST18K82](https://github.com/eclipse-sumo/sumo/assets/104182359/38265214-cc95-4afd-a3c6-bcdc8f412fb1)

**SUMO-version:1.17

**operating system:Windows

**Comment by namdre** [comment]
try: `py.traci.trafficlight.getPhase(tlsID)`

**Comment by deefsgh** [comment]
Thank you very much! Script runs successfully
