### ISSUE TITLE
Accessing Local SUMO Installation from Remote Jupyter Lab on University HPC

### ISSUE THREAD

**Issue by anaferraz** [eclipse-sumo/sumo#14855]
Currently, I am using SUMO (Simulation of Urban Mobility) 1.19 installed on my personal computer (Windows) for running simulations. However, due to the long simulation times, I am interested in utilizing a remote High-Performance Computing (HPC) system provided by my university. I would like to know if it is possible to access my local SUMO installation from a remote Jupyter Lab running on the university's HPC. Specifically, I have the following questions:

1. Is it feasible to connect and utilize the local SUMO installation on my personal computer from a remote Jupyter Lab environment?
2. If it is possible, what are the steps involved in setting up the connection between the remote Jupyter Lab and the local SUMO installation?
3. Are there any specific configurations or considerations to keep in mind during the setup process?
4. In case accessing the local installation is not possible, could you please suggest alternative approaches to leverage the power of the remote HPC while working with SUMO?

Thank you for your time and assistance.

**Comment by namdre** [comment]
No. If you want to have the speed of the HPC system, you need to have sumo running natively there. Installing SUMO should generally be possible (i.e. with pip: https://sumo.dlr.de/docs/Downloads.php#python_packages_virtual_environments)

**Comment by anaferraz** [comment]
Thank you, I installed natively there and it works.
