### ISSUE TITLE
project problem: Increase in Collision Incidents involving Sudden Disappearance of Vehicles and Changes in Driving Styles."

### ISSUE THREAD

**Issue by ray92423** [eclipse-sumo/sumo#14861]
I am working on a special project which focuses on the impact of adding warning signals at an uncontrolled intersection to enhance safety. The current idea involves calculating the Time to Collision (TTC) value when a pair of vehicles approaches the intersection within a distance less than 150 meters. When TTC is less than 3 seconds, the warning signal will be activated. I have set up three different driving styles: aggressive, normal, and conservative, each distinguished by different values of tau, acceleration, and deceleration. By default, if the driving style is aggressive, encountering the warning signal will switch to normal, and normal will switch to conservative. This simulates how people tend to become more cautious when encountering warning signals, aiming to reduce collision incidents and probabilities at intersections.

 But I encountered several issues during the simulation:
I found that some vehicles would suddenly teleport to the next road when approaching the intersection, without passing through the intersection. Some vehicles would even disappear suddenly. Additionally, some vehicles, for reasons I'm unsure of, would suddenly disappear when queuing to stop. Lastly, and most importantly, I anticipated that changing driving styles would reduce collision risks. However, in the collision information (collinfo), the number of collisions increased significantly. I suspect this increase in rear-end collisions might be due to changing driving styles. I'm wondering if this inference is incorrect, or if there's an error in my strategy file's code. How should I correct it? Or is there any method or strategy to prompt drivers to change their driving styles and behaviors after receiving warnings from the warning signals at uncontrolled intersections, and ensure that the simulated data reflects a decrease in collision frequency? Also, I'm not sure why my strategy file's simulation is very slow. Is there any way to speed it up? I'm sorry for asking so many questions and troubling you.

Below are my .rou ,turns and strategy files, while the strategy file is my attempt using TraCI to change driving styles based on warning messages. Thank you for your assistance.

.rou:
``<?xml version="1.0" encoding="UTF-8"?>
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">

    
    
    <vType id="Car" vClass="passenger" minGap="2" maxSpeed="13.88" jmDriveAfterRedTime="3">
        <param key="has.ssm.device" value="true"/>
        <param key="has.driverstate.device" value="true"/>
        <param key="device.ssm.measures" value="TTC PET"/>
        <param key="device.ssm.trajectories" value="true"/>
    </vType>

    <vType id="Aggressive" accel="4.5" decel="5.5" speedFactor="1.6" tau="0.45" minGap="0.5" jmDriveAfterRedTime="3"
           lcPushy="1.0" lcPushyGap="0.2" lcAssertive="1.0" lcTimeToImpatience="0.5" lcSpeedGain="10.0"
           lcCooperative="0.0" lcAccelLat="2.0" maxSpeedLat="3.0" lcMaxSpeedLatStanding="3.0"
           lcMaxSpeedLatFactor="1.0">
        <param key="has.ssm.device" value="true"/> 
        <param key="has.driverstate.device" value="true"/> 
        <param key="device.ssm.measures" value="TTC PET"/>
        <param key="device.ssm.trajectories" value="true"/> 
    </vType>

    <vType id="Aggressive_2" accel="2.5" decel="3.5" speedFactor="1.0" tau="0.75" minGap="1"
           jmDriveAfterRedTime="3">
        <param key="has.ssm.device" value="true"/>
        <param key="has.driverstate.device" value="true"/>
        <param key="device.ssm.measures" value="TTC PET"/>
        <param key="device.ssm.trajectories" value="true"/>
    </vType>

    
    <vType id="Car_truck" vClass="truck" minGap="2" maxSpeed="13.88" jmDriveAfterRedTime="3">
        <param key="has.ssm.device" value="true"/>
        <param key="has.driverstate.device" value="true"/>
        <param key="device.ssm.measures" value="TTC PET"/>
        <param key="device.ssm.trajectories" value="true"/>
    </vType>

    <vType id="Aggressive_truck" vClass="truck" accel="4.5" decel="5.5" speedFactor="1.6" tau="0.45" minGap="0.5" jmDriveAfterRedTime="3"
           lcPushy="1.0" lcPushyGap="0.2" lcAssertive="1.0" lcTimeToImpatience="0.5" lcSpeedGain="10.0"
           lcCooperative="0.0" lcAccelLat="2.0" maxSpeedLat="3.0" lcMaxSpeedLatStanding="3.0"
           lcMaxSpeedLatFactor="1.0">
        <param key="has.ssm.device" value="true"/> 
        <param key="has.driverstate.device" value="true"/> 
        <param key="device.ssm.measures" value="TTC PET"/>
        <param key="device.ssm.trajectories" value="true"/> 
    </vType>

    <vType id="Aggressive_2_truck" vClass="truck" accel="2.5" decel="3.5" speedFactor="1.0" tau="0.75" minGap="1"
           jmDriveAfterRedTime="3">
        <param key="has.ssm.device" value="true"/>
        <param key="has.driverstate.device" value="true"/>
        <param key="device.ssm.measures" value="TTC PET"/>
        <param key="device.ssm.trajectories" value="true"/>
    </vType>

    
    <vType id="Car_moped" vClass="moped" minGap="2" maxSpeed="13.88" jmDriveAfterRedTime="3">
        <param key="has.ssm.device" value="true"/>
        <param key="has.driverstate.device" value="true"/>
        <param key="device.ssm.measures" value="TTC PET"/>
        <param key="device.ssm.trajectories" value="true"/>
    </vType>

    <vType id="Aggressive_moped" vClass="moped" accel="4.5" decel="5.5" speedFactor="1.6" tau="0.45" minGap="0.5" jmDriveAfterRedTime="3"
           lcPushy="1.0" lcPushyGap="0.2" lcAssertive="1.0" lcTimeToImpatience="0.5" lcSpeedGain="10.0"
           lcCooperative="0.0" lcAccelLat="2.0" maxSpeedLat="3.0" lcMaxSpeedLatStanding="3.0"
           lcMaxSpeedLatFactor="1.0">
        <param key="has.ssm.device" value="true"/> 
        <param key="has.driverstate.device" value="true"/> 
        <param key="device.ssm.measures" value="TTC PET"/>
        <param key="device.ssm.trajectories" value="true"/> 
    </vType>

    <vType id="Aggressive_2_moped" vClass="moped" accel="2.5" decel="3.5" speedFactor="1.0" tau="0.75" minGap="1"
           jmDriveAfterRedTime="3">
        <param key="has.ssm.device" value="true"/>
        <param key="has.driverstate.device" value="true"/>
        <param key="device.ssm.measures" value="TTC PET"/>
        <param key="device.ssm.trajectories" value="true"/>
    </vType>
    

    
    <flow id="S1" type="Car" begin="0" end="3600" vehsPerHour="120" color="1,1,0" from="S2S"/>
    <flow id="S2" type="Aggressive" begin="0" end="3600" vehsPerHour="15" color="red" from="S2S"/>
    <flow id="S3" type="Aggressive_2" begin="0" end="3600" vehsPerHour="15" color="blue" from="S2S"/>
    <flow id="S4" type="Car_truck" begin="0" end="3600" vehsPerHour="40" color="1,1,0" from="S2S"/>
    <flow id="S5" type="Aggressive_truck" begin="0" end="3600" vehsPerHour="5" color="red" from="S2S"/>
    <flow id="S6" type="Aggressive_2_truck" begin="0" end="3600" vehsPerHour="5" color="blue" from="S2S"/>
    <flow id="S7" type="Car_moped" begin="0" end="3600" vehsPerHour="240" color="1,1,0" from="S2S"/>
    <flow id="S8" type="Aggressive_moped" begin="0" end="3600" vehsPerHour="30" color="red" from="S2S"/>
    <flow id="S9" type="Aggressive_2_moped" begin="0" end="3600" vehsPerHour="30" color="blue" from="S2S"/>

    <flow id="N1" type="Car" begin="0" end="3600" vehsPerHour="120" color="1,1,0" from="N2N"/>
    <flow id="N2" type="Aggressive" begin="0" end="3600" vehsPerHour="15" color="red" from="N2N"/>
    <flow id="N3" type="Aggressive_2" begin="0" end="3600" vehsPerHour="15" color="blue" from="N2N"/>
    <flow id="N4" type="Car_truck" begin="0" end="3600" vehsPerHour="40" color="1,1,0" from="N2N"/>
    <flow id="N5" type="Aggressive_truck" begin="0" end="3600" vehsPerHour="5" color="red" from="N2N"/>
    <flow id="N6" type="Aggressive_2_truck" begin="0" end="3600" vehsPerHour="5" color="blue" from="N2N"/>
    <flow id="N7" type="Car_moped" begin="0" end="3600" vehsPerHour="240" color="1,1,0" from="N2N"/>
    <flow id="N8" type="Aggressive_moped" begin="0" end="3600" vehsPerHour="30" color="red" from="N2N"/>
    <flow id="N9" type="Aggressive_2_moped" begin="0" end="3600" vehsPerHour="30" color="blue" from="N2N"/>

    <flow id="W1" type="Car" begin="0" end="3600" vehsPerHour="240" color="1,1,0" from="W2W"/>
    <flow id="W2" type="Aggressive" begin="0" end="3600" vehsPerHour="30" color="red" from="W2W"/>
    <flow id="W3" type="Aggressive_2" begin="0" end="3600" vehsPerHour="30" color="blue" from="W2W"/>
    <flow id="W4" type="Car_truck" begin="0" end="3600" vehsPerHour="80" color="1,1,0" from="W2W"/>
    <flow id="W5" type="Aggressive_truck" begin="0" end="3600" vehsPerHour="10" color="red" from="W2W"/>
    <flow id="W6" type="Aggressive_2_truck" begin="0" end="3600" vehsPerHour="10" color="blue" from="W2W"/>
    <flow id="W7" type="Car_moped" begin="0" end="3600" vehsPerHour="480" color="1,1,0" from="W2W"/>
    <flow id="W8" type="Aggressive_moped" begin="0" end="3600" vehsPerHour="60" color="red" from="W2W"/>
    <flow id="W9" type="Aggressive_2_moped" begin="0" end="3600" vehsPerHour="60" color="blue" from="W2W"/>

    <flow id="E1" type="Car" begin="0" end="3600" vehsPerHour="240" color="1,1,0" from="-E2E"/>
    <flow id="E2" type="Aggressive" begin="0" end="3600" vehsPerHour="30" color="red" from="-E2E"/>
    <flow id="E3" type="Aggressive_2" begin="0" end="3600" vehsPerHour="30" color="blue" from="-E2E"/>
    <flow id="E4" type="Car_truck" begin="0" end="3600" vehsPerHour="80" color="1,1,0" from="-E2E"/>
    <flow id="E5" type="Aggressive_truck" begin="0" end="3600" vehsPerHour="10" color="red" from="-E2E"/>
    <flow id="E6" type="Aggressive_2_truck" begin="0" end="3600" vehsPerHour="10" color="blue" from="-E2E"/>
    <flow id="E7" type="Car_moped" begin="0" end="3600" vehsPerHour="480" color="1,1,0" from="-E2E"/>
    <flow id="E8" type="Aggressive_moped" begin="0" end="3600" vehsPerHour="60" color="red" from="-E2E"/>
    <flow id="E9" type="Aggressive_2_moped" begin="0" end="3600" vehsPerHour="60" color="blue" from="-E2E"/>

</routes>

turns:
```<?xml version="1.0" encoding="UTF-8"?>

<turns>
   <interval begin="0" end="3600">
      <edgeRelation from="EC" to="CW" probability="0.18"/>
      <edgeRelation from="EC" to="CN" probability="0.77"/>
      <edgeRelation from="EC" to="CS" probability="0.05"/>

      <edgeRelation from="WC" to="CN" probability="0.15"/>
      <edgeRelation from="WC" to="CE" probability="0.81"/>
      <edgeRelation from="WC" to="CS" probability="0.04"/>

      <edgeRelation from="NC" to="CW" probability="0.11"/>
      <edgeRelation from="NC" to="CS" probability="0.82"/>
      <edgeRelation from="NC" to="CE" probability="0.07"/>
      
      <edgeRelation from="SC" to="CW" probability="0.17"/>
      <edgeRelation from="SC" to="CN" probability="0.79"/>
      <edgeRelation from="SC" to="CE" probability="0.04"/>

            

      
      
   </interval>
   <sink edges="-N2N"/>
   <sink edges="-W2W"/>
   <sink edges="-S2S"/>
   <sink edges="E2E"/>


</turns>

```

strategy file:
 ```import os
import sys
import optparse
import traci
import math
import random


if 'SUMO_HOME' in os.environ:
    tools = os.path.join(os.environ['SUMO_HOME'], 'tools')
    sys.path.append(tools)
else:
    sys.exit("请设置环境变量 'SUMO_HOME'")

from sumolib import checkBinary

def get_options():
    optParser = optparse.OptionParser()
    optParser.add_option("--nogui", action="store_true", default=False, help="run the commandline version of sumo")
    options, args = optParser.parse_args()
    return options

calculated_collisions = set()

def calculate_distance_to_intersection(vehicle):
    position = traci.vehicle.getPosition(vehicle)
    intersection_pos = (0,0)
    distance_to_intersection = abs(position[0]) + abs(position[1])
    return distance_to_intersection

def calculate_collision_risk(vehicle1, vehicle2,lane_type1,lane_type2):
    if (vehicle1, vehicle2) in calculated_collisions or (vehicle2, vehicle1) in calculated_collisions:
        return False
    pos1 = traci.vehicle.getPosition(vehicle1)
    pos2 = traci.vehicle.getPosition(vehicle2)
    speed1 = traci.vehicle.getSpeed(vehicle1)
    speed2 = traci.vehicle.getSpeed(vehicle2)
    angle1 = traci.vehicle.getAngle(vehicle1)
    angle2 = traci.vehicle.getAngle(vehicle2)
    distance = abs(pos1[0] - pos2[0]) + abs(pos1[1] - pos2[1])
     
    if abs(angle1 - angle2) == 90 or abs(angle1 - angle2) == 180:
        return False
    ttc = distance / max(0.1, abs(speed1 - speed2))
    #print("ttc:",ttc)
     # 更新計算過的碰撞風險車輛對
    calculated_collisions.add((vehicle1, vehicle2))

    # 確定是否存在碰撞風險
    return ttc < 3

    intersection_pos = (0,0)

def run():
    checked_vehicles = set()  # 儲存已經檢查過碰撞風險的車輛
    while traci.simulation.getMinExpectedNumber() > 0:
        # 更新模擬
        traci.simulationStep()
        # 獲取所有車輛列表及其所在的路段類型
        vehicles = traci.vehicle.getIDList()
        # 檢查所有車輛之間的碰撞風險
        for i in range(len(vehicles)):
            for j in range(i+1, len(vehicles)):
                vehicle1 = vehicles[i]
                vehicle2 = vehicles[j]
                # 檢查車輛是否已經被檢查過
                if vehicle1 in checked_vehicles or vehicle2 in checked_vehicles:
                    continue
                lane_type1 = traci.vehicle.getRoadID(vehicle1) 
                lane_type2 = traci.vehicle.getRoadID(vehicle2) 
                # 檢查兩車距離路口的距離是否小於150公尺
                if (calculate_distance_to_intersection(vehicle1) < 150 and
                        calculate_distance_to_intersection(vehicle2) < 150):
                    # 如果在150公尺內，則計算碰撞風險
                    if calculate_collision_risk(vehicle1, vehicle2, lane_type1, lane_type2):
                        # 如果存在碰撞風險，向兩輛車發送警示
                        print("警告：車輛 {} 和車輛 {} 存在碰撞風險！".format(vehicle1, vehicle2))
                        # 將已檢查過碰撞風險的車輛添加到集合中
                        checked_vehicles.add(vehicle1)
                        checked_vehicles.add(vehicle2)
                        vehicle1_type=traci.vehicle.getTypeID(vehicle1)  
                        vehicle2_type=traci.vehicle.getTypeID(vehicle2)
                        # 根據路段類型決定駕駛風格的改變
                        if lane_type1 in ["WC", "EC", "W2W", "-E2E"]:
                            # 如果車輛1在幹道上，則駕駛風格輕微改變
                            if vehicle1_type=="Car" or vehicle1_type=="Car_truck" or vehicle1_type=="Car_moped":
                                traci.vehicle.setType(vehicle1, "Aggressive_2")
                                print("變保守")
                            elif vehicle1_type=="Aggressive" or vehicle1_type=="Aggressive_truck" or vehicle1_type=="Aggressive_moped":
                                traci.vehicle.setType(vehicle1, "Car")
                                print("變普通")
                            else:
                                print("不變")
                        elif lane_type1 in ["NC", "N2N", "SC", "S2S"]:
                            # 如果車輛1在支道上，則駕駛風格嚴重改變
                            if vehicle1_type=="Car" or vehicle1_type=="Car_truck" or vehicle1_type=="Car_moped":
                                traci.vehicle.setType(vehicle1, "Aggressive_2")
                                print("變保守")
                            elif vehicle1_type=="Aggressive" or vehicle1_type=="Aggressive_truck" or vehicle1_type=="Aggressive_moped":
                                traci.vehicle.setType(vehicle1, "Aggressive_2")
                                print("變普通")
                            else:
                                print("不變")
                             
                        if lane_type2 in ["WC", "EC", "W2W", "-E2E"]:
                            # 如果車輛2在幹道上，則駕駛風格輕微改變
                            if vehicle2_type=="Car" or vehicle2_type=="Car_truck" or vehicle2_type=="Car_moped":
                                traci.vehicle.setType(vehicle2, "Aggressive_2")
                            elif vehicle2_type=="Aggressive" or vehicle2_type=="Aggressive_truck" or vehicle2_type=="Aggressive_moped":
                                traci.vehicle.setType(vehicle2, "Car")
                            else:
                                print("不變") 
                        elif lane_type2 in ["NC", "N2N", "SC", "S2S"]:
                            if vehicle2_type=="Car" or vehicle2_type=="Car_truck" or vehicle2_type=="Car_moped":
                                traci.vehicle.setType(vehicle2, "Aggressive_2")
                            elif vehicle2_type=="Aggressive" or vehicle2_type=="Aggressive_truck" or vehicle2_type=="Aggressive_moped":
                                traci.vehicle.setType(vehicle2, "Aggressive_2")
                            else:
                                print("不變")
                            # 如果車輛2在支道上，則駕駛風格嚴重改變
                            
    traci.close()
    sys.stdout.flush()

     
'''''''''
def run():
    while traci.simulation.getMinExpectedNumber() > 0:
        traci.simulationStep()
        vehicles = traci.vehicle.getIDList()
        for i in range(len(vehicles)):
            for j in range(i+1, len(vehicles)):
                vehicle1 = vehicles[i]
                vehicle2 = vehicles[j]
                if (vehicle1, vehicle2) in calculated_collisions or (vehicle2, vehicle1) in calculated_collisions:
                    continue
                distance1 = calculate_distance_to_intersection(vehicle1)
                distance2 = calculate_distance_to_intersection(vehicle2)
                lane_type1 = traci.vehicle.getRoadID(vehicle1) 
                lane_type2 = traci.vehicle.getRoadID(vehicle2) 
                if distance1 < 150 and distance2 < 150:
                    if calculate_collision_risk(vehicle1, vehicle2,lane_type1,lane_type2):
                        print("警告：車輛 {} 和車輛 {} 存在碰撞風險！".format(vehicle1, vehicle2))
                        calculated_collisions.add((vehicle1, vehicle2))
                        calculated_collisions.add((vehicle2, vehicle1))
                        adjust_driver_style(vehicle1)
                        adjust_driver_style(vehicle2)

def adjust_driver_style(vehicle):
    lane_type = traci.vehicle.getRoadID(vehicle)
    vehicle_type = traci.vehicle.getTypeID(vehicle)
    if lane_type in ["WC", "EC", "W2W", "-E2E"]:
        if vehicle_type in ["Car", "Car_truck", "Car_moped"]:
            traci.vehicle.setType(vehicle, "Aggressive_2")
            print("變保守")
        elif vehicle_type in ["Aggressive", "Aggressive_truck", "Aggressive_moped"]:
            traci.vehicle.setType(vehicle, "Car")
            print("變普通")
    elif lane_type in ["NC", "N2N", "SC", "S2S"]:
        if vehicle_type in ["Car", "Car_truck", "Car_moped"]:
            traci.vehicle.setType(vehicle, "Aggressive_2")
            print("變保守")
        elif vehicle_type in ["Aggressive", "Aggressive_truck", "Aggressive_moped"]:
            traci.vehicle.setType(vehicle, "Aggressive_2")
            print("變普通")
'''''''''
 

if __name__ == "__main__":
    import datetime
    options = get_options()

    # 根據需要選擇sumo的二進制文件
    if options.nogui:
        sumoBinary = checkBinary('sumo')
    else:
        sumoBinary = checkBinary('sumo-gui')

    # 單獨調用一次traci.start()
    traci.start([sumoBinary, "-c", "C:/專題/NEW/Untitled-1.sumocfg"])

    # 設置一個變數來跟踪是否已經執行了traci.start()函式
    traci_started = False


    for i in range(0, 10):
        now = datetime.datetime.now()
        filename ="C:/專題/NEW/RESULT_PV{}.xml".format(i+1)
        filename2 ="C:/專題/NEW/RESULT/collinfo_PV{}.xml".format(i+1)
        filename3 ="C:/專題/NEW\RESULT_NONSTRATEGY/ssm_PV{}.xml".format(i+1)
       # 如果尚未啟動traci，則在第一次迭代時啟動
        if not traci_started:
            traci.load(["--tripinfo-output", filename,
                          "--collision-output", filename2,"--device.ssm.file",filename3, "--random"])
            traci_started = True
        else:
            # 如果已經啟動了traci，只需重新載入檔案
            traci.load(["--tripinfo-output", filename,
                          "--collision-output", filename2,"--device.ssm.file",filename3, "--random"])

         
        # 在每次迭代中执行run()函数
        run()
```
Finally, thank you once again for your help.

**Comment by m-kro** [comment]
In order to reproduce your problem we need the network file as well. Please attach all needed files zipped into one archive to this issue.

**Comment by ray92423** [comment]
[project.zip](https://github.com/eclipse-sumo/sumo/files/15321931/project.zip)
 here is a file . strategy.py is my strategy trying to implement my thought. thanks!

**Comment by m-kro** [comment]
You don't have internal links in your network, so the vehicles get teleported to the other side. Please read the [doc](https://sumo.dlr.de/docs/Simulation/Intersections.html#internal_links) about this topic carefully and eventually change your network using netconvert. Additionally you have configured very low **tau** values (lower than the time step value). This makes vehicles using unsafe following distances - you should get warned at the simulation start saying the following: 
```
Warning: Value of tau=0.45 in vehicle type 'Aggressive' lower than simulation step size may cause collisions.
Warning: Value of tau=0.75 in vehicle type 'Aggressive_2' lower than simulation step size may cause collisions.
Warning: Value of tau=0.45 in vehicle type 'Aggressive_truck' lower than simulation step size may cause collisions.
Warning: Value of tau=0.75 in vehicle type 'Aggressive_2_truck' lower than simulation step size may cause collisions.
Warning: Value of tau=0.45 in vehicle type 'Aggressive_moped' lower than simulation step size may cause collisions.
Warning: Value of tau=0.75 in vehicle type 'Aggressive_2_moped' lower than simulation step size may cause collisions.
```
