### ISSUE TITLE
Question about edge/lane allowed vehicles

### ISSUE THREAD

**Issue by NoelGK** [eclipse-sumo/sumo#14864]
Hi, 
I wanted to ask if it is possible to allow / disallow vehicles in edges (or lanes) by **emission class** instead of by vehicle class. If not possible, is it possible to find a workaround, maybe to define new vechicle classes?

Thank you in advance.

**SUMO-version: Eclipse SUMO sumo Version v1_20_0+0070-a67160a3527**

**operating system: ubuntu:20.04**

**Comment by m-kro** [comment]
That depends on how many combinations of emission class and vehicle class you actually need for your case, as the number of vehicle classes cannot be extended by the SUMO user. The purpose of vehicle classes is lane permissions and default parameter values of vehicle types (see [doc](https://sumo.dlr.de/docs/Vehicle_Type_Parameter_Defaults.html)).

Vehicle classes **custom1** and **custom2** are directly meant for user-defined semantics. If you need more categories, you could reuse some other vehicle classes for your purpose as well. Just keep in mind to overwrite default vehicle type parameter values you don't want.
