### ISSUE TITLE
"Replace junction by geometry point" crash

### ISSUE THREAD

**Issue by transport45678** [eclipse-sumo/sumo#14863]
Hello,
After opening net file, I am loading the sumo config file. When I press right click on one of the junction to convert geometry point, file is closing suddenly. 
Sumo version 1.19
[junction_geometry_point.zip](https://github.com/eclipse-sumo/sumo/files/15320499/junction_geometry_point.zip)

**Comment by m-kro** [comment]
Can you please try with the latest release ([download version 1.20](https://sumo.dlr.de/docs/Downloads.php)) and report if the problem persists?

**Comment by m-kro** [comment]
Has to do with the set route (no need to load the net file first as it is reloaded with the sumocfg anyway). Crash at

https://github.com/eclipse-sumo/sumo/blob/a67160a35279c88179d1efc8a70e73d117c6c95b/src/netedit/elements/demand/GNERoute.cpp#L551 

(key SUMO_ATTR_EDGE)

**Comment by namdre** [comment]
there were more bugs fixed with this:
- relocation additionals along the edge
- a crash involving trips
