### ISSUE TITLE
Parking issues

### ISSUE THREAD

**Issue by qch333** [eclipse-sumo/sumo#14877]
I would like to know if it is possible to automate the vehicle to find a parking lot for parking？

**Comment by namdre** [comment]
Yes: https://sumo.dlr.de/docs/Simulation/Rerouter.html#rerouting_to_an_alternative_parking_area
see also https://sumo.dlr.de/docs/Tools/Misc.html#generateparkingarearerouterspy

**Comment by qch333** [comment]
I have defined a rerouter function, but when the parking lot is full, the car still waits next to the specified parking lot and doesn't go looking for a parking lot, what's going on, do I need to call some function in Python.
[test1.zip](https://github.com/eclipse-sumo/sumo/files/15343923/test1.zip)
Attached is my file, check it out if it's handy.
![7ef08ee572f35f472158d7f69f4abe3](https://github.com/eclipse-sumo/sumo/assets/170005169/f070f5d6-0c2d-4044-9ee1-50c598230f41)

**Comment by namdre** [comment]
The rerouter must define a *list* of alternative parking areas.
Do the following:
1. delete your rerouter from the file
2. call `sumo/tools/generateParkingAreaRerouters.py -n park.net.xml -a IntellPark.add.xml -o rerouter.add.xml`
3. change your sumocfg so it has `        <additional-files value="IntellPark.add.xml,rerouter.add.xml"/>`

**Comment by qch333** [comment]
Sorry, I don't quite understand how to implement the second step of calling the function, can you tell me the exact code to implement it?

**Comment by qch333** [comment]
I've solved this one for me, thanks, I was wondering what the basis is when subsequent vehicles make parking lot selections, didn't really read it and it doesn't feel like it's based on distance either

**Comment by namdre** [comment]
The choice of alternative is based on distance by default but this is highly configurable, see https://sumo.dlr.de/docs/Simulation/Rerouter.html#determining_the_alternative_parking_area
