### ISSUE TITLE
How can I turn off the avoidance function that comes with SUMO！

### ISSUE THREAD

**Issue by AHPUymhd** [eclipse-sumo/sumo#14871]
Add your issue description here.
Let's say I have a scenario like this, green is my code-controlled car, and blue is a randomly generated car, but I found that if the green car is close to the blue car, the blue car will automatically avoid or change lanes, but in fact I didn't ask them to do that, how can I turn this feature off, because I want to test the collision rate of the green car Thank you very much！
![image](https://github.com/eclipse-sumo/sumo/assets/72792297/5b14d549-eee2-4fdf-9b3f-1da87119144d)
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by m-kro** [comment]
Did you try to disable cooperative lane changing by setting the [lane change model parameter](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models) `lcCooperative="-1"` in the vehicle type of the cyan/blue car?

**Comment by AHPUymhd** [comment]
> Did you try to disable cooperative lane changing by setting the [lane change model parameter](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models) `lcCooperative="-1"` in the vehicle type of the cyan/blue car?

Please ask how to disable this collaborative lane change, and in which code is this parameter put in, I just came into contact with sumo, and I hope to get your answer，Thank you！

**Comment by AHPUymhd** [comment]
![image](https://github.com/eclipse-sumo/sumo/assets/72792297/445713db-20c4-4265-b401-d4b2fe3eeb38)
That's how I set it up, but they still work with each other to implement automatic avoidance

**Comment by namdre** [comment]
The code block at 
https://github.com/eclipse-sumo/sumo/blob/1f5962bf309834a5180045e7b9d63f5ace142a9c/src/microsim/lcmodels/MSLCM_LC2013.cpp#L327-L405
causes speed adjustment (i.e. when blocking another vehicle and currently cannot be disabled by user inputs)

**Comment by namdre** [comment]
At the moment, the only remaining reason for speed reduction (when setting lcCooperative=-1) is when a car itself wants to change lanes and get into a better position (so not strictly cooperative).
However, this doesn't match your observation so I would ask you to put together a minimal example for reproducing your issue (and attach it as .zip here).
