### ISSUE TITLE
Question about parameters of step length

### ISSUE THREAD

**Issue by pjj-OSM** [eclipse-sumo/sumo#14878]
if i set parameters step-length=0.5 seconds, I found some vehicle don't run when green light on traffic control intersection,  please look figure 1,  pink vehicles should turn left but it is keep stopping in lane even green light. But this situation will not occur  when i set step-length=1 seconds. 
Other parameters i set: carFollowModel="Krauss" actionStepLength="0.5" sigma="0.2" tau="1" sigmaStep="0.5" gui delay is 1000. 
_**figure 1: step-length=0.5 seconds**_
![simulationlong](https://github.com/eclipse-sumo/sumo/assets/22164090/12a28951-ce1f-4dae-9c8e-9cc1a68a826e)
**_figure 2: step-length=1 seconds_**
![simulationlong1](https://github.com/eclipse-sumo/sumo/assets/22164090/7cf15f15-2ccf-462c-a294-c913c37b33eb)

**Comment by namdre** [comment]
please provide a minimal example for reproducing this issue (zip the files and attach them here)
