### ISSUE TITLE
question: toll station simulation

### ISSUE THREAD

**Issue by lindsaymorgan** [eclipse-sumo/sumo#14881]
Hello! I am currently trying to build a toll station simulation. I put a all-way-stop junction in the middle of the toll station edge and a rerouter on the entrance edge. Ideally, those cars should choose a lane with shortest queue when enter the toll station edge, but they just keep choosing the first lane. Is there a better way to build this scenario? Can I customize the stoping duration of the all-way-stop junction?

![image](https://github.com/eclipse-sumo/sumo/assets/25105493/d9158c5d-7d62-4d61-86e0-dd60a2301f77)

**Comment by namdre** [comment]
The lane choice happens because the leftmost lane has right-of-way. Instead you could build the exit as a list of staggered zipper junctions (you need more than one because you can only merge 2 lanes at a time so the first junction turns 5 lanes into 3, the second junction 3 lanes into 2 and then 2 into 1. See https://sumo.dlr.de/docs/Networks/PlainXML.html#node_types

The easiest way to model the stopping duration is with a slow-speed section. If you need vehicles to actually stand still there are other ways though: 

a) define a parkingArea on each lane and let the parkingSearch module pick a free parking area:  https://sumo.dlr.de/docs/Simulation/ParkingArea.html#rerouting_when_the_current_parkingarea_is_full

b) define a traffic light with custom switching rules where each signal switches to green after a delay when detecting a vehicle on a detector (https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#type_actuated_with_custom_switching_rules)

**Comment by namdre** [comment]
and you can use vType attribute `startupDelay` to prolong the stop but this will have side effects if vehicles stop in your scenario for any other reason (https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#available_vtype_attributes)

**Comment by lindsaymorgan** [comment]
Thank you so much!

**Comment by lindsaymorgan** [comment]
> and you can use vType attribute `startupDelay` to prolong the stop but this will have side effects if vehicles stop in your scenario for any other reason (https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#available_vtype_attributes)

Thank you so much!

**Comment by lindsaymorgan** [comment]
> The lane choice happens because the leftmost lane has right-of-way. Instead you could build the exit as a list of staggered zipper junctions (you need more than one because you can only merge 2 lanes at a time so the first junction turns 5 lanes into 3, the second junction 3 lanes into 2 and then 2 into 1. See https://sumo.dlr.de/docs/Networks/PlainXML.html#node_types
> 
> The easiest way to model the stopping duration is with a slow-speed section. If you need vehicles to actually stand still there are other ways though:
> 
> a) define a parkingArea on each lane and let the parkingSearch module pick a free parking area: https://sumo.dlr.de/docs/Simulation/ParkingArea.html#rerouting_when_the_current_parkingarea_is_full
> 
> b) define a traffic light with custom switching rules where each signal switches to green after a delay when detecting a vehicle on a detector (https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#type_actuated_with_custom_switching_rules)

hello namdre! I build a simulation following your advice, with one 4 to 2 zipper ,one 2 to 1 zipper and a slow-speed section. But in this case, cars keep entering the toll station edge from the rightmost connection, although they change to other lane soon after they enter. Is there any way to let them choose better connection before entering the toll station edge?

https://github.com/eclipse-sumo/sumo/assets/25105493/d0d6cf87-a268-43a6-a6ac-9cca9707906f

**Comment by namdre** [comment]
There currently isn't code that would allow for picking a better lane based on queue length. This is a known issue (#7157).

You could give the cars a "waypoint" with a random lane at the start of the toll section:
`sumo/tools/route/addStops2Routes.py -n net.net.xml -r input.rou.xml -o out.rou.xml --speed 20 --lane random --reledge 0.2 --relpos 0`

Note, that this requires the latest dev version of the python tool (#14895). The option `--reledge 0.2` should pick edge 2 out of an 8-edge-route.

**Comment by lindsaymorgan** [comment]
> There currently isn't code that would allow for picking a better lane based on queue length. This is a known issue (#7157).
> 
> You could give the cars a "waypoint" with a random lane at the start of the toll section: `sumo/tools/route/addStops2Routes.py -n net.net.xml -r input.rou.xml -o out.rou.xml --speed 20 --lane random --reledge 0.2 --relpos 0`
> 
> Note, that this requires the latest dev version of the python tool (#14895). The option `--reledge 0.2` should pick edge 2 out of an 8-edge-route.

I saw some recent ideas in the issue#7157, would they be added to a future release like 1.21.0 in the near future?

**Comment by lindsaymorgan** [comment]
> I hope but I can't make any promise of actually putting this into 1.21.0. I would advise on using a work-around in the meantime.

OK, I understand. Thank you so much for your help~
