### ISSUE TITLE
Display issue - Tight spacing causing GUI to be unreadable

### ISSUE THREAD

**Issue by workcomms** [eclipse-sumo/sumo#14882]
![image](https://github.com/eclipse-sumo/sumo/assets/170085212/c59bf003-7724-4141-b9b7-16b6dcbdd91a)
![image](https://github.com/eclipse-sumo/sumo/assets/170085212/a94eab23-ce2f-4cd8-bb30-f4de087385ab)

SUMO and NETEDIT GUI spacing so tight that the words are sometimes unreadable. Icons are so small that it is difficult to navigate. Please help.

**SUMO-version:** 1.20.0

**operating system:** Windows

**Comment by namdre** [comment]
This is known to happen when you use high text scaling values in your windows display settings. What is your screen resolution?
