### ISSUE TITLE
Question about getting the lane ids of an edge.

### ISSUE THREAD

**Issue by RaffaeleTranfaglia** [eclipse-sumo/sumo#14893]
Is there a way to get the lane ids composing an edge from a given edge id?
e.g. something like traci.edge.getLanesID()

In general I need a way to iterate over the lanes of a given edge.

SUMO version: 1.20.0

**Comment by m-kro** [comment]
You can use sumolib to query static network information. Please look at [how to load a network with sumolib](https://sumo.dlr.de/docs/Tools/Sumolib.html#loading_a_network_file). Then you can access [sumolib.net.edge](https://sumo.dlr.de/pydoc/sumolib.net.edge.html) to get the lanes belonging to a certain edge.

**Comment by namdre** [comment]
`laneIDs = ["%s_%s" (edgeID, i) for i in range(traci.edge.getLaneNumber(edgeID)]`

**Comment by namdre** [comment]
Be asured that lanes always follow this naming scheme.
