### ISSUE TITLE
SUMO GUI option "Draw with constant size when zoomed out" doesn't work well for aircrafts

### ISSUE THREAD

**Issue by schwepmo** [eclipse-sumo/sumo#14899]
While playing around with SUMO's new aircrafts I've come across some very wide planes, while using the option "Draw with constant size when zoomed out".
I'm not sure whether that only occurs on my machine or is a general bug.

I've attached a screenshot and the small test scenario.

![grafik](https://github.com/eclipse-sumo/sumo/assets/39306374/340a9d58-9158-4381-8d90-30e57cf90703)
[airplaines.zip](https://github.com/eclipse-sumo/sumo/files/15400471/airplaines.zip)
**SUMO-version:** 1.20.0

**operating system:** Windows 11

**Comment by namdre** [comment]
Thanks for bringing this up!
