### ISSUE TITLE
Question about traci road/lane control

### ISSUE THREAD

**Issue by lindsaymorgan** [eclipse-sumo/sumo#14897]
Hello! I am currently working on highway simulation. There is one kind of situation that when a car accident occur, the traffic police will open the emergency lane for normal vehicles to pass in case of huge traffic jam happens. Since the edges of highway are always very long compared to the accident-area, they only want to open part of the emergency lane, instead of opening the whole section of emergency lane for its full length. And we cannot predict where the car accident will occur, so it is impossible to split the edge in advance. Is there any clever way to realize this control by traci?

Thank you so much for your advice.

**Comment by namdre** [comment]
If you process your network with something like 
`netconvert -s net.net.xml --geometry.max-segment-length 200 --geometry.split  -o net2.net.xml`
you can get enough shorter edges to then close a custom section as needed.

**Comment by lindsaymorgan** [comment]
> If you process your network with something like `netconvert -s net.net.xml --geometry.max-segment-length 200 --geometry.split -o net2.net.xml` you can get enough shorter edges to then close a custom section as needed.

Thank you so much for the advice! There is just one thing that I concern about, as highway is usually extremely long, will it largely increase the computation time for the simulation?

**Comment by namdre** [comment]
My guess is "No" unless you make the edges very short.
There is hardly any difference if you split a road in 200m segments but with 10m segments the running time could increases as a much as by a factor of 10.

**Comment by lindsaymorgan** [comment]
> If you process your network with something like `netconvert -s net.net.xml --geometry.max-segment-length 200 --geometry.split -o net2.net.xml` you can get enough shorter edges to then close a custom section as needed.

Hello! I am using the command you provide to split my road network. It seems to add a geometry point every 200m and then split  edges across geometry nodes. The problem is, I have too many ramps in my network and there are always a lot of geometry points in the ramps.  Splitting by geometry point will result in a road network with many short edges. Is there a way to split edges only by 200m but ignore other geometry points?
![image](https://github.com/eclipse-sumo/sumo/assets/25105493/9061827f-4d95-4990-a2fe-039fadfac6bc)

**Comment by namdre** [comment]
If you can live with a slight reduction in geometry detail you can also set option ** --geometry.max-segment-length 100** to reduce geometry detail on the ramps.

**Comment by lindsaymorgan** [comment]
> If you can live with a slight reduction in geometry detail you can also set option **--geometry.max-segment-length 100** to reduce geometry detail on the ramps.

Thanks~ I will have a try.

**Comment by namdre** [comment]
my mistake, the command you want to reduce the minimum segment size is:  **--geometry.min-dist 100**
