### ISSUE TITLE
My vehicle does not disappear automatically when using SUMO simulation

### ISSUE THREAD

**Issue by idl-KevinKaslana** [eclipse-sumo/sumo#14898]
I tried to use the randomTrips tool to generate a vehicle path, but when I simulated it I found that my vehicle would not disappear automatically after arriving at the destination and was still displayed above. Additionally, vehicles exhibit overlapping behavior when waiting at intersections. I want to know what should I do
*If possible, upload an example that shows your problem.*

**SUMO-version:1.190

**operating system:windows10

**Comment by m-kro** [comment]
Does the vehicle actually arrive at the very end of the last route edge or is it blocked by some other vehicle short before that?
Can you show us a screenshot of the overlapping vehicles? Do vehicles overlap when their paths cross?

**Comment by idl-KevinKaslana** [comment]
Like this!Multiple cars stacked on top of each other! I don't know what happened
![image](https://github.com/eclipse-sumo/sumo/assets/93482508/19c16736-9c63-40ed-814a-228d9abf47aa)


![carposition](https://github.com/eclipse-sumo/sumo/assets/93482508/a9a2338a-7a86-4c07-8234-cc0855fe2744

**Comment by m-kro** [comment]
Please check whether you have set a custom length value for the edge length (instead of relying on the one computed from geometry). Additionally go the visualization settings for vehicles and look whether "Scale with geometry length" is deactivated. Both together can lead to stacked vehicles in the GUI.

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/Distances.html

**Comment by idl-KevinKaslana** [comment]
Maybe it's not because of this problem. I redefined two two-way traffic flows on a road, but I found that the vehicles would return to the other traffic route after traveling. How should I set up my traffic flow so that the vehicles will automatically disappear after reaching the end point?
![image](https://github.com/eclipse-sumo/sumo/assets/93482508/4b6f5adf-d791-402d-8d3c-4e5a819e321a)

**Comment by idl-KevinKaslana** [comment]
![image](https://github.com/eclipse-sumo/sumo/assets/93482508/46bcc80a-b316-4d06-8855-e384993d97c4)
This is my defined vehicle endpoint

**Comment by m-kro** [comment]
You can inspect the vehicle's route through the context menu (right click on the vehicle, "Show current route"). You can show the edge IDs in the GUI as well (e.g. in the visualization settings). Then compare it with the definition in your routes files to see what it is really happening.
