### ISSUE TITLE
Wiedemann 74 model 

### ISSUE THREAD

**Issue by khzannat** [eclipse-sumo/sumo#14905]
HI, 
I want to do a local area traffic simulation using 2 parameters Wiedemann 74 model. I need to specify average standstill distance and safety distance (which has both additive and multiplicative random component) along with other car following components (minGap, accel, decel, tau, step length). However, in the given [link ](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#car-following_model_parameters) for Wiedemann two parameters model there are two attributes "security" and "estimation". How these  attributes are linked with the required parameters for Wiedemann model? Also, how can I specify the average standstill distance and safety distance component of Wiedemann model using default settings of sumo? Or, do I need to implement the 74 model as a new car following model?  Could you please share any additional documentation or example project of 2 parameters Wiedemann 74 model implemented using sumo.

**Comment by namdre** [comment]
- the 'ax' component (minimum brutto standstill distance) is controlled by the 'security' parameter as `ax = veh_length + 1. + 2. * security`
- the safety distance 'bx' is also controlled by security as `bx = (1 + 7 * security) * sqrt(velocity)`

The estimation parameter influences the distance threshold between following and freeflow behavior.

For details refer to the code at https://github.com/eclipse-sumo/sumo/blob/main/src/microsim/cfmodels/MSCFModel_Wiedemann.cpp

**Comment by namdre** [comment]
you may be interested in #14907

**Comment by namdre** [comment]
Also, the original Work by Wiedemann (including the formulas for ax and bx) can be found at: https://www.researchgate.net/profile/Peter-Vortisch/post/Where-I-can-find-the-mathematical-formulation-of-Wiedemann-99-car-following-model/attachment/59d64455c49f478072eacc42/AS%3A273739390881792%401442275965040/download/Wiedemann+72+Scan+low+quality.pdf?_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6Il9kaXJlY3QiLCJwYWdlIjoicXVlc3Rpb24ifX0

**Comment by khzannat** [comment]
Thank you very much. It was really helpful.  In the given [link](https://github.com/eclipse-sumo/sumo/blob/main/src/microsim/cfmodels/MSCFModel_Wiedemann.cpp), I found there is not need to specify the tau. Perception and reaction related factors are all governed by the random component (ex). If I specify or not specify tau in the vType does it has any implication with the estimation. It came into my mind while I see in the code "stopping" convention is derived from the krauss concept and tau is a crucial component in krauss model.

**Comment by namdre** [comment]
tau is only relevent for car-following so it doesn't affect the Krauss-safeStopSpeed code (used for intersections and schedule stops).

**Comment by khzannat** [comment]
Does there need to be an upper limit on the security and estimates parameter? Or they can be anything greater than 0?

**Comment by namdre** [comment]
there is technical reason for an upper limit.
