### ISSUE TITLE
How do I make my vehicle disappear?

### ISSUE THREAD

**Issue by idl-KevinKaslana** [eclipse-sumo/sumo#14906]
I hope that the number of vehicles will be in a stable state during the simulation process. I use the vehicle route generated by the randomTrips tool. The number of vehicles on the road network will gradually increase over time. How can I control the vehicle to disappear when generating the vehicle path?

**SUMO-version:1.19

**operating system:windows 10

**Comment by namdre** [comment]
See https://sumo.dlr.de/docs/FAQ.html#how_do_i_maintain_a_constant_number_of_vehicles_in_the_net
