### ISSUE TITLE
Removal of (JuPedSim) pedestrians in vanishing area with period < 1 not working correctly

### ISSUE THREAD

**Issue by RNippold** [eclipse-sumo/sumo#14900]
In file src/microsim/transportables/MSPModel_JuPedSim.cpp 1 pedestrian is removed in a vanishing area, if time - area.lastRemovalTime >= period (line 380) and a pedestrian is present at all. This works for values > 1 (e.g. (period) value = 2 -> 1 person each 2 seconds). However, in case the desired removal rate is below 1 (1000 in SUMOs internal resolution), then - regardless of what value you choose - a maximum of one person per time step (usually 1 second) is removed. Here, an array of length period/100 of available person IDs show be selected for removal. 

**SUMO-version:** any

**operating system:** OS-indepent

**Comment by behrisch** [comment]
@bcoueraud87 for you

**Comment by bcoueraud87** [comment]
@behrisch Please assign me.

**Comment by behrisch** [comment]
solved with #15021
