### ISSUE TITLE
Assign Dwell Times to Persons

### ISSUE THREAD

**Issue by denharma** [eclipse-sumo/sumo#14903]
I would like to assign the time it takes people to get on (or off) a bus or taxi **to a person** (and not to the vType, as is currently the case). This would help differentiate between people who are faster and those who take more time (e.g. due to an impairment or luggage transportation). 

As discussed at the SUMO User Conference 2024, it might be a possibility to assign people a factor that scales the boarding time of the vType. I think that would definitely help me, but maybe there are also other options.

In my case, I have a list of empirically measured dwell (stop) times, that I would like to use for a SUMO Simulation.  Each person who is picked up by a taxi or bus should be assigned one of the times from the list for the boarding/alighting process. 

If anything in my explanation is unclear, please let me know. I look forward to your solution - and thank you in advance!

*If possible, upload an example that shows your problem.*

**SUMO-version: 1.20.0**

**operating system: Windows**

**Comment by namdre** [comment]
this was already implemented in #14869
