### ISSUE TITLE
Max stop duration cannot be loaded from state

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#14904]
Discovered via #14793 .

1. set an infinite stop by calling `traci.vehicle.setStop` (without explicit duration argument)
2. save the state
3. load the state: stop element contains `duration="92233720368547758.07"`, converting into SUMOTime fails

**Comment by namdre** [comment]
there are two bugs here actually:
1. writing SUMOTime_MAX failed because of a special rounding related code path
2. converting the double value of SUMOTime_MAX back into a SUMOTime was creating a negative time value due to overflow.
