### ISSUE TITLE
Additional files compatibility Windows/Linux

### ISSUE THREAD

**Issue by anaferraz** [eclipse-sumo/sumo#14908]
I was initially using SUMO for windows in my computer then I switched to SUMO installed in Linux in a remote machine. 
I am able to connect to SUMO and load the configuration file, but the additional files I get this error:
I checked the additional file, the loops_detectors.xml and it contains the attribute period in that line 6. 

Message in Jupyter Notebook:
***Starting server on port 55311 ***
Loading net-file from 'sumo/BahrainConfig.net.xml' ... done (43ms).
Loading additional-files from 'sumo/loops_detectors.xml' ... 
Loading of additional-files failed.
Error: attribute 'period' is not declared for element 'inductionLoop'
 In file 'sumo/loops_detectors.xml'
 At line/column 6/128.

First 10 lines of loops_detectors.xml (removed <):
```
?xml version="1.0" encoding="UTF-8"?>

!-- generated on 2024-04-22 14:13:48 by Eclipse SUMO netedit Version 1.17.0
-->

additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">
    !-- Detectors -->
    inductionLoop id="loop_seg_0_after_0" lane="seg_0_after_0" pos="50.00" period="1.00" file="loop_detector_metrics.xml"/>
    inductionLoop id="loop_seg_0_before_0A" lane="seg_0_before_0" pos="-1.00" period="1.00" file="loop_detector_metrics.xml"/>
    inductionLoop id="loop_seg_0_before_0B" lane="seg_1_before_0" pos="-1.00" period="1.00" file="loop_detector_metrics.xml"/>
```
Quitting (on error).
malloc_consolidate(): unaligned fastbin chunk detected

**SUMO-version 1:**
Eclipse SUMO sumo Version v1_19_0
**operating system 1:**
Microsoft windows 10 enterprise 

**SUMO-version 2:**
Eclipse SUMO sumo Version v1_13_0
**operating system 2:**
Linux-5.14.21-150400.22-default x86_64 GNU 8.5.0 Release FMI Proj GUI SWIG GDAL GL2PS

**Comment by namdre** [comment]
this is not a windows/linux thing but rather a SUMO version related problem. Simply upgrade your version on linux to 1.19 (or better yet 1.20)

**Comment by anaferraz** [comment]
It works after the updated version 👍
