### ISSUE TITLE
netconvert core dump when converting from osm map

### ISSUE THREAD

**Issue by NotACoin** [eclipse-sumo/sumo#14917]
When doing an import of osm map directly from the website (go on openstreetmap.org, do an export and download the map.osm), using the following command:

`netconvert --osm-files map.osm -o map.net.xml`

gives sometimes the following fatal error:

`netconvert: ./src/netbuild/NBAlgorithms.h:193: double NBNodesEdgesSorter::edge_by_junction_angle_sorter::getConvAngle(NBEdge*) const: Assertion 'angle >= 0 && angle < (double)360' failed.
Abandon (core dumped)`

From my understanding, it means some roads are cut and make weird angles, probably at the limits of the map because it does not happen all the time (a very small map will (almost?) never have this problem).

Is there is a way to avoid this error and let netconvert converting the file despite those weird road angles he find?

Thank you!

**Comment by namdre** [comment]
Which version of SUMO are you using? Can you attach a minimal map.osm file (zipped) for reproducing the problem?

**Comment by NotACoin** [comment]
I'm using the version 3.41. 

[map.zip](https://github.com/eclipse-sumo/sumo/files/15430737/map.zip)

**Comment by namdre** [comment]
The problematic code was removed in 3773e05bf56d7b2b1ada843c5f0ee1b90c09ee67 so the easiest fix is to upgrade to the latest release: https://sumo.dlr.de/docs/Downloads.php#linux
