### ISSUE TITLE
retrieval of prior stops after rerouting

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#14918]
rerouters and TraCI can trigger a call to `replaceRoute` which deletes all information about the previous route (in contrast, `replaceRouteEdges` allways appends to the prior route route and preserves history).

When stops where recorded on the prior route, they potentially no longer fit after replaceRoute. 
We must either

- erase those past stops from history or
- change the behavior of `replaceRoute` so that it creates a new custom route that preserves history (just like replaceRouteEdges) - this implies that the routeID of the vehicle is different from the one that was set 

The problem comes up in the context of state-saving and loading (Related to #14793) but is also relevant without  saving/loading.

@behrisch comments?

**Comment by m-kro** [comment]
Went for the first option: If the lane mentioned in the stop parameters is not part of an edge in the updated route, then this entry is removed from the past stops.
