### ISSUE TITLE
How to do congestion visualisation at edge level in sumo

### ISSUE THREAD

**Issue by xueshulj** [eclipse-sumo/sumo#14921]
How can I visualise at the level of edges instead of lanes, as shown in the figure below, I want to show the occupancy change in the simulation interface, but the interface can only show for each lane, and I want the occupancy or density change for each edge, can this be achieved by traci or other methods? Thanks.
![20](https://github.com/eclipse-sumo/sumo/assets/170793613/728aea67-b64d-4b98-a735-2ef836ee5085)

**SUMO-version:sumo-1.19.0

**operating system:**Windows10

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/sumo-gui.html#using_live_data
and for more details also:
https://sumo.dlr.de/docs/sumo-gui.html#visualizing_edge-related_data
https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html

**Comment by namdre** [comment]
for static images, there is also https://sumo.dlr.de/docs/Tools/Visualization.html#plot_net_dumppy
