### ISSUE TITLE
Vehicles performing lane changes at signalized intersections

### ISSUE THREAD

**Issue by oshadajay** [eclipse-sumo/sumo#14926]
In the attached video, if you focus your attention to the vehicles entering from the east direction of the junction, the vehicle on the left lane waits and does a lane change very close to the traffic light. Usually lane changes are not allowed near traffic lights and I think the lane change should occur after the vehicle has crossed the intersection. Is there a way to modify this behaviour? Thank you.

https://github.com/eclipse-sumo/sumo/assets/55861474/93a40ece-2d73-4907-abd0-d0158e99b664

**SUMO-version:**
1.20

**operating system:**
Windows

**Comment by namdre** [comment]
The langechange is prompted by the parked vehicle on the left lane downstream of the intersection. You can do either one of the following:
- set a low value for lcStrategic in the vType  (to make the vehicle care less about the blocked left lane)
- enforce a lane strange prohibition ahead and/or on the intersection by setting attribute changeRight="authority" to prevent normal vehicles from changing to the right. It may be necessary to split the upstream edge because the setting applies to the full length of a lane.

**Comment by oshadajay** [comment]
@namdre Thank you so much for the reply. Could you please let me know how can I set the attribute changeRight="authority" for  a lane segment? I cannot find such an option for an edge on netedit. Thank you.

**Comment by namdre** [comment]
you need to edit the lane attributes: https://sumo.dlr.de/docs/Netedit/elementsNetwork.html#lanes

**Comment by oshadajay** [comment]
@namdre Thank you. If we change this attribute in the upstream lanes would that ensure there won't be any lane changes on the intersection itself as well?

**Comment by oshadajay** [comment]
These are the connections right? If we add two more tags saying changeLeft="authority" and changeRight="authority", would that stop all lane changes on the intersection?

![image](https://github.com/eclipse-sumo/sumo/assets/55861474/9c7f3884-dafe-4815-b866-fe8d67c1bf70)

**Comment by namdre** [comment]
Don't try to do this in the .net.xml (there are some other parts that would need to be changed as well). Set the connection attributes in netedit: https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#setting_connection_attributes

**Comment by oshadajay** [comment]
Oh right. Thank you. So if I change the attributes of the 4 connections that go straight in the left lane that would be sufficient to prevent vehicles moving from left lane to the right lane I think?

![image](https://github.com/eclipse-sumo/sumo/assets/55861474/eff9b777-eb6c-421b-ab4f-5a46a465aa84)

**Comment by namdre** [comment]
yes

**Comment by oshadajay** [comment]
@namdre Thank you very much. Much appreciated.
