### ISSUE TITLE
car following mode IDM

### ISSUE THREAD

**Issue by ewssss** [eclipse-sumo/sumo#14923]
I am currently using the IDM model to simulate car following behavior。I want to use the IDM model to simulate different levels of autonomous driving. I'm having trouble expressing the reaction times of different levels of autonomous driving in sumo.
I want to use two methods to represent recation time.
（1）There is actionStepLength in sumo. I want to use this parameter table to represent the reaction time, but the description of this parameter is very brief. Can you explain to me in detail what this parameter does?
（2）I noticed stepping in the IDM model, but it doesn't seem to play the role described in my actual application。
Can I use actionStepLength or stepping to represent the reaction time, and if so, how should I use them to represent an exact reaction time, such as 0.8s.

**Comment by namdre** [comment]
Did you find this explanation yet: https://sumo.dlr.de/docs/Car-Following-Models.html#model_parameters ?

**Comment by ewssss** [comment]
是的我已经看过这个内容了。Yes, I have seen this content. but, I have some doubt. I understand the role of actionStepLength in practical applications is that  if  I set simulation step as 0.1s ,and actionStepLength as 1s.the vehicle will keep constant speed and 
 aceleration is 0 until 1s upstade .but the fact is different . i can see the vehicle uptade speed and aceleration  every 0.1s.

**Comment by ewssss** [comment]
Yes, I have seen this content. but, I have some doubt. I understand the role of actionStepLength in practical applications is that if I set simulation step as 0.1s ,and actionStepLength as 1s.the vehicle will keep constant speed and
aceleration is 0 until 1s upstade .but the fact is different . i can see the vehicle uptade speed and aceleration every 0.1s.

**Comment by namdre** [comment]
can you provide a minimal input example for the non-constant acceleration between action steps? (just attach simulation input files here as a .zip archive)

**Comment by ewssss** [comment]
thanks for your reply. this is my simulation files. It sets simulation step0.1s and actionStepLength as 1s,
but the output file express that the state of vehicle is upstaed every 01s. 
[sumo.zip](https://github.com/eclipse-sumo/sumo/files/15463241/sumo.zip)

**Comment by namdre** [comment]
change `actionstepLength` to `actionStepLength` with a capital `S` and this is how the acceleration will look like:

![Screenshot from 2024-05-29 09-43-19](https://github.com/eclipse-sumo/sumo/assets/6240630/6e7bb69a-d4b3-47c6-8041-16b54e2d70e1)
