### ISSUE TITLE
Converting shapefiles to SUMO XML network file

### ISSUE THREAD

**Issue by SongKun2023** [eclipse-sumo/sumo#14924]
Add your issue description here.
Hi, Sir, I have an existing shapefile of some roads, but the geometric direction is opposite to the actual driving direction. So ,if I use "netconvert" to convert shapefiles to SUMO XML network file,  it will generate a net.xml file that the driving direction is wrong. I want to know  if there is any options or suggestions to solve this problem.

*If possible, upload an example that shows your problem.*

**SUMO-version:** 1.19.0

**operating system:**win10

**Comment by m-kro** [comment]
Can you please check your shape input file regarding the [attributes](https://sumo.dlr.de/docs/Networks/Import/ArcView.html#defining_the_input) netconvert reads information from? The attribute name for the driving direction is **DIR_TRAVEL**.

**Comment by m-kro** [comment]
Yes, you have to supply additional data with the shapes, e.g. the driving direction.

**Comment by SongKun2023** [comment]
OK, thanks again. I will try.
