### ISSUE TITLE
How to use edge data for visualisation

### ISSUE THREAD

**Issue by xueshulj** [eclipse-sumo/sumo#14922]
Hi, I would like to ask why after I load edge data it still shows no data? How can I use edge data for visualisation?

![2](https://github.com/eclipse-sumo/sumo/assets/170793613/10002415-82b4-47cd-a9c0-d7e912b1976e)
![0](https://github.com/eclipse-sumo/sumo/assets/170793613/4346c9a2-8951-4fd3-aae7-e33a9903e1b7)

**SUMO-version:** 1.19.0

**operating system:** windows10

**Comment by namdre** [comment]
Press the "recalibrate rainbow" button to add a color scale.

**Comment by rummel123** [comment]
You also need to let the simulation run to the time interval you want to show. Possibly the first interval starts later as the simulation starts...
