### ISSUE TITLE
Segmentation fault in netconvert

### ISSUE THREAD

**Issue by gladysmcgan** [eclipse-sumo/sumo#14930]
Hi, I'm trying to run netconvert on a modified OSM file (majority of roads with highway=service were removed), but it doesn't go through because of a segmentation fault. I've tried to find where the problem is from by changing different netconvert options, and seems to be because of a combination of my netccfg and enabling the keep-edges.by-type option (if applied individually, netconvert runs). 

`--keep-edges.by-type highway.motorway,highway.motorway_link,highway.trunk,highway.trunk_link,highway.primary,highway.primary_link,highway.secondary,highway.secondary_link,highway.tertiary,highway.tertiary_link,highway.unclassified,highway.residential,highway.living_street,railway.tram,highway.service`

Would appreciate any help or tips! Thanks!

The original file, and the modified file and the netccfg file are here: [issue.zip](https://github.com/eclipse-sumo/sumo/files/15470875/issue.zip)

**SUMO-version:**
v1_19_0+1749-50b24f5787f
**operating system:**
macOS

**Comment by namdre** [comment]
regression in 1.20.0

**Comment by gladysmcgan** [comment]
Thank you!
