### ISSUE TITLE
Is it possible to get vehicle info for lane ID and lane position in meso sim?

### ISSUE THREAD

**Issue by xmskk** [eclipse-sumo/sumo#14933]
I know that it's conventionally not supported to retrieve laneID for a vehicle in meso sim.

![스크린샷 2024-05-28 153917](https://github.com/eclipse-sumo/sumo/assets/28818052/f91bcd57-6158-4a52-aa15-96609d598da2)

But even in a meso sim, I can see in the GUI where the vehicles are specifically at each step, and I would like to retrieve that info.

Currently calling function getLanePosition(veh_ID) somewhat works but shows to undesirable behaviors (e.g., returning 0).

Calling getLaneID(veh_ID) does not work at all and always returns "".

Ultimate goal is to transfer that info into a micro sim and have the vehicles spawn at their correct positions, not at the start of their edges.

**SUMO-version: 1.20.0**

**operating system: Ubuntu 22.04**

**Comment by namdre** [comment]
You can get lanePosition at segment resolution. This means you won't always get 0 (if the edge is split into multiple segments).
The gui uses the following formula to interpolate vehicle positions:
`getLanePosition() + segmentLength * (now - entryTime) / (intendedLeaveTime - entryTime)` 

However, the value of entryTime isn't exposed via TraCI. You can (almost) get the intended leaveTime by calling `traci.vehicle.getLastActionTime` (strangely enough).  - ( #14935)

Maybe we could expose the interpolated position directly: #14936 (such a position could be used directly as microsim input easily converted into a lane-position)

**Comment by xmskk** [comment]
Thank you for clearing that up.

From my investigation, it seems that getPosition() always returns the coordinates of getLanePosition() on lane XXX_0.

Do you have any insight as to how the GUI determines the lane the vehicle is shown on?

**Comment by namdre** [comment]
When there are turn lanes ahead of an intersection, then the appropriate lane will be used. Otherwise it's always lane 0
(unless you set option **--meso-lane-queue**  in which case the whole meso simulation will be lane-based rather than edge based).

**Comment by behrisch** [comment]
If we have lane queues we can expose the mapping

**Comment by xmskk** [comment]
So I've looked into this and I think I see what you mean. In the GUI I can click on the parameters of a vehicle and the queue value seems to report the lane index.

I'm currently having trouble retrieving it in code however. I was trying to use traci.vehicle.getParameter(veh_id, KEY) but I don't think there is a key that supports this function?

**Comment by namdre** [comment]
fixed via #15341
