### ISSUE TITLE
Run multiple scenario sequentially

### ISSUE THREAD

**Issue by juun9714** [eclipse-sumo/sumo#14938]
Hello, I'm using sumo-gui and libtraci for my C++ project. 

I want my project to run multiple scenario(or repeat one scenario repeatedly) without any user interaction once I run simulation at first. I mean, if I start simulation once, I want my code to run multiple scenario sequentially. I'm using libtraci in C++ project. 

I tried **libtraci::Simulation::close()** and **libtraci::Simulation::start()**, but after first simulation secondly poped-up sumo-gui does not run properly. 

![image](https://github.com/eclipse-sumo/sumo/assets/64214295/9e159ace-28c7-41e0-a30c-9c726fffef38)

![image](https://github.com/eclipse-sumo/sumo/assets/64214295/ab3aa4b3-8355-4044-be22-3d774369ff3f)

**SUMO-version:1.19.0**

**operating system:Windows**

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/FAQ.html#how_to_perform_repeated_simulations_with_different_results
(you can use it also to run different configurations with the same seed or even the same seed repeatedly.
Use options **-S -Q** if you want to run with sumo-gui (but if there is nobody watching, running 'sumo' is even faster than 'sumo-gui').

**Comment by namdre** [comment]
If you want to do repeated runs with libsumo/libtraci, then instead of calling `start`, call `Simulation::load`

**Comment by juun9714** [comment]
Thanks! Before `Simulation::load()`, should I Simulation::close() ? or just call `Simulation::load()` when I want to restart it?

**Comment by namdre** [comment]
`load` by itself is enough.
