### ISSUE TITLE
Preserving link tls index

### ISSUE THREAD

**Issue by transport45678** [eclipse-sumo/sumo#14947]
Hello,
For instance, I have four-legged signalized intersection, and each leg consists of two lane. When I would like to add number of lanes, link tls index is updating also. What is the easiest way of preserving link tls index? Thank you for help,regards.

Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
If you add lanes using context menu function 'duplicate lane' then the link indices will be preserved.
You can then do the following:
1. in tls mode, edit the signal plan using button 'add states' (as many times as you want to add connections)
2. save tls edit
3. add a connection
4. inspect the connection and manually set the linkIndex attribute to one of the new index values (higher then the existing ones)
5. compute with F5 (all other indices are preserved)

**Comment by transport45678** [comment]
If I would like to delete connection, is it possible to made reverse process? I could not achive, Am I wrong?

**Comment by namdre** [comment]
deleting a connection should generally not change tls indices.
