### ISSUE TITLE
Transport limited to one container if using the taxi device

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#14943]
The taxi device limits the customer count to 1 by default, even if transporting containers. It seems the group option is only available for person rides?

**Comment by namdre** [comment]
according to the tests it's working.

**Comment by m-kro** [comment]
This is the container definition (from port Lübeck scenario):
```
    <containerFlow id="containertoship" begin="triggered" number="15" color="255,0,255"> 
        <transport from="149084838#0" containerStop="containerStop_trainstation" lines="train"/>
        <tranship containerStop="containerStop_truck_trainstation"/>
        <transport containerStop="containerStop_pier" lines="taxi"/>
        <tranship containerStop="containerStop_waterway"/>
        <transport to="5005413.18170" lines="containership"/>
    </containerFlow>
```
Calling sumo with **--persontrip.default.group g0** will not help here.

**Comment by m-kro** [comment]
It is an example case for #6552: Due to the temporal distribution of appearing containers and free vehicles the dispatch will assign one container per vehicle...
