### ISSUE TITLE
How to convert a preprocessed OSM network into SUMO network?

### ISSUE THREAD

**Issue by zihaooo** [eclipse-sumo/sumo#14942]
I have a preprocessed OSM file for another project. 

The preprocessing includes 
1. Cutting a long way to several short ways based on intersections it passes;
2. Splitting each (bi-direction) way into two separate single-direction ways and give them new IDs based on the original ID.

This preprocessed OSM file can be converted to SUMO networks, but the intersection became strange.
![image](https://github.com/eclipse-sumo/sumo/assets/64977999/a3a99f60-4b7f-4a5e-86dd-8557bc6b6cce)

I use the following command to do the conversion:
```bash
netconvert --osm test.osm --output.original-names -o test.net.xml
```

I also attached the minimum replicable examples.

If I want to use this preprocessed OSM work, which direction should I work on to solve this issue?

Thank you in advance, and I appreciate your time.

**SUMO-version: 1.20.0**

**operating system: Ubuntu 22.04**

[examples.zip](https://github.com/eclipse-sumo/sumo/files/15493508/examples.zip)

**Comment by namdre** [comment]
note, that netconvert does the same things (cutting at intersections and creating two directional edges out of an osm way).

**Comment by namdre** [comment]
set netconvert option **--osm.oneway-spread-right** during import and it will look fine.

**Comment by zihaooo** [comment]
Thank you so much for getting back to me so quickly. After applying **--osm.oneway-spread-right**, the road is no longer twisted. But it seems to have multiple stoplines/stopbars at the intersection. Is this just for visuals, or will it influence the simulation as well?

**Comment by zihaooo** [comment]
I think **-R --junctions.join** can help. Thank you.
