### ISSUE TITLE
Default distribution of vehicle generation in randomTrips.py

### ISSUE THREAD

**Issue by Kunal-Kumar-Sahoo** [eclipse-sumo/sumo#14958]
What is the default vehicle generation distribution in randomTrips.py script? Can we add more distributions?

**Comment by m-kro** [comment]
Please have a look in the SUMO docs:

- [Options for spatial distribution](https://sumo.dlr.de/docs/Tools/Trip.html#edge_probabilities) (customise more with custom[ edge weights](https://sumo.dlr.de/docs/Tools/Trip.html#customized_weights))
- [Options for temporal distribution](https://sumo.dlr.de/docs/Tools/Trip.html#traffic_volume_arrival_rate)
