### ISSUE TITLE
segmentation fault when running large sim

### ISSUE THREAD

**Issue by ambuehll** [eclipse-sumo/sumo#14963]
segmentation fault between sim sec 22200 and 25500
large network. device-rerouting-threads > 2 yields the segmentation fault. 
probably related to mac issues discussed previously; we'll run it on linux to double check. still wanted to report this quickly

**SUMO-version:** v1_20_0+0303-e59185a10d5
https://drive.google.com/file/d/1YwjHAgt2EFsGT6beUtAOhBYZuzEF86h_/view?usp=sharing (access only for @namdre currently)

**operating system:** macos

Thanks as always.

**Comment by ambuehll** [comment]
problem also persists in linux.

**Comment by namdre** [comment]
is this with enabled extra code to make routing randomness stable?

**Comment by namdre** [comment]
crash on simultaneous access to an std::set via `MSInsertionControl::descheduleDeparture`

**Comment by namdre** [comment]
an easy workaround would be to filter out invalid trips

**Comment by ambuehll** [comment]
perfect. thanks! we'll do that in that case.
