### ISSUE TITLE
How to merge two opendrive road networks and convert them into one sumo network？

### ISSUE THREAD

**Issue by JackYang2022** [eclipse-sumo/sumo#14961]
Hello everyone, I have two OpenDrive networks, and some of them overlap. How can I merge them into one Sumo road network? I tried to convert them separately to .net.xml files and then merge them using the "netconvert -- sumo net file road1.net.xml, road2.net.xml." command, but it prompted me with duplicate edges and some overlapping nodes that failed to be processed. How should I solve this error or use what method to merge the road network？Thank you！

**SUMO-version:1.8.0**

**operating system:Win10**

**Comment by namdre** [comment]
1. get a newer version of netconvert
2. set options for dealing with duplicate edges and nodes: https://sumo.dlr.de/docs/netconvert.html#merging_networks
