### ISSUE TITLE
Collision avoidance while using sumo

### ISSUE THREAD

**Issue by prasuka4** [eclipse-sumo/sumo#14969]
Hi,
I have tried to use traci to control the speed of the vehicle with traci.vehicle.setspeed. Due to this vehicle is getting collided with other vehicles. Is there any way where vehicle can avoid collision by detecting the vehicle ahead and make necessary lane changes or apply brake.
please do let me know any possible solution

**SUMO-version:**
SUMO - V 1-19
**operating system:**
Windows 11

**Comment by namdre** [comment]
if you don't call setSpeedMode, safety features should remain in affect by default: https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#speed_mode_0xb3

**Comment by prasuka4** [comment]
Hi I have not used setspeedmode earlier. 

I have also tested speed modes now but none of them were not giving expected output.
Vehicle is getting collided with other. Below snap is configuration for your reference.
Please do let me know if any other information required.

![Untitled](https://github.com/eclipse-sumo/sumo/assets/48856575/f66c82dc-6f1a-4c11-a9ca-f68e6cc84bb4)

**Comment by namdre** [comment]
please provide all input files for reproducing your problem (attach them as a zip archive here)

**Comment by prasuka4** [comment]
Hi,
Please do have a look at the sample files that are being shared for your reference
[Uploading DLR_Sample.zip…]()

**Comment by namdre** [comment]
The problem comes from
```
        if step > 100:
            traci.vehicle.moveToXY("Car", edgeID='E0', lane=0, x=260, y=-1.6)
```

The vehicle 'Car' is  moved (to the same spot) in every step after stop 100. While the other cars expect it to drive at a speed of 25m/s (and this is what it would naturally do), it is practically "beamed" backwards to the same spot. each step. 

If you want the car to keep staying in place, then issuing a setSpeed('Car', 0) fixes the problem (calling `setStop` would be even better). Otherwise reconsider the condition for calling moveToXY.

**Comment by prasuka4** [comment]
Thank you for your response, but if we have list of position that need to be updated at regular interval of time then, moveToXY need to be used. In that case the remaining vehicles will collide and pass over each other. Is it possible with any other means to avoid the collision or is there any alternate method.
Please do let me know 
Thanks in Advance

**Comment by prasuka4** [comment]
Hi I have tried to set low speeds based on previous suggestions, but to make vehicle move on list of specific x and y position along with along with variable speed is there any other possible way apart from using moveXY and setspeed to avoid collision.
Please do let me know
Thanks

**Comment by namdre** [comment]
if you use moveToXY whithout setSpeed everything (including the speeds) should work out fine. It it still doesn't work, attach a new problem scenario.
