### ISSUE TITLE
setSpeed is not taking effect 

### ISSUE THREAD

**Issue by Nitinyerra** [eclipse-sumo/sumo#14968]
When I use `traci.vehicle.setSpeed("A_0", 15.366)` to alter the speed of the vehicle, I don't see any change when I check the speed using `traci.vehicle.getSpeed("A_0")`. The speed remains the same before and after setting it with `setSpeed()`.

SUMO version: 1.19

Please help me with this issue. Thank you in advance.

**Comment by namdre** [comment]
by default safety features of the simulation remain active which means setSpeed would usually be able to lower the speed but not raise it. You can use `setSpeedMode` to overrule some or all of the safety features: https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#speed_mode_0xb3
