### ISSUE TITLE
libsumo 1.20 installation

### ISSUE THREAD

**Issue by way-thu** [eclipse-sumo/sumo#14978]
I installed libsumo 1.12 and then occurs a error like below:
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/33b35f9f-9fb1-4d7b-9678-7e41e98dccd0)
I tried to solve it by change the libsumo version to 1.20.
However, although I tried so many methods (pip install, conda install and so on), it doesn't work.
![image](https://github.com/eclipse-sumo/sumo/assets/113359869/a3857db9-bb08-45bb-bc45-67cb0a96a358)
 Is there any possible way to solve this problem?

**SUMO-version:1.18

**operating system:windows

**Comment by behrisch** [comment]
You seem to have a custom pypi index configured (pypi.tuna.tsinghua.edu.cn). Please try again with the standard pypi.org. Furthermore mixing conda and pip is in general not a good idea https://stackoverflow.com/questions/56134588/is-it-a-bad-idea-to-use-conda-and-pip-install-on-the-same-environment. Unfortunately we do not provide conda packages
