### ISSUE TITLE
Are there any good website proving TOD data and through & turn traffic volume for RL modeling?

### ISSUE THREAD

**Issue by jinx2plus** [eclipse-sumo/sumo#14970]
Probably 5 minute based data of one day is fine, too. 
I can find lots of traffic data but too many are aggregated as one day(AADT).

**Comment by namdre** [comment]
- hourly data here: https://roadtraffic.dft.gov.uk/downloads
- this seems to be 5min resolution or even more detailed but you need an account: https://pems.dot.ca.gov/
- 3-5min: https://utd19.ethz.ch/
- https://github.com/graphhopper/open-traffic-collection

**Comment by behrisch** [comment]
make this permanent in the docs

**Comment by jinx2plus** [comment]
https://github.com/graphhopper/open-traffic-collection
probably here too. Thank you!
