### ISSUE TITLE
Getting the number of teleported vehicles through TraCI

### ISSUE THREAD

**Issue by oshadajay** [eclipse-sumo/sumo#14977]
Hi, is there a way to retrieve the following values that get printed on the terminal through TraCI at the end of the simulation? I specifically need the number of teleported vehicles. I tried using the `vaporized` attribute in the `tripinfo.xml`, yet it does not match. And I think that `getStartingTeleportNumber` and `getEndingTeleportNumber` is with respect to a single step. I can sum them up, yet was wondering whether there is a better way to get end of simulation statistics into the code.

![image](https://github.com/eclipse-sumo/sumo/assets/55861474/fc612977-438c-4a91-a481-b34d4cbfdc89)

**SUMO-version:**
1.20

**operating system:**
Windows

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Simulation/Output/StatisticOutput.html

**Comment by namdre** [comment]
Statistic values can now also be retrieved at runtime: https://sumo.dlr.de/docs/TraCI/Simulation_Value_Retrieval.html#statistics_parameter_retrieval

**Comment by oshadajay** [comment]
Exactly what I was looking for. Thank you so much.

**Comment by oshadajay** [comment]
@namdre I am still getting `AttributeError: module 'traci' has no attribute 'stats'` when using the last nightly build. I am using the following code.

```
if traci.simulation.getMinExpectedNumber() == 0:
    no_of_teleports = traci.stats.teleports.total()
```

**Comment by oshadajay** [comment]
@namdre Thank you very much!
