### ISSUE TITLE
MSDevice_Battery warning Battery depleted not working

### ISSUE THREAD

**Issue by extremeCrazyCoder** [eclipse-sumo/sumo#14980]
Add your issue description here.
The following warning does not get triggered:
https://github.com/eclipse-sumo/sumo/blob/643e11125d2a5f75f9008f293e1fb5b9a6b77211/src/microsim/devices/MSDevice_Battery.cpp#L218

As far as I can tell the reason is the following:

When a vehicle depletes setActualBatteryCapacity is beeing called with a negative number:
https://github.com/eclipse-sumo/sumo/blob/643e11125d2a5f75f9008f293e1fb5b9a6b77211/src/microsim/devices/MSDevice_Battery.cpp#L205

This will result in the Battery Capacity beeing set to 0
https://github.com/eclipse-sumo/sumo/blob/643e11125d2a5f75f9008f293e1fb5b9a6b77211/src/microsim/devices/MSDevice_Battery.cpp#L361-L363

The warning checks for capacity < 0
https://github.com/eclipse-sumo/sumo/blob/643e11125d2a5f75f9008f293e1fb5b9a6b77211/src/microsim/devices/MSDevice_Battery.cpp#L215
But since it has been set to 0 the warning is not beeing triggered

There are 2 ways to fix this.
1) Let the battery capacity go below 0 (set it directly and not via the setter method, changing the setter method could have other side effects - traci / initial parameters)

2) Check for depletion prior to changing the value. For example like so:
```diff
diff --git a/src/microsim/devices/MSDevice_Battery.cpp b/src/microsim/devices/MSDevice_Battery.cpp
index 363c67c1ad3..34935129de1 100644
--- a/src/microsim/devices/MSDevice_Battery.cpp
+++ b/src/microsim/devices/MSDevice_Battery.cpp
@@ -201,9 +201,6 @@ bool MSDevice_Battery::notifyMove(SUMOTrafficObject& tObject, double /* oldPos *
             myConsum = MIN2(myConsum, 0.0);
         }
 
-        // Energy lost/gained from vehicle movement (via vehicle energy model) [Wh]
-        setActualBatteryCapacity(getActualBatteryCapacity() - myConsum);
-
         // Track total energy consumption and regeneration
         if (myConsum > 0.0) {
             myTotalConsumption += myConsum;
@@ -212,13 +209,16 @@ bool MSDevice_Battery::notifyMove(SUMOTrafficObject& tObject, double /* oldPos *
         }
 
         // saturate between 0 and myMaximumBatteryCapacity [Wh]
-        if (getActualBatteryCapacity() < 0) {
+        if (getActualBatteryCapacity() - myConsum < 0 && getActualBatteryCapacity() > 0) {
+            //only trigger this warning once after going below 0 to avoid spam
             setActualBatteryCapacity(0);
             if (getMaximumBatteryCapacity() > 0) {
                 WRITE_WARNINGF(TL("Battery of vehicle '%' is depleted."), veh.getID());
             }
-        } else if (getActualBatteryCapacity() > getMaximumBatteryCapacity()) {
+        } else if (getActualBatteryCapacity() - myConsum > getMaximumBatteryCapacity()) {
             setActualBatteryCapacity(getMaximumBatteryCapacity());
+        } else {
+            setActualBatteryCapacity(getActualBatteryCapacity() - myConsum);
         }
         myLastAngle = veh.getAngle();
     }
```

*If possible, upload an example that shows your problem.*
[example_depletion.zip](https://github.com/user-attachments/files/15586532/example_depletion.zip)

**SUMO-version:**
latest master (643e11125d2a5f75f9008f293e1fb5b9a6b77211)

**operating system:**
linux (ubuntu)

**Comment by m-kro** [comment]
Thanks. I have updated the device such that the warning message will be issued.

**Comment by extremeCrazyCoder** [comment]
I don't know how it was supposed to work, the warning message is now sent at every step (if the vehicle is out of charge)

In my opinion it would be enough to send that message once per car (add an additional check for getActualBatteryCapacity() > 0 at Line 205)
