### ISSUE TITLE
Apply (general) lane spread options to shape file import

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#14984]
Topic from the [mailing list](https://www.eclipse.org/lists/sumo-user/msg14056.html). The user wants to merge networks coming from different sources (OSM, shape file).

- Is there a common standard of lane spread settings for one way edges among the import formats?
- Can said lane spread settings be customised?

**Comment by namdre** [comment]
for OSM default is "right" for two-way roads (configurable with ** --default.spreadtype**).
 The default is "center" for one-way. You can change this with option **--osm.oneway-spread-right**.

**Comment by behrisch** [comment]
--default.spreadtype should be applied to shape file imports as well

**Comment by m-kro** [comment]
Do we need --shapefile.oneway-spread-right then?

**Comment by behrisch** [comment]
I don't think so
