### ISSUE TITLE
dfrouter minimum number of detectors

### ISSUE THREAD

**Issue by NoelGK** [eclipse-sumo/sumo#14998]
I would really appreciate if someone could answer me this: is there a minimum number of detectors needed for dfrouter to work properly?

**Comment by namdre** [comment]
dfrouter works best if every entry and exit are covered with detectors. If you have less than that, use routeSampler instead.
See https://sumo.dlr.de/docs/Demand/Routes_from_Observation_Points.html#choosing_the_right_tool
