### ISSUE TITLE
 Information of bus stop disappears at the end of the first cycle (when buses pass through the rerouters). 

### ISSUE THREAD

**Issue by claudiacbh** [eclipse-sumo/sumo#14996]
Hello,

Could you please help me with the following issue?

I have a BRT system that is simulated using a circular network, for which I utilized two rerouters. The vehicles on their route have assigned bus stops, but this information disappears at the end of the first cycle (when buses pass through the rerouters). 

How could I fix the problem? I need the buses always stop at their assigned bus stops. 

The network circuit only has one lane. If I remove one rerouter, the same thing happens. In other words, the bus loses the information about the bus stops at the end of the first round.

Thank you

*If possible, upload an example that shows your problem.*

octagono2.rou.xml
```
<routes>
    <!-- VehiclesTypes -->
    <vType id="bus_Linea" vClass="bus" personCapacity="50" maxSpeed="50" boardingDuration="5" length="10.0" width="4.0" height="25"/>
	<route id="busRoute"  edges = "e2 e3 e4 e5 e6 e7 e8 e1" repeat = "1000"  departPos="stop">
        <stop busStop="stop_1" duration="0.00" />
		<stop busStop="stop_2" duration="0.00" />
        <stop busStop="stop_3" duration="0.00" />
		<stop busStop="stop_4" duration="0.00" />
    </route>	
	
	<flow id="bus1" type="bus_Linea" route ="busRoute"  begin="0.0" number="4" period = "211"  line="1"  /> 
	
</routes>
```
octagono2_R.add.xml
```
<additionals>

   <rerouter id="rerouter_0" edges="e8">
        <interval end="1e9">
           <destProbReroute id="e2"/>
        </interval>
    </rerouter>

   <rerouter id="rerouter_1" edges="e2">
        <interval end="1e9">
           <destProbReroute id="e8"/>
        </interval>
    </rerouter>

</additionals>
```
octagono2.sumocfg
```
<configuration>

    <input>
        <net-file value="octagono2.net.xml"/>
		<route-files value="octagono2.rou.xml, octagono2_P.rou.xml"/>
        <additional-files value="octagono2.add.xml, octagono2_R.add.xml"/>
    </input>
	
	 <time>
        <begin value="0"/>
        <end value="3600"/>
    </time>

</configuration>
```

**SUMO-version:** 1.20.0

**operating system:** Windows 11

**Comment by m-kro** [comment]
If you want to use rerouters, you are better off with the `routeProbReroute` command (see [doc](https://sumo.dlr.de/docs/Simulation/Rerouter.html#assigning_a_new_route)). Then stops included in predefined routes are served by the bus. 

If you know in advance how often the bus will travel the route, just relying on `repeat="1000"` would be enough to make the bus go in circles for a while.
