### ISSUE TITLE
traci.vehicle.dispatchTaxi() crashes SUMO with no logs

### ISSUE THREAD

**Issue by coopwilliams** [eclipse-sumo/sumo#15016]
Hello, I'm finding that SUMO crashes with no logs or helpful errors when using `traci.vehicle.dispatchTaxi()`. The expected behavior is that a taxi is created and begins to pick up the "cooper" person, OR that a helpful error message is produced to indicate why this Traci call is in error. 

I've included my files here. To reproduce:
1. Add the files to the same folder.
2. Remove the .txt extension from the files.
3. Add the python code below to `main.py`
4. Run `python main.py -p tinytest.sumocfg`
5. Step 2 simulation steps forward in the SUMO window, to see the window crash without an error. The only error reported is this, which I take to be a generic error that SUMO server has stopped responding.

```
Traceback (most recent call last):
    traci.vehicle.dispatchTaxi(f"terminator-{timescale_current_step}", reservation_ids[0])
  File "/Users/cooper/.pyenv/versions/3.12.1/lib/python3.12/site-packages/traci/_vehicle.py", line 1479, in dispatchTaxi
    self._setCmd(tc.CMD_TAXI_DISPATCH, vehID, "l", reservations)
  File "/Users/cooper/.pyenv/versions/3.12.1/lib/python3.12/site-packages/traci/domain.py", line 164, in _setCmd
    self._connection._sendCmd(self._cmdSetID, varID, objectID, format, *values)
  File "/Users/cooper/.pyenv/versions/3.12.1/lib/python3.12/site-packages/traci/connection.py", line 231, in _sendCmd
    return self._sendExact()
           ^^^^^^^^^^^^^^^^^
  File "/Users/cooper/.pyenv/versions/3.12.1/lib/python3.12/site-packages/traci/connection.py", line 137, in _sendExact
    raise FatalTraCIError("Connection closed by SUMO.")
traci.exceptions.FatalTraCIError: Connection closed by SUMO.
```

I'm working off of [this Taxi Service Tutorial](https://sumo.dlr.de/docs/Tutorials/TaxiService.html). My `SUMO_HOME` is set to the location given by the `brew install`. As you can see, I've added the `traci` setup both to the Sumocfg file and to the Start command. I've also defined the Taxi Vtype in the Route file.

It's unclear whether this configuration is to blame, or something else entirely, because the LOGFILE contains no output.

## *If possible, upload an example that shows your problem.*
[tinytest.net.xml.txt](https://github.com/user-attachments/files/15789056/tinytest.net.xml.txt)
[tinytest.netecfg.txt](https://github.com/user-attachments/files/15789064/tinytest.netecfg.txt)
[tinytest.rou.xml.txt](https://github.com/user-attachments/files/15789065/tinytest.rou.xml.txt)
[tinytest.sumocfg.txt](https://github.com/user-attachments/files/15789068/tinytest.sumocfg.txt)

```
import traci        # this could be replaced by `import libsumo as traci` later
import argparse
import time 

if __name__ == "__main__":

    # TODO get args
    #path arg
    #wait arg

    # Initialize parser
    parser = argparse.ArgumentParser()
    
    # Adding optional argument
    parser.add_argument("-p", "--path", help = "path to SUMO config")
    parser.add_argument("-w", "--wait_on_finish", help = "wait to end simulation before window is closed", action="store_true")
    
    args = parser.parse_args()
    if args.path:
        sumo_path = args.path
    else:
        sumo_path = "."
    if args.wait_on_finish:
        WAIT_FOR_SIM_FINISH = args.wait_on_finish
    else:
        WAIT_FOR_SIM_FINISH = False

    # configure SUMO start command
    sumoBinary = "sumo-gui"
    sumoDelay = '--delay 1000'
    # sumoCmd = [sumoBinary, "-c", f"{sumo_path}", '--delay', '200', "--log", "LOGFILE"]
    sumoCmd = [sumoBinary, "-c", f"{sumo_path}", '--delay', '200', "--device.taxi.dispatch-algorithm", "traci", "--log", "LOGFILE"]


    # start SUMO
    traci.start(sumoCmd)


    # demo adding one person
    traci.person.add("cooper", "-E17", 0)
    traci.person.appendDrivingStage("cooper", "E4", "taxi")
    traci.person.appendWaitingStage("cooper", 100)



    timescale_current_step = 0
    traci.simulationStep()
    reservations = traci.person.getTaxiReservations(0)
    reservation_ids = [r.id for r in reservations]
    print(reservations)
    print(reservation_ids)

    if reservation_ids:
        traci.vehicle.add(f'terminator-{timescale_current_step}', 'r_4', 'taxi', depart=f'{timescale_current_step}', line='taxi')
        traci.vehicle.dispatchTaxi(f"terminator-{timescale_current_step}", reservation_ids[0])

    while timescale_current_step < 200:
        traci.simulationStep()

        timescale_current_step += 1
    
    traci.close(WAIT_FOR_SIM_FINISH)
    print("simulation done.")
```

## **SUMO-version:**
Eclipse SUMO sumo Version 1.20.0
 Build features: Darwin-23.0.0 arm64 AppleClang 15.0.0.15000040 Release FMI Proj GUI Intl
 Copyright (C) 2001-2024 German Aerospace Center (DLR) and others; https://sumo.dlr.de
 License EPL-2.0: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>

## **operating system:**
Sonoma 14.5
16-inch Apple M2 Max 64GB

**Comment by namdre** [comment]
crash is caused by sending `dispatchTaxi` to a vehicle that hasn't yet entered the network.

**Comment by namdre** [comment]
Either put at least one `simulationStep` between the `add` and the `dispatchTaxi` or force the vehicle into the network with `vehicle.moveTo` directly after calling `add`
