### ISSUE TITLE
GLOSA device resets myNextTLSLink

### ISSUE THREAD

**Issue by Domsall** [eclipse-sumo/sumo#15011]
I am currently using the GLOSA device and stumbled across a bug:

- When a vehicle gets inserted, the function `MSDevice_GLOSA::notifyEnter` is called and the information of the next traffic light gets written into `myNextTLSLink`. The Code uses `bestLaneConts` to find the next lanes that lead up to the traffic light. This works as intended.
- `MSDevice_GLOSA::notifyEnter` is also called everytime a vehicle drives onto or off a junction. `myNextTLSLink` is then always calculated new.
- The issue: When calling `getBestLanesContinuation` at the beginning or end of the junction, the whole vector or the first value is empty. The algorithm then thinks that the vehicle has driven past the tls, which is not true.

**Comment by Domsall** [comment]
In `MSVehicle::executeMove()`, it seems that `myLane` gets updated in `processLaneAdvances`, but `updateBestLanes()` is called at a later point. When `MSDevice_GLOSA::notifyEnter` is reached, `myLane` is one Lane ahead of `myBestLanes` 

If I can somehow help to get this issue resolved faster, please let me know.

**Comment by namdre** [comment]
What influence are you expecting from the GLOSA device when the vehicle is entering or leaving the tls-controlled junction?
Or does this manifest for every junction *ahead* of the tls?
It will probably help if you provide a small sample scenario and describe where the driving behavior differs from your expectation.

**Comment by Domsall** [comment]
This happens at every junction ahead of the tls.

**Comment by Domsall** [comment]
Here the sample scenario:

[GLOSA_tls.zip](https://github.com/user-attachments/files/15801198/GLOSA_tls.zip)

And the output when debugging (tls=NULL appears when driving over the first junction):
![image](https://github.com/eclipse-sumo/sumo/assets/53042793/be8e53b7-77f6-48a4-a8b3-93dc860c125b)

**Comment by m-kro** [comment]
Now `updateBestLanes` is called explicitly in the GLOSA device to ensure best lane data is available. This comes with some additional computing cost but was estimated acceptable.
