### ISSUE TITLE
Question about speed deviations in congested edges

### ISSUE THREAD

**Issue by gladysmcgan** [eclipse-sumo/sumo#15029]
Hi, I am looking at the speeddev option in meso simulation. I understand that the cars would drive in free-flow conditions using speeds within the set deviation of the speed limit. I was wondering how does this behavior change in congestion? Cars would slow down but would their preferred driving speed still be varied?

**Comment by namdre** [comment]
in a full congestion, the speed would be dominated by the outflow headway and so the desired speed takes no effect (similar to micro simulation). In a "moderate" congestion there should still be an effect but smaller than for free flow.

**Comment by gladysmcgan** [comment]
Thanks for the explanation! Good to know that the effect works in moderate congestion. Could you point us to the source code so that we can understand better what speeds to expect?

**Comment by namdre** [comment]
https://github.com/eclipse-sumo/sumo/blob/be24f5f3ca2ffbc3a1c3dd28081b2e98670dbdb1/src/mesosim/MESegment.cpp#L625
In a moderate congestion, some vehicles will have the `MAX` term dominated by `uspeed` and some by the blockTime of the queue.

**Comment by gladysmcgan** [comment]
Super, thanks :)
