### ISSUE TITLE
createVehTypeDistribution.py: avoid suprising behavior when defining speedFactor

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#15025]
at the moment, the user (i.e. @robertalms) expects to define speedFactor and thereby obtain a distribution of values for the vehTypes.
However, speedFactor has multiple semantics and when define as a double only sets the mean of the distribution.

The default speedDev of 0.1 then leads to a wider distribution than expected.
As a remedy, speedDev should be set to 0 if the user defines speedFactor but not speedDev in the config file for createVehTypeDistribution.py (maybe with a message or warning)

**Comment by robertalms** [comment]
thanks!
