### ISSUE TITLE
Usage of filterElements.py

### ISSUE THREAD

**Issue by transport45678** [eclipse-sumo/sumo#15028]
Hello, I would like to filter some values from my trip-info xml file. In this regard, I used command like:
`python filterElements.py -f 1.trip_info.xml -o filtered.xml -t tripinfo -a depart --remove values 0.60`

It gives an error: unrecognized arguments: 0.60

As a second question, For instance, I would like to delete depart times smaller than 900.0, it seems it is not possible by using this tool. Am I right? Thank you for help,regards.

**Comment by namdre** [comment]
1. the option is **--remove-values** (note the hyphen between 'remove' and 'values')
2. you can use option **--keep-interval* or **--remove-interval** for this

**Comment by transport45678** [comment]
I tried as : `python filterElements.py -f 1.trip_info.xml -o filtered.xml -t tripinfo -a depart --remove-interval 0,900`. It gives same unrecognized argument error.
By searching --help option, I could not see the intervals options.
![image](https://github.com/eclipse-sumo/sumo/assets/153621221/0dfb73e4-2e58-4d11-a01a-5910c42ecf61)

**Comment by namdre** [comment]
here are our tests :https://sumo.dlr.de/extractTest.php?path=tools/xml/filterElements
check if you can run them successfully on your end.

Unfortunately, your screenshot doesn't show the call or the full error message, Can you copy directly from the command line window?

**Comment by transport45678** [comment]
Thank you for example, solved.

**Comment by transport45678** [comment]
Hello @namdre ,
I would like to ask one more question to make sure for this tool. Is it possible to give multiple input files and obtain multiple output files at the same time? I tried commands using comma separator and space between files below:
`python filterElements.py -f 1.trip_info.xml 2.trip_info.xml -o 1.trip_info_new.xml 2.trip_info_new.xml -t tripinfo -a depart --remove-interval 0,900`
`python filterElements.py -f 1.trip_info.xml, 2.trip_info.xml -o 1.trip_info_new.xml, 2.trip_info_new.xml -t tripinfo -a depart --remove-interval 0,900`

 It gives an error: unrecognized arguments: 2.trip_info.xml 2.trip_info_new.xml

Thank you for help,regards.

**Comment by namdre** [comment]
multiple input/ouput files are not supported.
