### ISSUE TITLE
Simulation Error when rebuilding tls-default-type NEMA

### ISSUE THREAD

**Issue by aminissn** [eclipse-sumo/sumo#15023]
I am rebuilding network using NETCONVERT by setting tls-default-type NEMA. The converison returns on success a network but when I run the simulation for 3 intersections I get an error saying: 

Error: At traffic signal 3459661227 the barrier and coordinated phases 8, 1 are located on the same side of a barrier. Please check your configuration file
Quitting (on error).

and tllogic looks like this:
<img width="775" alt="image" src="https://github.com/eclipse-sumo/sumo/assets/30176885/f1b470ed-71c6-475a-bacf-3a88edfcea1e">

The error can be resolved by changing the logic to:

<img width="783" alt="image" src="https://github.com/eclipse-sumo/sumo/assets/30176885/b2524632-877e-437e-831c-2012a5eef6c3">

SUMO-version:1.20.0

operating system:MacOS

**Comment by namdre** [comment]
can you provide a cut-out of the network with just this intersection (in other words, a minimal failing example)?
