### ISSUE TITLE
Creating network from plain xml creates new connections (netconvert)

### ISSUE THREAD

**Issue by gladysmcgan** [eclipse-sumo/sumo#15039]
Hi, I have a question about creating networks from plains. I removed a couple of connections from the connection plain xml, and then tried to form the network again by using the following line:

`netconvert -n net.nod.xml -e net.edg.xml -x net_modified.con.xml -t net.typ.xml -o new.net.xml`

I noticed that the connections (and new ones) are made when building the network from plains, essentially ignoring the modification in the connection file. Is there a way to keep the plain changes in the rebuilt net?

The end goal is to be able to remove a connection(s) on a junction, and regenerate the tls such that the new tls reflects the updated connections layout on that junction. 

Expected net: 
![Screenshot 2024-06-17 at 15 19 15](https://github.com/eclipse-sumo/sumo/assets/59922884/106f69d2-2aab-46b5-9c20-55df7a80ed76)
Resulting net:
![Screenshot 2024-06-17 at 15 19 18](https://github.com/eclipse-sumo/sumo/assets/59922884/5464f394-1e83-4832-a9d7-a47c037beaf5)

Thanks for your help! 

**SUMO-version:**  Version v1_20_0+0381-39ca464cc5e

**operating system:** MacOS

**Comment by namdre** [comment]
if an edge has no connection information at all in plain.xml then it's connections are guessed from scratch. To specify "no connections" in plain xml requires using the `<delete>` element (https://sumo.dlr.de/docs/Networks/PlainXML.html#explicitly_setting_which_edge_lane_is_connected_to_which).
If that doesn't solve your problem, please provide a minimal failing example

**Comment by gladysmcgan** [comment]
It does solve the problem, thanks! :)
