### ISSUE TITLE
3d View of SUMO through a command or a script

### ISSUE THREAD

**Issue by Nitinyerra** [eclipse-sumo/sumo#15032]
I have recently started using the 3D view option available in SUMO (experimental stage). I need to know if it is possible to set the 3D view as the default instead of the normal SUMO GUI, either through the command line or a Python script. Please provide guidance on how this can be achieved.

Version: 1.20.0

**Comment by namdre** [comment]
set option **--osg-view** (https://sumo.dlr.de/docs/sumo-gui.html#3d_visualization)
or `<osg-view value="true"/>` in a sumocfg
