### ISSUE TITLE
Persons joining edge via access can collide with vehicles

### ISSUE THREAD

**Issue by theDivj** [eclipse-sumo/sumo#15030]
This behaviour appeared with SUMO v1.20.

Persons joining an edge via an access can collide with vehicles at the access point. The access point is centred on the lane and the passenger emerges on top of/underneath the vehicle.

Attached example has a breakpoint at 417s and a collision with bus b2 and person p1.23 at 419s.
[accesstest.zip](https://github.com/user-attachments/files/15849136/accesstest.zip)

This is a cut down example from a larger simulation involving many bus/passenger interactions which demonstrated many collisions at v1.20 which were not seen at v1.19 - the public transport warning in the example is an artefact of the cut-down.

The scenario behind this is airport buses picking up passengers leaving an aircraft where there is no airbridge. Specifically where second or subsequent buses arrive to pick up passengers where there are more passengers than a single bus capacity.

The second bus is slowing on the lane in order to 'stop' for pickup and happens to overlap the access point as a person emerges.

I have no urgent requirement here - this is just something I'm playing with out of interest.

**Comment by namdre** [comment]
new lateral positioning after access stage via 767b59f and e18378f. Previous code path used `UNSPECIFIED_POS_LAT` and then heuristically placed persons next to the road if it had any vehicles on it: https://github.com/eclipse-sumo/sumo/blob/2db6a127b44bc42f996dd41b179eb52b0bbd7bea/src/microsim/transportables/MSPModel_Striping.cpp#L1702-L1705

**Comment by theDivj** [comment]
Great! many thanks for getting that done so quickly.

Using the windows build from last night - v1_20_0+0669-48320fb5977.   that resolves the person/access conflict.

However I am now getting a warning related to container insertion. I have freight aircraft landing with no passengers, just containers, but am getting warnings for each container in the vehicle when the 'aircraft' is inserted:-

Warning: Vehicle 'UA905' exceeds personCapacity 0 when placing triggered person 'cUA110.0', time=22260.00

Where UA905 is the freight aircraft (vClass rail with  personCapacity="0" containerCapacity="30") and cUA110.0 is one of 30 containers on the landing aircraft - specified in a triggered container flow.  Everything behaves as expected - the warning is just spurious.

Is this an artefact of in-progress development that I can ignore  or should I cut the scenario down to a simple example?

thanks again - as before, no panic.

**Comment by theDivj** [comment]
Warning does not appear if personCapacity is >0 - ie representing passengers + baggage

**Comment by namdre** [comment]
A small text case would help to get it sorted out quickly. Please also open a new ticket for this.
