### ISSUE TITLE
SUMO Traci generated output

### ISSUE THREAD

**Issue by ArnoldChoon** [eclipse-sumo/sumo#15031]
Hi, i ask just want to ask if after running the sumo configuration with the help of traci will automatically generate a summary report of the sumo configuration? In my code I did not print any output but the report summary seems to generate itself, is there anyway to customize what output to print and how do I how if the generated output is accurate? The picture below show the summary report that is automatically generated. Thank you in advanced for those who helps

![image](https://github.com/eclipse-sumo/sumo/assets/167608645/ad4ff24f-883c-4b8a-9571-f5ea717ed5e5)

**Comment by namdre** [comment]
this is due to an extra option when launching sumo:
see https://sumo.dlr.de/docs/Simulation/Output/index.html#aggregated_traffic_measures
