### ISSUE TITLE
Pedestrian Head rotation control and Visual Detection Area 

### ISSUE THREAD

**Issue by muhammadfaizan91** [eclipse-sumo/sumo#15033]
I am working on modeling pedestrian decision-making behavior at crosswalks in SUMO and I am facing two specific challenges. I need assistance with the following:

1. **Pedestrian Head Rotation Behavior:** I aim to simulate pedestrian head rotation behavior at unsignalized midblock crosswalks, where pedestrians look left and right to observe approaching vehicles before making crossing decisions. Is it possible to control pedestrian head rotation at each time step in SUMO? If so, please provide guidance on how to achieve this.

2. **Field of View (FOV) and Detection Area:** With the head rotation, the pedestrian's observation area changes based on their Field of View (FOV) and rotation angle. I want to depict the pedestrian's FOV as the detection area for approaching vehicles. Can this be controlled in SUMO? If yes, how can I implement it?

Thank you.

**Comment by m-kro** [comment]
This is beyond the scope of SUMO being a traffic simulation.
