### ISSUE TITLE
Get the number of conflicts in real-time

### ISSUE THREAD

**Issue by way-thu** [eclipse-sumo/sumo#15046]
I hope to obtain the number of conflicts (using PET) at the intersection (between vehicles and pedestrians) in real-time during the simulation run. Through my research, I found that it seems possible to use the SSM device to count the total number of conflicts after the simulation ends.

Is there any method to help me obtain the number of conflicts in real-time, such as using TraCI or other tools?

**SUMO-version: 1.18.0

**operating system: win 11

**Comment by m-kro** [comment]
This isn't possible (yet) but we have it on our list of enhancement proposals at #4983.
