### ISSUE TITLE
Try to make vehicles change lanes continuous using lateral resolution

### ISSUE THREAD

**Issue by TracyLiu556** [eclipse-sumo/sumo#15053]
I'm trying to code vehicles lane changing when encountering an emergency vehicle. In Python, I use traci.vehicle.changeLaneRelative() command to change lanes. I add this in my configuration file:
```     
</input>
	<processing>
	<lateral-resolution value="3.66"/>
  	</processing>
</configuration>
```
But the vehicles are still changing lanes instantly.
I set the step length to 0.02, not sure if that relates.

**SUMO-version:1.19.0**

**operating system: Windows 10**

**Comment by TracyLiu556** [comment]
![Screenshot 2024-06-18 124431](https://github.com/eclipse-sumo/sumo/assets/100657008/af54ca34-613e-4ea9-90ab-b68270ca2749)

**Comment by m-kro** [comment]
You can find an [example scenario](https://sumo.dlr.de/extractTest.php?path=complex/traci/vehicle/changeLane_subLane/changeRelative) for your use case at your disposal.

**Comment by TracyLiu556** [comment]
Thank you! Just realized that I added --lateral-resolution command in my configuration file but when I use traci.start() I only referenced the net and route file, not the configuration file so it doesn't work.
