### ISSUE TITLE
[Question] How to set a minimum speed limit

### ISSUE THREAD

**Issue by usamael2000** [eclipse-sumo/sumo#15055]
Hi:
Is there a way to set a minimum speed limit for a certain lane/edge?
I want the target lane/edge to have "maximum speed limit of 120 km/hr and minimum speed limit of 90 km/hr.
The maximum speed limit can be achieved using the "speed" property of the lane/edge, but I was not able to find any source in how to set the minimum speed limit.

I would appreciate if you let me know how to set the minimum speed limit .

**Comment by m-kro** [comment]
This isn't considered, mainly because this kind of rules is not widespread across the world. The only application here in Germany would be to exclude slow vehicles from motorways, which can be done with lane permissions / vehicle classes.

**Comment by namdre** [comment]
(i.e. mopeds are forbidden on motorways be default). You can use vClass `custom1` and `custom2` if you have custom vehicles that you want to prevent from driving on some roads.
