### ISSUE TITLE
Questions GLOSA device

### ISSUE THREAD

**Issue by Domsall** [eclipse-sumo/sumo#15061]
I looked into the current GLOSA device and couldn't fully understand the `adaptSpeed`-function (when the light signal is red). I hope you can help me with answers to the following questions:

1. I reviewed the calculation of `targetSpeed` and got the same results. However, the calculation of `duration` and the comments do not seem to be correct. `duration` is the time it takes the vehicle to decelerate to `targetSpeed`. Shouldn't this be equal to `(v-x)/d`?
2. It appears that the vehicles want to reach the stop line with vMax exactly when the light signal turns green. Is this true? Don't the vehicles need some kind of safeguard distance? What if the traffic light is malfunctioning and does not turn green?
3. The function `setSpeedTimeLine` is used to set the `targetSpeed`. Is it possible to set the speed factor instead and somehow ignore the traffic light? I would like to let the CarFollowing model choose the speed depending on `targetSpeed` (smooth, realistic human driving transitions).

Thanks in advance!

**Comment by namdre** [comment]
1. there is a known problem here that we didn't fix yet: #12217.    
> It should be y = t - (w-x) / a (because w-x concerns the acceleration to maximum speed after having slowed down from v to x earlier."
basically, after keeping the speed for y, we only need to accelerate again.

3. Yes. Safety w.r.t malfunctioning green prediction is not considered at the moment
4. Yes. setting a speedFactor should work as well but then you have to reset it at the end of `duration`. Pull requests are welcome

**Comment by Domsall** [comment]
![image](https://github.com/eclipse-sumo/sumo/assets/53042793/4a0a26f9-2669-4497-888e-90a5708a1416)

1. Aside from the bug (using w instead of v), `duration` is calculated as the time 1+2 (see above picture). From my understanding, the green curve is the `SpeedTimeLine` right now, but the speed should follow the orange curve. Therefore, `duration` should only be time 1?!
2. I will create a pull request for the speedFactor-adaption. I will also add a calculation for v > x.

**Comment by namdre** [comment]
fixed via #15067
