### ISSUE TITLE
Spurious warning in containerFlow when personCapacity=0

### ISSUE THREAD

**Issue by theDivj** [eclipse-sumo/sumo#15077]
windows build from git - current development sumo-gui v1_20_0+0701-f6b3dd88262

after fix (https://github.com/eclipse-sumo/sumo/issues/15030), inserting a vehicle with personCapacity="0" to support a container flow results in a spurious warning:
> Warning: Vehicle 'UA15' exceeds personCapacity 0 when placing triggered person 'cUA904.0', time=10.00

Attached example has break at 9. Warning is issued at 10. on vehicle insertion.

Scenario is landing freight aircraft (train) - equivalent to a departing freight train.
Vehicle parameters in example are irrelevant - cosmetic, warning not issued if personCapacity > 0

I also get a crash downstream in a larger scenario (heathrow) where memory references obviously corrupted - may or may not be related - I'll investigate when build is stable.

As before, no urgency, just something I'm playing with.

**Comment by theDivj** [comment]
[initialContainerTest..zip](https://github.com/user-attachments/files/15929555/initialContainerTest.zip)
Forgot example!

**Comment by theDivj** [comment]
Appears to be a simple check error in sumo\src\microsim\transportables\MSStageDriving.cpp
ie not obvious why this is >= pCap
```
        const int pCap = startVeh->getVehicleType().getParameter().personCapacity;
        if (startVeh->getPersonNumber() >= pCap) {
            WRITE_WARNING(TLF("Vehicle '%' exceeds personCapacity % when placing triggered person '%', time=%",
                        startVeh->getID(), pCap, transportable->getID(), time2string(SIMSTEP)));
        }

```

**Comment by namdre** [comment]
the `>= pCap` is because the check is done even before adding another person/container to the vehicle.
