### ISSUE TITLE
use netconvert to convert sumo net coordinate system 

### ISSUE THREAD

**Issue by lindsaymorgan** [eclipse-sumo/sumo#15071]
Hello！I am working on sumo-carla cosimulation these days. Because Carla need a certain Mercator-based coordinate network to synchronize car positions, I am trying to use netconvert to convert WGS-based .net.xml file to mercator-based .net.xml. The command I used is as follows:
```
netconvert.exe -s kejiyuan.net.xml --output-file kejiyuan_tmer.net.xml --proj "+proj=tmerc +lat_0=22.53021243154133 +lon_0=113.9454667692975 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +geoidgrids=egm96_15.gtx +vunits=m +no_defs"
```
I copied the proj parameter from the xodr file used by carla simulation. But I found no difference between the input and output files, except for the location line. And cars in sumo-carla cosimulation are not on road.
Is it normal that edge coordinates remain the same after converting the coordinate system? Or there is anything wrong with my command line?

**Comment by namdre** [comment]
the **--proj** option only takes effect when loading a network that isn't yet projected. Here is how to do this:

1. convert net to plain-xml with geo-coordinates: `netconvert -s old.net.xml -p plain --proj.plain-geo`
2. rebuild with mercator: `netconvert -e plain.edg.xml -n plain.nod.xml -x plain.con.xml -i plain.tll.xml  --proj "+proj=tmerc +lat_0=22.53021243154133 +lon_0=113.9454667692975 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +geoidgrids=egm96_15.gtx +vunits=m +no_defs"`

**Comment by namdre** [comment]
also note, that Mercartor is "bad" in that it can seriously mess up your distances (i.e. roads twice as long as in reality)
