### ISSUE TITLE
negative emissiosn with HBEFA4

### ISSUE THREAD

**Issue by ricBin93** [eclipse-sumo/sumo#15079]
In the HBEFA4 model related to emissions, negative values appear at certain time instances. How are these evaluated?

**SUMO-version:1.19**

**operating system: Windows 11**
[Emisson.zip](https://github.com/user-attachments/files/15953235/Emisson.zip)

**Comment by namdre** [comment]
the values are a polynomial fit to the data table from HBEFA4. All coefficients of the polynomial are positive but we didn't explicitly filter out negative values until now.  You can find quality metrics for the data fit at https://sumo.dlr.de/docs/Models/Emissions/HBEFA4-based.html
