### ISSUE TITLE
How to fix check and cast error in (LteMacUeD2D)

### ISSUE THREAD

**Issue by shakeri1992** [eclipse-sumo/sumo#15088]
Hello

I want to create a D2Dmulticast connection for cars, for this purpose I have considered the number of vehicles to be "30" and I have also changed a part of the code in the inifile, which is as follows:
*.car[ * ].numApps =1

car[0..30].ipv4.configurator.mcastGroups ="224.0.0.10"
// transmitter
car[0].app[ * ].typname ="AlertSender"
car[0].app[ * ].localport=3088+ancestorIndex(0)
car[0].app[ * ].startTime = uniform(0s,0.02s)
car[0].app[ * ].destAddress = "224.0.0.10"
car[0].app[ * ].desport =1000
// receivers
car[1..29].app[ * ].typename ="AlertReceiver"
car[1..29].app[ * ].localport =1000

I have also added this line of code from the README.txt file in the demo.xml file:

<multicast-group hosts="car[ * ]" interfaces="cellular" address="224.0.0.10"/>

When I run the simulation, I get the following error:

check_and_ cast():Cannot cast nullptr to type'LteMacEnbD2D*' in module(LteMacUeD2D)Highway.car[1].cellularNic.mac(id=409)

I don't know why I get this error and what does it means ?
I greatly appreciate any help!

**Comment by namdre** [comment]
Sorry, but this is the wrong project for your question. Maybe this can help: https://veins.car2x.org/documentation/faq/

**Comment by shakeri1992** [comment]
I'm sorry, thank you for your replaying

در تاریخ سه‌شنبه ۲۵ ژوئن ۲۰۲۴،‏ ۰۸:۳۴ Jakob Erdmann <
***@***.***> نوشت:
