### ISSUE TITLE
Rerouter does not have any effect (sumo 1.20)

### ISSUE THREAD

**Issue by davide990** [eclipse-sumo/sumo#15094]
Hello, I tried to setup a little example where I close one edge and I want the vehicles to reroute exactly to one specific edge. But this does not seems to work as expected. Here's the rerouter definition:

`<additional>
<rerouter id="example" edges="-19 17">
   <interval begin="0" end="3600">
    <closingReroute id="-9" disallow="all"/>
   </interval>
</rerouter>
</additional>`

So here I close edge -9, put the rerouter in -19 and I want the vehicles to be redirected exactly to edge 17. But, the vehicles seem to go freely either to edge 17 or 25, ignoring the rerouter definition.

I join the example in a zip file.

Do I forgot something??

[rerouting example.zip](https://github.com/user-attachments/files/15971455/rerouting.example.zip)

**Comment by namdre** [comment]
1. the edges attribute of the rerouter doesn't define the new route but rather all edges on which a "notification" is posted to make vehicles aware of the road closure and let them find a new route
2. if you want to disable right turns from edge `-19` you can add `  <closingReroute id=":8_4" disallow="passenger"/> ` (this closes the internal lane for right turns, see https://sumo.dlr.de/docs/sumo-gui.html#investigating_internal_edges_and_lanes
3. cars that use the closed edge `-9` as their destination will block the simulation. You can counteract this with `terminateRoute`

```
<rerouter id="example" edges="-19 -17 -25 9">
   <interval begin="0" end="3600">
    <closingReroute id="-9" disallow="passenger"/>
    <closingReroute id=":8_4" disallow="passenger"/>
    <closingReroute id=":8_7" disallow="passenger"/>
    <destProbReroute id="terminateRoute" probability="1"/>
   </interval>
</rerouter>
```

**Comment by namdre** [comment]
you could also use a `<destProbReroute id="17" probability="1"/>`
