### ISSUE TITLE
Discrepancy between laneData and edgeData in Meso Simulation

### ISSUE THREAD

**Issue by alayasreih** [eclipse-sumo/sumo#15093]
Continuing the issue posted to the mailing list, here is a minimal scenario. Edge '767378478' is a good example where there is a high difference between edge and lane output.

![image](https://github.com/eclipse-sumo/sumo/assets/103211467/f0dab48d-40d8-4882-9710-09982b5b1266)

[test_example.zip](https://github.com/user-attachments/files/15969127/test_example.zip)

**SUMO-version: 1.20.0**

**operating system: Windows 11 Enterprise 23H2**

**Comment by ambuehll** [comment]
just as a quick double-check: this bug did not affect edge-based outputs, right?

**Comment by namdre** [comment]
For all I know, no.
