### ISSUE TITLE
Questions about tool “randomTrips.py”

### ISSUE THREAD

**Issue by xql5891129** [eclipse-sumo/sumo#15108]
Add your issue description here.
When I use the “randomTrips.py” tool and attach the “--additional-files” attribute to generate the bus，
I have some bus stops in my “additional.add.xml” file, so will the randomly generated bus route pass through the bus stops？

*If possible, upload an example that shows your problem.*
python D:\SUMO\tools/randomTrips.py -n net.net.xml -r bus.rou.xml --additional-files additional.add.xml --vtype="bus"

**SUMO-version:**
1.20.0
**operating system:**
windows11

**Comment by namdre** [comment]
No. If you want cars to stop at random stops you can use https://sumo.dlr.de/docs/Tools/Routes.html#addstops2routespy after calling randomTrips.py (call it multiple times if you want multiple stops)

**Comment by xql5891129** [comment]
> 不。如果你想让汽车在随机停靠点停下来，你可以在呼叫 randomTrips.py 后使用 https://sumo.dlr.de/docs/Tools/Routes.html#addstops2routespy（如果你想要多次停靠，可以多次调用它）

Thank you very much
