### ISSUE TITLE
Extend net2geojson.py to optionally include numLanes and speed as properties

### ISSUE THREAD

**Issue by RobertHilbrich** [eclipse-sumo/sumo#15109]
Geometries in GeoJSON format of a SUMO network are sometimes used in web-based applications (e.g. SESAM or Baustellenatlas) based on OpenLayers or Leaflet. It would be great to include the following additional properties for an edge (or lane) as part of the GeoJSON input:

- Number of lanes
- Speed limit
- Maybe: allow/disallow status

These properties should be optional to avoid inflating the resulting file if they are not needed.

Tricky: what if lane geometries are rendered, but we want to include edge properties (e.g., number of lanes).

**Comment by behrisch** [comment]
Before closing this we might want to rethink the names of the extra attributes in geojson. I admit that "laneIndex" and "allowedVehicles" is more self-explanatory but sticking to the "original" names "index" and "allow" has its benefits too.

**Comment by aminissn** [comment]
Original names are fine by me, I have no strong opinion.

**Comment by RobertHilbrich** [comment]
Thank you for your contribution @aminissn. I added "allow" for the edges as well and switched to "original" names. This should conclude this issue.
