### ISSUE TITLE
Expires when the additional uses the  “Draw with constant size when zoomed out Draw with constant size when zoomed out” function

### ISSUE THREAD

**Issue by xql5891129** [eclipse-sumo/sumo#15104]
**Update**: Has to be extended to demand elements

When I use the “Draw with constant size when zoomed out Draw with constant size when zoomed out” function, keep zooming the map and the busstop disappears

*If possible, upload an example that shows your problem.*

![1](https://github.com/eclipse-sumo/sumo/assets/76653806/10c166cf-ff9e-4da2-a648-5d0c1a92da8e)
![2](https://github.com/eclipse-sumo/sumo/assets/76653806/d36d7013-1c99-4556-9ca7-34e3ac68a7c8)

**SUMO-version:**
1.20.0
**operating system:**
windows11

**Comment by m-kro** [comment]
All additional elements are drawn only from a certain zoom level on. This seems to be related with #13894 .

**Comment by palvarezlopez** [comment]
@xql5891129 thanks for reporting it!

**Comment by xql5891129** [comment]
> 所有其他元素仅从特定的缩放级别绘制。这似乎与 #13894 有关。Thanks for the answer

**Comment by namdre** [comment]
regression in 1.20.0
