### ISSUE TITLE
Build an overpass in SUMO

### ISSUE THREAD

**Issue by TracyLiu556** [eclipse-sumo/sumo#15107]
Hi, I'm trying to build an overpass in SUMO according to a real overpass. I know that I can add height to the edges in the net file to change the height of the road. But where can I get the height information from? The open street map data does not contain the heights of the roads. What is the easiest way to do it?

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Networks/Elevation.html
the easiest thing is probably https://sumo.dlr.de/docs/Networks/Import/OpenStreetMap.html#layer_information

Note, that the core models of sumo don't require z-data and will work fine if you put everything at z=0
