### ISSUE TITLE
Traffic Lights Reinforcement Learning Agent

### ISSUE THREAD

**Issue by Cornslakes** [eclipse-sumo/sumo#15113]
Hey together,

I am currently working on a university project where the goal is to develop a reinforcement learning agent which controls the traffic light states.
I heard that SUMO is the most appropriate for it as the a-b-street API isn't very supportive towards versatile access to traffic lights states, agent positions etc.

Has someone already worked on some similar project and can maybe help me get a starting point on how to best develop a "light-weight" approach? It's not a big project but the topic seems interesting to me.

Thanks for any help in advance!

**SUMO-version:**1.20.0

**operating system:** WIN11

**Comment by JamesPsh** [comment]
Hi there,

I've worked on a similar project and found some repositories that might be helpful for you:

1. [ReinforcementLearning-TrafficLights](https://github.com/JamesPsh/ReinforcementLearning-TrafficLights): This repository provides an example of controlling traffic lights using reinforcement learning.
   
2. [deeprl_signal_control](https://github.com/cts198859/deeprl_signal_control): This repository also focuses on traffic signal control using deep reinforcement learning.
   
3. [Deep-QLearning-Agent-for-Traffic-Signal-Control](https://github.com/AndreaVidali/Deep-QLearning-Agent-for-Traffic-Signal-Control): This repository explains traffic signal control using deep Q-learning.

I hope these resources help you get started with your project. They should work well with SUMO. If you have any questions, feel free to ask!

Thanks.

**Comment by ambuehll** [comment]
Have a look at: https://arxiv.org/abs/2311.09851
DeePC cc: @AlessioRimoldi

**Comment by AlessioRimoldi** [comment]
Here to help if needed!

**Comment by behrisch** [comment]
Thanks for all the input!
