### ISSUE TITLE
mapDetectors.py: failure to read CSV with BOM

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#15116]
- see https://stackoverflow.com/questions/40310042/python-read-csv-bom-embedded-into-the-first-key
- workarounds: https://unix.stackexchange.com/questions/381230/how-can-i-remove-the-bom-from-a-utf-8-file

**Comment by behrisch** [comment]
The solution is to use "utf-8-sig" as input encoding whenever you are unsure whether the file may have a BOM. This will always work also if the file has no BOM and is now the default for sumolib.openz
