### ISSUE TITLE
Crash removing junction with crossing in loaded network

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse-sumo/sumo#15112]
1) Load network
2) Delete junction Junction4
3) Crash

Related with crossings

[net.net.xml.zip](https://github.com/user-attachments/files/16015063/net.net.xml.zip)

**Comment by namdre** [comment]
regression in 1.20.0

**Comment by namdre** [comment]
@palvarezlopez  please set up a regression test for this

**Comment by namdre** [comment]
as a side effect, crossings are visible now upon first loading a network.

**Comment by palvarezlopez** [comment]
> @palvarezlopez please set up a regression test for this

yes!
