### ISSUE TITLE
traci changeTarget and setRoute issue

### ISSUE THREAD

**Issue by yougeyxt** [eclipse-sumo/sumo#15123]
I try to use `traci.vehicle.changeTarget` and `traci.vehicle.setRoute` to update the vehicle's target however both of them fail (with both traci and libsumo). In the attached minimum example, I anticipate the vehicle will pass the intersection to reach the new target, however, it leaves the network at the end of the edge. 

I am using SUMO 1.19.0 and Linux Ubuntu 20.04.

Thank you!

[sumo-change-target-issue.zip](https://github.com/user-attachments/files/16042764/sumo-change-target-issue.zip)

**Comment by namdre** [comment]
regression in 1.13.0 via #4250

**Comment by yougeyxt** [comment]
Hi, I tried the nightly build 1.20.0.post484. However, the issue seems still there.

[sumo-change-target-issue.zip](https://github.com/user-attachments/files/16075888/sumo-change-target-issue.zip)

**Comment by namdre** [comment]
That one is too old. Todays version is v1_20_0+0963-89ad34cf688  
We currently have a problem with outdated python wheels. In the meantime you could download a binary directly or build from source.

**Comment by yougeyxt** [comment]
Hi namdre, thank you so much. However, I did not find the latest traci and sumolib in https://sumo.dlr.de/daily/wheels/ (I do find eclipse-sumo and libsumo). I would prefer not to build from source since I want to use virtual env. Could you please help me with that? Thanks a lot.

**Comment by namdre** [comment]
We did some changes to our build process. Please check again at https://sumo.dlr.de/daily/wheels/
