### ISSUE TITLE
How to apply two or three types of prefix files to '--weights-prefix' option in randomTrips.py? 

### ISSUE THREAD

**Issue by TGW795** [eclipse-sumo/sumo#15124]
Hi.

I've been trying to generate a route file with restricted departures and destinations edges with randomTrips.py,  however, only one of the files, departure.src.xml or destinations.dst.xml can be applied to '--weights-prefix' option. How should I do to generate such a route file?

**SUMO-version:**
1.20.0
**operating system:**
Ubuntu 20.04

Thank you.

**Comment by TGW795** [comment]
Resolved by creating a python code that generates rou.xml file.

**Comment by namdre** [comment]
for the record: the **--weights-prefix** option only takes the *prefix* of the file name so you would create two files *custom.src..xml* and *custom.dst.xml* then set option **--weights-prefix custom**.

**Comment by TGW795** [comment]
Thanks!
