### ISSUE TITLE
Assessing Node Connectivity in Pedestrian Sidewalk Networks

### ISSUE THREAD

**Issue by M-Colley** [eclipse-sumo/sumo#15127]
I need to determine how well a given node (specifically within a pedestrian sidewalk network) is connected to the remaining network. This assessment should not simply count incoming edges but should perhaps be recursive to provide a more comprehensive measure of connectivity.

The motivation for this is to better decide on the placement of certain buildings and other infrastructure. I believe that the PageRank algorithm could be relevant here (https://en.wikipedia.org/wiki/PageRank).

Could you please let me know if this kind of connectivity assessment is already possible within SUMO? If not, are there other metrics or methods available within SUMO to evaluate the connectedness of a given node in a network?

Thank you!

**Comment by namdre** [comment]
you can use duarouter options **--intermodal-nework-output** and **--intermodal--weight-output** to expose the intermodal routing graph (including sidewalks, crossing and public transport). This should make it rather easy to compute an isochrone map or whatever analysis you need.
