### ISSUE TITLE
Crash moving a massive network

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse-sumo/sumo#15132]
1. Select all network elements
2. try to move

[net.net.xml.zip](https://github.com/user-attachments/files/16065541/net.net.xml.zip)

**Comment by namdre** [comment]
problem first shows up in version 1.16.0
Notably, the failing versions freeze for a while before crashing which indicates heavy computation. Version 1.15.0. was somewhat fast when moving large selections.

**Comment by palvarezlopez** [comment]
<img width="979" alt="{87CE1C85-E2F4-4D21-B749-9B5F72552169}" src="https://github.com/user-attachments/assets/19bc8a6c-9a12-4e8f-a271-852017cf5f85">

myMoveOperations contains invalid elements

**Comment by palvarezlopez** [comment]
The crash is related with the connection geometries
