### ISSUE TITLE
Clearing the build folder resolved the cmake issue

### ISSUE THREAD

**Issue by Fisher-007** [eclipse-sumo/sumo#15131]
Hello, I compiled SUMO-1.16.0 on Ubuntu 18.04 and found an error during the process:

```txt
[ 36%] Linking CXX executable /home/dongyu/sumo/SUMO/bin/sumo
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
src/CMakeFiles/sumo.dir/build.make:130: recipe for target '/home/dongyu/sumo/SUMO/bin/sumo' failed
make[2]: *** [/home/dongyu/sumo/SUMO/bin/sumo] Error 1
CMakeFiles/Makefile2:1986: recipe for target 'src/CMakeFiles/sumo.dir/all' failed
make[1]: *** [src/CMakeFiles/sumo.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
```

But when I cleared other files in the `build` folder, I recompiled successfully, why did this happen? What are the effects of other files in the `build` folder on SUMO, and will this practice affect the subsequent use of SUMO?

Has anyone encountered this issue before, or knows the answer  to the question, many thanks!

**Comment by namdre** [comment]
The file in the build folder are all created during the build process and no longer used afterwards so you will not suffer negative effects when you delete them.    Deleting the build folder is a known remedy if a build got stuck for some reason.

**Comment by Fisher-007** [comment]
Thanks for your reply!

But I noticed that, not all files in `build` folder are created during the build process in the old version (e.g. 1.16.0), in that version all files in `cmake-build` folder are created during the build process, while other files in `build` folder are originally in the source code.

Because they are included in the source code, I am not sure if it will affect the compiled SUMO.

**Comment by namdre** [comment]
files are copied from the src into the build hierarchy. At some point we changed the build process so that the former role of the `cmake-build` folder is now taken by the  `build` folder.

**Comment by Fisher-007** [comment]
Thank you @namdre for your help
