### ISSUE TITLE
[build minor issue]  MSStoppingPlaceRerouter.cpp

### ISSUE THREAD

**Issue by usamael2000** [eclipse-sumo/sumo#15130]
I am building sumo from source, and in the last three days I am getting this warning:

#########
[ 19%] Building CXX object src/microsim/transportables/CMakeFiles/microsim_transportables.dir/MSPModel_Interacting.cpp.o

/home/usama/sumo/src/microsim/trigger/MSStoppingPlaceRerouter.cpp: In member function ‘MSStoppingPlace* MSStoppingPlaceRerouter::reroute(std::vector<std::pair<MSStoppingPlace*, bool> >&, const std::vector<double>&, SUMOVehicle&, bool&, ConstMSEdgeVector&, const MSEdgeVector&)’:
/home/usama/sumo/src/microsim/trigger/MSStoppingPlaceRerouter.cpp:85:83: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]

   85 |     if ((stopAnywhere < 0 || (stopAnywhere > getNumberStoppingPlaceReroutes(veh)) && myStoppingType == SUMO_TAG_PARKING_AREA)) {
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#### END of Warning ##

I am not sure this would affect the simulation, but may be you have a different opinion.

**SUMO-version:** Eclipse SUMO sumo Version v1_20_0+0946-0eafbaa8d0b (built from source)

**operating system:** Debian GNU/Linux trixie x86_64

**Comment by m-kro** [comment]
This part has been rewritten very recently to be reusable at other places in the simulation. We have changed the condition (see #14504), thank you.

**Comment by usamael2000** [comment]
This is to confirm the warning is no longer appear.
Thanks
