### ISSUE TITLE
an error about the function traci.trafficlights.setCompleteRedYellowGreenDefinition;

### ISSUE THREAD

**Issue by sjh30** [eclipse-sumo/sumo#15134]
I met some problems when i use the function `traci.trafficlights.setCompleteRedYellowGreenDefinition(tlsID,tls)` in the matlab
when i use the function `tls=traci.trafficlights.Logic(programID, type, currentPhaseIndex,phases,subParameter);` and i can use it correctly . Hovever, i met some problems  when i use `traci.trafficlights.setCompleteRedYellowGreenDefinition(tlsID,tls)`. 
and here is my code:
```
phase_0 = struct('duration', 60, 'state', 'GGGGGGGrrrGGGGGGGrrr','minDur', 10, 'maxDur', 30, 'next', ([])); % Using character array for state
phase_1 = struct('duration', 60, 'state', 'rrrGGGGGGGrrrrGGGGGG','minDur', 10, 'maxDur', 30, 'next', ([]));
phases = {phase_0, phase_1};
% tls = struct();
type = 0;
currentPhaseIndex = 0; % 当前相位索引
programID = '1';
% tls.phases = phases;
subParameter = containers.Map();
tls=traci.trafficlights.Logic(programID, type, currentPhaseIndex,phases,subParameter);
traci.trafficlights.setCompleteRedYellowGreenDefinition(tlsID, tls); 
```
and the error messages are followed :
```
Error: Answered with error to command 0xc2: set program 4.5 parameter (next) must be a compound (list of ints).
Error: Answered with error to command 0xc2: Wrong position in requestMessage after dispatching command 194. Expected command length was 164 but 156 Bytes were read.
```
 Can anyone tell me how to solve this problem?

**Comment by sjh30** [comment]
P.S :my sumo version is 1.19.0

**Comment by m-kro** [comment]
The problem concerns the "next" value is defined in the first line of your code snippet. This does not seem to convert to the data type used in TraCI (list of integers). I am not a MATLAB expert, but have you tried to use [this notation for typed arrays](https://www.mathworks.com/help/matlab/ref/empty.html) instead?

**Comment by sjh30** [comment]
P.S  i use the code phase_0 = struct('duration', 60, 'state', 'GGGGGGGrrrGGGGGGGrrr','minDur', 10, 'maxDur', 30, 'next',int32([1])); 
and the error is still the same

**Comment by m-kro** [comment]
Did you try `py.list` as mentioned in the [MATLAB documentation](https://www.mathworks.com/help/matlab/matlab_external/pythonlistvariables.html)?

**Comment by sjh30** [comment]
could you tell me why i should try py.list ,because i use traci4matlab  and use the function setCompleteRedYellowGreenDefinition in the matlab directly。i just wanna know that i have to use    py.list or i can choose another way to solve the error.

**Comment by m-kro** [comment]
Sorry, I didn't look close enough because there is also the option to [use the standard TraCI python client in MATLAB](https://www.mathworks.com/help/matlab/call-python-libraries.html) and I mixed up both options. So traci4matlab has become obsolete, hasn't been updated for long and probably won't be anymore. Would you mind trying the python client directly? Otherwise you could still try to print the result of `traci.trafficlights.setCompleteRedYellowGreenDefinition` and try to replicate it in the set function.

**Comment by sjh30** [comment]
i tried  to print the result of traci.trafficlights.getCompleteRedYellowGreenDefinition and try to replicate it in the set function.  Unfortunately,it is still wrong .So,is there ant chance that this function is wrong ,and i should use TraCI python directly. Thanks for your reply
