### ISSUE TITLE
warn about unusual distribution values

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#15146]
Defining a distribution like normc(50000,3000,0.1,10) is not wrong but also probably not the intention of the author. An idea would be to give a warning and ignore the bounds if they are outside of (mean +/- 2 stddev). The problem with those definitions is that they can slow down the simulation startup considerably because sumo tries repeatedly to draw values from the distribution until they fit the bounds.

**Comment by behrisch** [comment]
We should fail hard if we sample more than a 100 times

**Comment by namdre** [comment]
or rather if we expect having to sample more than 100 times. Because we don't want failure to depend on the random seed.

**Comment by behrisch** [comment]
two standard deviations are probably too little (about 5% is outside this range), so I decided for three standard deviations which gives more in the range of 500 samples but should still be fast enough and is more transparent to the user (3-sigma rule is even a term). We should probably still check whether minimum and maximum are too close to each other.

**Comment by behrisch** [comment]
The check is now for a distance of less than 0.001 * stddev which means a probability of less than 0.08%.
