### ISSUE TITLE
Allow dynamically adding personTrip (i.e. with "modes=taxi")

### ISSUE THREAD

**Issue by JulianCzymmeck** [eclipse-sumo/sumo#15154]
Hi sumo team, 
I would like to convert (some of) my vehicles in a simulation to taxi customer pedestrians to simulate the effects of alternative traveling options, such as urban aerial mobility, on traffic in a large scale. Ideally I would like to do this during simulation time using traci and avoid writing new rou.xml files. The pedestrians should be functionally identical to the following xml definition:
```
<person id="converted_ped_xx" depart="0.00">
        <personTrip from="from_edge" to="to_edge" modes="taxi"/>
</person>
```
I can easily get and set the id, departure time and departure edge for the pedestrian I want to create, but I can't find a way to create a taxi customer with traci. I also struggle with adding the destination edge, since I don't want to append a walking stage, as I assume that this might not work with driving in a taxi.
One more related question: Is it possible to further narrow down that the pedestrian should only use a certain type of taxi, as I use a custom vClass with a taxi device. When only specifying "modes=taxi" I am unable to use other taxi services is my simulation, as it would be unclear which service should be used.

Thank you!

**Comment by namdre** [comment]
- there is currently no possibility for creating personTrips with traci
- you can add a riding stage with `lines="taxi"` to define a person that will automatically create a reservation with the taxi dispatcher (`traci.person.appendDrivingStage`)
- you can use something like  `lines="taxi:fleetA"` to limit usage to parts of the fleet (see https://sumo.dlr.de/docs/Simulation/Taxi.html#multiple_taxi_fleets)

**Comment by JulianCzymmeck** [comment]
Thank you for the quick response. One question regarding appending a driving stage:
When adding a pedestrian to the simulation, given a starting edge, and then appending said driving stage with `lines="taxi:uamFleet"` and the very last edge of the trip, will the pedestrian walk to an edge/lane where taxis are permitted, and then drive as far as possible (and walk the rest of the way)? Or does appending a driving stage lock the pedestrian from walking.
This is very relevant for my simulation, as the taxis I'm using are heavily restricted on where they are allowed.
Additionally, if the taxi road network is far from the route from the starting point to the destination, would the pedestrian walk to the destination without interacting with the taxi network at all (this would be the desired behaviour)?

**Comment by namdre** [comment]
If you need walking in addition to taxi use, then appending a single driving stage won't work. Here is what you can do instead:
- call `traci.simulation.findIntermodalRoute(..., modes="taxi")
- append the list of returned stages with `traci.person.appendStage` (it will be a mix of walking and driving)
  - for every driving stage, change lines from `taxi` to the desired fleet (i.e. `taxi:uamFleet`)

This will work as long as the pick-up and drop-off locations don't differ between the fleets.

**Comment by JulianCzymmeck** [comment]
Unfortunately this suggested solution doesn't always work. It has the following issue:
When calling `traci.simulation.findIntermodalRoute(fromEdge=<edgeWithRestrictedAccess>, ... , modes="taxi")`, for example if the starting edge is a pedestrian only edge, the following warning occurs: `Warning: Ignoring vehicle type 'DEFAULT_TAXITYPE' when performing intermodal routing because it is not allowed on the start edge 'E14'`.
This results in only one stage (walking) getting generated, even though there is a section with taxi traffic in the middle. Furthermore, if the route to the destination is not reachable by foot (contains a section where pedestrians are disallowed and no sidewalk), but would have been reachable via taxi for example, an empty string gets returned.

For my specific use case thus this solution never works, as I always want the pedestrian to use an "aerial lane" where only uam taxis are allowed.
Is there any other way of doing this or am I stuck with editing xml files?

**Comment by namdre** [comment]
This does sound like a bug. I'll investigate.

**Comment by namdre** [comment]
The bug (#15172) has been fixed and you can obtain an updated version tomorrow at https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots
Note, that you either have to have at least one taxi in the simulation before calling findIntermodalRoute or set options
 **--persontrip.transfer.walk-taxi allJunctions --persontrip.transfer.taxi-walk allJunctions** for routing to succeed.

**Comment by namdre** [comment]
I'm afraid, this kind of co-existence is currently not supported. I also had to disallow taxi on all non-aerial edges in [this years tutorial](https://youtu.be/9WCGxJDdY9s). The relevant ticket is #9812
