### ISSUE TITLE
customized required waiting time at stop sign

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#15163]

**Comment by kasop1** [comment]
@namdre nice to meet you.
I want to change the pause time (jmStopSignWait) in allwaystop, but it doesn't work. please tell me.

**Comment by namdre** [comment]
this is supported in the latest dev version (#15428) using `jmAllwayStopWait`

**Comment by kasop1** [comment]
Thank you.
I am using sumo 1.20version. But I can not use jmAllwayStopWait.
I'm very sorry, but could you please write an example sentence?

**Comment by namdre** [comment]
the latest dev version is v1_20_0-1864-gce7940e5e49 you can download updated binaries tomorrow at https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots

**Comment by kasop1** [comment]
Thank you. I got it.
What is the difference between jmAllwayStopWait and jmStopSignWait?

**Comment by namdre** [comment]
One is for allway_stop and the other is for priority_stop. In the first situation, drivers know that all other drivers have to stop so, running the stop sign is somewhat "safe". In the second type, the other roads have priority and running the stop sign is a lot more dangerous.  Since the model parameters can be used to disable stopping they should be treated separately.

**Comment by kasop1** [comment]
Thank you.
I installed new version "v1_20_0+1854-a5de182d326".
I can use jmstopsignWait. 
cvc-complex-type.3.2.2: Attribute 'jmStopSignWait' is not allowed to appear in element 'vType'.
why?

**Comment by namdre** [comment]
You are using the version built tonight. It also contains an invalid error in xsd-schema validation (you can circumvent this: https://sumo.dlr.de/docs/XMLValidation.html#disabling_schema_validation) or simply download again tomorrow for a fix which also supports the new attribute.

**Comment by kasop1** [comment]
I got it. Thank you.
Is it correct to interpret that tomorrow's version will allow both("jmstopsignWait" and "jmAllwayStopWait")  to be used?

**Comment by namdre** [comment]
please provide more information (https://sumo.dlr.de/docs/FAQ.html#how_do_i_report_erroneous_behavior_of_a_sumo_application)
