### ISSUE TITLE
About pedestrians did not take the bus

### ISSUE THREAD

**Issue by xql5891129** [eclipse-sumo/sumo#15162]
Add your issue description here.
I have a bus line line0 and I define a personFlow that is on line0, but after I run the simulation, the pedestrian is not on the bus。
And give a warning：Not using public transport line '0' for routing persons. It has less than two usable stops.

*If possible, upload an example that shows your problem.*
My personFlow  is indicated by the red arrows on the map
![image](https://github.com/eclipse-sumo/sumo/assets/76653806/b0add3d1-5983-4a49-a0bb-1aa7a3c6b3b3)

**SUMO-version:**
1.20
**operating system:**
Windows11

**Comment by m-kro** [comment]
This error message is triggered when the bus schedule has some flaws regarding the stop departure times (`until` attribute). If a previous stop is set to leave later than the current one, the stops are discarded.

**Comment by xql5891129** [comment]
> 当公交车时刻表在站点出发时间（属性）方面存在一些缺陷时，会触发此错误消息。如果将上一个停靠点设置为晚于当前停靠点离开，则该停靠点将被丢弃。`until`

But I didn't set the until attribute
![image](https://github.com/eclipse-sumo/sumo/assets/76653806/9741efd8-472c-4a3e-802a-92a5f616791c)

**Comment by m-kro** [comment]
Can you please share a preferably small scenario where the problem can be observed?

**Comment by xql5891129** [comment]
> 您能否分享一个可以观察到问题的小场景？

The route of the pedestrians was on the bus_0, but instead of stopping at the bus stop, these pedestrians continued on.
（My personFlow has set ” modes=’public‘ “）

https://github.com/eclipse-sumo/sumo/assets/76653806/2bc011fc-3380-487b-bb99-4ff4553dbc58

**Comment by m-kro** [comment]
Actually I meant the SUMO files to replicate the problem, not a video...

**Comment by m-kro** [comment]
Please wait until the upload is finished. When you post earlier the link just points to the issue and there is no scenario to download.

**Comment by xql5891129** [comment]
I'm really sorry, this time I finished uploading
[Test.zip](https://github.com/user-attachments/files/16125170/Test.zip)

**Comment by m-kro** [comment]
Although it may easily be overseen in the [documentation](https://sumo.dlr.de/docs/Simulation/Public_Transport.html#public_transport_schedules), the `until` attribute is necessary for public transport flows.
