### ISSUE TITLE
Additionals disappear at certain zoom levels in netedit

### ISSUE THREAD

**Issue by henrigrossmann** [eclipse-sumo/sumo#15175]
**Description:**
I am experiencing an issue with netedit version 1.20.0 where additional elements such as detectors are not drawn in constant size when zoomed out. Initially, the detectors are displayed with a constant size, but upon further zooming out, they suddenly disappear.

**Steps to Reproduce**
Open netedit with the provided net
Load additional
In view settings: set additionals to be "Draw with constant size when zoomed out"
Zoom out gradually and observe the behavior of the display of detectors.

**Expected Behavior**
Detectors should be displayed with a constant size irrespective of the zoom level, allowing for continuous visibility.

**Actual Behavior**
Detectors are displayed with a constant size only up to a certain level of zooming out. Beyond this level, they disappear  or are not visible anymore because they are too small.

**Sample Data**
I have attached the sample data that reproduces this issue.

**Additional Information**
SUMO Version: 1.20.0
Operating System: MacOS 14.5

Thank you for looking into this!

[sample.zip](https://github.com/user-attachments/files/16141871/sample.zip)

**Comment by namdre** [comment]
Thanks. It's already tracked at #15104
