### ISSUE TITLE
Error: tcpip::Storage::readIsSafe: want to read 4 bytes from Storage, but only 3 remaining

### ISSUE THREAD

**Issue by 2901162744** [eclipse-sumo/sumo#15182]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by 2901162744** [comment]
I conducted simulations using a JSON configuration file.

**Comment by m-kro** [comment]
SUMO uses XML configuration files. Do you use some other software together with SUMO like OMNeT++/Veins?

**Comment by 2901162744** [comment]
I haven't used software like OMNeT++ or Veins together with SUMO，and I'm trying to run SUMO using a Python script.

**Comment by 2901162744** [comment]
![1](https://github.com/eclipse-sumo/sumo/assets/145012396/b0a296e6-03f6-47c8-8459-6b7d5da786e4)

**Comment by 2901162744** [comment]
![Uploading 1.png…]()

**Comment by 2901162744** [comment]
![Uploading 1.png…]()

**Comment by m-kro** [comment]
So it seems you use `https://github.com/jlubars/RL-MPC-LaneMerging`. On their github page they state compatibility with SUMO 1.7. Which version do you use?

**Comment by 2901162744** [comment]
Yeah, I'm currently replicating this code. However, I previously downloaded version 1.7.0, but SUMO displays version 0.32. What could be the reason for this? I am currently using the SUMO version from GitHub repository.

**Comment by m-kro** [comment]
Please follow the instructions at [https://github.com/jlubars/RL-MPC-LaneMerging](https://github.com/jlubars/RL-MPC-LaneMerging). You have to set the environment variable **SUMO_HOME** to point to the main directory of the SUMO 1.7 installation.

**Comment by 2901162744** [comment]
I have a try again，thank you very much！
