### ISSUE TITLE
How to copy and paste an area of segments in SUMO netedit?

### ISSUE THREAD

**Issue by TracyLiu556** [eclipse-sumo/sumo#15189]
I built a roundabout in SUMO netedit and I'm trying to make another one on the same network. Can I copy the current roundabout and paste it at the location I want? Thanks.

**Comment by namdre** [comment]
No. Copy-paste isn't supported directly. But creating a roundabout can be done by right-clicking a junction a selecting "convert to roundabout".  Change junction attribute 'radius' beforehand to customize the roundabout radius.

**Comment by TracyLiu556** [comment]
> No. Copy-paste isn't supported directly. But creating a roundabout can be done by right-clicking a junction a selecting "convert to roundabout". 
Thanks! Is there any way in netconvert that I can copy and paste the certain area of my network in SUMO?

**Comment by namdre** [comment]
There is a somewhat complicated way:
- use netedit to cut out the part you want to copy 
- load and save it with netconvert and option --prefix (to obtain new edge and junction ids) and option --offset.x / --offset.y to shift it to the desired position
- load both networks with netconvert to merge them: https://sumo.dlr.de/docs/netconvert.html#merging_networks
