### ISSUE TITLE
Creating flows from detector count data when we have multiple edges on a lane

### ISSUE THREAD

**Issue by oshadajay** [eclipse-sumo/sumo#15207]
I am following https://sumo.dlr.de/docs/Tools/Detector.html#flowrouterpy to create traffic flows based on detector count data and I have a question on how to create flows when we have multiple edges on a lane. If we place one detector per each edge and have the counts separately in the flows.csv file would that work? Or if we have aggregated detector counts for all edges in each lane, is there a way to use that to create the flows? Appreciate your help getting this resolved. Thank you.

**Comment by namdre** [comment]
flowrouter will automatically aggregated all "parallel" detectors on the same edge. It will work 
- If your total count is split among multiple detectors
- and if there is a single detector holding the total count value per edge

**Comment by oshadajay** [comment]
@namdre Thanks a lot. On a different matter, if we are to count traffic flow from multiple edges on the same lane should we have to put multiple detectors in parallel and aggregate them? Is there a better way of doing this? Can E2 detectors be used? Thank you.

**Comment by namdre** [comment]
you can use E3 detectors or even edgeData to count traffic on the whole edge: https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html

**Comment by oshadajay** [comment]
@namdre Thanks a lot!
