### ISSUE TITLE
Edge data Output 

### ISSUE THREAD

**Issue by Nifemi954** [eclipse-sumo/sumo#15215]
Good day, edge data output returns nothing if I do not set the begin time to 0. Is there a way around this?

**Comment by m-kro** [comment]
Can you write down your edge data configuration (like [here](https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html#meandata_definition))? Normally it should work as well without specifying the begin time.

**Comment by Nifemi954** [comment]
<?xml version="1.0" encoding="UTF-8"?>



<meandata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/meandata_file.xsd">
</meandata>

**Comment by Nifemi954** [comment]
<?xml version="1.0" encoding="UTF-8"?>



<meandata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/meandata_file.xsd">
</meandata> the edgedata output just returns the above

**Comment by Nifemi954** [comment]
![edata](https://github.com/user-attachments/assets/9de5f876-a7a1-4b43-85fe-db2263aab075)

**Comment by Nifemi954** [comment]
I have realized my mistake and fixed it
