### ISSUE TITLE
Build E1/E2-Detectors for all traffic lights if defined via param

### ISSUE THREAD

**Issue by Domsall** [eclipse-sumo/sumo#15219]
We would like to use LaneArea detectors for a queue estimation at traffic lights. The detector information is going to be sent to the GLOSA device / vehicle, that calculates queue lengths depending on its position.

The needed information is already retrievable for some traffic lights (https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#custom_detectors_1 and via `getDetectorStates()`). We are currently using static TLlogic and it seems to be missing here (the function is a place holder).

Could the Code for custom detectors also be included for static traffic lights? Or does it somehow already work?

Thanks in advance!

**Comment by namdre** [comment]
No detectors are created for static programs. However, you could define actuated and static programs for all traffic lights and then only have the static programs active (and would still keep the detectors from the actuated ones).

**Comment by Domsall** [comment]
so if we just define the TL as "actuated" and do not define minDur/maxDur/etc., the TL logic stays the same as with static?

That would do the job.

**Comment by namdre** [comment]
At the moment, detectors are only built if they are relevant for an actuated phase and this is indicated by minDur != maxDur so this wouldn't work.  Though, an option that overrides this and always builds detectors for all lanes is feasible.
