### ISSUE TITLE
guessing crossings in netedit

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#15212]
The following workflow would be nice but does not work as expected:
Load a network, enable the crossings.guess option in the options dialog, press F5.
Even better: A separate checkbox where we enable / disable crossing guessing.

I remember we already discussed which options actually have an effect for an already loaded network but I don't remember the result or where this is documented (if at all).

**Comment by namdre** [comment]
set the option and then press Shift+F5 (compute with volatile options)
