### ISSUE TITLE
The implementation of the MOBIL model that can be integrated with SUMO 

### ISSUE THREAD

**Issue by LMCAV** [eclipse-sumo/sumo#15229]
I don't understand the C++ programming language. Could you help me add the IDM model and MOBIL model mentioned in the document to /src/microsim/lcmodels? 

[MOBIL and IDM.pdf](https://github.com/user-attachments/files/16262133/MOBIL.and.IDM.pdf)
If you could provide me with any help, I would be immensely grateful.

**Comment by m-kro** [comment]
See #15120 . The IDM [car-following model](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#car-following_models) is present in SUMO whereas the MOBIL lane-changing model is not.

**Comment by namdre** [comment]
There are currently no resources for adding the MOBIL model on our side. Especially not over the summer holidays. If you have a longer time horizon, help may be possible. Still, we cannot teach you C++ so I suggest you find a local programmer who can help you out.

**Comment by LMCAV** [comment]
Thanks for your prompt reply.
