### ISSUE TITLE
Having only the shortest path routes in flowrouter output

### ISSUE THREAD

**Issue by oshadajay** [eclipse-sumo/sumo#15225]
Hi, when using flowrouter to create flows from inductor count data, I have observed that the output has routes like the following. This route contains loops and has a low probability of becoming an actual route of a vehicle. I understand that by having these kind of routes, it would be easier to match the inductor count data. Yet is there a way to calculate the flows only using shortest path routes between sources and sinks? Or is there any other tool which is better handling this? Thank you very much.

```
<route id="B4B3_C3C4.qPKW.1425.0" edges="B4B3 B3B2 B2C2 C2C1 C1C2 C2C3 C3C2 C2C1 C1C2 C2C3 C3B3 B3C3 C3D3 D3C3 C3C4"/>
```

**Comment by namdre** [comment]
The problems of implausible routes are discussed at https://sumo.dlr.de/docs/Demand/Routes_from_Observation_Points.html#choosing_the_right_tool

I would recommend routeSampler.py where you can specify a set of candidate (i.e. shortest-path) routes in advance.

**Comment by oshadajay** [comment]
@namdre worked like a charm. Thank you very much.
