### ISSUE TITLE
Crash replacing junction by geometry point

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse-sumo/sumo#15233]
[replace_junction_by_geometry_point.zip](https://github.com/user-attachments/files/16264929/replace_junction_by_geometry_point.zip)

**Comment by transport45678** [comment]
#14863

**Comment by palvarezlopez** [comment]
> regression? If so which version?

I think this is not a regression ( the original test was did in a network without demand elements)

**Comment by namdre** [comment]
was only crashing before the first F5
