### ISSUE TITLE
Saturation flow

### ISSUE THREAD

**Issue by SSAreddt** [eclipse-sumo/sumo#15234]
How to set saturated traffic in sumo simulation software

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/RoadCapacity.html which explains the necessary parameters (i.e. departSpeed="avg").

**Comment by SSAreddt** [comment]
> 请参阅https://sumo.dlr.de/docs/Simulation/RoadCapacity.html，其中解释了必要的参数（即departSpeed="avg"）。

Thank you for your reply
