### ISSUE TITLE
What's the meaning of ROUTE-SETPS in DuaIterate.py tool

### ISSUE THREAD

**Issue by pjj-OSM** [eclipse-sumo/sumo#15259]
I am using DuaIterate.py to get trips by Dynamic User Equilibrium method, but i can't understand the meaning of the parameters of ROUTE-SETPS, i need some guidance, thank you.
<img width="1129" alt="4" src="https://github.com/user-attachments/assets/e193ffe1-5bec-4ab2-b026-e368a1fa0fdf">

**Comment by m-kro** [comment]
It is the time interval in seconds for which future routes are loaded (checked, determined). See [this explanation](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#routes) in the documentation.
