### ISSUE TITLE
SUMO  sumo-gui UNKNOWN

### ISSUE THREAD

**Issue by rechuin** [eclipse-sumo/sumo#15250]
Hello together and sumo comunity
I'm a new user of Sumo and after installing it I realized that there is no version number on the GUI, only UNKNOWN.
I have tried several demo programs and they all work fine.
I was wondering if this is a big problem for using Sumo?
![image](https://github.com/user-attachments/assets/2a9e023d-b43a-4b40-ab1f-af029989812e)

**Comment by m-kro** [comment]
This means the build process was not able to detect/generate a version information. Other than that, the program should work fine.

**Comment by behrisch** [comment]
> **I also found some warning information when I install the application as below, do you think these error messages will influence on the performance of the sw?** Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.3.1/maven-jar-plugin-2.3.1.pom [WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-jar-plugin:2.3.1: Plugin org.apache.maven.plugins:maven-jar-plugin:2.3.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-jar-

No, this usually means a network problem either on your side or on the maven side. Unless you want to do some java stuff (libsumojni, libtracijni, traas or lisum) you can safely ignore it.

**Comment by rechuin** [comment]
> > **I also found some warning information when I install the application as below, do you think these error messages will influence on the performance of the sw?** Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.3.1/maven-jar-plugin-2.3.1.pom [WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-jar-plugin:2.3.1: Plugin org.apache.maven.plugins:maven-jar-plugin:2.3.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-jar-
> 
> No, this usually means a network problem either on your side or on the maven side. Unless you want to do some java stuff (libsumojni, libtracijni, traas or lisum) you can safely ignore it.

But if I want to build the co simulation framework between sumo and VTD/CarMaker, do I need these libraries that you mentioned in the previous comment?
