### ISSUE TITLE
default capacity of a parkingArea is 0

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#15264]
If you define a parkingArea without giving roadSideCapacity or explicit lots, it has capacity 0. That is at least unexpected because it has a visual extension of exactly one default vehicle length. So probably 1 is the better default. (This seems to be no regression at least back to 1.13.)

**Comment by behrisch** [comment]
Maybe, but on the other hand a busStop has also a minimum capacity of 1. A parkingarea of capacity 0 seems quite pointless

**Comment by m-kro** [comment]
Some tests which relied on the previous default value have to be checked. E.g. sumo/extended/rerouter/parking/reroute_on_junction shows strange behaviour (vehicle does not park although the parkingArea has capacity)...

**Comment by namdre** [comment]
As our own need to change test inputs showed, this has the potential of breaking other peoples simulations. I recall relying on default capacity 0 to trigger parkingAreaRerouting from a defined starting point in some project.
