### ISSUE TITLE
Wrong lane used in lane area detector end position checks

### ISSUE THREAD

**Issue by Domsall** [eclipse-sumo/sumo#15275]
During debugging, I ran into the following assert:

https://github.com/eclipse-sumo/sumo/blob/6f9ff4ddaa42305c87f46edd44a88626180a9a71/src/microsim/output/MSE2Collector.cpp#L282

For now, I just deleted "- POSITION_EPS". The test case to reproduce the error:

[Delay_based_assert.zip](https://github.com/user-attachments/files/16361322/Delay_based_assert.zip)

**Comment by m-kro** [comment]
I think the detector end position is not detected correctly because the snap function still takes the first lane's length:
https://github.com/eclipse-sumo/sumo/blob/6f9ff4ddaa42305c87f46edd44a88626180a9a71/src/microsim/output/MSE2Collector.cpp#L264-L266

**Comment by m-kro** [comment]
Thanks as always for looking carefully at the code ;-)
