### ISSUE TITLE
connections

### ISSUE THREAD

**Issue by zlh212** [eclipse-sumo/sumo#15274]
![image](https://github.com/user-attachments/assets/0cf1e3be-48b5-4332-ac32-bb06b01eedb4)
Whether there is a problem with such path connections, randomly generated vehicles seem to prefer to walk on both sides of the road

**Comment by zlh212** [comment]
![8ad98187ca8fc6e9dccc817fb20df91](https://github.com/user-attachments/assets/703bb677-8abd-4a69-9e42-75867fc9a28c)
![a401b319f179d813b83b2d70ec7c7c6](https://github.com/user-attachments/assets/4c2cc53d-f177-48f0-b56b-dc6464f3386f)
![9f488c973783ee0f156399d7ff74310](https://github.com/user-attachments/assets/79a28ac7-96b6-4230-9014-397040738497)
As you can see in the first two images, the source lane on the left can connect the two target lanes on the right. However, in the third picture, the second source lane on the left conflict with the right lane. Why is that? and is there a problem if I force them to connect?

**Comment by namdre** [comment]
Generally, you should avoid have two lanes of the same incoming edge target the same lane on the outgoing edge. This creates traffic flow conflict which rarely occur on a "real" intersections. It will also impede traffic flow in the simulation just as it would in the real world.  It gets even worse if you have two connections with the same source and target edge cross each other.
