### ISSUE TITLE
Error: No option with the name 'pedestrian.jupedsim.model' exists.

### ISSUE THREAD

**Issue by henrigrossmann** [eclipse-sumo/sumo#15272]
I encountered an issue with the latest version of SUMO (commit 3b591bd) where an error regarding pedestrian.jupedsim.model is thrown even when running a simulation that does not include any pedestrians.

Error: No option with the name 'pedestrian.jupedsim.model' exists.

**Comment by behrisch** [comment]
All checks are green on our side. Can you double check your version (and/or do a clean build) and please share your precise call? We had a problem like this but it has been fixed in https://github.com/eclipse-sumo/sumo/commit/a754c2ec37f893ec4b2bd284be6d7b08c0729466

**Comment by henrigrossmann** [comment]
Sorry for not getting back to that. I couldn't reproduce the error; it seems to work fine now since the fix, and I just had an old version installed. Sorry for the inconvenience caused.
