### ISSUE TITLE
Can't get the excel file of output.

### ISSUE THREAD

**Issue by LoneCrise** [eclipse-sumo/sumo#15278]
Hello guys,
I got the problem in SUMO, that is when my simulation is done so there is an output file which is in the excel format. That output file is not generating when my simulation is completed. Please try to solve my issue.

One last thing is how can I open "sumo_run.py". I don't know how I can open this.

**SUMO-version: 1.20.0**

**operating system: Windows 11 (64-bit) with latest update **

**Comment by m-kro** [comment]
"Vanilla" SUMO creates XML output in first place. You seem to use some third-party extension / Python scripts (like `sumo_run.py`) together with SUMO we are not aware of. The file you named is probably a Python script which can be read in a text editor and executed with [python](https://www.python.org/).

**Comment by LoneCrise** [comment]
> "Vanilla" SUMO creates XML output in first place. You seem to use some third-party extension / Python scripts (like `sumo_run.py`) together with SUMO we are not aware of. The file you named is probably a Python script which can be read in a text editor and executed with [python](https://www.python.org/).
> 
> If you need more help, tell us about the third-party extensions you use together with sumo.

Actually i have seen "sumo_run.py" in youtube . Actually I am not using any third part extension. I have seen the video.  

Part 1 video link   https://www.youtube.com/watch?v=zQH1n0Fvxes
Part 2 video link   https://www.youtube.com/watch?v=DQq2mUbN27Q

In part2 video he show the output file where the vehicle details are there.
I have seen the video only for tutorial.

Can you guide how I will get the output file of my simulation (when the simulation is done ). Right now I am not using any third party app or extension.  I am not getting the output files.

**Comment by m-kro** [comment]
Well you use the script from **[https://github.com/ethanpng2021/sumo-example](https://github.com/ethanpng2021/sumo-example)** which is in fact some third-party code. This script collects some values during the simulation using TraCI and afterwards uses the pandas package to write it to a file. If you can see that the simulation runs until the end, you'll have to check possible directories for a file called "output.xlsx". Normally it should be in the directory you call the script from.
