### ISSUE TITLE
Asking about SUMO for my project.

### ISSUE THREAD

**Issue by LoneCrise** [eclipse-sumo/sumo#15285]
Hey guys,  

Right now I am doing the internship. So i get the task that , I have to make a model of "Smart Traffic Light Control For Urban Traffic".

So if I make a normal simulation model of SUMO will it be consider as a "Smart Traffic Light Control For Urban Traffic".
And my mentor told me that  AIML concept should be used.

Guys ,
Firstly tell me will this SUMO simulation can I show or call as "Smart Traffic Light Control For Urban Traffic".

If yes, so how i can use the concept of AIML.
If yes, so SUMO use any concept related to the AIML , if its directly or indirectly  , just help  to solve my queries.

**Comment by m-kro** [comment]
Can you explain what the abbreviation AIML means? "Artifical intelligence / machine learning"?

**Comment by LoneCrise** [comment]
> Can you explain what the abbreviation AIML means? "Artifical intelligence / machine learning"?

yes sorry to mention the full form,

**Comment by m-kro** [comment]
See ticket #15113
