### ISSUE TITLE
Add person ride to parkingArea with TraCI

### ISSUE THREAD

**Issue by sean-reed** [eclipse-sumo/sumo#15281]
When defining a person in a route file, you can set them to ride a vehicle to a parking area by setting the lines attribute to the vehicle ID and parkingArea attribute to the parking area ID, for example:

```
<person id="p1" depart="triggered">
        <ride parkingArea="pa_0" lines="vehicle_1"/>
</person>
```
Is there a way to do the same from the Traci Python library? I played around with traci.person.appendDrivingStage but couldn't find a way to do it. Thanks!

**Comment by m-kro** [comment]
I can confirm that currently `traci.person.appendDrivingStage` works with stops for public transport only (not parking areas or charging stations...)
