### ISSUE TITLE
Sudden angle change in freshly moved vehicles

### ISSUE THREAD

**Issue by LuminousLamp** [eclipse-sumo/sumo#15283]
It is observed that vehicles moved by Traci.vehicle.moveToXY() sometimes experience a relatively large angle change (10~15 degrees) at the step right after the movement.

To be more specific, the problem happens like this: I call vehicle.moveToXY() to a vehicle, explicitly providing the coordinates, the edge, the laneIndex **and the heading angle**; SUMO faithfully move the vehicle, as I instruct, to the position and angle. Now the vehicle's angle is slightly diverged to the angle of its lane, but without making the vehicle lie outside the lane. At the next time step (step length 0.1s), **SUMO simulates the vehicle such that it is forced to completely align with the angle of the lane. This makes a 10~20 degrees change of the vehicle's heading, in 0.1s**, which is very unrealistic and not smooth. What I expect is that the vehicle can slowly change its angle when moving forward to align itself with the lane.

I attach an example. Run bug2.py and you will find the problem happens on the only vehicle in that scenario.

My expectation might be too high to the perfectness in simulation, but it is still desired if there is a solution to avoid this small bug and make the simulation more smooth. Thank you!
[bug2.zip](https://github.com/user-attachments/files/16385566/bug2.zip)

**SUMO-version:** v1_20_0+1235-b29e719b814

**operating system:** Ubuntu 20.04

**Comment by m-kro** [comment]
Even when following a lane, the vehicle will change its angle abruptly depending on the lane geometry. So clearly this is something which was seen out of scope for a mere traffic simulation...
