### ISSUE TITLE
Difficulty in Creating Perfect Circular Roundabout in Netedit

### ISSUE THREAD

**Issue by TerzaSlayer2000** [eclipse-sumo/sumo#15289]
Hello,

I am currently working on a traffic simulation project using SUMO, and I have encountered significant difficulties in creating a perfect circular roundabout using Netedit. My project requires an exact circular shape for the roundabout with a specified radius, similar to what is seen on Google Maps. However, the roundabout created from imported OSM data in SUMO is very complicated and does not meet the required precision.

Despite following various methods and suggestions, including the "Convert to Roundabout" feature and manually adjusting nodes and edges, I am unable to achieve the perfect circular shape needed for my simulations. This issue significantly impacts the accuracy of my traffic models, especially when cross-referencing with Google Maps for exact measurements.

**Steps Taken:**
1. Imported OSM data and converted intersections to roundabouts using Netedit.
2. Manually adjusted junctions and edges to attempt a perfect circular shape.
3. Followed the guidelines and examples from SUMO documentation and GitHub discussions.

Despite these efforts, the roundabout remains irregular and does not align with the specified radius.

**Requirements:**
- A method to create a perfect circular roundabout in Netedit with a user-defined radius.
- Accurate representation of the roundabout to match real-world measurements as seen on Google Maps.

I would appreciate any guidance or solutions to achieve the required precision for the roundabout in SUMO. 

Thank you.

I have attached the below attachments for reference :

-Screenshots of the current roundabout in SUMO
-Screenshots of the Google Maps reference

![IMG_20240727_204442](https://github.com/user-attachments/assets/20e00087-51ed-4e5c-b08a-76011798abb9)
![IMG_20240727_204514](https://github.com/user-attachments/assets/bf75b9b1-41be-4e0a-9664-2ae4a6e92c8e)

Best regards,
Sain

**Comment by m-kro** [comment]
We have some helper script to create an approximated circle polygon at `tools/shapes/circlePolygon.py` which you can use as model for your roundabout and place it just below. Keep in mind that the current shape reflects the OSM data which is not a perfect circle.

**Comment by namdre** [comment]
You can get a "perfect" circle in netedit:

1. select all junctions that belong to the roundabout (in selection mode)
2. press F7 to join them into a single junction
3. use inspect mode to set the radius attribute of that junction to the desired radius of the roundabout
4. right-click on the junction and click item "convert to roundabout"

**Comment by TerzaSlayer2000** [comment]
Thank you so much guys @namdre @m-kro
