### ISSUE TITLE
Repeated route and flow between junctions in same route file causes disconnected route error

### ISSUE THREAD

**Issue by sean-reed** [eclipse-sumo/sumo#15292]
If a route file contains a flow between junctions and a repeated route, then an error occurs on loading the simulation that the route between the junctions is disconnected when repeating. It appears the repeat in the route is somehow "leaking" through to the flow.

I have attached a minimal example demonstrating this that has a flow of cars between junctions J0 and J3 and a bus that repeats a route around the network. No error occurs if the repeating bus route is removed, or if the junction flow is modified to a flow between edges instead of junctions, or if separate route files are used for the flow and repeating route.

[RepeatRouteTest.zip](https://github.com/user-attachments/files/16409891/RepeatRouteTest.zip)

SUMO 1.20.0
Windows 11

**Comment by sean-reed** [comment]
May be related to #14992

**Comment by namdre** [comment]
> May be related to #14992

exactly. Upgrading to the latest development version fixes this.
