### ISSUE TITLE
met an error when i used function getCompleteRedYellowGreenDefinition in matlab

### ISSUE THREAD

**Issue by sjh30** [eclipse-sumo/sumo#15298]
i copied the code  in the traci4matlab example traci_test2.m
  And i met the error when i used the fuction  traci.trafficlights.setCompleteRedYellowGreenDefinition('0',tlsRYGDefinition{1});
  Here is the example code:
```
tlsRYGDefinition = traci.trafficlights.getCompleteRedYellowGreenDefinition('0')
traci.trafficlights.setCompleteRedYellowGreenDefinition('0',tlsRYGDefinition{1});
```
  I used the code  in the same way,but it went wrong.
  And here is the wrong message:
错误使用 traci.sendExact (第 46 行)
74  194  255 Error set program 4.5 parameter (next) must be a compound (list of ints).

出错 traci.trafficlights.setCompleteRedYellowGreenDefinition (第 58 行)
traci.sendExact();

出错 TACIR (第 139 行)
traci.trafficlights.setCompleteRedYellowGreenDefinition(tlsID,myRYGDefinition);

 Can this function be used in the old sumo version? Or this function can not be used all the time? 
 If i want to use it in the matlab .which version should i download.Because it seems like this function can not be used in my version :1.19

**SUMO-version:1.19

**operating system:windows

**Comment by m-kro** [comment]
Traci4Matlab is a third-party contribution which hasn't been updated for some years. This means changes to the TraCI commands have not been included in Traci4Matlab and probably won't anymore. We advise to [use the python client from inside Matlab](https://sumo.dlr.de/docs/TraCI.html#interfaces_by_programming_language) instead. Otherwise you would need to downgrade to an older SUMO version.

**Comment by sjh30** [comment]
Thanks，if i want to downgrade my sumo version,which version should i download?

**Comment by m-kro** [comment]
Version 1.1 should work, but after that relevant changes (#4789) were introduced. So I think this should be the last working version in this context.

**Comment by sjh30** [comment]
Thank you so much,And I wanna know that my matlab version is 2024 ,so version 1.1 and its traci can be used in the matlab2024. Thanks so much!!
