### ISSUE TITLE
how to downgrade the traci version

### ISSUE THREAD

**Issue by sjh30** [eclipse-sumo/sumo#15300]
I downgrade my sumo version because i want to use the function in the traci4matlab which can not be used in the latest version. But the traci version is still the same 20. So how can i downgrade my traci version ?

**SUMO-version:1.10

**operating system:windows

**Comment by m-kro** [comment]
That depends on how you installed the old version and TraCI. The first step is to set the environment variable **SUMO_HOME** to the main directory of the wanted SUMO installation. If you have installed TraCI for python using pip you need to uninstall that one.

**Comment by sjh30** [comment]
I  installed sumo1.19 and the Traci version was 20.And at the same time i set the environment variable SUMOHOME to the main directory.
And now i install sumo1.10 by sumo1.10.msi  which set the environment  variable automatically (if my mind serves me right)So,should I delete the old environment variable  and set it again? 
By the way,i also downgrade traci version from 1.20 to1.19.But I dont know Traci 20 and Traci 1.20 is actually the same version ,can u tell me?
The last question is traci version 19 and sumo version 1.10 can really work which i mean in these version the function set completeredyellowgreendefintion in the traci4matlab can be used successfully.thank u so much

**Comment by sjh30** [comment]
P.S. i downgrade traci version to 1.19 for the python.But if   it doesn’t work,and I have to uninstall traci for python Please tell me!

**Comment by m-kro** [comment]
You can check the environment variable value either by typing `echo %SUMO_HOME%` in cmd or using the graphical access in Windows system control (you can change it there as well). If you have installed traci from pip, you have to uninstall it.

**Comment by sjh30** [comment]
Thanks a lot.Does Traci version 19 really work? I
mean traci4matlab is compatible with Traci 19 or not which means i need to install the older version?

**Comment by sjh30** [comment]
thank you so much.i really appreciate！
