### ISSUE TITLE
Overtaking in a circular network with one lane per edge

### ISSUE THREAD

**Issue by claudiacbh** [eclipse-sumo/sumo#15302]
Hello,

I would appreciate it if you could help me with the following concern.

I created a circular network with 8 stops and 5 buses. The network has only one lane per edge. The buses pick up and drop off passengers at the stops. The stops are the same length as the buses, meaning only one bus can be at a stop at a time.

As time progresses, buses that initially depart at regular intervals start to exhibit bus bunching behavior (some bunch up while others spread out significantly).

I graphed the behavior of the buses (spacing vs. time) and observed an overtaking of one bus. The Y-axis represents the position relative to the starting point, with Ymax being the length of the entire circuit, and the X-axis is the elapsed time.

-Can overtaking occur if there is only one lane per edge? 

-How can overtaking be prevented in SUMO's configuration, without implementing bus control mechanisms?

**SUMO-version:** 1.20

**operating system:** Windows 11

**Comment by m-kro** [comment]
We don't see the figure you described in your post. Overtaking may happen if the lane is wide enough for two buses and the [sublane model](https://sumo.dlr.de/docs/Simulation/SublaneModel.html) is activated.

**Comment by namdre** [comment]
- If the stop definitions of the buses are configured for "parking", then other buses may overtake (https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#stops_and_waypoints)
- if any of the buses has to stop for more than 300s in the same spot it may be "teleported" (https://sumo.dlr.de/docs/Simulation/Why_Vehicles_are_teleporting.html)
