### ISSUE TITLE
Duarouter unable to find route for intermodal trip

### ISSUE THREAD

**Issue by 1BlattPapier** [eclipse-sumo/sumo#15318]
I created demand for a multimodal simulation and stored in a trips.xml. I can run the simulation without errors. However, when I run duaIterate.py to reach an equilibrium, duaIterate does not seem to be able to handle and find routes for the multimodal trips.

**SUMO-version:**
1.20

**operating system:**
Rocky Linux 8.9

**Error message:**
```
Warning: No connection between edge '1226623062#0' and edge '78059338' found.
Error: No route for trip in person '8340001'.
Quitting (on error).
```

**Trip in question:**
```
<person id="8340001" depart="25500">
	<personTrip from="1226623062#0" to="78059338" modes="public"/>
</person>
```

**To reproduce:**
1. Unzip folder ([files_to_reproduce_error.zip](https://github.com/user-attachments/files/16510219/files_to_reproduce_error.zip)).
2. Run `python3 sumo/tools/assign/duaIterate.py -n wedding.net.xml -t 'trips.xml,gtfs_pt_vehicles.add.xml' -+ 'gtfs_pt_stops.add.xml,vtypes.xml' --skip-first-routing`

**Comment by m-kro** [comment]
You'll have to work on your network to connect places better with each other. At various intersections crossings for pedestrians are missing. So it is not a surprise some relations are unfeasible. If you want to try first to run duaIterate.py and ignore errors call it with **duarouter--ignore-errors true** (see [doc](https://sumo.dlr.de/docs/Demand/Dynamic_User_Assignment.html#iterative_assignment_dynamic_user_equilibrium) / [duarouter arguments](https://sumo.dlr.de/docs/duarouter.html#report)).

**Comment by 1BlattPapier** [comment]
I know that the network is not optimal and has, e.g., missing crossings. Sadly it is not feasible for me to resolve all those issues as I want to scale the size of the network later on.

The problem is that the relation does seem to be feasible when running it like that with SUMO as a route does seem to exist. Only when using duaIterate.py I get that error.

**Comment by 1BlattPapier** [comment]
Hey I want to comment again as I am not sure whether I was clear enough:

Normal routing and running the simulation with SUMO works fine without errors and there are routes found for the intermodal trips. Only when using duaIterate.py it does not find routes.

**Comment by m-kro** [comment]
The public transport files are not added to the duarouter call for unknown reasons. As the person needs to take public transport, the trip fails.

**Comment by m-kro** [comment]
Please try
```
python3 sumo/tools/assign/duaIterate.py -n wedding.net.xml -t trips.xml -+ vtypes.xml,gtfs_pt_stops.add.xml,gtfs_pt_vehicles.add.xml --skip-first-routing duarouter--additional-files vtypes.xml,gtfs_pt_stops.add.xml,gtfs_pt_vehicles.add.xml
```
See [docs](https://sumo.dlr.de/docs/Tools/Assign.html#loading_vehicle_types_from_an_additional_file). You can always load a route file as an additional file as well. This has some implications regarding the loading order and time but in this context it seems right as you don't want to change the public transport schedule.
