### ISSUE TITLE
Jtrrouter stops issues

### ISSUE THREAD

**Issue by Delnia-G** [eclipse-sumo/sumo#15316]
I am working with SUMO to recreate daily traffic behavior, where I am using jtrrouter for decision-making based on the probabilities it offers. When trying to create the stops, I attempted two things:

Automating in a Python script that would iterate through the routes created by the router to add the stops per route. This created a separate .rou.xml file from the original with the routes, and I tried to change the updated .rou file with the stops in the .sumocfg script. However, the program started to load and then closed. I also tried opening it from the shell to see if there was any error, but it didn't show anything.
I also tried running the jtrrouter simulation and activating the "load demand on netedit" option to use the stops option from Netedit, but when I wanted to position one, I got the error: "Stop must be placed over an embedded route's edge."
Currently, I am not sure how to add these stops to the routes or the net.

This is my code (an example):
Without stops
```<vehicle id="EntradasAlfalfares7.0" depart="1.00">
<route edges="ALFALFARES_IN ZORRILLA1 ZORRILLA2 INFANTE3 INFANTE2 INFANTE1 LASCASAS3 LASCASAS4 VICUNA_OUT"/>
</vehicle>
<vehicle id="EntradasBenavente7.0" depart="1.00">
    <route edges="BENAVEN_IN LASCASAS4 VICUNA_OUT"/>
</vehicle>
<vehicle id="EntradasBenavente7.1" depart="2.00">
    <route edges="BENAVEN_IN BENAVENTE BENAVENTE1 VICUNA1 CANTOURNET4 CANTOURNET_OUT"/>
</vehicle>
```

With Stops

```<vehicle id="EntradasAlfalfares7.0" depart="1.00">
    <route edges="ALFALFARES_IN ZORRILLA1 ZORRILLA2 INFANTE3 INFANTE2 INFANTE1 LASCASAS3 LASCASAS4 VICUNA_OUT"/>
    <stop edge="LASCASAS3" lane="0" startPos="50" endPos="50" duration="15"/>
    <stop edge="ZORRILLA2" lane="0" startPos="50" endPos="50" duration="15"/>
    <stop edge="ZORRILLA2" lane="1" startPos="50" endPos="50" duration="15"/>
</vehicle>
<vehicle id="EntradasBenavente7.0" depart="1.00">
    <route edges="BENAVEN_IN LASCASAS4 VICUNA_OUT"/>
</vehicle>
<vehicle id="EntradasBenavente7.1" depart="2.00">
    <route edges="BENAVEN_IN BENAVENTE BENAVENTE1 VICUNA1 CANTOURNET4 CANTOURNET_OUT"/>
    <stop edge="BENAVENTE1" lane="0" startPos="50" endPos="50" duration="15"/>
    <stop edge="BENAVENTE1" lane="1" startPos="50" endPos="50" duration="15"/>
</vehicle>
```

**SUMO-version: 1.20.0**

**operating system: Windows**

**Comment by m-kro** [comment]
Please provide a preferably small sample scenario for the case SUMO exits without any message.

**Comment by Delnia-G** [comment]
When I run the command `sumo-gui -c Myfile.sumocfg,` it keeps me waiting for a while and then appears to finish the process without displaying any messages. 
![image](https://github.com/user-attachments/assets/a221bff3-8ffa-4051-b659-7a5a811424ad)

**Comment by m-kro** [comment]
In any case this should read `sumo-gui -c SituAct.cfg` (see [how to use command line with SUMO applications](https://sumo.dlr.de/docs/Basics/Using_the_Command_Line_Applications.html)).

**Comment by m-kro** [comment]
Closing due to lack of feedback. If you still have the same issue, please post here again.
