### ISSUE TITLE
Problem with stopping a taxi manual at off-road 

### ISSUE THREAD

**Issue by indieflunk** [eclipse-sumo/sumo#15310]
Hello, I want to stop a taxi on the off-road like the taxi with idle Behavior "stop".  But I only find the function “traci.vehicle.setStop()” to stop the car in the lane, which other vehicles cannot past the lane. would it be possible to stop a vehicle at off-road like in idle Behavior "stop"? Thanks!

**Comment by m-kro** [comment]
You can use `traci.vehicle.setStopParameter(vehID, stopIndex, "parking", "true")` (see [ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setStopParameter)) to configure your stop in this respect.

**Comment by namdre** [comment]
also, `vehicle.setStop` accepts flags with which to configure parking directly

**Comment by indieflunk** [comment]
Thank you for your suggest! What number should I give the flag to stop the car on the off-road? @namdre

**Comment by namdre** [comment]
`traci.constants.STOP_PARKING`

**Comment by indieflunk** [comment]
I cannot find traci.constant.STOP_PARKING (traci version 1.20.0）but it works with flags=1, danke für deine Hilfe!

**Comment by namdre** [comment]
for the record: https://github.com/eclipse-sumo/sumo/blob/81a650f32a8a8e83e1504c296e80c96dfda8bf1f/tools/traci/constants.py#L567
