### ISSUE TITLE
Cannot set looped trip with intermediate stop on a different edge

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#15319]
Trip example:
```
    <trip depart="102996.00" from="332893804" id="100109482_100067859_284_0" to="332893804" type="large_passenger_dist" via="23423609#1" departPos="stop">
        <stop parkingArea="PA332893804" until="114756.00" />
        <stop parkingArea="PA23423609#1_restricted" until="147096.00" />
        <stop parkingArea="PA332893804" until="157656.00" />
    </trip>
```
The stop is not loaded because ... 
`Error: parkingArea 'PA23423609#1_restricted' for vehicle '100109482_100067859_284_0' on lane '23423609#1_0' is not downstream the current route.`

Probably there is some case missing in the stop insertion...

**Comment by namdre** [comment]
most likely fixed in the context of #15353, #15503
