### ISSUE TITLE
Incorrect Overtaking Behavior of Motorcycles in Left-Hand Traffic Simulation

### ISSUE THREAD

**Issue by TerzaSlayer2000** [eclipse-sumo/sumo#15321]
Hello, I am currently working on a traffic simulation project using SUMO where the traffic system is configured for left-hand driving. I have encountered an issue where motorcycles are overtaking other vehicles (such as cars and mini trucks) from the left side, which is incorrect for left-hand traffic. In a left-hand traffic system, overtaking should occur from the right side.

Configuration Details:

1- Network Setup:
    The network is set up for left-hand traffic using the osmWebWizard interface in browser.

2-Vehicle Definitions:
    Here are the vehicle type configurations for cars, motorcycles, and mini trucks:

    <vType id="car" vClass="passenger" accel="2.6" decel="4.5" sigma="0.5" length="5.0" minGap="2.5" maxSpeed="70.0"
       lcStrategic="0.5" lcCooperative="0.5" lcSpeedGain="0.5" lcSublane="1.0" lcKeepRight="0.5" lcPushy="0.5"
       lcAssertive="0.5" lcImpatience="0.5" lcOpposite="0.5" color="1,0,0"/>

    <vType id="motorcycle" vClass="motorcycle" accel="3.0" decel="4.5" sigma="0.5" length="2.0" minGap="1.5" maxSpeed="80.0"
       lcStrategic="1.0" lcCooperative="1.0" lcSpeedGain="1.0" lcSublane="1.0" lcKeepRight="1.0" lcPushy="1.0"
       lcAssertive="1.0" lcImpatience="1.0" lcOpposite="1.0" color="0,0,1"/>

    <vType id="mini_truck" vClass="truck" accel="1.2" decel="3.0" sigma="0.5" length="7.0" minGap="3.0" maxSpeed="60.0"
       lcStrategic="0.5" lcCooperative="0.5" lcSpeedGain="0.3" lcSublane="1.0" lcKeepRight="0.5" lcPushy="0.5"
       lcAssertive="0.5" lcImpatience="0.5" lcOpposite="0.5" color="0.5,0.5,0.5"/>

Observed Behavior:
During the simulation, motorcycles are seen overtaking from the left side of other vehicles, which contradicts the left-hand traffic rules where overtaking should be from the right.

Expected Behavior:
Motorcycles should overtake other vehicles from the right side in a left-hand traffic system.

Screenshot:
Attached is a screenshot from the SUMO-GUI showing the overtaking behavior of motorcycles.

![image](https://github.com/user-attachments/assets/e5cf5746-eac8-428a-ad28-d9ed232e73cc)

I would appreciate any guidance or solutions to correct this behavior, ensuring motorcycles overtake from the correct side in left-hand traffic. Thank you for your assistance.

**SUMO-version:** - 1.18.0

**operating system:** - Windows 11

Best regards,
Sain

**Comment by namdre** [comment]
could it be that cars where overtaking motorcycles instead?
