### ISSUE TITLE
Problem with taxi driving randomly with idle "randomCircling"

### ISSUE THREAD

**Issue by indieflunk** [eclipse-sumo/sumo#15324]
Add your issue description here.
I want to run a taxi simulation under the idle scenario  "randomCircling". In this Simulation, I would like to let the taxi leave the charging station and drive randomly on the maps. After the car was fully charged, I used _traci.vehicle.changeTarget(Vehid, random_edge)_ and _traci.vehicle.resume(Vehid)_. The "random_edge" will be chosen from the maps. In the GUI, I can see that the taxi leaves the Charging Station and drives randomly on the maps. But occasionally, the taxi just stops randomly at the junction, which results in traffic jams (the stop at junctions is after arriving at the _"random edge_"). But the taxi can leave the Junction, if it gets a request (_traci.vehicle.dispatchTaxi_) from the costumer. So I have two questions about it:

1. Is there any better function that lets the car from a place to run randomly on the map, with the idle scenario "randomCircling"? 
2. Is there a solution to avoid the stop of the taxi with idle "randomCircling"? (I would rather not use teleport)

![Screenshot 2024-08-06 135716](https://github.com/user-attachments/assets/1ece7f47-78c1-4fd6-821a-969e46d6fafe)
![Screenshot 2024-08-06 173706](https://github.com/user-attachments/assets/91add40c-7f7f-439e-86f0-3e621175074b)
![Screenshot 2024-08-06 231923](https://github.com/user-attachments/assets/ddc47315-291d-4809-a078-40fd71bcd9e0)

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
windows 11

**Comment by m-kro** [comment]
Can you please clarify:

- Which one is the taxi in the screenshots?
- Is it blocked by other vehicles?

**Comment by indieflunk** [comment]
![Screenshot 2024-08-06 135716](https://github.com/user-attachments/assets/51007f75-9b75-40ac-8dc7-ac171274e349)
![Screenshot 2024-08-06 173706](https://github.com/user-attachments/assets/529f8433-bd9a-4e03-b494-33b4ad52e20e)
![Screenshot 2024-08-06 231923](https://github.com/user-attachments/assets/72b4a849-e7f4-42bb-8822-65e2bf692c44)
@m-kro thank you for your kind reply! I have marked the taxi in the screenshots with a blue circle.  The taxi is the first vehicle at this junction and blocked other cars which want to pass this junction.

**Comment by indieflunk** [comment]
The problem occurred after arriving at the target edge and after transporting a customer to the target edge. However, if the vehicle has a specific objective, such as transporting a customer or accessing a charging station, this will not occur.

**Comment by m-kro** [comment]
Could you provide a **small** example scenario?

**Comment by indieflunk** [comment]
I use the following code to leave the Vehicle leave the Charging Station:

_def Vehicle_leave_CS(Vehid, clean_all_edges, time):   
    random_edge = clean_all_edges[random.randint(0, 100)]
    traci.vehicle.changeTarget(Vehid, random_edge)
    traci.vehicle.resume(Vehid)_

_the clean_all_edges_ is a list of all edges in the maps.  And I have checked the time, the random stopping at junctions is later the arriving at the target edge.

**Comment by m-kro** [comment]
Can you please prepare a scenario & script which can be run out of the box and show the problem? Preferably the network should be small and contain only few vehicles so that the simulation time remains short.

**Comment by indieflunk** [comment]
It is difficult to provide a small example because currently work with a big map (14142 edges) and many vehicles (200 taxis). I try to provide an example later. Would you be able to give me some tips on how to get a stopped taxi to drive around randomly, without stopping until the next thing happens with idle "randomcircling"?  Thank you very much!

**Comment by m-kro** [comment]
Well actually "randomCircling" should do this out of the box. The only thing I am not sure is how it interferes with your individual route-related commands such as charging and changing the target in TraCI.

**Comment by indieflunk** [comment]
I have found the correct Description of my problem on SUMO website : Grid lock. I think I will try to solve the grid lock problem with the advice from the website. Thank for your explain!
