### ISSUE TITLE
A question about Mesoscopic model

### ISSUE THREAD

**Issue by pjj-OSM** [eclipse-sumo/sumo#15326]
I using mesoscopic model in my simulation, but it raise a error information **Sublane dynamics are not supported by mesoscopic** when running sumo-gui. I don't use sublane model for any vehicle type in rou.xml, i need some guidance.
<img width="366" alt="1" src="https://github.com/user-attachments/assets/90a9258a-0648-4722-872c-6d59c1e6360a">

This is my document
[Document.zip](https://github.com/user-attachments/files/16538124/Document.zip)

**Comment by m-kro** [comment]
Using the option **-lanechange.duration** triggers this message as well. So please remove this option.
