### ISSUE TITLE
Vehicles Not Using Opposite Lane for Overtaking in Left-Hand Traffic Scenario

### ISSUE THREAD

**Issue by TerzaSlayer2000** [eclipse-sumo/sumo#15329]
Hello SUMO community,

I am currently working on a traffic simulation project involving a left-hand traffic system. In my scenario, I need vehicles to overtake by using the opposite lane, particularly when the regular lanes are congested or blocked. I've tried configuring the lcOpposite parameter in the vehicle types (vType) as well as setting --lanechange.overtake-right to true in the configuration file, but the vehicles still do not use the opposite lane for overtaking.

Here are the key configurations I've used:

Vehicle Type Configuration:
    <vType id="car" vClass="passenger" accel="2.6" decel="4.5" sigma="0.5" length="5.0" minGap="2.5" maxSpeed="70.0"
       lcStrategic="0.5" lcCooperative="0.5" lcSpeedGain="0.5" lcSublane="1.0" lcPushy="0.5"
       lcAssertive="0.5" lcImpatience="0.5" lcOpposite="0.5" color="1,0,0"/>

    <vType id="mini_truck" vClass="truck" accel="1.2" decel="3.0" sigma="0.5" length="7.0" minGap="3.0" maxSpeed="60.0"
       lcStrategic="0.5" lcCooperative="0.5" lcSpeedGain="0.3" lcSublane="1.0" lcPushy="0.5"
       lcAssertive="0.5" lcImpatience="0.5" lcOpposite="0.5" color="0.5,0.5,0.5"/>
    
    <vType id="motorcycle" vClass="motorcycle" accel="3.0" decel="4.5" sigma="0.5" length="2.0" minGap="1.5" maxSpeed="80.0"
       lcStrategic="1.0" lcCooperative="1.0" lcSpeedGain="1.0" lcSublane="1.0" lcPushy="1.0"
       lcAssertive="1.0" lcImpatience="1.0" lcOpposite="1.0" color="0,0,1"/>

Configuration File Processing Section:
    <processing>
        <lanechange.overtake-right value="true"/>
    </processing>

Problem Encountered:
Despite the above configurations, the vehicles do not seem to be overtaking using the opposite lane as expected. They continue to follow the regular lanes without attempting to use the opposite lane, even when there is heavy traffic.

Simulation Scenario:
1- Left-hand traffic system.
2- Mixed traffic including cars, motorcycles, and trucks.
3- Need vehicles, particularly smaller ones like motorcycles, to overtake using the opposite lane when safe.

Request:
Could you please provide guidance or suggest any additional parameters or settings that I may have overlooked? I have also attached a screenshot of the simulation where the issue is evident. Your assistance in resolving this would be greatly appreciated.

Thank you!

Screenshot :
![image](https://github.com/user-attachments/assets/d197ada6-58d3-4c65-9540-dfbebda72ca7)

**SUMO-version:** 1.18.0

**operating system:**  Windows 11

**Comment by m-kro** [comment]
Please check if you have [prepared your network](https://sumo.dlr.de/docs/Simulation/OppositeDirectionDriving.html#building_a_network_for_opposite-direction-driving) for opposite-direction driving and whether vehicles should overtake given the [model conditions](https://sumo.dlr.de/docs/Simulation/OppositeDirectionDriving.html#model_description).

**Comment by TerzaSlayer2000** [comment]
Thank you for the guidance and the link you provided. However, I’m still facing some difficulties with implementing opposite-direction driving in my network.

Heuristic Method: The documentation mentions enabling opposite-direction driving heuristically, but the instructions aren’t entirely clear to me. Could you elaborate on how this method works and how I can ensure it's correctly applied to my network?

Explicit Method: While I understand that I can explicitly allow opposite-direction driving through configuration, I’m uncertain about the exact steps and syntax required. Could you provide a more detailed example?

Netedit (Visual) Method: Since I'm more comfortable with Netedit, I attempted to change the opposite parameter directly. However, I encountered an issue: the "opposite" option in the edge parameters is marked with a red cross, and I’m unable to change it to a tick mark (I’ve attached a screenshot for reference). Could you advise on why this might be happening and how to resolve it?

![Screenshot (9)](https://github.com/user-attachments/assets/b50cc8d3-c9c8-44b8-8e61-f513e4fd436e)

**Comment by TerzaSlayer2000** [comment]
Thank you for the guidance and the link you provided. However, I’m still facing some difficulties with implementing opposite-direction driving in my network.

Heuristic Method: The documentation mentions enabling opposite-direction driving heuristically, but the instructions aren’t entirely clear to me. Could you elaborate on how this method works and how I can ensure it's correctly applied to my network?

Explicit Method: While I understand that I can explicitly allow opposite-direction driving through configuration, I’m uncertain about the exact steps and syntax required. Could you provide a more detailed example?

Netedit (Visual) Method: Since I'm more comfortable with Netedit, I attempted to change the opposite parameter directly. However, I encountered an issue: the "opposite" option in the edge parameters is marked with a red cross, and I’m unable to change it to a tick mark (I’ve attached a screenshot for reference). Could you advise on why this might be happening and how to resolve it?

![Screenshot (16)](https://github.com/user-attachments/assets/15bb7934-2511-4de8-86d6-5ec8b12d103c)

**Comment by TerzaSlayer2000** [comment]
Actually i want the motorcycles and emergency vehicles only to overtake using the opposite lane if there is any space available.

**Comment by m-kro** [comment]
Please read carefully what the cross and tick mark are about. They tell you whether the attribute is dynamic, thus can change over the course of the simulation. You have to edit the attribute **opposite** in the main netedit window in the inspect frame (you have one in your screenshot on the left side).

**Comment by TerzaSlayer2000** [comment]
if i use the edit parameter, do i need to just add opposite=true?
Actually i have tried before but it was not working

**Comment by m-kro** [comment]
You have to set opposite to the ID of the opposite lane.

**Comment by TerzaSlayer2000** [comment]
Thanks for correction. I have followed your instructions by setting the opposite lane ID of both the opposite lane, but still my motorcycles are not overtaking using the opposite lane. Below is my network file config for opposite lane : 

<edge id="-835504484#0" from="2805324080" to="9695041407" name="Laitumkhrah Main Road" priority="10" type="highway.tertiary">
        <lane id="-835504484#0_0" index="0" allow="pedestrian" speed="13.89" length="374.02" width="4.28" >
            <param key="origId" value="835504484"/>
        </lane>
        <lane id="-835504484#0_1" index="1" disallow="pedestrian tram rail_urban rail rail_electric rail_fast ship" speed="13.89" length="374.02" width="4.28">
            <param key="origId" value="835504484"/>
        </lane>
        <param key="opposite" value="835504484#0_1"/>
    </edge>


<edge id="835504484#0" from="9695041407" to="2805324080" name="Laitumkhrah Main Road" priority="10" type="highway.tertiary">
        <lane id="835504484#0_0" index="0" allow="pedestrian" speed="13.89" length="378.13" width="4.28">
            <param key="origId" value="835504484"/>
        </lane>
        <lane id="835504484#0_1" index="1" disallow="pedestrian tram rail_urban rail rail_electric rail_fast ship" speed="13.89" length="378.13" width="4.28">
            <param key="origId" value="835504484"/>
        </lane>
        <param key="opposite" value="-835504484#0_1"/>
    </edge>

And below is the vehicles config where i have set lcOpposite for motorcycle=1.0:

 <vType id="car" vClass="passenger" accel="2.6" decel="4.5" sigma="0.5" length="5.0" minGap="2.5" maxSpeed="70.0"
       lcStrategic="0.5" lcCooperative="0.5" lcSpeedGain="0.5" lcSublane="1.0" lcPushy="0.5"
       lcAssertive="0.5" lcImpatience="0.5" lcOpposite="0.5" color="1,0,0"/>

    <vType id="mini_truck" vClass="truck" accel="1.2" decel="3.0" sigma="0.5" length="7.0" minGap="3.0" maxSpeed="60.0"
       lcStrategic="0.5" lcCooperative="0.5" lcSpeedGain="0.3" lcSublane="1.0" lcPushy="0.5"
       lcAssertive="0.5" lcImpatience="0.5" lcOpposite="0.5" color="0.5,0.5,0.5"/>
    
    <vType id="motorcycle" vClass="motorcycle" accel="3.0" decel="4.5" sigma="0.5" length="2.0" minGap="1.5" maxSpeed="80.0"
       lcStrategic="1.0" lcCooperative="1.0" lcSpeedGain="1.0" lcSublane="1.0" lcPushy="1.0"
       lcAssertive="1.0" lcImpatience="1.0" lcOpposite="1.0" color="0,0,1"/>
    
And below is the screenshot of the sumo gui:
![Screenshot (19)](https://github.com/user-attachments/assets/3f82cc02-2451-414e-8455-fd827ee93c67)

**Comment by TerzaSlayer2000** [comment]
<edge id="835504484#0" from="9695041407" to="2805324080" name="Laitumkhrah Main Road" priority="10" type="highway.tertiary" shape="0.00,386.07 11.44,391.27 22.65,395.46 30.89,398.34 40.36,401.57 49.68,405.12 67.74,410.28 89.63,417.34 110.06,426.62 122.14,432.91 131.90,439.33 139.37,445.52 187.23,485.87 192.73,490.51 242.25,532.77 260.41,546.89 270.29,553.26 280.78,557.84 287.37,559.38 310.00,558.78 323.83,558.06">
        <lane id="835504484#0_0" index="0" allow="pedestrian" speed="13.89" length="378.13" width="4.28" shape="-2.66,391.91 8.98,397.21 20.47,401.50 28.80,404.41 38.18,407.61 47.65,411.22 65.87,416.42 87.31,423.34 107.25,432.39 118.89,438.45 128.08,444.50 135.25,450.45 183.09,490.78 188.58,495.41 238.19,537.75 256.69,552.13 267.25,558.94 278.75,563.96 286.71,565.82 310.25,565.20 323.42,564.51">
            <param key="origId" value="835504484"/>
        </lane>
        <lane id="835504484#0_1" index="1" disallow="pedestrian tram rail_urban rail rail_electric rail_fast ship" speed="13.89" length="378.13" width="4.28" shape="-0.89,388.02 10.62,393.25 21.92,397.47 30.19,400.36 39.63,403.58 49.00,407.15 67.12,412.33 88.86,419.34 109.12,428.54 121.06,434.76 130.63,441.05 138.00,447.16 185.85,487.51 191.35,492.14 240.90,534.43 259.17,548.64 269.28,555.15 280.10,559.88 287.15,561.53 310.08,560.92 323.19,560.24">
            <param key="origId" value="835504484"/>
        </lane>
        <param key="opposite" value="-835504484#0_1"/>
    </edge>

<edge id="-835504484#0" from="2805324080" to="9695041407" name="Laitumkhrah Main Road" priority="10" type="highway.tertiary" shape="323.83,558.06 310.00,558.78 287.37,559.38 280.78,557.84 270.29,553.26 260.41,546.89 242.25,532.77 192.73,490.51 187.23,485.87 139.37,445.52 131.90,439.33 122.14,432.91 110.06,426.62 89.63,417.34 67.74,410.28 49.68,405.12 40.36,401.57 30.89,398.34 22.65,395.46 11.44,391.27 0.00,386.07">
        <lane id="-835504484#0_0" index="0" allow="pedestrian" speed="13.89" length="374.02" width="4.28" shape="322.75,551.69 309.75,552.36 288.03,552.94 282.81,551.72 273.33,547.58 264.13,541.65 246.31,527.79 196.89,485.62 191.37,480.96 143.50,440.61 135.72,434.16 125.39,427.37 112.87,420.85 91.95,411.34 69.61,404.14 51.71,399.02 42.54,395.53 32.98,392.27 24.83,389.42 13.90,385.33 2.66,380.23">
            <param key="origId" value="835504484"/>
        </lane>
        <lane id="-835504484#0_1" index="1" disallow="pedestrian tram rail_urban rail rail_electric rail_fast ship" speed="13.89" length="374.02" width="4.28" shape="322.97,555.96 309.92,556.64 287.59,557.23 281.46,555.80 271.30,551.37 261.65,545.14 243.60,531.11 194.12,488.88 188.61,484.23 140.75,443.88 133.17,437.61 123.22,431.06 111.00,424.70 90.40,415.34 68.36,408.23 50.36,403.09 41.09,399.56 31.59,396.32 23.38,393.45 12.26,389.29 0.89,384.12">
            <param key="origId" value="835504484"/>
        </lane>
        <param key="opposite" value="835504484#0_1"/>
    </edge>

**Comment by m-kro** [comment]
You have to enter the lane ID in the opposite attribute of the lane, not define a custom parameter named opposite in the edge! You can access the lane attributes by either ticking the box "Clicks target lanes" in the upper menu or scroll down in the inspect frame to the hierarchy tree and then right-click on the lane > Inspect.

**Comment by TerzaSlayer2000** [comment]
Thank you for the clarification. But it is still not working. Is it the number of lanes the problem? Actually my road network consist of single-lane roads in each direction, is that an issue?

**Comment by m-kro** [comment]
No. In your network file, you should now have `<neigh` tags mentioning the opposite lanes. Vehicles may still choose not to overtake because of the [conditions](https://sumo.dlr.de/docs/Simulation/OppositeDirectionDriving.html#model_description) and [model limitations](https://sumo.dlr.de/docs/Simulation/OppositeDirectionDriving.html#limitations), especially about the edge length. Both edges have to have the same length.

**Comment by TerzaSlayer2000** [comment]
actually the neigh tag as been set automatically when i set the opposite lane attribute:
<edge id="835504484#0" from="9695041407" to="2805324080" name="Laitumkhrah Main Road" priority="10" type="highway.tertiary" length="374.35" shape="0.97,386.58 11.44,391.27 22.65,395.46 30.89,398.34 40.36,401.57 49.68,405.12 67.74,410.28 89.63,417.34 110.06,426.62 122.14,432.91 131.90,439.33 139.37,445.52 187.23,485.87 192.73,490.51 242.25,532.77 260.41,546.89 270.29,553.26 280.78,557.84 287.37,559.38 310.00,558.78 323.65,558.05">
        <lane id="835504484#0_0" index="0" allow="pedestrian" speed="13.89" length="374.35" width="4.28" shape="-2.09,392.24 9.00,397.21 20.47,401.50 28.80,404.41 38.18,407.61 47.65,411.22 65.87,416.42 87.31,423.34 107.25,432.39 118.89,438.45 128.08,444.50 135.25,450.45 183.09,490.78 188.58,495.41 238.19,537.75 256.69,552.13 267.25,558.94 278.75,563.96 286.71,565.82 310.26,565.20 323.41,564.49">
            <param key="origId" value="835504484"/>
        </lane>
        <lane id="835504484#0_1" index="1" disallow="pedestrian tram rail_urban rail rail_electric rail_fast ship" speed="13.89" length="374.35" width="4.28" shape="-0.29,388.36 10.63,393.25 21.92,397.47 30.19,400.36 39.63,403.58 49.00,407.15 67.12,412.33 88.86,419.34 109.12,428.54 121.06,434.76 130.63,441.05 138.00,447.16 185.85,487.51 191.35,492.14 240.90,534.43 259.17,548.64 269.28,555.15 280.10,559.88 287.15,561.53 310.09,560.92 323.19,560.22">
            <neigh lane="-835504484#0_1"/>
            <param key="origId" value="835504484"/>
        </lane>
    </edge>

<edge id="-835504484#0" from="2805324080" to="9695041407" name="Laitumkhrah Main Road" priority="10" type="highway.tertiary" length="374.35" shape="323.83,558.06 310.00,558.78 287.37,559.38 280.78,557.84 270.29,553.26 260.41,546.89 242.25,532.77 192.73,490.51 187.23,485.87 139.37,445.52 131.90,439.33 122.14,432.91 110.06,426.62 89.63,417.34 67.74,410.28 49.68,405.12 40.36,401.57 30.89,398.34 22.65,395.46 11.44,391.27 0.64,386.07">
        <lane id="-835504484#0_0" index="0" allow="pedestrian" speed="13.89" length="374.35" width="4.28" shape="322.75,551.69 309.75,552.36 288.03,552.94 282.81,551.72 273.33,547.58 264.13,541.65 246.31,527.79 196.89,485.62 191.37,480.96 143.50,440.61 135.72,434.16 125.39,427.37 112.87,420.85 91.95,411.34 69.61,404.14 51.71,399.02 42.54,395.53 32.98,392.27 24.83,389.42 13.96,385.36 3.43,380.29">
            <param key="origId" value="835504484"/>
        </lane>
        <lane id="-835504484#0_1" index="1" disallow="pedestrian tram rail_urban rail rail_electric rail_fast ship" speed="13.89" length="374.35" width="4.28" shape="322.97,555.96 309.92,556.64 287.59,557.23 281.46,555.80 271.30,551.37 261.65,545.14 243.60,531.11 194.12,488.88 188.61,484.23 140.75,443.88 133.17,437.61 123.22,431.06 111.00,424.70 90.40,415.34 68.36,408.23 50.36,403.09 41.09,399.56 31.59,396.32 23.38,393.45 12.28,389.30 1.57,384.14">
            <neigh lane="835504484#0_1"/>
            <param key="origId" value="835504484"/>
        </lane>
    </edge>

the edge length is also the same for both edges

**Comment by TerzaSlayer2000** [comment]
<edge id="835504484#0" from="9695041407" to="2805324080" name="Laitumkhrah Main Road" priority="10" type="highway.tertiary" length="374.35" shape="0.97,386.58 11.44,391.27 22.65,395.46 30.89,398.34 40.36,401.57 49.68,405.12 67.74,410.28 89.63,417.34 110.06,426.62 122.14,432.91 131.90,439.33 139.37,445.52 187.23,485.87 192.73,490.51 242.25,532.77 260.41,546.89 270.29,553.26 280.78,557.84 287.37,559.38 310.00,558.78 323.65,558.05">
        <lane id="835504484#0_0" index="0" allow="pedestrian" speed="13.89" length="374.35" width="4.28" shape="-2.09,392.24 9.00,397.21 20.47,401.50 28.80,404.41 38.18,407.61 47.65,411.22 65.87,416.42 87.31,423.34 107.25,432.39 118.89,438.45 128.08,444.50 135.25,450.45 183.09,490.78 188.58,495.41 238.19,537.75 256.69,552.13 267.25,558.94 278.75,563.96 286.71,565.82 310.26,565.20 323.41,564.49">
            <param key="origId" value="835504484"/>
        </lane>
        <lane id="835504484#0_1" index="1" disallow="pedestrian tram rail_urban rail rail_electric rail_fast ship" speed="13.89" length="374.35" width="4.28" shape="-0.29,388.36 10.63,393.25 21.92,397.47 30.19,400.36 39.63,403.58 49.00,407.15 67.12,412.33 88.86,419.34 109.12,428.54 121.06,434.76 130.63,441.05 138.00,447.16 185.85,487.51 191.35,492.14 240.90,534.43 259.17,548.64 269.28,555.15 280.10,559.88 287.15,561.53 310.09,560.92 323.19,560.22">
            <neigh lane="-835504484#0_1"/>
            <param key="origId" value="835504484"/>
        </lane>
</edge>

<edge id="-835504484#0" from="2805324080" to="9695041407" name="Laitumkhrah Main Road" priority="10" type="highway.tertiary" length="374.35" shape="323.83,558.06 310.00,558.78 287.37,559.38 280.78,557.84 270.29,553.26 260.41,546.89 242.25,532.77 192.73,490.51 187.23,485.87 139.37,445.52 131.90,439.33 122.14,432.91 110.06,426.62 89.63,417.34 67.74,410.28 49.68,405.12 40.36,401.57 30.89,398.34 22.65,395.46 11.44,391.27 0.64,386.07">
        <lane id="-835504484#0_0" index="0" allow="pedestrian" speed="13.89" length="374.35" width="4.28" shape="322.75,551.69 309.75,552.36 288.03,552.94 282.81,551.72 273.33,547.58 264.13,541.65 246.31,527.79 196.89,485.62 191.37,480.96 143.50,440.61 135.72,434.16 125.39,427.37 112.87,420.85 91.95,411.34 69.61,404.14 51.71,399.02 42.54,395.53 32.98,392.27 24.83,389.42 13.96,385.36 3.43,380.29">
            <param key="origId" value="835504484"/>
        </lane>
        <lane id="-835504484#0_1" index="1" disallow="pedestrian tram rail_urban rail rail_electric rail_fast ship" speed="13.89" length="374.35" width="4.28" shape="322.97,555.96 309.92,556.64 287.59,557.23 281.46,555.80 271.30,551.37 261.65,545.14 243.60,531.11 194.12,488.88 188.61,484.23 140.75,443.88 133.17,437.61 123.22,431.06 111.00,424.70 90.40,415.34 68.36,408.23 50.36,403.09 41.09,399.56 31.59,396.32 23.38,393.45 12.28,389.30 1.57,384.14">
            <neigh lane="835504484#0_1"/>
            <param key="origId" value="835504484"/>
        </lane>
</edge>

**Comment by m-kro** [comment]
Did you actually check whether the conditions to overtake (especially free space downstream to move back to the original lane) are met? If not, vehicles will not overtake.

**Comment by TerzaSlayer2000** [comment]
Thanks

**Comment by TerzaSlayer2000** [comment]
Can you please check my simulation once? I am really stuck here on opposite lane changing of vehicles and i am unable find the issue and move forward. I would be very grateful to you if you kindly help me. I have attached the zip file of my project below : 
[Sumo Simulation.zip](https://github.com/user-attachments/files/16570455/Sumo.Simulation.zip)
Thank you so much.
Operating System : Windows 11
Sumo version : 1.18.0

**Comment by m-kro** [comment]
I'd assume there simply is no good opportunity to overtake (and maybe no reason):

- oncoming traffic
- rather short stretch up to the next intersection
- vehicles travel more or less at the same speed (limited by road speed limit)

**Comment by TerzaSlayer2000** [comment]
Thanks for the clarification Sir.
