### ISSUE TITLE
Add Restrict Zones in my Road edges

### ISSUE THREAD

**Issue by Deibynta** [eclipse-sumo/sumo#15336]
Good Afternoon Sumo Community.
I want to simulate restrict zones in the edges of my road network. I am working in a road network and i want to simulate the realistic scenarios and in my realistic scenario some the road edges of my network consist of restricted zones where vegetables vendor, fruit vendor occupy the space and because of that we can see a lot of congestion and bottleneck in the road intersection. And i want that exact congestion and bottleneck in my simulation. I just want to add restricted zones as a small portion in one of the edges. I would be very grateful if you kindly help me.

**SUMO-version:** 1.18.0

**operating system:** Windows 11

**Comment by m-kro** [comment]
You have the option to close entire lanes (statically or [temporarily using a Rerouter](https://sumo.dlr.de/docs/Simulation/Rerouter.html#closing_a_lane)) or place [stopping vehicles](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#stops_and_waypoints) where you want the lane to be occupied.

**Comment by Deibynta** [comment]
Ok Thanks, I have one more doubt. When i set my junctions type as unregulated, instead of creating a congestion or bottleneck at the intersection, the vehicles are colliding and are passing from top of each other which should not be the case. And i wanted to use unregulated junction type only for a realistic scenario that i want to create.

**Comment by m-kro** [comment]
The observed behaviour is expected for unregulated junctions. You probably want to choose a different junction type such as priority, right_before_left...

**Comment by Deibynta** [comment]
Ok sure thanks
