### ISSUE TITLE
SUMO build problem

### ISSUE THREAD

**Issue by lnkird** [eclipse-sumo/sumo#15335]
My system is similar to centos and I ran into these problems when I installed it, can it help me

-- Found Python: /usr/local/python39/bin/python3.9
-- Found Proj: /usr/local/lib/libproj.so
-- Found Fox: -I/root/include/fox-1.6 -L/root/lib -lFOX-1.6 -lX11 -lXext -lfreetype -lfontconfig -lXft -lXrender -lGL -lGLU -ldl -lpthread -lrt -lpng -ltiff -lz -lbz2 -lGLU -lGL
-- Could NOT find osgGA (missing: OSGGA_LIBRARY OSGGA_INCLUDE_DIR) 
-- Could NOT find osgViewer (missing: OSGVIEWER_LIBRARY OSGVIEWER_INCLUDE_DIR) 
-- Could NOT find osgUtil (missing: OSGUTIL_LIBRARY OSGUTIL_INCLUDE_DIR) 
-- Could NOT find osgDB (missing: OSGDB_LIBRARY OSGDB_INCLUDE_DIR) 
-- Could NOT find osgText (missing: OSGTEXT_LIBRARY OSGTEXT_INCLUDE_DIR) 
-- Could NOT find osg (missing: OSG_LIBRARY OSG_INCLUDE_DIR) 
-- Could NOT find OpenThreads (missing: OPENTHREADS_LIBRARY OPENTHREADS_INCLUDE_DIR) 
-- Could NOT find OpenSceneGraph (missing: OPENSCENEGRAPH_LIBRARIES OPENSCENEGRAPH_INCLUDE_DIR) (Required is at least version "3.4.0")
-- Could NOT find GL2PS (missing: GL2PS_LIBRARY GL2PS_INCLUDE_DIR) 
-- Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK) (Required is at least version "3.2")
-- Could NOT find JuPedSim! Skipping JuPedSim integration.
-- Could NOT find Java (missing: Java_JAVA_EXECUTABLE Java_JAVAC_EXECUTABLE Java_JAR_EXECUTABLE Java_JAVADOC_EXECUTABLE Java_JAVAH_EXECUTABLE Development) 
-- Could NOT find Java (missing: Java_JAVA_EXECUTABLE Java_JAR_EXECUTABLE Java_JAVAC_EXECUTABLE Java_JAVAH_EXECUTABLE Java_JAVADOC_EXECUTABLE) 
-- Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
CMake Warning at src/libsumo/CMakeLists.txt:151 (message):
  ENABLE_JAVA_BINDINGS is set but Java or JNI was not found.

-- Could NOT find Java (missing: Java_JAVA_EXECUTABLE Java_JAR_EXECUTABLE Java_JAVAC_EXECUTABLE Java_JAVAH_EXECUTABLE Java_JAVADOC_EXECUTABLE) 
-- Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
CMake Warning at src/libtraci/CMakeLists.txt:110 (message):
  ENABLE_JAVA_BINDINGS is set but Java or JNI was not found.

.......
collect2: error: ld returned 1 exit status
make[2]: *** [src/traci_testclient/CMakeFiles/testlibsumo.dir/build.make:101: ../bin/testlibsumo] Error 1
make[1]: *** [CMakeFiles/Makefile2:3974: src/traci_testclient/CMakeFiles/testlibsumo.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX shared library ../../../bin/libsumofmi2.so
[100%] Built target libsumofmi2
[100%] Linking CXX shared module ../../../tools/libtraci/_libtraci.so
[100%] Built target libtraci
[100%] Linking CXX shared module ../../../tools/libsumo/_libsumo.so
[100%] Built target libsumo
make: *** [Makefile:146: all] Error 2
[root@iZ3il01cuoswexxac9745wZ build]#

**Comment by palvarezlopez** [comment]
Could you please install the osg-dev libraries, gl2ps and a jdk and retry? If after install it doesn't work, please reopen the ticket.
