### ISSUE TITLE
About output settings

### ISSUE THREAD

**Issue by iiyuu1222** [eclipse-sumo/sumo#15334]
I am currently setting battery.xml as the output file, but I am having trouble because information is not output for each step.
Normally, if it starts at `<timestep=1.00>`, it should end at `</timestep>`, but it is interrupted in the middle. My guess is that the data is stored in the buffer, but there was no point in using flash.
Also, I am currently using ubuntu22.04, and SUMO version is the latest 1.20.0.
How should I manipulate the output file? thank you.

**Comment by palvarezlopez** [comment]
Hi! I cannot fully understand your question. Could you please show here the sumo config file?

**Comment by iiyuu1222** [comment]
thank you for your reply.
I will attach the zip file. Also, I use TraCI for execution, and the program is written in runner.py. The battery.xml in question is inside the data folder.
When I run it, battery.xml should be updated every step, but it doesn't work.
thank you.
[sumo.zip](https://github.com/user-attachments/files/16579473/sumo.zip)

**Comment by m-kro** [comment]
Your scenario crashes because of an unknown edge:
> Error: The edge '922855629#2' within the route for trip 'veh621' is not known.

Otherwise I don't see any problem. You have to wait until the simulation ended to access the battery output, though.

**Comment by iiyuu1222** [comment]
thank you for your reply. The official documentation states that the results are output for each simulation step, but for some reason when I run it on ubuntu, it is not updated at each simulation step, and the results are not output until several steps have passed. yeah. (When executed on Windows, it was output for each simulation step.)
https://sumo.dlr.de/docs/Simulation/Output/FCDOutput.html

**Comment by m-kro** [comment]
These are two separate things:

1. Time resolution of data output
2. When the output can be accessed safely

Also on Windows it may happen that data isn't written every time step. Please do not rely on that and wait until simulation is over. If you want to know vehicle information while simulating, you can use TraCI.

**Comment by iiyuu1222** [comment]
thank you for your reply.
I understand how it works on Windows.
Also, I originally wanted to link SUMO and NS-3, and after one step forward, I would draw on NS-3 based on the coordinates output from SUMO, so that information from SUMO can be transferred to each I want it for each simulation step.
Therefore, I am using TraCI, which was mentioned earlier, but the battery.xml gets cut off midway through, and although the output is being output for each simulation step, it is only half-finished. (Actually, I will paste the battery, xml at 100 seconds under the name 100.xml. The </timestep> at the end is cut off by the tag in the middle.)
Also, since I want to perform this kind of behavior, if I output the results after completing the SUMO simulation, it will be too late, so I would like to solve this problem. Finally, I will paste the SUMO file that I am currently creating and the NS-3 file (sumo_1.cc). Since it performs packet communication with NS-3, it will not work if it is used alone.
[allfile.zip](https://github.com/user-attachments/files/16588364/allfile.zip)

**Comment by m-kro** [comment]
You can query some of properties of the battery using [TraCI](https://sumo.dlr.de/docs/Models/Electric.html#traci). Let us know if something is missing. We cannot assist you further messing with the file output during writing.
