### ISSUE TITLE
Loading a state fails when the vehicle is on the direct successor internal edge of the (previous) stop edge

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#15338]
In this case `updateBestLanes` fails because it is started with the stop edge (although the stop position has already been passed). As the best lanes search ends at stops, no best lanes are determined for the vehicle which is already on the internal lane downstream.

**Comment by m-kro** [comment]
Probably rather a question of where the vehicle should stop and maybe of parking rerouting...

**Comment by namdre** [comment]
most likely fixed in the context of #15353, #15503
