### ISSUE TITLE
I ran into a problem using plotXMLAttributes.py

### ISSUE THREAD

**Issue by jamongadejoa28** [eclipse-sumo/sumo#15340]
I am currently trying to run this code to extract speed from an XML file and create a graphical file.
[fcd_analysis.txt](https://github.com/user-attachments/files/16590853/fcd_analysis.txt)

The main script to run the attached code is here

```
import os
import sys
import osmnx as ox
import subprocess
import random
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import sumolib
import traci
import optparse
import csv
import xml.etree.ElementTree as ET
from fcd_analysis import FCDAnalyzer
from collections import defaultdict

if 'SUMO_HOME' in os.environ:
    sumo_home = os.environ['SUMO_HOME']
    tools = os.path.join(sumo_home, 'tools')
    sys.path.append(tools)
    fcd_analyzer = FCDAnalyzer(sumo_home)
else:
    sys.exit("please declare environment variable 'SUMO_HOME'")

.
.
.
.

fcd_analyzer.analyze_fcd_xml(
        input_file="data/fcd.xml",
        output_file="data/avg_speeds_518937795.xml",
        graph_file="data/avg_speed_518937795_lanes.png"
    )
```    
 When I run the code, the generated xml file looks like this
 
[xmlfile.txt](https://github.com/user-attachments/files/16590924/xmlfile.txt)

The xml file is coming out fine, but when I look at the result of the generated image file, only the first element(interval  begin="43.0" end="44.0" meanSpeed="22.07" ) of the xml file is getting the data value.

Why is this happening?

**Comment by m-kro** [comment]
Please add `--idattr @NONE` to your plotXMLAttributes.py call. By default the script expects another attribute to aggregate the data into separate lines (e.g. data per vehicle base).

**Comment by jamongadejoa28** [comment]
@m-kro 
Thank you!

**Comment by namdre** [comment]
If you use the latest development version, you can also set the option **--robust-parser** which is slower but can handle all valid xml files regardless of whitespace/linebreaks
