### ISSUE TITLE
Run SUMO on AWS

### ISSUE THREAD

**Issue by iiyuu1222** [eclipse-sumo/sumo#15358]
Hello Sumo Community,I want to run SUMO on AWS ubuntu 22.04. However, since it is a CUI, you will not be able to display the map and will receive an error.
What should I do to display the map in a CUI environment?

**Comment by m-kro** [comment]
What does the abbreviation CUI stand for?

**Comment by iiyuu1222** [comment]
CUI stands for Character User Interface. I would like to check the results on "SUMO-gui" on my laptop. But I cannot use SUMO-gui on AWS. I use the file "runner.py" with the following code: 

`    options = get_options()

    if options.nogui:
        sumoBinary = checkBinary('sumo')
    else:
        sumoBinary = checkBinary('sumo-gui')

    traci.start([sumoBinary, "-c", "data/osm.sumocfg", "--device.fcd.period", "1", "--tripinfo-output", "tripinfo.xml"])`

Could you give me some advice, please?

**Comment by m-kro** [comment]
You can [save and load](https://sumo.dlr.de/docs/Simulation/SaveAndLoad.html) simulation states. Please keep in mind the loaded simulation may differ to a small degree as not exactly everything is saved in the state (see [limitations](https://sumo.dlr.de/docs/Simulation/SaveAndLoad.html#know_issues)).
