### ISSUE TITLE
libsumo.libsumo.TraCIException: stop for vehicle '47' on lane 'E1_0' is too close to brake.

### ISSUE THREAD

**Issue by cherryh2021** [eclipse-sumo/sumo#15351]
I am running sumo-meso and the command 
libsumo.vehicle.setStop(veh, rou[1][0], pos=pos, duration=3) get error:
libsumo.libsumo.TraCIException: stop for vehicle '47' on lane 'E1_0' is too close to brake.

```
print("vehicle edge {}, position{}".format(libsumo.vehicle.getRoadID(veh), libsumo.vehicle.getLanePosition(veh)))
print("step {}, veh {}, edge {}, pos {}".format(i, veh, rou[1][0], pos))
```
output:
vehicle edge E1, position0.0
step 253, veh 47, edge E1, pos 0.0

I try to debug by changing the command `libsumo.vehicle.setStop(veh, rou[1][0], pos=pos, duration=3)` to `libsumo.vehicle.setStop(veh, rou[1][0], pos=pos+50.0, duration=3)` still can't help

I am wondering why this error 'stop for vehicle '47' on lane 'E1_0' is too close to brake' arises and how can I fix it. Thank you!

**Comment by m-kro** [comment]
At which speed does the vehicle travel and how string can it brake (decel)?

**Comment by cherryh2021** [comment]
Use `libsumo.vehicle.getSpeed(veh), libsumo.vehicle.getDecel(veh)` command output:
speed 12.507817385866167, 
decel 4.5

**Comment by m-kro** [comment]
[Here](https://sumo.dlr.de/extractTest.php?path=complex/traci/vehicle/setStop/newStop) you can find an example scenario using `traci.vehicle.setStop` you can compare with yours. Actually it should work as well with your vehicle speed and decel but maybe there is some other problem...

**Comment by namdre** [comment]
The meso vehicle fails to stop at pos+50 whereas the micro vehicle manages to do so. (even though meso doesn't even model deceleration)

**Comment by namdre** [comment]
In meso, stopping is only possible when entering a new segment. Thus, the minimum stopping distance is tied to the segment length.

**Comment by cherryh2021** [comment]
> In meso, stopping is only possible when entering a new segment. Thus, the minimum stopping distance is tied to the segment length.

Thanks for the reply!
