### ISSUE TITLE
 Constraint for Mandatory Stop

### ISSUE THREAD

**Issue by TerzaSlayer2000** [eclipse-sumo/sumo#15354]
Hello Sumo Community, I want to create one scenario in sumo that contain  constraint of mandatory stop for my vehicles.
The vehicles should stop before the roundabout intersection so that the roundabout intersection is cleared (or a buffer zone is created) all the time and there is no bottle neck or congestion in the roundabout intersection. Below is the screenshot of my roundabout intersection and the blue mark is where i want my vehicles to stop. I would be very grateful for your kind help.
Thank you.

![Screenshot (22)](https://github.com/user-attachments/assets/5b6718f0-8e86-45ba-a3cd-807daf6bc2fc)

**SUMO-version:** 1.18.0

**operating system:** Windows 11

**Comment by m-kro** [comment]
See #14129 . Currently it is not possible to completely avoid gridlocks originating in roundabouts.

**Comment by TerzaSlayer2000** [comment]
Thanks.

**Comment by namdre** [comment]
Actually, a single lane roundabout should not gridlock in SUMO as long as the outflow edges are clear. If the roundabout is correctly configured (there should be a `<roundabout>` element in the .net.xml file).
Please provide an example scenario if your roundabout has a problem.
