### ISSUE TITLE
[Question] Questions about lane changes

### ISSUE THREAD

**Issue by jamongadejoa28** [eclipse-sumo/sumo#15360]
**SUMO-version:**
1.20.0
**operating system:**
pycharm
Runtime version: 17.0.10+1-b1087.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

When faced with a temporarily blocked lane in a situation where the lanes are not connected, is there a way for the vehicle to change lanes from the edge of the blocked lane to the unblocked lane? In this case, the edges before and after the edge containing the blocked lane are included in the vehicle's route.

**Comment by m-kro** [comment]
Do you mean [teleporting vehicles](https://sumo.dlr.de/docs/Simulation/Why_Vehicles_are_teleporting.html)?

**Comment by jamongadejoa28** [comment]
> bu

As a result of the simulation, when you look at the gui screen, you can pass the driveway in an unblocked lane, but the vehicle actually stopped until the lane reopened as if it had stopped in front of a stop signal at a traffic light.
I thought that if the lanes were blocked, of course, as in actual traffic conditions, they would detour to the unblocked lanes. However, the connection confirmed that the unblocked lanes were not connected to the current lanes of the vehicle passing through the previous road.
Is it because of this problem as I thought?? I want to know sumo's rules and conditions for this phenomenon. Even if the lane is not connected, if the edge with blocked lane is included in the path, please let me know if there is a way to detour to the lane that is not blocked.

**Comment by m-kro** [comment]
Vehicles do not reroute by default. I'm still not sure because your message is not that clear and I don't see any screenshot you seem to refer to. You need to configure rerouting to happen by using either:

- [rerouter](https://sumo.dlr.de/docs/Simulation/Rerouter.html#closing_a_street) definitions upstream the blocked edge (actually upstream the intersection they should choose a different path)
- [rerouting device](https://sumo.dlr.de/docs/Demand/Automatic_Routing.html) (issues a periodic rerouting)

**Comment by jamongadejoa28** [comment]
@m-kro 
![image](https://github.com/user-attachments/assets/c1b02ad7-0fde-4093-916f-3a99cf47f0e2)
![image](https://github.com/user-attachments/assets/e2e27cfa-a2d6-4dd5-b6b3-2f766986e2c3)
![image](https://github.com/user-attachments/assets/d592d37e-5030-4f55-bbc9-9e2ea1bf049c)

The id of the blue edge is 552440699#0, the id of the yellow edge is 518937795, and the id of the red edge is 762774291#1.
Lane Blocking occurs at the 518937795 edge. There are three lanes blocked in order from the top.
When a vehicle with a route shown in the image is passing through the blue lane shown in the road image, is it not possible to detour to the unblocked lane?

**Comment by m-kro** [comment]
Routes are always edge-based. As long as there is still a lane open for the vehicle class in question, the vehicle will try to use that one.

**Comment by jamongadejoa28** [comment]
@m-kro 
What exactly do you mean by edge-based? As shown in the attached figure, lanes on the connected access road (yellow edge) are blocked. At this point, the vehicle that was about to enter is stopped until the lane is allowed again, as if it had stopped in front of a stop signal at the traffic light.

**Comment by m-kro** [comment]
Previously you wrote that three (so 3/4 lanes) are blocked with one remaining open. So if one lane of the route edge is still open the route should still be viable.

Please show or upload the real simulation scenario (not the netedit view of the network) in case it is still unclear.

**Comment by jamongadejoa28** [comment]
@m-kro 
[https://drive.google.com/file/d/1e6pmhVMHapi_BoEz80sOuz5a0E5Rmmgd/view?usp=sharing](url)

**Comment by m-kro** [comment]
At least I see some vehicles passing on the leftmost lane which is not closed. Vehicles on the rightmost lane will stop when the lanes downstream closed shortly before their arrival and they just made it to come to a stop. Just delay the lane closing to one at a time (first the rightmost, some seconds later the second and so on).

**Comment by jamongadejoa28** [comment]
@m-kro 
Thank you for your kind reply. I also accessed and read the Routing document link through the rerouter link you mentioned. When I used that setting, I confirmed that the vehicle movement can be teleported.
