### ISSUE TITLE
Regarding the implementation of two functions "getIncomingEdges(self, junctionID)" and "getOutgoingEdges(self, junctionID) "

### ISSUE THREAD

**Issue by technomancerAdarsh** [eclipse-sumo/sumo#15378]
i just want the incoming edges and outgoing edges from the junction  and for that i went through the documentation of sumo and found that in junction value retrieval there is two functions :
getIncomingEdges(self, junctionID)
[getIncomingEdges](https://sumo.dlr.de/pydoc/traci._junction.html#JunctionDomain-getIncomingEdges)(string) -> list(string)
 
Returns the ids of the edges that end at this junction
getOutgoingEdges(self, junctionID)
[getOutgoingEdges](https://sumo.dlr.de/pydoc/traci._junction.html#JunctionDomain-getOutgoingEdges)(string) -> list(string)
 
Returns the ids of the edges that start at this junction

is mentioned so i have implemented that using traci in python in the code as :

import traci
import time
import traci.constants as tc
import pytz
import datetime
from random import randrange
import pandas as pd

def getdatetime():
    utc_now = pytz.utc.localize(datetime.datetime.utcnow())
    currentDT = utc_now.astimezone(pytz.timezone("Asia/Singapore"))
    DATIME = currentDT.strftime("%Y-%m-%d %H:%M:%S")
    return DATIME

def flatten_list(_2d_list):
    flat_list = []
    for element in _2d_list:
        if isinstance(element, list):
            flat_list.extend(element)
        else:
            flat_list.append(element)
    return flat_list

sumoCmd = ["sumo", "-c", "osm.sumocfg"]
traci.start(sumoCmd)

packVehicleData = []
packTLSData = []
packBigData = []

while traci.simulation.getMinExpectedNumber() > 0:
    traci.simulationStep()

    junctions = traci.junction.getIDList()

    for jun_id in junctions:
        incoming_edge = traci.junction.getIncomingEdges(jun_id)
        outgoing_edge = traci.junction.getOutgoingEdges(jun_id)
        # Flatten lists before adding to packBigData
        junction_list = [jun_id, ','.join(incoming_edge), ','.join(outgoing_edge)]
        packBigData.append(junction_list)

traci.close()

# Saving the junction data to CSV
column_names = ['junction_id', 'incoming_edge', 'outgoing_edge']
dataset = pd.DataFrame(packBigData, columns=column_names)
dataset.to_csv("output_junction.csv", index=False)

# Optionally, delay before the script ends
time.sleep(5)

**but when i run it says that the junction domain have no attributes getIncomingEdges(jun_id) and getOutgoingEdges(jun_id)
if anyone can help then it would be benifical .
do help asap because its urgent .**

thank you
Adarsh Shukla

**Comment by namdre** [comment]
The functions are implemented only since the latest release version (1.20.0). Please ensure that your `import traci` call imports this version. See also https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#determine_the_traci_library_being_loaded
