### ISSUE TITLE
Error: whitespace expected

### ISSUE THREAD

**Issue by Consept-Pedro** [eclipse-sumo/sumo#15377]
Boa noite,

Estou desenvolvendo um teste de simulação simples com od2trips para verificar a possibilidade de utilização em uma rede mais complexa.
Gerei para cada tipo de veículos as rotas separadamente. A simulação individual de cada veículo deu certo. Porém, ao tentar simular todas as rotas juntas, aparece a mensagem no SUMO:
 ----------------------------------------------------------------------------------------
Error: whitespace expected
Error:  (At line/column 11/63).
Error: Could not load configuration 'C:\Users\Pedro\Sumo\Int-T.sumocfg'.
Quitting (on error).

Segue link para download de todos os arquivos
https://conseptbr-my.sharepoint.com/:u:/p/pedro/EZRRprLo219Mubb-HKPemYcBPklx1LoCql_fVNRZZ2i6zQ?e=q4mgYZ

Desde já agradeço.

**Comment by Consept-Pedro** [comment]
Me desculpe,

Já consegui encontrar o problema. A aspas deve ser fechada só ao final.
    <input>
        <net-file value="Int-T.net.xml"/>
        <route-files value = "od_route_file-bus.odtrips.rou.xml,od_route_file-carro.odtrips.rou.xml,od_route_file-cam.odtrips.rou.xml,od_route_file-moto.odtrips.rou.xml"/>
    </input>

**Comment by Consept-Pedro** [comment]
<input>
        <net-file value="Int-T.net.xml"/>
        <route-files value = "od_route_file-bus.odtrips.rou.xml,od_route_file-carro.odtrips.rou.xml,od_route_file-cam.odtrips.rou.xml,od_route_file-moto.odtrips.rou.xml"/>
    </input>

**Comment by behrisch** [comment]
Please ask in English the next time. Thank you!
