### ISSUE TITLE
[Question] Calculation of LOS in SUMO

### ISSUE THREAD

**Issue by transport45678** [eclipse-sumo/sumo#15371]
Hello, How can I calculate Level of Service in SUMO at intersections? Thank you for help.

**Comment by m-kro** [comment]
You can use [lane area detectors](https://sumo.dlr.de/docs/Simulation/Output/Lanearea_Detectors_%28E2%29.html) or [Multi-Entry-Exit Detectors](https://sumo.dlr.de/docs/Simulation/Output/Multi-Entry-Exit_Detectors_%28E3%29.html) to collect statistics about delays upstream of the intersection.

**Comment by namdre** [comment]
see also https://sumo.dlr.de/docs/Simulation/Output/#values_for_junctions
