### ISSUE TITLE
meanData: exclude non-driving lanes from laneDensity computation

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#15383]
laneDensity is computed as density / laneNumber.
At least the following lanes should not count towwards this computation
- sidewalks
- green verges
- sidewalk + bicycles

**Comment by namdre** [comment]
it may be feasible to fine-tune this based on the `vTypes` attribute of the meanData element. (Even though the types don't need to be known yet when loading meanData, they must have shown up at write-time if there was any unfiltered traffic measured on the edge/lane).

**Comment by behrisch** [comment]
affects edge density as well

**Comment by namdre** [comment]
not excluding bike lanes because bikes are counted by default and thus increase density.
