### ISSUE TITLE
Sumo simulation results and traffic light information defined in network files do not match.

### ISSUE THREAD

**Issue by chang0959** [eclipse-sumo/sumo#15391]
Hello. 

When I set the begin value in the sumocfg file for 36000 seconds, I expected that the` <phase duration="28" state="grrgrgrgrgggggggr" />` of mon-2 in TLS-Programs would work, but it is not. 

What is the reason? 

But, when the start value is set to 21600 seconds, it is well expressed as `<phase duration="32" state="grrrgrgrggggggggr" />` 
I'm curious about the rules of how the signal program is displayed in the simulation according to the begin value in the sumocfg file.

I'd appreciate it if you could tell me in detail.

Thank you.

1. time="36000"
![image](https://github.com/user-attachments/assets/a4d185a1-a113-4180-9b01-cc7e69d6b9a2)

2. time="21600"
![image](https://github.com/user-attachments/assets/64b460ac-ff5a-4b78-beaf-98e765d8a0fe)

------

**SUMO-version:** 1.20.0
![image](https://github.com/user-attachments/assets/41bb63a0-fbb8-40c0-a7fb-a51cd46e4400)

**operating system:** Mac Apple Silicon M1 (Darwin arm64) 

-----

### [Network File (.net.xml)]
```
  <tlLogic id="2330016500" type="static" programID="mon-0" offset="0">
    <phase duration="28" state="grrrrGrrrGggggGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="40" state="rrrrrrrrrrrrrrrrrr" />
    <phase duration="31" state="grrrrGrrrGrrrrGGgg" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="27" state="gggggGrrrGrrrrGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="32" state="grrrrGGggGrrrrGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
  </tlLogic>
  <tlLogic id="2330016500" type="static" programID="mon-1" offset="0">
    <phase duration="32" state="grrrrGrrrGggggGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="40" state="rrrrrrrrrrrrrrrrrr" />
    <phase duration="27" state="grrrrGrrrGrrrrGGgg" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="31" state="gggggGrrrGrrrrGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="38" state="grrrrGGggGrrrrGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
  </tlLogic>
  <tlLogic id="2330016500" type="static" programID="mon-2" offset="0">
    <phase duration="28" state="grrrrGrrrGggggGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="40" state="rrrrrrrrrrrrrrrrrr" />
    <phase duration="31" state="grrrrGrrrGrrrrGGgg" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="27" state="gggggGrrrGrrrrGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="32" state="grrrrGGggGrrrrGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
  </tlLogic>
  <WAUT id="2330016500_program" startProg="mon-0" refTime="0" period="7:0:0:0">
    <wautSwitch to="mon-0" time="0" />
    <wautSwitch to="mon-1" time="21600" />
    <wautSwitch to="mon-2" time="36000" />
  </WAUT>
  <wautJunction junctionID="2330016500" wautID="2330016500_program" procedure="Stretch" />

```

### [.sumocfg]
```
<configuration>
    <input>
        <net-file value="hwaseong_out.net.xml"/>
        <route-files value="livinglab.route.xml"/>
    </input>
    <time>
        <step-length value="0.1"/>
        <begin value="36000"/> 
    </time>
</configuration>
```

**Comment by namdre** [comment]
All loaded programs (even those that are not active at a given junction) are running through their cycles in the background all the time. When the WAUT activates a new program it goes into the phase that was currently active in the background (and this isn't necessarily phase 0).

When you start a simulation with a different begin time, all programs are initialized to the phase that they would have had if the simulation had started at time 0. Again, this means that a WAUT doesn't always switch into phase 0 but into whatever phase would have been active if the program had been running continuously from time 0. To get the desired behavior you can set `offset=36000` for program `mon-2`

**Comment by chang0959** [comment]
Thank you for your confirmation.

As you said, if the cycle continues in the background, why does <phase duration="28" state="grrgrgrgrgggggggggr" /> continue for 28 seconds when you set the begin value to 21600 seconds?

The mon-0 program cycle is 170 seconds, so at 21600 seconds, `<phase duration="28" state="grrGrrGrrGggggggGrr" />` will last 10 seconds (170s x 127 times = 21590s) and proceed to `<phase duration="3" state="yyyyyyyyyyyyyyyyyy" />` 

![image](https://github.com/user-attachments/assets/f9f89579-e739-4c38-8646-db2ffd1a70b0)


I'm curious about the rule where the signal is simulated when I start a simulation with a different begin.

**Comment by namdre** [comment]
As you have correctly computed, the running duration at the beginning of the simulation is 10s. However, your screenshot shows time 21606 which is 6seconds after the begin. Hence, the running time is 16s.

**Comment by chang0959** [comment]
I emailed you to namdre.sumo@gmail.com because of security issues.
Please use it only for verification purposes.

Thank you for your help.

**Comment by namdre** [comment]
The switch is delayed because you configured `procedure="Stretch"` in your `<wautJunction>`
Also, I noticed that you are working with a modified .net.xml file. This is strongly discouraged: https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why

**Comment by chang0959** [comment]
Thank you for letting me know that it shouldn't be modified.
I'll keep in mind.

But I still don't understand how the signal program works.

<procedure="Stretch"> Even when I remove it and turn it around, the rules for the program to switch are not constant.

The same is true when you set it to synchron="t".

--


The first example is 10 seconds before the mon-1 program (switching time: 21600 seconds) starts, and the second example is 10 seconds before the mon-2 program (switching time: 36000 seconds) starts.


In the first example, it switches well to the mon-1 program after 10 seconds, but I don't think it works in the second example.

The results I expected should start at 35990 seconds and be converted to mon-2 program 10 seconds later, but it turns into a strange phase.


Can you check by simulating each of <begin value="21590"/> and <begin value="35990"/>?

Even if I set it to a few seconds, I want the current program to switch to the same rule.

Or send me an example file that works well and I'll check it out.


Thank you.

-- 
Watch the 36,000 second video carefully. 

1-1. 21590s
![image](https://github.com/user-attachments/assets/41af2fc1-3a0b-4377-8b6d-1a3ad9cfe5b7)

1-2. 21600s
![image](https://github.com/user-attachments/assets/8f5a6d9b-8617-4cd2-9657-23491730b82f)

2-1. 35990s
![image](https://github.com/user-attachments/assets/f1c2c47d-8046-470d-8439-26e2740b7614)

2-2. 36000s
https://github.com/user-attachments/assets/fe93ac72-b985-4c9a-adbf-28053a09971d

**Comment by namdre** [comment]
> but it turns into a strange phase.

As mentioned earlier, you can fix this with an offset:

```
    <tlLogic id="2330016500" type="static" programID="mon-1" offset="21600">
...

    <tlLogic id="2330016500" type="static" programID="mon-2" offset="36000">
...
```

Also, use the default switching procedure:
`  <wautJunction junctionID="2330016500" wautID="2330016500_program"/>
`

**Comment by chang0959** [comment]
The same phenomenon continues even if you modify it according to what you said.

Even if you modify it through offset parameter as below, it works in a strange phase. 

I have no idea what the reason is. 


```
example)  
  <tlLogic id="2330016500" type="static" programID="mon-0" offset="0">
    <phase duration="28" state="grrrrGrrrGggggGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="40" state="rrrrrrrrrrrrrrrrrr" />
    <phase duration="31" state="grrrrGrrrGrrrrGGgg" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="27" state="gggggGrrrGrrrrGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="32" state="grrrrGGggGrrrrGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
  </tlLogic>
  <tlLogic id="2330016500" type="static" programID="mon-1" offset="21600">
    <phase duration="32" state="grrrrGrrrGggggGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="40" state="rrrrrrrrrrrrrrrrrr" />
    <phase duration="27" state="grrrrGrrrGrrrrGGgg" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="31" state="gggggGrrrGrrrrGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="38" state="grrrrGGggGrrrrGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
  </tlLogic>
  <tlLogic id="2330016500" type="static" programID="mon-2" offset="36000">
    <phase duration="28" state="grrrrGrrrGggggGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="40" state="rrrrrrrrrrrrrrrrrr" />
    <phase duration="31" state="grrrrGrrrGrrrrGGgg" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="27" state="gggggGrrrGrrrrGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="32" state="grrrrGGggGrrrrGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
  </tlLogic>
  <tlLogic id="2330016500" type="static" programID="mon-3" offset="57600">
    <phase duration="27" state="grrrrGrrrGggggGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="40" state="rrrrrrrrrrrrrrrrrr" />
    <phase duration="32" state="grrrrGrrrGrrrrGGgg" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="28" state="gggggGrrrGrrrrGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="41" state="grrrrGGggGrrrrGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
  </tlLogic>
  <tlLogic id="2330016500" type="static" programID="mon-4" offset="72000">
    <phase duration="28" state="grrrrGrrrGggggGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="40" state="rrrrrrrrrrrrrrrrrr" />
    <phase duration="31" state="grrrrGrrrGrrrrGGgg" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="27" state="gggggGrrrGrrrrGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
    <phase duration="32" state="grrrrGGggGrrrrGrrr" />
    <phase duration="3" state="yyyyyyyyyyyyyyyyyy" />
  </tlLogic>
```

**Comment by namdre** [comment]
please send the exact files that you are using, the command line options you are setting, the relevant simulation time to look at and describe which phase you expect and which phase you are seeing instead.

**Comment by chang0959** [comment]
The current modifications I made are as follows.

1. I set the program's initial time with offset properties. (offset="21600", offset="36000...")

2. I used "the default switching procedure" (Not procedure="Stretch")


---- 
### [Expectations]
If SUMO Simulation is run at 35990 seconds,
I thought the phase 7 signal was displayed in the mon-1 program (`<phase duration="38" state="grrrrGGggGrrrrGrrr" />`
)

The reason is
1. 35990 seconds start (10 seconds before mon-2 program start)

2. From 21600 seconds to 3600 seconds, 180 second cycles are performed 80 times in total. (21600 + 180 * 80 = 36000)

3. At 35990 seconds, it stayed in phase 7, and I thought it would switch to phase 0 of the mon-2 program right after 10 seconds

---- 
### [Current situation]
**The signal color in SUMO Simulation remains in phase 5 (`<phase duration="31" state="gggggGrrrGrrrrGrrr" />`), and the information seen through "Show Parameters" is phase 7 (`<phase duration="38" state="grrrrGGggGrrrrGrrr" />`). 
SUMO Simulation display information and Show parameter information are different, and the result I expected is Show parameter information. (For your information, linkindex goes up by 1 clockwise.)**




https://github.com/user-attachments/assets/8ebebec9-40d3-41e6-b43a-34b328bd2442




-- 

I sent the SUMO file back by gmail.

Thank you for your help.

Have a nice day.

**Comment by namdre** [comment]
The problem came up because you modified the .net.xml :man_facepalming: 
WAUTS should be loaded from an additional file after all  `<connection>` elements from the network and your input caused them to be loaded in the wrong order.

**Comment by chang0959** [comment]
I modified it as you said, so it works properly.

Thank you for your detailed confirmation.

Have a nice day.
