### ISSUE TITLE
A question about SUMO in linux system

### ISSUE THREAD

**Issue by pjj-OSM** [eclipse-sumo/sumo#15396]
I install sumo(version 1.20.0) on linux(x86) (follow this [link](https://sumo.dlr.de/docs/Installing/Linux_Build.html#Building_the_SUMO_binaries_with_cmake)), and set the environment variable like that:
SUMO_HOME=/usr/local/share/sumo
PATH=$SUMO_HOME/bin:$SUMO_HOOME/tools
But I found i just can use the command "sumoD",  other command like "sumo" and "sumo-gui" using in windows  is invalid. So whether the command ("sumo"、"sumo-gui") are useless in linux? if prossible how to use it.

**Comment by namdre** [comment]
it seems like you configured the debug build with `cmake -D CMAKE_BUILD_TYPE=Debug -B build .`

instead rebuild and install with only `cmake -B build .`

**Comment by pjj-OSM** [comment]
thank you ,i rebuild sumo using cmake -B build .   
**sumo command** is work, but **sumo-gui** is invalid?

**Comment by namdre** [comment]
this means the fox-toolkit wasn't installed or not found during build. 
Make sure to install all dependencies with `sudo apt-get install git cmake python3 g++ libxerces-c-dev libfox-1.6-dev libgdal-dev libproj-dev libgl2ps-dev python3-dev swig default-jdk maven libeigen3-dev` 
If you are not on a debian-based distro, the packages may have different names.

**Comment by pjj-OSM** [comment]
> this means the fox-toolkit wasn't installed or not found during build. Make sure to install all dependencies with `sudo apt-get install git cmake python3 g++ libxerces-c-dev libfox-1.6-dev libgdal-dev libproj-dev libgl2ps-dev python3-dev swig default-jdk maven libeigen3-dev` If you are not on a debian-based distro, the packages may have different names.

when i install libfox in **Kylin Linux Advanced Server release V10 system** ,raise this error

FXGLCone.cpp: 在成员函数‘virtual void FX::FXGLCone::drawshape(FX::FXGLViewer*)’中:
FXGLCone.cpp:51:23: 错误：‘GLUquadric’在此作用域中尚未声明
 #define GLUquadricObj GLUquadric
                       ^
FXGLCone.cpp:110:3: 附注：in expansion of macro ‘GLUquadricObj’
   GLUquadricObj* quad=gluNewQuadric();
   ^~~~~~~~~~~~~
FXGLCone.cpp:51:23: 附注：suggested alternative: ‘GLUquadricObj’
 #define GLUquadricObj GLUquadric
                       ^
FXGLCone.cpp:110:3: 附注：in expansion of macro ‘GLUquadricObj’
   GLUquadricObj* quad=gluNewQuadric();
   ^~~~~~~~~~~~~
FXGLCone.cpp:110:18: 错误：‘quad’在此作用域中尚未声明
   GLUquadricObj* quad=gluNewQuadric();
                  ^~~~
FXGLCone.cpp:110:18: 附注：suggested alternative: ‘load’
   GLUquadricObj* quad=gluNewQuadric();
                  ^~~~
                  load
FXGLCone.cpp:110:23: 错误：‘gluNewQuadric’在此作用域中尚未声明
   GLUquadricObj* quad=gluNewQuadric();
                       ^~~~~~~~~~~~~
FXGLCone.cpp:111:36: 错误：‘GLU_FILL’在此作用域中尚未声明
   gluQuadricDrawStyle(quad,(GLenum)GLU_FILL);
                                    ^~~~~~~~
FXGLCone.cpp:111:36: 附注：suggested alternative: ‘GL_FILL’
   gluQuadricDrawStyle(quad,(GLenum)GLU_FILL);
                                    ^~~~~~~~
                                    GL_FILL
FXGLCone.cpp:111:3: 错误：‘gluQuadricDrawStyle’在此作用域中尚未声明
   gluQuadricDrawStyle(quad,(GLenum)GLU_FILL);
   ^~~~~~~~~~~~~~~~~~~
FXGLCone.cpp:111:3: 附注：suggested alternative: ‘glXQueryDrawable’
   gluQuadricDrawStyle(quad,(GLenum)GLU_FILL);
   ^~~~~~~~~~~~~~~~~~~
   glXQueryDrawable
FXGLCone.cpp:118:3: 错误：‘gluCylinder’在此作用域中尚未声明
   gluCylinder(quad,radius,0,height,FXGLCONE_SLICES_NUMBER,FXGLCONE_STACKS_NUMBER);
   ^~~~~~~~~~~
FXGLCone.cpp:119:38: 错误：‘GLU_INSIDE’在此作用域中尚未声明
   gluQuadricOrientation(quad,(GLenum)GLU_INSIDE);
                                      ^~~~~~~~~~
FXGLCone.cpp:119:38: 附注：suggested alternative: ‘GL_INDEX’
   gluQuadricOrientation(quad,(GLenum)GLU_INSIDE);
                                      ^~~~~~~~~~
                                      GL_INDEX
FXGLCone.cpp:119:3: 错误：‘gluQuadricOrientation’在此作用域中尚未声明
   gluQuadricOrientation(quad,(GLenum)GLU_INSIDE);
   ^~~~~~~~~~~~~~~~~~~~~
FXGLCone.cpp:119:3: 附注：suggested alternative: ‘XNQueryOrientation’
   gluQuadricOrientation(quad,(GLenum)GLU_INSIDE);
   ^~~~~~~~~~~~~~~~~~~~~
   XNQueryOrientation
FXGLCone.cpp:120:3: 错误：‘gluDisk’在此作用域中尚未声明
   gluDisk(quad,0,radius,FXGLCONE_SLICES_NUMBER,FXGLCONE_LOOPS);
   ^~~~~~~
FXGLCone.cpp:120:3: 附注：suggested alternative: ‘glIsList’
   gluDisk(quad,0,radius,FXGLCONE_SLICES_NUMBER,FXGLCONE_LOOPS);
   ^~~~~~~
   glIsList
FXGLCone.cpp:121:3: 错误：‘gluDeleteQuadric’在此作用域中尚未声明
   gluDeleteQuadric(quad);
   ^~~~~~~~~~~~~~~~
FXGLCone.cpp:121:3: 附注：suggested alternative: ‘glDeleteTextures’
   gluDeleteQuadric(quad);
   ^~~~~~~~~~~~~~~~
   glDeleteTextures
make[1]: *** [Makefile:1288：FXGLCone.lo] 错误 1

**Comment by namdre** [comment]
try installing freeglut-devel, mesa-libGL-devel mesa-libGL and make sure that you have the fox devel package (not just fox)
