### ISSUE TITLE
od2Trips

### ISSUE THREAD

**Issue by Consept-Pedro** [eclipse-sumo/sumo#15407]
Good afternoon,

I have SUMO version 1.20.0, Windows-11. I am using the od2trips command. I would like to check if this command only works in the path: C:\Users\"Name"\Sumo. I tried a different way and it didn't work.
Another question is whether there is a practical way to insert the "bus-stop" and "duration" information into bus routes. The way I initially found it was to place the information within each route in the ".rou" file, but for many routes, this practice is quite long.
Thank you in advance for your attention.
Link to download the files: https://we.tl/t-cfbbgYokNy

**Comment by namdre** [comment]
the od2trips executable needs to stay in the SUMO/bin folder but you can call it from any working directory by configuring your PATH settings. See https://sumo.dlr.de/docs/Basics/Basic_Computer_Skills.html#configuring_path_settings

For generating bus routes, see https://sumo.dlr.de/docs/Simulation/Public_Transport.html#importing_public_transport

**Comment by Consept-Pedro** [comment]
Good afternoon!

Thank you very much for the assistance.
It may be something that I'm not developing correctly, but I'm still only able to execute the od2trips and duaroter commands through the sumo folder.
Regarding bus routes, we will create them without the od2trips command and then add them to the sumo.cfg file.
