### ISSUE TITLE
WalkingArea shapes ignored in netconvert

### ISSUE THREAD

**Issue by LuminousLamp** [eclipse-sumo/sumo#15419]
Hi SUMO development team, I am using netconvert for generating a **.net.xml** net file from **plain XML**. In the input .con.xml file I define walking areas and specify their shapes. In the generated .net.xml file however, some of the walking areas do not use the shape I gave, but instead use a shape guessed by default. In other words the specified shapes of some walking areas are ignored.

Below is the screenshot of an example, the walking area in the red box is one whose shape is ignored (the shape I give to this walking area should generally follow the right turn lane).

![img_v3_02ec_3a9657f3-d67f-464b-8f0b-0a2da1755b6h](https://github.com/user-attachments/assets/e8460b95-8ebb-4690-9c4e-5af47343f261)

Is this a bug or are there any additional requirements in specifying custom walking area shape? Thank you a lot for your help!

**SUMO-version:** 1_20_0+1629

**operating system:** Ubuntu 20.04

**Comment by namdre** [comment]
please attach the input files to netconvert as a zip archive

**Comment by LuminousLamp** [comment]
[example-roadnet.zip](https://github.com/user-attachments/files/16841130/example-roadnet.zip)

Here it is. It contains .nod.xml, .edg.xml, .con.xml and .tll.xml as inputs.

Seems that this behavior I mentioned has some kind of randomness. When I generate the network again without modifying any code, another walking area shape is ignored.
![img_v3_02ec_36abc4be-2f95-494c-a872-92afe45f011h](https://github.com/user-attachments/assets/ca561865-ce65-4241-a791-ec429e7531f7)

**Comment by namdre** [comment]
when specifying the edges attribute, all your walkingareas had edge '10' in them which makes their interpretation ambiguous. Having edges attributes of "3", "9", "49", "51" for "node-0" walkingareas makes it work fine.
