### ISSUE TITLE
Regression in sumolib.net.readNet

### ISSUE THREAD

**Issue by neumannje** [eclipse-sumo/sumo#15422]
Commit 297f0d2 introduced a regression for sumolib.net.readNet.

In 1.19,  sumolib.net.readNet accepted pathlib.Path instances for filename 
In 1.20, Path instances causes `TypeError: Argument must be string or unicode.` if `lxml` is present

Reason: 
`xml.sax.parse` accepts `pathlib.Path`
`lxml.etree.iterparse` does not accept `pathlib.Path`  (see https://bugs.launchpad.net/lxml/+bug/1820837) 

Fix:
When entering the `HAVE_LXML`-branch, check for and convert Path-instances to plain strings. 

```python
from pathlib import Path

[...]
def readNet(filename, **others):
  [...]
  if HAVE_LXML and others.get("lxml", True):
     if isinstance(source, Path):
          source = str(source.absolute())
      for event, v in lxml.etree.iterparse(source, events=("start", "end")):
          if event == "start":
              netreader.startElement(v.tag, v.attrib)
          elif event == "end":
              netreader.endElement(v.tag)
```

**Comment by behrisch** [comment]
Just for the record: This is unlikely to affect many people since lxml has fixed this https://github.com/lxml/lxml/pull/337. lxml 4.8 (which is the default on ubuntu 22.04) and later should do this out of the box. But since it is a three-line fix, I included it anyway.
