### ISSUE TITLE
insertionChecks through vehicle.add()

### ISSUE THREAD

**Issue by cherryh2021** [eclipse-sumo/sumo#15420]
Hello,

I am wondering if there is a way that I can disable insertionChecks through vehicle.add(), or add a vehicle type that insertionChecks is disabled? #10740 seems to be targeting to add insertionChecks to vehicle.add(), but 'TypeError: 'insertionChecks' is an invalid keyword argument for vehicle_add()' was thrown when trying to do so (with command `traci.vehicle.add(veh, str(i) + route[0], depart='now', departLane='best', departPos=pos_uniform, departSpeed=0, insertionChecks='none')` 

SUMO version 1.20
Linux

**Comment by namdre** [comment]
As long as #10740 is not implemented, you cannot configure insertionChecks with `vehicle.add`.
However, you can circumvent all insertion checks and force a vehicle into the network by calling 
`vehicle.moveTo` or `vehicle.moveToXY` after `vehicle.add`.
