### ISSUE TITLE
Emergency braking at AllWayStop in subsecond simulation

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15434]
When simulating an All Way Stop intersection (all cars have the same parameters), emergency braking occurs within the junction. Looking at the GUI to find out why, it seems that the cars are very close to each other when they cross, which is why emergency braking occurs. In straight sections, we can specify the minimum distance between cars(parameter "minGap"), but is it possible to specify the distance between cars within a junction?

**Comment by kasop1** [comment]
@khaleel2788 I can not download this file. please  attach this directly.

**Comment by namdre** [comment]
the link suggestion from khaleel2788 is most likely malicious. It did not
come from the SUMO team.

Am Mi., 4. Sept. 2024 um 15:02 Uhr schrieb kasop1 ***@***.***

**Comment by namdre** [comment]
please provide more information on the emergency braking (https://sumo.dlr.de/docs/FAQ.html#how_do_i_report_erroneous_behavior_of_a_sumo_application)

**Comment by kasop1** [comment]
maybe if pararmeter "impatience" of vehicle is negative value, Can I avoid above?

**Comment by kasop1** [comment]
@namdre 
Look at about 608 seconds into the video(below). Cars are approaching the intersection from the north and east entrances. These two cars arrive at almost the same time. However, if you look closely, you will see that the car that entered from the north entrance arrives at the intersection a little earlier (if you look really closely). Therefore, the correct answer is that the car on the north side enters the intersection first, and the car on the east side enters the intersection a little later. Since they are really entering the intersection at the same time as in the video, the car on the east side applies the emergency brakes to avoid a collision. In today's society, the car on the east side would probably wait at the stop line for a little longer, rather than moving forward as in the video.

Also, if you look at where the stop line is, it is actually not at the very end, but 10 cm in front. For example, if the lane is 150 m long, the stop line appears to be at 150 m, but in reality the car stops at the 149.9 m point. Why is there such a difference?


[video.zip](https://github.com/user-attachments/files/16872175/video.zip)

**Comment by kasop1** [comment]
＃15435

**Comment by namdre** [comment]
Instead of a video, please attach the simulation input files (sumocfg, etc)

**Comment by kasop1** [comment]
Understood. 
I will send it tomorrow. 
Would it be effective if I set the impatience parameter to -2 or -3?

**Comment by namdre** [comment]
impatience is unlikely to be involved in the situation you describe. Normally it takes 1-3 minutes of waiting time to have a noticable effect.

**Comment by kasop1** [comment]
I see, even if there are cars crossing, once the waiting time for the stop is over, the car starts to move forward gradually, so the result is that the emergency brake is applied. If it were a human driver, he would not move gradually, but would wait a certain distance. Is this a simulation specification?

**Comment by namdre** [comment]
yes. All files needed to reproduce the situation on my end.

**Comment by kasop1** [comment]
[test.zip](https://github.com/user-attachments/files/16885105/test.zip)
Please check this files. 
I think This problem would likely be solved if the lateral time and distance between vehicles could be specified.

**Comment by kasop1** [comment]
Regarding the above, is this (getMinGapLat) valid?

**Comment by namdre** [comment]
The problem was caused by comparing waiting times of vehicles (to decide who goes first at allway_stop) in an inappropriate manner when a simulation is running with actionStepLength.

**Comment by kasop1** [comment]
Okay, thank you. How can I solve this? Should I wait for a fix for this bug?

**Comment by namdre** [comment]
you can download a fixed version tomorrow at https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots

**Comment by kasop1** [comment]
Same as yesterday. 
Thank you. 
I'm very grateful for your kind response. 

Also, regarding #15435, this may also be a problem caused by a simulation time step of less than 1s. The trend may be similar to this time.

I look forward to your kind reply.
