### ISSUE TITLE
e2_Detectors can only be set shorter than the lane they are on. Can they span multiple lanes?

### ISSUE THREAD

**Issue by lnkird** [eclipse-sumo/sumo#15436]
Detectors are arranged at intersections. Due to the presence of ramps at intersections, the length of the road sections at intersections is relatively short. Is there any way to solve the problem that the queue length may not be covered?

**Comment by namdre** [comment]
yes, see https://sumo.dlr.de/docs/Simulation/Output/Lanearea_Detectors_%28E2%29.html#instantiating_within_the_simulation

In netedit, there is the multiLaneAreaDetector element provided for this purpose.
