### ISSUE TITLE
Set the position of the stop line (minor link)

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15442]
I know two ways to set stop lines (jmStoplineGap, stopOffset).
I want to use jmStoplineGap to set stop lines, but this can only be used for priority or TL junctions. I want to use jmStoplineGap to set the position of stop lines at other junctions, such as All Way stop. 
Could you please improve this?

**Comment by namdre** [comment]
you can also configure this on the network level with `endOffset` (https://sumo.dlr.de/docs/Networks/PlainXML.html#lane-specific_definitions) or do you need this per vehicleType?

**Comment by kasop1** [comment]
Yes, I want to set it for each vtype.

**Comment by namdre** [comment]
jmStopLineGap is intended for situations where the vehicle can expect to drive with priority.
In all other cases, the driver is on a "minor" road and has to find a gap in foe traffic. The current model assumes that drivers will always drive up as far as possible in this situation to simplify finding a gap. A new model parameter should be introduced to make this configurable.

**Comment by namdre** [comment]
Arguably, allway_stop could fall in the first group because the driver receives a window with full priority at some point and so doesn't have to worry about finding a gap.

**Comment by kasop1** [comment]
I look forward to the updates. Thank you so much for your efforts.

**Comment by namdre** [comment]
this won't work for allway_stop in the near future (#15449)
