### ISSUE TITLE
configurable POI size

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#15444]
Currently the width and height parameters only apply if the POI has an image. I would like to use the width parameter for the diameter of the POI but unfortunately the default for width is 1 while the hard coded diameter is 2.6. @namdre Would reducing the default POI size to 1m be okay?

**Comment by namdre** [comment]
I think 1m diameter POIs don't have sufficient visibility.  
We could instead change the default for imgWidth since it's quite unlikely that people were using imgFile with the default width/height values.
