### ISSUE TITLE
invalid approach speed at allway_stop when setting lane-stopOffset 

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#15449]
the current code relies on entering the junction in a single step (because startup resets the waitingTime to 0 and this is checked when deciding who may drive)

https://github.com/eclipse-sumo/sumo/blob/f014b84d3525a4589cdc56db7304494f4ba04db6/src/microsim/MSVehicle.cpp#L2657-L2660

The problem also applies to junction type `priority_stop` and to `traffic_light_right_on_red` (for any connection that requires coming to a stop before passing)

**Comment by namdre** [comment]
this also precludes #15448

**Comment by namdre** [comment]
the same problem applies if the intersection has pedestrian crossings since these impose a safety offset of 1m by default.

**Comment by kasop1** [comment]
Thank you for kind response.

昨日は stop-offset を使用して停止線を変更できましたが、今は変更できないのですか?

**Comment by kasop1** [comment]
Thank you for your kind response.

Yesterday I was able to change the stop line using stop-offset, but now I can't?

**Comment by namdre** [comment]
Nothing changed since yesterday. If you look closely you can find an inappropriate pattern of braking and acceleration between the lane stopOffset and the end of the lane.
