### ISSUE TITLE
How to accelerate the simulation speed of SUMO?

### ISSUE THREAD

**Issue by dongjingao** [eclipse-sumo/sumo#15454]
Add your issue description 
I am conducting a simulation test of a large-scale road network, and it takes about an hour to complete one simulation. Are there any methods to significantly reduce the simulation run time? I have made some attempts, but the results have not been satisfactory.
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
- switch of expensive features (sub-second time resolution, sublane model, ...)
- reduce the amount of routing that happens during simulation
- if your simulation network has more jams than in reality, this may create a huge slowdown in simulation speed. Check for jams and if this is the case, see https://sumo.dlr.de/docs/FAQ.html#the_simulation_has_lots_of_jamsdeadlocks_what_can_i_do
- depending on the accuracy required, you can activate a simplified simulation model by setting option **--mesosim** (see https://sumo.dlr.de/docs/Simulation/Meso.html)
