### ISSUE TITLE
Represent tunnels in SUMO (trac #1545)

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#1545]
Information about tunnels are available e.g. in OSM, but so far they can not display in SUMO. Also bridges ...

This information would be useful when merging two networks and deciding whether two edges have an intersection or not.

Migrated from http://sumo.dlr.de/ticket/1545
```json
{
    "status": "new", 
    "changetime": "2015-01-08T09:21:30Z", 
    "description": "Information about tunnels are available e.g. in OSM, but so far they can not display in SUMO. Also bridges ...\n\nThis information would be useful when merging two networks and deciding whether two edges have an intersection or not.\n", 
    "reporter": "mknocke", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1420708890063820", 
    "component": "simulation gui (GUISIM)", 
    "summary": "Represent tunnels in SUMO", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2015-01-08T08:27:58Z", 
    "milestone": "2.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by fywu85** [comment]
Hey, is it possible to still _simulate_ bridge/tunnel traffic in SUMO 1.0? If so, how to define them in XML?

**Comment by behrisch** [comment]
What exactly do you mean by simulate? While there is already some annotation in the network now, vehicles in SUMO do not behave differently on bridges / in tunnels.

**Comment by fywu85** [comment]
Hey, thanks for the quick response! I meant to ask how to define a bridge or tunnel network in SUMO. For example, how do I draw a diverging diamond intersection with the XML syntax? I could not find any information from the documentation website. If there is already some annotation, could you kindly point me to the relevant url? Thanks!

**Comment by behrisch** [comment]
I thought something like an automatic translation from bridge/tunnel param to elevation level would still be useful?

**Comment by namdre** [comment]
this is done by --osm.layer-elevation and due to the way elevation values need to be smoothed heuristically around the bridge/tunnel i think the current implementation is already the "simplest" solution.

Due to the way bridges/tunnels are rendered in OSM maps, the relationship between bridge/tunnel status and layer information is very reliable.

**Comment by behrisch** [comment]
But that's only true for OSM. My impression was that we want to have that also for netedit and/or dlr-navteq. So the user can label the bridge / tunnel and we do the elevation "right".

**Comment by behrisch** [comment]
No, I don't expect this to be part of the standard model and user defined models may as well read edge params and don't need an edge attribute.
