### ISSUE TITLE
A question about close lane

### ISSUE THREAD

**Issue by pjj-OSM** [eclipse-sumo/sumo#15466]
I want to close a part of lane by specific length but not the whole lane, except that way setting the allow and disallow of vehicle type for lane, Is there any other way to do it ?

![Honeyview_Honeyview_Snipaste_2024-09-11_10-48-18](https://github.com/user-attachments/assets/7291a47b-1124-47c0-9add-d0d2c92a348d)

**Comment by namdre** [comment]
You can define a vehicle of the appropriate length that stops in that location for the desired duration.
