### ISSUE TITLE
using GUI with Libtraci 

### ISSUE THREAD

**Issue by UTTUBALIYAN** [eclipse-sumo/sumo#15462]
I 'm basically working on the sumo eclipse source code in which i want to add new logic for which i want traci library but libtraci is showing me some errors if i'm using the libtraci in the function of the button which i made

**Comment by namdre** [comment]
can you get the libtraci example (https://sumo.dlr.de/docs/Libtraci.html#c) to work with an unmodified version of sumo?

**Comment by UTTUBALIYAN** [comment]
Yeah I get that and I make another file also for this and replicate this code then it runs fine but i want to use libtraci with the functions i made for buttons in that it is not working

**Comment by namdre** [comment]
what is the error message?

**Comment by UTTUBALIYAN** [comment]
So i basically make another test.cpp file in which I'm using that function in which i load the .cfg which i call from that GUIApplicationWindow.cpp file which is giving me this error 

/usr/bin/ld: gui/libgui.a(test.cpp.o): in function `Test::filtering()':
test.cpp:(.text+0x2e0): undefined reference to `libtraci::Simulation::start(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, void*)'
/usr/bin/ld: test.cpp:(.text+0x417): undefined reference to `libtraci::Simulation::step(double)'
/usr/bin/ld: test.cpp:(.text+0x42c): undefined reference to `libtraci::Simulation::getCurrentTime()'
/usr/bin/ld: test.cpp:(.text+0x563): undefined reference to `libtraci::Simulation::close(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/sumo-gui.dir/build.make:161: ../bin/sumo-gui] Error 1
make[1]: *** [CMakeFiles/Makefile2:2411: src/CMakeFiles/sumo-gui.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by namdre** [comment]
Sorry, linker problems in custom code are beyond the scope of help topics here.
