### ISSUE TITLE
[Question] How to find the location of a route easily?

### ISSUE THREAD

**Issue by jamongadejoa28** [eclipse-sumo/sumo#15465]
Is there an easy way to view a path file in the GUI or on Netdit and see where the ID in that path points to? Like finding the text you want with Ctrl + F.

**Comment by namdre** [comment]
You can use the locate menu in sumo-gui and netedit to jump to individual road edges.
Netedit also supports locating a route if you know it's ID.

The shortcut for edges is SHIFT+E.
