### ISSUE TITLE
Traci is always retrying

### ISSUE THREAD

**Issue by MRX2005nzr** [eclipse-sumo/sumo#15487]
<img width="1760" alt="截屏2024-09-14 16 22 34" src="https://github.com/user-attachments/assets/2d52dee1-2fbd-4b19-bf96-3bf62feac107">
<img width="1331" alt="截屏2024-09-14 16 22 50" src="https://github.com/user-attachments/assets/1a924926-a670-4627-9b94-0193720d8d72">
I want to start traci by jupyter then the error is coming. The sumo-gui open and the net.xml file is loaded but just stay here

**Comment by behrisch** [comment]
The message about retrying is just informative and not an error. Especially if you run with GUI, the server is not present at first try but usually the second connection attempt is successful (If not you will see more retries and eventually an error message). To start the simulation you will need to press the green triangle (play) button. Alternatively you can start sumo-gui with the "-S" option and it will start automatically on launch.
