### ISSUE TITLE
Setting expected stop parameter through Traci does not work

### ISSUE THREAD

**Issue by sean-reed** [eclipse-sumo/sumo#15486]
I tried to set the expected parameter of a triggered vehicle stop through Traci:

`traci.vehicle.setStopParameter(vehicle_id, 0, "expected", person_ids)`

where person_ids is a list (space separated as this is the only way I got it to work when defined in XML but I also tried comma separated) of person IDs. However, the vehicle still leaves after the first person arrives instead of waiting until all the persons.

**Comment by sean-reed** [comment]
I attach a minimal example of a vehicle waiting for persons foo and bar before it departs:
[triggered-test.zip](https://github.com/user-attachments/files/16993244/triggered-test.zip)

I think the fix might be as simple as inserting  `stop.initPars(pars);`  below line 1369 in sumo/src/libsumo/Vehicle.cpp

**Comment by namdre** [comment]
Thank you for the clear test case!
