### ISSUE TITLE
Intersection types

### ISSUE THREAD

**Issue by TerzaSlayer2000** [eclipse-sumo/sumo#15497]
Hello Sumo Community, when the intersection is set with the type "priority" and i don't use any traffic lights, what exactly will be the behavior of vehicles and the output that we can observe?
Thank you.

**SUMO-version:** 1.18.0

**operating system:** Windows 11

**Comment by m-kro** [comment]
Vehicles will adhere to the [right-of-way rules](https://sumo.dlr.de/docs/Networks/SUMO_Road_Networks.html#junctions_and_right-of-way) defined for the intersection. This means vehicles coming from certain edges do not need to stop while vehicles at other edges have to let them pass before entering the intersection. If you want some vehicles to violate the right-of-way, you can set this using [junction model parameter](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#junction_model_parameters) **jmIgnoreFoeProb**.

**Comment by namdre** [comment]
for more details, see https://sumo.dlr.de/docs/Networks/PlainXML.html#right-of-way
