### ISSUE TITLE
How to create circle with the help of polygon::add() for libtraci cpp

### ISSUE THREAD

**Issue by UTTUBALIYAN** [eclipse-sumo/sumo#15496]
Hello, basically I'm trying to make a circle for my vehicle suppose i want to make 100 m circle around my vehicle so how can i do that i tried polygon::add() can you tell me for shape what type of parameter should i pass

**Comment by UTTUBALIYAN** [comment]
Actually in passing the parameters only i am facing issue i am facing issue for creating basically circle

**Comment by UTTUBALIYAN** [comment]
I have tried to create the shape because it is of TraCIPositiionvector datatype so i used this
 "MSBaseVehicle* veh = Helper::getVehicle(vehID);

    // Center of the highlight circle
    Position center = veh->getPosition();
    const double l2 = veh->getLength() * 0.5;
    center.sub(cos(veh->getAngle())*l2, sin(veh->getAngle())*l2);
    // Size of the highlight circle
    if (size <= 0) {
        size = veh->getLength() * 0.7;
    }
    // Make polygon shape
    const unsigned int nPoints = 34;
    const PositionVector circlePV = GeomHelper::makeRing(size, size + 1., center, nPoints);
    TraCIPositionVector circle = Helper::makeTraCIPositionVector(circlePV); "
to create the shape for passing in the parameter of polygon::add() but while getVehicle() only it is giving me segmentation fault is i am doing right or should i use different method to make circle

**Comment by behrisch** [comment]
I am not sure you are using libsumo the way it is intended to be used. There should be no need to access the Helper functions. Please try to write your code in Python first if it helps and limit your self to the functions in the libsumo header files.

**Comment by UTTUBALIYAN** [comment]
But i'm working in c++

**Comment by behrisch** [comment]
Please calculate the circle positions yourself like here https://stackoverflow.com/questions/5300938/calculating-the-position-of-points-in-a-circle and add them directly to the TraCIPositionVector. Do not use any functions which are not in the libsumo namespace!
