### ISSUE TITLE
How to load the sumo.cfg file with the help of libtraci

### ISSUE THREAD

**Issue by UTTUBALIYAN** [eclipse-sumo/sumo#15495]
Hello I'm working on the source code of sumo eclipse and I want to only load the file in window of sumo gui ,basically if i am using the start function to load that .cfg file  but how can we do that on the same window.

**Comment by m-kro** [comment]
Did you try [traci.load](https://sumo.dlr.de/pydoc/traci.main.html#-load) ?

**Comment by UTTUBALIYAN** [comment]
Yes, this traci.load() function is giving me segmentation fault basically when i run my executable sumo-gui window gets opened and then when i click to load that file it is giving me segm.. fault with this traci.load() in traci.load() i'm passing the same parameters i.e. the address of the .cfg file

**Comment by UTTUBALIYAN** [comment]
Can you please reply I have used load function in which i am passing the path of the sumo.cfg file but when i am running my simulator it is giving me segmentation fault , so can you tell me what i am doing wrong

**Comment by m-kro** [comment]
Do you have the problem as well with an unmodified version of SUMO?

**Comment by UTTUBALIYAN** [comment]
No Problem with that

**Comment by UTTUBALIYAN** [comment]
So, basically I wanted to make one button kind thing in which if you click then that .cfg file gets load but with the help of libtraci
