### ISSUE TITLE
Fixed distance of Simpla vehicles

### ISSUE THREAD

**Issue by prasuka4** [eclipse-sumo/sumo#15500]
Hi, Is there a way where distance between vehicles in platoon can be fixed at specific distance such as 5m, 8m, 20m etc. than adjusting min and max gap.
Please do let me know

SUMO version - V1_19

**Comment by m-kro** [comment]
Simpla does not change the ordinary car-following models in SUMO but adjusts the vehicle type settings according to the detected situation (follow, catch up, ...). The minimum following distance is a result of the car-following model and influenced by [parameters](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#car-following_model_parameters) such as tau and minGap. So you cannot just set a plain following distance but have to adjust the car-following model parameters.
