### ISSUE TITLE
Add detectPersons to InductionLoop attributes in netedit 

### ISSUE THREAD

**Issue by sean-reed** [eclipse-sumo/sumo#15515]
I couldn't find a way to edit the detectPersons attribute of an InductionLoop within the netedit UI. If it's not currently possible, could it be added to the set of internal attributes please?

Netedit 1.20.0

**Comment by palvarezlopez** [comment]
@sean-reed thanks! I'm going to implement now, and for the daily version of tomorrow will be ready

**Comment by sean-reed** [comment]
Great, thank you!
