### ISSUE TITLE
Duarouter random seed doesn't work with same filename

### ISSUE THREAD

**Issue by xule19970907** [eclipse-sumo/sumo#15523]
```
def run_duarouter(net_xml_file, input_file, output_file, add_xml):
    seed = random.randint(0, 1000000)
    command = [
        'duarouter',
        '-n', net_xml_file,
        '--additional-files', add_xml,
        '--route-files', input_file,
        '--randomize-flows',
        '--output-file', output_file,
        '--seed', str(seed),       
    ]
    try:
        subprocess.run(command, check=True)
        print(f"Generated {output_file} with seed {seed}")
    except subprocess.CalledProcessError as e:
        print(f"Error occurred: {e}")
```
I define the above function, every time  I run it and output (overwrite) on a file with the same name, it brings me the same traffic allocation, it won't change unless I use different file name. But overwrite on a file with same name will result in the same outcomes

```
import subprocess
import random

def run_duarouter(net_xml_file, input_file, output_file, add_xml):
    seed = random.randint(0, 1000000)
    command = [
        'duarouter',
        '-n', net_xml_file,
        '--additional-files', add_xml,
        '--route-files', input_file,
        '--randomize-flows',
        '--output-file', output_file,
        '--seed', str(11),
        '--random',
    ]

    try:
        subprocess.run(command, check=True)
        print(f"Generated {output_file} with seed {seed}")
    except subprocess.CalledProcessError as e:
        print(f"Error occurred: {e}")

if __name__ == '__main__':
    input_file = "E:/深度学习_project/GNN_试验/sumo_stuff/major66/major66_demand.rou.xml"
    output_file = "E:/深度学习_project/GNN_试验/sumo_stuff/major66/random_major66_demand.rou.xml"
    add_xml = "E:/深度学习_project/GNN_试验/sumo_stuff/major66/major66.add.xml"
    net_xml = "E:/深度学习_project/GNN_试验/sumo_stuff/major66/major66.net.xml"

    run_duarouter(net_xml, input_file, output_file, add_xml)
```
**SUMO-version:**
1.19.0
**operating system:**
window 11

**Comment by namdre** [comment]
please check whether the second file (with the same name) has
- an updated timestamp in the file header (`generated by duarouter on ...`)
- a different seed value compared to the previous call

**Comment by xule19970907** [comment]
The timestamp doesn't update (), nor does the seed. However, the second file shows a modified date in Windows, which is strange.

**Comment by namdre** [comment]
Windows can be tricky with overwriting files. (i.e. if the file is open in any application, windows will prevent overwriting in contrast to Linux where overwriting always works).

**Comment by xule19970907** [comment]
I close my Python file that generates the .rou.xml file, then reopen it and run it, and the timestamp updates as expected. However, I need to keep it open to generate the new .rou.xml.
Like ：for i in range(10):
                  run_duarouter(net_xml, input_file, output_file, add_xml)
How can I know whether it has been overwrited?

**Comment by namdre** [comment]
This question is beyond the scope of this issue tracker. Try stackoverflow.

**Comment by xule19970907** [comment]
Thank you very much!

**Comment by xule19970907** [comment]
: )
