### ISSUE TITLE
Convert net.xml to osm

### ISSUE THREAD

**Issue by Sephiroth1118** [eclipse-sumo/sumo#15524]
Recently I'm working on a project that sumo co-simulates with carla. One of the carla function is digital twin tool, that can realize environment procedural generation with OSM file. But it can only be used with OSM. Netconvert doesn't seem to be able to convert net.xml to osm file.

I'm wondering is there any tool that can convert net.xml to an osm? It seems quite difficult because osm's basic logic is different from net.xml and .xodr and osm contains a lot of information rather than just road network.

**Comment by namdre** [comment]
netconvert doesn't support OSM output and probably won't for the foreseeable future.
It may be easier to start with an extract of the OSM database and rebuild everything (including the sumo network) from this.
