### ISSUE TITLE
Can lanes be set with priorities?

### ISSUE THREAD

**Issue by lnkird** [eclipse-sumo/sumo#15528]
At the connection of road sections, all vehicles are taking one lane. Can lanes be set with priorities?

**Comment by namdre** [comment]
No. You could set waypoints to force specific lanes: https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#waypoints

If vehicles all take the same lane it could also be due to strategic preferences (i.e. they all want to be on a turning lane).

**Comment by lnkird** [comment]
Does it need to be set in the initial file? Can you tell me the reason why all vehicles on a multi-lane road section only take the leftmost lane? Thank

**Comment by namdre** [comment]
You can use the vehicle parameter dialog in sumo-gui to check what the vehicles "think" about changing to the other lane. If the reason is "strategic stay" then they deem the lane favorable for continuing their route. Feel free to attach your scenario If you cannot figure it out.

The waypoints could also be set dynamically via TraCI but figuring out the current lane choice should come first.

**Comment by lnkird** [comment]
The road condition is as follows.![1727363029088](https://github.com/user-attachments/assets/e3d65c63-287d-45b6-a9ed-b744f44768e7)

**Comment by namdre** [comment]
there are several things going on here:
- when the number of lanes decreases, some connections will have priority and vehicles will prever the corresponding lanes. A remedy would be a zipper junction (pairs of neighboring lanes can merge with equal priority but you need to cascade multiple such junctions if the number is reduced to less than half of the maximum. See https://sumo.dlr.de/docs/Networks/PlainXML.html#node_types
- the road downstream (outside of the screenshot) could impose further strategic considerations on lane choice
- you can find an example scenario for a toll station with evenly distributed queues in [b6237e1](https://github.com/eclipse-sumo/sumo/commit/b6237e103e3dcb7dfd4d3ad7901b81544085b610) - note, that without the latest development version, the "processing time" of 10s will not work and vehicles will only wait for 1s.
