### ISSUE TITLE
Crash during undo-redo of edited network

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse-sumo/sumo#15534]
The crash is caused because after inverting all elements, the connections was selected. After the undo-redo, Netedit try to select the conections agains, but it doesn't' exist and generates an error in NBEdge::getConnectionRef(int fromLane, const NBEdge* to, int toLane).

Bug found in test \selection\bugs\ticket2948 (but not related with #2948)

**Comment by palvarezlopez** [comment]
Sequence:

1) Create an empty network
2) Create three junctions connected with two edges
3) compute (this create a connection)
4) select all elements inverting (this include the connection)
5) undo all elements
6) recompute (this destroy the selected connection)
7) redo all. When Netedit try to select the connection again, CRASH

**Comment by namdre** [comment]
the crash comes faster if you edit an attribute of the connection and then press undo.
It already occurs as far back as 1.2.0

**Comment by namdre** [comment]
It's not the pretties solution but in light if this being a negligible use case, I find it preferable to putting connections into the undo list every time the user presses F5.
