### ISSUE TITLE
fcdReplay.py-generated POI elements are hidden below edges

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#15546]
Probably because of missing layer information...

**Comment by namdre** [comment]
the default layer for POIs is 202 so they should have always been visible. This is probably related to #15558

**Comment by m-kro** [comment]
Even if libsumo defines a default layer of 0?

https://github.com/eclipse-sumo/sumo/blob/59e7d0903bb46c47e0fca61e9c86f511ce18248a/src/libsumo/POI.h#L66-L68
