### ISSUE TITLE
Adding a Visibility Radius for Ego Car

### ISSUE THREAD

**Issue by Ahmad1441** [eclipse-sumo/sumo#15542]
We at York university developed an open source Co-Simulation of SUMO and Unity which have driver simulator, road assets etc. See below:

https://github.com/SimuTraffX-Lab/SUMO2Unity

To further improve the co-simulation, we need to stop exchanging data from SUMO to Unity for those cars which are out of a visibility radius (e.g., 100 meter) of the ego car. We do not need to show cars which are very far from Ego Car in Unity. An easy solution is to check each cars distance from ego car and hide them; however, this is very resource intensive process. 

We ask if you have any visibility radius function (built-in function) in SUMO so that we can control the number of cars around ego car?

Thanks,

**Comment by m-kro** [comment]
Please look at TraCI [object context subscription](https://sumo.dlr.de/docs/TraCI/Object_Context_Subscription.html). It seems [this has been added](https://github.com/CodingConnected/CodingConnected.Traci/blob/master/CodingConnected.TraCI.NET/Commands/TraCIContextSubscribableCommand.cs) to the .NET / C# client you use.
