### ISSUE TITLE
How to make a arc road

### ISSUE THREAD

**Issue by way-thu** [eclipse-sumo/sumo#15540]
When creating lanes with SUMO, the default roads are straight. Now I want to turn the roads into an arc shape, just like the following picture shows， how can I achieve this?

Straight road:
![image](https://github.com/user-attachments/assets/3c4b3863-5bd3-49cd-a183-524ebd8c8ba7)

Arc road
![image](https://github.com/user-attachments/assets/94bd8e3c-507e-48bd-b1b0-ea8a91ced7f4)

**SUMO-version:1.18.0

**operating system:windows

**Comment by m-kro** [comment]
There is the context option "Smooth Edge" which adds intermediate points (see [docs](https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#making_curved_roads)).

**Comment by palvarezlopez** [comment]
We're going to implement in the next Release ( #15548)
