### ISSUE TITLE
Emission of Pollutants

### ISSUE THREAD

**Issue by TerzaSlayer2000** [eclipse-sumo/sumo#15553]
emission.xml : 

[sample_emission.zip](https://github.com/user-attachments/files/17241533/sample_emission.zip)

Hello Sumo Community, above is my sample emission.xml data till timestep 10 that i have generated for my scenario in sumo, my simulation is set to run for 10000 timesteps which is around 2.7 hrs. Actually i want to calculate the average amount of pollutants released throughout the simulation and i have used a python script to extract data from the emission.xml file to calculate the total amount of pollutants emission throughout the simulation  and below is the output :

Total CO2: 7760123224.28 grams
Total CO: 549483292.13 grams
Total HC: 2337134.90 grams
Total NOx: 23439792.13 grams
Total PMx: 982667.10 grams

The above output is calculated from the emission.xml file and for a simulation of 10000 timesteps and using a python script i found out that there are around 2475 total number of vehicles in the simulation, isn't the above results too much high? I would be very grateful if you kindly provide some suggestion. Thank You.

**SUMO-version:** 1.18.0

**operating system:** Windows 11

**Comment by m-kro** [comment]
Just to be sure: The emission output uses mg/s as unit. Did you take that into account when summing up the numbers?

**Comment by TerzaSlayer2000** [comment]
Okay thanks I will look into it. Btw Sir, in the emission output that is being generated, at every timestep is it the new emission output of a particular pollutant, or it is being sum up from the previous timestep? Meaning if I want to check the emission output of CO2 of a specific vehicle, which data shall I consider? Shall I consider all the emission data at every timestep?

**Comment by m-kro** [comment]
Please look at the [emission output](https://sumo.dlr.de/docs/Simulation/Output/EmissionOutput.html) page in the doc. Each time step entry is self-contained meaning the values are not accumulated over time steps.

**Comment by TerzaSlayer2000** [comment]
Okay Thanks alot.
