### ISSUE TITLE
Rerouting on the last route edge with a stop there fails

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#15552]
Triggers the error `Vehicle X has no valid route from edge 'final' to stop edge 'final'.` The route is checked because a stop is defined on the last edge of the route. However the router looks for connections which obviously do not exist, as there is no self-loop in SUMO.

**Comment by namdre** [comment]
a route between an edge and itself is usually not a problem since the vehicle can leave the edge and return to it via some loop in the network  (unless the edge is a dead-end).

**Comment by m-kro** [comment]
@namdre Yes that's actually the case I meant, see as well the commit message

**Comment by m-kro** [comment]
Reverted the commit as the main problem seems to be with the stop position given by the parkingArea.

**Comment by m-kro** [comment]
The current solution does not take into account vehicles which did not stop in time (already passed by the initial parking position) and still cannot reroute to the edge through a loop. Even though there may be successive edges, they may not lead back to the parking edge.
