### ISSUE TITLE
Sumo Timestep clarification

### ISSUE THREAD

**Issue by TerzaSlayer2000** [eclipse-sumo/sumo#15568]
Hello Sumo community, i want to simulate a scenario in sumo-gui that will correspond to 1 hour of the real life scenario, is it correct to set the timestep to 3600 secs? Does 3600 in sumo means 1 hour in real life? Can you please clarify. Thank You. 

**SUMO-version:** 1.18.0

**operating system:** Windows 11

**Comment by m-kro** [comment]
Short answer: No, the time step is the temporal resolution of the simulation. Still the basic time unit in SUMO are seconds, so 3600 s = 1h. See the docs:
- [time to simulate](https://sumo.dlr.de/docs/Simulation/Basic_Definition.html#defining_the_time_period_to_simulate)
- [time step length](https://sumo.dlr.de/docs/Simulation/Basic_Definition.html#defining_the_time_step_length)

**Comment by TerzaSlayer2000** [comment]
Thank you.
