### ISSUE TITLE
A question about lane choose for vehicle in node with different lane number

### ISSUE THREAD

**Issue by pjj-OSM** [eclipse-sumo/sumo#15577]
In this case, there is a node that fromedge(id is A) with two lanes and toedge(id is B) with three lanes, and the connection is like figure 1.
lane0 in edge A is connect to lane0 and lane1 in edge B, but I found,  the vehicle always choose the right lane(or connection) in simulation.(in this case vehicle always choose connection **lane0 to lane0**, no vehicle use  **lane0 to lane1**,  like figure2 ).
How to solve this problem, or how to set the parameters in laneChangeModel or carFollowModel to improve this problem

**figure 1**
<img width="649" alt="1" src="https://github.com/user-attachments/assets/871c0f5f-b63e-4a90-878b-7db01520fa80">
**figure 2**
<img width="327" alt="2" src="https://github.com/user-attachments/assets/7d72958d-1999-4ccb-a288-783ab3870e9e">

**Comment by m-kro** [comment]
You can influence the lane choice in some ways (see [#13916](https://github.com/eclipse-sumo/sumo/issues/13916). Which settings are most effective depend on your net topology, traffic volume and routes.

**Comment by namdre** [comment]
As soon as there is congestion on the downstream edge you should see multiple queues forming (unless lane 0 carries strategic advantage for following the route - i.e. for a subsequent right-turn).
also related to #7157

**Comment by namdre** [comment]
the latest development version provides a new model parameter to configure the lane choice. See #15579
