### ISSUE TITLE
netconvert:the center of xodr and the center of net.xml

### ISSUE THREAD

**Issue by zlh212** [eclipse-sumo/sumo#15576]
When converting xodr to a net.xml file using netconvert, how is the centrality of the net.xml determined and how does it relate to the parameters in the xodr file?
For example, if I convert data.xodr to a data.net.xml file, why is the center point in the red box？
![11](https://github.com/user-attachments/assets/fbcc4d6e-23cf-4b2e-a9f1-077faf8c2719)

[data.zip](https://github.com/user-attachments/files/17336551/data.zip)

**Comment by namdre** [comment]
netconvert always shifts the network so that the center is at the bottom left (mainly to avoid floating point errors in UTM-projected networks that would have large values otherwise).
To avoid the shift, set option **--offset.disable-normalization** during import
