### ISSUE TITLE
How to assign different meso parameter settings on different edges in the simulation network?

### ISSUE THREAD

**Issue by cherryh2021** [eclipse-sumo/sumo#15578]
Hello SUMO community, 

I am recently working on a research which needs to calibrate the SUMO meso's parameter settings, including
meso-tauff, meso-taufj, meso-taujf, meso-taujj, meso-jam-threshold. Since these parameters have high correlation with the link's capacity, jam density, it is necessary to calibrate on every edge and assign a set of this five parameters combination setting for every edge. And I am wondering if there is a way that can do this.

Thank you!

**Comment by m-kro** [comment]
Please note that the used parameters [depend on the lane number](https://sumo.dlr.de/docs/Simulation/Meso.html#longitudinal_model):

> The headways are scaled according to the inverse of the lane number (with three lanes, the headways are divided by 3).

**Comment by namdre** [comment]
You can assign edge types and load distinct parameters for every type: https://sumo.dlr.de/docs/Simulation/Meso.html#configuration_by_edge_type

**Comment by cherryh2021** [comment]
Thanks, it helps a lot!
