### ISSUE TITLE
Question about station finder

### ISSUE THREAD

**Issue by indieflunk** [eclipse-sumo/sumo#15584]
Hello, I have a question about the station finder: If a taxi is occupied, and the soc of the vehicle reaches the emptythreshold of SOC during the trip. Will the taxi finish the reservation first, or will go to the charging station immediately (and the person will also go to the charging station)?

**Comment by m-kro** [comment]
Currently the stationfinder device makes the vehicle head directly to a charging station and does only interfere with the battery device. I'd assume the vehicle will go to the charging station even with passengers.

**Comment by m-kro** [comment]
See #15586

**Comment by indieflunk** [comment]
> See #15586

Thanks for your answer!
