### ISSUE TITLE
Issue with integrating GTFS data with SUMO OSM

### ISSUE THREAD

**Issue by AimanKhan1997** [eclipse-sumo/sumo#15589]
Hey,

I am trying to simulate the bus networks of Stockholm in SUMO, however facing some issues. I have followed the tutorial and downloaded the dataset and generated route files using
```
python C:/Users/makhan6/AppData/Local/anaconda3/Lib/site-packages/sumo-1.20.0/tools/import/gtfs/gtfs2pt.py -n osm.net.xml.gz --gtfs filtered_gtfs.zip --date 20241008 --osm-routes osm_ptlines.xml --repair --modes bus
```

The first issue I am having is the files generated which are named 
gtfs_pt_vehicles.add.xml, gtfs_pt_stops.add.xml, gtfs_missing.xml and gtfs_repair_errors.txt.

As mentioned in the tutorial, the vehicles should be generated as a route file, however it is generated as additional file in my case.

When I try to call the simulation using 
`sumo-gui -n osm.net.xml.gz --additional gtfs_pt_stops.add.xml --routes gtfs_pt_vehicles.add.xml`, I get the following error in SUMO GUI-
Error: The vehicle type 'bus' for vehicle '14010000664323221.0' is not known.
Quitting (on error).

I am having trouble identifying the issue here. Let me know your suggestions.

Thanks a lot for your time and consideration.

**SUMO-version:**- 1.20.0

Panda version- 2.2.2
Python verson- 3.11.10

Please find attached the zip file of the GTFS and SUMO network. The zip file without network file
[2024-10-02-18-30-45.zip](https://github.com/user-attachments/files/17364098/2024-10-02-18-30-45.zip)
The network file.
[osm.net.xml.gz](https://github.com/user-attachments/files/17364101/osm.net.xml.gz)

**Comment by m-kro** [comment]
You should load your vehicle types file `vtypes.xml` as additional file as well. Actually this is [shown](https://sumo.dlr.de/docs/Tutorials/GTFS.html#routes_from_shortest_path) in the tutorial.

**Comment by m-kro** [comment]
I think this was a mistake in the tutorial. Any vehicle definition created by the GTFS import references a custom vehicle type which has to be defined beforehand.
