### ISSUE TITLE
Vehicle position mismatch while using traci.vehicle.moveTo

### ISSUE THREAD

**Issue by prasuka4** [eclipse-sumo/sumo#15582]
Hi,
I have tried to make vehicle to move from one position to other using "traci.vehicle.moveTo(veh2, lane1, pos1)". But every time when vehicle is trying to move it is moving to start of new edge but not the exact position that is mentioned. Could you please help me in this regard.

Thanks
![image](https://github.com/user-attachments/assets/3be364de-3e40-42ed-a270-776ae2dedd18)

**SUMO-version:**
V1_20
**operating system:**
Windows

**Comment by namdre** [comment]
vehicle.moveTo takes effect before vehicle movements, which means that the final position in that step will be the sum of the moveTo position and the vehicle movement.

**Comment by prasuka4** [comment]
Hi 
Thanks for the response, but if we try to log the previous position and passing it to the vehicle it should ideal move there but here it is trying to move to start of the edge.
Let me know how to proceed with that.

THanks
