### ISSUE TITLE
Regarding right-turning vehicles passing each other at a signalized intersection

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15591]
At a default signalized intersection, when two cars approach each other and both turn right at the same time, why does one of them stop? Is it because there is a risk of a collision? With ALLwaystop, the other car does not stop and both cars can pass through the intersection at the same time.

**Comment by kasop1** [comment]
At a default signalized intersection　→　At a default cross-signal intersection

**Comment by namdre** [comment]
I'm not sure what you mean by "cross-signal". Please post a screenshot or describe the junction type in SUMO terms.
See https://sumo.dlr.de/docs/Networks/PlainXML.html#node_types,
https://sumo.dlr.de/docs/sumo-gui.html#right_of_way

**Comment by kasop1** [comment]
"cross-signal intersection" means 90 degree crossroads.

**Comment by kasop1** [comment]
"cross-signal intersection" means 90 degree cross signal intersection

**Comment by kasop1** [comment]
![image](https://github.com/user-attachments/assets/57017b6c-e0e9-49be-8eb0-9fe88917f43b)

**Comment by namdre** [comment]
In a network with left-hand traffic rules, the cars turning right must potentially yield to other streams of traffic. The distance at which the presence or absence of such cars becomes known can be configured with the connection attribute `visibilityDistance` (default 4.5m). When above that distance, cars will slow down so they can stop if a foe vehicle comes into view.

**Comment by kasop1** [comment]
Thank you. 
Can we assume that there will be no physical collisions between right-turning vehicles at this intersection? I believe the two vehicles are quite close to each other.

**Comment by kasop1** [comment]
![image](https://github.com/user-attachments/assets/7a5816b2-4554-48ab-8641-73bd9451886c)

**Comment by kasop1** [comment]
Thanks, so does that mean that because the collision check does not simulate the real car shape, even if I turn on the junction collision detection option, there may be cases where there is no collision when in fact there is?

**Comment by namdre** [comment]
The rounded geometries aren't circles but rather rectangles with the corners cut off. Hence, you should get a collision report if you see a visual collision. You can also fine-tune the sensitivity for the collision check  with sumo option **--collision.check-junctions.mingap**.

However, if netconvert decided during the build process that two connections aren't in conflict, then no collision checking will be done for those connections even if you set the option. In this case, the netconvert option mentioned above should help.

**Comment by kasop1** [comment]
Thank you. I understand. Just to confirm, are you assuming that the shape of the car is a rectangular prism with rounded corners, as seen in the GUI, and performing collision detection based on that?
But why are you using a rectangular prism with rounded corners? I think that actual cars are rectangular.

**Comment by kasop1** [comment]
Also, I have another question.
--collision.check-junctions.mingap represents the fraction(same as "--collision.mingap-factor") or "minimum distance" of vehicles at an intersection?

**Comment by kasop1** [comment]
> Thank you. I understand. Just to confirm, are you assuming that the shape of the car is a rectangular prism with rounded corners, as seen in the GUI, and performing collision detection based on that? But why are you using a rectangular prism with rounded corners? I think that actual cars are rectangular.

This means that instead of a regular rectangle, the 4 corners of the rectangle were cut off, which may have prevented the collision (the cars nearly collided, but no collision output was generated) which is why the cars are so close to each other in the photo above.

**Comment by namdre** [comment]
The collision-hitbox tries to follow the "simple shape" visualization which is slightly rounded. Also, when looking at a random sample of cars pictured from above, most of them show rounded corners.  The value of **--collision.check-junctions.mingap** is in *m* and unrelated to the `minGap` attribute of the vehicleType.

**Comment by kasop1** [comment]
Thank you for all your detailed answers so far. They have been very helpful. 

Finally, let me ask one more question. 


Why aren't cars shaped like rectangular prisms? I'm really curious. Is there a reason?

**Comment by namdre** [comment]
It's just to have the collision hitbox match the "simple shape".  We were seeing collision warnings for cars that visually did not collide when using rectangles.
