### ISSUE TITLE
How does sumo calculate the exterior nodes of intersection area?

### ISSUE THREAD

**Issue by ZeroHezi** [eclipse-sumo/sumo#15599]
I realized that SUMO is able to calculate the geometry of junction areas, which are not explicitly shown in the junction section of the XODR file.
My question is: How is this calculated—perhaps using an alpha shape algorithm? Are there any clues about the algorithm SUMO uses for calculating exterior nodes?
Thanks in advance for your answer!

**Comment by namdre** [comment]
netconvert takes the points where the incoming/outgoing roads terminate and the *connecting roads* start as the boundary of the junction. These points are extended according to the lane width and combined with some splines to create the outer boundary.
