### ISSUE TITLE
Updated Xerces-C to 3.3.0

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse-sumo/sumo#15593]

**Comment by palvarezlopez** [comment]
Error with Mutex

**Comment by palvarezlopez** [comment]
Updated SUMOLibraries

**Comment by kaustubhharapanahalli** [comment]
Hi @palvarezlopez,

This update is not shown in the documentation for the installation of SUMO 1.20.0 on Mac.

I had to run
```bash
brew install xerces-c
brew tap dlr-ts/sumo
brew reinstall xerces-c
```

to get sumo to work as expected on Mac OS.

My Mac OS version: Version 15.1 (24B83)
Mac Chip: Apple M1 Max

I was not sure where to update this and create a pull request, so thought of addressing in this issue.
