### ISSUE TITLE
routeSampler and add vType

### ISSUE THREAD

**Issue by khzannat** [eclipse-sumo/sumo#15609]
I am using routeSampler to generate trips based on counter data. However, in this tool there is no option to add --additional-files  so that I can add additional vehicle description. I was able to add this for randomTrips but not in the routeSampler. How can I add the vType information using routeSampler?

**Comment by namdre** [comment]
set option **--attributes "vType=\"myType\""** and then load an additional file that contains the respective `<vType id="myType" .../>` when you run sumo. See https://sumo.dlr.de/docs/Tools/Turns.html#vehicle_attributes
