### ISSUE TITLE
getNextLinks traci function cause fatalerror(in traci) and segmentation fault(in libsumo) on Linux

### ISSUE THREAD

**Issue by miracelplus** [eclipse-sumo/sumo#15603]
When running a SUMO simulation using TraCI in Python, the simulation crashes with a `FatalTraCIError` while attempting to retrieve the next links for a vehicle using `traci.vehicle.getNextLinks(veh_id)`. The simulation starts and runs for a while before encountering this error. I have attached the minimum running example to reproduce this error.

[debug_example.zip](https://github.com/user-attachments/files/17397893/debug_example.zip)

Steps to reproduce:
1. Set up a SUMO simulation with at least one vehicle.
2. Use TraCI to start and run the simulation.
3. Attempt to retrieve the next links for a vehicle using `traci.vehicle.getNextLinks(veh_id)`.

Expected behavior: The `getNextLinks()` function should return the next links for the specified vehicle without closing the connection.

Actual behavior: The simulation crashes with a `FatalTraCIError`, indicating that the connection was closed by SUMO.

Error message:
```
Traceback (most recent call last):
  File "/path/to/debug_minimum_example.py", line 47, in <module>
    run_simulation(sumo_cmd)
  File "/path/to/debug_minimum_example.py", line 25, in run_simulation
    next_links = traci.vehicle.getNextLinks(veh_id)
  File "/path/to/traci/_vehicle.py", line 808, in getNextLinks
    return self._getUniversal(tc.VAR_NEXT_LINKS, vehID)
  File "/path/to/traci/domain.py", line 149, in _getUniversal
    return _parse(self._retValFunc, varID, self._getCmd(varID, objectID, format, *values))
  File "/path/to/traci/domain.py", line 154, in _getCmd
    r = self._connection._sendCmd(self._cmdGetID, varID, objID, format, *values)
  File "/path/to/traci/connection.py", line 232, in _sendCmd
    return self._sendExact()
  File "/path/to/traci/connection.py", line 137, in _sendExact
    raise FatalTraCIError("Connection closed by SUMO.")
traci.exceptions.FatalTraCIError: Connection closed by SUMO.
```

*If possible, upload an example that shows your problem.*

**SUMO-version:** 1.21.0

**operating system:** Ubuntu 22.04

**Comment by miracelplus** [comment]
[debug_example.zip](https://github.com/user-attachments/files/17397886/debug_example.zip)

**Comment by namdre** [comment]
regression in 1.21.1 via  616e1e8

**Comment by namdre** [comment]
happens at junction types allway_stop and priority_stop (so hopefully doesn't affect too many people)

**Comment by namdre** [comment]
also affects `traci.lane.getLinks` if its incoming to an allway_stop or priority_stop
