### ISSUE TITLE
Appearance of Lanearea detector (e2 detector)?

### ISSUE THREAD

**Issue by dawn-fm** [eclipse-sumo/sumo#15612]
Hi,

I wonder if I can indicate a border of each e2 detector.

In below attached figure, my custom road network example, I added e2 detectors with an interval of 20m. (Line with light blue color is all the detectors.)

However, I want to make SUMO clarify the boundary of adjacent detectors at a glance and I want to add a border of detectors.

Is there any methods to do so?

Thank you!

*If possible, upload an example that shows your problem.*
![image](https://github.com/user-attachments/assets/ce7d2434-3590-473e-8589-18c49ad376de)

**SUMO-version:**
1.21.0

**operating system:**
Ubuntu 22.04 (on WSL 2)

**Comment by m-kro** [comment]
There isn't any option to change the detector appearance as you want to it to be.

**Comment by namdre** [comment]
for debugging correct positioning, the best approach is to load fewer detectors at a time.
If you are confident in correctness and need to provide more information in sumo-gui, you can define and load additional polygons: https://sumo.dlr.de/docs/Simulation/Shapes.html

**Comment by bonchoe** [comment]
@m-kro @namdre Thank you for quick response! I think I should consider adding polygons or give up the border 🥲

**Comment by dawn-fm** [comment]
@m-kro @namdre Thank you for quick response! I think I should consider
adding polygons or give up the border 🥲

2024년 10월 18일 (금) 오후 8:49, Jakob Erdmann ***@***.***>님이 작성:
