### ISSUE TITLE
Screen flickering

### ISSUE THREAD

**Issue by AndiLeni** [eclipse-sumo/sumo#15615]
On my laptop, all gui windows of sumo seem to flicker when they are larger than a specific size.
The issue can NOT be recorded via screenshots of window recording tools and only appears on my laptop screen and not on connected displays. 
The window "splits" in multiple parts when a ui update is triggered, f.e. when scrolling, clicking buttons, running simulations or resizing the window.

The same issue appears in netedit as well.

https://github.com/user-attachments/assets/a5fc6485-9959-46f8-9061-a6fc93997e1c

**SUMO-version:** 1.21

**operating system:** Windows 10

Kind regards
Andreas

**Comment by m-kro** [comment]
Please check your Windows screen scaling settings (see [FAQ](https://sumo.dlr.de/docs/FAQ.html#sumo-gui_and_netedit_flickering)).

**Comment by AndiLeni** [comment]
If ayone has the same issue and needs help to make these changes there are two ways.

**1. Nvidia Control panel installed**

Add sumo-gui.exe to the program settings and change the used graphics card to "integrated".

![912](https://github.com/user-attachments/assets/d228ff77-7768-4626-a98c-b8fe3421e56d)

**2. Use windows settings**

Open Settings App > Screen > Graphics settings.
Add sumo-gui.exe and change the power mode to use the inetgrated graphics card.

![911](https://github.com/user-attachments/assets/65c1ea87-bb23-45cb-ba25-251e7458cf26)
![913](https://github.com/user-attachments/assets/7687829a-2925-4fb6-9b11-6dd6f183f33c)
