### ISSUE TITLE
configure Pedestrian congestion behavior

### ISSUE THREAD

**Issue by way-thu** [eclipse-sumo/sumo#15610]
When pedestrian density is too high, congestion can occur at intersections, causing pedestrians to be unable to move. What are some good methods to ensure pedestrians can continue moving normally, unaffected by density and other factors?

![image](https://github.com/user-attachments/assets/11da5457-f261-4dcd-afd9-372030bb27ef)

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
The easiest fix is to switch to the non-interacting model with option **--pedestrian.model nonInteracting**

**Comment by way-thu** [comment]
I tried this method, but after changing to the nonInteracting model, pedestrians do not move according to the original OD matrix (in my scenario, this means they are not using the crosswalks to cross at intersections).

**Comment by namdre** [comment]
At the moment, congested pedestrian speed is hard-coded to 25% of their default speed. This should be made configurable.

Together with the existing options **--pedestrian.striping.jamtime** and **--pedestrian.striping.jamtime-crossing**, it should be possible to fine-tune (or disable) any density specific effects while making full use of pedestrian infrastructure
