### ISSUE TITLE
pedestrian jaywalking behavior

### ISSUE THREAD

**Issue by way-thu** [eclipse-sumo/sumo#15611]
I want to know how to simulate jaywalking for pedestrians. I tried using the .person.moveToXY function, But from what I observed in the GUI, it seems that the pedestrian is directly mapped to the specified position, instead of walking across the crosswalk. 
I would like to know if there is a way to simulate jaywalking behavior as it occurs in reality.  
Thanks for your help.

**SUMO-version:1.18.0

**operating system:windows

**Comment by namdre** [comment]
if you want to achieve walking on red or walking with disregard to vehicle traffic declare vType for the person with `jmDriveAfterRedTime` or
 `mIgnoreFoeProb` and  `jmIgnoreFoeSpeed`
(see https://sumo.dlr.de/docs/Simulation/Safety.html#junction_model)

Crossing the speed at arbitrary places works only by calling moveToXY in every simulation step (your own process assumes full control while crossing the street).
