### ISSUE TITLE
adding more geometry types in polyconvert

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse-sumo/sumo#15621]
Some geometry types are not considered in polyconvert yet. The respective shape information cannot be properly extracted. 

**SUMO-version:**
V1_21_0+0044-84cccc6c05f
**operating system:**
Windows

**Comment by yunpangfloetteroed** [comment]
An example data set is put in S:\Sumo\Bugreports\15621_add_geometry_type

**Comment by behrisch** [comment]
The test has been added to the internal repo
