### ISSUE TITLE
Positive vs. negative offset when converting coordinates to UTM

### ISSUE THREAD

**Issue by m-kro** [eclipse-sumo/sumo#15624]
The offset stored in the net file is used in **tracemapper.py** via **sumolib.net** to project trace input from geographic coordinates to UTM. UTM offset / UTM coordinates usually have positive values (easting/northing) but are added to the projection result instead of being subtracted. This leads to wrong results. The tracemapper test works with manually patched network data with negative offset.

Would be better to catch this automatically instead of relying on negative offset in the network file...?!

**Comment by namdre** [comment]
the offset is always negative in an UTM projected network. There is nothing patched about this.

**Comment by m-kro** [comment]
Maybe this is specific to OpenDrive. Our test files currently do not cover the XODR offset tag.

**Comment by namdre** [comment]
opendrive has reversed semantics for the offset sign compared to .net.xml (see image at https://releases.asam.net/OpenDRIVE/1.6.0/ASAM_OpenDRIVE_BS_V1-6-0.html#_georeferencing_in_opendrive).  
Whereas net.xml stores the value that shifts from projected coordinate to network coordinate, opendrive encodes the reverse shift.
