### ISSUE TITLE
Issues with Multiple Calibrators in SUMO for Market Penetration Simulation

### ISSUE THREAD

**Issue by Mujeebabiola** [eclipse-sumo/sumo#15632]
Hi everyone,

I'm working on a simulation to test the sensitivity of the market penetration rate of autonomous vehicles. My XML files are updated using Python, and I'm using two calibrators for different vehicle types (CAVs and HDVs). However, I’m encountering issues when using two calibrators together — it seems they don’t work well with each other (I’m relatively new to SUMO).

The reason I used calibrators is that my regular simulation doesn’t finish within an hour, making it difficult to collect data at specified intervals. below is snippet of my code : 

`<additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">
    
    <vType id="CAV" carFollowModel="IDM" tau="0.6" />
    <vType id="HDV" carFollowModel="W99" cc1="1.0" cc2="10.0" cc3="-12.66" cc4="-0.10" cc5="0.20" cc6="4.0" cc7="0.1" cc8="2.1" cc9="0.5" />
    
    <route id="r_0" edges="E0 E0.1000 E0.1400" />
    

    
    <calibrator id="ca_1" edge="E0" pos="0.00">
        <flow type="CAV" begin="0.00" color="green" end="3600.00" route="r_0" departLane="random" vehsPerHour="7802" />
    </calibrator>

    <calibrator id="ca_0" edge="E0" pos="0.00">
    <flow type="HDV" begin="0.00" color="red" end="3600.00" route="r_0" departLane="random" vehsPerHour="7802" />
    </calibrator> 
    
    
    <inductionLoop id="e1_0" lane="E0.1000_2" pos="400.00" period="300.00" file="e1_0.xml" />
    <inductionLoop id="e1_1" lane="E0.1000_1" pos="400.00" period="300.00" file="e1_1.xml" />
    <inductionLoop id="e1_3" lane="E0.1000_0" pos="400.00" period="300.00" file="e1_3.xml" />
    <inductionLoop id="e1_4" lane="E0_0" pos="200.00" period="300.00" file="e1_4.xml" />
</additional>`

I’d appreciate any guidance on how to make both calibrators work together or suggestions on alternative approaches.

Thank you for your time!

**Comment by m-kro** [comment]
The documentation of [calibrators](https://sumo.dlr.de/docs/Simulation/Calibrator.html) doesn't mention it explicitly, but one may get it looking at the examples: Calibrators work with time intervals and and edge level. This means defining multiple flow elements with overlapping time intervals for the same edge will not work as expected. The vehicle type in the `flow` element is used to generate new vehicles of that kind in case less vehicles than indicated pass by.

**Comment by namdre** [comment]
side note: several outputs permit writing of unfinished vehicles or writing at specified time intervals so it may be feasible to set a hard simulation end with option **--end** and still obtain the desired outputs.
