### ISSUE TITLE
Sumo Graphical Interface - Edit coloring scheme - Street - byLiveEdgeData stopped working

### ISSUE THREAD

**Issue by TahxeolT** [eclipse-sumo/sumo#15637]
My goal was to create a heatmap of my simulation. To do that, I used 'Edit coloring scheme - Street - byLiveEdgeData' -> entered to have SUMO collect data for each edge as it was entered. However, at one point (to try to save time), I tried to save the setting in my registry. Since then, the entire map is permanently in NoData regarding edges if I use this mode, and 'byLiveEdgeData' present an empty array of choice, so I can't do it again

I tried restarting my computer, using other maps...

![Capture d’écran 2024-10-25 141541](https://github.com/user-attachments/assets/4fc2b108-cd8f-438f-a10b-30ba53fb182a)
![Capture d’écran 2024-10-25 141622](https://github.com/user-attachments/assets/fe53c480-490e-4db8-8404-614a8fb73050)

**SUMO-version:**
1.2.0

**operating system:**
Windows

**Comment by m-kro** [comment]
On my side the drop-down elements are populated when I close the dialog once and reopen it. Nevertheless it should be done immediately and is considered a bug...

**Comment by TahxeolT** [comment]
Potentially related: Using this button cause SUMO to crash
![Capture d’écran 2024-10-25 155700](https://github.com/user-attachments/assets/cc7c303a-3814-49ba-9970-5aa878b01038)

**Comment by m-kro** [comment]
@TahxeolT Is your SUMO version really 1.2.0? Then please update to the latest release to see if it happens there as well. I wasn't able to reproduce the crash.

**Comment by namdre** [comment]
You can download a fixed version tomorrow at https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots
As a work-around, you can also change the settings scheme without opening the settings dialog (the settings scheme selector is also part of the main application window). In this case, all the ui elements will be available once you open the settings dialog for the first time.
