### ISSUE TITLE
MacOS environment depends on xerces-c version issue

### ISSUE THREAD

**Issue by TransTony** [eclipse-sumo/sumo#15638]
Hello fellows,
Recently, I am installing SUMO on my MacBook laptop. I found that the lastest version of SUMO  (e.g. 1.20) still depends on xerces-c 3.2 ( a package from brew ). However, brew installs xerces-c 3.3 defaultly. This creates some unconvinience, since the SUMO can not accept such a new version of package. 

**SUMO-version:1.20**

**operating system:MacOS**

**Comment by ulrivo** [comment]
I have the same problem

`Library not loaded: /opt/homebrew/opt/xerces-c/lib/libxerces-c-3.2.dylib`

` Referenced from: <AD6DC055-F4A6-3145-B9E8-B2FC0500B254> /opt/homebrew/Cellar/sumo/1.20.0/bin/sumo-gui
`

There is installed

`/opt/homebrew/Cellar/xerces-c/3.3.0`

**Comment by ulrivo** [comment]
I could solve the problem for me with

` brew reinstall --build-from-source sumo`

**Comment by TransTony** [comment]
Thanks, I also solve this problem in this way.
