### ISSUE TITLE
colliding before the stop line

### ISSUE THREAD

**Issue by zlh212** [eclipse-sumo/sumo#15634]
Vehicle always change lanes before the stop line, and collide with other vehicles, how to avoid or optimize？
![微信图片_20241025110242](https://github.com/user-attachments/assets/4d8e71c0-630e-42de-9137-17a76a4b05b0)

**Comment by m-kro** [comment]
Do you use the option **--lanechange.duration**? I believe there was a problem which hasn't been fixed yet...

**Comment by zlh212** [comment]
Yes, I did.
![image](https://github.com/user-attachments/assets/d227195a-85bc-4c6d-bb9d-5c3cfc0124ed)
Because I want the lane change process

**Comment by m-kro** [comment]
Possible duplicate of #13926.

**Comment by zlh212** [comment]
Can "lcStrategic" optimize this problem?

**Comment by RobertHilbrich** [comment]
No, it cannot
