### ISSUE TITLE
stop to brake

### ISSUE THREAD

**Issue by PJiang521** [eclipse-sumo/sumo#15633]
Add your issue description here.
I put constraints on the exit and when the exit condition is not met ，it stops at the end of the road, but I get a stop to brake error
*If possible, upload an example that shows your problem.*
```
def outcar1():#
    roadlength=1500
    jihe=traci.vehicle.getIDList()#
    for carID in traci.vehicle.getIDList():
        if traci.vehicle.getLaneID(carID)=='E0_1':
            if carID==jihe[0]:
                if traci.vehicle.getLanePosition(carID)+traci.vehicle.getSpeed(carID)>roadlength:
                       if random.random()>pout:
                        traci.vehicle.setStop(carID,'E0',pos=roadlength,laneIndex=1,duration=1)
```
**SUMO-version:**

**operating system:**

**Comment by m-kro** [comment]
I suspect the vehicle is not able to come to a standstill within at most one second. Still that is what your condition checks (`traci.vehicle.getSpeed` returns speed in meters per second). You can use `traci.vehicle.getSecureGap(carID, 0, 0)` ([ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getSecureGap)) to request the minimum braking distance.
