### ISSUE TITLE
Bashism in CMakeLists.txt while invoking doxygen

### ISSUE THREAD

**Issue by sanvila** [eclipse-sumo/sumo#15645]
Hello. CMakeLists.txt has a line like this:

`COMMAND doxygen sumo.doxyconf &> doxygen.log`

but that's bash-specific and works differently when /bin/sh is a minimal POSIX shell, as it happens in Debian. In particular, the Debian package failed to build from source in some cases because of that:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1082135

We have changed the line to this, which works with both bash and sh:

`COMMAND doxygen sumo.doxyconf > doxygen.log 2>&1`

Thanks.

**Comment by behrisch** [comment]
@sanvila  Thanks for reporting!
