### ISSUE TITLE
Intersection turn right during red light logic, how it works

### ISSUE THREAD

**Issue by zhengli-hub** [eclipse-sumo/sumo#15646]
Add your issue description here.
I'm working on accurately modeling right-turn-on-red behavior in SUMO traffic simulation, with the goal of calibrating the simulation to match observed trajectory data. The basic vehicle behavior should follow this sequence: approach intersection, brake to stop, verify safety conditions, then accelerate to complete the right turn. I have two specific questions:

How can I modify the vehicle's stopping position relative to the stop line during a red light? Currently, SUMO vehicles consistently stop very close to the stop line, but I need more control over this distance.
What determines the duration of the stop before the vehicle proceeds with the right turn? I'm interested in understanding and potentially modifying the logic that governs this waiting period.

I understand these modifications might be challenging to implement through standard simulation parameters or the TraCI interface. I'm open to making changes directly in the source code and recompiling SUMO if necessary. Any guidance on either the configuration approach or the relevant sections of source code would be helpful.
*If possible, upload an example that shows your problem.*

**SUMO-version:**
SUMO 1.20.0
**operating system:**
Windows

**Comment by m-kro** [comment]
You can set the [jmStoplineGap parameter](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#junction_model_parameters) in the vehicle type for altering the distance to the stop line.  Use the [jmStopSignWait parameter](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#junction_model_parameters) for the stopping duration.

**Comment by namdre** [comment]
`jmStopLineGap` currently doesn't work for connections where a minimum duration of stopping is required (#15448, #15449)

**Comment by zhengli-hub** [comment]
I really appreciate your timely response!
Yeah, I tried to change [jmStoplineGap](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#junction_model_parameters) and [jmStopSignWait](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#junction_model_parameters). But they do not work from my observation. I read previous discussion about jm parameters. They can only be changed by the vtype input file. Following are my vtype input file and code to add vehicle in simulation:
<img width="885" alt="image" src="https://github.com/user-attachments/assets/e6848374-fc44-4424-85c2-fb5be2d8420a">
<img width="509" alt="image" src="https://github.com/user-attachments/assets/2c23ef93-b5f0-4403-aa99-e8b6440c5a85">
Not only jmStoplineGap and jmStopSignWait, all other jm parameters defined in vtype input file do not work for me. Could you please let me know any incorrect definitation in my code. Thank you so much for your kindly help!

**Comment by namdre** [comment]
- jmStopLineGap is ignored for some junction types (try with a normal priority or traffic_light junction)
- jmStopSignWait is not implemented in version 1.20.0. You need 1.21.0 for this
- you can set jm params with `traci.vehicletype.setParameter("junctionModel.jmStopLineGap", "3")`

**Comment by wnederpel** [comment]
Might #15939 be related? Are your problems resolved @zhengli-hub? When vehicles are not respecting the stop light they also do not respond to the junction model stop parameters.
