### ISSUE TITLE
Intersection turn left during green light with conflict vehicle logic

### ISSUE THREAD

**Issue by zhengli-hub** [eclipse-sumo/sumo#15651]
Add your issue description here.
I'm working on accurately simulating left-turn behavior in SUMO. Here's the difference between the real-world behavior and my simulation:
Ground truth behavior:
<img width="982" alt="1" src="https://github.com/user-attachments/assets/8bdb0aff-5403-460b-a0ee-fc5a43ac0fd8">
<img width="953" alt="2" src="https://github.com/user-attachments/assets/50ad43c3-00f2-4381-8a10-49eb162f5f7f">
<img width="988" alt="3" src="https://github.com/user-attachments/assets/12404f14-6bc0-4e40-b9c7-41342c4afe00">
The left-turning vehicle (red) comes to a complete stop before the intersection. It waits until the conflicting right-turning vehicle (blue) completely exits the intersection. Only then does it begin its left turn

Current SUMO simulation behavior from my observation:
<img width="583" alt="11" src="https://github.com/user-attachments/assets/949fcbc3-1c6f-4c61-84e6-f5ddafb998e0">
<img width="779" alt="22" src="https://github.com/user-attachments/assets/45cb47f2-776b-4ddd-adbb-c89b035e97b2">
<img width="683" alt="33" src="https://github.com/user-attachments/assets/9a4a0f57-b0d1-4586-bdd7-aace0f299e22">
The left-turning vehicle creeps into the intersection. It follows closely behind the right-turning vehicle. It doesn't exhibit the proper stopping behavior

I'd like to understand: Which parameters can I adjust to match the real-world behavior? I tried using the 'jmTimegapMinor' parameter since it seemed relevant, but it didn't produce the desired effect. Are there other parameters I should consider?
*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.20.0
**operating system:**
Windows

**Comment by namdre** [comment]
There are two model features at play here:
1. waiting inside the intersection (https://sumo.dlr.de/docs/Simulation/Intersections.html#waiting_within_the_intersection). This is a network level feature and can be disabled by setting connection attribute `contPos="0"`.
2. smoothly following a a foe that is still on the intersection.  The value of `jmTimeGapMinor` is only applied for conflict checking when the foe vehicle is still outside the intersection. Thus it has no impact on the observed behavior. Instead, this merging situation  is governed by the default car-following behavior.  For a detailed discussion see, #15654

**Comment by zhengli-hub** [comment]
I've been experimenting with the parameters 'jmAdvance' and 'jmExtraGap', but I haven't achieved the desired behavior yet. Upon reviewing the source code, we noticed a parameter called 'myFoeVisibilityDistance' that might help address our needs. Would you be able to advise if it's possible to modify or calibrate this visibility distance parameter? We really appreciate your continuous support and help!

**Comment by namdre** [comment]
Unfortunately, your screenshot cuts of the version number so I'm not sure whether you are using the version that contains the #15654 enhancements. You need version v1_21_0-526 or later.
Also, the `jmExtraGap` is only evaluated as long as the foe vehicle is still on the intersection. Afterwards, normal car-following rules apply (minGap and tau).

The value of `myFoeVisibilityDistance` only affects situations where there is no foe vehicle. It controls the point at which the ego vehicle has full visibility and becomes aware of the fact that no foe is present. While the ego distance to the stop line is larger than myFoeVisibilityDistance it must retain the possibility to safely stop at the stop line.

**Comment by zhengli-hub** [comment]
<img width="805" alt="image" src="https://github.com/user-attachments/assets/eb2ae962-3328-4aa7-8f96-e00c4cd000dd">
I think I am using the version v1_21_0-533. And the red vehicle is also so close to the foe vehicle in the intersection. It seems like jmExtraGap not works for me.

**Comment by namdre** [comment]
please attach the scenario from that screenshot.

**Comment by zhengli-hub** [comment]
Dear SUMO developers,

After about a year, I’ve run into this issue again with the same example. I’m studying a signalized-intersection scenario where a left-turning vehicle (red) conflicts with a right-turning vehicle (purple). My goal is to enlarge the gap between the left-turner and the right-turner inside the intersection.

Following the solution you previously suggested, I set jmExtraGap to 50 (I know this is unrealistic; I just want to test whether the parameter works). I also set minGap to 1.

<img width="1542" height="1542" alt="Image" src="https://github.com/user-attachments/assets/8bf491f5-ba1e-44b1-a939-359de33d5d65" />

Expectation: the left-turning vehicle should wait a long time within the junction and only proceed once the right-turning vehicle is far ahead.
Observation: the left-turning vehicle follows the right-turning vehicle very closely. It looks as if jmExtraGap has no effect in my simulation.

Could you advise what might be wrong here (or whether I’m misunderstanding how jmExtraGap applies in this conflict)? I’m on Linux and using the latest build available from GitHub: v1_24_0+0808.

Thank you very much for your time and help!

<img width="6144" height="3456" alt="Image" src="https://github.com/user-attachments/assets/79374210-744c-4e6a-9981-688c172093c6" />
<img width="6144" height="3456" alt="Image" src="https://github.com/user-attachments/assets/f7379b1c-6cbc-46e1-a644-7fd26ca5a157" />
<img width="6144" height="3456" alt="Image" src="https://github.com/user-attachments/assets/45973534-fddf-4f8e-8d62-7a6b99b99a55" />
<img width="6144" height="3456" alt="Image" src="https://github.com/user-attachments/assets/5ca68ed2-504a-4649-918c-6a49cfd5d595" />
