### ISSUE TITLE
lcContRight not work

### ISSUE THREAD

**Issue by zlh212** [eclipse-sumo/sumo#15657]
I added ”lcContRight“ to the vehicle type,but it didn't seem to work.
![微信截图_20241101120109](https://github.com/user-attachments/assets/b4eb6dfe-ca6e-474a-b488-a1c8affc740e)
![微信截图_20241101120136](https://github.com/user-attachments/assets/e4c655ae-1c1a-4744-83d2-78fab0f3a11f)

**Comment by zlh212** [comment]
Another problem that vehicles generated on the left tend to go straight through the two lanes marked by green arrow, rather than the road marked by red arrow
![微信截图_20241101121626](https://github.com/user-attachments/assets/445f7c72-a945-4752-815d-c2ac1cfb442c)
![微信截图_20241101121842](https://github.com/user-attachments/assets/eafff54c-6a01-4b4b-89c1-6c621cde5033)

**Comment by m-kro** [comment]
The parameter `lcContRight` has been introduced only recently. You can try it within the current [development version](https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version).
