### ISSUE TITLE
Emission calculation for parked vehicles

### ISSUE THREAD

**Issue by oshadajay** [eclipse-sumo/sumo#15652]
Hi, I have gone through the documentation for emissions (https://sumo.dlr.de/docs/Models/Emissions.html) and found out that it is assumed that the engine will go off if the stop duration is more than 300 seconds in a foreseeable stop like a jam or a junction. Could you please explain a bit more what a foreseeable stop is? And how would this work with parking which is a scheduled stop? I assume at a parking area the engine will be switched off immediately. But are there any parameters associated with it? Thank you so much. 

**SUMO-version:**
1.20

**operating system:**
Windows

**Comment by namdre** [comment]
a "foreseeable" (also "planned") stop is something defined with a `<stop>` element or `traci.setStop`.
Even at a parkingArea, the engine will only be switched of if the planned duration is above the configured threshold.

**Comment by oshadajay** [comment]
@namdre Thank you so much. Could you also please let me know where I should configure the `shutOffStopDuration` parameter? I could not find it under the parameters of vtype (https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html).

**Comment by namdre** [comment]
please refer to the updated documentation at https://sumo.dlr.de/docs/Models/Emissions.html#standing_vehicles

**Comment by oshadajay** [comment]
@namdre clear as crystal. Thank you so much!
