### ISSUE TITLE
About vehicle right-of-way

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15672]
I am running a simulation at an intersection where trams and cars are mixed. I have a few questions. 

1. What is the priority between trams and cars? Which has priority? 
2. I want to simulate cars passing in front of trams ignoring the priority. How can I do this? 

Thanks in advance.

**Comment by m-kro** [comment]
Right-of-way is determined at infrastructure level. So if vehicles of different vehicle classes use the same incoming lane, it doesn't matter of which vehicle class the vehicle is. Do you intend with "mixed" using the same lanes?

**Comment by kasop1** [comment]
![image](https://github.com/user-attachments/assets/5c988b4b-4975-4bc4-b466-772bf0ea350a)

**Comment by kasop1** [comment]
Consider an intersection like this with a tram (going straight) and a car (turning right) coming from the east. In my simulation, the car will cut off the tram, forcing it to turn right first. But even if I give it the command using traci, it will still wait for the tram to pass.

**Comment by kasop1** [comment]
Or I have a car turning right from the east and a streetcar going straight from the west, and I want the car to block the streetcar and make the right turn first, but currently no matter what commands I issue with Traci, the car will not pass in front of the streetcar to make the right turn.

**Comment by m-kro** [comment]
Additionally, if you want to influence the right-of-way rules persistently for a given combination of conflicting edges, you can choose the **edgePriority** computation mode of right-of-way (see [doc](https://sumo.dlr.de/docs/Networks/PlainXML.html#right-of-way)). Then set a higher value for the attribute **priority** of the incoming edge the vehicles should drive first.

**Comment by kasop1** [comment]
I set parameters such as jmIgnoreFoeProb but it didn't work. Why? How is it different from the content of the above URL?

**Comment by m-kro** [comment]
Did you set **jmIgnoreFoeSpeed** and **jmIgnoreJunctionFoeProb** as well? Setting **jmIgnoreFoeProb** alone will do nothing because it is applied exclusively where vehicles drive less than **jmIgnoreFoeSpeed** (0 by default).

**Comment by kasop1** [comment]
I set both, and the speed is set to high, so why doesn't it work?

**Comment by kasop1** [comment]
In fact, I get a map from OSM, make it into a net file, and use it. Does anything unexpected happen when I do this?

**Comment by m-kro** [comment]
Well in some case the imported OSM intersections represent only parts of the whole intersection and work better when cleaned/joined together. Difficult to say without knowing the place / the OSM ID of some net element.

Here you can [download our test examples](https://sumo.dlr.de/extractTest.php?path=sumo/junction_model/ignoreRightOfWay) regarding the **jmIgnoreJunctionFoeProb** settings. If you think everything is right on your side, you may attach as well a small failing example we can look at.

**Comment by namdre** [comment]
Instead of ignoring all foes with some probability (jmIgnoreFoeProb, jmIgnoreJunctionFoeProb), you can ignore specific foes by their ID or vType independent of the speed: 
https://sumo.dlr.de/extractTest.php?path=sumo/junction_model/ignoreID/EW_ignores
https://sumo.dlr.de/extractTest.php?path=sumo/junction_model/ignoreType/EW_ignores

**Comment by kasop1** [comment]
If I set the probability of ignoring enemy vehicles to 1 in the parameters, it should run 100% but why does it still not work?

**Comment by kasop1** [comment]
I would like to post an example here for you to see, but unfortunately I cannot do so due to regulations. Sorry.

**Comment by namdre** [comment]
If you cannot post your own examples, please use our examples and modify them until they reflect your problem.

**Comment by m-kro** [comment]
@kasop1 Do you have an example for us where it does not work? Doesn't need to be the one you are actually working on, but where we can see the problem happening...

**Comment by kasop1** [comment]
Sorry for the delay in getting back to you. 
After a lot of testing over the last few days, I found that the problem I asked about is not caused by what I wrote above, but by the Keepclear mode not being set to “false”. 

Thank you very much.
