### ISSUE TITLE
fcd-output: optionally write meso properties

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#15670]
- segment
- queue
- entryTime
- eventTime
- blockTime

see #14935

**Comment by namdre** [comment]
mainly to aid with debugging

**Comment by aminissn** [comment]
I just tested with sumo Version v1_21_0+0603-0949a42256f and fcd-output has not changed compared to stable version 1.21.0

**Comment by namdre** [comment]
not the default output, since the new attributes are optional.
