### ISSUE TITLE
Get the lane ID

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15678]
Let's say I'm driving through a multi-lane intersection, and the subsequent exit edge is also multi-lane, is there a way to get the lane ID of the lane I'm exiting before I enter the intersection? I know how to get the edge ID.

Thank you in advance.

**Comment by m-kro** [comment]
Please look at [traci.vehicle.getBestLanes](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getBestLanes) for this purpose. "best lanes" contains the lanes the vehicle plans to use.

**Comment by kasop1** [comment]
Is “getBestLanes” determined at the time of vehicle insertion? 
Or does the value of “getBestLanes” change at each simulation step based on the amount of traffic in the road? 
If so, when is the final BestLanes determined?

**Comment by kasop1** [comment]
Does this mean that it may change for each simulation step? In other words, does it take into account the traffic conditions of My Step?

**Comment by m-kro** [comment]
There are several events the best lanes are recomputed, e.g. a lane change. So yes, traffic conditions impact the best lanes obviously.
