### ISSUE TITLE
Unable To Pick Passengers in Bus(veh_type) at Bus Stops!

### ISSUE THREAD

**Issue by maddymohammad** [eclipse-sumo/sumo#15673]
Hi everyone'
I am contacting here with reference to an issue I am facing while using SUMO. I have made a sample track(dual lanes) also added vehicles after routing too. Now the issue is I am unable to make these buses stop at the bus stops and pick the pedestrian. I have added pedestrian path too. But as soon as the pedestrian reach to the bus stop they dont stay or stop but just dissappear. I have tried using (stop mode in persons tab in netedit), that just spawns them in the bus stops for me. 
----------------------------------------------------- MAIN OBJECTIVE-----------------------------------------------------
I just want to use bus stops to pick and drop passenggers from different bus stops. I am sorry this issue might be totally useless as it is due to my incompetancy(for which i apologize again). But I will be grateful to any support from your community. I tried both ways by coding directly into the xml files but also through the net edit software. I added stops at every bus stops so that atleast the vehicles could stop. But ALAS I had to give up and seek for support. 
I hope you all understand my problem

**Comment by namdre** [comment]
- you can download a simple example at: https://sumo.dlr.de/extractTest.php?path=sumo/basic/personFlow/busStop_ride_busStop
- if you want public transport in a real-world network, use osmWebWizard and activate 'pedestrian' in the traffic tab and 'public transport' in the general settings tab (see https://sumo.dlr.de/docs/Tutorials/OSMWebWizard.html)
