### ISSUE TITLE
Use traci to disable or enable lane changes

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15688]
Can I use traci to disable or enable lane changes? 
I would appreciate it if you could tell me. 
If not, is it possible to create a new feature for this?

**Comment by m-kro** [comment]
This can be done by setting the lane change mode (see [docs](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6)).

**Comment by kasop1** [comment]
Thank you. 
I have read it many times, but I am not sure if it is correct, so please give me an example sentence. I would be grateful if you could give me an example sentence that completely prohibits lane changing. I apologize for the trouble.

**Comment by namdre** [comment]
As the documentation states, setting it to 256 or 512 prevents all changing.

**Comment by kasop1** [comment]
I understand. I will try it later.
Thank you.
I appreciate for your kindness.
