### ISSUE TITLE
How I can add events to a specific road using TraCI？

### ISSUE THREAD

**Issue by hyxie2023** [eclipse-sumo/sumo#15689]
Hello, may I ask how I can add events to a specific road using TraCI? For example, how to set up a road closure for a certain road for 3 hours, or simulate a traffic accident on a certain road at a specific time. Thank you.

**Comment by m-kro** [comment]
Close / open lanes by removing / adding permissions: [traci.lane.setDisallowed](https://sumo.dlr.de/pydoc/traci._lane.html#LaneDomain-setDisallowed) / [traci.lane.setAllowed](https://sumo.dlr.de/pydoc/traci._lane.html#LaneDomain-setAllowed). Accidents can be modeled as well by placing a vehicle on the lane through [traci.vehicle.add](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-add) and let it stop there.

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/FAQ.html#how_to_simulate_an_accident
