### ISSUE TITLE
incorrect 'caccVehicleMode' state overrided by freeSpeed

### ISSUE THREAD

**Issue by alexmajy** [eclipse-sumo/sumo#15682]
https://github.com/eclipse-sumo/sumo/blob/03fd38ac0ce6ce7e1b5c2b48c961ee43bda6e287/src/microsim/cfmodels/MSCFModel_CACC.cpp#L111

this code always sets the 'caccVehicleMode' into CC for most time even if the vehicle in other modes, like Gap-closing control mode.

**Comment by m-kro** [comment]
@robertalms

**Comment by alexmajy** [comment]
@m-kro yes.

I mean the vehicle should be in Gap-closing control mode, but the outside retrieved status is CC.  

This the windows 1.21.0 version from official wesite. The image showed the vehicle's caccVehicleMode is CC. However it time gap is 1.06s, and according to the [docs](https://sumo.dlr.de/docs/Car-Following-Models/CACC.html), from my understanding, the vehicle should be in **Gap-closing control mode when the time-gap is less than 1.5 s**.
<img width="795" alt="sumo_caccVehicleMode_1 21 0" src="https://github.com/user-attachments/assets/22670eda-102a-4020-bd46-edc7788163a5">

Then I downloaded the 1.21.0 source code, remove the line and rebuild the sumo, the results is correct.
<img width="521" alt="wsl2_sumo_caccVehicleMode_modified_1 21 0" src="https://github.com/user-attachments/assets/d78faed7-1b47-4000-b532-8bbb568f3367">

**Comment by m-kro** [comment]
Can you please attach your sample scenario to this ticket?

**Comment by alexmajy** [comment]
no problem. It's here. [cacc_and_cc_issue15682.zip](https://github.com/user-attachments/files/17679722/cacc_and_cc_issue15682.zip)

BTY, the sample scenario is also for a problem related [couldChangeLane issue 10739](https://github.com/eclipse-sumo/sumo/issues/10739). Although the issue is closed, but I encouter the problem. Should I open a new issue?

**Comment by m-kro** [comment]
@alexmajy  It is fine posting in the old issue if you are convinced it has to do with the topic.
