### ISSUE TITLE
Create a lane changeable area

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15685]
I want to create a lane changeable area. I know that we can regulate lane changes (changeRigh, changeLeft) for each lane. But is it possible to specify that only 20-60m of this lane cannot change lanes, etc.?

**Comment by m-kro** [comment]
Well you can always split the edge where you want the lane change rules to change...

**Comment by kasop1** [comment]
Thank you. 
I know it is possible to split the lane and prohibit lane changes that way. However, I would like to specify the lane change area using pos for convenience.

**Comment by m-kro** [comment]
That's the way it is done - there is no such thing as as part of a edge with different rules.

**Comment by kasop1** [comment]
I understand. 
Thank you. 
I'll do it that way from now on.
