### ISSUE TITLE
Force a lane change.

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15686]
I want to use traci to change lanes from “A” lane to “B” lane. For example, setLanechange. 
Is there a way to do this?

**Comment by m-kro** [comment]
The actual function is called [traci.vehicle.changeLane](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-changeLane). There are as [traci.vehicle.changeLaneRelative](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-changeLaneRelative) and [traci.vehicle.changeSublane](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-changeSublane) (sublane model).

**Comment by kasop1** [comment]
Thank you. 
I tried to find the command myself before asking the question, but I couldn't find it. 
If I want to change lanes to the next lane forever, how long should the duration be? Should it be longer than the simulation time?

**Comment by m-kro** [comment]
If you want to be sure you can do that...

**Comment by kasop1** [comment]
Did the developers manage to do that?

**Comment by kasop1** [comment]
I understand.
Thank you.
I appreciate for your kindness.
