### ISSUE TITLE
speedErr is inconsistent with the paper formular for CACC CFModel

### ISSUE THREAD

**Issue by alexmajy** [eclipse-sumo/sumo#15683]
https://github.com/eclipse-sumo/sumo/blob/03fd38ac0ce6ce7e1b5c2b48c961ee43bda6e287/src/microsim/cfmodels/MSCFModel_CACC.cpp#L288

according to the formula in the paper[1], the speedErr is derivative of desSpacing. According to the code:

```
double desSpacing = myHeadwayTime * speed;
double spacingErr = gap2pred - desSpacing;

```
d(spacingErr)/dt = d(gap2pred)/dt - d(desSpacing)/dt
                 = d(gap2pred)/dt - myHeadwayTime * d(speed)/dt
                 = (predSpeed - speed) - myHeadwayTime * accel

so myHeadwayTime * accel should be substracted from rather than added to in the code. change the code into:
` double speedErr = predSpeed - speed - myHeadwayTime * accel; `

[1] Xiao, Lin, Meng Wang, and Bart Van Arem. "Realistic car-following models for microscopic simulation of adaptive and cooperative adaptive cruise control vehicles." Transportation Research Record 2623.1 (2017): 1-9.

**Comment by m-kro** [comment]
@robertalms ?

**Comment by robertalms** [comment]
Yep, that's seems to be correct. Thanks for noticing this error @alexmajy ! I suppose, changing this code will break a lot of tests, but I will have leave that matter to my colleagues. Unfortunately, I have no time at the moment to look into this subject in greater detail myself.

**Comment by namdre** [comment]
I'm a bit worried about the change in trajectory when following a faster leader (the leader accelerates at 2.6 for the first 8s and then drives at constant speed, the plots show the acceleration of the follower with the old and new code).
![accel](https://github.com/user-attachments/assets/6772ba9e-28ca-4109-a800-ed8f2325b564)

The scenario is at tests/sumo/cf_model/drive_in_circles_steplength/CACC (and shows a reduction in insertion capacity)

**Comment by robertalms** [comment]
As discussed with @namdre, the CACC model generally exhibited some oscillations with gap-closing observed also in other cases. Even though your plot doesn’t appear satisfactory, fixing this bug in the speed error equation might adequately resolve some other issues, as well. Compare the vanishing micro-oscillations from the maneuver in #11776

![image](https://github.com/user-attachments/assets/c8d15e2a-79f4-4f5a-b765-42d06c3b8313)
