### ISSUE TITLE
Vehicles avoid certain lanes 

### ISSUE THREAD

**Issue by Millich-NoTraffic** [eclipse-sumo/sumo#15693]
Hello, 
while simulating an intersection corridor I observed a strange behavior in one of the intersections.
In the intersection, the SB exit has 3 lanes where each of them is connected to a different lane, yet all the cars choose the left most lane causing a large delay existing the intersection over time. Effectively the cars behave as if the SB exit has only 1 lane and not 3 when there is low congestion and will use 2 lanes instead of 3 when there is high congestion.

I attached an example video of the issue 
https://github.com/user-attachments/assets/54a9c69a-7507-42e4-8ce5-4fc07d98ea79

connections in netedit looks good
![Screenshot from 2024-11-10 18-07-24](https://github.com/user-attachments/assets/5380f98d-7636-4c2d-94f4-af5ae90fc49a)

Vtypes are
<vType id="passenger" vClass="passenger" carFollowModel="W99" cc1="1.5" cc2="1" cc8="3" jmDriveAfterYellowTime="3" sigmaStep="0.1" desiredMaxSpeed="17.88" lcStrategic="1" lcSpeedGainLookahead="0" startupDelay="0.2" lcLookaheadLeft="3" lcOpposite="0" jmTimegapMinor="1.0" jmStoplineGap="2.0" jmIgnoreFoeProb="1" impatience="off" accel="2.0" decel="4.5" emergencyDecel="9" sigma="0.0" length="4.5" width="1.8" height="1.5" minGap="1.4" tau="1.2" maxSpeed="50" departLane="best" guiShape="passenger" />    

Output lanes:
    <edge id="I33_S_out" from="I33" to="PR_33_32_" priority="-1">
        <lane id="I33_S_out_0" index="0" allow="bicycle" speed="15.89" length="335.06" width="1.80" shape="659.19,1977.59 655.79,1642.55"/>
        <lane id="I33_S_out_1" index="1" speed="15.89" length="335.06" shape="661.69,1977.57 658.29,1642.52"/>
        <lane id="I33_S_out_2" index="2" speed="15.89" length="335.06" shape="664.89,1977.54 661.49,1642.49"/>
        <lane id="I33_S_out_3" index="3" speed="15.89" length="335.06" shape="668.09,1977.50 664.68,1642.46"/>
    </edge>

Do you have any idea what may cause the error?
Thank you in advance, 
Michael 

**SUMO-version:** 1.13.0

**operating system:** Ubuntu 22.04

**Comment by m-kro** [comment]
See FAQ: [Why do the vehicles not use all available lanes?](https://sumo.dlr.de/docs/FAQ.html#why_do_the_vehicles_not_use_all_available_lanes)
If this does not apply to your simulation, please explain more about the route southbound of the shown intersection.

**Comment by Millich-NoTraffic** [comment]
Thank you!
the FAQ helped,
looking further there was a lane that was not connected, connecting it properly fixed my problem
