### ISSUE TITLE
Emergency blinkers

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15692]
![image](https://github.com/user-attachments/assets/835e2c59-ccab-492b-92a9-a1e3d9550459)

What does this mean?

**Comment by kasop1** [comment]
Why are there four yellow lights on?

**Comment by m-kro** [comment]
Emergency blinking should only be activated externally through TraCI calls. Did you use[ traci.vehicle.setSignals](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setSignals) ?

**Comment by kasop1** [comment]
Not used. Specifying laneindex with setstop caused this issue.

**Comment by m-kro** [comment]
You are right. While it is not defined explicitly in the code, the vehicle will use emergency blinkers if it does not stop on the outermost lane.

**Comment by kasop1** [comment]
Thank you. 
I refrain from  showing this GUI to other people so I'd like to turn its light off. Is that possible?

**Comment by m-kro** [comment]
Using the TraCI function named above calling it with value 0 will switch all lights off.

**Comment by kasop1** [comment]
Thank you. 
I'm sorry for being selfish. 
I definitely want to turn on the lights when turning right and left.

**Comment by kasop1** [comment]
I think I asked the wrong question... 
I do not want all 4 lights to be on as shown in the attached photo, but in the situation in this photo the car is trying to turn right. Therefore, when I indicate 0 on the traci, the left blinker, which should be on, also goes off. I do not want this to go off.

**Comment by kasop1** [comment]
Thank you.

Do you have an example code? I think if I do it the way you say, the left blinker will also go off.

**Comment by kasop1** [comment]
I've been thinking about this, but does this mean that even if there are, say, 4 lights on, you can still use TRACI to tell the driver to turn on the left turn light?

**Comment by m-kro** [comment]
You never set single lights but always the complete state. You can query the current state with [traci.vehicle.getSignals](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getSignals). 

All blinkers active at the same time but no other light equals an integer value of 3 (first two bits set) or 4 (third bit set). Now if you want only the left blinker this state is represented by the integer value 2 (only second bit set). If you want to activate the braking lights together with left/right blinkers equals 12 (third and fourth bit set).

**Comment by kasop1** [comment]
Thank you.
I got it.
