### ISSUE TITLE
Changing exit lanes just before entering an intersection

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15690]
Just before entering an intersection, I want to change my preferred exit lane. For example, I entered the intersection in lane E2_0 and planned to exit the intersection in lane E3_5, but I changed my mind and want Traci to exit in lane E3_3. How can I do this?

**Comment by kasop1** [comment]
Sorry for my poor English. 
I want to use Traci to change the exit lane just before the intersection, can you tell me how to do it?

Thank you in advance.

**Comment by namdre** [comment]
If the internal lanes (the lanes within the intersection) belong to the same internal edge then you should be able to trigger a lane change you as you would on a normal edge.

**Comment by kasop1** [comment]
Understood, thank you. I'll give it a try.

**Comment by kasop1** [comment]
An error occurred. I want to do the following:

**Comment by kasop1** [comment]
![image](https://github.com/user-attachments/assets/4f9ae959-1636-4b49-a300-bc2012edb8c1)

**Comment by kasop1** [comment]
![image](https://github.com/user-attachments/assets/2165690f-904d-48a1-b7a8-1e2e4ea94092)

**Comment by kasop1** [comment]
I would like to change to the exit lane just before the intersection as shown in this diagram. Do you know how to do this?

**Comment by kasop1** [comment]
I am Sorry.
I did it. I had the wrong settings.
Thank you very much.
