### ISSUE TITLE
About no-block-heuristic

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15701]
Intuitively, I think it's to prevent junction blockage. I don't really understand the criteria at this point. Is there a threshold? For example, if there is a car within "10m" of the intersection exit, will it prevent junction blockage by not entering the intersection? Could you tell me a bit more about the criteria for determining whether junction blockage is likely to occur? 

Thank you in advance.

**Comment by m-kro** [comment]
Please read more about the heuristic in the paper referenced in the documentation: [[Road Intersection Model in SUMO, Krajzewicz et al]](https://elib.dlr.de/93669/1/LNCS_SUMOIntersections.pdf)

**Comment by kasop1** [comment]
I read this paper.
I got it.
Thank you.
