### ISSUE TITLE
Questions about simulation result data period

### ISSUE THREAD

**Issue by cloudpetticoats** [eclipse-sumo/sumo#15707]
I used randomTrips.py to successfully auto-generate the simulation data for my OSM map. The simulation output period is fixed as 1, such as following picture. But I want to get data with an output period of 0.1. Inside the official documentation I found that `--device.fcd.period` is used to set it. But after I run the simulation using `sumo -c your_simulation.sumocfg --device.fcd.period 0.1`. The result is still data with 1 as the output period. Can someone help me about this, please?

<img width="202" alt="Screenshot 2024-11-12 at 16 35 08" src="https://github.com/user-attachments/assets/9945a4ae-62c4-41cc-8621-1c9ab68eda97">

**Comment by m-kro** [comment]
Did you set an appropriate time step (sumo argument `--step-length`, see [docs](https://sumo.dlr.de/docs/sumo.html#time)) smaller or equal to the wished output frequency? Otherwise this will not work as everything is bound to the general simulation execution steps.

**Comment by cloudpetticoats** [comment]
Thank you so much, I've had results after using `--step-length`.
