### ISSUE TITLE
About the speed of stopping

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15704]
In the real world, the speed of a stopped car is exactly zero. However, when the getSpeed command is executed, the output is not a perfect “0” but a value as close to zero as possible, such as 0.00000098 or 0.0001, even though the car is clearly at a complete stop on the SUMO GUI. Why is this? Also, according to the SUMO documentation, I believe there is a statement that speeds below 0.1 m/s are treated as a stop, so what does this have to do with this case?

Thank you in advance.

**Comment by kasop1** [comment]
What this means is that the GUI will display to two decimal places, correct?

**Comment by namdre** [comment]
Yes. And you can set option --precision to increase the number of digits.

**Comment by kasop1** [comment]
Thank you.
I got it.

**Comment by kasop1** [comment]
> getSpeed returns the raw internal data.
How many decimal places are output?

**Comment by namdre** [comment]
2 by default, configurable with option **--precision**

**Comment by kasop1** [comment]
No,no.
Is the number of decimal places in getspeed also 2 digits?
I am asking about GETSPEED.

**Comment by kasop1** [comment]
With mine, it is more than two digits.

**Comment by namdre** [comment]
getSpeed gives the raw internal data with 15 decimal places

**Comment by kasop1** [comment]
Thank you.I got it.

As a developer, how many orders of magnitude do you consider any disturbance, such as noise, to be reliable?

**Comment by kasop1** [comment]
Is there any option to specify the number of digits for getspeed?Or do I have to use python rounds?

**Comment by namdre** [comment]
you need to round in python

**Comment by kasop1** [comment]
Thank you very much.Understood.How many digits do you recommend?

**Comment by kasop1** [comment]
Thank you.
I will.
