### ISSUE TITLE
tlsCycleAdaptation not working problem

### ISSUE THREAD

**Issue by ufukkirbas** [eclipse-sumo/sumo#15706]
Add your issue description here.

I run the tlsCycleAdaptation script from the tools tab in the sumo netedit interface. Then I define the net-file and route-files files along with the folder path they are saved in. When I run the start command, I get the error I mentioned below on a new information screen. There is only one junction in the file I specified. And I write the name of the junction on that opened page. Where could I be going wrong? If you have an application example on this subject, could you share it?

*If possible, upload an example that shows your problem.*

`python "C:\Program Files (x86)\Eclipse\Sumo/tools/tlsCycleAdaptation.py" --net-file "C:\Sinyal_Optimizasyon\Yol_Agi.net.xml" --output-file "tlsAdap.add.xml" --route-files "C:\Sinyal_Optimizasyon\Yol_Agi_Rotalar.rou.xml" --begin "7200" --existing-cycle --write-critical-flows --program "J1" --restrict-cyclelength --unified-cycle --sorted --verbose` başlangıç süreci...
Warning: The period is less than 1 hour. The flows will be proportionally scaled up to 1-hour flow with the scaling factor 4.0.
the total number of tls: 1
Begin time:7200.0
parsing route file: C:\Sinyal_Optimizasyon\Yol_Agi_Rotalar.rou.xml
Warning: No vehicles parsed from C:\Sinyal_Optimizasyon\Yol_Agi_Rotalar.rou.xml.
There are no flows at the given intersections. No green time optimization is done.
süreç bitti

**SUMO-version:**
1.20.0
**operating system:**
Win 11
[Try.zip](https://github.com/user-attachments/files/17713634/Try.zip)

**Comment by namdre** [comment]
at the moment, tlsCycleAdaptation only supports route-files with `<vehicle>` elements (neither `<trip>` nor `<flow>`). How did you defined your traffic?

**Comment by m-kro** [comment]
It's attached to this issue (`<flow> definitions`)...

**Comment by ufukkirbas** [comment]
> at the moment, tlsCycleAdaptation only supports route-files with `<vehicle>` elements (neither `<trip>` nor `<flow>`). How did you define your traffic?

I defined traffic as Vehicles->flow(embedded flow). How can I define it as you said?

**Comment by namdre** [comment]
you can convert a flow input into vehicles by calling `duarouter -n your.net.xml -r flow.rou.xml -o vehicles.rou.xml`

**Comment by ufukkirbas** [comment]
> you can convert a flow input into vehicles by calling `duarouter -n your.net.xml -r flow.rou.xml -o vehicles.rou.xml`

Thank you for your reply. Is there a solution to operate the duarouter command in the Netedit interface?

**Comment by namdre** [comment]
not yet, but it's planned: #15710
