### ISSUE TITLE
Hide the edge

### ISSUE THREAD

**Issue by Ahmad1441** [eclipse-sumo/sumo#15726]
Add your issue description here.

Hello Sumo Team,

Can you consider to add a feature to hide the edge. So, we can see the map and make sure edges are on top of the map? Currently, the feature is only for junction (ctrl + J will hide junction).

![image](https://github.com/user-attachments/assets/041cf3ac-1923-4a20-936b-47f2e0c8cb98)

**SUMO-2021:**

**Windows:**

**Comment by m-kro** [comment]
What if you choose fully transparent colour values? Just go to the [visualisation settings](https://sumo.dlr.de/docs/sumo-gui.html#changing_the_appearancevisualisation_of_the_simulation) ("streets" tab) and set the Alpha value for each road category to 0.

**Comment by Ahmad1441** [comment]
![image](https://github.com/user-attachments/assets/12f301df-98dc-492d-85b4-8187310baf03)

I followed your guide, nice, Thanks
