### ISSUE TITLE
How to make the SUMO vehicle "speedFactor" different based on different edge

### ISSUE THREAD

**Issue by TroubledWind** [eclipse-sumo/sumo#15729]
I'm using SUMO to simulate the snowfall road network. Is it possible to give each edge a vehicle speed factor? This factor will influence the vehicle itself max speed, not the edge speed limit; which means when a vehicle drives to an edge, vehicle real speed = vehicle max speed* edge speed factor

In vtypes.add.xml, there is a speed factor. But this factor is influenced by vehicle types, not edges. I only have one type of vehicle. How can I modify the add.xml so that the vehicle speed factor can change based on different edge id.

```
<additional>
    <vType id="car" minGap="1.5" length="5" maxSpeed="33.08" speedFactor="0.8"/>
</additional>
```

sumo Version 1.18.0

**Comment by namdre** [comment]
You could use road friction for this: https://sumo.dlr.de/docs/Simulation/Friction.html

**Comment by TroubledWind** [comment]
Appreciate! This is indeed what I want.
