### ISSUE TITLE
About definition of "STOP"

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15731]
According to the following, a stop is defined as a velocity of 0.1 m/s or less. Why is this? Shouldn't it be 0? Are noise and other factors involved?
https://sumo.dlr.de/docs/Simulation/Output/Summary.html#generated_output

**Comment by namdre** [comment]
Some movement models don't easily reach speed 0 but rather speed many steps at speeds close to 0. Classifying such vehicles as "moving" would be misleading.
Since SUMO tries to accommodate different carFollowModels without substantially altering them from their published form, this is a pragmatic way of interpreting their behavior.

**Comment by kasop1** [comment]
Thank you very much. 
Can you tell me why it happens?

Also, Does that happen("Some movement models don't easily reach speed 0 but rather spend many steps at speeds close to 0") with the default "krauss model"?

**Comment by kasop1** [comment]
> they spend another 5% of their time at speeds between 0 and 0.1 with Krauss

Is this actually moving? Or is it zero, but is this happening because of noise or something?

**Comment by namdre** [comment]
I consider this numerical noise.

**Comment by namdre** [comment]
Yes. See https://github.com/eclipse-sumo/sumo/blob/109d92981300a730f914862fa252573cf48dc8f2/src/utils/common/StdDefs.h#L57-L58

**Comment by kasop1** [comment]
When you say that the speed is less than 0.1, do you mean that the speed of the value obtained from getspeed is less than 0.1? Or is the value obtained to two decimal places from the getspeed value less than 0.1?

**Comment by kasop1** [comment]
> Yes. See
> 
> https://github.com/eclipse-sumo/sumo/blob/109d92981300a730f914862fa252573cf48dc8f2/src/utils/common/StdDefs.h#L57-L58

Also, is 0.1 included?

**Comment by namdre** [comment]
yes. See
https://github.com/eclipse-sumo/sumo/blob/ec154b4d664899390538cbc1bac8fa83d52c90bb/src/microsim/MSVehicle.cpp#L4158-L4159

**Comment by kasop1** [comment]
When determining if it is 0.1, is it the speed displayed in the GUI? If so, how many decimal places? Or is it the value you get from getspeed?

**Comment by kasop1** [comment]
Thank you.

You mean "vNext = getSpeed()", right?
