### ISSUE TITLE
how to  generate traffic flows from junction to junction

### ISSUE THREAD

**Issue by dongjingao** [eclipse-sumo/sumo#15732]
Add your issue description here.
I want to use the od2trips and duarouter tool to generate traffic flows from junction to junction, but I don't know how to properly define the TAZ file (for adjacent junctions). How should I define the TAZ file?
*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.20
**operating system:**

**Comment by namdre** [comment]
- define the taz based on edges
- run duarouter on the od2trip-output  with option **--write-trips --write-trips.junctions**
