### ISSUE TITLE
about the sumo version of the function of Stationfinder device

### ISSUE THREAD

**Issue by koharris** [eclipse-sumo/sumo#15733]
I would like to ask about the sumo version of the function of Stationfinder device. Can it be implemented using Sumo 1.20.0, or can it only be used normally if Sumo 1.20.0 is upgraded to 1.21.0?

**Comment by namdre** [comment]
The device is already present in version 1.20.0 but the functionality isn't officially completed (#9663).
I would strongly recommend working with 1.21.0  or even the nightly version.

**Comment by koharris** [comment]
Thanks for your advice, I tried to use the sumo1.20.0 version to set different parameters of the Stationfinder device, but it doesn't seem to work. So I'm ready to upgrade my sumo version to 1.21.0.
