### ISSUE TITLE
Error of Vtype attribute "jmAllwayStopWait"

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15745]
> Attribute 'jmAllwayStopWait' is not allowed to appear in element 'vType'.xml(cvc-complex-type.3.2.2)

The above error message is displayed. Do you have a solution?

Thank you.

**Comment by m-kro** [comment]
That means your XML input files are being checked for correct XML elements and that probably you use a SUMO version where the named attribute didn't exist yet. `jmAllwayStopWait` was introduced in SUMO v.1.21.

If you just want to skip the XML validation, call sumo with the option `--xml-validation never`.

**Comment by kasop1** [comment]
Thank you.
But I am using  v1_21_0+0853-3c053a3b301 that is in "https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots".
Why do errors still occur?

**Comment by m-kro** [comment]
Is that the only SUMO version you have on your computer? If not, can you verify which one is used in the call?

**Comment by kasop1** [comment]
only using v1_21_0+0853-3c053a3b301

**Comment by kasop1** [comment]
I have never seen before using v1_21_0+0853-3c053a3b301.

**Comment by kasop1** [comment]
I never saw it until I used v1_21_0+0853-3c053a3b301

**Comment by namdre** [comment]
please check the output of `echo %sumo_home%`  (or `echo $SUMO_HOME` on linux/Mac).
The most likely reason is that SUMO_HOME/data/xsd/routeTypes.xsd is outdated and does not contain jmAllwayStopWait

**Comment by kasop1** [comment]
`<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://sumo.dlr.de/xsd/routes_file.xsd">`

I am using this but It is occured "Attribute 'jmAllwayStopWait' is not allowed to appear in element 'vType'.xml(cvc-complex-type.3.2.2)"

**Comment by m-kro** [comment]
Please follow the advice of @namdre to check whether the SUMO_HOME variable corresponds to the main directory of the SUMO instance you use.

**Comment by namdre** [comment]
Where exactly did you use data/xsd?  Can you confirm that the problem was not on the SUMO side?

**Comment by kasop1** [comment]
Yes, I used data/xsd when declaring it in the route file.I did not get any errors at that time.

**Comment by namdre** [comment]
The routeTypes.xsd  has already been updated in version 1.21.0 to include jmAllwayStopWait.

Please post the line that you changed in your xml file (the working and the non-working version).

**Comment by kasop1** [comment]
I am using route_files.xsd and declaring it at the top of route file.

**Comment by namdre** [comment]
Please post the lines rather than describing them

**Comment by kasop1** [comment]
working version
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://sumo.dlr.de/xsd/routes_file.xsd">

non-working version
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SUMO_HOME/data/routes_file.xsd">

**Comment by kasop1** [comment]
When I use working version, I don't get error.On the other hand, when using non-workin version I get error such as above I said.

**Comment by namdre** [comment]
This is unexpected since the only version (https://sumo.dlr.de/xsd/routeTypes.xsd) also includes jmAllwayStopWait.
Furthermore, the location in the `xsi:noNamespaceSchemaLocation` should only be retrieved if the local $SUMO_HOME variable is not set.

**Comment by kasop1** [comment]
Thank you.

What do you mean "unexpected"?
Please tell me more detail.

**Comment by behrisch** [comment]
Can you give the precise call you do when you get this error? It does not look like the regular xerces-c error. Also an information on your platform and xerces-c version may be helpful. Furthermore sumo does not write https in the file headers so did you modify the file header manually or how did you generate the route file?
