### ISSUE TITLE
How to make a "time-space diagram"

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15746]
I want to make a "time-space diagram".
Is there any way to make it after doing the simulation in sumo?
Thank you.

**Comment by m-kro** [comment]
Have a look at [plot_trajectories.py](https://sumo.dlr.de/docs/Tools/Visualization.html#plot_trajectoriespy)

**Comment by kasop1** [comment]
I will try it.
Thank you.
