### ISSUE TITLE
SUMO-GUI one step ahead of TRACI?

### ISSUE THREAD

**Issue by Ahmad1441** [eclipse-sumo/sumo#15752]
Hello Sumo Team,

Does Traci perform always one step before simulation time (SUMO/SUMO-Gui time)? 

In my example, simulation step is 1 second, and I  Spwaned two cars at simulation time 0.1 second.

When simulation time is second 1, two cars are already there in SUMO GUI, But Traci print no cars in simulation. In fact, Traci print the status of simulation for one step back. Is this understanding correct? 

![image](https://github.com/user-attachments/assets/24c7213e-b0e9-4130-9a46-596a19aa2982)

Thanks

**Comment by namdre** [comment]
Yes. See https://sumo.dlr.de/docs/Developer/Implementation_Notes/Simulation_Loop.html
TraCI is active at the start of simulation step (before vehicles have moved and where they still have the positions from the prior step) and the GUI shows the state at the end of the step (after vehicles have moved).

**Comment by namdre** [comment]
Note, you can call `traci.simulation.executeMoveme` to perform further queries/manipulations after vehicles have moved but before the step is "done" and shown in the GUI.
