### ISSUE TITLE
Reproducible segmentation fault

### ISSUE THREAD

**Issue by henrigrossmann** [eclipse-sumo/sumo#15751]
**Description:**
I am encountering a reproducible (on different machines with MacOS 15.1) segmentation fault when running simulations in SUMO -HEAD (commit [5dd07af](https://github.com/eclipse-sumo/sumo/commit/5dd07af25629349e5d29985d223f2a4df8966be8)). The issue arises shortly after step #17900.00 (always at the same step) – even on a single thread.

**Steps to Reproduce:**
Run the provided simulation example.
The simulation runs until step #17900.00 and then crashes consistently with a segmentation fault.

**Observations:**
The issue does not occur when using older SUMO version, e.g. [v1_21_0](https://github.com/eclipse-sumo/sumo/releases/tag/v1_21_0)[v0_13_7](https://github.com/eclipse-sumo/sumo/releases/tag/v0_13_7).

**Expected Behavior:**
The simulation should run to completion without a segmentation fault.

**Additional Information:**
-Run the simulation by simply using the command: sumo -c ~/error_example/input/sumo.sumocfg

**Attachments:**
[error_example.zip](https://github.com/user-attachments/files/17829121/error_example.zip)

Thank you for looking into this issue.

**Comment by namdre** [comment]
happens when teleport-disconnected happens and the subsequent edge is jammed.
