### ISSUE TITLE
setEmissionClass does not work correctly with PHEMlight

### ISSUE THREAD

**Issue by Domsall** [eclipse-sumo/sumo#15761]
I am currently using executeMove() and it works great with Emission-outputs using HBEFA.
However, I am getting unrealistic results with PHEMlight.

Is PHEMlight output created earlier/differently?

**Comment by Domsall** [comment]
@namdre After debugging, I think the issue is different.
When I use traci and the command `setEmissionClass`, it seems that SUMO does not correctly import the PHEMlight-maps. I am working on it.

**Comment by behrisch** [comment]
I am not sure I understand the problem. Are you giving vehicle parameters like mass which are not used correctly when changing the emission class? Can you give an example?

**Comment by behrisch** [comment]
You are right, the parameter default settings are broken. I will rework that. HBEFA is basically not influenced by parameters. The point is really that the defaults are not used correctly when a new vehicle type (with a different emission class) is being created via traci
