### ISSUE TITLE
Draw edges as lines with a high zoom

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse-sumo/sumo#15767]
Necessary to avoid holes in big networks

**Comment by namdre** [comment]
drawing edges as straight lines doesn't help for the many short (straight) edges and distorts the long expensive edges too much.

A possible solution is to compute a low-resolution geometry and draw that instead but probably the impact would be low. 
We should look for other speedups

- drawing a canned image when zoomed out
- #10280
