### ISSUE TITLE
About last step delay

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15773]
The traci manual says that the getspeed and getnxttls commands, etc. get the value at the last step.Why can't I get the value at the current simulation step?Please let me know if there are any restrictions.If it is a simulation, it should be possible to get the value at the current simulation step.Also, wouldn't referencing the value at the last step mean that the vehicle information is delayed by the last step?
Thank you.

**Comment by m-kro** [comment]
This can be explained by the TraCI execution order inside a single time step as[ shown in the developer docs](https://sumo.dlr.de/docs/Developer/Implementation_Notes/Simulation_Loop.html). TraCI is executed before the vehicle state is updated, thus the vehicle positions are those from the previous step.

There is a separate TraCI block after the vehicle state update which is active after calling `traci.simulation.executeMove`.

**Comment by kasop1** [comment]
Thank you.

I am not sure if this is the case, but I am curious if you have a better idea.
Did you mean that traci.simulation.executeMove can get the velocity at the current simulation step, not the value one step length ago, for example?

**Comment by m-kro** [comment]
Yes, see this [test example](https://sumo.dlr.de/extractTest.php?path=complex/traci/misc/execute_move).

**Comment by kasop1** [comment]
Thank you. 
I got it and will try it.

**Comment by kasop1** [comment]
Am I correct in assuming that all commands that display the value of the last step (get~) will cause the current value to be retrieved by traci.simulation.executeMove?

Sorry for repeating your question.

**Comment by namdre** [comment]
After calling `executeMove` all `get-`methods retrieve the value of the current step.

**Comment by kasop1** [comment]
Thank you.
I got it.

I have another question.
```
while traci.simulation.getMinExpectedNumber() > 0:
    def1() # getSpeed command written in another python file
    def2() # getNextTLS command written in another python file
    traci.simulationStep()
```
Suppose you have a code like this. The speed and distance to the signal are imported from another python file and retrieved. In this case, is there any way to get the current values just by writing it once, without having to use executeMove many times?

**Comment by m-kro** [comment]
No need to call `traci.simulation.executeMove` more than once per time step. Everything happening after the call will get the value of the current step. It does not matter whether you group these functions in separate files - only the sequence of actual TraCI calls sent to the SUMO instance acting as server matter.

**Comment by kasop1** [comment]
Thank you very much.I understand.

For example, in my code above, where should I write executeMove?

**Comment by kasop1** [comment]
Do I write executeMove between traci.simulation.getMinExpectedNumber() > 0: and def1()?

**Comment by m-kro** [comment]
Yes.

**Comment by kasop1** [comment]
Thank you very much.
I will try it.
