### ISSUE TITLE
About the time lag in the start

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15774]
I am doing a simulation using setstop, and after stopping for a while, I set the duration of setstop to 0 to release the stop.However, if there are no cars or traffic lights in front of the car after the stop is released, the car should start running immediately, but in sumo, the car does not start running immediately and remains stationary for several steps.Why is this?I want it to start running as soon as it is unstopped.

Also, is there any other command besides setstop that can be used to specify the stop position and make it stop?

**Comment by kasop1** [comment]
Thank you.

Which is more appropriate, traci.vehicle.resume or setstop (duration 0)?

Also, please tell me why there is a time lag before the vehicle leaves in the case of setstop (duration 0).

**Comment by m-kro** [comment]
Difficult to say because the delay does not happen in my example scenario. Do you have other vehicles nearby which may block the stopping vehicle?

**Comment by kasop1** [comment]
I will show you later.

> Which is more appropriate, traci.vehicle.resume or setstop (duration 0)?

Are they both the same thing?

**Comment by m-kro** [comment]
`traci.vehicle.resume` cares more about keeping all internal data structure updated and should be preferred.

**Comment by kasop1** [comment]
Thank you.
I got it.
