### ISSUE TITLE
About Difference When using "while traci.simulation.getMinExpectedNumber() > 0:"

### ISSUE THREAD

**Issue by kasop1** [eclipse-sumo/sumo#15778]
I sometimes saw 2 pattern when using "while traci.simulation.getMinExpectedNumber() > 0:"

For example, 
1.
```
while traci.simulation.getMinExpectedNumber() > 0:
       print(traci.vehicle.getSpeed("veh_0")
       traci.simulationStep()
```

2.
```
while traci.simulation.getMinExpectedNumber() > 0:
        traci.simulationStep()
        print(traci.vehicle.getSpeed("veh_0")
```
What is the difference? I would appreciate it if you could tell me how to use it correctly.

**Comment by m-kro** [comment]
Actually it does not depend on `traci.simulation.getMinExpectedNumber()`. The only difference is the point when the time step is executed.
The second example assumes the vehicle `veh_0` is still in the network after executing one time step, whereas in the first example this assumption is not needed. So the first one should be preferred if no further checks or try/catch blocks are added to make sure no exception is thrown.

**Comment by kasop1** [comment]
Thank you. 
You mean that 1st example and 2nd example are almost the same meaning and you recomend that I use 1st example, right?

**Comment by m-kro** [comment]
Yes.
