### ISSUE TITLE
activitygen crashes if attribute is not set

### ISSUE THREAD

**Issue by iiyuu1222** [eclipse-sumo/sumo#15782]
I am currently using sumo to reproduce traffic flow similar to reality, so I would like to use activitygen.
However, even after making various settings, an error occurs and activitygen cannot be used. Could you please tell me the cause of the error?
The execution method is "activitygen --net-file osm.net.xml --stat-file stat.xml --output-file trips.trips.xml --random --verbose" on the directory.
The output looks like this:
"C:\Users\iiyuu\Sumo\1126_1\data>activitygen --net-file osm.net.xml --stat-file stat.xml --output-file trips.trips.xml --random --verbose
Loading net... done.
Loaded 8058 edges.
"Reading input..."

I have attached the file I am using as a zip file. I would like to hear your suggestions for improvement. thank you.

[sumo_1.zip](https://github.com/user-attachments/files/17918728/sumo_1.zip)

**Comment by m-kro** [comment]
You didn't define the positions of schools by setting the `edge` attribute of `school` elements. However this should not lead to an activitygen crash but output an error message (thus should be fixed).

**Comment by m-kro** [comment]
@iiyuu1222 Please always define a school location by edge and position. Generally the attributes in the statistics file of activitygen are obligatory. Nevertheless, from now on new SUMO releases will not crash but output an error message.
