### ISSUE TITLE
traci.simulation.executeMove() removes the ego car when reaching to a junction

### ISSUE THREAD

**Issue by Ahmad1441** [eclipse-sumo/sumo#15787]
Following with our talk on [15572](https://github.com/eclipse-sumo/sumo/issues/15752)
I am running a co-simulation of Unity and SUMO where I controlled a car (called it as ego car) in sumo from Unity. 
I need to use traci.simulation.executeMove() as SUMO-GUI one step ahead of TRACI as shown in below image:

![image](https://github.com/user-attachments/assets/4be3ca03-ac7b-45cd-ac44-31b5bc82e67e)

I am using a simple code like below where we collect UnityEgoCarDataCollection() from Unity and we take control of ego car in Sumo then advance one simulation step then we call  traci.simulation.executeMove() for putting Traci and SUMO GUI in the same time (removing one step delay of Traci), then call sumoDataCollection() which collects the trajectory data of SUMo at the end of simulation step to pass to Unity to visualize the movement.

      `while traci.simulation.getMinExpectedNumber() > 0:  

        UnityEgoCarDataCollection()  # Collect data from Unity before advancing simulation 

        traci.simulationStep()  # Advance simulation

        traci.simulation.executeMove()

        vehicle_data = sumoDataCollection() # Collect data and speed of SUMO

        vehicle_data_json = json.dumps(vehicle_data, indent=4) 

        socket.send_string(vehicle_data_json)`         # Send the JSON data to unity

This works perfectly fine however, when ego car reaches to a junction, SUMO removes ego car and simulation stops. See:

https://github.com/user-attachments/assets/57ba30ad-4b57-4c36-af8a-5c8fccaa167b

For your information, this is my UnityEgoCarDataCollection(), i tried different keepRoute=1,2,3,4 paramters, but it does not work.

    `def UnityDataCollection():
        """
        Receives data from Unity via ZMQ, processes it, and updates the position of 'f_0.0' in SUMO.
        """
        try:
        message = socket.recv()
        unity_data_wrapper = json.loads(message)
        unity_data = unity_data_wrapper.get("array", [])

        for vehicle in unity_data:
            if vehicle["vehicle_id"] == "f_0.0":
                x = float(vehicle["position"][0])
                y = float(vehicle["position"][1])
                angle = float(vehicle["angle"])
                # Convert position to edge ID and lane index
                road_data = traci.simulation.convertRoad(x, y)
                edge_id = road_data[0]
                lane_id = road_data[1]
                traci.vehicle.moveToXY(
                    vehicle["vehicle_id"],
                    "",
                    0,
                    x,
                    y,
                    angle,
                    keepRoute=2
                )
    except Exception as e:
        print(f"Error processing Unity data: {e}")`

I would appreciate any help as this co-simulation is for an opensource project which helps many researchers job.

**Comment by namdre** [comment]
most likely, this happens because the car is on it's final route edge and would disappear in the next step. As a workaround, modify the route of the car so that it always has more edges to drive.

**Comment by Ahmad1441** [comment]
Thanks Jakob for your response. I tried your solution and the issue remains the same. I saved trajectory of ego car in a txt file so you dont need unity. The below file is SUMO files with a txt. 

Please run with and without line 126 (executivemove()).

![image](https://github.com/user-attachments/assets/31e8c82b-43ea-4c26-ab03-1a5a8f364e47)

[SUMOdata.zip](https://github.com/user-attachments/files/17924363/SUMOdata.zip)

**Comment by Ahmad1441** [comment]
I think I found the solution if we put keepRoute=1 instead of 2, it worked. Thanks for taking your time
