### ISSUE TITLE
About function traci. simulation. findRoute returns the length of the route of strange questions

### ISSUE THREAD

**Issue by koharris** [eclipse-sumo/sumo#15791]
When I use `traci.simulation.findRoute` to find vehicles arrived at a certain the path of the charging station, appeared abnormal when get its route length, the following is my example of using this function. In my sumo network, which has only one road, charging stations cs1, cs2, cs3, when using this function, its distance to the corresponding charging station is shown in this list, [('cs1', 0.0), ('cs2', 0.0), ('cs3', 59684.320000000014)], However, the current position of the vehicle is between cs2 and cs3, so it cannot have a route to cs1, cs2, but its distance is 0. So there will be a traci. Exceptions. TraCIException: chargingStation 'cs1' for vehicle 'av_0' on lane '524627099_0' is not downstream the current route. I would like to ask if there is any solution to deal with this problem.
![屏幕截图 2024-11-27 171758](https://github.com/user-attachments/assets/9dbb71ed-dcd5-4b90-a216-043567524c80)

**SUMO-version:**1.21.0

**operating system:**win11

**Comment by m-kro** [comment]
Better check the returned route (Stage.edges). If the returned edge list is empty, no route has been found.

**Comment by koharris** [comment]
I tried to print out the Stage.edges that reach each charging station. As you said, the Stage.edges that reach cs1 and cs2 are indeed empty, which is the error that leads to not downstream the current route.
I also have a question about this, whether Stationfinder device of the electric car, I can use traci. Vehicle. SetChargingStationStop control vehicle charging behavior, Instead of using the Stationfinder device, is there a conflict between the two?

**Comment by m-kro** [comment]
@koharris The **stationfinder** device creates/updates stops at charging stations under certain conditions (basically too low state of charge to complete the vehicle's route). It checks periodically whether the vehicle should charge urgently and where.
Adding charging stops via TraCI may influence the **stationfinder** device indirectly:

- If the vehicle charges earlier, the state of charge may rise sufficiently to complete the route such that the **stationfinder** device does not plan a charging stop 
- If the next stop is at a charging station added through TraCI, the **stationfinder** device checks if it can probably be reached with the current state of charge and then skips planning a stop, too

**Comment by m-kro** [comment]
Under certain conditions, setting a charging stop with TraCI will influence the **stationfinder** behaviour (as explained above). So yes, that is right.

**Comment by koharris** [comment]
Thank you very much for your reply！
