### ISSUE TITLE
Missing connection to parkingArea in chargingStation stop checks 

### ISSUE THREAD

**Issue by koharris** [eclipse-sumo/sumo#15815]
I found that when using traci.vehicle.setchargingStationStop, the vehicle stopped charging at the specified point, but it did not charge. Since my charging station is connected to a parkingArea, it does not automatically stop to the parking space when parking at the charging station, as shown below, I do not know whether it is the cause of this problem.

![屏幕截图 2024-11-29 164905](https://github.com/user-attachments/assets/fc291971-0fff-4d2b-ae05-0190b9f1cb10)

**SUMO-version:**1.21

**operating system:**win 11

**Comment by koharris** [comment]
In fact, I'm using traci. Vehicle. SetChargingStationStop (VEHICLE_ID nearest_station, duration = STOP_DURATION, flags = 1) when the flags to set to 1, Vehicles can be recharged now, but it still will not stop to parkingArea subordinates space, whether you need combined with traci. Vehicle. SetParkingAreaStop function used in order to realize my idea?
![屏幕截图 2024-11-29 175926](https://github.com/user-attachments/assets/0308c797-9184-43ad-9872-6c16385f64cd)

**Comment by m-kro** [comment]
Yes that's more or less the problem (stop on road of off the road and the corresponding default settings). We'll think about changing the settings in this regard.

**Comment by koharris** [comment]
There are also related questions about the charging power of the vehicle. In the setting of the vType of my vehicle, I set it
<param key="device.battery.maximumChargeRate" value="80000"/>
<param key="device.stationfinder.maxChargePower" value="80000"/>
I set power="80000.00 "in the charging station parameter in add.xml, but in the gui interface I get the image below, currently charging [Wh]=21.11, maximum charge rate [W]=22.22, so what I want to know is whether there is a problem, and what is the priority of these parameters in use？
![屏幕截图 2024-11-29 201740](https://github.com/user-attachments/assets/64648d1e-6570-41d0-ada5-1ff05f3df30e)

**Comment by koharris** [comment]
There are also related questions about the charging power of the vehicle. In the setting of the vType of my vehicle, I set it
<param key="device.battery.maximumChargeRate" value="80000"/>
<param key="device.stationfinder.maxChargePower" value="80000"/>
I set power="80000.00 "in the charging station parameter in add.xml, but in the gui interface I get the image below, currently charging [Wh]=21.11, maximum charge rate [W]=22.22, so what I want to know is whether there is a problem, and what is the priority of these parameters in use？
![屏幕截图 2024-11-29 201740](https://github.com/user-attachments/assets/02407db7-362f-4ddf-a165-0c93fe3905c2)

**Comment by koharris** [comment]
There are also related questions about the charging power of the vehicle. In the setting of the vType of my vehicle, I set it
<param key="device.battery.maximumChargeRate" value="80000"/>
<param key="device.stationfinder.maxChargePower" value="80000"/>
I also set power="80000.00 "in the charging station parameter in add.xml, but in the gui interface I get the image below, 
currently charging [Wh]=21.11, maximum charge rate [W]=22.22,
 so what I want to know is whether there is a problem, and what is the priority of these parameters in use？
![屏幕截图 2024-11-29 201740](https://github.com/user-attachments/assets/f715f5d2-c2e8-44ab-837a-5a2dbdcc4000)

**Comment by m-kro** [comment]
For the record: Strange that is hasn't been noticed before. Although most work of #13596 was completed, there seems to be some missing part. The relation between chargingStation and parkingArea was implemented but not checked for planned stops.

**Comment by koharris** [comment]
Ok, I will try again. Thank you for your help！
