### ISSUE TITLE
Generate container stops

### ISSUE THREAD

**Issue by hcao720** [eclipse-sumo/sumo#15813]
Hi, is there any way to automatically generate container stops like the way in netedit. Since I found the set stop instructions in traci all include the parameter veh_id. May I just generate the stops first and then assign them to some veh? Thank you in advance.

**Comment by namdre** [comment]
SUMO distinguishes between infrastructure elements (`<containerStop>`) and the agent behavior of stopping on the road or at some infrastructure element (i.e. `setStop` and `<stop containerStop="cs_0" duration="30">`). 
Only the latter can be controlled via TraCI.

To create additional infrastructure, you have to write a script that generates the corresponding XML file.
If you need containerStops all over your network, I recommend you take a look at tools/generateParkingAreas.py and adapt that to your purpose.
