### ISSUE TITLE
SUMO nightly packages on windows requests debug instead of release versions for DLLs

### ISSUE THREAD

**Issue by RNippold** [eclipse-sumo/sumo#15828]
A fresh installation of the nightly snapshot "Windows installer with all extras (contains GPL code): https://sumo.dlr.de/daily/sumo-win64extra-git.msi" requests MSVCP140D.dll and other DLLs as debug version instead of the release versions. Therefore, the programme will not run with the DLLs provides in the SUMO package.

**SUMO-version:** latest git

**operating system:** Windows 11

**Comment by palvarezlopez** [comment]
The problem is geos-c, that was linked in debug mode

**Comment by palvarezlopez** [comment]
Updated geos_c and gdal in SUMOLibraries. Fixed
