### ISSUE TITLE
Asking about the origin of the default IDM car-following model parameters in SUMO

### ISSUE THREAD

**Issue by HeartBroken4619** [eclipse-sumo/sumo#15839]
What is the origin of the default IDM car-following model parameters in SUMO, and have the developers selected these parameters to accurately reflect general human behavior? Besides, are there any references for having these default parameters for the IDM car-following model?
<img width="175" alt="微信图片_20241202110032" src="https://github.com/user-attachments/assets/fef9cd9b-ebad-4064-80dd-086cb52b282b">

**Comment by namdre** [comment]
- the emergencyDecel value shown in netedit shows the wrong default. If you don't define anything, the default is 9.
- the default values of accel, decel and tau are independent of the carFollowModel but they were originally chosen for the Krauss-model https://sumo.dlr.de/pdf/KraussDiss.pdf

If you are interested in realism, see https://sumo.dlr.de/docs/Car-Following-Models/EIDM.html

Note, that our documentation went offline just now (#15840) but you can find a copy in the docs/userdoc folder of your sumo installation.
