### ISSUE TITLE
[Q]How to treat "select area"

### ISSUE THREAD

**Issue by jamongadejoa28** [eclipse-sumo/sumo#15849]
I'm wondering how the web page that appears after running osmwebwizard.py handles information about "select area" and distinguishes between when "select area" are specified and when they are not.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by m-kro** [comment]
The selected area defaults to the current view if not defined differently through "select area".

**Comment by jamongadejoa28** [comment]
@m-kro When I specify the information (range) for the selection area, I want to know how to communicate it to the network creation process and how to receive it (the form or method of data). Which part will I find out if I check it out?

**Comment by m-kro** [comment]
The selected area is defined by the border coordinates. The resulting bounding box is used in **SUMO_HOME/tools/osmGet.py** to create and execute an [Overpass](http://www.overpass-api.de/) query.
