### ISSUE TITLE
[Q]I'd like to get some advice on implementing the "osmwebwizard.py" feature.

### ISSUE THREAD

**Issue by jamongadejoa28** [eclipse-sumo/sumo#15859]
Currently, I'm only trying to implement up to osmwebwizard.py 's file generation function on Ubuntu. The current problem I'm experiencing is that maps are being implemented so strangely when creating networks. Which part should I check? I desperately need some advice.

[Repository](https://github.com/jamongadejoa28/PJ/tree/main/nextpj)

ubuntu24.04 live-server
next.js(15version)

**Comment by namdre** [comment]
From your question, I can neither determine what you are trying to achieve nor what problem you are facing.
Maybe you can provide the screenshot  of  a "strange network" and describe the steps by which you obtain that network.

**Comment by jamongadejoa28** [comment]
@namdre 
mycode result : [scenario_1733335764.zip](https://github.com/user-attachments/files/18019895/scenario_1733335764.zip)
osmwebwizard.py result : [2024-12-01-13-46-34.zip](https://github.com/user-attachments/files/18019903/2024-12-01-13-46-34.zip)

**Comment by namdre** [comment]
Your netconvert configuration sets option sidewalks.guess which adds sidwalks to all edges with a speed up to 50 km/h and obviously gives the wrong result for motorway links.
Is there anything else you find strange?

**Comment by jamongadejoa28** [comment]
@namdre 
I will check and let you know if there are any other problems. What information should I look at regarding the information you gave me (docs site). And I visited the document site to find information related to the facts, but it was hard to find it because it was down. Often the fact that the document site goes down creates the hassle of having to find the document directly in GitHub. 😔

**Comment by namdre** [comment]
The documentation was down due to a server upgrade. This shouldn't be a problem again anytime soon.

**Comment by jamongadejoa28** [comment]
@namdre 
I tested the build using osmnx. The results were similar to before. Are there any differences when configuring a network with osmwebwizard.py ?
[repository](https://github.com/jamongadejoa28/PJ/tree/main/nextpj(%ED%85%8C%EC%8A%A4%ED%8A%B82))

**Comment by namdre** [comment]
osmWebWizard.py sets various netconvert options depending on the wizard interface options (i.e. "public transport", "Car-only Network") and traffic modes ("Pedestrians", "Bicycles").  You can find all the used options in osm.netccfg and also in the comment header of the generated .net.xml file. 
I find your question *Are there any differences when configuring a network with osmwebwizard.py ?* unclear because I'm not sure what exactly you are comparing it with.

**Comment by jamongadejoa28** [comment]
@namdre 
![스크린샷 2024-12-05 015835](https://github.com/user-attachments/assets/68685757-ea1b-45be-9ce4-fe27fa3aa560)
![스크린샷 2024-12-04 204021](https://github.com/user-attachments/assets/d336436c-d2b8-47cc-bdff-5da3854b6a0e)
When creating networks with the same coordinate values and the same conditions. The GUI graphics don't matter, but there seems to be a difference between what I created by selecting the desired area in osmwebwizard.py and what I created with the code in the first link. 
Of course, I tried to implement the selection area specification in the first link, but my implementation created the same network as the attached image, with or without this feature. 
I'm wondering what could be causing the problem, as when I used OSMnx to provide a distance value of 1000 and generated the network under the same conditions, it still generated the same network as the code in the first link.

**Comment by jamongadejoa28** [comment]
![image](https://github.com/user-attachments/assets/d5fdfedb-f159-43f7-9ca7-5051ecd57eb0)
![image](https://github.com/user-attachments/assets/cfd5ae24-e857-421a-a473-cd157a21b881)

@namdre 
When I create a network with osmnx, even when I reduce the radius from 1000 to 500, it comes out long at the top like the first image (but the left and right sides are significantly reduced).
It didn't seem to recognize the center location correctly, so I set the coordinates to the top of the IC road and set the radius to 1000, and it came out like the second image. The length of the road in the second image looks almost identical to the length of the top part of the result when centered on the IC road.
The options are still using [highway: motorway], car-only network in the road type.

**Comment by namdre** [comment]
you can find the code that pulls data from the OSM servers in sumo/tools/osmGet.py
