### ISSUE TITLE
[Question] Get all running vehicle info through Traci subscription

### ISSUE THREAD

**Issue by lindsaymorgan** [eclipse-sumo/sumo#15862]
Hello! I'm writing a python script to get the position, velocity and acceleration of all running vehicles in a simulation at each step. I'm leaning towards using the Traci subscription method given program performance. I know I can filter the subscription results by context, but I haven't found a way to filter out all the running vehicles in the simulation. Is there a convenient way to do this?

**Comment by namdre** [comment]
you can do `traci.simulation.subscribeContext("", traci.vehicle.DOMAIN_ID, 10, ...`
