### ISSUE TITLE
sumo to Unreal 5

### ISSUE THREAD

**Issue by zn960829** [eclipse-sumo/sumo#15865]
I want to restore the simulation of sumo completely in UE5, just like the project of sumo-web3d. Do you have relevant examples? What should I do?

**Comment by m-kro** [comment]
There was a [contribution](https://www.tib-op.org/ojs/index.php/scp/article/view/1104/1238) on our last user conference about co-simulation SUMO - Unreal4. Maybe this is of help for you.
