### ISSUE TITLE
traci.parkingarea.getIDList() not working

### ISSUE THREAD

**Issue by zsdfaker** [eclipse-sumo/sumo#15874]
when i simulating a parking demo,i get a error
ParkingAreaList = traci.parkingarea.getIDList()
  File "/home/zsder/.local/lib/python3.8/site-packages/traci/domain.py", line 173, in getIDList
    return self._getUniversal(tc.TRACI_ID_LIST, "")
  File "/home/zsder/.local/lib/python3.8/site-packages/traci/domain.py", line 149, in _getUniversal
    return _parse(self._retValFunc, varID, self._getCmd(varID, objectID, format, *values))
  File "/home/zsder/.local/lib/python3.8/site-packages/traci/domain.py", line 154, in _getCmd
    r = self._connection._sendCmd(self._cmdGetID, varID, objID, format, *values)
  File "/home/zsder/.local/lib/python3.8/site-packages/traci/connection.py", line 232, in _sendCmd
    return self._sendExact()
  File "/home/zsder/.local/lib/python3.8/site-packages/traci/connection.py", line 144, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Command not implemented in sumo

**Comment by zsdfaker** [comment]
my sumo version is 1.21.0

**Comment by namdre** [comment]
zip and attach the file `home/zsder/.local/lib/python3.8/site-packages/traci/constants.py`

**Comment by zsdfaker** [comment]
[sumo_parking_test.zip](https://github.com/user-attachments/files/18058920/sumo_parking_test.zip)
this is my code and traci/constants.py

**Comment by namdre** [comment]
The header of your file tripinfo.xml reveals that you have an older version of SUMO on your system (which doesn't traci.parkingarea functionality):
```
<!-- generated on 2024年12月09日 星期一 16时46分09秒 by Eclipse SUMO GUI Version 1.4.0
```
Remove that version or at least make sure that the $SUMO_HOME variable points to version 1.21.0

**Comment by zsdfaker** [comment]
You are right, although I set up the environment variables for SUMO 1.21.0, there is still another SUMO in /usr/bin
