### ISSUE TITLE
Can't see the saved route files after running duaIterate.py

### ISSUE THREAD

**Issue by lucylu2024** [eclipse-sumo/sumo#15872]
I'm running duaIterate.py, and everything seems to be working fine without any errors. I can see each Executing step information as expected. There is a Warning: Could not set locale to 'C'. However, after the process finishes, I cannot find any saved route files in the folder. Could anyone help me understand why this is happening?

**Comment by namdre** [comment]
the route files are in numbered subfolders corresponding to the iterations.

**Comment by lucylu2024** [comment]
There is no subfolders at all.

**Comment by namdre** [comment]
what are the contents of "stdout.log" and "dua.log"?

**Comment by lucylu2024** [comment]
Thank you so much for prompt reply. I found the route files. But they do not appear in the folders under SUMO/CASE/case1. Instead, they are directly under the SUMO folder.

**Comment by namdre** [comment]
they are expected to appear in the working directory and subfoldeers (whereverver you called the duaIterate.py)

**Comment by lucylu2024** [comment]
Oh, thank you.  I first changed the execution path to the target case folder using `cd`, and then ran `duaIterate.py`. This way, I saw the route file automatically saved to the case folder. Now I understand what was going on.
