### ISSUE TITLE
Auto-routing with fromXY and toXY for personTrip in SUMO

### ISSUE THREAD

**Issue by leonefamily** [eclipse-sumo/sumo#15873]
I know about a possibility to compute a `personTrip` route using duarouter, but there's currently no way to use this functionality directly in SUMO, which is a bit disappointing, given that `trip` works perfectly fine with these parameters.

How complicated is it to implement?

It would be useful, if SUMO could automatically assign start and end edge or node to a `personTrip` or `walk` in the same manner it is done for `trip`, whenever start and/or end coordinates are given in various combinations, including PT ride stages, e.g.

```
  <person id="p_0" depart="0.0">  <!-- or depart="triggered" if person starts in a vehicle -->
    <personTrip fromXY="x1,y1" busStop="stop1"/>
    <ride lines="line1" busStop="stop2.1"/>
    <walk busStop="stop2.2"/>
    <ride lines="line2" busStop="stop3"/>
    <personTrip toXY="x2,y2"/>
  </person>
```

**SUMO-version:**
1.21.0

**operating system:**
Windows, Linux

**Comment by namdre** [comment]
this has already been implemented as #15739 and you can use it already with the nightly version: https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots
