### ISSUE TITLE
Unexpected green streaks on the simulated road network

### ISSUE THREAD

**Issue by yuqianlong** [eclipse-sumo/sumo#15884]
![green](https://github.com/user-attachments/assets/25dc049c-05be-42bc-bc12-b70e301fd033)
As shown in the picture, there is unexpected green streaks on the simulated road network. My operating system is windows 11, and the downloaded version is ''SUMO 1.21.0 for Windows 64-bit''. How could I do to slove this problem? Thank you very much.

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/FAQ.html#distorted_view_with_green_lines_all_over_the_network

**Comment by yuqianlong** [comment]
> see https://sumo.dlr.de/docs/FAQ.html#distorted_view_with_green_lines_all_over_the_network

Thank you. Selecting nvidia as preferred graphics processor works!
