### ISSUE TITLE
when the number of lanes increases,vehicles prefer to choose the rightmost lane

### ISSUE THREAD

**Issue by Crush1121** [eclipse-sumo/sumo#15897]
when the number of lanes increases,vehicles prefer to choose the rightmost lane.

how to change this situation or specify the lane to enter

**Comment by Crush1121** [comment]
![f08fe5d0e3e1a230baad4cce6e3ea23](https://github.com/user-attachments/assets/3c7b9dc9-fb36-4ef6-b588-1a1a17fcf9dc)

**Comment by m-kro** [comment]
In the [development version](https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version) of SUMO you can use the lane change model parameter [lcContRight](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models) to change the probability of choosing the rightmost lane. Moreover, our [FAQ](https://sumo.dlr.de/docs/FAQ.html#why_do_the_vehicles_not_use_all_available_lanes) gives some more hints what to do.

**Comment by namdre** [comment]
Note, that connecting every incoming lane with every outgoing lane is not recommended (as it creates unnecessary conflicts). Instead cars should typically change to the correct turning lane ahead of an intersection.
