### ISSUE TITLE
[Question] Semi-actuated tls in SUMO

### ISSUE THREAD

**Issue by usamael2000** [eclipse-sumo/sumo#15894]
How to Implement a Semi-Actuated Traffic Light Signal for a U-Turn Crossover Instead of a Fully Actuated One?

I want to control a U-turn crossover. My plan is to add detectors exclusively at the U-turn while removing detectors from the major street. In this configuration, the major street will maintain a continuous green signal (with a defined maximum green time). The signal will switch to green at the U-turn only when vehicles are detected at the crossover.

Does anyone have suggestions for implementing this without using TraCI?

**Comment by m-kro** [comment]
This sounds like you could do this with [custom phase switching rules](https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#type_actuated_with_custom_switching_rules). There is an [example for public transport priority](https://sumo.dlr.de/extractTest.php?path=sumo/tls/actuated/conditions/bus_prio) but the principle should be the same for your case.

**Comment by namdre** [comment]
You can simply remove actuation from a phase by removing the `minDur` and `maxDur` attributes.
