### ISSUE TITLE
Calibrator addition element usage problem

### ISSUE THREAD

**Issue by ufukkirbas** [eclipse-sumo/sumo#15906]
Add your issue description here.

In order to be able to calibrate the traffic flow, I added a calibrator as an additional element. Then, I opened the calibrator dialog box and entered the edge information on the route I wanted to calibrate, in order. In addition, there are routes and traffic flows in the file for which I provided flow information. When I try to enter the Add newcalibratorFlows data, it gives an error. Then the software closes. The error is as seen in the photo. How can I overcome this?
![Hata](https://github.com/user-attachments/assets/aaa1b520-256d-445b-acd5-8390e1529910)

*If possible, upload an example that shows your problem.*
[Sinyal_Optimizasyon - Kopya.zip](https://github.com/user-attachments/files/18126530/Sinyal_Optimizasyon.-.Kopya.zip)

**SUMO-version:**
1.21.0
**operating system:**
Windows 10

**Comment by palvarezlopez** [comment]
@ufukkirbas Thanks for reporting it!

**Comment by namdre** [comment]
regression introduced in 1.19.0
