### ISSUE TITLE
How is the mean speed on the edge/lane calculated

### ISSUE THREAD

**Issue by lucylu2024** [eclipse-sumo/sumo#15905]
Hi, how is the mean speed on the edge/lane calculated ? I noticed that when I set the demand higher and traffic becomes more congested, but the mean speed in the lane-based output file and aggregate out put file on the lane doesn't change significantly. This doesn't seem reasonable. thanks.

**Comment by namdre** [comment]
possible reasons:
- your aggregation period is set to a large value (maybe the whole simulation) which reduces the relative impact of congestion episodes
- not all the traffic that you define actually enters the network (but rather is held back with delayed departure). See https://sumo.dlr.de/docs/Simulation/RoadCapacity.html#further_headway_effects. This way you have less congestion and higher speeds than expected.

**Comment by lucylu2024** [comment]
Thanks. I noticed a significant change in speed when I increased the demand further.
