### ISSUE TITLE
How to park a vehicle in the opposite lane

### ISSUE THREAD

**Issue by zsdfaker** [eclipse-sumo/sumo#15917]
How to park directly into a spot on the left side without making a U-turn ahead when my vehicle is in the right lane and the right-side parking spots are full
![Screenshot 2024-12-16 20-40-08](https://github.com/user-attachments/assets/2cd74571-7a7b-482d-8ac3-913cfb458bef)

**Comment by m-kro** [comment]
While you can have parking areas on both sides of an edge, you cannot access a parking linked to the opposite edge directly. Currently this is not implemented.

**Comment by namdre** [comment]
Actually, stopping on the opposite side is supported with the opposite-direction driving feature: https://sumo.dlr.de/docs/Simulation/OppositeDirectionDriving.html#model_description but this doesn't extend to parkingAreas yet (#15919)

**Comment by zsdfaker** [comment]
I've tried opposite-direction-driving, but it can only achieve overtaking across lanes and can't park. How should I solve this problem?

**Comment by namdre** [comment]
you can add turnaround-connections near the parkingarea and if necessary, split the edge so that the turnaround is close to the parkingarea.
