### ISSUE TITLE
dyld[26171]: Library not loaded: /opt/homebrew/opt/xerces-c/lib/libxerces-c-3.2.dylib

### ISSUE THREAD

**Issue by khondhaker** [eclipse-sumo/sumo#15913]
Facing issue while installing SUMO on macOS. I have tried to use the terces version 3.2, but still getting the same error. 

**(base) momin@Khondhakers-MacBook-Pro-2 ~ % sumo --version**
dyld[26171]: Library not loaded: /opt/homebrew/opt/xerces-c/lib/libxerces-c-3.2.dylib
  Referenced from: <1FCAEFA0-3B2A-3E81-97EB-31D48936B9B5> /opt/homebrew/Cellar/sumo/1.20.0/bin/sumo
  Reason: tried: '/opt/homebrew/opt/xerces-c/lib/libxerces-c-3.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/xerces-c/lib/libxerces-c-3.2.dylib' (no such file), '/opt/homebrew/opt/xerces-c/lib/libxerces-c-3.2.dylib' (no such file), '/opt/homebrew/Cellar/xerces-c/3.3.0/lib/libxerces-c-3.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/xerces-c/3.3.0/lib/libxerces-c-3.2.dylib' (no such file), '/opt/homebrew/Cellar/xerces-c/3.3.0/lib/libxerces-c-3.2.dylib' (no such file)
zsh: abort      sumo --version
**(base) momin@Khondhakers-MacBook-Pro-2 ~ % brew install xerces-c**
Warning: xerces-c 3.3.0 is already installed and up-to-date.
To reinstall 3.3.0, run:
  brew reinstall xerces-c

**SUMO-version:** 1.20.0

**operating system:** macOS Version 15.2 (24C101)

<img width="852" alt="Screenshot 2024-12-16 at 2 06 50 AM" src="https://github.com/user-attachments/assets/9a8e4c83-dfbb-47c7-a2e9-203ad5fa1ff6" />

**Comment by RobertHilbrich** [comment]
Thank you for bringing up the issue regarding version instabilities when using Homebrew. We are aware of these challenges and have decided to deprecate the SUMO Homebrew formula in the near future. Instead, we will offer two main alternatives:

1. **macOS Installer**:  
   We are in the process of developing a new macOS installer for SUMO. The latest version is currently in beta and not yet notarized. However, you can try the unsigned beta version here: [Download the macOS Installer](https://github.com/eclipse-sumo/sumo/actions/runs/12344852602/artifacts/2323971023).  
   This installer is self-contained, requiring no additional dependencies, and it installs launchers in `/Applications`. We are actively working to release a signed and notarized version soon.

2. **Compiling from Source**:  
   If you prefer to compile SUMO from source, the process is straightforward on macOS. You can refer to our [GitHub workflow file](https://github.com/eclipse-sumo/sumo/blob/main/.github/workflows/build-macos.yml) for guidance or consult our detailed documentation here: [Installing SUMO on macOS](https://sumo.dlr.de/docs/Installing/MacOS_Build.html).

We appreciate your patience and feedback as we improve the installation experience on macOS. If you encounter any issues or have further questions, please let us know!

**Comment by khondhaker** [comment]
Thanks a lot for the quick response. I have another question. I have added the following paths in my ~/.zshrc, but I can not use the **netconvert**

The installation package installed these three app.
<img width="563" alt="Screenshot 2024-12-16 at 10 44 02 AM" src="https://github.com/user-attachments/assets/66f4bf96-ba24-4918-a44b-2945278c6c2f" />

(base) momin@Khondhakers-MacBook-Pro-2 ~ % ls /Applications | grep SUMO
SUMO Scenario Wizard.app
SUMO netedit.app
SUMO sumo-gui.app

**Comment by RobertHilbrich** [comment]
So netconvert would reside in `/Library/Frameworks/EclipseSUMO.framework/Versions/Current/EclipseSUMO/share/sumo/bin/netconvert`.
