### ISSUE TITLE
Vehicle teleport

### ISSUE THREAD

**Issue by Crush1121** [eclipse-sumo/sumo#15920]
I use Sumo to simulate highway vehicle collisions. By detecting collisions, the vehicle in the collision is made to stop and wait for rescue vehicles.However, when they stop, I find that the accident vehicles will be teleported to other sections downstream. Why does this phenomenon occur?

![image](https://github.com/user-attachments/assets/66832b87-7428-43d9-97e7-2e88b084d31e)

（The vehicles in the red frame are the collided ones.）

**Comment by m-kro** [comment]
Teleport is the default setting for **--collision.action** option (see [docs](https://sumo.dlr.de/docs/Simulation/Safety.html#collisions)). If you didn't set this option at sumo start or in the sumocfg file, that's probably the reason.

**Comment by Crush1121** [comment]
> Teleport is the default setting for **--collision.action** option (see [docs](https://sumo.dlr.de/docs/Simulation/Safety.html#collisions)). If you didn't set this option at sumo start or in the sumocfg file, that's probably the reason.

![image](https://github.com/user-attachments/assets/38a7b9e8-6763-4f58-8d2c-20df19f1c175)
this is my setting,I set 'warn' for --collision.action option

**Comment by m-kro** [comment]
@Crush1121 Do you issue any other TraCI commands regarding the collided vehicles? You can let them stop for a globally defined time by option **--collision.stoptime**.

**Comment by m-kro** [comment]
Keep in mind that other vehicles waiting behind the accident may be teleported if not disabled through setting **--time-to-teleport -1** (see [docs](https://sumo.dlr.de/docs/Simulation/Why_Vehicles_are_teleporting.html)).

**Comment by m-kro** [comment]
The user opened a similar topic #15926
