### ISSUE TITLE
how to define cost function

### ISSUE THREAD

**Issue by lucylu2024** [eclipse-sumo/sumo#15921]
Sumo assigns routes based on travel time. I would like to define my own cost function. How can I do that? Thanks.

**Comment by m-kro** [comment]
You can provide custom edge weights (see [docs](https://sumo.dlr.de/docs/Simulation/Routing.html#routing_by_effort)) / overwrite the travel time. Keep in mind that routing by effort (= using custom weights) with a custom weight attribute can be done exclusively through TraCI,.

**Comment by lucylu2024** [comment]
I see. Thank you. Are there any examples related to this?

**Comment by m-kro** [comment]
See [these examples](https://sumo.dlr.de/extractTest.php?path=sumo/devices/rerouting/weights) from our tests
