### ISSUE TITLE
traffic_light_right_on_red stop not working with crossings

### ISSUE THREAD

**Issue by wnederpel** [eclipse-sumo/sumo#15939]
When I define an intersection with free right turns and no pedestriants the vehicles stop before passing and give way to conflicting foe streams as expected. 
However, when I add a pedestrian crossing on the edge over the outgoing lane of the free right turn, the vehicles no longer stop or give way. 
The right turning vehicles with the stop light move as though the light is G. 
They move full speed through the intersection when there is not conflicting stream.
When there is a conflicting stream, the vehicles drive up close to the conflict point and untill the conflicting stream halts at the stop line (to avoid a collision or intersection block) and the right turning vehicles turns in the resulting gap.

EBRT on red works as expected in:
![image](https://github.com/user-attachments/assets/be4c4019-1ec2-4bec-99ab-a7141097a7b9)

EBRT on red works as expected in:
![image](https://github.com/user-attachments/assets/59e37168-59c5-443e-a6c0-41476a2f5aba)

EBRT on red does not work  as expected in:
![image](https://github.com/user-attachments/assets/a166e759-aa33-4e48-bdfe-b331aec406c2)

**SUMO-version:**
tested on both 1.21.0 and  SUMO v1_21_0+1417-602c787ec9f (nightly build installed on 2024-12-18 iirc)

**operating system:**
Windows 11

**Comment by namdre** [comment]
sumo must ignore the internal junction when the connection has state 's'  (the internal junction before the crossing still has to be build for the green phase)

**Comment by namdre** [comment]
@wnederpel Thanks for reporting. You can download a fixed version starting tomorrow at https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots

**Comment by wnederpel** [comment]
Thank you for the quick response and the quick fix! Truly impressive and very much appreciated.
