### ISSUE TITLE
[Q]How do I display the movement of a vehicle on a map as an image in real time?

### ISSUE THREAD

**Issue by jamongadejoa28** [eclipse-sumo/sumo#15948]
I don't know the details of how vehicles are moved within the simulation used by SUMO.
When I searched for the image on GitHub, it uses an XPM file and seems to be a program in C++ and is utilized in the internal GUI.
In my code, which is currently structured as next.js+fastapi, I've implemented something that uses the icon image in the webwizard folder to represent the position of the vehicle on the map in real time as the simulation progresses. What would I need to do to make it look more realistic, to make it look like the vehicle is moving along the road like in the sumo-gui? I am hoping to get some advice.
(My map is using Kakao map from Korea and this may not be represented abroad)

[mycode](https://github.com/jamongadejoa28/PJ/tree/main/nextpj(%EC%A4%91%EA%B0%84%EB%8B%A8%EA%B3%84))

**Comment by jinyuxinjinyuxin** [comment]
You can use SUMO's TraCI to subscribe to each vehicle's latitude and longitude, then convert them to your current map's coordinate system, and update frame by frame. Try this approach.

**Comment by jamongadejoa28** [comment]
@jinyuxinjinyuxin 
Currently, I'm using traci.vehicle.getPosition() to get the position of the vehicle, calculate it for the coordinate system of the Korean terrain, and send the returned value to the client to display the real-time movement on the map.
However, the current movement of the vehicle looks like a circular magnet attached to a blackboard being moved by hand. I'm looking for a way to make it look like the vehicle is actually traveling while changing its viewing direction (the angle of the image frame) to match the direction of the road, like SUMO-GUI.

**Comment by namdre** [comment]
you can also use `traci.vehicle.getAngle`

**Comment by jinyuxinjinyuxin** [comment]
> @jinyuxinjinyuxin 目前，我正在使用 traci.vehicle.getPosition() 获取车辆的位置，计算韩国地形的坐标系，并将返回值发送到客户端以在地图上显示实时移动。 但是，车辆的当前移动看起来就像一块固定在黑板上的圆形磁铁被手动移动一样。我正在寻找一种方法，让车辆看起来像是在实际行驶，同时改变其视角（图像框的角度）以匹配道路的方向，就像 SUMO-GUI 一样。

You can check the usage of traci.vehicle.subscribe and traci.vehicle.getAllSubscriptionResults, which can subscribe to and retrieve various information at once, including latitude, longitude, angle, speed, etc

**Comment by jinyuxinjinyuxin** [comment]
> @jinyuxinjinyuxin Currently, I'm using traci.vehicle.getPosition() to get the position of the vehicle, calculate it for the coordinate system of the Korean terrain, and send the returned value to the client to display the real-time movement on the map. However, the current movement of the vehicle looks like a circular magnet attached to a blackboard being moved by hand. I'm looking for a way to make it look like the vehicle is actually traveling while changing its viewing direction (the angle of the image frame) to match the direction of the road, like SUMO-GUI.

You can check the usage of traci.vehicle.subscribe() and traci.vehicle.getAllSubscriptionResults(), which can subscribe to and retrieve various information at once, including latitude, longitude, angle, speed, etc

**Comment by jamongadejoa28** [comment]
@namdre 
This solved the problem, thank you.
It's amazing that you can use the angular data of the vehicle to interpolate the image as if the vehicle is actually traveling according to the direction of the road.
