### ISSUE TITLE
How can I close a lane during a simulation, just like in SUMO-GUI?

### ISSUE THREAD

**Issue by jinyuxinjinyuxin** [eclipse-sumo/sumo#15954]
I originally wanted to use a method like traci.lane.setAllowed('laneID', []), but the final effect seems different from closing the lane by clicking in the GUI. Does the GUI use TraCI at its core to close the lane?

**Comment by jamongadejoa28** [comment]
@jinyuxinjinyuxin 
[test.txt](https://github.com/user-attachments/files/18259777/test.txt)
This is the code I used. Notice how the road blocking traci method is applied inside the simulation function.
