### ISSUE TITLE
What are the methods for adjusting the speed of SUMO simulations in development environments that do not use the GUI?

### ISSUE THREAD

**Issue by jamongadejoa28** [eclipse-sumo/sumo#15957]
I have a map in a web client, and I'm watching the movement of a vehicle in real time with an image overlay. I want to adjust the speed of the simulation in real time, so I tried to apply traci.simulation.setScale(), but there is no change.

**Comment by namdre** [comment]
the simulation steps only in response to client calls to `simulationStep`. Therefore, delays can be implemented in the client code by calling `sleep()`

**Comment by jamongadejoa28** [comment]
@namdre 
Thank you!
