### ISSUE TITLE
Set max speed for a specific zone within one edge

### ISSUE THREAD

**Issue by cherryh2021** [eclipse-sumo/sumo#15952]
Hello SUMO community,

I was wondering if there is a way to set a speed limit to a specific zone within one edge? For example, set the maximum speed of 5m/s to the last 50m range from the rear end of one edge?

Thank you.

**Comment by namdre** [comment]
The easiest solution is to split the edge and then set the speed limit for the shorter sections.
However, you can also define vehicle waypoints to reduce the speed for a specific section of a lane (note, that waypoints force the vehicle onto a specific lane): https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#waypoints
