### ISSUE TITLE
add --junction-output (trac #1622)

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#1622]
the following output (with variable aggregation period) would be useful:
- time loss at intersection 
- waiting time at intersection
- combined flow at intersection

all within a definable radius or up to the next upstream "real" intersection.

Migrated from http://sumo.dlr.de/ticket/1622
```json
{
    "status": "new", 
    "changetime": "2015-02-20T11:33:50Z", 
    "description": "the following output (with variable aggregation period) would be useful:\n- time loss at intersection \n- waiting time at intersection\n- combined flow at intersection\n\nall within a definable radius or up to the next upstream \"real\" intersection.\n\n", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1424432030165180", 
    "component": "simulation data output", 
    "summary": "add --junction-output", 
    "priority": "major", 
    "keywords": "", 
    "time": "2015-02-20T11:33:50Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by behrisch** [comment]
But not if we are interested in only a part of an edge.

**Comment by namdre** [comment]
brainstorming:

in .add.xml
`<junctionData id="<string>" range="<double>" file="<file>" begin="<time>" end="<time>" freq="<time>"  excludeEmpty="<bool>"/ edges="<optional_edge_filter>">`

in output file
```
<junctionData>
  <interval begin="..." end="..." id="...">
     <junction id="..." 
            sampledSeconds="<COLLECTED_VEHICLE_SECONDS>" 
            traveltime="<MEAN_TRAVEL_TIME>" 
            density="<MEAN_DENSITY>"
            occupancy="<MEAN_OCCUPANCY>" 
            waitingTime="<TOTAL_WAITING_TIME>" 
           timeLoss="<TOTAL_TIME_LOSS>"
            speed="<MEAN_SPEED>" 
            entered="<ENTERED_VEH_NUMBER>" 
            left="<LEFT_VEH_NUMBER>"    
  </interval>
</junctionData>
```

All outputs would apply to the incoming edges within the given range.
The optional 'edges' attribute could be used to filter approaches (i.e. only main direction). 

The main advantage over edgeData output would be constriction to parts of the edge and automatic aggregation over the incoming edges.

Implementation can probably re-use most of the meanData code.

**Comment by namdre** [comment]
Alternatively, the input definition of <junctionData> from above could be used as a shortcut to configure a multi-entry-exit detector for each junction. When using an edge filter, the warning "vehicle left without entering" would need to be disabled. This approach would probably have the least implementation effort.

**Comment by namdre** [comment]
This functionality is mostly covered by tools/output/generateTLSE3Detectors.py (except the restriction to TLS intersections which could be made optional).
The only potential gain would be convenience by avoiding the need for calling python. This may not be worth the effort.
