### ISSUE TITLE
allow actuated traffic light to react to a pedestrian crossing (trac #1746)

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#1746]
this should build a pedestrian-actuated crossing as in tutorial/traci_pedestrian_crossing

possibly related to #5252 but using e2Detector on walkingArea is not enough since the nextCrossing must also be detected.

**Comment by namdre** [comment]
this could also be  the default behavior when placing tlType="actuated" at geometry-like node with a pedestrian crossing.

**Comment by namdre** [comment]
two ways this could work:
- pedestrian phase only becomes active on demand (depends on #5042) and is otherwise skipped in the cycle
- non-pedestrian phase is prolonged as long as no pedestrians are detected (only for a two-phase controller)

**Comment by namdre** [comment]
could make use of the same logic as  traci.trafficlight.getServedPersonCount

**Comment by namdre** [comment]
we need to allow for multiple possibilities when we have an actuated traffic light with pedestrian crossings: 
1. controller reacts only to vehicles (pedestrians are automatically served in vehicular phases)
2. controller reacts to vehicles and pedestrians (i.e. if the controller stays in a default phase then either a side road or a crossing may trigger a phase switch)
3. controller only reacts to pedestrians (i.e. no vehicular intersection and there is an optional pedestrian phase)

Variant 3 can be auto-detected but the user needs to decide between 1 and 2
