### ISSUE TITLE
allow retrieving traffic light, distance to it and tlLink index ahead of a vehicle (trac #1760)

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#1760]
- traci.lane.getLinks() should include traffic light index
- implement traci.vehicle.getTrafficLightsAhead() -> [(tlID, tlLinkIndex, state, distance), ...] (within bestlanes range)

It would also help to be able to retrieve tlIndices for a given network connection without being a wizard (they are recorded in substructes of net._id2tls but not easily cross-referenced when starting with a lane id).

Migrated from http://sumo.dlr.de/ticket/1760
```json
{
    "status": "closed", 
    "changetime": "2016-04-26T12:19:11Z", 
    "description": "- traci.lane.getLinks() should include traffic light index\n- implement traci.vehicle.getTrafficLightsAhead() -> [(tlID, tlLinkIndex, state, distance), ...] (within bestlanes range)\n\n\nIt would also help to be able to retrieve tlIndices for a given network connection without being a wizard (they are recorded in substructes of net._id2tls but not easily cross-referenced when starting with a lane id).\n\n", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1461673151849258", 
    "component": "TraCI", 
    "summary": "allow retrieving traffic light, distance to it and tlLink index ahead of a vehicle", 
    "priority": "major", 
    "keywords": "", 
    "time": "2015-04-27T06:27:08Z", 
    "milestone": "0.27.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by passengerxuhongli** [comment]
what the naming rules of tlLinkIndex? how can i know which connection is controled by the tlLinkIndex only(Without the aid of the information of "fromedge" "toedge")?
