### ISSUE TITLE
lane-change models do not respect left-hand traffic (trac #1920)

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#1920]
one of the reasons being, that the microsim doesn't even know the network is for left-hand traffic.

Migrated from http://sumo.dlr.de/ticket/1920
```json
{
    "status": "closed", 
    "changetime": "2015-11-21T22:51:10Z", 
    "description": "one of the reasons being, that the microsim doesn't even know the network is for left-hand traffic.", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "invalid", 
    "_ts": "1448146270106950", 
    "component": "microsim - lane change", 
    "summary": "lane-change models do not respect left-hand traffic", 
    "priority": "major", 
    "keywords": "", 
    "time": "2015-09-17T08:24:40Z", 
    "milestone": "0.25.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by ichtreenewbee** [comment]
Dear SUMO-Developer:

I got the same problem now. How can i fix it?

Thank you very much.
![turning](https://user-images.githubusercontent.com/47788125/63256919-f0016c80-c278-11e9-938b-b9113d89d0a9.png)

**Comment by namdre** [comment]
upgrade to the latest development version or wait until the release of sumo version 1.3 tomorrow
