### ISSUE TITLE
c++ TraCIAPI is broken and nobody noticed until now (trac #2007)

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#2007]
TraCITestClient uses the API but not all of it. We need tests!

Thanks to Alexander Weidinger for reporting

Migrated from http://sumo.dlr.de/ticket/2007
```json
{
    "status": "closed", 
    "changetime": "2016-02-01T07:57:06Z", 
    "description": "TraCITestClient uses the API but not all of it. We need tests!\n\nThanks to Alexander Weidinger for reporting\n\n", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1454313426268404", 
    "component": "TraCI", 
    "summary": "c++ TraCIAPI is broken and nobody noticed until now", 
    "priority": "major", 
    "keywords": "", 
    "time": "2015-11-17T08:02:29Z", 
    "milestone": "0.25.0", 
    "owner": "namdre", 
    "type": "defect"
}
```

**Comment by shivarajshivu** [comment]
Hi All,

I'm using Sumo simulator for a project. I downloaded sumo-3.1.2 version 3 months back, using which i was able to simulate and control the vehicle from a c++ application using traci library.  

Now i have checkout the latest source code. Is there a change in  "simulationStep" api...?

Earlier when i used to call "simulationStep" , after one step of simulation, the control used to come back to my c++ application. But now after the call, "simulationStep" is not returning. The simulation is running for large amount of time.

The code snippet looks like this:
```

TraCIAPI client_;
client_.connect("127.0.0.1", 9898)

TraCIAPI::VehicleScope vobj(client_);
client_.simulationStep(1);
std::cout<<" The current speed of the vehicle is " <<vobj.getSpeed("veh0");
```

The output looks like this:

**sumo -c quickstart.sumocfg --remote-port 9898
Loading configuration... done.
Step #312735.00 (0ms ?*RT. ?UPS, vehicles TOT 1 ACT 0)**


The same code was working in the 3.1.2 version , Am i missing any statements before calling simulationStep()...?

Can you please help me in this...

Thanks & Regards,
Shivraj

**Comment by behrisch** [comment]
Please make sure that you do not have another outdated version of sumo in your path. The last significant change to simulationStep was for version 1.0. There is no sumo 3.1.2, the most recent version is 1.6.0, three months ago it was 1.5.0. Also please do not comment on unrelated tickets but either write to the mailing list or open a new ticket, see https://www.eclipse.org/sumo/contact/
