### ISSUE TITLE
functional vehicle color does not work with osg (trac #2120)

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#2120]
Migrated from http://sumo.dlr.de/ticket/2120
```json
{
    "status": "new", 
    "changetime": "2016-04-06T08:39:08Z", 
    "description": "", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1459931948243196", 
    "component": "simulation gui (GUISIM)", 
    "summary": "functional vehicle color does not work with osg", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2016-01-26T14:21:40Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by mennowo** [comment]
Just as a remark: this works with the experimental binaries with OSG that are dowloadable from the wiki

**Comment by namdre** [comment]
Coloring by speed, waitingTime, emissions etc works but some coloring modes such as
coloring by type/route color or random coloring are implemented slightly different and are not yet supported for OSG.

**Comment by m-kro** [comment]
Just added functional colouring (by type, random, ...) in a similar way it is done for 2D view. See https://github.com/eclipse/sumo/blob/dc90125386084d58d46d78233c06685ab7644518/src/guisim/GUIBaseVehicle.cpp#L701-L709

**Comment by m-kro** [comment]
@behrisch : Can we close this?
