### ISSUE TITLE
collision after bestlane changes (trac #2329)

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#2329]
bestlanes should be static. see bugreports folder
The error goes back at least to 0.23.0

Warning: Teleporting vehicle 'veh6017'; collision with vehicle 'veh5840', lane='318210383#0_1', gap=-2.30, time=3367.00 stage=move.
Warning: Teleporting vehicle 'veh6853'; collision with vehicle 'veh6241', lane='318210383#0_1', gap=-3.85, time=3746.00 stage=move.
Warning: Teleporting vehicle 'veh7104'; collision with vehicle 'veh6241', lane='318210383#0_1', gap=-4.56, time=3748.00 stage=move.
Warning: Teleporting vehicle 'veh6377'; collision with vehicle 'veh6241', lane='318210383#0_1', gap=-0.87, time=3787.00 stage=move.

Migrated from http://sumo.dlr.de/ticket/2329
```json
{
    "status": "new", 
    "changetime": "2016-10-14T10:47:55Z", 
    "description": "bestlanes should be static. see bugreports folder\nThe error goes back at least to 0.23.0\n\nWarning: Teleporting vehicle 'veh6017'; collision with vehicle 'veh5840', lane='318210383#0_1', gap=-2.30, time=3367.00 stage=move.\nWarning: Teleporting vehicle 'veh6853'; collision with vehicle 'veh6241', lane='318210383#0_1', gap=-3.85, time=3746.00 stage=move.\nWarning: Teleporting vehicle 'veh7104'; collision with vehicle 'veh6241', lane='318210383#0_1', gap=-4.56, time=3748.00 stage=move.\nWarning: Teleporting vehicle 'veh6377'; collision with vehicle 'veh6241', lane='318210383#0_1', gap=-0.87, time=3787.00 stage=move.\n\n", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1476442075681620", 
    "component": "other (also unclassified)", 
    "summary": "collision after bestlane changes", 
    "priority": "major", 
    "keywords": "", 
    "time": "2016-05-18T07:54:59Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
collision no longer occurs in test
