### ISSUE TITLE
Efficiency of charging stations changes during simulation (trac #2358)

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#2358]
User should have the possibility to define a function to change the efficiency of charge during simulation:

Example: Start with a efficiency of 0.95 and end with an efficiency of 0.70 with a logarithmic progression.

Suggested in SUMO Conference 2016 

Migrated from http://sumo.dlr.de/ticket/2358
```json
{
    "status": "new", 
    "changetime": "2016-10-25T07:45:02Z", 
    "description": "User should have the possibility to define a function to change the efficiency of charge during simulation:\n\nExample: Start with a efficiency of 0.95 and end with an efficiency of 0.70 with a logarithmic progression.\n\n\nSuggested in SUMO Conference 2016 ", 
    "reporter": "pablo", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1477381502937752", 
    "component": "simulation general (micro)", 
    "summary": "Efficiency of charging stations changes during simulation", 
    "priority": "minor", 
    "keywords": "charging station, efficiency, electric", 
    "time": "2016-05-26T11:48:37Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by m-kro** [comment]
I think we can close this one. Today charging station efficiency can be set through TraCI and the maximum charging rate of the vehicle battery can be defined as a function depending on the state of charge (#14860). As a result, the vehicle may charge less when being close to fully charged.
