### ISSUE TITLE
allow fixed cycle lengths for actuated traffic lights (trac #2390)

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#2390]
configurable as the sum of duration attributes (when giving allongside minDur and maxDur)?
Migrated from http://sumo.dlr.de/ticket/2390  "changetime": "2016-06-08T10:44:54Z", 

additional params should be used to define the main phase which is supposed to profit from coordination.
The main phase should reliably by green for at least minDur within the time frame of the default duration cycle.

- prolongation of the prior phases is a aborted to ensure that the main phase starts at the correct offset (taking into account the minimum transition time from the current phase into the main phase)
- the main phase is prolonged to ensure that it is active at the correct time within the coordination cycle (whenever switching to another phase would prevent return to the main phase within the remaining time)

**Comment by namdre** [comment]
probably obsolete with #9748
