### ISSUE TITLE
consistent id handling in route and vtype distributions (trac #2677)

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#2677]
Currently routes in distributions are not allowed to have an id while it is required for vtypes. It should be optional in both cases.

Migrated from http://sumo.dlr.de/ticket/2677
```json
{
    "status": "new", 
    "changetime": "2016-11-17T08:47:47Z", 
    "description": "Currently routes in distributions are not allowed to have an id while it is required for vtypes. It should be optional in both cases.", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1479372467363788", 
    "component": "simulation data input", 
    "summary": "consistent id handling in route and vtype distributions", 
    "priority": "major", 
    "keywords": "", 
    "time": "2016-11-17T08:43:34Z", 
    "milestone": "1.0.0", 
    "owner": "behrisch", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment]
I think the ID is required for type distributions because the vehicle must be able to specify it's current type ID in a meaningful way. For route distributions I would make it optional

**Comment by behrisch** [comment]
Although we also have now anonymous types due to traci, I agree that the benefit of having a named vtype probably outweighs the small inconsistency. Furthermore routes are far more dynamic and distributions can even be defined inside vehicles so a little difference is more than justified.
