### ISSUE TITLE
Draw a dotted contour of inspected and selected object under mouse cursor after click over it

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#2905]
in Inspect, delete and select mode, draw a dotted contour around the object under cursor (see contourLane.png)

**Comment by namdre** [comment]
@palvarezlopez : Peter independently suggest this feature. How much effort do you think it would be to implement it at least for edges, lanes and junctions?

**Comment by palvarezlopez** [comment]
@namdre It should not take long. I can do it the next week.

**Comment by namdre** [comment]
Please do (-:

**Comment by palvarezlopez** [comment]
Update: Dotted contour has to be only drawn after click over object, not during movement
