### ISSUE TITLE
make SUMO work with external pedestrian simulator (trac #3166)

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#3166]
Implement a remote controlled pedestrian model that communicates via protobuf over grpc with an external similator

Migrated from http://sumo.dlr.de/ticket/3166
```json
{
    "status": "new", 
    "changetime": "2017-06-07T11:26:02Z", 
    "description": "Implement a remote controlled pedestrian model that communicates via protobuf over grpc with an external similator", 
    "reporter": "laemmel", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1496834762471155", 
    "component": "other (also unclassified)", 
    "summary": "make SUMO work with external pedestrian simulator", 
    "priority": "major", 
    "keywords": "", 
    "time": "2017-06-07T11:26:02Z", 
    "milestone": "1.0.0", 
    "owner": "laemmel", 
    "type": "enhancement"
}
```

**Comment by meltawk** [comment]
Hello Berhish,

how we get information about that feature ?

please advice
regards

**Comment by namdre** [comment]
@bcoueraud87 for you

**Comment by bcoueraud87** [comment]
@namdre Please assign me.

**Comment by behrisch** [comment]
actually the description and the title do not fit well the things you are doing with JuPedSim. I would prefer closing this as won't fix and open a new ticket

**Comment by bcoueraud87** [comment]
@behrisch Yes I just thought that the work with JuPedSim is some kind of replacement for this ticket and so requested an assigment, But you're right, it would be better to create another one (if really needed).
