### ISSUE TITLE
persons arriving at the end of bus stops

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#3872]
shouldn't this also be in the middle like in #3843 or is this more like a car which always arrives at the end?

**Comment by namdre** [comment]
I would prefer the middle.

**Comment by palvarezlopez** [comment]
And an extra Parameter with options "begin, end, middle?

**Comment by namdre** [comment]
this is already covered by the value of "arrivalPos". We're only discussing the default behavior.

**Comment by namdre** [comment]
person now target the middle (values comes from MSStoppingPlace::getAccessPos)
