### ISSUE TITLE
model start-stop system

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#4021]
Vehicles equipped with such a system should not consume fuel / create emissions when waiting in a jam or at a traffic light (possibly tied to the waitingTime) or when stopping with a < stop >.

It may be possible to deduce the presence of such a system from the emission class (i.e. all vehicles with EURO6). This should be discussed with the maintainers of PHEMLight.

**Comment by jprk** [comment]
If such a vehicle is a hybrid vehicle (typically a public transport bus), it might have to keep its engine running even when stopped to recharge batteries/supercapacitors. Deciding on this this is the work of vehicle power management -- if you decide to implement this, I would vote for an additional "power management device" that can be later extended to full power management implementation that works even for hybrids.

**Comment by namdre** [comment]
original idea implemented with energyParams `shutOffStopDuration` and `shutOffAutoDuration` (implementation of power management for hybrid vehicles should be put into a new ticket).
