### ISSUE TITLE
Why this happen

### ISSUE THREAD

**Issue by dcaisurusampath** [eclipse-sumo/sumo#4616]
```
Loading configuration... 
Error: '<' character cannot be used in attribute value 'value'; use &lt; instead
Error:  (At line/column 7/2).
Error: Could not load configuration 'D:\Acadamic\Final year research\Research\sumo\New folder\galle.sumocfg'.
Quitting (on error).
```

**Comment by namdre** [comment]
Please attach the file galle.sumocfg

**Comment by namdre** [comment]
in the line `<route-files value="galle.rou.xml'/>` you've mixed the quoting characters `" `and` '`

**Comment by dcaisurusampath** [comment]
> in the line `<route-files value="galle.rou.xml'/>` you've mixed the quoting characters `"`and`'`

what is the correct one

**Comment by namdre** [comment]
`<route-files value="galle.rou.xml"/>`

**Comment by dcaisurusampath** [comment]
> `<route-files value="galle.rou.xml"/>`

Thank you

**Comment by dcaisurusampath** [comment]
> <route-files value="galle.rou.xml"/>

yes it is success thank you so much
