### ISSUE TITLE
od2trips(results are error)

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse-sumo/sumo#4970]
I want to use od2trips to generate trip files for my sumocfg, but the generate trips have some errors:
1. There have some empty "from" or "to" in generated trips, how does it happen?
2. some trips are error:

Warning: No connection between edge '119460298#5' and edge '-269895569#24' found.
Warning: No route for vehicle '62359' found.
Error: Vehicle '62359' has no valid route.

I think the trips files are given the starting edge ID and the ending edge ID. The intermediate route is automatically generated, so why is the above error?Looking forward to your reply
[shengzhen.zip](https://github.com/eclipse/sumo/files/2704920/shengzhen.zip)

**Comment by shuowang572875852** [comment]
Thank you very much for your reply, I ran the above command but the generated shengzhen_valid.trips.xml file is empty. The command lines are:

i. C:\Users\Administrator\Desktop\shengzhen>F:\software\sumo\bin\duarouter -n shengzhen.net.xml -r shengzhen.trips.xml -o tmp.rou.xml -a shengzhen.add.xml --vtype-output dummy --ignore-errors

.........
Error: Attribute 'from' in definition of trip '161552' is empty.
Error: Attribute 'from' in definition of trip '176525' is empty.
Error: Attribute 'to' in definition of trip '145796' is empty.
Error: Attribute 'to' in definition of trip '22182' is empty.
Error: Attribute 'to' in definition of trip '28449' is empty.
Error: Attribute 'to' in definition of trip '133197' is empty.
Error: Attribute 'from' in definition of trip '176645' is empty.
Error: Attribute 'to' in definition of trip '107709' is empty.
Error: Attribute 'to' in definition of trip '34057' is empty.
Quitting (on error).

ii.  C:\Users\Administrator\Desktop\shengzhen>python F:\software\sumo\tools\route2trips.py tmp.rou.xml > shengzhen_valid.trips.xml

the generated shengzhen_valid.trips.xml is : 

<?xml version="1.0" encoding="UTF-8"?>

<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">
</routes>

**Comment by namdre** [comment]
you need to fix your taz file first to remove superfluous space ' ' and correct edge ids, then run od2trips again and afterwards run duarouter. The duarouter step is only to deal with connectivity but requires valid edge ids all around.

**Comment by shuowang572875852** [comment]
For me my OD matrix is the number of times from one road to another, so can I use the road as a taz .
I want to know if the taz  is an area, so whether the inside edges should be closed . Whether tazSource is the arrival edge in the taz region  and tazSink is the  destination edge  in the taz region.

**Comment by namdre** [comment]
Yes, tazSource is the arrival edge in the taz region and tazSink is the destination edge in the taz region.
Each taz can have multiple tazSource and tazSink elements. You can edit taz using netedit version 1.1.0

**Comment by shuowang572875852** [comment]
I used netedit for taz partitioning, but the generated districts.taz.xml is empty. What is the reason? Whether the edges in taz can distinguish between source and sink.
the command lines are : 
C:\Users\Administrator\Desktop\shengzhen>F:\software\sumo\bin\polyconvert --visum shengzhen.net.xml -o shengzhen.poi.xml
Success.

C:\Users\Administrator\Desktop\shengzhen>F:\software\sumo\tools\edgesInDistricts.py -n shengzhen.net.xml -t shengzhen.poi.xml
[shengzhen.zip](https://github.com/eclipse/sumo/files/2708720/shengzhen.zip)

**Comment by behrisch** [comment]
What is the reason for the polyconvert call? I got the impression you want to generate your taz files manually and do not have polygons describing them. (And they are definitely not described in the sumo network.) Also this ticket does not seem to be the right place for discussions. We should continue on the mailing list, see http://sumo.dlr.de/wiki/Contact

**Comment by behrisch** [comment]
Please continue at the mailing list.

**Comment by Rayaprolus** [comment]
Hi! I used od2trips to generate vehicle trips among 26 TAZs (13 for inflow and 13 for outflow). The simulation is expected to simulate 6000 vehicles in 3.5 hrs. (12600 timesteps). When I generate trips, the trips were distributed from 0 to 3600 instead of 12600. Why? Here's my command:
"od2trips -c Updated_od2trips_proj.config.xml -n Updated_TAZ_proj.taz.xml -d Updated_OD_proj.od -o Updated_od_proj.odtrips.xml --begin 0 --end 12600 --spread.uniform true -H true"

All I want is to spread out vehicle departures uniformly from 0 to 12600 sim steps. 
I'd really appreciate your help.

**Comment by behrisch** [comment]
see #6289
