### ISSUE TITLE
[sumo-gui]  In Linux Ubuntu, the visual appearance after "run" or "resizing window" jumps in the lower left corner and is too small

### ISSUE THREAD

**Issue by mkrech** [eclipse-sumo/sumo#5811]
Hi,
SUMO 1.2
SUMO 1.1
Ubuntu 16.04 via vncserver  TightVNC Viewer.

The visual appearance after "run" or "resizing window" swaps in to the lower left corner and is too small.
![3](https://user-images.githubusercontent.com/5424861/60812354-93973180-a191-11e9-8dd3-96de26afbe1f.PNG)

Regards
Michael

**Comment by namdre** [comment]
Thanks for reporting. I'm not sure how to fix this though. You might try a different VNC client or even https://en.wikipedia.org/wiki/VirtualGL
You could also try older versions of SUMO. If it works for any of them, this we would at least be a clue that it can be fixed on the SUMO side.
