### ISSUE TITLE
NETEDIT parameter input by paste with ctrl+V not working properly

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse-sumo/sumo#6018]
Hi,

I use the latest development version v1_3_1+0039-5d6d0f05d7 on Windows 10. When I want to copy edge or junction parameters from another object, I use the ctrl+C which copies the data to the clipboard (I tested with notepad), but at the destination the ctrl+V does not write it in. Instead it deletes the content. The problem disappears when I switch to Demand mode and back to Network mode.

**Comment by palvarezlopez** [comment]
@ZoltanBaksa Thanks, as usual, for your bug reports. In this case I cannot reproduce the problem as a bug, but as a feature. If you try to paste a string into a numerical field (For example, an startPos), the paste isn't possible, and instead the content will be deleted. Can you give me a concrete example?

**Comment by ZoltanBaksa** [comment]
I usually do changes in the network by re-annotating some edges and junctions by copying the from-to parameters, sometimes I copy the junction id from the junction object's info panel. If I create a new edge on a previously existing road, I usually copy the Name, priority, type parameters from an existing edge.

**Comment by palvarezlopez** [comment]
@ZoltanBaksa I updated the design of TextFields. Now every value can be added/pasted. Can you check if now it works as expected?

**Comment by ZoltanBaksa** [comment]
Hi Pablo,
In v1_3_1+0068-6b9b87bc7e version it is not working.
**Use case 1:** Start Netedit, load network, select an edge in inspect mode, copy type parameter with Ctrl+c to clipboard, select another edge, paste to type field with ctrl+v.
It is possible to copy the data if I previously paste the value to the original field
**Use case 2:** Start Netedit, load network, select an edge in inspect mode, copy type parameter with Ctrl+c to clipboard, _paste value with Ctrl+v_, select another edge, paste to type field with ctrl+v.
After selecting another parameter the "use case 1" occurs again.

**Comment by palvarezlopez** [comment]
@ZoltanBaksa yes, now I can reproduce the error again. Probably related with a focus problem. I fix it.

**Comment by ZoltanBaksa** [comment]
Hello Pablo,
The issue is still reproducible, with the same test cases in v1_3_1+0555-c0a2b3e52e

**Comment by palvarezlopez** [comment]
@ZoltanBaksa I know, but I think the problem is related with FOX Toolkit, not with NETEDIT. I'm working on it.

**Comment by namdre** [comment]
@ZoltanBaksa Save yourself some copy/paste work by using the setTemplate function for the edge you want to copy. Then activate the template when creating new edges.
