### ISSUE TITLE
migrate CI build infrastructure to GitHub actions

### ISSUE THREAD

**Issue by RobertHilbrich** [eclipse-sumo/sumo#6489]
- [x] Successful build on Linux, Windows, MacOS
- [x] Activate on pull requests, not just commits
- [x] Do not trigger an action on documentation changes
- [x] Build multiple python versions on Windows
- [x] Linux: gcc, clang compiler and cmake-minimal build
- [x] Add badges to Readme
- [x] Disable travis build
- [x] How to download generated artifacts?
- [x] Enable tags fetching for Linux and OSX (based on Windows template)
- [x] Eclipse-conform minimal build for Windows
- [ ] Windows SUMO binary artifacts upload only for most recent python version
- [x] Build Google Tests during windows build and execute SUMO gtests during Windows build
- [x] Enable TRaaS build on Windows
- [ ] Documentation build on all platforms - only if commits on doc path
- [ ] Migrate nightly tests to GitHub Actions
- [ ] GUI Testing on Windows possible? Netedit tests on Windows 2019?

**Comment by schwamborn** [comment]
I'd be in favor of still keeping the macOS formula and bottle building separate from eclipse/sumo CI infrastructure. A new sumo release still requires some manual testing on the dlr-ts/homebrew-sumo side before updated bottles can be built.

**Comment by RobertHilbrich** [comment]
> 
> I'd be in favor of still keeping the macOS formula and bottle building separate from eclipse/sumo CI infrastructure. A new sumo release still requires some manual testing on the dlr-ts/homebrew-sumo side before updated bottles can be built.

Alright - I removed the brew cask building from the list of action items.

**Comment by RobertHilbrich** [comment]
GitHub Actions are now well in use and changes are tracked in #3
