### ISSUE TITLE
Peter Wagner CF followSpeed method uses dawdling 

### ISSUE THREAD

**Issue by MaxVanDeursen** [eclipse-sumo/sumo#6557]
Although the [documentation of the `followSpeed` method](https://github.com/eclipse/sumo/blob/3ee22d763ebde82ce5f965e4e0b2fc5327251bde/src/microsim/cfmodels/MSCFModel_PWag2009.h#L60) mentions that this method should not include dawdling, the [implementation (line 75)](https://github.com/eclipse/sumo/blob/3ee22d763ebde82ce5f965e4e0b2fc5327251bde/src/microsim/cfmodels/MSCFModel_PWag2009.cpp#L75) seems to suggest otherwise.

If I interpret this code correctly, this would in turn mean that for this car following model, dawdling is applied twice when computing the following speed.

EDIT: I have noticed that the [`dawdle` method](https://github.com/eclipse/sumo/blob/3ee22d763ebde82ce5f965e4e0b2fc5327251bde/src/microsim/cfmodels/MSCFModel_PWag2009.cpp#L104) does in fact not do anything but return the passed speed. Is this done on purpose? I would think that it seems more logical to instead move the dawdling to this method

**Comment by namdre** [comment]
the dawdling in this model is a bit special and this is probably why the original author put it there. I'll try to refactor it when I find the time.
Also, the model is very experimental:
 - it's not being thorougly tested
 - it's known to cause collisions in one of our test
