### ISSUE TITLE
TraCI and libsumo: different keyword arguments

### ISSUE THREAD

**Issue by obrusvit** [eclipse-sumo/sumo#6918]
Hi, I'm trying to use libsumo instead of traci for faster simulations. So far, I encountered three inconsistencies.

Consider:
```
import traci
traci.route.add(routeID='my_rou', edges = ["DEP2A4","A4B4"])
traci.vehicle.add(vehID = vehID, typeID = 'MY_CAR', routeID = initRouID, personCapacity=1)
traci.vehicle.setParameter(myVeh, param="my_generic", value="state1")
traci.vehicle.getParameter(myVeh, param="my_generic")
```

If using libsumo this must change to:
```
import libsumo as traci
traci.route.add(routeID='my_rou', edgeIDs = ["DEP2A4","A4B4"])  # edges -> edgeIDs
traci.vehicle.add(vehicleID = vehID, typeID = 'MY_CAR', routeID = initRouID, personCapacity=1)  # vehID -> vehicleID
traci.vehicle.setParameter(myVeh, key="my_generic", value="state1")  # param -> key
traci.vehicle.getParameter(myVeh, key="my_generic")  # param -> key
```

Is the libsumo API intended to be completely the same as python client or should I deal with it?
Thank you very much.

**Comment by behrisch** [comment]
sometimes it is better to change the name in traci than in libsumo but we should consider providing aliases: https://stackoverflow.com/questions/41784308/keyword-arguments-aliases-in-python
