### ISSUE TITLE
check usage of cfModel.brakeGap() (trac #780)

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#780]
we frequently compute the lookahead distance for safety computations like this:

  dist = cfModel.brakeGap(speed)

However, we currently flag collisions whenever vehicles get within minGap distance. Therefore, the lookahead should be computed as

  dist = cfModel.brakeGap(speed) + vehicle->getVehicleType().getMinGap()

in most cases.

Migrated from http://sumo.dlr.de/ticket/780
```json
{
    "status": "new", 
    "changetime": "2013-09-10T09:24:50Z", 
    "description": "we frequently compute the lookahead distance for safety computations like this:\n\n  dist = cfModel.brakeGap(speed)\n\nHowever, we currently flag collisions whenever vehicles get within minGap distance. Therefore, the lookahead should be computed as\n\n  dist = cfModel.brakeGap(speed) + vehicle->getVehicleType().getMinGap()\n\nin most cases.", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1378805090384370", 
    "component": "microsim - car following", 
    "summary": "check usage of cfModel.brakeGap()", 
    "priority": "major", 
    "keywords": "", 
    "time": "2012-11-09T15:54:01Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by behrisch** [comment]
I did a short look and already the first occurrence in MSLane::lastInsertion looked spurious, so this seems to be still a valid point although the mingap is already included in several places.

**Comment by namdre** [comment]
for lastInsertion, the brakeGap includes tau which typically makes it safe. Testing with a contrived example and short headway reveals the subsequent call to isInsertionSuccess removes any safety issues.

I suspect that there are similar compensations in other places (at least I'm not aware of any collisions caused by this. I vote for closing.
