### ISSUE TITLE
create maven repo or publish to existing one

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#7921]
All the jars should be available via maven, maybe using [Github packages](https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-apache-maven-for-use-with-github-packages) or [Eclipse infrastructure](https://wiki.eclipse.org/Jenkins#How_can_artifacts_be_deployed_to_Nexus_OSS_.28repo.eclipse.org.29.3F)

**Comment by RobertHilbrich** [comment]
I think, we should go with GitHub packages, since the Eclipse infrastructure seems to be tied pretty closely to the build process there. We should integrate the process with a GitHub Action for each release.

Steps to do:

- [ ] Build a maven artifact out of the existing jar library (see [link](https://dzone.com/articles/creating-maven-artifacts-from-a-jar-file))
- [ ] Extend the pom.xml file with information about GitHub Package registry
- [ ] Test locally and make sure, that we are able to delete packages too
- [ ] Create a GitHub Action (see [link](https://docs.github.com/en/free-pro-team@latest/packages/guides/configuring-apache-maven-for-use-with-github-packages))

**Comment by RobertHilbrich** [comment]
With a proper local version of a ```settings.xml``` in the ```~/.m2```folder, the ```mvn deploy``` command in the build directory of libsumo and libtraci leads to a successful upload of the artifacts to the Github Package Registry. 
Unfortunately, existing packages and their assets cannot be deleted, so repeated uploads of the same version result in multiple assets of the same version.
All left to do is to have a GitHub action script reacting on tagged builds, which does a ```mvn deploy``` in the libsumo and libtraci build folders to upload the proper package versions.

**Comment by RobertHilbrich** [comment]
Action is now updated to contain the upload; we need to make sure, that:
- [ ] the full build in Linux also includes the ```JAVA_BINDINGS``` so that the ```pom.xml``` files exist after a successful build
- [ ] we have meaningful descriptions for the packages in the GitHub Package website

**Comment by behrisch** [comment]
nightly build still fails with missing authorization

**Comment by RobertHilbrich** [comment]
> nightly build still fails with missing authorization

Scheduled build on GitHub via cron definition or nightly build on our internal servers?

**Comment by RobertHilbrich** [comment]
Hm ... seems the scheduled builds via GitHub actions seem to be unable to access the secret GitHub token for authorization. Not sure how to debug this. Maybe a glitch at GitHub?
For the moment, I re-enabled the upload for tagged commits only. Scheduled builds are not tagged commits, so this may fix this issue for the time being...

**Comment by kschrab** [comment]
I'm a bit unsure if the solution with GitHub packages is the best option though. It currently requires everyone who wants to grab the dependency to setup an API token and therefore needs a GitHub account. So if add `libsumo` as a dependency to MOSAIC, it would mean that everyone who wants to build MOSAIC would need to setup this API token too. Or did I miss something? Currently it is very simple to build MOSAIC, just clone and hit `mvn install`.

**Comment by behrisch** [comment]
I just read [this thread ](https://github.community/t/download-from-github-package-registry-without-authentication/14407) and it seems you are completely right. You need a token to use the package. I did not know that and that restriction makes the github packages indeed quite useless. Does Eclipse itself host a public maven repo? I could not find one.

**Comment by kschrab** [comment]
You can request an own public maven repo for each project, by opening a bug report (e.g. [like we did](https://bugs.eclipse.org/bugs/show_bug.cgi?id=565277)). We use their Jenkins instance to deploy the jar to the maven repo, just [like they described here](https://wiki.eclipse.org/Jenkins#How_can_artifacts_be_deployed_to_Nexus_OSS_.28repo.eclipse.org.29.3F). But that would require you to build SUMO on that Jenkins too, right? I'm not sure if there's a way to deploy Jars without using that Jenkins instance.
A nasty hack could be that you deploy your jars to github packages, and a Jenkins job would grab those and re-deploy them to the Eclipse repo.. 🤓

**Comment by RobertHilbrich** [comment]
Damn ... who would have thought ... I will look into the matter and get back to you.

**Comment by RobertHilbrich** [comment]
Created [bug 572104](https://bugs.eclipse.org/bugs/show_bug.cgi?id=572104) for the nexus repo for SUMO.

**Comment by kschrab** [comment]
As far as I know, you could also publish directly to Maven Central using the OSSRH repository. You'd need to apply for a namespace though (https://central.sonatype.org/pages/ossrh-guide.html) and you'd need to sign your artifacts using PGP. There's also GitHub action tutorial which show how to publish to OSSRH (https://docs.github.com/en/actions/guides/publishing-java-packages-with-maven#publishing-packages-to-the-maven-central-repository). Hope that helps somehow :)

**Comment by RobertHilbrich** [comment]
@kschrab: I was able to have a running SUMO build on Eclipse CI infrastructure. Do you know:
1. How to sign the jars?
2. How to configure the poms to upload to repo.eclipse.org?

**Comment by kschrab** [comment]
1. I don't know how to sign jars. However, for the eclipse repo you do not need to sign your jar. We do not sign our jars either. 
2. you need to add the following snippet to the pom.xml of libsumo and libtraci:

```xml
 <distributionManagement>
        <repository>
            <id>repo.eclipse.org</id>
            <name>Project Repository - Releases</name>
            <url>https://repo.eclipse.org/content/repositories/sumo-releases/</url>
        </repository>
        <snapshotRepository>
            <id>repo.eclipse.org</id>
            <name>Project Repository - Snapshots</name>
            <url>https://repo.eclipse.org/content/repositories/sumo-snapshots/</url>
        </snapshotRepository>
</distributionManagement>
```

Fingers crossed that the ubuntu-container recognizes the `.m2/settings.xml` (that's where the credentials are stored). If that not works, you better ask eclipse team for help again.

**Comment by RobertHilbrich** [comment]
Ok - the build succeeded. See [here](https://repo.eclipse.org/#view-repositories;sumo~browsestorage). Could you check, if you can make use of the jars now?

Open action items:
- [ ] check jars for usability
- [ ] apply for an Eclipse SUMO account on dockerhub
- [ ] execute CI build on Jenkins on a regular basis
- [ ] improve performance of Jenkins build via `make -j4`

**Comment by kschrab** [comment]
The version is not correct yet (this should be `1.9.0-SNAPSHOT` right now, but is `79b067bf`):

![image](https://user-images.githubusercontent.com/2386865/112987430-01a03b00-9163-11eb-8a33-64a27b53a970.png)

apart from that the jar's can be loaded and my code compiles so far

**Comment by RobertHilbrich** [comment]
Sorry, it took me a while, but now with 1.9.0-SNAPSHOT it seems to be ok. @kschrab please test again ...

<img width="1044" alt="Bildschirmfoto 2021-04-15 um 22 25 36" src="https://user-images.githubusercontent.com/1360688/114934006-a5fbd000-9e39-11eb-88a9-36061c6bbd7e.png">

**Comment by kschrab** [comment]
Ah, I wrote that before the release ;) In the world of maven you usually add the `-SNAPSHOT` suffix for a development version of the next planned release, thus you _now_ would use `1.10.0-SNAPSHOT`. And also users would expect release versions for each release, such as `1.9.0` (which is too late for now).

**Comment by RobertHilbrich** [comment]
Wow - semantics are tricky. I think, we fixed the issues. So, we should be okay for the future. Key thing is, we override the SUMO versioning according to the following schema:

 - SUMO: 1.9.0                 --> MAVEN: 1.9.0  (release)
 - SUMO: 1.9.1                  --> MAVEN: 1.9.1  (release)
 - SUMO: 1.9.0.post18    --> MAVEN: 1.10.0-SNAPSHOT
 - SUMO: 1.9.1.post23    --> MAVEN: 1.10.0-SNAPSHOT

It ain't perfect for patch-level releases, but I think that is the best we can do. @kschrab Do you think, that should be okay?

**Comment by kschrab** [comment]
This looks indeed quite nice!

We also set our snapshot version to the next _planned_ release (ignoring any potential bugfix releases), and it fact it is really not that important as long as the release versions are fix and snapshot version are higher than the latest release version. So everything is fine I guess.

 Thanks for that 🤩

**Comment by kschrab** [comment]
Btw. I just saw that your build pipeline in Jenkins is kinda broken. There are several build running in parallel and the first one seems to have frozen:

![image](https://user-images.githubusercontent.com/2386865/115837853-53ae4680-a419-11eb-97f2-7fe8f12d1e46.png)

**Comment by RobertHilbrich** [comment]
Oh I am glad ... so I will *finally* close this issue and hope that everything works as expected for the next releases to come ... let me know, if anything does not work as expected ... You're welcome - glad to be of service :)

**Comment by kschrab** [comment]
Hi @RobertHilbrich. Sorry to bother you again with this topic, but there were no JAR files deployed with your latest release 🧐

The latest deployment of a SNAPSHOT was in august:
https://repo.eclipse.org/content/repositories/sumo/org/eclipse/sumo/libsumo/

**Comment by RobertHilbrich** [comment]
Sorry for answering a bit late. I think, the Eclipse CI build needed a reconfiguration after we switched from the branch name "master" to "main". I did a full reconfiguration at ci.eclipse.org and triggered a rebuild. I think it should work now ... Sorry for the delay!

**Comment by RobertHilbrich** [comment]
Yup - seems fixed to me: [https://repo.eclipse.org/content/repositories/sumo/org/eclipse/sumo/libsumo/1.12.0-SNAPSHOT/](https://repo.eclipse.org/content/repositories/sumo/org/eclipse/sumo/libsumo/1.12.0-SNAPSHOT/)

**Comment by kschrab** [comment]
The jars for the recent release 1.12.0 were not pushed to the maven repo (or they are incorrectly tagged with 1.13.0-SNAPSHOT)

**Comment by RobertHilbrich** [comment]
Hm - seems we may have exceeded some quota on the Eclipse infrastructure: 
```
...
WARNING: Unable to create pod: kubernetes sumo/my-agent-pod-458qk-4kg2v because kubernetes resource quota exceeded. 
Failure executing: POST at: https://10.30.0.1/api/v1/namespaces/sumo/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "my-agent-pod-458qk-4kg2v" is forbidden: exceeded quota: jenkins-instance-quota, requested: requests.cpu=1500m, used: requests.cpu=1750m, limited: requests.cpu=2650m.
Retrying...
...
```
I will open a ticket for the infra team at Eclipse and try to get things sorted out. Sorry for the mess.

**Comment by RobertHilbrich** [comment]
See: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/812

**Comment by RobertHilbrich** [comment]
Weird the ci build 511 for the latest release did not upload a RELEASE, but a SNAPSHOT instead. 
See: https://ci.eclipse.org/sumo/job/sumo-build/job/main/511/console

**Comment by behrisch** [comment]
We should probably move to a nightly build instead of building on every push. This will also solve the problem of not picking up the tag.

**Comment by RobertHilbrich** [comment]
After opening an issue with the Eclipse Foundation [issue 1413](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1413), I was able to configure Jenkins to "discover tags" (see below). Support believes, that it should work now. I guess, we will see with the next release. 

(Or @behrisch: could you force push the old tags of the latest release again?)


![](https://gitlab.eclipse.org/eclipsefdn/helpdesk/uploads/dc7dc06d0fdff202a11d8448dbf2cc13/image.png)

**Comment by behrisch** [comment]
I do not have more rights here than you and `git push --tags --force` says "Everything up to date". So probably no.

**Comment by RobertHilbrich** [comment]
I was not sure, what could happen on our end, if we were to update the tags ... So, we have to wait for the next release and hope for the best?

**Comment by kschrab** [comment]
Have you tried clicking on "Scan repository now"?
![image](https://user-images.githubusercontent.com/2386865/174017179-24af0c35-b783-442e-9e2d-cabb56db569e.png)

**Comment by kschrab** [comment]
Also, maybe your include filter prevents the tags from being discovered.. you may add a wildcard, e.g. `main v1_*`

![image](https://user-images.githubusercontent.com/2386865/174017653-0dc5b6d6-73c4-4cca-8ea0-6881c5e166de.png)

**Comment by kschrab** [comment]
Hi again, I just noticed that the jars for the recent release 1.15.0 were not pushed to the maven repo in https://repo.eclipse.org/content/repositories/sumo-releases/org/eclipse/sumo

**Comment by behrisch** [comment]
apparently also 1.14.1 did not show up

**Comment by RobertHilbrich** [comment]
Another try with the Jenkins build - now with two separate builds for snapshots and releases. I triggered the releases build manually for 1.14.1 and 1.15.0 and it seems to have worked. @kschrab: please check.

**Comment by behrisch** [comment]
I hate to say this but it did not work automatically. I needed to trigger the 1.16.0 build manually

**Comment by RobertHilbrich** [comment]
Nope, the artifacts have been built and uploaded. 

See: 
- https://repo.eclipse.org/content/repositories/sumo-releases/org/eclipse/sumo/libtraci/1.16.0/
- https://repo.eclipse.org/content/repositories/sumo-releases/org/eclipse/sumo/libsumo/1.16.0/

**Comment by kschrab** [comment]
Thanks for the new release! 🥳 As a reminder, 1.17.0 jar files are not yet available in the eclipse repo

https://repo.eclipse.org/content/repositories/sumo-releases/org/eclipse/sumo/libsumo/

**Comment by RobertHilbrich** [comment]
Sigh ... thanks for reporting.
The build queue at ci.eclipse.org/sumo seems stuck. Opened a ticket: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3058

**Comment by RobertHilbrich** [comment]
Maybe we should move to GitHub Actions instead - with a published token for easy access.

**Comment by kschrab** [comment]
> Okay - it took a while, but the artifacts have now been build. Also the Jenkins CI build should now run only once per day for the snapshot builds, so for 1.18.0 everything should be done automagically ... lets keep our fingers crossed.

You did not cross your fingers strong enough 🫣 the jars for 1.18.0 are missing in the release repo.

there actually is 1.19.0-SNAPSHOT in the snapshot repo, so your automagic seems to work. maybe your daily run just missed out the 1.18.0 tag due to bad timing?

**Comment by behrisch** [comment]
Thanks Karl for reporting (again). I think we will ditch the Eclipse workflow and publish here on github. We will create a "public" download token for that

**Comment by RobertHilbrich** [comment]
I triggered the maven release ci job manually and after about 1hr it seems to have produced the proper artifacts https://repo.eclipse.org/content/repositories/sumo-releases/org/eclipse/sumo/.

We will still continue to look into the the public token approach as mentioned by @behrisch.

**Comment by kschrab** [comment]
I'm not sure anymore how this was resolved. Is there a new place for the release jars already? Currently 1.20.0 is missing again in [the eclipse-repo](https://repo.eclipse.org/content/repositories/sumo-releases/org/eclipse/sumo/libsumo/).

Thanks for the new release though 🚀

**Comment by kschrab** [comment]
@RobertHilbrich @behrisch have you seen my previous comment?

**Comment by RobertHilbrich** [comment]
It seems like a never ending story. We triggered the build process at ci.eclipse.org manually, it re-discovered all tags and finally started to build the 1.20.0 release as well - in addition to the snapshots. Thanks @kschrab for reporting. We will keep an eye on this issue and investigate the alternative of moving this to GitHub.

**Comment by kschrab** [comment]
Happy release day! 🥳 Here I am again to annoy you with missing maven artifacts ;)

**Comment by RobertHilbrich** [comment]
Hi Karl, I think the maven artifacts where created successfully, but the Eclipse CI build was a bit late (24h)...
