### ISSUE TITLE
can't subscribe pedestrian information

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse-sumo/sumo#8609]
Hello, I generate random pedestrians through random.Trips, but I can't subscribe pedestrian information through getContextSubscriptionResults. At the same time, the .add file can't guarantee pedestrians to drive according to the routing cycle.

**Comment by namdre** [comment]
> the .add file can't guarantee pedestrians to drive according to the routing cycle.

- In what way to you expect pedestrians to "drive"? I would expect them to walk
- what are you doing with an .add file?
- what do you mean by a "routing cycle"?

**Comment by Jianhua-Jiang** [comment]
> > the .add file can't guarantee pedestrians to drive according to the routing cycle.
> 
> * In what way to you expect pedestrians to "drive"? I would expect them to walk
> * what are you doing with an .add file?
> * what do you mean by a "routing cycle"?

Pedestrian “drive” just like this.
<person id="00" depart="0.00">
    <walk edges="a1toa2 a2toa3 a3toa4 a4toa1"/>
</person>

.add file is defined as rerouter.

I mean that person don't walk cycle with above rou.xml and add.xml.

And, I can't get informations of person with traci.person.getContextSubscriptionResults.

THANKS!

**Comment by namdre** [comment]
rerouters currently do not work for pedestrians (#1722) 
If you need persons that walk in a circle, define a route that repeats many times:

```
    <route edges="a b c" color="yellow" repeat="5" id="route_0"/>
    <person id="person_0" depart="0.00">
        <walk route="route_0"/>
    </person>
```

If you need persons that keep walking in random loops around the network, use randomTrips option **--intermediate INT**.



contextSubscriptionResults are only available after a previous call to person.subscribeContext. They are working fine in our tests.

**Comment by Jianhua-Jiang** [comment]
> rerouters currently do not work for pedestrians (#1722)
> If you need persons that walk in a circle, define a route that repeats many times:
> 
> ```
>     <route edges="a b c" color="yellow" repeat="5" id="route_0"/>
>     <person id="person_0" depart="0.00">
>         <walk route="route_0"/>
>     </person>
> ```
> 
> If you need persons that keep walking in random loops around the network, use randomTrips option **--intermediate INT**.
> 
> contextSubscriptionResults are only available after a previous call to person.subscribeContext. They are working fine in our tests.

Thanks! I try it. But when I run these code I also received an error.

        traci.junction.subscribeContext(
            objectID='a4', domain=traci.constants.CMD_GET_PERSON_VARIABLE,
            dist=10000.0, varIDs=[traci.constants.VAR_POSITION,
                                                traci.constants.VAR_LENGTH,
                                                traci.constants.VAR_WIDTH,
                                                traci.constants.VAR_ANGLE,
                                                traci.constants.VAR_SIGNALS,
                                                traci.constants.VAR_SPEED,
                                                traci.constants.VAR_EDGES
                                                ],
            begin=0.0, end=2147483647.0)

Error: Answered with error to command 0xae: Get Person Variable: unsupported variable 0x5b specified
Error: Storage::readChar(): invalid position

**Comment by namdre** [comment]
when you run junction.subscribeContext, you also have to call junction.getContextSubscriptionResults to retrieve those results. (and it will then contain the persons)

**Comment by Domsall** [comment]
0x5b is the variable VAR_SIGNALS and can only be retrieved from vehicles and not persons.
https://sumo.dlr.de/docs/TraCI/Vehicle_Signalling.html

**Comment by Jianhua-Jiang** [comment]
> 0x5b is the variable VAR_SIGNALS and can only be retrieved from vehicles and not persons.
> https://sumo.dlr.de/docs/TraCI/Vehicle_Signalling.html

THANKS!!! How can I get the complete edges information of pedestrians? 

When I use “traci.constants.VAR_EDGES”, I will report the following error.
Error: Storage::readChar(): invalid position

**Comment by Domsall** [comment]
What do you mean with edges information? A few examples:
- VAR_ROAD_ID: Edge-ID of current Edge
- VAR_LANEPOSITION: lane position on current edge
- VAR_ROUTE_ID: Route-ID of the person/vehicle (not sure if this works correct with pedestrians)

For results that don't change in every step, you could use get-Commands. E.g. to get the edges from a route you would call something like traci.route.getEdges(<RouteID>) after getting the Route-ID via subscription or traci.person.getRouteID(<personX>).

**Comment by Jianhua-Jiang** [comment]
> What do you mean with edges information? A few examples:
> 
> * VAR_ROAD_ID: Edge-ID of current Edge
> * VAR_LANEPOSITION: lane position on current edge
> * VAR_ROUTE_ID: Route-ID of the person/vehicle (not sure if this works correct with pedestrians)
> 
> For results that don't change in every step, you could use get-Commands. E.g. to get the edges from a route you would call something like traci.route.getEdges() after getting the Route-ID via subscription or traci.person.getRouteID().

Thanks! In fact, I need to get the completed route of pedestrians, just like "edge_1 egde_2 edge_3 edge_4". But "VAR_ROUTE_ID" don't works correct with pedestrians.

**Comment by Jianhua-Jiang** [comment]
> For person stages it gets a bit trickier, because a person can have different stages. But it should be possible to get the edges from each stage. See also https://sumo.dlr.de/docs/TraCI/Person_Value_Retrieval.html#extended_retrieval_messages

Thank you very much! I try it.

**Comment by namdre** [comment]
You can call `traci.person.getEdges` but you cannot currently subscribe to this directly. However, you can simply subscribe to all person ids in an area and then retrieve the edges based on the person id.
