### ISSUE TITLE
How to prohibit vehicles from changing lanes at intersections

### ISSUE THREAD

**Issue by MAD-dee** [eclipse-sumo/sumo#8968]
When we do the simulation, we found that when the vehicle stopped at the intersection, the following vehicle will change lane by lateral moving like Left and right traverse. **So, if we can set some parameters to prohibit vehicles from changing lanes at intersections!!!**

**Comment by namdre** [comment]
Can you attach a small example simulation that demonstrates your problem?

**Comment by MAD-dee** [comment]
<img width="953" alt="06c8ece2ec42445209aa54747426738" src="https://user-images.githubusercontent.com/77570850/130013581-7054f673-19bd-48dc-89ad-a6df5f6cbf02.png">
<img width="953" alt="f2e4e720c6bcb231028a015a4a59d14" src="https://user-images.githubusercontent.com/77570850/130013589-7d8b5be7-ed85-4b4d-8bf7-5047bed8028a.png">
Like the yellow car and the green truck. They will change lane by lateral moving. So, it looks unreal. if we can set some parameters to prohibit vehicles from changing lanes at intersections.

**Comment by MAD-dee** [comment]
So, what can i do to slove this

**Comment by namdre** [comment]
you can set attribute 'lcMaxSpeedLatStanding="0"` in the vType.

**Comment by namdre** [comment]
The above advice suffers from problems explained in #3392 and may not achieve your goal at this time. You can also limit the amount of unwanted changing be setting the values of 'lcSpeedGain' and 'lcKeepRight' below their default of 1.
