### ISSUE TITLE
How to configure CMakeList.txt to use libtraci to control a vehicle in sumo-gui

### ISSUE THREAD

**Issue by HuaweiAlgolux** [eclipse-sumo/sumo#9279]
Hi. I'm trying to write a c++ program to control the behavior of an ego vehicle at an intersection (e.g. when to wait for other cars to go first at the intersection, when to proceed) in sumo-gui via its c++ interface - libtraci. However, I'm super confused about how to configure my CMakeList.txt. Here is my CMakeList.txt.

```
cmake_minimum_required(VERSION 3.10)
project(btcpp_sumo)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Bring the headers into the project
include_directories(include)
include_directories(bt_nodes)
include_directories(../sumo/src)

# Add the source files, i.e. define SOURCES
set(SOURCES src/main.cpp
            bt_nodes/crossdoor_nodes.cpp
            bt_nodes/dummy_nodes.cpp
            bt_nodes/movebase_node.cpp)

######################
# BehaviorTreeV3
list(APPEND CMAKE_PREFIX_PATH "bt_nodes")
find_package(BehaviorTreeV3 REQUIRED PATHS /usr/local/lib)


######################
#SUMO and libtraci
find_package(sumo REQUIRED PATHS ../sumo/bin/libsumocpp)


# target
add_executable(${PROJECT_NAME} ${SOURCES})
target_link_libraries(${PROJECT_NAME} BT::behaviortree_cpp_v3 SUMO::libsumocpp)

```

And I got the following error:
```
CMake Error at CMakeLists.txt:23 (find_package):
  Could not find a package configuration file provided by "sumo" with any of
  the following names:

    sumoConfig.cmake
    sumo-config.cmake

  Add the installation prefix of "sumo" to CMAKE_PREFIX_PATH or set
  "sumo_DIR" to a directory containing one of the above files.  If "sumo"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/huawei.zhu/btcpp-sumo/build/CMakeFiles/CMakeOutput.log".
```
Can you point out what I did wrong? If it's possible, can you show me the correct way?
Especially, can you point out if the following lines related to SUMO are correct in my CMakeList.txt
`include_directories(../sumo/src)`
`  find_package(sumo REQUIRED PATHS ../sumo/bin/libsumocpp)`
`target_link_libraries(${PROJECT_NAME} BT::behaviortree_cpp_v3 SUMO::libsumocpp)`

Should I use `libsumocpp` in the `find_package` and `target_link_libraries` commands? or I should use `libtracicpp` or `_libtraci` or `_libsumo`? What's the difference between them? 
---
*If possible, upload an example that shows your problem.*

**SUMO-version:** 1.10

**operating system:** Ubuntu 18.04

**Comment by HuaweiAlgolux** [comment]
Below is my updated CMakeList.txt. I can successfully build my program with it. But I have the following error when run the generated executable. And have no clue how to fix it.
```
cmake_minimum_required(VERSION 3.10)
project(btcpp_sumo)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Bring the headers into the project
include_directories(include)
include_directories(bt_nodes)
include_directories(../sumo/src)
link_directories(../sumo/bin)

# Add the source files, i.e. define SOURCES
set(SOURCES src/main.cpp
            bt_nodes/crossdoor_nodes.cpp
            bt_nodes/dummy_nodes.cpp
            bt_nodes/movebase_node.cpp)


####### BehaviorTreeV3 #######
find_package(BehaviorTreeV3 REQUIRED PATHS /usr/local/lib)

# Define the target
add_executable(${PROJECT_NAME} ${SOURCES})
target_link_libraries(${PROJECT_NAME} BT::behaviortree_cpp_v3 tracicpp)
```
The error is as follows:
```
Testing the sumo and traci
Could not connect to TraCI server at localhost:32795 tcpip::Socket::connect() @ connect: Connection refused
 Retrying in 1 second
terminate called after throwing an instance of 'tcpip::SocketException'
  what():  tcpip::Socket::recvAndCheck @ recv: Connection reset by peer
Aborted (core dumped)
```

**Comment by HuaweiAlgolux** [comment]
I did the following:
`./sumo-gui -n ~/btcpp-sumo/map/test_track/track.net.xml --remote-port 9999`

And then replace the 
`Simulation::start({"../../sumo/bin/sumo-gui", "-c", "../map/nordelec/nordelec.sumocfg"})`
with 
`Simulation::init(9999)`
I can see that `Error: Invalid network. No network version decleared.` is gone in sumo-gui. But my program is not proceeding after the `Simulation::init(9999)`. The code after `Simulation::init(9999)` is as the following.
```
	for (int i = 0; i < 5; i++) {
		Simulation::step();
		std::cout << "i = " << i << std::endl;
	}
	Simulation::close();
```
Nothing prints out. Can you tell me what should I do next to debug.

**Comment by behrisch** [comment]
Are there any messages in the sumo-gui window? Does it report that it is listening for connections?

**Comment by behrisch** [comment]
Closing for lack of feedback. Please add another comment if you have more information

**Comment by UTTUBALIYAN** [comment]
I also want to use the gui c++ in libtraci in my sumo eclipse existing source code only ,so how can i do that because if I am adding the header file of libtraci then linker error is coming how should I configure my Cmakelists.txt can anyone help me for this please

**Comment by behrisch** [comment]
@UTTUBALIYAN Please open rather new issues than replying to closed ones
