### ISSUE TITLE
warn about dangerous parking rerouter input

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#9363]

**Comment by behrisch** [comment]
A problem I observed in this context is two vehicles being redirect to the same location which has only one empty space and the new location has no rerouter of its own.

**Comment by namdre** [comment]
This was exactly the problem. Rerouter edge definitions were wrong.

**Comment by namdre** [comment]
I think there should be a warning if any parkingArea is targeted by a rerouter and doesn't have a parkingRerouter on its own edge.
