### ISSUE TITLE
netconvert  osm Error: No nodes loaded

### ISSUE THREAD

**Issue by zhangqi1008** [eclipse-sumo/sumo#9391]
Add your issue description here.
 Hi，
     When we use the following osm file for netconvert and use the following command：
    “netconvert.exe --osm-files wuhanqingnianlushp.osm -o processed.net.xml --junctions.join --edges.join true --geometry.remove true --osm.elevation true --output.street-names --numerical-ids.edge-start 1 --numerical-ids.node-start 1”

 , it displays Error: No nodes loaded. Why does this happen?
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:*
[wuhanqingnianlushp.zip](https://github.com/eclipse/sumo/files/7415632/wuhanqingnianlushp.zip)
*

**Comment by namdre** [comment]
@osakanatengoku-AS193

> Also, is there a page that describes the highway key?

https://wiki.openstreetmap.org/wiki/Key:highway

**Comment by osakanatengoku-AS193** [comment]
Thank you very much.
I understand a little now.
I will read a little more.
