### ISSUE TITLE
improve default efficiency of chargingStation

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#9414]
efficiency is 0 by default which doesn't seem very useful.

@palvarezlopez @behrisch anyone opposite to changing this to 1 instead?

**Comment by behrisch** [comment]
I feel a little bit ignored ;-) Why not deprecate it? Is there really a usecase?

**Comment by namdre** [comment]
Sorry. I just did the simplest thing to solve the problem. 

I can only guess at why Tamasz et al. added both attributes and my guess is that the power rating is something that is given in the actual specs of installed chargers and that efficiency was added to make use of those specs while accounting for physical reality.

**Comment by namdre** [comment]
If you don't have efficiency, people are left to wonder: is power the rated power or the actual charging power?

**Comment by palvarezlopez** [comment]
There are a user case: Charging depends of certain factors (Temperature, inductor construction , etc.). With the efficiency this factors can be modeled.

**Comment by namdre** [comment]
I guess you would need this if a connected simulation wants to track the power draw of the charging station. When looking from the point of view of the battery only the product of of power and efficiency matters.

**Comment by behrisch** [comment]
Exactly but I think none of our outputs / APIs delivers this value, that's why I think it is pointless.

**Comment by namdre** [comment]
What about my point above about real-world specs of these things? My gut feeling is to rather add method traci.chargingStation.getPower().

**Comment by behrisch** [comment]
I am not sure about the real world specs. You probably still need to guess the efficiency. But yes, maybe opening it up by having getters and setters for both values is the best way to go. This way you can add the value from the specs and modify the efficiency dynamically or the other way round. More power to the user.
