### ISSUE TITLE
SUMO  [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by zaheenSyed** [eclipse-sumo/sumo#9722]
I am trying to run veins module but getting this error (Shown below). Somehow the code works with other sumo.cfg file but when to load my model it does not work

Also I have tried running the line below separately and it works
> C:/Users/za696465/Documents/sumo-1.8.0/bin/sumo.exe -c I75_121_Final.sumocfg

Error
----------------------------------------------------------------------------------------------------------------
/c/Users/za696465/Documents/omnetpp-5.6.2$ C:/Users/za696465/Documents/veins-5.1/bin/veins_launchd -vv -c C:/Users/za696465/Documents/sumo-1.8.0/bin/sumo.exe
Logging to C:/Users/za696465/AppData/Local/Temp/sumo-launchd.log
Listening on port 9999
Connection from 127.0.0.1 on port 53604
Handling connection from 127.0.0.1 on port 53604
Got TraCI message of length 2
Got TraCI command of length 1
Got TraCI command 0x0
Got CMD_GETVERSION
Got TraCI message of length 394
Got TraCI command of length 389
Got TraCI command 0x75
Got CMD_FILE_SEND for "b'sumo-launchd.launch.xml'"
Got CMD_FILE_SEND with data "b'<launch>\n  <copy file="i75_121_zz.net.xml"/>\n  <copy file="I75_121.rou.xml"/>\n  <copy file="I75_121_router.add.xml"/>\n  <copy file="I75_121_loop.add.xml"/>\n  <copy file="data.add.xml"/>\n  <copy file="I75_121_Final.sumocfg" type="config"/>\n  <basedir path="C:/Users/za696465/Documents/veins_i75/veins_i75/examples/veins_i75/"/>\n  <seed value="0"/>\n</launch>\n'"
Creating temporary directory...
Temporary dir is C:/Users/za696465/AppData/Local/Temp/sumo-launchd-tmp-fd2rc4u5
Base dir is C:/Users/za696465/Documents/veins_i75/veins_i75/examples/veins_i75/
Seed is 0
Finding free port number...
Claiming lock on port
...found port 53605
Starting SUMO (C:/Users/za696465/Documents/sumo-1.8.0/bin/sumo.exe -c I75_121_Final.sumocfg) on port 53605, seed 0
Connecting to SUMO (C:/Users/za696465/Documents/sumo-1.8.0/bin/sumo.exe -c I75_121_Final.sumocfg) on port 53605 (try 1)
Error ([WinError 10061] No connection could be made because the target machine actively refused it)
Connecting to SUMO (C:/Users/za696465/Documents/sumo-1.8.0/bin/sumo.exe -c I75_121_Final.sumocfg) on port 53605 (try 2)
Error ([WinError 10061] No connection could be made because the target machine actively refused it)
Connecting to SUMO (C:/Users/za696465/Documents/sumo-1.8.0/bin/sumo.exe -c I75_121_Final.sumocfg) on port 53605 (try 3)
Error ([WinError 10061] No connection could be made because the target machine actively refused it)
Connecting to SUMO (C:/Users/za696465/Documents/sumo-1.8.0/bin/sumo.exe -c I75_121_Final.sumocfg) on port 53605 (try 4)
Error ([WinError 10061] No connection could be made because the target machine actively refused it)
Connecting to SUMO (C:/Users/za696465/Documents/sumo-1.8.0/bin/sumo.exe -c I75_121_Final.sumocfg) on port 53605 (try 5)
Error ([WinError 10061] No connection could be made because the target machine actively refused it)
Connecting to SUMO (C:/Users/za696465/Documents/sumo-1.8.0/bin/sumo.exe -c I75_121_Final.sumocfg) on port 53605 (try 6)
Error ([WinError 10061] No connection could be made because the target machine actively refused it)
Connecting to SUMO (C:/Users/za696465/Documents/sumo-1.8.0/bin/sumo.exe -c I75_121_Final.sumocfg) on port 53605 (try 7)
Error ([WinError 10061] No connection could be made because the target machine actively refused it)
Connecting to SUMO (C:/Users/za696465/Documents/sumo-1.8.0/bin/sumo.exe -c I75_121_Final.sumocfg) on port 53605 (try 8)
Error ([WinError 10061] No connection could be made because the target machine actively refused it)
Connecting to SUMO (C:/Users/za696465/Documents/sumo-1.8.0/bin/sumo.exe -c I75_121_Final.sumocfg) on port 53605 (try 9)
Error ([WinError 10061] No connection could be made because the target machine actively refused it)
Connecting to SUMO (C:/Users/za696465/Documents/sumo-1.8.0/bin/sumo.exe -c I75_121_Final.sumocfg) on port 53605 (try 10)
Error ([WinError 10061] No connection could be made because the target machine actively refused it)
Releasing lock on port
Cleaning up
Result: "<?xml version="1.0"?>
<status>
        <exit-code>-1</exit-code>
        <start>1638496898</start>
        <end>1638496930</end>
        <status>Could not start SUMO (C:/Users/za696465/Documents/sumo-1.8.0/bin/sumo.exe -c I75_121_Final.sumocfg): [WinError 10061] No connection could be made because the target machine actively refused it</status>
        <stdout><![CDATA[Loading configuration ... done.
]]></stdout>
        <stderr><![CDATA[Error: File 'I75_121_Final.settings.xml' is not accessible (No such file or directory).
Quitting (on error).
]]></stderr>
</status>
"
Closing connection from 127.0.0.1 on port 53604

---

**Comment by behrisch** [comment]
Can you try whether one of the simple traci tutorials works?

**Comment by behrisch** [comment]
closing for lack of feedback
