### ISSUE TITLE
python errors crash libsumo

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#9750]
The simple 
```
import libsumo
libsumo.start()
```
should trigger 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: start() missing 1 required positional argument: 'args'
```
and does so on Windows but on Linux (at least on our compute server) we get:
```
free(): invalid pointer
Aborted (core dumped)
```

**Comment by behrisch** [comment]
seems to be a compute server problem only

**Comment by schwamborn** [comment]
Can confirm I get the first one with the TypeError on Ubuntu 18.04.6.

**Comment by behrisch** [comment]
The error does not occur in a python 3.9 installation and also not in a virtualenv. So it is most likely something in the dist-packages or the site-packages

**Comment by behrisch** [comment]
whatever it was it does not seem to occur any longer, even on the compute server
