### ISSUE TITLE
optionally keep vehicle objects in memory for a configurable time after their arrival

### ISSUE THREAD

**Issue by namdre** [eclipse-sumo/sumo#9891]
- to retrieve properties like arrivalLane and driven distance
- to re-insert them back into the network (i.e. with moveTo or moveToXY)

**Comment by mahima1321** [comment]
In case we do not to use moveTo and want to add new vehicles with the identical parameters, we do need to read arrival lane information. From where else, can we get this information?
Or what is the other way to do this?

**Comment by namdre** [comment]
You could continuously record the lane of each vehicle in your script and look up the last value once the vehicle is listed in
`traci.simulation.getArrivedIDList`.

**Comment by mahima1321** [comment]
Thanks, will try that

**Comment by namdre** [comment]
keeping objects in memory brings a number of complications because the simulations currently has quite a few assumptions around the object life-cycle. An alternative solution would be #9924
